### ISSUE TITLE
error XS9999: An internal compiler error has occurred

### ISSUE THREAD

**Issue by RWooters** [X-Sharp/XSharpPublic#100]
**Describe the bug**
I started removing the Vulcan runtime and replace them with the XSharp runtime from an existing project. 

**Output**
GlobalDefines.vh(127,1): **error XS9999**: An internal compiler error has occurred: 'Object reference not set to an instance of an object.',    at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformation.GenerateInitializer(DatatypeContext datatype) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpTreeTransformation.cs:line 3443

RedX.prg(1,10): warning XS9081: Include file 'VOWin32APILibrary.vh' will be skipped because its values are included in assembly 'vowin32apilibrary.dll'.
RedX.prg(1,1): **error XS9999**: An internal compiler error has occurred: 'Object reference not set to an instance of an object.',    at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformation.GenerateInitializer(DatatypeContext datatype) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpTreeTransformation.cs:line 3443

**Comment by cpyrgas** [comment]
Richard, is it possible to send me (by email) the project that causes this error? Should be able to find what's causing it and give you a quick workaround.

**Comment by RWooters** [comment]
We have an NDS with Robert, I could send it to him first if that's ok?

**Comment by cpyrgas** [comment]
Yes of course! He's just on short vacation right now though, so please allow him some time to respond.

**Comment by RWooters** [comment]
I'm trying to find out if I can get the NDS to cover you.

**Comment by RWooters** [comment]
Ok, Robert signed the NDA for the company so I can send the zip to you. 
Just give me a few to zip it up.

**Comment by cpyrgas** [comment]
Problem is caused by STATIC LOCALs that have no type clause and no inline assignment, the compiler chokes on that:

FUNCTION Test() AS VOID
	STATIC LOCAL n1 := 1// ok
	STATIC LOCAL n2 AS USUAL // ok
	STATIC LOCAL n3 // ICE
	STATIC n4 // ICE
RETURN
