### ISSUE TITLE
Conversion Decimal to float

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1001]
Using the transform function we got an exception in the following code:
```
      local val := 1 as decimal
      local uVal := val as usual
      var test1 := Transform(val, "@R{9999}") // -> no exception
      var test2 := Transform(uVal, "@R{9999}") // -> exception
```
In this case I assume the Picture is wrong. Correct would be "@R {9999}". What is strange though, on the first call the transform works without error (the return is not the expected one because the picture is not accepted). On the second call there is an exception, because in the TransformN function [see code](https://cs.github.com/X-Sharp/XSharpPublic/blob/2061cbbfdb7b861d9564e9bf6f5f279a15fad39a/Runtime/XSharp.RT/Functions/Transform.prg#L563)

![image](https://user-images.githubusercontent.com/20905638/161208045-daee29b0-b61c-4ebd-912d-99ce19c50a5c.png)

Here the problem is `nValue:Decimals < 0` ist. So you get an exception here `System.String{c'9' , nValue:Decimals}`.
The first call of Transform results in the cast of decimal -> float entering 2 for decimals. The 2nd call, where the decimal is passed as usual, results to an float with -1 for decimals

**Comment by cpyrgas** [comment]
Yes, indeed, the VO docs specify that there should be a space between the "function" and the "template" string parts of the picture, so the original picture string is incorrect.

And indeed the sample shows an inconsistency with decimal numbers in conversion from DECIMAL -> USUAL compared to DECIMAL -> FLOAT, will look into ti, thanks. New sample directly demonstrating the problem:

```
FUNCTION Start() AS VOID
LOCAL d AS System.Decimal
LOCAL f AS FLOAT
LOCAL u AS USUAL

f := 123.456
? f:Decimals // 3, OK

u := 123.456
f := u
? f:Decimals // 3, OK

d := 123.456m
f := d
? f:Decimals // 2, OK, using the default SetDecimal() setting

SetDecimal(4)
d := 123.456m
f := d
? f:Decimals // 4, OK

u := d
f := u
? f:Decimals // -1, wrong, should be 4
```
