### ISSUE TITLE
Usage of System.Drawing.Size in Macro expressions give errors

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#1003]
**Describe the bug**
Exceptions when trying to evaluate System.Drawing.Size in Macros
	System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei XSharp.MacroCompiler.Compilation.Error(Token t, ErrorCode e, Object[] args) in C:\XSharp\DevRt\Runtime\MacroCompiler\Diagnostic\Error.cs:Zeile 219.
   bei XSharp.MacroCompiler.Binder.ConversionError(Expr expr, TypeSymbol type) in C:\XSharp\DevRt\Runtime\MacroCompiler\Binder\Binder.Error.cs:Zeile 117.
   bei XSharp.MacroCompiler.Binder.Convert(Expr& e, TypeSymbol type, ConversionSymbol conv) in C:\XSharp\DevRt\Runtime\MacroCompiler\Binder\Binder.Conversion.cs:Zeile 31.
   bei XSharp.MacroCompiler.Binder.Convert(Expr& e, TypeSymbol type) in C:\XSharp\DevRt\Runtime\MacroCompiler\Binder\Binder.Conversion.cs:Zeile 35.
   bei XSharp.MacroCompiler.Syntax.ExprResultStmt.Bind(Binder b) in C:\XSharp\DevRt\Runtime\MacroCompiler\Binder\Node.Bound.Stmt.cs:Zeile 61.
   bei XSharp.MacroCompiler.Binder.BindStmt[T](T& node) in C:\XSharp\DevRt\Runtime\MacroCompiler\Binder\Binder.Expr.cs:Zeile 47.
   bei XSharp.MacroCompiler.Syntax.Codeblock.Bind(Binder b) in C:\XSharp\DevRt\Runtime\MacroCompiler\Binder\Node.Bound.cs:Zeile 1148.
   bei XSharp.MacroCompiler.Binder.Bind[T](T& node) in C:\XSharp\DevRt\Runtime\MacroCompiler\Binder\Binder.Expr.cs:Zeile 15.
   bei XSharp.MacroCompiler.Binder`2.Bind[U](U macro) in C:\XSharp\DevRt\Runtime\MacroCompiler\Binder\Binder.cs:Zeile 626.
   bei XSharp.MacroCompiler.Compilation`2.Compile(String source) in C:\XSharp\DevRt\Runtime\MacroCompiler\Compiler\Compiler.cs:Zeile 80.
or 
	XSharp.MacroCompiler.CompilationError: Macrocompiler (1,42): error XM0201: No conversion from 'System.Drawing.Size' to 'usual'

**To Reproduce**
cm := "System.Drawing.Size{680,480}"
               c := "{||" + cm + "}"
         	ocb   := &( c )
             uResult := ocb:Eval()

**Expected behavior**
Internal return value as a usual.

**Screenshots**
Could be sent if necessary. Test program attached. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version X#  2.11
 

**Additional context**
[ConsoleTests.zip](https://github.com/X-Sharp/XSharpPublic/files/8408500/ConsoleTests.zip)

**Comment by cpyrgas** [comment]
Couldn't run the attached solution because it's missing a base dll, but I can reproduce some problems with the macrocompiler and classes from the System.Drawing namespace, although with different errors, see below:


```
FUNCTION Start() AS VOID
// make sure assemblies are loaded
? System.Drawing.Size.Empty
? System.Windows.Forms.AnchorStyles.Left

// all the following run with no errors
? MCompile("System.Int32.MaxValue")
? MCompile("System.Windows.Forms.AnchorStyles.Left")
? MCompile("System.Windows.Forms.Form{}")
? MExec(MCompile("System.Collections.ArrayList{}"))
? MExec(MCompile("System.Collections.ArrayList{123}"))
? MExec(MCompile("System.Collections.BitArray{1,FALSE}"))

// those throw a System.NullReferenceException
? MCompile("System.Drawing.Size.Empty")
? MCompile("System.Drawing.Size{1,2}")

/*
System.NullReferenceException
Object reference not set to an instance of an object.

Callstack : 
static CompilationError XSharp.MacroCompiler.Compilation.Error(XSharp.MacroCompiler.Syntax.Token t, XSharp.MacroCompiler.ErrorCode e, System.Object[] args)() 
static CompilationError XSharp.MacroCompiler.Binder.ConversionError(XSharp.MacroCompiler.Syntax.Expr expr, XSharp.MacroCompiler.TypeSymbol type)() 
static System.Void XSharp.MacroCompiler.Binder.Convert(XSharp.MacroCompiler.Syntax.Expr e, XSharp.MacroCompiler.TypeSymbol type, XSharp.MacroCompiler.ConversionSymbol conv)() 
System.Void XSharp.MacroCompiler.Binder.Convert(XSharp.MacroCompiler.Syntax.Expr e, XSharp.MacroCompiler.TypeSymbol type)() 
XSharp.MacroCompiler.Syntax.ExprResultStmt.Node XSharp.MacroCompiler.Syntax.ExprResultStmt.Bind(XSharp.MacroCompiler.Binder b)() 
XSharp.MacroCompiler.Binder`2[XSharp.__Usual,XSharp.MacroCompiler.UsualMacro.MacroCodeblockDelegate].System.Void XSharp.MacroCompiler.Binder.BindStmt(System.Object node)() 
Node XSharp.MacroCompiler.Syntax.Codeblock.Bind(XSharp.MacroCompiler.Binder b)() 
System.Void XSharp.MacroCompiler.Binder.Bind(System.Object node)() 
Object XSharp.MacroCompiler.Binder`2[XSharp.__Usual,XSharp.MacroCompiler.UsualMacro.MacroCodeblockDelegate].Bind(System.Object macro)() 
XSharp.MacroCompiler.Compilation`2[XSharp.__Usual,XSharp.MacroCompiler.UsualMacro.MacroCodeblockDelegate].CompilationResult XSharp.MacroCompiler.Compilation`2[XSharp.__Usual,XSharp.MacroCompiler.UsualMacro.MacroCodeblockDelegate].Compile(System.String source)() 
_Codeblock XSharp.Runtime.MacroCompiler.CompileCodeblock(System.String macro, System.Boolean lAllowSingleQuotes, System.Reflection.Module module)() 
static _Codeblock XSharp.RT.Functions.MCompile(System.String cString, System.Boolean lAllowSingleQuotes)() 
static _Codeblock XSharp.RT.Functions.MCompile(System.String cString)() 
static System.Void xRuntime.Exe.Functions.Start()()   :  C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg  :  15
*/
```

**Comment by ArneOrtlinghaus** [comment]
Thank you for the tests. Yes, this is what happens also in our environment.

**Comment by cpyrgas** [comment]
Confirmed fixed
