### ISSUE TITLE
Winforms Designer - missing override on dispose

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1004]
The code generator currently doesn't generate the override keyword for the Dispose method. This causes a warning, when the EnforceOverride project option is enabled. 

**current behavior**

protected method Dispose( disposing as logic ) as void strict

**Expected behavior**

protected **override** method Dispose( disposing as logic ) as void strict

**Comment by cpyrgas** [comment]
Confirmed fixed
