### ISSUE TITLE
Add references with "Reference Manager" instead of "Add Reference Dialog Box"

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1005]
If you want to add references, X# will still use the reference dialog from previous Visual Studio versions. For example, in the old version the extensions do not exist yet.

![image](https://user-images.githubusercontent.com/20905638/163183544-85171e26-759a-444d-88b8-229023e383c6.png)

![image](https://user-images.githubusercontent.com/20905638/163183615-413141f6-75f5-4235-8284-b93631242edc.png)

**Comment by cpyrgas** [comment]
Confirmed done
