### ISSUE TITLE
Entries not in navigation-bar 

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1008]
With the following class the navigation bar does not display all the entries of the class. In our case the entry with Grid is missing.

![image](https://user-images.githubusercontent.com/20905638/163527822-644c827c-0e28-4dcd-9278-c7aa8d253b65.png)

```c#
using System


//TODO seal class and fix warnings in generated code (created by virtual)
public partial class Brw1
    public property LastRecNo as dword => 1

    public property Grid as BrwGrid
        get
            return null
        end get
        set
            return
        end set
    end property
end class
```

**Comment by RobertvanderHulst** [comment]
The code in the editor does not properly recognize the => operator when merging the members of different parts of partial classes. This is fixed in the next build.

**Comment by cpyrgas** [comment]
Confirmed fixed
