### ISSUE TITLE
ReportPro2 problem with export to RTF

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1012]
When exporting any report to RTF, latest version of RP2 produces an empty page.

**Comment by cpyrgas** [comment]
Problem is caused due to this change: https://github.com/X-Sharp/Rp2Net/commit/6b73b93a4ff054f4ff7caadfeb436c4eee3866e4#r72841345

Not sure why this change was made though. Robert?

**Comment by cpyrgas** [comment]
Problem seems to be fixed, needs testing :)

**Comment by RobertvanderHulst** [comment]
Fixed
