### ISSUE TITLE
Debugger shows wrong Value on MouseOver

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1015]
Sometimes the debugger does show wrong values on mouse over. Here's an example

![image](https://user-images.githubusercontent.com/9860916/165550614-5b810fa7-03c6-4a59-b3e7-3d3bcd20afa5.png)

Instead of using the complete expression, the debugger seems to use only the word under the cursor. To get the correct value, I first have to select the complete expression

![image](https://user-images.githubusercontent.com/9860916/165550832-ad432858-b390-40b8-a924-9ecb4a8d044c.png)

This is the solution, that was used to create the screenshots.

[XSharpTestsDebugger.zip](https://github.com/X-Sharp/XSharpPublic/files/8573289/XSharpTestsDebugger.zip)

**Comment by RobertvanderHulst** [comment]
Volkmar,
I think this happens because the debugger does not recognize the ':' as valid separator between the variable and the member.
If/when we have completed our debugger expression evaluator then this should be solved.
I'll run this through the debugger (debugging the debugger) to see if I can maybe work around this

**Comment by VolkmarR** [comment]
I tried changing the : to . but that also get the incorrect value

![image](https://user-images.githubusercontent.com/9860916/165903406-13d28083-8826-4ae1-9080-879492b130a2.png)

**Comment by RobertvanderHulst** [comment]
Did you try this with C# too ?

**Comment by VolkmarR** [comment]
Yes. It works in c#
![image](https://user-images.githubusercontent.com/9860916/166096611-90c83e17-bbfd-4976-9592-11b1ce3b0750.png)

This is the soultion in c# [TestDebugger.zip](https://github.com/X-Sharp/XSharpPublic/files/8596361/TestDebugger.zip)

**Comment by RobertvanderHulst** [comment]
This cannot be easily solved at this moment.
The Debugger sends in the string "Dummy" and not "e.Dummy".
We will need to investigate further how we can tell the debugger to pass us the complete string for the expression.

**Comment by RobertvanderHulst** [comment]
I checked one more thing and have it working now !

**Comment by cpyrgas** [comment]
I can't confirm this, when I hover over "Dummy" of "e:Dummy" in the sample provided, I get to debugger tooltip at all. Ig I hover it over "e", then I do get the expected tooltip.

**Comment by RobertvanderHulst** [comment]
Chris,
> I get to debugger
Do you mean
I get *NO* debugger

Which version of VS ?

**Comment by cpyrgas** [comment]
Robert, sorry I fixed the comment, yes I meant I get no tooltip at all. In VS2017. I used the specific solution attached to the report for testing.

**Comment by RobertvanderHulst** [comment]
Ok, I see this in VS2017 too. It does work in VS2019 and VS2022.
I am not sure if I should spend the time to fix this for VS2017 too ?
I plan to drop the support for VS2017 with X# 3

**Comment by VolkmarR** [comment]
+1 for dropping support for VS2017.

**Comment by cpyrgas** [comment]
Sorry, no idea, as I'm not a VS user myself, I prefer VS 2017 only because it has nicer default colors :)
I think it's best to ask people in the forum if they are all OK with dropping VS 2017 support.

**Comment by RobertvanderHulst** [comment]
Chris,
I found it. Vs 2017 does not like it when the expression starts with a space. There was a problem in the offset calculation.

**Comment by cpyrgas** [comment]
I'm afraid this still doesn't work here, in either VS 2017 or VS 2019. Here's the current solution I'm testing with:

[CurrentTest.zip](https://github.com/X-Sharp/XSharpPublic/files/9243919/CurrentTest.zip)

**Comment by RobertvanderHulst** [comment]
Volkmar,
Can you confirm that this is fixed ?

**Comment by cpyrgas** [comment]
Robert, it still doesn't work in my VS2019.

**Comment by RobertvanderHulst** [comment]
Chris,
In the locals window. Are you seeing "this" or "SELF" ?
I assume you are seeing "this", which means that the X# debugger extension is not loaded properly. I'll check why that is.

**Comment by cpyrgas** [comment]
Robert, indeed I see "this" in the locals window.

**Comment by VolkmarR** [comment]
I tested this with the current version 2.13.1.
In VS 2022, the correct value is shown on mouseover
In VS 2019, no value is shown on mouseover

**Comment by RobertvanderHulst** [comment]
please check with 2.13.1.0

**Comment by cpyrgas** [comment]
I confirm it's fixed now, but will let also Volkmar confirm, just in case
