### ISSUE TITLE
LOCAL FUNCTION warning - Fox dialect

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#1017]
If you choose the VO dialect the code compiles without a warning. But if you choose the Fox dialect you´ll see the warning:  

`XS9025:Missing RETURN statement. A statement with a default 'empty' return value is returned.`

Although the warning is thrown the result is correct:

```
Test4
Test3
```

To remove the Fox warning disable the first `RETURN "Test3"` and enable the second `RETURN "Test3"`. Using the VO dialect it doesn´t matter where the `RETURN "Test3"` is placed. Shouldn´t the Fox dialect work the same way ?

```
FUNCTION Start() AS VOID 
	
	? Test3()
	
	RETURN 


FUNCTION Test3() AS STRING
	
	? Test4() 
	
RETURN "Test3"

// ----------	
LOCAL FUNCTION Test4() AS STRING 
RETURN "Test4" 
END FUNCTION 	
// ----------
	
// RETURN "Test3"	

END FUNCTION 

```
Karl-Heinz

**Comment by RobertvanderHulst** [comment]
I have no idea why the FoxPro dialects behaves differently here. I'll look into that and I will come back to you.

**Comment by RobertvanderHulst** [comment]
Karl,
The explanation for this is that the dialect FoxPro automatically enables the /vo9 flag when this is not included as /vo9- in the commandline parameters.
And when analyzing the body of function Test3() we see 3 statements:
- QOut Statement
- RETURN statement
- LOCAL FUNCTION Declaration statement
The code that checks for missing returns does not take the LOCAL FUNCTION Declaration statement into account (yet).

**Comment by cpyrgas** [comment]
Confirmed fixed
