### ISSUE TITLE
Typing a comma in some cases does not invoke parameter tip

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1019]
Copy & paste the following in a file, then type a comma after each of the two function calls, this does not invoke the parameter tip to show. If you start by typing the opening paren, then it does show. Also with other functions it does work as expected, but not with this one:

```
FUNCTION Start() AS VOID STRICT
MyFunc(1) 

FUNCTION MyFunc(a AS INT, B AS STRING) AS INT
	MyFunc(1)
RETURN 123
```

**Comment by RobertvanderHulst** [comment]
This seems to happen if the cursor is direct before the closing paren. If there is a space between then the parameter list is shown. I'll fix that.

**Comment by cpyrgas** [comment]
Tooltip is invoked now, but it shows in the top of the file, not in the correct location:

![VS_comma_tooltip](https://user-images.githubusercontent.com/14542129/168032136-535bce7a-ccac-4671-81cd-fee71e5620eb.png)

This happens only when invoking the tooltip with a comma. With an opening paren, then it shows in the correct place.

**Comment by cpyrgas** [comment]
Confirmed fixed
