### ISSUE TITLE
Winforms Designer generates invalid code

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1020]
**To Reproduce**

1. Open the solution [XSharpTestWinforms.zip](https://github.com/X-Sharp/XSharpPublic/files/8589640/XSharpTestWinforms.zip)
2. Open the designer for form1
3. Add a Form_Load eventhandler by double clicking the form in the designer
4. The code in the form1.prg file is now invalid. The ```#endregion``` should not be added

![image](https://user-images.githubusercontent.com/9860916/165916726-7e78396d-46b1-4d0c-8541-8ed50a771520.png)

**Comment by cpyrgas** [comment]
Confirmed. Thanks a lot for the always very helpful repro samples!

**Comment by cpyrgas** [comment]
Confirmed fixed
