### ISSUE TITLE
Intellisense problem with ":" inside a string literal

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1021]
Try typing the code in the last line below, at the moment you type the colon, a member completion list shows up, containing members of the type STRING. Then type the backslash and you end up with cPath := "c:Aggregate(\". Of course nothing should be invoked regarding intellisense while typing inside a string literal (open or close ended).

```
FUNCTION Test()
LOCAL cPath AS STRING
cPath := "C:\"
```

**Comment by VolkmarR** [comment]
The same happens, when you type . in a string (maybe releated to the "Enable Dot ..." option)

**Comment by cpyrgas** [comment]
Confirmed fixed (both for colon and dot)
