### ISSUE TITLE
Unknown identifier makes bogus member completion list to show on colon

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1022]
I can't reproduce it in all solutions, but at least in ReprotPro2, if you press a colon after anything and anywhere, shows a bogus completion list:

![VS_member_completion](https://user-images.githubusercontent.com/14542129/166694334-75477148-8e35-40a2-a76a-11c9de04a9a9.png)

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
Confirmed fixed
