### ISSUE TITLE
Add option to insert page and reorder pages in a tabcontrol, in the VOWED

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1024]
https://www.xsharp.eu/forum/private-product/2990-vs-integration#22376

**Comment by cpyrgas** [comment]
Feature should be implemented, but I could not test it, because for some reason registering the new dll fails in my machine. I have tested the same code in the VOWED in XIDE though and it works fine. Robert you can give it a test, I will also test it when there's a new build available for testing. The new commands appear in the TabControl context-menu.

**Comment by RobertvanderHulst** [comment]
I am no seeing the new menu items. I am only seeing Add Page, Delete Page, Cut,, Copy and Delete

**Comment by cpyrgas** [comment]
Oops, right, the new items need to be displayed, too :)
Done now, please give it a quick test

**Comment by RobertvanderHulst** [comment]
Fixed
