### ISSUE TITLE
Goto Definition in the XAML code editor does not work

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1026]
https://www.xsharp.eu/forum/public-product/2994-issues-with-creating-a-new-wpf-x-program

When right clicking on a method name (like button_click in the attached solution) in the XAML editor of a WPM window and selecting "Goto Definition", in c# the relevant code is opened in the source code editor. In X#, an error is reported "Cannot navigate to definition"

[WpfAppTestcSharp.zip](https://github.com/X-Sharp/XSharpPublic/files/8663406/WpfAppTestcSharp.zip)

**Comment by RobertvanderHulst** [comment]
Fixed in the WPF changes that Fabrice did

**Comment by RobertvanderHulst** [comment]
Fabrice has worked on this. I merged the code and confirm that it is fixed now
