### ISSUE TITLE
Code completion doesn't show extension methods on enum types

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1027]
I created a test project, that defines extension methods on an Enum. When I create a variable of type enum and trigger the code completion. I don't see these extension methods. 

![image](https://user-images.githubusercontent.com/9860916/168320971-5e422b7d-396b-46ae-b12d-a335fbba494f.png)

Here's the test project to reproduce this problem. [XSharpTestEnumExtensionMethods.zip](https://github.com/X-Sharp/XSharpPublic/files/8689182/XSharpTestEnumExtensionMethods.zip)

This is IMHO a minor problem, because extension methods on enums are probably rarely used.

**Comment by VolkmarR** [comment]
This is what is shown in c#:
![image](https://user-images.githubusercontent.com/9860916/168321710-d2d4fec2-6475-4707-9a13-2ab119bfd83a.png)

**Comment by RobertvanderHulst** [comment]
This requires a change in the Intellisense parser. Right now it does not mark methods as extension methods.
I have delayed this until Build 2.14

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
Confirmed fixed
