### ISSUE TITLE
Bogus completion list when typing in the editor

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1028]
Paste the following in the editor:

```
FUNCTION Start() AS VOID STRICT
MyFun()

FUNCTION MyFunc(n AS STRING) AS VOID
```

then put the caret between "n" and "(" in the function call, and correct it by typing a "c". Now a bogus completion list is shown:

![VS_func1](https://user-images.githubusercontent.com/14542129/168640339-d0774b89-bb31-4628-808e-82c034c8c45f.png)

Also try changing the function name in the declaration from MyFunc to something else like MyFuncNew, the same bogus list appears also now:

![VS_func2](https://user-images.githubusercontent.com/14542129/168640635-59ef0faa-9071-4971-bb8e-9cea3dcf020c.png)

More important version of the problem: Paste the following, but type the final line, without auto completing "nTest", just type it char by char:

```
CLASS SomeClass
EXPORT nTest AS INT
METHOD Test()
SELF:nTest
```

The moment you type the final "t", the bogus list appears again:

![VS_bogus_list](https://user-images.githubusercontent.com/14542129/168646103-279f4a1e-3d06-4bbc-9319-f5e5ae37da25.png)

and if you don't notice it and continue typing, space or a colon etc, you end up with "SELF:CompareTo( ":

![VS_bogus_list2](https://user-images.githubusercontent.com/14542129/168646307-51d5bd03-0c4c-4c64-b13d-8f35d4d97cff.png)

**Comment by cpyrgas** [comment]
It's better, but still problematic. Type this:

```
FUNCTION Start()
LOCAL c123456 AS STRING
c12345:Length
```

and then type the missing "6", you get:

![VS_bogus_list3](https://user-images.githubusercontent.com/14542129/168853211-195ada33-bf83-41ef-abec-f005e4d52393.png)

or with this:

```
FUNCTION Start()
LOCAL c AS STRING
c:Lengt:CompareTo()
```

add the missing "h" and you get

![VS_bogus_list4](https://user-images.githubusercontent.com/14542129/168853753-b06dd9ed-15e5-4722-8290-11793f59a914.png)

If you don't notice the incorrect list in the above cases and accidentally accept with enter, space etc, you get 

c123456Aggregate(

and

c:LengthCompareTo( :CompareTo()

**Comment by RobertvanderHulst** [comment]
Please retest with 2.13.
If you see new issues, then please create a new ticket with detailed description.

**Comment by cpyrgas** [comment]
The original problem as described in https://github.com/X-Sharp/XSharpPublic/issues/1028#issuecomment-1129034723 still happens. The other cases are fixed.

**Comment by cpyrgas** [comment]
Problem not happening anymore, but that's due to the feature completely disabled. Reopening this, so I remember to retest, when the feature is introduced again.

**Comment by RobertvanderHulst** [comment]
The autotype is disabled. However Ctrl-Space works as expected. 
Can we close this now and make new tickets for AutoType later when needed?

**Comment by cpyrgas** [comment]
OK, confirmed fixed!
