### ISSUE TITLE
IVarGet with reintroduced property (X#2.11.0.1)

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1030]
IVarGet doesn't return reintroduced property. In this example, TestForm.Owner returns Dummy, IVarGet(testForm, #Owner) returns nil

```
function Start() as void strict
    var testForm := BaseForm{}
    if (testForm.Owner != IVarGet(testForm, #Owner))
        Console.WriteLine("Error")
[XSharpTestsIVarGetNew.zip](https://github.com/X-Sharp/XSharpPublic/files/8727069/XSharpTestsIVarGetNew.zip)

    endif
return

class BaseForm inherit Form
    public new virtual property Owner as object get "Dummy"
end class

```

Example solution: [XSharpTestsIVarGetNew.zip](https://github.com/X-Sharp/XSharpPublic/files/8727073/XSharpTestsIVarGetNew.zip)

**Comment by VolkmarR** [comment]
The same is true for IVarPut

**Comment by RobertvanderHulst** [comment]
Volkmar,
Can you confirm that this is fixed ?

**Comment by VolkmarR** [comment]
Confirmed Fixed. Works with IVarGet and IVarPut
