### ISSUE TITLE
Winforms Designer creates duplicate properties for file with private class (X#2.12)

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1031]
* Open the Form 1 in Test Solution [XSharpTestWinforms.zip](https://github.com/X-Sharp/XSharpPublic/files/8737806/XSharpTestWinforms.zip)
* Create an event in the designer (ex FormLoad)
* Properties of private class are copied to form class
* Additionally, the private class is moved

Code before adding event handler:

![image](https://user-images.githubusercontent.com/9860916/169489114-2dd7aec0-fcd9-4fbb-a85b-7878dbb62a65.png)

Code after adding event handler:

![image](https://user-images.githubusercontent.com/9860916/169489184-1676eee7-fff0-430c-8983-c24c6500b585.png)

**Comment by RobertvanderHulst** [comment]
You guys are really pushing the VS Form editor to the limit.
Why not create a new PRG file with the same partial class that contains the nested class ?
I'll try to fix it, but it might be easier if you do not put code like this in the source of the class

**Comment by VolkmarR** [comment]
I did that to fix this problem. In my concrete example, I've a DataGrid, that shows a items from a list. Since this class is only used inside that form, I prefer to put it inside that class, so no one else uses it.

**Comment by RobertvanderHulst** [comment]
Chris confirms that this is fixed
