### ISSUE TITLE
Problems with "Complete word "

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1036]
In the following case the complete word command seems to display only namespaces and not the classes (e.g. Action)

```
using System.Text
using System.Collections.Generic

/// <summary>The ClassName1 class.</summary>
public class ClassName1
	public method Test() as void
		System.ac
		return

end class
```
![image](https://user-images.githubusercontent.com/20905638/170021972-79a193f4-d6f0-49d2-bfe5-99b0a7399836.png)

In this situation it concats the whole selected word, also if it is written already something:
```
using System.Text
using System.Collections.Generic

/// <summary>The ClassName1 class.</summary>
public class ClassName1
	public method Test() as void
		var name := "name"
		if (name is Sy)
		return

end class
```
![image](https://user-images.githubusercontent.com/20905638/170022593-08b28a6f-e686-44bb-a117-7230c1fdc9e7.png)

Here you don't get any suggestions (if statement -> after "Sy")
```
using System.Text
using System.Collections.Generic

/// <summary>The ClassName1 class.</summary>
public class ClassName1
	public method Test() as void
		var name := "name"
		if name is Sy
		return

end class
```

**Comment by hpetriffer** [comment]
Attached is a solution with the first example. 
[XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/8768138/XSharpTests.zip)

Do you need also one  with the other cases?

**Comment by cpyrgas** [comment]
Thanks, but no need to, the other cases are just not supported yet, it's a known issue.

Problem is I can't reproduce the first problem with your solution (thanks for posting it though!) either. Let's see if maybe Robert can reproduce it.

**Comment by hpetriffer** [comment]
Strange. We have the issue on all pc's. Maybe it is a setting in VS?

**Comment by RobertvanderHulst** [comment]
Hansjoerg,
Can you open the settings dialog Tools/Options and then Search for X# in the search box on the top.
You should see an entry called "Settings Completion".
Can you make sure that all the checkboxes on this form are checked (by pressing the All button)

Robert

**Comment by hpetriffer** [comment]
I have everything checked:
![image](https://user-images.githubusercontent.com/20905638/170192152-ab759c4c-edf9-4f3e-aa27-fd41f65bf4b3.png)

Attached I have a log file (only log code completion enabled). May be it helps
[Project_7FC8_20220525.log](https://github.com/X-Sharp/XSharpPublic/files/8768458/Project_7FC8_20220525.log)

**Comment by RobertvanderHulst** [comment]
Hansjoerg,
Ok, I can see this now too. Will try to fix it.

**Comment by hpetriffer** [comment]
Once I had also a strange behaviour when I was inside the settings dialog und pressing Ok...Everything was disabled after that...

**Comment by RobertvanderHulst** [comment]
> Oh, now it is working again! And I am getting a message saying that VS was closed automatically during a software update and offers me an option to restore my prg files. I do not know what I should believe when VS reports things, I'll just leave it at that.
> 
> Bottom line is I can now check all those options, but none seem to work, but I think this is by design, isn't it? Didn't we decide to enable this functionality again in a later build, because the current implementation is too problematic?

Yes, they normally are only used for code completion while typing.
