### ISSUE TITLE
SetAnsi(FALSE) causes SingleLineEdit controls with pictures to show random characters when entering umlautes

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1038]
Attached sample has an SLE with a picture "@!". When typing an umlaut char in that SLE, a random character is inserted instead. Same with "@A" etc.

When SetAnsi(TRUE) is used, or no picture at all, then it works as expected.

[TestProject.zip](https://github.com/X-Sharp/XSharpPublic/files/8762654/TestProject.zip)

**Comment by RobertvanderHulst** [comment]
FormattedString:ProcessKeyEvent() calls Chr() with the ASCII code from the keyevent.
Chr() uses the current setting of SetAnsi to determine which codepage to use to convert the key number into a character.
With SetAnsi(FALSE) this uses the DOS Codepage.
I am not sure why but in this case it has to use the Windows Codepage.
Maybe we should create an overload of Chr() or a ChrAnsi() that always uses the Ansi codepage and call that from the ProcessKeyEvent() and similar methods

**Comment by RobertvanderHulst** [comment]
Alternatively we can change the code from 
`lRet := SELF:ProcessChar(Chr(oKeyEvt:ASCIIChar))`
to
`lRet := SELF:ProcessChar( ((char) oKeyEvt:ASCIIChar):ToString())`

**Comment by cpyrgas** [comment]
Oops! Apparently I had added it many years ago in the vulcan code then :)

**Comment by cpyrgas** [comment]
Robert, do you mean you will include this in the next build, not in 2.12?
If that's the case, I will send Moritz (who reported this) directly a fix shortly after the 2.12 release.

**Comment by RobertvanderHulst** [comment]
Ok, I will create another installer with the changes to the Forms editor and this runtime change.

**Comment by cpyrgas** [comment]
Robert, maybe don't include the winforms changes, since they can have potentially side effects and won't be easy to find with a quick test. But this particular fix with ProcessChar() was apparently proven to be working well already 10 years ago in vulcan :)
