### ISSUE TITLE
VS incorrect highliting of ()

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1040]
Paste this code in a prg file and put the caret exactly between the opening and closing paren in any line, then all parens are being highlited in the file. And if you use the up cursor key to move to a different line, the parens still remain highlited.

```
FUNCTION Start() AS INT
	ErrorTest()
	IF TRUE
        Test()
	ENDIF
RETURN 0

FUNCTION Test()
	Something()
```

![VS_parens](https://user-images.githubusercontent.com/14542129/170352224-26817196-2055-4460-8740-865b927e961a.png)

**Comment by RobertvanderHulst** [comment]
We are using a generic  "HighlightWord" routine now and this routine received the word "()" and was highlighting that word everywhere in the buffer.
I am now excluding words that do not start with a valid identifier character

**Comment by cpyrgas** [comment]
Robert, the problem is two fold, one that the parens get highlited and the other that they keep highlited after you move the caret. This happens with any token, for example put the caret on "test" of Function test, it highlights this and another occurence, which is correct. Now press the Up arrow, the caret goes to another line, but "test" is still being highlited.

**Comment by cpyrgas** [comment]
Unfortunately it is still very problematic. Put the caret over any of the "abc" below, all occurrences get highlited, which is nice. But now move the cursor to as many lines up or down, the words are kept highlited all the time, even though the care is now in an empty line, a comment etc.


```
FUNCTION test()
	LOCAL abc AS INT
	abc := 1
	
// still here
	
	abc := 2
//   
	abc := 3
	
	// comment
	
```

**Comment by RobertvanderHulst** [comment]
This problem also existed in the previous builds, but because the colors are now more "prominent" we see it now.
We use a feature from the Community.VisualStudio.Toolkit here. I have found the issue in that toolkit, fixed it and I have sent in a Pull Request. I'll mark this as completed when the pull request has been approved

**Comment by cpyrgas** [comment]
Indeed confirmed fixed!
