### ISSUE TITLE
Winforms Designer Issues

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1042]
The latest fixes resolved already many issues with the winforms designer. I was able find two new issues with the designer.

1) A comment is duplicated in certain situations
2) A Function/Procedure located outside of the form class is removed

before:
![image](https://user-images.githubusercontent.com/9860916/170444830-8d67e599-4234-47a0-9a76-8f4ffabb6a13.png)

after adding a event handler:
![image](https://user-images.githubusercontent.com/9860916/170444971-bdca0cce-6650-49d0-a76b-88f626f810b7.png)

Testsolution: [XSharpTestWinformsDesigner.zip](https://github.com/X-Sharp/XSharpPublic/files/8777356/XSharpTestWinformsDesigner.zip)

**Comment by cpyrgas** [comment]
Confirmed, and also GLOBALs and DEFINEs are being removed

**Comment by cpyrgas** [comment]
...but it looks like it is actually an old issue, not new in 2.12. I checked with 2.11 and it also removes functions at the end.
So while this needs to be fixed of course, I think it can wait for 2.13.

**Comment by VolkmarR** [comment]
You are right. It is not a new issue.

**Comment by RobertvanderHulst** [comment]
Ok, fixed,
For now all "global" entities (functions, procedures, globals, defines, _DLL functions, VOSTRUCT and UNION are written at the end of the compilation unit (file).

**Comment by cpyrgas** [comment]
The GLOBALs/FUNCTIONs indeed do net get removed anymore, but the comments still keep getting duplicated after each change and save in the designer

**Comment by cpyrgas** [comment]
Unfortunately it still does not work correctly. See this test solution I am working with.

[NewTest.zip](https://github.com/X-Sharp/XSharpPublic/files/9243862/NewTest.zip)

1. Open the form in design mode.
2. Do a dummy change and Save
3. Do another dummy change and Save again
4. View the code in the prg, now a PROPERTY inside it is duplicated:

    PUBLIC PROPERTY SelLength AS INT AUTO SET GET // TODO Test
    PUBLIC PROPERTY SelLength AS INT AUTO SET GET // TODO Test

**Comment by cpyrgas** [comment]
Nah, reopening it, there are too serious side effects with adding new winforms to the project.

**Comment by cpyrgas** [comment]
Confirmed fixed!
