### ISSUE TITLE
Implicit typecast error that didn't exist before (X# 2.12.2.1)

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1048]
I updated X# from version 2.9.1.1 to X# 2.12.2.1
When compiling the following code, an error occurs that was not there before:
```
#pragma options ( "vo7", ON )
FUNCTION TestFunc() AS VOID STRICT

	LOCAL val AS INT
	LOCAL b AS BYTE

	val := 1
	b |= val & 0x0F

	RETURN
#pragma options ( "vo7", DEFAULT )
```
> Error XS0266 Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)

The error itself is correct, if you do not specify compatibility options in the compiler settings, that you are doing this consciously. In X# 2.9, such code compiled without errors and worked correctly. It seems that the compatibility options have stopped working.

**Comment by leon-ts** [comment]
Robert,
Is it possible to return the behavior as in version 2.9 with the vo7 parameter enabled (without any warnings)? After all, the meaning of the vo7 parameter is that the result is similar to VO, including the display of warnings. The VO in this example does not generate warnings. Otherwise, ported code (as in my case) will have a gazillion of compiler warnings. If vo7 is off, then the current behavior (typecast error) is quite correct.

**Comment by leon-ts** [comment]
On the other hand, when I've ported a project (the vo7 option is enabled) and continue to work with it in X# (editing old code, adding new code, etc.), the warning you added will come in handy and help avoid potential errors.

**Comment by leon-ts** [comment]
> For now I am generating a warning:
> `warning XS9070: The compiler generated an implicit cast to a smaller type from type 'int' to 'byte'.`
> Is that OK with you ?

Yes.

**Comment by cpyrgas** [comment]
I agree, all VO apps will have /vo7 enabled, so the warning is necessary, otherwise people would never get something to tell them about this potential issue. And warnings are very easy to be disabled if they are annoying.

**Comment by cpyrgas** [comment]
Ah, spoke too soon  probably. When /vo4 or /vo7 are enabled, now the above code (and code in C855) reports a warning, which is correct.

But when both /vo4 and /vo7 are disabled, again the same warning is reported. Shouldn't it be an error in that case instead?

**Comment by RobertvanderHulst** [comment]
Chris,
VO7 is not related to numeric conversions, but is related to conversion between pointers.
VO4 and VO11 are meant for numeric conversions.
And XS9070 is always a warning. You can make this an error by enabling "warnings as errors"

**Comment by cpyrgas** [comment]
Robert, when /vo7 (and /vo4) is disabled, this reports an error XS0266: Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?):

FUNCTION Start() AS VOID
LOCAL b AS BYTE
LOCAL n AS INT
b := n

When /vo7+ is enabled (even though /vo4- is still disabled), it does not report an error and neither a warning anymore.

We have talked about it in the past, /vo7 should not be related to numeric conversions, but it actually is, and it's complicated to change that in the compiler code now.

**Comment by cpyrgas** [comment]
...and this is also a current inconsistency related to the general issue discussed here, since "b := n" and "b += n" behave differently regarding reported warnings/errors, for the same set of /vo4 and /vo7 compiler options used

**Comment by RobertvanderHulst** [comment]
Chris,
This was an error. On one spot I was still checking for the setting of /vo7 to determine if a numeric assignment should generate an error or not.

**Comment by cpyrgas** [comment]
Robert, that's nice, much better now! But there are still several inconsistencies, for example see the different errors/warnings/no warnings at all for each cluster of commands in this code when /vo4+ is enabled and /vo11- is disabled:


```
FUNCTION Start() AS VOID
LOCAL dw := 0 AS DWORD
LOCAL i := 0 AS INT
LOCAL b := 0 AS BYTE

dw := i // warning 9021
dw += i // warning 9021
dw := i + 1 // NO WARNING
i := dw // warning 9021
i += dw // warning 9021
i := dw + 1 // NO WARNING
testD(i) // NO WARNING
testI(dw) // NO WARNING
testB(i) // NO WARNING
testB(dw) // NO WARNING

b := i // error 0266
b := i + 1 // error 0266
b += i // warning 9070
b := dw // error 0266
b := dw + 1 // error 0266
b += dw // warning 9070

FUNCTION testI(n AS INT) AS VOID
FUNCTION testD(n AS DWORD) AS VOID
FUNCTION testB(n AS BYTE) AS VOID

```

**Comment by leon-ts** [comment]
Robert,
I installed version 2.13 intended for beta testing and got the following compilation results.

**Errors:**
_XS0266 Cannot implicitly convert type 'dword' to 'word'. An explicit conversion exists (are you missing a cast?)
XS0266 Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
etc._

**Warnings:**
_XS9021 Signed/unsigned conversions from 'int' to 'dword' may lead to loss of data or overflow errors
XS9021 Signed/unsigned conversions from 'dword' to 'int' may lead to loss of data or overflow errors
etc._

The vo4 and vo7 options are enabled in the project under test.

**Comment by leon-ts** [comment]
Sample code that generates the mentioned errors:
```
// wDec AS WORD
wDec := SetDecimalSep(Asc("."))
```

Sample code that generates the mentioned warnings:
```
// i AS INT
// dwStart AS DWORD
i := dwStart
```

**Comment by cpyrgas** [comment]
Leonid, for the error, SetDecimalSep() returns a DWORD, but you are storing the result to a WORD, which can lead to overflow. So you either need to add a (WORD) cast, or enable the /vo11 (compatible arithmetic conversions) compiler option.

The warning in the second case is reported for a similar reason, you can get the wrong result by assigning a DWORD to an INT, or the opposite. You can get rid of the warning with a cast again, or you can completely disable those specific warning number (in the project properties) if you wish

**Comment by cpyrgas** [comment]
Additional inconsistency:

With no compiler options used, this code reports an error and a warning:

```
// error XS0266: Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)
// warning XS9020: Narrowing conversion from 'int' to 'byte' may lead to loss of data or overflow errors
FUNCTION Start() AS VOID
LOCAL b := 1 AS BYTE
LOCAL n := 2AS INT
b := _Or(b,n)
? b
```

When /vo11 (soon to be replaced with /vo4 as we decided) is enabled, then both the error and warning disappear. This is inconsistent with the rest of the related behavior, a warning needs to be reported still.

**Comment by cpyrgas** [comment]
It's mostly looking good now, except for one problem:

This does not report any warning, while it should, for every function call:

```
// vo4+
FUNCTION Start() AS VOID
LOCAL dw := 0 AS DWORD
LOCAL i := 0 AS INT

testD(i) // NO WARNING
testI(dw) // NO WARNING
testB(i) // NO WARNING
testB(dw) // NO WARNING

FUNCTION testI(n AS INT) AS VOID
FUNCTION testD(n AS DWORD) AS VOID
FUNCTION testB(n AS BYTE) AS VOID

```

**Comment by RobertvanderHulst** [comment]
Chris,
I am not sure (did not test this) but I think the compiler is smart enough to see that `dw `and `i` have a constant value of 0, and I am suppressing error messages for numeric values that are constant.

**Comment by cpyrgas** [comment]
Robert, that's not it, I changed the code to

LOCAL dw := UInt32.MaxValue AS DWORD
LOCAL i := -1234 AS INT

and get the same result (no warnings) and of course at runtime the parameters get overflowed values

**Comment by cpyrgas** [comment]
Looking good now. Still the compiler could be smarter and also throw a warning/error for example for this (that now compiles with no warnings):

FuncWhichAcceptsAnIt( UInt32.MaxValue )

since UInt32.MaxValue is a constant, but that's for sometime in the future maybe, in another ticket. For now, this is confirmed done!
