### ISSUE TITLE
Code generation issue with ASYNC code

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1049]
See https://www.xsharp.eu/forum/private-product/3031-v-2-12-2-problem
We'll have to create a small example to reproduce this

**Comment by cpyrgas** [comment]
My version of the repro code does indeed work well now, but that's possibly different to the original problem (sample was not provided, so I created one based on the info I had and the result that was reported). So it looks good now, but will need Trevor to test it with their own code to confirm it fixed.

**Comment by RobertvanderHulst** [comment]
Trevor confirmed that this is fixed
