### ISSUE TITLE
Feature Request: enable this keyword as alternative to self keyword

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1050]
The watch window currently doesn't accept the self keyword. So code like 

`self:Location:X`

must be rewritten to 

`this.Location.X`

in order to work in the watch window. It is already possible to use the . instead of the : in the code. Would it be possible to also enable  the `this` keyword as a alternative for `self`? That would simplify the work with the watch window.

**Comment by RobertvanderHulst** [comment]
Nikos is currently working on the debugger expression evaluator. When that is finished then you can use "normal" expressions like self:caption everywhere ( case insensitive as well)

**Comment by cpyrgas** [comment]
Confirmed done!
