### ISSUE TITLE
Problems with code generation in the WinForms designer

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1052]
1. (this is the most important one)
- Create a new WinForms project
- Add a new WinForm in the project, use the standard "Windows Forms Form" template
- Add a Button control to the form
- Save the form (with either CTRL+S or the save toolbar button)
- Move the Button somewhere else in the form
- Save the form again
- Use "View code", you will see that the CONSTRUCTOR is duplicated in the .prg

2. (not so important issue, just annoying and probably caused by the same reason as 1)
- Create a new WinForms project
- Add a new WinForm in the project, this time use the template "Windows Forms Simple Form" 
- Same as in (1):
- Add a Button control to the form
- Save the form (with either CTRL+S or the save toolbar button)
- Move the Button somewhere else in the form
- Save the form again
- Use "View code", you will see that the line "PRIVATE button1 AS System.Windows.Forms.Button" is at the bottom of the prg, instead just after the class declaration.

**Comment by RobertvanderHulst** [comment]
Duplicate code generation is suppressed.
For the fields I change the algorithm:
- if there are no fields (not even the components field) then the new field are placed as the first children of the class
- if there are existing fields then the new fields are placed right after the first "group" of fields

**Comment by cpyrgas** [comment]
Unfortunately I'm still seeing the duplicate constructor generation. To reproduce, I just followed 1:1 the instructions in the report.

**Comment by cpyrgas** [comment]
Confirmed fixed.
