### ISSUE TITLE
VS freeze with Clean Solution

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1053]
In VS2017, in any solution, select "Rebuild Solution" (does not matter if it succeeds or not) and right after, select "Clean Solution", now VS freezes seemingly forever.

**Comment by cpyrgas** [comment]
I'm on 15.9.39.

Here's a test solution that reproduces this here, just in case it does not happen with really every solution:

[XsharpFormsTest.zip](https://github.com/X-Sharp/XSharpPublic/files/8877741/XsharpFormsTest.zip)

**Comment by RobertvanderHulst** [comment]
No, I do not see the problem with this solution in 15.9.48.
I'll try to install build 15.9.39 on a VM to see if I can reproduce it.

**Comment by RobertvanderHulst** [comment]
I do not see the problem with 15.8.9.
I cannot find an installer for 15.9.39. MS does not provide individual installers for VS 2017 "sub builds".
The only 15.9 installer that I can find is 15.9.48 :(

**Comment by cpyrgas** [comment]
Robert, Frank is having also the problem with VS2019, version 16.11.15 (see https://www.xsharp.eu/forum/public-product/3037-visual-studio-crashes-since-last-xsharp-update#22728), so I'm guessing it does not have to do with a specific VS version. Anything I can do to help you diagnose this?

**Comment by RobertvanderHulst** [comment]
Maybe this has to do with the fact if the error list window is open when you build, or if the output window is open when you build.
Can you tell me what is the situation on your VS2017 installation?

**Comment by cpyrgas** [comment]
Robert, they are both "open" in the sense they are docked in the bottom part of the mains VS window. When I click Rebuild, VS automatically makes Errors the "active" one from all those in the bottom part. When I click Clean, then Output becomes active and at that moment, VS freezes

**Comment by cpyrgas** [comment]
Confirmed fixed
