### ISSUE TITLE
Optimization of speed Intellisense

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1061]
If you have the following code and want to correct the error "=" instead of ":=" than it takes a few seconds to insert the ":". After inserting it you get some intellisense hints which are wrong. In the case that a space i before the ":" it is not needed to search the info

`_rtb.EditValue = getChar(e)`

![image](https://user-images.githubusercontent.com/20905638/175321912-1667c94d-0e2e-4f68-baff-0203a3adf63f.png)

**Comment by RobertvanderHulst** [comment]
This was fixed in an earlier build.

**Comment by cpyrgas** [comment]
Will let @hpetriffer confirm this one

**Comment by hpetriffer** [comment]
Confirmed. It works now
