### ISSUE TITLE
X# 2.13 Beta Runtime error Das Objekt des Typs "xxxkann nicht in Typ "System.Func`2[XSharp.__Usual,System.Boolean]" 

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#1062]
**Describe the bug**
Runtime error that happens with the attached program

**To Reproduce**
But now I get strange errors when running the program:
System.InvalidCastException
HResult=0x80004002
Message=Das Objekt des Typs "tabSettingsAllgemeinEdit" kann nicht in Typ "System.Func`2[XSharp.__Usual,System.Boolean]" umgewandelt werden.
Source=BaseSystem
StackTrace:
at DataServer.RegisterClient(Object oForm) in C:\projects\xsharp\AcsLib\src\BaseSystem\DataServer.prg:line 291
at IM.XsLib.AcsSQL.SqlDynamic.RegisterClient(Object oForm) in C:\projects\xsharp\AcsLib\src\AcsSQL\SqlDynamic.prg:line 1561

The position of the code is this. This is also verified with the debugger. The array is empty in this moment.

->>> if AScan( aClients, oForm ) # 0
[ConsoleTests.zip](https://github.com/X-Sharp/XSharpPublic/files/8980647/ConsoleTests.zip)

**Comment by cpyrgas** [comment]
Confirmed, here's a cut down sample of the problem:

```
CLASS TestClass
END CLASS

FUNCTION Start() AS VOID
LOCAL a AS ARRAY
LOCAL o AS OBJECT

a := {}

? AScan(a,NIL)	// OK
? AScan(a,1)	// OK
? AScan(a,NULL_SYMBOL)	// OK
? AScan(a,#ABC)	// OK
? AScan(a,Today())	// OK
? AScan(a,NULL_OBJECT)
? AScan(a,TestClass{}) // OK
o := TestClass{}
? AScan(a,o) // Unable to cast object of type 'System.Collections.ArrayList' to type 'System.Func`2[XSharp.__Usual,System.Boolean]'.

```

**Comment by cpyrgas** [comment]
Problem happens only when /lb is enabled!

**Comment by cpyrgas** [comment]
Confirmed fixed
