### ISSUE TITLE
X# 2.13 Beta - Runtime error AScan with param nStart supplied 

### ISSUE THREAD

**Issue by fxxm** [X-Sharp/XSharpPublic#1063]
This is new to the 2.13 beta.

```
LOCAL aArray0 := {"SomeString1"} AS ARRAY
AScan(aArray0, {|x|x=="1"})  // Works
AScan(aArray0, {|x
|x=="1"}, 1) // Fails - "Value does not fall within the expected range" 
```
[ConsoleApplication5.zip](https://github.com/X-Sharp/XSharpPublic/files/8989642/ConsoleApplication5.zip)

**Comment by cpyrgas** [comment]
Thanks, problem confirmed. It's similar but also different to https://github.com/X-Sharp/XSharpPublic/issues/1062, will update the test case with it

**Comment by cpyrgas** [comment]
Confirmed fixed
