### ISSUE TITLE
Intellisense for enums

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1064]
In our code it often happens that with enums the wrong values are suggested with Intellisense.

```
public constructor()
        super()
        self:InitializeComponent()
        if self:IsDesignTime
            return
        endif

        // Create a new empty document to load the default font etc.
        self:richEdit:CreateNewDocument()

        _commandHelper := EditFormattedTextCommandHelper{self}
        _customLayoutVisitor := CustomLayoutVisitor{self:richEdit}

        // Set 100% as the default zoom
        self:SetZoom(100)

        self:SwapInsertLineBreakAndInsertParagraph := true

        self:richEdit:Options:Hyperlinks:ShowToolTip := false

        // With this the cursor will not change when hovering over a hyperlink
        self:richEdit:Options:Hyperlinks:ModifierKeys := DevExpress.Portable.Input.PortableKeys.A
        self:richEdit:Options:Export:Html:CssPropertiesExportType := DevExpress.XtraRichEdit.Export.Html.CssPropertiesExportType.

        return

```
If you make the dot in the last line before the return, then you have to wait for a longer time. Afterwards one gets many classes, instead of the values of the enum, as suggestion for the autocompletion.
Attached is the log of Visual Studio with enabled Intellisense output.

[Project_9E74_20220628 - Copy.log](https://github.com/X-Sharp/XSharpPublic/files/8999088/Project_9E74_20220628.-.Copy.log)

**Comment by hpetriffer** [comment]
Making an example I had some other strange things:

If you write the code:

```
using System.Text
using System.Collections.Generic

/// <summary>The ClassName1 class.</summary>
public partial class ClassName1
	public property TestType as IM.Test.

end class
```
First you geht the following entries:
![image](https://user-images.githubusercontent.com/20905638/176137013-c132ec8e-0b73-414a-907e-2437cb3d9de2.png)

If I press later after the dot CTRL+Space you get the following
![image](https://user-images.githubusercontent.com/20905638/176138097-83da0833-6d5f-48e1-b35c-48644585f9a9.png)

Also if you have not the right namespace the following is displayed
![image](https://user-images.githubusercontent.com/20905638/176140187-41befe3a-5e2a-48af-95e3-c1802b79427f.png)

Attached for this cases a small example. 
[XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/8999431/XSharpTests.zip)

Unfortunally the behaviour of the above problem is not possible to reproduce. I will send you the solution with email

**Comment by cpyrgas** [comment]
Thanks, I see those problems too. And one more, when you type "IM.", you do not get a list that should contain namespaces/classes included in the IM namespace.

**Comment by cpyrgas** [comment]
Original problem still exists, typing dot on the enum produces a list of members, but not the members of the enum:

![enum_bug](https://user-images.githubusercontent.com/14542129/202106562-534726f4-bf88-4bc1-ab6b-c7cfb77ce65d.png)

To reproduce, just add a DevExpress RichEditControl to any form, so that VS adds the necessary references, then type this code:

local o as object
o :=  DevExpress.XtraRichEdit.Export.Html.CssPropertiesExportType.

**Comment by RobertvanderHulst** [comment]
The problem in this ticket that it actually shows a couple of different problems:
- There is a Namespace IM.Test and a type called Test. The editor had problems resolving IM.Test to the namespace. It was returning the Test type
- There was a problem looking up the members of an Enum type.
I'll check both again and make the necessary changes. Let's hope this does not break other things :)

**Comment by cpyrgas** [comment]
Confirmed fixed
