### ISSUE TITLE
Wrong display for hint of parameter at method call

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1066]
The following code produces this output in VS. As you can see during writing the forth parameter you get the hint that you are on the second parameter. 

![image](https://user-images.githubusercontent.com/20905638/176368410-be392368-c14f-4a5f-ad2d-9fb1bbb0c7b1.png)

```
using System
using System.Collections.Generic
using System.Linq
using System.Text

class Test
	public method TestCall(i1 as int, i2 as int, i3 as int, i4 as int) as void
		return
		
	public method GetVal() as int
		return 1
end class

function Start() as void strict
	var test := Test{}
	test:TestCall(1, 2, test:GetVal(),
	
	return
```

**Comment by cpyrgas** [comment]
Confirmed fixed
