### ISSUE TITLE
Feature request: make overloads for Between

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1067]
Some time ago, there was a request from X# users to create typed overloads for the 'Empty' function:
#669 

This approach to improving runtime functions has proven to be very effective. In this regard, I ask you to add overloaded versions of the 'Between' function to X# as well.

**Example:**
```
FUNCTION Between(uValue AS USUAL, uMin AS USUAL, uMax AS USUAL) AS LOGIC
    RETURN ( uValue >= uMin .AND. uValue <= uMax )

#region Between Overloads

[MethodImpl(MethodImplOptions.AggressiveInlining)];
FUNCTION Between(cValue AS STRING, cMin AS STRING, cMax AS STRING) AS LOGIC
    RETURN ( cValue >= cMin .AND. cValue <= cMax )

[MethodImpl(MethodImplOptions.AggressiveInlining)];
FUNCTION Between<T>(uValue AS T, uMin AS T, uMax AS T) AS LOGIC WHERE T IS System.IComparable<T>
    RETURN ( uValue:CompareTo(uMin) >= 0 .AND. uValue:CompareTo(uMax) <= 0 )

#endregion

```

**Comment by RobertvanderHulst** [comment]
I will have to rewrite the string version as 
```
[MethodImpl(MethodImplOptions.AggressiveInlining)];
FUNCTION Between(uValue AS STRING, uMin AS STRING, uMax AS STRING) AS LOGIC
    return XSharp.RuntimeState.StringCompare(uMin, uValue) <= 0 .and. ;
        XSharp.RuntimeState.StringCompare(uValue, uMax) <= 0
```
so it will take into account the current /vo13 and the SetExact settings

**Comment by RobertvanderHulst** [comment]
We will move this code to the XSharp.Tools repository as well.
See my comment  https://github.com/X-Sharp/XSharpPublic/issues/1068#issuecomment-1193292316

**Comment by leon-ts** [comment]
Robert,
The gradual typing of RT functions would be consistent with the overall X# improvement strategy that you and your team are pursuing (strong compiler, new warnings and errors, etc.). After all, functions like Between, Min, Max and others have always been part of the RT, both in VO and in X#. That is, I am not suggesting adding any new functions or classes, but only improving existing ones.

Typing not only improves the performance of the code, but also eliminates errors like the following (compiles without problems, and the error will only be at runtime):
```
IF Between(1, "abc", TRUE)
    ? "Oops!"
ENDIF
```
Maybe, in addition to other function overloads, always leave the USUAL version of the function as well? In this case, for the Min and Max (INT + DWORD) functions you provided, the compiler would simply choose the USUAL (original) version of the function. Or maybe you can make a typed version of RT, like you did with TypesSDK.

**Comment by leon-ts** [comment]
If there are no objections, then I think this ticket can be deleted.
See my comment [#1068 (comment)](https://github.com/X-Sharp/XSharpPublic/issues/1068#issuecomment-1193991833)
