### ISSUE TITLE
InvalidCastException when Casting a Usual to a Enum defined as DWord

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1069]
When Enums are defined as dwords, a Cast from a Usual variable containing a valid number throws an InvalidCastException 

```
public enum MyTwoValues
   First := 1
   Second := 2
end enum

public enum MyTwoValuesDword as dword
   First := 1
   Second := 2
end enum

function Start() as void strict
   local UsualVal := 1 as usual
   var EnumVal1 := (MyTwoValues)UsualVal // This works
   var EnumVal2 := (MyTwoValuesDword)UsualVal // This doesn't work
   return
```

Here's the test-solution: [XSharpTestsEnumCast.zip](https://github.com/X-Sharp/XSharpPublic/files/9054079/XSharpTestsEnumCast.zip)

**Comment by RobertvanderHulst** [comment]
Values in a USUAL are stored as either INT, INT64, DECIMAL or FLOAT.
If you add a cast
`var EnumVal2 := (MyTwoValuesDword) (LONG) UsualVal`
then it works.
I will see if I can tell the compiler to add that cast automatically.

**Comment by cpyrgas** [comment]
Confirmed fixed
