### ISSUE TITLE
Unexpected XS0460 error when adding public keyword

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1072]
The compiler gives an unexpected XS0460 error (Constraints for override and explicit interface implementation methods are inherited from the base method, so they cannot be specified directly, except for either a 'class', or a 'struct' constraint.) on the Dummy2 method declaration.

The only difference between Dummy1 and Dummy2 is the  "public" keyword (and the method name).

```
public class Test

    method Dummy1<T>(val as string) as T where T is IEnumerable
        return default(T)

    public method Dummy2<T>(val as string) as T where T is IEnumerable
        return default(T)

end class
```

Testproject:  [XSharpTestsGenericsPublic.zip](https://github.com/X-Sharp/XSharpPublic/files/9119555/XSharpTestsGenericsPublic.zip)

**Comment by cpyrgas** [comment]
Confirmed. Problem happens only when /vo3 (all instance methods VIRTUAL) is enabled, so it probably reveals some deeper issue with applying this modifier in methods.

**Comment by cpyrgas** [comment]
Confirmed fixed
