### ISSUE TITLE
XBase++ preprocessor: #translate unexpected behaviour

### ISSUE THREAD

**Issue by Ig0rizm** [X-Sharp/XSharpPublic#1073]
I have a problem with Extended Expression Match Marker

**test.ch:
`#translate PN(<(pole)>) => GF(<(pole)>)`

**test.prg:
`PN(NAME)`

##Expected:
`GF("NAME")`

##Actual:
`PN(NAME)`

------------------------------------------------------------------------
I use version 2.12.2.0

Same with #XTranslate 
With Regular Match Marker and #command everything works fine.

**Comment by cpyrgas** [comment]
Shouldn't that be like that instead?

#translate PN(<pole>) => GF(<(pole)>)

**Comment by kpa174** [comment]
Of course not. This will result in an error:

error XS9003: Pre-processor: Result Marker 'pole' not found in match list

**Comment by kpa174** [comment]
One more example.
**To Reproduce**
```
#translate PN(<file>, <(field)>) => GF(<file>, <(field)>)
local f := PN(handle,F_NAME)
```
**Expected behavior (xBase ppo)**
```
local f := GF(handle, "F_NAME")
```
Actual behavior (x# ppo)
```
local f := PN(handle,F_NAME)
```

**Comment by cpyrgas** [comment]
Hmm, that's strange, it works fine here. And when I change also the second sample to

#translate PN(<file>, <field>) => GF(<file>, <(field)>)

then it also works as expected (as in the mentioned Expected behavior).

But I must admit I am no expert in the preprocessor, will let Robert further comment on that 9he's currently out of office for a couple days)

**Comment by Serggio** [comment]
Try using ```<"pole">``` on the right

**Comment by kpa174** [comment]
> Try using `<"pole">` on the right
It has no effect.

But the following examples work fine:
```
#translate PN(<file>, <(field)>) => GF(<file>, <(field)>)
local f := PN(handle,F_NAME ) // space before right paranthesis
local n := PN(handle,"F_CODE") // expression
```
Result:
```
local f := GF(handle ,"F_NAME" ) // extra space before comma
local n := GF(handle ,"F_CODE" ) // extra space before comma and before right paranthesis
```

**Comment by cpyrgas** [comment]
Confirmed fixed
