### ISSUE TITLE
Errors in AScan  with XS 2.13.2 Beta

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#1074]
**Describe the bug**
Exception in AScan in parts that always worked
ArgumentException: Der Wert liegt außerhalb des erwarteten Bereichs.

**To Reproduce**
Please run the attached program

**Expected behavior**
AScan should finish without errors

**Screenshots**
XSharp.Error
  HResult=0x80131500
  Message=Der Wert liegt außerhalb des erwarteten Bereichs.
  Source=XSharp.RT
  StackTrace:
 __USUAL:USUALEQUALS (Line: 1421)
 __USUAL:EQUALS (Line: 1249)
 OBJECT:EQUALS (Line: 0)
 ARRAYHELPERS:ASCAN (Line: 21)
 ASCAN (Line: 669)
 BRWERROR (Line: 1092)
 START (Line: 1135)

**Desktop (please complete the following information):**
 - OS: Windows 10
[Program.zip](https://github.com/X-Sharp/XSharpPublic/files/9129928/Program.zip)

**Comment by cpyrgas** [comment]
Thanks! Now I don't understand why I could not reproduce this earlier, but I see it is actually reproducible by calling AScan() with any array, just by supplying the 4th argument:

```
FUNCTION Start() AS VOID
LOCAL a AS ARRAY
a := {1,2,3,4,5}
? AScan(a, {|x| x == 3}, 1, 1

XSharp.Error
Value does not fall within the expected range.

Callstack : 
Boolean XSharp.__Usual.UsualEquals(XSharp.__Usual rhs, System.String op)() 
Boolean XSharp.__Usual.Equals(System.Object obj)() 
static Boolean System.Object.Equals(System.Object objA, System.Object objB)() 
static UInt32 XSharp.RT.ArrayHelpers.AScan(XSharp.__ArrayBase`1[System.Object] aTarget, System.Object element, System.Int32 nStart, System.Int32 nCount)() 
static UInt32 XSharp.RT.Functions.AScan(XSharp.__ArrayBase`1[System.Object] aTarget, System.Object uSearch, System.Int32 nStart, System.Int32 nCount)() 
static System.Void xRuntime.Exe.Functions.Start()()   :  C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg  :  4


```

**Comment by cpyrgas** [comment]
AScan() problem is fixed, but R850 fails now

**Comment by cpyrgas** [comment]
After updating the runtime files, it works fine now! Confirmed fixed.
