### ISSUE TITLE
Possibly wrong change in the SDK in DBServer:FieldGetFormatted()

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1076]
Report from customer:

/===============================================
In DBServer2

METHOD FieldGetFormatted

In line 1637 you will see

SELF:__DataField(wPos):__FieldSpec:Transform( uRetVal )

Shouldn’t it be

uRetVal := SELF:__DataField(wPos):__FieldSpec:Transform( uRetVal )

The way it is it crashes as we expect to get a string back instead of the original field value.
/===============================================

I checked the SDK in VO and indeed has an assignment to uRetVal in this line. Same goes in the vulcan SDK.
In X#, it was originally like that, too, but was changed in July 2019, in this commit: https://github.com/X-Sharp/XSharpPublic/commit/09515832e16e3db7299b25409fd7ca857b3d2d8f

Now the question is, was that change intentional? Did it fix some other problem?

**Comment by RobertvanderHulst** [comment]
Yes, this is an error in the X# code. Will fix that for the next build.

**Comment by cpyrgas** [comment]
Confirmed fixed
