### ISSUE TITLE
StrEvaluate() does not recognise MEMVARs with underscores in their names

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1078]
https://www.xsharp.eu/forum/public-product/3076-memvar-variable-naming

I just ran into something interesting about MEMVAR variable naming. You cannot have underscore as part of the variable name. Here is my sample console program:

```
USING System
USING System.Collections.Generic
USING System.Linq
USING System.Text

FUNCTION Start() AS VOID STRICT

local cFilter, cFilter2 as string
local cPolicy as string
memvar cOpt_Filter_Var
memvar cOptFilterVar

cPolicy := "100L"
cOpt_Filter_Var := cPolicy
cOptFilterVar := cPolicy

cFilter := StrEvaluate('mpolicy == "&cOpt_Filter_Var"')
cFilter2 := StrEvaluate('mpolicy == "&cOptFilterVar"')

console.WriteLine("cFilter: " + cFilter)
console.WriteLine("cFilter2: " + cFilter2)
console.ReadKey()
```

Here is the result:

cFilter:  mpolicy == "cOpt_Filter_Var"
cFilter2: mpolicy =="100L"

**Comment by cpyrgas** [comment]
There's also another problem, the following prints "&abc" instead of "test":

```
FUNCTION Start() AS VOID
PUBLIC abc := "test"
? StrEvaluate1("&abc")

```

**Comment by RobertvanderHulst** [comment]
Chris
I see you are working on this.
May I suggest that you use the _IsIdentifierStartChar and _IsIdentifierPartChar functions to check for acceptible characters instead of Char.IsLetterOrDigit() and a '_'. The compiler uses the same functions as well as the Type() function. That way we keep the logic the same everywhere. 
These functions also accept several special unicode characters as valid part of identifiers.

**Comment by cpyrgas** [comment]
Robert, OK will do.
I found also an incompatibility with VO, VO replaces memvars in the macro only if the memvar contains a string, otherwise it does not replace it. For example VO prints "@abc" for all of the below:

MEMVAR abc := 123
abc := 123
? StrEvaluate("&abc")
abc := TRUE
? StrEvaluate("&abc")
abc := Today()
? StrEvaluate("&abc")

while X# replaces them with the string representation of the memvar contents? Should I change that, to make it compatible with VO? I much prefer X# behavior, but it is incompatible....

**Comment by RobertvanderHulst** [comment]
Chris,
What does FoxPro do ?
What does XBase++ do?
Maybe we can make this dependent on the dialect ?
And of course document the differences...

Robert

**Comment by cpyrgas** [comment]
And another problem

**Comment by cpyrgas** [comment]
Robert,
Can't seem to find such a function in either XBase++ or FoxPro. Maybe there's one doing the same thing with a different name.
I think I'd better leave it as is for now (as the X# implementation makes more sense), and if anyone complains in the future will change it, it is just one line change required.

**Comment by RobertvanderHulst** [comment]
FoxPro and Alaska do need StrEvaluate(). They always perform this operation. Try this with Xbase++ or FoxPro.

```
function main
local cFilter, cFilter2 
local cPolicy 
private cOpt_Filter_Var
private cOptFilterVar
cPolicy = "abc"
cOpt_Filter_Var = cPolicy
cOptFilterVar = cPolicy
cFilter = 'mpolicy == "&cOpt_Filter_Var"'
cFilter2 = 'mpolicy == "&cOptFilterVar"'
? cFilter
? cFilter2
```
Now try to assign a number or a date. Then XBase++ also does not replace the value in the string.
FoxPro behaves the same: it also only replaces string values.
So I think we should do that too.

**Comment by cpyrgas** [comment]
Ah, OK! Will change that, will also make sure the "&" symbol is not removed when a memvar specified is not found (or is not string), because before this was incorrectly removed in this case.

**Comment by cpyrgas** [comment]
Done in https://github.com/X-Sharp/XSharpPublic/commit/04cc2f37add540af100f01295234b71f2dfe1016
