### ISSUE TITLE
Performance Issue when typing . for .and.

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1080]
When working on a large solution, there a re noticeable delays in Visual Studio when typing the first dot for the _.and._ / _.or._ keywords. 

Maybe this is releated to the "enable DOT for instance members" option, that we have enabled.

Here's a screen recording, that shows this issue. It takes ~7 seconds after the keypress before the dot get's shown in the editor:
![TypingAnd](https://user-images.githubusercontent.com/9860916/181034543-7c46ec80-5422-4c15-97a9-de740c3beaeb.gif)

**Comment by cpyrgas** [comment]
Will leave this up to @VolkmarR to confirm.

**Comment by VolkmarR** [comment]
@cpyrgas would it be possible to get a beta build, so I could verify this issue?

**Comment by RobertvanderHulst** [comment]
The beta will be released tonight

**Comment by RobertvanderHulst** [comment]
Volkmar,
Can you conform that this is fixed ?

**Comment by VolkmarR** [comment]
It is fixed in the new version
