### ISSUE TITLE
Code Completion shows invalid entries

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1081]
Code completion on a class instance should not show static method
![image](https://user-images.githubusercontent.com/9860916/181049489-608d7bd6-8155-494a-94e8-e7975bba14f2.png)

Code completion on type should not show methods
![image](https://user-images.githubusercontent.com/9860916/181049826-e734aa47-12c4-4a61-8292-fbb7f5410a32.png)

Test project:
[XSharpTestsCodeCompletion.zip](https://github.com/X-Sharp/XSharpPublic/files/9191290/XSharpTestsCodeCompletion.zip)

**Comment by cpyrgas** [comment]
Problem fixed, although typing the dot produces a completion list even if option "Allow DOT for instance members" is disabled.
But I think this problem is probably very minor, so confirmed fixed.
