### ISSUE TITLE
Extend matching keyword support to return

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1089]
Currently the new matching keyword support works for class/end class, if/else/endif, while/end, ...

It would be useful to extend the support also to the _return_ and  _exit_ keywords.  

The _return_ keyword should highlight the method.
![image](https://user-images.githubusercontent.com/9860916/183063781-715d8d19-e3f7-4cb1-af4f-6d92e5d151e7.png)

The _exit_ keyword should highlight the loop.
![image](https://user-images.githubusercontent.com/9860916/183063585-a391e5f0-d2e2-4616-bb35-f92dbbdd2c50.png)

I also noticed a small bug with the matching, when _end method_ is used. In that case, the _end  method_ matches the _class_ keyword.
![image](https://user-images.githubusercontent.com/9860916/183064334-6e7f0999-0720-4ed7-b6c2-dfa3e9277a59.png)

**Comment by RobertvanderHulst** [comment]
Thanks, valuable suggestions. I will see what I can do.

**Comment by RobertvanderHulst** [comment]
This was already added in 2.15 or 2.16
