### ISSUE TITLE
Inlist works different for XSharp Beta Version 2.13.0.5

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#1095]
**Describe the bug**
In VO and previous XS-Version Inlist with Strings worked with Exact string comparisons although the documentation told different

local _cFormat := "BEZ" as string

if InList (_cFormat, "VOLL", "FIBU", "BEZZUS", "BEZZUSORT", "BEZZUSORTSTR", "BEZZUSSTRORT", "BEZZUSSTR")
    // XSharp Beta Version 2.13.0.5 return true

    // VO and previous XSharp versions returned false

**To Reproduce**
Attached example which should be run once with the new compiler and the new runtime (8/2022) and then with the old compiler and old runtime (in our case compiler from 6/2022 and runtime from 3/2022)
[ConsoleTests.zip](https://github.com/X-Sharp/XSharpPublic/files/9315640/ConsoleTests.zip)

**Comment by RobertvanderHulst** [comment]
Arne,
What I see is that the function now follows the "SetExact" rules when comparing the values. So when Set Exact is set to FALSE then Inlist will compare just as you would expect.
If you want to enforce the SetExact() comparison rules you should either call InListExact() or set SetExact() to TRUE.
I am not sure if we have changed anything in this area.
Our implementation of InList and InListExact look like this:

```
/// <include file="VoFunctionDocs.xml" path="Runtimefunctions/inlist/*" />
FUNCTION InList(u AS USUAL, uValueList PARAMS USUAL[]) AS LOGIC
    RETURN _InListWorker(u, uValueList, {x,y => x = y})

/// <include file="VoFunctionDocs.xml" path="Runtimefunctions/inlistexact/*" />
FUNCTION InListExact(u AS USUAL, uValueList PARAMS USUAL[]) AS LOGIC
    RETURN _InListWorker(u, uValueList, {x,y => x == y})
```
For the codeblock inside Inlist the compiler generates a call to 

`__Usual.__InexactEquals(x, y)`
And the code inside __InexactEquals does this:

```
STATIC METHOD __InexactEquals( lhs AS __Usual, rhs AS __Usual ) AS LOGIC
        IF lhs:IsString .AND. rhs:IsString
            RETURN __StringEquals( lhs:_stringValue, rhs:_stringValue)
        ELSE
            RETURN lhs:UsualEquals(rhs, "=")
        ENDIF
```
__StringEquals does take the Setting of SetExact into account.

**Comment by cpyrgas** [comment]
Robert, i think this is a (VO compatibility) bug in X#, because for the following VO prints FALSE, FALSE, while X# prints FALSE, TRUE:


```
FUNCTION Start() AS VOID
LOCAL _cFormat := "BEZ" AS STRING
SetExact(TRUE)
? InList (_cFormat, "VOLL", "FIBU", "BEZZUS", "BEZZUSORT", "BEZZUSORTSTR", "BEZZUSSTRORT", "BEZZUSSTR")
SetExact(FALSE)
? InList (_cFormat, "VOLL", "FIBU", "BEZZUS", "BEZZUSORT", "BEZZUSORTSTR", "BEZZUSSTRORT", "BEZZUSSTR")

```

**Comment by cpyrgas** [comment]
Robert, the problem was introduced in this commit: https://github.com/X-Sharp/XSharpPublic/commit/c2a434f346ee61df6fc0370bca11ad2ad626f858

**Comment by ArneOrtlinghaus** [comment]
My test program attached shows that something has changed between the two X#versions. I was also surprised that the programs work like this. Therefore I tested with VO.

**Comment by RobertvanderHulst** [comment]
I will fix this for the next installer. 
The problem seems to be that the original code was comparing the usual value with the array element as `u = a[i]`
The new code is comparing the array element with the usual: `a[i] = u`.
Since the comparison is reversed a comparison of an array element with the value `"BEZZUS"` with the value `"BEZ"` now returns true because only 3 characters are compared. where originally "`BEZ"` was compared with `"BEZZUS"` which returns false because the right hand side is longer than the left hand side.
I changed this to simplify the code (there was a duplicate loop inside _InListWorker). Sorry for the inconvenience.

**Comment by ArneOrtlinghaus** [comment]
Thanks. I understand how difficult it is to make any enhancements with this type of history as VO has. 
I am normally disposed to make beta testing of X# Versions early. 
Fortunately we now have a bigger library of unit tests. Although it covers only a percentage of our code it often shows some undesired behavior. 
I will be off the next days and will be back on 23 August.  I can then test a new version.

**Comment by cpyrgas** [comment]
Confirmed fixed
