### ISSUE TITLE
Incorrect runtime error message with ambiguous late bound call

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1096]
The following code:

```
FUNCTION Start() AS VOID
LOCAL u AS OBJECT
u := TestClass{}
TRY
	u:Test(123)
CATCH e AS Exception
	? e:ToString()
END TRY

CLASS TestClass
	METHOD Test(o AS OBJECT) AS VOID
		? "object"
	METHOD Test(o AS USUAL) AS VOID
		? "usual"
	METHOD Test(o AS USUAL , n := 1 AS INT) AS VOID
		? "usual and 2nd default param"
END CLASS
```

at runtime produces an exception:

```
Description :   No exported method 'TEST'
Subsystem :     BASE
GenCode :       EG_NOMETHOD No exported method
FuncSym :       DoSend
Severity :      ES_ERROR
Can Default :   False
Can Retry :     False
Can Substitute :        False
Argument Number :       2
Argument :      cMethod
Arguments :     {TestClass,TEST,XSharp.__Usual[]}
Stack Trace :
 OOPHELPERS:DOSEND (Line: 0)
 __INTERNALSEND (Line: 0)
 START (Line: 5)
```

But this is misleading, because the method does exist, the problem instead is that the call is ambiguous. Stepping through the debugger, the following **handled** exceptions are thrown in succession:

```
System.Reflection.AmbiguousMatchException
Ambiguous match found.
```

```
XSharp.Error
Method is overloaded, Send() is not supported for overloaded methods
```

```
XSharp.Error
No exported method
```

**Comment by RobertvanderHulst** [comment]
I have solved this by adding separate CATCH clauses for XSharp.Error. These are obviously generated by the runtime itself and there is no need to do additional processing on these errors.
On top of that I have modified the error message that is generated when the runtime does not know which overload to call. The # and prototypes of the methods/functions is included in the error message.

**Comment by cpyrgas** [comment]
That's much better, but the message in this case is not quite right. The real problem in the code, is that there's a 3rd overload with a default param, while the error message mentions two overloads, the other two:

```
Description :   Method is overloaded, Cannot determine the right overload to call.
Found 2 overloads
1. TestClass:Test(o AS Object)
2. TestClass:Test(o AS USUAL)

Subsystem :     BASE
GenCode :       EG_AMBIGUOUSMETHOD Method is overloaded, Cannot determine the right overload to call.
FuncSym :       TEST
Severity :      ES_ERROR
Can Default :   False
Can Retry :     False
Can Substitute :        False
Argument Number :       1
Argument :      MethodName
Arguments :     {TestClass:Test}
Stack Trace :
 OOPHELPERS:FINDBESTOVERLOAD (Line: 0)
 OOPHELPERS:SENDHELPER (Line: 0)
 OOPHELPERS:DOSEND (Line: 0)
 __INTERNALSEND (Line: 0)
 START (Line: 5)
```

And actually if only those two overloads were defined, then there would be no runtime error, instead the call would be made to the "object" overload, ignring the "usual" one (which behavior is wrong, but maybe better not touch it now). It's only when introducing the 3rd overload with the default param that the error starts happening, but this overload is not being mentioned in the message.

**Comment by cpyrgas** [comment]
Still getting the same issue as mentioned in https://github.com/X-Sharp/XSharpPublic/issues/1096#issuecomment-1216937099. Not sure if my version of the compiler is not correct, but I have updated the codeanalysis dll in the GAC. Maybe it's better to wait for a full installer?

**Comment by RobertvanderHulst** [comment]
If you have recompiled the runtime then you should see that there are now 3 overloads in the list.
There still is an error because `u:Test(123)` can match all 3 of the overloads

**Comment by cpyrgas** [comment]
Ahhh, right, I did not notice this previously. My problem was the inconsistency that the code throws an exception with the 3 overloads, while it silently runs with no errors with the 2 overloads (while there still is an ambiguity), but better leave this as it is, it's a very complicated area in the runtime, so let it be like that. So confirmed fixed.
