### ISSUE TITLE
SetDefault()/GetDefault() incompatibilities with VO

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1099]
(VO dialect)

```
FUNCTION Start() AS VOID
SetDefault("c:\folder\")
? GetDefault() // "c:\folder\" in both, OK
SetDefault("c:\folder")
? GetDefault() // "c:\folder\" in VO, "c:\folder" in X#
SetDefault("c:\some\folder")
? GetDefault() // "c:\some\folder\" in VO, "c:\some\folder" in X#

SetDefault("c:\")
? GetDefault() // "c:\" in both, OK
SetDefault("c:")
? GetDefault() // "c:" in both, OK
SetDefault("c")
? GetDefault() // "c:" in VO, "c" in X#

SetDefault("")
? GetDefault() // "" in both, OK
```

**Comment by RobertvanderHulst** [comment]
Let's make sure that the results in Xbase++ and other dialects (if they support this too?) is also correct.
Especially the case where SetDefault is called with "C" and GetDefault() returns "C:"

**Comment by cpyrgas** [comment]
Ah, good point. Alaska has the same behavior with the current X# one, it just accepts and returns whatever string was passed to it. 

VFP does not seem to make any sense at all. Set("DEFAULT") returns always "c", no matter what is passed to SET DEFAULT TO. Set("DIRECTORY") always returns the previous setting, in other words SET DEFAULT TO seems to be ignored, when passed "c", "c:", or "c:\". With a valid path specified, then Set("DIRECTORY") does return that path, with the last backslash truncated, and this is already implemented in the X# runtime.

VO's behavior with "c", "c:" and "c:\" does not make sense either, I think it's the usual semi-random behavior of VO functions.

My suggestion would be to just make sure SetDefault() applies a trailing backslash when there's a path specified for the VO dialect (which is the opposite to what the VFP dialect currently does) and be done with it. If anybody really depends on this insane behavior with c, c: and c:\, then we can adjust it.

**Comment by cpyrgas** [comment]
The fix is not entirely correct, as it adjusts the behavior for all dialects (except for VFP). The new behavior should be implemented ONLY for the VO dialect.
It's of course not a showstopper for releasing 2.13 now though.

**Comment by RobertvanderHulst** [comment]
> The fix is not entirely correct, as it adjusts the behavior for all dialects (except for VFP). The new behavior should be implemented ONLY for the VO dialect. It's of course not a showstopper for releasing 2.13 now though.

The official 2.13.0.7 installer contains the modified code that only adds the backslash for the VO and Vulcan dialects
