### ISSUE TITLE
Bogus warning about ambiguous methods, with NEW ToString()

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1101]
Following reports

warning XS9043: 'ToString' is ambiguous. Could be Method 'TestClass.ToString()' in xRuntime or Method 'object.ToString()' in mscorlib. Using the first one.

But since the declared method in the base class is a NEW one, the base one is effectively hidden, so there should be no warning.

```
FUNCTION Start() AS VOID
LOCAL o AS TestClass
o := TestClass{}
o:ToString()

CLASS TestClass
NEW METHOD ToString() AS STRING
RETURN "123"
END CLASS

```

**Comment by RobertvanderHulst** [comment]
Ok, this does NOT happen in the Core dialect but only in one of the other dialects.

**Comment by RobertvanderHulst** [comment]
Chris,
Can you test the various compiler related issues. The latest Action on Github contains the new DLLs. All tests are running without errors (at least online) now.

**Comment by cpyrgas** [comment]
Confirmed fixed.
