### ISSUE TITLE
VS 2022 and XS 2.13.0.7 XSharpSetupFox2.13.0.7.exe First builds not starting

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#1104]
I have some undesired effects when starting the first compilations in certain solutions. 
 
When trying to build a project or the solution first nothing happens. I can even wait an hour. There is no xscompiler in the process list. (Screenshots 1 and 2)
 
Then I try to leave the program and it says “The build must be stopped”. After confirming the build process starts. (Screenshot 3)  Similar behavor with Ctrl Break when trying to compile single projects. 
 
Afterwards every build process starts normal. So I can work normally afterwards. 
 
This does not happen with every solution. It happens with our solutions ACSLIB and RADIX, but not with the solution IOS which contains fewer projects. 
 
In this case Devenv seem to wait with prox. 0,4% cpu consumation and two threads showing some activity (screenshot 4)
 
After making Ctrl Break and compile the compiler appears normally in the processes. So it seems as if there are some problems starting the compiler initially. 
 
 
If you need further info we can look what happens on my computer. 
 
Screenshots as sent by email to Chris and Robert.

**Comment by ArneOrtlinghaus** [comment]
Volkmar has installed the version on his computer and the same happens. So probably it is not an installation issue. If it helps, I can give you a complete solution for testing as it seems to be solution depending.

**Comment by VolkmarR** [comment]
I've installed the new version XSharpSetupFox2.13.1.1 and can confirm, that this issue is now fixed.
