### ISSUE TITLE
Member completion and parameter tip not working in very specific cases

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1110]
Copy/paste this:

local n as int
n:CompareTo

now type an opening paren "(", there is not parameter tip shown. 

Now type also the closing paren and a colon, so you end up with:

n:CompareTo():

but no member completion list is shown.

With other methods, like n:Equals() or n:ToString(), the above does work as expected.

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
Confirmed fixed.
