### ISSUE TITLE
Intellisense not available for variables defined in CATCH clauses

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1118]
Type or copy paste the following. The tooltip over "oException" shows "UNDECLARED" and there's no member completion on it.

```
FUNCTION Start() AS VOID STRICT
    try
    catch oException as System.Exception
          oException:
    end try

```

**Comment by cpyrgas** [comment]
Problem happens in both VS2017 and VS2019

**Comment by cpyrgas** [comment]
Sample solution, just in case:

[ConsoleApplication21.zip](https://github.com/X-Sharp/XSharpPublic/files/9539682/ConsoleApplication21.zip)

**Comment by RobertvanderHulst** [comment]
> Problem happens in both VS2017 and VS2019

The code that scans for local variables is in the X# codemodel project that is the same for all versions of X#.

**Comment by cpyrgas** [comment]
Still not working, or actually working under specific conditions. FOr example:

- NOT working:

```
function test()
local n as int
try
    n := 1
catch e as Exception
    e:
end try
```

- Also NOT working:

```
function test()
try
    local n as int
    n := 1
catch e as Exception
    e
end try
```

- But this one, DOES work well:

```
function test()
try
    local n as int
catch e as Exception
    e:
end try
```

**Comment by cpyrgas** [comment]
Confirmed fixed!
