### ISSUE TITLE
Default() function with NULL_OBJECT incompatibility with VO

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1119]
Following code prints TRUE in all cases in VO, while in X# Default() changes the value of the usual, so the final two checks print FALSE:

```
FUNCTION Start() AS VOID
LOCAL u AS USUAL
u := NULL_OBJECT

? IsNil(u) // TRUE
? u == NULL_OBJECT // TRUE

Default(@u , "test")

? IsNil(u) // FALSE
? u == NULL_OBJECT // FALSE

```

**Comment by cpyrgas** [comment]
This looks like really strange behavior, but apparently the VOSDK in places relies on it, as in the ComboBox:AddItem() method, where it causes this sample to crash with an invalid cast exception:

[TestComboBox.zip](https://github.com/X-Sharp/XSharpPublic/files/9540750/TestComboBox.zip)

**Comment by cpyrgas** [comment]
Still getting the same behavior, maybe the new runtime was not included in the latest installer?

**Comment by RobertvanderHulst** [comment]
This was fixed today AFTER creating the installer

**Comment by cpyrgas** [comment]
Ah OK, makes sense then!

**Comment by cpyrgas** [comment]
Confirmed fixed
