### ISSUE TITLE
VS option "Rebuild intellisense database" causes VS to restart with no warning

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1120]
When the "Rebuild intellisense database" option is selected, VS totally shuts down and restarts (without reopening the previous solution).

Not sure if the restart is intended, or causes by a crash, but if it is intended, then I think a warning should be shown first, that VS will shut down.

It happens with any solution it seems.

**Comment by RobertvanderHulst** [comment]
Restarting VS is intentional. However the current solution should be reopened.

**Comment by cpyrgas** [comment]
Robert, I think this needs a Yes/No question box, not just a message that the restart is now inevitable :)

**Comment by RobertvanderHulst** [comment]
Chris,
What do you think this does ?
`
if (await VS.MessageBox.ShowConfirmAsync("Rebuild Intellisense Database", "This will close the current solution, shutdown Visual Studio and reopen the current solution.\r\nOK to restart Visual Studio?"))
`

**Comment by cpyrgas** [comment]
Ah right :)

**Comment by cpyrgas** [comment]
Looking good, except for that VS2017 does not reopen the solution, after the restart (it does reopen fine in VS2019). But let's ignore that, confirmed fixed.
