### ISSUE TITLE
Icons (native resources) are not loaded in some cases

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#1123]
Here is the sample solution:

[TestIconsApp.zip](https://github.com/X-Sharp/XSharpPublic/files/9546108/TestIconsApp.zip)

There are 2 icons defined in 2 rc-files. One of them is loaded perfectly (named "deflink"), the other one is not (named "CancelIcon").
If you put the "CancelIcon" definition in the same rc-file as "deflink", it will work. If defined separately (as it should be), no.

PS. X# 2.13.2.0

**Comment by cpyrgas** [comment]
That's because the CancelIcon.rc file is in UTF8 format. Unfortunately the resource compiler from MS cannot handle this and instead treats the BOM of the file as part of the resource's name, which ends up with an unreadable one. Please change the file to ansi and it should work well.

**Comment by Serggio** [comment]
Thank you, Chris!
