### ISSUE TITLE
Invalid LookupAccountSid function signature (Win32)

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1125]
**VOSDK\VOWin32APILibrary\WinBase.prg**
```
_DLL FUNC LookupAccountSid(lpSystemName AS PSZ, Sid AS PTR, Name AS PSZ,;
	cbName AS DWORD PTR, ReferencedDomainName AS PSZ,;
	cbReferencedDomainName AS DWORD PTR, peUse AS WORD) AS LOGIC PASCAL:ADVAPI32.lookupLookupAccountSidA
```
The **peUse** parameter should be **DWORD PTR** instead of **WORD** (same as in LookupAccountName function signature).

**Comment by RobertvanderHulst** [comment]
Will change that in the next build. This won't break things. I think nobody has ever used this so far (or else they would have reported the issue).
The SDK docs are not very clear btw:
`[out]           PSID_NAME_USE peUse`
You will have to know that PSID_NAME_USE  is an enum and will have to "guess" that this enum is 32 bits...
I see that the last 3 Sid defines do not exist. Will add these as well.
```
SidTypeComputer
SidTypeLabel
SidTypeLogonSession

```

**Comment by leon-ts** [comment]
Robert,
This error came with VO. There's also an incorrect signature. Because of this, my team had to write their own definition with the correct parameter. We named it the same, but with an underscore at the end of the name: LookupAccountSid_. We have been using it for a long time, where clients order integration with ActiveDirectory.

**Comment by leon-ts** [comment]
Robert,
Maybe then you will add a couple more definitions from the same section?
```
INTERNAL _DLL FUNCTION ConvertSidToStringSid(pSid AS BYTE PTR, pcStringSid AS PSZ PTR) AS LOGIC PASCAL:Advapi32.ConvertSidToStringSidA
INTERNAL _DLL FUNCTION ConvertStringSidToSid(pStringSid AS PSZ, pSid AS BYTE PTR) AS LOGIC PASCAL:Advapi32.ConvertStringSidToSidA
```

**Comment by cpyrgas** [comment]
Confirmed fixed
