### ISSUE TITLE
Empty string in Intellisense tooltips (XML documentation)

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1127]
If the description of an entity is formatted in separate lines in the Summary section, then an empty line appears at the end of the text when the Intellisence hint is displayed (see screenshot). Apparently the last line separator is not discarded. If the Summary section is formatted as a single line, then the tooltip is displayed correctly.

**Screenshot:**
![screenshot1](https://user-images.githubusercontent.com/64518775/190967946-0d971673-a8ef-4bbc-abb5-5a2b6a1a47de.png)

**Example code:**
```
/// <summary>Test1 summary.</summary>
FUNCTION Test1() AS VOID
	RETURN
	
/// <summary>
/// Test2 summary.
/// </summary>
FUNCTION Test2() AS VOID
	RETURN
```

**X#:** 2.13.2.2
**IDE:** VS 2019 (16.11.19)

P.S. I upgraded to X# 2.13.2.2 from version 2.9.1.1, in which both ways of formatting XML documentation were displayed without an empty line.

**Comment by cpyrgas** [comment]
Confirmed fixed
