### ISSUE TITLE
Missing XMLHelp Warning for Compiler generated Code

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1128]
When enabling the generation of the XMLDoc file, I get warnings for missing xml comments for compiler generated code. 

In the example solution, I'll get the following three warnings:

    Missing XML comment for publicly visible type or member 'Lib.Functions.$Init1()'
    Missing XML comment for publicly visible type or member 'Lib.Functions.$Exit()'	
    Missing XML comment for publicly visible type or member 'TestClass.TestClass()'

The first two warnings are caused by the generated init and exit functions. The third is caused by the automatically generated clipper contructor (/vo16 option).

Generating XMLComments for this generated code should fix this issue. The comments can be empty or contain the member name.

[XSharpTestsXMLCommentsCompilerGenerated.zip](https://github.com/X-Sharp/XSharpPublic/files/9598001/XSharpTestsXMLCommentsCompilerGenerated.zip)

**Comment by RobertvanderHulst** [comment]
Volkmar,
We can choose to generate empty XML comments, or XML comments with the <exclude /> token, so these functions and constructors will also not be included in a help file (if your tool supports that). What do you prefer?

**Comment by VolkmarR** [comment]
Personally I would prefer XML Comments with the token. Maybe it is even possible to generate some helpful comments like "Method generated to init the Lib assembly" for the init?

An alternative could also be to add the Pragma to the generated files to disable the warning.

**Comment by RobertvanderHulst** [comment]
The $Init1, $Init2 and $Init3 methods now have the comment: Compiler generated helper method that calls Init Procedures.
The $Exit method now has the comment: Compiler generated helper method that calls Exit Procedures.
All other $ methods have the comment: Compiler generated helper method.

**Comment by cpyrgas** [comment]
Confirmed fixed
