### ISSUE TITLE
Delegate with argument having default value results in "null reference" exception in compiler

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#1129]
```DELEGATE Test(nParam := 0 AS INT) AS VOID```

leads to:
```XS9999	An internal compiler error has occurred: 'Object reference not set to an instance of an object.',    at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationRT.ExitParameter(ParameterContext context)```

X# 2.13.2.2
Worked fine in 2.9.1.1

**Comment by cpyrgas** [comment]
Looks, fixed, but when the DELEGATE has a default param, then shouldn't this also be enforced to the delegated function/method as well? Because currently the code below does not report any errors, even though the function does not have the default param that the delegate specifies:

```
DELEGATE TestDelegate(nParam := 0 AS INT) AS INT
FUNCTION TestFunc(n AS INT) AS INT
RETURN 100+ n * 2

FUNCTION Start() AS VOID STRICT
LOCAL del AS TestDelegate
del := TestFunc
? del:Invoke(123)
? del:Invoke()
```

**Comment by RobertvanderHulst** [comment]
Chris,
There is no need for the function to have the same default.
At the place where the delegate is invoked with missing parameter values (`del:Invoke()`) then the compiler inspects the delegate and copies the values of the default parameters in the delegate definition to the method call. The function is not involved with this at all.
