### ISSUE TITLE
Extra type members in dropdown list

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1130]
If some library X is included to the project as a DLL, then when you type a dot after the name of some type, VS displays, in addition to the static members of this type, also types from the X library (marked with a vertical red line in the screenshot.).

**Example:**
![screenshot1](https://user-images.githubusercontent.com/64518775/191005249-ceca3f69-be9d-403b-b3ea-540b75c0742c.png)
Note that the types Test1, Test2, and Test3 are contained in the ClassLibrary.

**Test solution:**
[TestConsoleApplication.zip](https://github.com/X-Sharp/XSharpPublic/files/9598399/TestConsoleApplication.zip)

**X#:** 2.13.2.2
**IDE:** VS 2019 (16.11.19)

**Comment by cpyrgas** [comment]
Confirmed fixed
