### ISSUE TITLE
Extension methods in Goto definition, Peek definition, QuickInfo tips and parameter tips

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1131]
Extension methods are included in the code completion list, but not found for Goto Definition, Peek definition, QuickInfo tips and Parameter Tips. See AddFilesToNewZip() function in attached example. CreateEntryFromFile is an extension method.

[DevTeamTest.zip](https://github.com/X-Sharp/XSharpPublic/files/9598530/DevTeamTest.zip)

**Comment by cpyrgas** [comment]
Doesn't seem to work fully, I created a small test containing the following code, and even though the info tooltip on "CreateEntryFromFile()" works correctly, neither Peek or Goto definition work on it:

```
FUNCTION Start() AS VOID
    LOCAL oZip AS System.IO.Compression.ZipArchive
    oZip:CreateEntryFromFile("asd","zxc")
```

[ConsoleApplication26.zip](https://github.com/X-Sharp/XSharpPublic/files/10019424/ConsoleApplication26.zip)

**Comment by cpyrgas** [comment]
Confirmed fixed
