### ISSUE TITLE
#pragma warning restore XS0414 seems to restore all warnings

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1133]
When building this code file, I get an XS1591 warning. 

    #pragma warning disable XS1591
    public class ClassWithPragma
        #pragma warning disable XS0414
        private test as logic
        #pragma warning restore XS0414 // <-- remove this line and the XS1591 warning is gone
        public method Execute() as void
            return
    end class

If I remove the code line with the comment and recompile the project, the XS1591 warning is ignored as I would expect it. 

It seems, that the pragma restore ignores the warning number and enables all both disabled warnings.

Example solution: [XSharpTestsPragmaRestore.zip](https://github.com/X-Sharp/XSharpPublic/files/9600432/XSharpTestsPragmaRestore.zip)

**Comment by cpyrgas** [comment]
Also normally this code should report another warning:

warning XS0169: The field 'ClassWithPragma.test' is never used

but it is not reported. If all #pragmas as removed, then it is now reported as expected

**Comment by cpyrgas** [comment]
Confirmed fixed
