### ISSUE TITLE
No parameter tooltips in a multiline expression

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#1135]
```
LOCAL nStart := 2 AS DWORD
LOCAL nCount := 3 AS DWORD

? SubStr3("test";
		, nStart;
		, nCount;
		)
```

If you hover over the nStart and nCount arguments of SubStr3, the tooltip will not appear.

**Comment by RobertvanderHulst** [comment]
Hovering over nStart and nCount should show the tooltip for the locals. However, I can confirm that typing a comma on the second or third lines does not bring up the parameter tips

**Comment by cpyrgas** [comment]
Confirmed fixed
