### ISSUE TITLE
Feature request: improved debugger current line indication

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1136]
In X# 2.13.2.2, in debug mode, the current line is not completely filled with background. This makes it difficult to visually identify the current line. Please highlight the entire line being debugged. For example, how it is done in C#.

**An example of what it looks like now (X#):**
![screenshot2](https://user-images.githubusercontent.com/64518775/191226892-38be5893-ef7a-4727-8f16-e6409a10bacf.png)

**Preferred visualization example (C#):**
![screenshot1](https://user-images.githubusercontent.com/64518775/191227440-bd0774a1-dac7-47a8-b801-8193d598a2e5.png)

**Comment by cpyrgas** [comment]
Confirmed fixed
