### ISSUE TITLE
Strange behaviour with mark of a word with mouse double click in debug mode and version 2.13.2.2

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1138]
During debugging if I double click on code I have a strange beaviour.
e.g.
`oCurrentControl:ServerTyped`
-> If I double click within ServerTyped, everything incl. oCurrentControl is marked

e.g.
`oCurrentControl:_ServerTyped`
-> If I double click within _ServerTyped, only  "ServerTyped" without the underscore is marked.

If I'm not in debug mode I have the normal expected bahaviour

**Comment by RobertvanderHulst** [comment]
Hansjoerg,
What do you see as the "normal expected behaviour" ?

**Comment by hpetriffer** [comment]
In the first case "ServerTyped" is marked
in the second case "_ServerTyped"

**Comment by RobertvanderHulst** [comment]
> In the first case "ServerTyped" is marked in the second case "_ServerTyped"
We changed this to make sure that if you hover your mouse in the debugger over a field access or property access that the whole expression is evaluated, and not only the part of the expression until the ':' or '.'.
This was a problem that your colleague Volkmar reported.
Unfortunately this has the side effect.
The fact that the underscore is not selected is an error on our side. We can fix that.
But the other thing (the selection of the while expression) will have to remain like it is until we have completed our X# expression evaluator for the VS Debugger.

**Comment by hpetriffer** [comment]
Ok thanks

**Comment by cpyrgas** [comment]
Confirmed fixed

**Comment by cpyrgas** [comment]
Well, problem with the underscores is fixed, but I think ticket should remain open, until (in a future build) a double-click does not select the full expression while in a debugging session anymore.

**Comment by RobertvanderHulst** [comment]
Ok, but then I'll add this to another project too, because I want to close the project asap.

**Comment by RobertvanderHulst** [comment]
Ok, I managed to fix this, by inspecting the callstack. When the callstack reveals that the word delimiter is searched from a ToolTip then the word `oCurrentControl:_ServerTyped `will be selected as a whole. When the callstack does not contain a trace from the tooltip then the ':' is treated as a delimiter and double clicking on `_ServerTyped ` will only select that word.

**Comment by cpyrgas** [comment]
Confirmed fixed!
