### ISSUE TITLE
Ctrl+Space (Edit.CompleteWord) seems to work only after "." or ":" in 2.13.2.2

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1140]
Ctrl+Space works only directly after "." or ":". If I begin to write the methodname and press after that CTRL+Space I don't get any hints

e.g. here it is working
`return self:oGridView:`
![image](https://user-images.githubusercontent.com/20905638/191665247-e6b42869-9ba0-4c96-a64d-3f03d71455e7.png)

e.g. here it is not working
![image](https://user-images.githubusercontent.com/20905638/191665201-a1e100c0-4e32-41ae-8e29-24a8f3312ce1.png)

**Comment by RobertvanderHulst** [comment]
Cannot reproduce this anymore.

**Comment by cpyrgas** [comment]
I still see the problem, pressing Ctrl+Space with the care after "self"te" does not show the member completion list

```
class testclass
    method test() as void
        self:te
end class

```

**Comment by RobertvanderHulst** [comment]
The problem with this code was that because the last token is partial "Te".
I will change lookup code to allow a partial name matches for the last token in the list of tokens ("self", ":" and "te" in this case)

**Comment by cpyrgas** [comment]
Confirmed fixed
