### ISSUE TITLE
Wrong autoindent during typing with the following code 

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1142]
With the following settings in Identation
![image](https://user-images.githubusercontent.com/20905638/191702671-60c85a6a-1474-4aa3-a930-7f5d491ccb91.png)
and this code
```
/// <summary>
/// Browser
/// </summary>
class Brw 
    public method Delete() as logic
// x
        if !self:oGridView:IsDataRow(self:oGridView:FocusedRowHandle)
            return false
        endif


end class
```
If you press enter at the end of "if !self:oGridView:IsDataRow(self:oGridView:FocusedRowHandle)" than you get 
![image](https://user-images.githubusercontent.com/20905638/191702961-bede3c23-2666-4bf8-89e0-0dbb6f1e2c06.png)
The identation problem has something todo with the position of the comment before the if statement. It happens also if there is an empty line with no spaces

**Comment by cpyrgas** [comment]
Confirmed fixed
