### ISSUE TITLE
Some oddities in the behavior of the VS editor when creating automatic indents

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1143]
When editing text in the VS editor, there are some oddities when creating automatic indents with the **Tabs = Smart** setting enabled. To visually show what happens, I recorded a short video (attached). The video shows the pressed keys (for better analysis, it is recommended to turn on slow playback). Also attached a screenshot of the settings.

**IDE:** VS 2019 (16.11.19)
**X#:** 2.13.2.2

**Indentation Settings (Tabs = Smart):**
![screenshot1](https://user-images.githubusercontent.com/64518775/191969594-c31ccd4f-b388-44bd-aeda-50bcf11d8545.png)

**Video:**
[ScreenRecorderProject1.zip](https://github.com/X-Sharp/XSharpPublic/files/9633948/ScreenRecorderProject1.zip)

**Discussion topic on the X# forum:**
[https://www.xsharp.eu/forum/welcome/3186-indentation](https://www.xsharp.eu/forum/welcome/3186-indentation)

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
All problems shown in the video confirmed fixed
