### ISSUE TITLE
Identifier highlighting in VS Editor hangs in certain situation

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1145]
With a certain sequence of actions, the highlighting of identifiers stops working, hanging on its last state. Only closing the tab helps.

In the following video, I demonstrated how to reproduce this:
[ScreenRecorderProject1.zip](https://github.com/X-Sharp/XSharpPublic/files/9654578/ScreenRecorderProject1.zip)

**IDE:** VS 2019 (16.11.19)
**X#:** 2.13.2.2

**Comment by leon-ts** [comment]
Addition:
The problem described above can be reproduced more simply than I showed in the video. It is enough to highlight the identifier, then move the mouse cursor over the vertical scrollbar (map mode) of the document.

**Comment by RobertvanderHulst** [comment]
We have used the feature from the VS Community Toolkit.
The same feature is used in the pkdef support from Mads Kristensen. I see the problem in that extension too.
I have created a ticket here:
https://github.com/VsixCommunity/Community.VisualStudio.Toolkit/issues/385

**Comment by RobertvanderHulst** [comment]
I fixed this in the Community.VisualStudio.Toolkit

**Comment by cpyrgas** [comment]
Confirmed fixed
