### ISSUE TITLE
Compiler rule for DO does not recognize &

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1147]
The following code is not properly recognized by the compiler

```
cFunction := "DoSomething"
DO &cFunction
```
The DO rule is declared as

` D=DO Id=identifier (WITH ArgList=argumentList)?    end=eos`

We should probably add `(Amp=AMP)?` before Id=identifier and handle that in the parser

**Comment by RobertvanderHulst** [comment]
See https://www.xsharp.eu/forum/public-vfp/3201-searching-for-a-solution-with-do-varname

**Comment by cpyrgas** [comment]
Confirmed fixe
