### ISSUE TITLE
Enforce (optionally) the usage of override/new modifers

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#115]
See https://www.xsharp.info/forum/private-product/1379-tabcontrol#10087

If the compiler had enforced the use of the OVERRIDE modifier when overriding a base method, errors would had been thrown if the base method signature changed, preventing unexpected runtime behavior.

We cannot make the compiler always enforce this, but maybe we should implement that optionally, with a compiler switch at a later build.

**Comment by RobertvanderHulst** [comment]
COrrection: the checkin fixes 104 and not 115
