### ISSUE TITLE
Form designer event handler methods strange code creation

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1152]
When creating a new event handler in the VS form designer, the output code looks like this below. So there's zero tabs for the first line (the "METHOD" line), 3 tabs indentation for the "RETURN" line and 2 tabs for the "END METHOD" line.

The indentation options in the editor do not seem to have an effect on that, the event handlers are always created like that.

```
BEGIN NAMESPACE WindowsFormsApplication40
    
    PUBLIC PARTIAL CLASS Form3 ;
        INHERIT DevExpress.XtraEditors.XtraForm
        
    public constructor() strict
        
        InitializeComponent()
        return
    end constructor
    
   
PRIVATE METHOD Form3_Load(sender AS System.Object, e AS System.EventArgs) AS VOID STRICT
            RETURN
        END METHOD
    
END CLASS 
END NAMESPACE
```

**Comment by cpyrgas** [comment]
It's improved, but still clumsy. Try for example the attached solution, it has this code:

```
    PUBLIC PARTIAL CLASS Form1 ;
        INHERIT System.Windows.Forms.Form
                                      

        PUBLIC CONSTRUCTOR()   STRICT//Form1
            InitializeComponent()
            RETURN
        END CONSTRUCTOR
        
        EXPORT myfield AS INT                
        PROPERTY MyProperty2 AS STRING AUTO

    END CLASS 
```

Now generate a button click, or Load etc event handler from the designer, the code ends up as (note also the property going in the same line with the field):


```
    PUBLIC PARTIAL CLASS Form1 ;
        INHERIT System.Windows.Forms.Form
                                      

        PUBLIC CONSTRUCTOR()   STRICT//Form1
            InitializeComponent()
            RETURN
        END CONSTRUCTOR
        
        EXPORT myfield AS INT                PROPERTY MyProperty2 AS STRING AUTO

                PRIVATE METHOD Form1_Load(sender AS System.Object, e AS System.EventArgs) AS VOID STRICT
            RETURN
        END METHOD

    END CLASS 
```

[WindowsFormsApplication45.zip](https://github.com/X-Sharp/XSharpPublic/files/10019894/WindowsFormsApplication45.zip)

**Comment by cpyrgas** [comment]
Now I get again the behavior as originally reported in the ticket. Obviously not a showstopper

**Comment by RobertvanderHulst** [comment]
Ok, I will leave this one for the next build.
