### ISSUE TITLE
Suggestion for the VS indentation issues

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1153]
Given the problems like this one below, I think the best solution is to decrease the effect of the Enter key regarding indentation in the editor.

To explain with an example, with editor indent options set to "Indent entities inside namesapces" and "indent statements inside entities" only, the following code is indented like that, after a Format Document command:

```
BEGIN NAMESPACE WindowsFormsApplication40
    
    PUBLIC PARTIAL CLASS Form3

    public constructor() strict
        InitializeComponent()
        return
    end constructor
    
    PRIVATE METHOD Form3_Load(sender AS System.Object, e AS System.EventArgs) AS VOID STRICT
        RETURN
    END METHOD
    
END CLASS 

END NAMESPACE
```

It looks good, except for the END CLASS statement, which does not have the same indentation with the CLASS declaration, but that's minor.

The problem is when you press Enter to open new lines. Do it while at the end of the CLASS declaration, then this declaration is incorrectly moved to indentation 0, in the beginning of the line. Do this at the END CONSTRUCTOR or END METHOD lines, and those will get an incorrect extra indentation to the right. Do it on the END CLASS line, now in this case this statement will be moved to the correct position, one tab to the right.

But this is very clumpy and IMO the solution is simple and will take care of almost all problems. At least optionally, make Enter do not affect indentation of the CURRENT line at all, except for very specific things, when on a "ENDIF", "END IF", "END", "END CASE" etc and that's it. For all other cases, let the user manually handle re indenting code if he/she likes, but do not change the current indentation level on lines like class/entity declarations, normal executable code etc.

Of course that's for affecting the line on which the cursor is positioned the moment the user presses enter. For the next line, the one that gets now created after pressing Enter, then the indentation should remain as it is now, and this is actually working in at least 95% of the cases already.

IMO this will automatically take care of almost all the indentation problems currently existing in VS while typing and I think it must be easy enough to implement?

**Comment by cpyrgas** [comment]
Confirmed, looks much better now!

**Comment by cpyrgas** [comment]
Ah, not quite, it still does thins on its own. For example, taking this code from RP2:

```
FUNCTION DOFontAttributes(oFont AS cFont,nFontColor AS DWORD) AS ARRAY 
RETURN {	rpLangString(IDS_DO_FONT),;
			rpLangString(IDS_FONTNAME)		+" = "+	oFont:FaceName,;
			rpLangString(IDS_FONTHEIGHT)	+" = "+	float2Str(FLOAT(Abs(oFont:Height))/FLOAT(TWIPS_PER_POINT),10,2),;
			rpLangString(IDS_BOLD)			+" = "+	IIF(oFont:Bold,rpLangString(IDS_TRUE), rpLangString(IDS_FALSE)),;
			rpLangString(IDS_ITALIC)		+" = "+	IIF(oFont:Italic,rpLangString(IDS_TRUE), rpLangString(IDS_FALSE)),;
			rpLangString(IDS_UNDERLINE)		+" = "+	IIF(oFont:Underline,rpLangString(IDS_TRUE),rpLangString(IDS_FALSE)),;
			rpLangString(IDS_FONTCOLOR)		+" = "+	DOColorAttributes(nFontColor)}

```

Go at the end of any line and press enter, the line is now getting a new identantation, breaking the indentation of the method.

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
It's not only that though, in general I don't like it that the editor changes my indenting the way it likes, that was the general matter of my report. 

For example, I prefer to have RETURN statements indented (when they are in the last line of the method) at the same level with the method, not one tab to the right. I might even prefer to put them at zero indentation. I know, Format Document cannot cover all people's strange preferences, so it's ok that it indents it the "regular" way. But then, I manually reindent the RETURN the way I like it, only to have the editor put it back when it wants, when I press <Enter> on it again.

And not only that. I may want other times to put some code in zero indentation, or in a very high indentation, in order for it to be easily spotted and draw my attention for some reason. I do that (and of course do not use Format Document on that code), but again, next time I press <Enter>, VS puts it back where it wants (or where it believes I want to put it).

It's things like that that make me never want to use VS, it's not only about our X# integration (this is how it works also in c# I think), but it's the general style in it, to decide what it wants to do for myself, instead of letting me do what I want. It's the same thing with Dick I'm sure :)

So my suggestion was to (optionally at least) do not touch indentation of the code I'm typing, unless it's a begin or end of a block statement (or entity).

**Comment by cpyrgas** [comment]
Unfortunately now auto indent does not work at all on IF, FOR etc and other block statements, it doesn't auto indent after entity definition lines etc.

I'm afraid my suggestion (to auto indent all lines that need to be auto indented, but leave alone the resr) is difficult to implement the way VS works, so better leave it as it was before and ignore this ticket. Most people seem to be OK with it as it was before, the rest of us will just keep using another editor :)

**Comment by RobertvanderHulst** [comment]
> It's not only that though, in general I don't like it that the editor changes my indenting the way it likes, that was the general matter of my report.
> 
> For example, I prefer to have RETURN statements indented (when they are in the last line of the method) at the same level with the method, not one tab to the right. I might even prefer to put them at zero indentation. I know, Format Document cannot cover all people's strange preferences, so it's ok that it indents it the "regular" way. But then, I manually reindent the RETURN the way I like it, only to have the editor put it back where it wants, when I press Enter on it again.
> 
> And not only that. I may want other times to put some code in zero indentation, or in a very high indentation, in order for it to be easily spotted and draw my attention for some reason. I do that (and of course do not use Format Document on that code), but again, next time I press Enter, VS puts it back where it wants (or where it believes I want to put it).
> 
> It's things like that that make me never want to use VS, it's not only about our X# integration (this is how it works also in c# I think), but it's the general style in it, to decide what it wants to do for myself, instead of letting me do what I want. It's the same thing with Dick I'm sure :)
> 
> So my suggestion was to (optionally at least) do not touch indentation of the code I'm typing, unless it's a begin or end of a block statement (or entity).

I think the only way to achieve what you want is by disabling "Smart Indenting". 
Of course, I can add an option, like "align last (return) statement with entity start", but what should happen then for entities of type VOID that have no return statement (which is perfectly valid). Or an entity that ends with an IF statement with a return in every IF/ELSEIF/ENDIF branch? Should the whole IF statement be indented at the same level as the entity start?
The only real way to do something like that is by putting an END METHOD/FUNCTION etc  after the last line of the statement list.

**Comment by cpyrgas** [comment]
Robert, I think we're thinking in very different terms, regarding how indenting works/should work, you're too used to how VS works and I'm too used to XIDE :)
I'll just close this for now and next time we do an online meeting, I will show you on my screen how I expect it to work. 
Btw, I tried putting the setting to "Block instead of "Smart", but this does not do any indenting at all it seems.

**Comment by cpyrgas** [comment]
Hmm, can't find a way to "unassign" this form the current "Project"

**Comment by RobertvanderHulst** [comment]
> Hmm, can't find a way to "unassign" this form the current "Project"
I have no idea what you mean...

**Comment by cpyrgas** [comment]
Robert, I want to detach it from this Project named "Build 2.15 - fixes in X# 2" and leave it without "currently assigned" project. This way I wouldn't need to close the ticket (so we will look into it again in the future), without us bothering right now showing up in the "todo" list for the current project.
