### ISSUE TITLE
CLOSE ALL command results to runtime exception

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1163]
Following code results to an "Invalid alias specification" runtime error, when calling CLOSE ALL. Indeed, this command is translated to:

`ALL ->( DbCloseArea() )`

because the directive in dbcmd.xh is defined as

`#command CLOSE [al: DATABASES,ALL>] => DbCloseAll()`

Not sure if this is a bug in the directive or in the pre processor not handling it correctly

```
FUNCTION Start() AS VOID
LOCAL cDbf AS STRING
TRY
	cDbf := "C:\test\testdb"
	DbCreate(cDbf, {{"FLD","C",10,0}})
	DbUseArea(,,cDbf)
	CLOSE ALL
CATCH e AS Exception
	? e:ToString()
END TRY

Description :   Invalid alias specification
Subsystem :     DBCMD
GenCode :       EG_ARG Argument error
SubCode :       1010 Invalid alias specification
FuncSym :       ERROR.VODBERROR
Severity :      ES_ERROR
Can Default :   False
Can Retry :     False
Can Substitute :        False
Argument :      ALL
Arguments :     {ALL}
Stack Trace :
 __PUSHWORKAREA (Line: 0)
 START (Line: 6)

```

**Comment by Karl1155** [comment]
Chris,

it seems there are two problems

1. In the current `CLOSE [al:DATABASES,ALL>] `declaration a "<" char is missing. The correct declaration looks like 
`#command CLOSE [<al:DATABASES,ALL>] => DbCloseAll()`
 
2. in the dbcmd.xh the `CLOSE => DbCloseArea()` declaration must be the very last CLOSE declaration.
instead of :

```
// NOTE:  CLOSE <alias> must precede the others
#command CLOSE <alias>              => <alias>->( DbCloseArea() )
#command CLOSE &<alias>             => (<alias>)->( DbCloseArea() )
#command CLOSE                      => DbCloseArea()
#command CLOSE [al: DATABASES,ALL>] => DbCloseAll()

```
it should look like:

```
// NOTE:  CLOSE <alias> must precede the others
#command CLOSE <alias>              => <alias>->( DbCloseArea() )
#command CLOSE &<alias>             => (<alias>)->( DbCloseArea() )
#command CLOSE [<al: DATABASES,ALL>] => DbCloseAll()
#command CLOSE                      => DbCloseArea()

```
now these commands: 

```
CLOSE SMALL  // Alias "SMALL"
CLOSE 
CLOSE DATABASES 
CLOSE ALL 	
```

are correctly translated to:

```
SMALL ->( DbCloseArea() )
DbCloseArea()
DbCloseAll()
DbCloseAll()

```
regards
Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz, Thanks.
Only CLOSE INDEXES was missing. This needs to be added too.

**Comment by cpyrgas** [comment]
Confirmed fixed
