### ISSUE TITLE
RDD big speed drop when using indexes

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1165]
Put the attached dbf/cdx files in a LAN or in an external HD and run this code in both VO and X# as is. Execution speed is comparable in both.

Now remove the DBSetOrder(0) line, or change it to use order 1 (it's only one available) and run again. In VO, execution speed remains similar to before, there's only a 20%-30% performance drop. But in X#, the time needed to execute is more than double that without using the index.

```
FUNCTION Start() AS VOID
LOCAL cDbf AS STRING
LOCAL nRecords := 0 AS INT
LOCAL nSeconds AS REAL8
cDbf := "d:\INDEXFIL"

DbUseArea(,"DBFCDX",cDbf,,TRUE)
DbSetOrder(0)
nSeconds := Seconds()
DbSetFilter({||_FIELD->FileType = "BOOKING"})
DbGoTop()
? "Recno after setting filter:", RecNo()
DO WHILE .not. Eof()
	nRecords ++
	DbSkip()
END DO
? "Records in filter:", nRecords
? "Time passed:", Seconds() - nSeconds
DbCloseArea()
```

[DBF_CDX.zip](https://github.com/X-Sharp/XSharpPublic/files/9979021/DBF_CDX.zip)

**Comment by RobertvanderHulst** [comment]
The DBF driver now uses the new InputBuffer classs that Nikos wrote. We are not using this (yet) in the CDX or the Memo drivers. Switching to the input buffer will most likely result in a better performance.

**Comment by RobertvanderHulst** [comment]
The customer reports that the speed is better,
The remaining issues seem to be related to filter optimizations.
