### ISSUE TITLE
Missing Start() function results to report reported on "CompileGeneratedCode.prg" file

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1167]
Small thing which I think is new, compiling an app with missing Start() function results to an error message mentioning the non existant file "CompileGeneratedCode.prg"

CompileGeneratedCode.prg(1,317): error XS1558: 'Test.Exe.Functions' does not have a suitable static 'Start' function

Edit: no, it's an old issue

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
Confirmed fixed
