### ISSUE TITLE
Intellisense not working in some cases

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1168]
Following solution compiles with no errors and has two files with code:

[DevTeamTest.zip](https://github.com/X-Sharp/XSharpPublic/files/10019091/DevTeamTest.zip)

Functions.prg:
```
CLASS TestClass
METHOD AddFilesToNewZip() AS LOGIC
LOCAL oZip AS System.IO.Compression.ZipArchive
? oZip:
RETURN TRUE
END CLASS
```

typing the colon on "oZip" produces no member completion list. But hovering over the var, does produce the correct tooltip.

Program.prg:
```
FUNCTION Start() AS VOID
LOCAL test AS System.IO.Compression.ZipArchive
? test
```

typing the colon on "test" produces no member completion list again. And this time hovering over the var produces an incorect "Undeclared test" tooltip.

Problem can not be reproduced always, in another solution I tried it worked ok, but in this simple one, it is consistently reproducible.

(new issue in 2.14)

**Comment by cpyrgas** [comment]
As a matter of fact, even a simple

**Comment by RobertvanderHulst** [comment]
This particular problem (the undeclared test) only occurs in a very small source file with only one function.

**Comment by RobertvanderHulst** [comment]
The first problem was the same as another problem with extension methods.

**Comment by cpyrgas** [comment]
Confirmed fixed
