### ISSUE TITLE
VS2017 Tab inserted inside line of code when pressing Enter

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1169]
When "Indent statements inside entities" is enabled, try typing this (not copy/paste):

```
FUNCTION Start() AS VOID STRICT
LOCAL n AS INT
```

and now press Enter at the end of the 2nd line, you end up with

```
FUNCTION Start() AS VOID STRICT
LOCAL     n AS INT
```

so a tab, or spaces (depending on the tabs) setting inserted between LOCAL and n, instead of the beginning of the line. Problem happens only in VS2017, in VS2019 it works as expected

(old issue)

**Comment by RobertvanderHulst** [comment]
I cannot reproduce this in 2.14.0.4.
Do you still see this?

**Comment by cpyrgas** [comment]
Yes, it happens always here!

**Comment by cpyrgas** [comment]
Update: This happens actually in both VS2017 and VS2019, just need to have keyword case sync option set to UPPER. It also depends on the indentation options, you need to have enabled the indentation for code inside entities, for this to happen. Another similar example, type (not paste):

class Foo
method Bar()

and press enter, you end up with 

```
CLASS Foo
METHOD     bar()
```

It is important to type the word method in lower case, because this will trigger the case sync to convert the line to uppercase, which in turn will trigger the problem. Same with the original sample, it actually needs to be typed in lower case:

```
FUNCTION Start()
local n as int
```

Sorry, had not realized this before in my original report

**Comment by RobertvanderHulst** [comment]
This should be fixed in the built that I will share today.

**Comment by cpyrgas** [comment]
Confirmed fixed!
