### ISSUE TITLE
Add ASYNC support to XBase++ methods

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1183]
Add ASYNC to the xppMemberModifiers rule. Check for other modifiers that should be added as well.
e.g. SEALED, ABSTRACT, UNSAFE, EXTERN

**Comment by cpyrgas** [comment]
Robert, how can I test this? Not sure what the bug is about.
Is it enough to just use some ASYNC/AWAIT code in the XBase++ dialect? That does work fine now. Or is it more complicated than that?

**Comment by cpyrgas** [comment]
I think it's confirmed fixed.
