### ISSUE TITLE
System.FormatException with interpolated string in X# 2.14.0.1 beta

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1184]
The following code produces an Runtime error
`var teststring := ie"{1}}"`
In c# you get an compiler error "error CS8086: A '}' character must be escaped (by doubling) in an interpolated string."
It would be great to get also in x# an compiler error for this

**Comment by cpyrgas** [comment]
Compiler error is now correct, but the compiler does not respect it's advice :). Even after doubling the "}" character, the error remains. The same problem exists also with the "{" character.

Also, when using "{}", an Internal Compiler Error occurs. In c# the error reported is "error CS1733: Expected expression"

```
FUNCTION Start( ) AS VOID
	LOCAL n := 123 AS INT
	LOCAL c AS STRING

	c := i"{n} {{" // error XS8076: Missing close delimiter '}' for interpolated expression started with '{'.
	? c

	c := i"{n} }}" // error XS8086: A '}' character must be escaped (by doubling) in an interpolated string.
	? c

	c := i"{n} {{}}" // error XS8086: A '}' character must be escaped (by doubling) in an interpolated string.
	? c

	c := i"{}" // Internal Compiler Error
	? c
RETURN
```

**Comment by cpyrgas** [comment]
Confirmed fixed
