### ISSUE TITLE
Intellisense problem with LOGICs in some cases

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1185]
Following code does not produce a member completion list on the first 2 cases, but does produce it for the final one. Problem is not reproducible in all solutions, but it always is in the attached one

[ConsoleApplication30.zip](https://github.com/X-Sharp/XSharpPublic/files/10126194/ConsoleApplication30.zip)

```
FUNCTION Start() AS VOID STRICT
    LOCAL b AS LOGIC
    LOCAL n AS INT
    n:Equals(): // no member completion
    b: // no member completion
    LOCAL sb AS System.Boolean
    sb: // this one works
    
```

**Comment by RobertvanderHulst** [comment]
The problem was that we have an alternative type for LOGIC (__WinBool). When looking up the right type we were not getting System.Boolean but XSharp.__WinBool. That has been fixed

**Comment by cpyrgas** [comment]
Confirmed fixed
