### ISSUE TITLE
VS integration: class members select list shows private class members

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1188]
If overloaded methods are declared in a class, one of which is private, and it is declared first, then when you hover the mouse cursor over the method, the description of the private method is displayed. Also, such a method is displayed by the VS editor in the selection list of overload methods available for calling.

**Example:**
```
FUNCTION Start() AS VOID STRICT

	LOCAL oTestClass AS TestClass
	oTestClass := TestClass{}
	oTestClass:DoSomething(1)

	RETURN

CLASS TestClass

	CONSTRUCTOR() STRICT
	END CONSTRUCTOR

	/// <summary>Private DoSomething.</summary>
	HIDDEN METHOD DoSomething(nParam1 AS INT, nParam2 AS INT) AS VOID STRICT
		RETURN

	/// <summary>Public DoSomething.</summary>
	METHOD DoSomething(nParam1 AS INT) AS VOID STRICT
		RETURN

END CLASS
```

**Screenshot 1:**
![Screenshot1](https://user-images.githubusercontent.com/64518775/207380270-fca55c01-f989-45c0-ab1f-a4c421cace8e.png)

**Screenshot 2:**
![Screenshot2](https://user-images.githubusercontent.com/64518775/207380342-c1297ec6-4eea-46bd-8950-015931a5fc83.png)

If you declare a public method first, then the display of tooltips and the overload selection list become correct (without the private method).

**Environment:**
X# 2.14.0.4
VS 2019

**Comment by RobertvanderHulst** [comment]
Having 2 methods with the same name and a different visibility is apparently supported, but I am not sure if that is a good idea.
I will fix this though.

**Comment by cpyrgas** [comment]
There's still a problem, when you type the "(", then the parameter tip shows 2 methods. The fist one, is a bogus "DoSomething() AS USUAL", while the 2nd one is the correct "DoSomething(nParam1 AS INT) As VOID"

![Method_Tooltip](https://user-images.githubusercontent.com/14542129/216017331-b03ad535-afbb-4056-900e-052053b64245.png)

**Comment by RobertvanderHulst** [comment]
Chris,
I am sorry but, I cannot reproduce that over here.
I do see that in the build that you have, immediately after opening the solution you see no parameter tips at all. But when you close and then reopen the solution then I only get the public overload of Something.
Can you zip the solution where you see this?

**Comment by cpyrgas** [comment]
Robert,
Hmm, that's really strange, but now I can't reproduce it that way either. Maybe something had went on wrong with the intellisense database. But I can reproduce a slightly different issue, type again

oTestClass:

and select "DoSomething" from the list, now again it shows 2 overloads

this way there are both the "real" overloads defined in the code, but again the hidden one should not be shown. When only retyping the "(", indeed only one is shown, as expected.

**Comment by cpyrgas** [comment]
Confirmed fixed
