### ISSUE TITLE
Cannot find base.Value when CaseSensitive is On

### ISSUE THREAD

**Issue by fforay** [X-Sharp/XSharpPublic#1189]
// Using VS2022 17.4.2
// Using XSharp 2.14.0.4

When CaseSensitive is OFF, the following code compiles fine.

When ON, Error is the following :
error XS1061: 'valueError.Class1' does not contain a definition for 'value' and no accessible extension method 'value' accepting a first argument of type 'valueError.Class1' could be found (are you missing a using directive or an assembly reference?)

It seems the default "value" parameter in the Setter is searched as a Field/Property

```
USING System
USING System.Collections.Generic
USING System.Linq
USING System.Text

BEGIN NAMESPACE valueError
	CLASS Class1 INHERIT System.Windows.Forms.DataGridViewColumnHeaderCell
		
		CONSTRUCTOR() STRICT
			RETURN		
			
		PROPERTY Text AS STRING 
			GET
				IF SELF:Value != NULL
					return SELF:Value:ToString()
				ELSE
					RETURN NULL
				ENDIF
			END GET
			SET
				#warning !!!! This affectation doesn't work when Case Sensitive is ON <<<<<<<<<<<<<<<<<<<<<
				SELF:Value := (object)value
			END SET
		END PROPERTY
	END CLASS
END NAMESPACE
```

**Comment by RobertvanderHulst** [comment]
As workaround you can prefix Value with @@

**Comment by cpyrgas** [comment]
Confirmed fixed
