### ISSUE TITLE
XDocument instancing with XDeclaration results to an argument exception

### ISSUE THREAD

**Issue by pemo11** [X-Sharp/XSharpPublic#1195]
The following code line does not work with X# 2.14 when compiling with the VO dialect

var xDoc := XDocument{XDeclaration{"1.0", "utf-8", "False"}}

executing the code results to an argument excecption - "Non white space characters cannot be added to content"

The line above can be run with X# 2.13.

**Comment by cpyrgas** [comment]
Problem has to do with the available constructors of the XDocument class, which includes one accepting object[]: https://learn.microsoft.com/en-us/dotnet/api/system.xml.linq.xdocument.-ctor?view=netframework-4.8.1

When compiled in Core, the expression XDocument{ XDeclarationObject } resolves to the constructor https://learn.microsoft.com/en-us/dotnet/api/system.xml.linq.xdocument.-ctor?view=netframework-4.8.1#system-xml-linq-xdocument-ctor(system-xml-linq-xdeclaration-system-object()) which accepts params (XDeclaration, Object[]). It would make more sense I think to resolve to the overload https://learn.microsoft.com/en-us/dotnet/api/system.xml.linq.xdocument.-ctor?view=netframework-4.8.1#system-xml-linq-xdocument-ctor(system-xml-linq-xdocument) that accepts a single XDeclaration object, but c# is doing the same thing, so it's OK.

But when compiled in VO dialect, then the same code is resolved to a call to the constructor overload https://learn.microsoft.com/en-us/dotnet/api/system.xml.linq.xdocument.-ctor?view=netframework-4.8.1#system-xml-linq-xdocument-ctor(system-object()) that accepts params object[], which leads to the problem above.

**Comment by RobertvanderHulst** [comment]
Chris,
In the non core dialect we have our own rules to determine which overload to choose. 
I think (in retrospect) we should only use these rules when:
- One or both overloads are functions in a Functions class
- One of the parameters or one of the arguments is an X# type, like USUAL, DATE, ARRAY, FLOAT etc
- Maybe something else (will have to see which of test fails if I implement the checks above)

In all other cases (standard datatypes, methods/constructors that do not use one of our types) we should probably let Roslyn determine the overload that needs to be chosen. 
That should at least solve the problem in this case.

**Comment by pemo11** [comment]
My colleague Harald found out, that adding a null value for the last parameter helps the compiler chosing the appropriate overload:

var xDoc := XDocument{XDeclaration{"1.0", "utf-8", "False"}, Null}

**Comment by cpyrgas** [comment]
Robert, was that different behavior implemented just in order to emulate VO's behavior with variable amount parameters? Was that only for functions, or is it also supported for methods in VO? (I don't even remember the syntax for that, I think it had to do with using three dots or similar in the param list).

**Comment by RobertvanderHulst** [comment]
The different behavior is for things such as:
- functions in user code that replace functions in the runtime
- if a parent class has an overload with a Date and the childclass with a DateTime and the parameter is a Date, then the method in the parent should be called, although there is an implicit converter to datetime
- treating 'usual' like 'object', so it can match any overload
- several other cases like these

**Comment by cpyrgas** [comment]
Robert, OK, so if also all the other cases have to do with VO types, then I guess your suggestion above to fall back to Roslyn default behavior when the criteria are meant should work.

**Comment by cpyrgas** [comment]
Confirmed fixed
