### ISSUE TITLE
VS Integration: incorrect display of type hierarchy

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1198]
**X#** 2.14.0.4
**IDE:** VS 2019

**Example code:**
```
USING System

BEGIN NAMESPACE TestNamespace

	CLASS TestClass

		METHOD DoSomething() AS VOID STRICT
			RETURN

		#region TestClass utility classes

		HIDDEN CLASS UtilityClass1
		END CLASS

		HIDDEN CLASS UtilityClass2
		END CLASS

		#endregion

	END CLASS

END NAMESPACE
```

**Issue 1:**
When opening a PRG file, the list of types (left combobox) is empty. There is not even a "Global Scope" item. In order for the list to be filled with content, you need to place the cursor on the class definition (in the example, this is the TestClass class).

![Screenshot1](https://user-images.githubusercontent.com/64518775/213466936-e9a0f967-8bb6-4e3f-bc32-c038ae3f6947.png)

**Issue 2:**
The TestClass class has two nested classes, but only one of them is displayed in the correct hierarchy (the UtilityClass2 class). And the UtilityClass1 class displayed outside the namespace and root class.

![Screenshot2](https://user-images.githubusercontent.com/64518775/213468078-21b679f1-9619-4dc4-a6cb-31d6d38c9fbc.png)

Also UtilityClass1 is missing from right combobox.
![Screenshot3](https://user-images.githubusercontent.com/64518775/213472684-08061042-ef1b-4458-b3aa-a72d3c09eead.png)

**Comment by cpyrgas** [comment]
Confirmed fixed
