### ISSUE TITLE
Add option in the VS VOWED to manually adjust the x/y possitions/sizes in the generated resource with multipliers

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1199]
See https://www.xsharp.eu/forum/public-product/3326-new-updated-resource-file-makes-form-enormous#24968

**Comment by cpyrgas** [comment]
Done, there are two new options in the Custom Editors/VO Window Editor page of VS Options dialog for x/y size adjustment. 1000 stands for 1:1, 2000 makes size double and 500 makes it half. Zero also stands for default.

**Comment by cpyrgas** [comment]
(attempted to store options in strings - floats are not available due to those options saved in the registry, but that would further complicate things with various regional settings)

**Comment by RobertvanderHulst** [comment]
Chris, it works, but needs some explanation on the valid range of values and what the editor does with the number.
I started with values < 100 and then nothing happens. I had to look in the source to see that the value needs to be > 100.
At this moment, the descriptions for the values are:
- Correction factor for Size adjustment horizontally 
- Correction factor for Size adjustment vertically.

Can you create a better description? I think the description should also mention the High DPI monitors for which this was needed.
And I also think that the valid range of values needs to be mentioned. 
From what I see 1000 means no scaling. So should the default not be 1000 then?

**Comment by cpyrgas** [comment]
Robert, I was just trying to limit as much as possible the cases where this resize would happen by accident, for example due to an incorrect default value in those options etc. A value of 100 would mean emitting the size as 10% of the edited size, which does not make sense, so I added that as the minimum limit, same as 900% for the upper limit. I don't really like this range entered like that, but using a string for the value would probably be even more confusing...

I was thinking about a description, but where will this description show up?

**Comment by cpyrgas** [comment]
Oh, right, there's a description in the bottom of the properties window, had not noticed that! OK, will write a small description for it.

**Comment by RobertvanderHulst** [comment]
I did some checks, and it seems that I CAN make this a System.Double value. 
In that case it would make sense to just use the value 1 to indicate no scaling.

**Comment by cpyrgas** [comment]
Confirmed! I also adjusted the descriptions, still not entirely happy with them, but will do for now.
