### ISSUE TITLE
When generating a new project in VS2019, then the "Debug" folder is created (and maintained) outside the Bin folder

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1201]
Create for example a new VOMDI app in VS2019, then build in Debug and Release Mode. The Layout of the folders where the assemblies get generated becomes:

(Solution)
- Debug
- (Project)
- - Obj
- - - Debug
- - - Release
- - Bin
- - - Release

So while the Obj folder contains both a Debug and Release sub folder, Bin contains only Release and the "bin" Debug folder is actually generated in the base solution folder.

Furthermore, doing a "Clean" on the debug configuration, does not delete the contents of that Debug folder.

[VOMDIApp29.zip](https://github.com/X-Sharp/XSharpPublic/files/10478942/VOMDIApp29.zip)

**Comment by RobertvanderHulst** [comment]
Fixed in 3ca7b9b4f57191046b10ea4d273eb789b5abccd2

**Comment by cpyrgas** [comment]
Fixed. I didn't test ALL X# project types, but tested several and they are fine now.
