### ISSUE TITLE
Debugger shows wrong error location for exceptions elseif branch 

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1202]
The following code throws an exception in the second elseif branch. 

    function Start() as void strict
	    local x := "x" as usual
	    local y := 1 as usual
    
	    if Empty(x) // Visiual studio shows the error here
		    X := "x"
	    elseif Empty(y)
		    X := "x"
	    elseif x == y // Exception happens here
		    X := "x"
	    endif
	    return

But the Visual Studio Debugger shows the location of the error in the line with the if statement. 

![image](https://user-images.githubusercontent.com/9860916/216566578-11a133d8-0604-4387-8477-509bb653ad92.png)

This makes it very hard to identify the reason for the error, especially if you have many elseif statements and/or complex conditions.

Test Solution: 
[XSharpTestsDebugger.zip](https://github.com/X-Sharp/XSharpPublic/files/10577608/XSharpTestsDebugger.zip)

**Comment by RobertvanderHulst** [comment]
This is already fixed. Duplicate of #1187

**Comment by cpyrgas** [comment]
Can't test this one at the moment due to the debugger issue

**Comment by cpyrgas** [comment]
Confirmed fixed
