### ISSUE TITLE
Missing compiler error for missing END token

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1203]
I know, this is partly my fault and it actually hit myself today! Old bug, the following does not report any errors, although there's a missing "END" for the outer IF statement. If I remove the TRY...END TRY, or I include a CATCH or FINALLY statement, then the error does come as expected.

```
FUNCTION DoTest() AS VOID
	LOCAL n := 0 AS INT
	IF n == 1
		? "if"
	ELSE
		? "else"
		TRY
			? "try"
		END TRY
		IF TRUE
			? "newif"
		END IF

? "end"		

```

**Comment by RobertvanderHulst** [comment]
There is a setting in the parser, that suppresses errors for blocks when there is an error / warning inside the block.
In this case there is a warning about the missing CATCH clause, and therefore the error about the missing END IF is suppressed.
I will change the compiler to not do this when there is a warning, but only when there is an error.

**Comment by cpyrgas** [comment]
Confirmed fixed
