### ISSUE TITLE
Rebuild Intellisense Database command causes member completion and tips to stop working

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1206]
In any X# solution, use Rebuild Intellisense Database in VS2019. VS will close and will automatically reopen the solution, but now none of the classes defined in this solution provide member completion, and hovering the mouse over a type shows "Undeclared".

After closing and reopening the solution, it all works fine again.

**Comment by RobertvanderHulst** [comment]
Does this also happen when you delete the .vs folder before starting VS?

**Comment by cpyrgas** [comment]
Robert, I was about to say no (not anymore at least), but I just gave it a try again and yes I saw the same problem again also by deleting the ".vs" folder. And while yesterday this wasn't happening to me anymore, now I can reproduce it consistently again.

And one of the times that I tried the "Rebuild Intellisense Database" command, intellisense was actually available when VS auto-restarted. But that was only once out of ten attempts, all other times instellisens was not available.

Something really bizarre is going on... But then again it's VS, so I'm not surprised...

**Comment by RobertvanderHulst** [comment]
I think I know what the problem is, and it is in OUR code and not the VS code.

**Comment by RobertvanderHulst** [comment]
Btw, I will NOT delay the 2.15 build for this.

**Comment by cpyrgas** [comment]
I know, I just meant that due to the ways VS works, it's so extremely difficult making our integration play by all its rules and quirks.

**Comment by leon-ts** [comment]
Guys,
just additional information:

In X# 2.14.0.4 + VS 2019, this functionality (rebuild intellisence database) works without problems on my computer - after restarting VS, hints and type member selection lists work. I often use this functionality, for example, after some global renames. Maybe this is a new bug only in version 2.15?

**Comment by cpyrgas** [comment]
Leonid, yes indeed this is a side effect of some other change for the new build.

**Comment by cpyrgas** [comment]
Confirmed fixed
