### ISSUE TITLE
Strange behavior with menus which were created by X# VO Porter and then edited and saved in Visual Studio

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1207]
From Christian Schmid:

I have a strange behavior here with menus which were created by X# VO Porter and then edited and saved in Visual Studio for the first time.

1. the original code from VO where the menu items are assigned to the correct generated defines.
2. the *.rc file which was created by the X# VO Porter, in which the menu items are assigned constant values and not the defines. In menus where menu items were added later and the numbers are not in a row, the assigned constant values do not match the defines.
3. the *.prg file which was created by the X# VO porter and contains the defines with the correct, original numbers.
4. the *.rc file modified by Visual Studio after editing the menu for the first time and newly created defines with new numbers, which is wrong, because the original defines in the *.prg file with the old numbers remain.

Can you please take a look at this, maybe I just set a setting wrong.

![image001](https://user-images.githubusercontent.com/14542129/218811343-7f5da16c-7b9d-42f5-ba0c-91d868ab857d.png)

**Comment by cpyrgas** [comment]
Indeed, the VO menu editor in X# uses a complete custom number for the menu item defines.
Robert, can you please check in VO, where does it save the DEFINE values used for each menu item and how we can read this from the VOXporter?

**Comment by RobertvanderHulst** [comment]
Chris,
If you look at the file Menus.EMPTYSHELLMENU.xsmnu in the VoExportedExamples folder then you will see that each menu item has the ID on the line below the caption.
For example

```
&File
21649
File
.
.
.
&Open...
21650
FileOpen
```

and the resource looks like this:
```
EMPTYSHELLMENU MENU
Begin
	POPUP "&File"
	BEGIN
		MENUITEM "&Open...\tCTRL+O", 21650
		MENUITEM SEPARATOR
		MENUITEM "P&rint Setup...", 21652
		MENUITEM SEPARATOR
		MENUITEM "E&xit\tALT+F4", 21654
	END
.
.

End
```

So the IDs are on the second line of each item.

**Comment by cpyrgas** [comment]
Robert, arghh, it's that simple...just saw I'm already reading this value in the binary reader and then I'm ignoring it :)
Thanks! But btw where is the VoExportedExamples folder?

**Comment by RobertvanderHulst** [comment]
That was a typo. Not a 'd' but a 'r'. On my machine it is in

c:\XSharp\DevPublic\Samples\VOExporterExamples

**Comment by cpyrgas** [comment]
Oh right. But do we install those somewhere in users' machines?

**Comment by RobertvanderHulst** [comment]
Yes, below the folder c:\Users\Public\Documents\XSharp

**Comment by cpyrgas** [comment]
Thanks!

**Comment by cpyrgas** [comment]
Fixed. Now the VOXporter exports also the original DEFINE value used in the VO app for every menu item, and the VO Menu Editor in VS reads and uses this value when generating defines and .rc file contents. So for the fix to have an effect, of course the app needs to be ported again. For menu items added after exporting the app, the menu editor gives new ID numbers, consecutive to the highest original define value found for previously already existed menu items. 

For menu binaries that do not contain this information (original define values), the old behavior is retained, there's a setting for the starting ID value in the main menu item in the Menu Editor, and all menu items use values increased by one to that base value.

Also note that the point (4) made in the original bug report is not accurate, actually also before this fix, the menu editor was re-generating also the DEFINES in the prg file, using the new (different to the original ones) define values. But of course, even having said that, the new behavior is much better.

**Comment by RobertvanderHulst** [comment]
I see that this works in VS. The exported XIDE menus do not have the original define value and when imported in XIDE new defines are generated. I am sure you will take care of that.

**Comment by cpyrgas** [comment]
Yeah, working on the XIDE side now
