### ISSUE TITLE
The VO Menu Editor in some cases generated different names for menu item DEFINEs than in VO

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1208]
In our code the automatically generated Defines to activate/deactivate etc. are used in different places and there I have nevertheless a problem. After I have changed and saved all VO generated menus once via Visual Studio, umlauts, special characters, uppercase letters and numbers in the defines are generated differently to VO which then leads to the fact that all uses of such defines outside of the generated code are no longer functional.

The points 1 and 3 show the code which was taken from Vo with the Vox#Porter, the points 2 and 4 the changes which were made after editing and saving by the menu editor in Visual Studio.

![image010](https://user-images.githubusercontent.com/14542129/218982951-06c471b7-e839-479a-a26c-1b0ce6a2561f.jpg)

![image011](https://user-images.githubusercontent.com/14542129/218982977-01b06907-8e1f-4c1d-b79c-5fe3dd5f7902.png)

**Comment by cpyrgas** [comment]
Robert, I will definitely need your help in this...can you find the algorithm VO uses for determining the DEFINE names for each menu item?

**Comment by RobertvanderHulst** [comment]
Chris,
The code that does this is very dirty. There is a table that translates accented chars to normal chars. 
The code also takes into account the double byte characters for Chinese, Korean etc. 
If you forget about these, then the rules are:
- normal ascii is written unchanged when it is an underscore, a number or between 'A' and 'Z' or between 'a' and 'z'
- other normal ascii characters are written as '_'
- accented chars are written as their unaccented version (using the table that I mentioned above)
- Remaining upper ascii characters are written as numbers between underscores (`ß` becomes `_223_` for example)

**Comment by cpyrgas** [comment]
Robert,

Thanks, but which characters are considered "accented"? Because I see that VO does not change umlauts or  the "ß" character, while our code (which currently uses string:Normalize(System.Text.NormalizationForm.FormC) among other things) changes them to the "regular" char version.

**Comment by cpyrgas** [comment]
Especially the ß symbol that you mentioned, I tried entering a menu item in VO named "ßßßßß" and the generated DEFINE was IDM_EmptyShellMenu_File_ßßßßß_ID

**Comment by RobertvanderHulst** [comment]
Chris,
I have no idea why that happens...

**Comment by RobertvanderHulst** [comment]
And I do NOT want to debug the VO code...

**Comment by RobertvanderHulst** [comment]
This may also have been changed between VO 2.5 and VO 2.8.

**Comment by cpyrgas** [comment]
Robert, I can see the behavior by testing for every character and see the result, it's indeed very different what VO does now. I can make it be very close in X#, although for the resources I will need to put there the define value instead of the define name, since the resource compiler cannot handle chars > 127. Will do that, although not sure if it's worth the risk to break something else..

**Comment by cpyrgas** [comment]
Fixed, customer confirmed it is working as expected now
