### ISSUE TITLE
Attributes in code cause auto indentation to misbehave

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1210]
When you have this

```
[STAThread];
FUNCTION Start() AS VOID
```

and press ENTER at the end of the 2nd line, you end up with

```
[STAThread];
    FUNCTION Start() AS VOID
// and now writing code at column 0

```

**Comment by RobertvanderHulst** [comment]
Do you have the option to indent "continued lines" enabled.
Then strictly speaking this is correct.
But you would like to make an exception for lines with attributes only?

**Comment by cpyrgas** [comment]
Ah, that's why the FUNCTION line gets indented. OK, to be honest I am not sure what should be the correct behavior with that.

But either way, with this option enabled or not, after pressing Enter, the caret goes to the very beginning of the next line, which is wrong in both cases (since also the other indent options are enabled)

**Comment by cpyrgas** [comment]
Confirmed fixed
