### ISSUE TITLE
ooptree

### ISSUE THREAD

**Issue by TimothyShea** [X-Sharp/XSharpPublic#1216]
**Describe the bug**
The ooptree function doesn't work. It only returns the class originally entered.

**To Reproduce**
Run ooptree( MyVar ) 

**Expected behavior**
The class hierarchy. 

As a workaround, I used the code for ooptree that Chris sent me in 2011. Works fine. 
Thought you might like to know.

**Comment by cpyrgas** [comment]
2011, that's a long time ago! Tim, it seems to work here OK, can you please include a small sample showing that it doesn't?

**Comment by cpyrgas** [comment]
@TimothyShea could it be you are using the vulcan runtime, instead of the X# one?

**Comment by RobertvanderHulst** [comment]
Closing this issue because there is not info.
