### ISSUE TITLE
FormatException with Interpolated/Extended string in X# 2.15

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1218]
The following code results to a FormatException. The problem seems that the compiler translates it to a string.Format without the parameter (seen in IL Spy c# Code)
```
function Start() as void strict
    var paramSetting := "xyz"
    var test := ei"\"{paramSetting}\""
      Console.ReadLine()
      Return
```

**Comment by cpyrgas** [comment]
Original problem is fixed, but I'm seeing a problem which I'm not sure if it existed before, following is not an escaped string, but reports error XS1039: Unterminated string literal

```
FUNCTION Start() AS VOID
LOCAL paramSetting := "xyz" AS STRING
LOCAL test := i"/\{paramSetting}/\" AS STRING
? test
```

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
Confirmed fixed
