### ISSUE TITLE
Compiler incorrectly allows accessing static members with a colon instead of dot

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1219]
Following code compiles without errors, while it should had reported 2 errors, for each static member access with the ":" operator

```
FUNCTION Start( ) AS VOID
	TestClass:StaticExport := 123
	TestClass:StaticMethod(123)

CLASS TestClass
	STATIC METHOD StaticMethod(n AS INT) AS INT
	RETURN n * 2
	STATIC EXPORT StaticExport AS INT
END CLASS
```

**Comment by cpyrgas** [comment]
I'm still seeing some issues, see this code:

```
CLASS TestClass
	EXPORT Test1 := DateTime.Now AS DateTime
	EXPORT Test2 := DateTime:Now AS DateTime
	CONSTRUCTOR()
		? DateTime:Now
	RETURN
END CLASS
```

This reports 3 warnings:

```
warning XS9112: You should not access the instance member 'TestClass.Test1' with the DOT '.' operator.
warning XS9114: You should not access the static member 'System.DateTime.Now' with the COLON ':' operator.
warning XS9114: You should not access the static member 'System.DateTime.Now' with the COLON ':' operator.
```

The first warning is bogus, this line of code is perfectly fine.
The other two warnings are correct, but those should be errors, shouldn't they? It's clearly wrong code..

**Comment by RobertvanderHulst** [comment]
I will fix the first warning,
W.r.t. the question if this should be a warning or an error.
I found several issues like this in the runtime, and I thought that making them an error will generate too much noise.
And if our users have 'warnings as errors' enabled, then these become errors.

**Comment by cpyrgas** [comment]
Robert, yes, I found a couple such cases in some of your code :)

But I think such code is just wrong. I mean we have the a = 123 assignment report an error (correctly), but using Int32:MaxValue is just a warning?

Can you please at least temporarily change it into an error, so I can check against a couple million lines of people's code, to see how often this occurs? This will make it easier for me to spot it, because many projects actually give 1000s of (other) warnings

**Comment by cpyrgas** [comment]
I temporarily adjusted XIDE so that it converts this warning to an error, and in about @M lines of code, I found 10 lines with this problem. They were 4 different cases:

WebUtility:UrlDecode
Image:FromFile()
Console:WriteLine()
Debug:WriteLine()

which I think all are very clear errors and easy to fix.

In one project I also got a bogus error, repeated a lot of times on this code:

```
LOCAL oRange     AS Microsoft.Office.Interop.Excel.Range
oRange:Value := "Transactions " // You should not access the static member 'System.Type.Missing' with the COLON ':' operator.
```

But I assume this is the same bug as the one pointed out in https://github.com/X-Sharp/XSharpPublic/issues/1219#issuecomment-1467014841

**Comment by RobertvanderHulst** [comment]
Chris,
Can you check again with this build:
https://github.com/X-Sharp/XSharpDev/actions/runs/4422130985

**Comment by cpyrgas** [comment]
Are you sure this includes the latest fix? Because I still get the same behavior as before, the test code in https://github.com/X-Sharp/XSharpPublic/issues/1219#issuecomment-1467014841 still produces 3 warnings. I did make sure to replace also XSharp.CodeAnalysis.dll in the GAC and tried downloading the action twice.

**Comment by cpyrgas** [comment]
Tested also with today's action, but still get the same issues

**Comment by RobertvanderHulst** [comment]
Chris, I f*ed up. The push failed. Just did it again.

**Comment by cpyrgas** [comment]
Haha, OK, glad it was not my fault!
Much better now, but seems the error is reported only for properties, not for methods? Because the following all compile with no errors:

System.Net.WebUtility:UrlDecode("")
System.Net.WebUtility.UrlDecode("")
Console:WriteLine("")
Console.WriteLine("")
System.Diagnostics.Debug.WriteLine("")
System.Diagnostics.Debug:WriteLine("")

**Comment by cpyrgas** [comment]
OK :). It's almost perfect now, all user code looks great (compiler finds around a dozen incorrect usages of colon/dot in around 2M lines of code), except for one thing which I found in the X# runtime. Following reports an error when trying to invoke a static delegate var:


```
FUNCTION Start() AS VOID
	TestClass.TestExport:Invoke(123) // OK
	TestClass.TestExport(123) // error XS9112: Can't access the instance member 'TestDelegate.Invoke(int)' with the DOT operator '.'.
	TestClass.TestProperty:Invoke(123) // OK
	TestClass.TestProperty(123) // error XS9112

DELEGATE TestDelegate(n AS INT) AS VOID

CLASS TestClass
	STATIC EXPORT TestExport AS TestDelegate
	STATIC PROPERTY TestProperty AS TestDelegate AUTO
END CLASS

```

**Comment by cpyrgas** [comment]
Oh, there's one more problem, this does not report any errors :)

System:Windows:Forms:Application.EnableVisualStyles()

**Comment by RobertvanderHulst** [comment]
This 

`? Nameof(System.Windows:Forms)`
will produce the following error
`Can't use the COLON operator ':' as delimiter in the Namespace 'System.Windows:Forms'`

**Comment by cpyrgas** [comment]
Sounds good! Got family visiting in the last days, but will test the newer version ASAP and will confirm.

**Comment by cpyrgas** [comment]
Unfortunately there are still some problems:

1) As noted in https://github.com/X-Sharp/XSharpPublic/issues/1219#issuecomment-1475860188, the following reports two bogus errors, in addition to the two correct ones:

```
FUNCTION Start() AS VOID
	TestClass.TestExport:Invoke(123) // OK
	TestClass.TestExport(123) // error XS9112: Can't access the instance member 'TestDelegate.Invoke(int)' with the DOT operator '.'.
	TestClass.TestProperty:Invoke(123) // OK
	TestClass.TestProperty(123) // error XS9112

DELEGATE TestDelegate(n AS INT) AS VOID

CLASS TestClass
	STATIC EXPORT TestExport AS TestDelegate
	STATIC PROPERTY TestProperty AS TestDelegate AUTO
END CLASS
```

2) The code from test C883 produces only one error, while there should be 6 errors, for every line in the Start() function:

```
// 883. Compiler incorrectly allows accessing static members with a colon instead of dot
// There should be 6 errors reported on the following code:
#pragma options("allowdot", false)
FUNCTION Start( ) AS VOID
	TestClass:StaticExport := 123 // no error, wrong
	TestClass:StaticProperty := 123 // no error, wrong
	TestClass:StaticMethod(123) // error, OK
	TestClass:DoSomething += MyEventHandler // no error, wrong
	? System.Environment:CurrentDirectory // no error, wrong
	? System.Environment:CurrentDirectory:Length // no error, wrong

FUNCTION MyEventHandler(sender AS OBJECT, args AS EventArgs) AS VOID

CLASS TestClass
	STATIC METHOD StaticMethod(n AS INT) AS INT
	    DoSomething(n, EventArgs.Empty)
	RETURN n * 2
	STATIC EXPORT StaticExport AS INT
	STATIC PROPERTY StaticProperty AS INT AUTO GET SET
	STATIC EVENT DoSomething AS EventHandler
END CLASS
```

I hope I am not just testing with a non updated compiler version! But one of the recent reports has been actually fixed, so I do not think this is the case.

**Comment by cpyrgas** [comment]
Well done, looking very good now! Confirmed fixed.
