### ISSUE TITLE
Opening (and closing) a DBF file changes the file date

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#122]
https://www.xsharp.info/forum/private-product/1380-opening-a-dbf-file-changes-the-file-date#10103

When closing a dbf file, its time stamps changes, even if no changes were made to it.

USING System.IO
FUNCTION Start() AS VOID
	LOCAL cDbf AS STRING
	cDbf := "C:\test\test.dbf"
	? DbCreate(cDbf , {{"TEST","L",1,0}})
	? File.GetLastWriteTime(cDbf)
	System.Threading.Thread.Sleep(2000)
	? DbUseArea(,,cDbf)
	? File.GetLastWriteTime(cDbf)
	? DbCloseArea()
	? File.GetLastWriteTime(cDbf) // 2 seconds later than first one
RETURN

**Comment by JohanNel** [comment]
Hi Chris,  this might also be linked to opening a DBF in ReadOnly mode that fails as I have spoken to you earlier about.
