### ISSUE TITLE
VS Integration: Wrong type of parameters in hints in separated strings

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1221]
In the following example, Intellisense shows the wrong type of parameters (on mouse hover), as well as in general the description of the parameters of the TestMethod1 method, which are placed in the second and following lines (parameters c, d and e). The same problem is observed in the body of the method, if you split the line of code into separate lines (in the example, this is a call to the TestMethod2 method).

**Example:**
```
CLASS TestClass

	METHOD TestMethod1(a AS INT, b AS STRING,;
				c AS INT, d AS DATETIME,;
				e AS REAL4) AS VOID STRICT

		SELF:TestMethod2(a, b,;
				c, d,;
				e)

		RETURN

	METHOD TestMethod2(a AS INT, b AS STRING, c AS INT, d AS DATETIME, e AS REAL4) AS VOID STRICT
		RETURN

END CLASS
```

Apparently, for all parameters that are not related to the first line, the type of the last parameter of the main line is displayed.

**Environment:**
X# 2.15.0.3
IDE VS2019

P.S. I did not notice this problem in version 2.14.0.4. Therefore, perhaps this is a new error (something was broken). But I'm not sure about this, since I have already completely switched to version 2.15.0.3 and there is no desire to return to 2.14.0.4.

**Comment by leon-ts** [comment]
Robert,
I still put the old version 2.14.0.4 on the side to check if this error was in it. Version 2.14.0.4 did not have this bug. That is, the bug was introduced in version 2.15.0.3.

**Comment by leon-ts** [comment]
Robert,
Given that separated line hints worked well in 2.14.0.4 and were broken in 2.15.0.3, can we expect this to be fixed in 2.16?

**Comment by RobertvanderHulst** [comment]
Leonid,
Hope: Yes, Expect: No.  I will do my best.

**Comment by RobertvanderHulst** [comment]
Duplicate of #1260

**Comment by leon-ts** [comment]
Fixed!
