### ISSUE TITLE
Incorrect visibility of MEMVARs created with MemVarPut()

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1223]
Following code creates a memvar with MemVarPut() and then checks for the visibility of this var in the function where it was created and also in a child and parent function. 

- In VO, the var is visible ONLY in the same function where MemVarPut() created it. In the child and parent functions it does not exist and using MemVarGet() on it leads to a runtime exception "Variable does not exist"
- In X#, the var and its values are visible in all 3 cases

```
GLOBAL gcMemVarName := "MyMemVar" AS STRING

FUNCTION Start() AS VOID
	CreateMemVarInAFunction( )
	? "Value outside the function:" , MemVarGet( gcMemVarName ) // testing123, exception in VO

PROCEDURE CreateMemVarInAFunction( )
	MemVarPut( gcMemVarName, "testing123" )
	? "Value inside the function it was declared:" , MemVarGet( gcMemVarName ) // testing123, OK
	CheckInChild()

PROCEDURE CheckInChild()
	? "Value in a child function:" , MemVarGet( gcMemVarName ) // testing123, exception in VO
```

**Comment by cpyrgas** [comment]
There's something more bizarre going on. Just declaring any MEMVAR with a random name cause the original code to have a different behavior. This version of the code only has that random MEMVAR added, and the behavior is different, while it shouldn't make any difference:

```
GLOBAL gcMemVarName := "MyMemVar" AS STRING

FUNCTION Start() AS VOID
	CreateMemVarInAFunction( )
	? "Value outside the function:" , MemVarGet( gcMemVarName ) // now it also throws an exception as in VO!!!

PROCEDURE CreateMemVarInAFunction( )
	MEMVAR JustARandomMemvar // only added this
	MemVarPut( gcMemVarName, "testing123" )
	? "Value inside the function it was declared:" , MemVarGet( gcMemVarName ) // testing123, OK
	CheckInChild()

PROCEDURE CheckInChild()
	? "Value in a child function:" , MemVarGet( gcMemVarName ) // testing123, exception in VO
```

**Comment by RobertvanderHulst** [comment]
Chris,
When /memvar is enabled then each function / method should have a try catch block like this:

```
int nLevel = XSharp.RT.Functions.__MemVarInit();
try
{
   // body
}
finally
{
		XSharp.RT.Functions.__MemVarRelease(nLevel);
}
```
I see that this is not always done for your example code. I will fix that.

The __MemVarInit() and __MemVarRelease(nLevel) take care of managing the lifetime of private variables.
Private variables SHOULD be visible in code called from a function/method where they were declared.
According to fox example the FoxPro docs, they actually do the opposite of what you expect: PRIVATE does not declare a new variable but hides a variable declared in a previous level.

> Hides specified variables or arrays that were defined in a calling program from the current program. 

The VO Docs say something similar:

> When you create a private variable or array, existing and visible private and public variables of the 
> same name are hidden until the current routine terminates or the private variable is explicitly released.

MEMVAR does not create variables, but declares that an identifier is a memory variable (public or private)

> The MEMVAR statement neither creates the variables nor verifies their existence.  
> Its primary purpose is to ensure correct references to variables that are known to exist at runtime.  
> Attempting to access variables before they are created will raise a runtime error.

MemVarPut() should create a PRIVATE variable if one does not already exist. So variables created with it should follow the same rule as the PRIVATE statement.

**Comment by cpyrgas** [comment]
Robert, it's not what I expect myself, but what VO actually does. The problem/incompatibility was reported by a customer because his ported code did not work anymore, because of this implementation difference between VO/X# (and apparently also FoxPro as you point out)

**Comment by RobertvanderHulst** [comment]
Chris,
I see it. The MemvarInit() code is not generated when the function does not have a MEMVAR, PUBLIC or PRIVATE statement but only MemVarPut() or MemVarGet(). 
I optimized that out, but that is not compatible.
I will always generate that now when the compiler option /memvar is enabled.

**Comment by cpyrgas** [comment]
OK, but does this also cover the visibility in child functions? Because in VO, when you create a memvar with SetMemVar(), this becomes visible only in the entity where this is called, not in entities called by that code (and neither in parent entities of course). When you create the memvar with MEMVAR, the behavior is different... Of course I will also test this myself, once the updated action is available.

Also maybe there should be a compiler warning (or error), when SetMemVar() is used, but /memvar option is disabled?

**Comment by leon-ts** [comment]
Guys,
I drew attention to this ticket, since my application also uses memvars and, as far as I remember, private memvars declared in any way are visible in child functions (and algorithms are guided by this). So I took the example that Chris gave and ran it in my VO (28SP3). Chris, I don't see this behavior in child functions as you wrote. In my VO, in the CheckInChild function, the MyMemVar memvar is visible and does not throw an error (and this is exactly what I expected to see). In the last line in the Start method, an error did occur, but this is correct.

**Screenshot:**
![screenshot1](https://user-images.githubusercontent.com/64518775/223831357-3012e976-138b-4473-af7b-95c2ee5950f4.png)

I'm just worried that something will break in the memvars in the new version.

**Comment by RobertvanderHulst** [comment]
> I drew attention to this ticket, since my application also uses memvars and, as far as I remember, private memvars declared in any way are visible in child functions (and algorithms are guided by this). So I took the example that Chris gave and ran it in my VO (28SP3). Chris, I don't see this behavior in child functions as you wrote. In my VO, in the CheckInChild function, the MyMemVar memvar is visible and does not throw an error (and this is exactly what I expected to see). In the last line in the Start method, an error did occur, but this is correct.

That is exactly how it is intended to work.
The problem that Chris found was that when a function does not have a MEMVAR, PUBLIC or PRIVATE statement, but when it creates a new memvar with MemVarPut() (or VarPut, or in a Macro or Codeblock) then that variable is added to the "MemVarLevel" above the function, because the compiler does not generate code to store the private at the stack level where the MemVarPut() was called.
I have now changed the compiler to detect MemVarPut(), VarPut() and a couple of other functions and to recognize that these functions may create new memvars, so a new MemVarLevel has to be declared and cleared afterward.

**Comment by wriedmann** [comment]
We have tested this now in our reporting engine, and using the suggested __MemVarInit() and __MemVarRelease() method solved our problem in many of our reports (putting them only in the Eval() method of our Report class).
But unfortunately this is really old code, and we have found several places in many VO applications where we use MemVarPut() directly to push variable contents to the report engine evaluator.
So we would like to have a warning when MemVarPut or similar methods are used when an application is compiled without memvar support (both by compiler option and pragma).

**Comment by RobertvanderHulst** [comment]
> We have tested this now in our reporting engine, and using the suggested __MemVarInit() and __MemVarRelease() method solved our problem in many of our reports (putting them only in the Eval() method of our Report class). But unfortunately this is really old code, and we have found several places in many VO applications where we use MemVarPut() directly to push variable contents to the report engine evaluator. So we would like to have a warning when MemVarPut or similar methods are used when an application is compiled without memvar support (both by compiler option and pragma).

Wolfgang,
The warning will not be necessary. I am detecting the use of MemvarPut and similar functions in the compiler now and I am now also generating the  Init/Release code when these are used.

**Comment by cpyrgas** [comment]
Robert, it's better, but still not entirely correct. The following should throw an exception, because the memvar is created in a child function, so it should not be visible in the one calling it, but it actually is. If I uncomment the explicit MEMVAR declaration, then I do get the expected exception

```
FUNCTION Start() AS VOID
	CreateMemVarInAFunction( )
	? MemVarGet( "MyMemVar" ) // Should throw exception

PROCEDURE CreateMemVarInAFunction( )
//	MEMVAR MyMemVar
	MemVarPut( "MyMemVar", "testing123" )
	? MemVarGet( "MyMemVar" ) // testing123, OK

```

**Comment by RobertvanderHulst** [comment]
Chris,
You need the new compiler for this.
I will merge my changes to the main branch and run the action to create new files.

**Comment by RobertvanderHulst** [comment]
Please try again with the compiler in the last run of the ContinuousBuild action.

**Comment by cpyrgas** [comment]
Looks good indeed now! Confirmed fixed.
