### ISSUE TITLE
Type-Help in Visual Studio 2022 shows wrong type (X#2.15.0.3)

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1224]
Visual Studio 2022 shows a wrong type for the following statement:

`
var oIcon := (icon)CreateInstance(#Icon)
`

![image](https://user-images.githubusercontent.com/9860916/223759017-cd9ac4b8-d83f-4ea1-a5e1-f7ccfcc3ccce.png)

**Comment by cpyrgas** [comment]
Confirmed fixed
