### ISSUE TITLE
_DLL FUNCTION With name in Quotes does not work correctly

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1225]
The following code

`_DLL FUNCTION FooBar as LONG PASCAL:Foo."Bar"`
Produces a` [DllImport]` attribute that includes the quores around Bat.
This variation is used to allow mangled names, such as `?GetNumberOfItems@@YAHXZ`

**Comment by RobertvanderHulst** [comment]
The compile also complains about missing LPAREN in the syntax above

**Comment by cpyrgas** [comment]
Confirmed fixed
