### ISSUE TITLE
RP2 PrintPreview shows a blank page when moving to the last page

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1228]
If you preview any report in the designer that has multiple pages:

![image010](https://user-images.githubusercontent.com/14542129/224973600-cb165bdd-71a9-4022-98f4-32c0d9a15a38.png)

Then click the ‘Move To Last Page’ toolbar button you just get a blank page:

![image011](https://user-images.githubusercontent.com/14542129/224973650-1b236d40-d818-467f-8e87-ad48d61698c1.png)

Go back a page and forward again and you get the correct last page:

![image012](https://user-images.githubusercontent.com/14542129/224973721-10f9a724-e7ea-4974-8f3c-713c9aba8c0f.png)

Looks like this was working ok until at least version 2.35.0.4

**Comment by ecosSystem** [comment]
Hi Chris,
I think there are (a lot of) problems in method _CollectPreviewPage() // class PtrDevice
I experienced the same behaviour and changed the method totally. Robert should already have a copy of my changes.
Here is my method:

INTERNAL METHOD _CollectPreviewPage() AS LOGIC STRICT
// This method collects the information that is displayed on the print preview screen.
// This method is for internal use, DO NOT CALL DIRECTLY.
LOCAL nNextPage	AS LONGINT
LOCAL nPage			AS LONGINT
LOCAL nFlag			AS LONGINT

SELF:_StartPage()

nNextPage	:= SELF:nNextPageNo						
nPage			:= min(nNextPage,SELF:aMFCache:Count+1)
nFlag			:= PRINT_ERROR

REPEAT						
	IF SELF:CallPrintSetPage(nPage) < 1
		EXIT
	ENDIF
	SELF:oPreviewWindow:SetPageNo(nPage)
	SELF:nPageNo		:= nPage
	SELF:nNextPageNo	:= nPage
	nFlag					:= SELF:_CollectPage()
	nPage					+= 1	
UNTIL nPage > nNextPage .OR. SELF:Quit .OR. nFlag<>PRINT_OK

SELF:oPreviewWindow:PaintNewPage()

RETURN !(nFlag=PRINT_ERROR)

Hope this helps
Karl

**Comment by cpyrgas** [comment]
Hi Karl,
Thanks a lot! But I'm now getting a runtime error when I use this method:

```
System.DivideByZeroException: Attempted to divide by zero.
   at XSharp.__Float.op_Division(__Float lhs, __Float rhs)
   at ReportPro2.rpPrintPreviewMDI.CalcFormSize() in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\PtrDevPreview MDI - Code (R,S,D).prg:line 117
   at ReportPro2.rpPrintPreviewMDI.PaintNewPage() in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\PtrDevPreview MDI - Code (R,S,D).prg:line 709
   at ReportPro2.PtrDevice._CollectPreviewPage() in C:\ReportPro\Rp2Net\ReportPro2, Runtime\Printing\PtrDev (R,S,D).prg:line 485
```

Also your version of the method is A LOT smaller than the original one, are you sure all that extra stuff that the original code was doing is not necessary? I will also give it a closer look.

**Comment by ecosSystem** [comment]
Hi Chris,

IMHO my code should be enough. I tried to understand what is going on in the original code but in the end I gave up and startet from scratch. For me it works without problems so far.
Your crash is a divide by zero (nPaperwidth) in calcformsize() of the RP-Preview class. In this method two lines are disabled:
//nPaperWidth		:=SELF:oPtrDevice:LogPaperWidth 	// get the logical paper size
//nPaperLength	:=SELF:oPtrDevice:LogPaperLength
I have my own Preview-Window. In my calcformsize() I have enabled these lines. Perhaps you should include
if nPaperwidth = 0
   nPaperWidth		:=SELF:oPtrDevice:LogPaperWidth 	// get the logical paper size
...
endif

Karl

**Comment by cpyrgas** [comment]
Hi Karl,

Thanks, it's very much appreciated of course. And thanks for pointing us in the right direction! I had a close look into the original code and (even though I also still do not fully understand it) I do see a bug in this code:

```
	                DO WHILE nFromPage<=nPage .AND. !SELF:Quit .AND. nFlag==PRINT_OK
                            nFromPage := SELF:CallPrintSetPage(nFromPage+1)
                            SELF:nPageNo		:=nFromPage
                            SELF:nNextPageNo	:=nFromPage
                            nFlag := SELF:_CollectPage()                //Haupt 16.08.2013
                        ENDDO
```

This must be a typo, I think it should be `DO WHILE nFromPage<nPage` ("<" instead of "<=") and when I make this change, it seems to work well, but will need further testing of course. But does your method fixes other issues, too?

**Comment by ecosSystem** [comment]
Hi Chris,

I don't know if it also fixes other issues. I remember the problem was only in handwritten reports. Designer-reports always seemed to work fine. I simply had the impression that the method was changed several times to fix specific issues with more and more if's...
The RemoveCache-part at the end didn't increase my confidence either. So I decided to start from scratch. It should not make any difference to skip to the last page or to skip to any page. It should neither make any difference whether a report is handwritten or not. In the end my code worked and I forgot about it...

**Comment by ecosSystem** [comment]
I agree with you, therefore it is most important to have the sourcecode where I can keep my changes. This is also why I marked 1000 € for enhancements in the poll. To fully understand ReportPro I think a lifetime is not enough...

**Comment by cpyrgas** [comment]
Totally agreed :)

**Comment by cpyrgas** [comment]
Fixed and confirmed by customer (Leigh)
