### ISSUE TITLE
DBServer error in exclusive mode

### ISSUE THREAD

**Issue by ecosSystem** [X-Sharp/XSharpPublic#1230]
Hi Robert,

maybe I'm wrong, but I think there is a bug in DBServer:Commit:

BEGIN SEQUENCE
		VODBSelect( wworkarea, OUT dwCurrentWorkArea )
		SELF:__OptimisticFlush( )
		lRetCode := __DBSCommit( nTries )
		__DBSSetSelect( dwCurrentWorkArea )  //SE-060527
...
	END SEQUENCE
...
	IF lRetCode
		IF ! SELF:lShared
			SELF:___InitRecordBuf( )
		ENDIF
	ELSE
...

Inside the sequence, after __DBSCommit, the current workarea is reset via __DBSSetSelect( dwCurrentWorkArea)
Inside ___InitRecordBuf() VoDbFieldGet() is called without switching the workarea. aOriginalBuffer is then filled with wrong values and even crashes:
Fehlercode: 	BEREICHSGRENZEN-FEHLER
Subsystem: 	XSharp.Rdd
Beschreibung: 	Der Index war außerhalb des Arraybereichs.

I fixed the crash in my DBServer-subclass with:

METHOD __InitRecordBuf( ) AS VOID STRICT
LOCAL dwCurrentWorkArea AS DWORD
	
VODBSelect( wworkarea, OUT dwCurrentWorkArea )
SUPER:__InitRecordBuf()
__DBSSetSelect( dwCurrentWorkArea )
	
RETURN

Karl

**Comment by cpyrgas** [comment]
Indeed, that looks like a bug in the SDK code (also in the VO version). It happens only when DbSetRestoreWorkarea() is set to TRUE.

Sample to reproduce, the following prints
abc
NIL
NIL
123

when DbSetRestoreWorkarea() is set to FALSE, then it gives the expected correct results:

abc
abc
abc
abc

```
FUNCTION Start() AS VOID

LOCAL cDbf1,cDbf2 AS STRING
cDbf1 := "c:\test\dbfone"
cDbf2 := "c:\test\dbftwo"

DbCreate(cDbf1, {{"FLD1","N",10,0}})
DbCreate(cDbf2, {{"FLD1","C",10,0},{"FLD2","C",10,0}})

DbSetRestoreWorkarea(TRUE)

LOCAL oDBServer AS MyDBServer
oDBServer := MyDBServer{cDbf2 , FALSE}
oDBServer:Append()
oDBServer:FIELDPUT(1,"abc")
oDBServer:GoTop()
? "aOriginalBuffer before commit", oDBServer:GetOriginalBufferValue(1)
oDBServer:Commit()
? "aOriginalBuffer AFTER commit", oDBServer:GetOriginalBufferValue(1)

DbUseArea(TRUE,,cDbf1)
DbAppend()
FieldPut(1,123)

? "aOriginalBuffer before commit", oDBServer:GetOriginalBufferValue(1)
oDBServer:Commit()
? "aOriginalBuffer AFTER commit", oDBServer:GetOriginalBufferValue(1)

oDBServer:Close()

RETURN

CLASS MyDBServer INHERIT DbServer
	CONSTRUCTOR(oFile, lShareMode, lReadOnlyMode, xDriver)
		SUPER(oFile, lShareMode, lReadOnlyMode, xDriver)
	METHOD GetOriginalBufferValue(nField) AS USUAL
		RETURN SELF:aOriginalBuffer[BUFFER_VALUE,nField]
END CLASS

```

**Comment by cpyrgas** [comment]
Confirmed fixed
