### ISSUE TITLE
Implicit conversion from NULL_PSZ to STRING should generate NULL

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1234]
Implicit conversion from NULL_PSZ to STRING should generate NULL
See https://www.xsharp.eu/forum/private-product/3437-x-runtime-advantage-part-2

**Comment by RobertvanderHulst** [comment]
Chris,
I'll see what I can do.
I assume you changed the NULL to NULL_STRING in VO?. In VO all four of these return TRUE.
In X# I indeed see False / True/ True / False when vo2 is off. When vo2 is ON then I see True / True False / False (when NULL is changed into NULL_STRING).

**Comment by cpyrgas** [comment]
Confirmed fixed and the warning message looks good!
