### ISSUE TITLE
Output in Debugger of Action "CALLSTACK" does not show class names

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1236]
If you make an Tracepoint with an Output Action "$CALLSTACK" in the debugger, the Callstack does not show any class names for X# classes

![image](https://user-images.githubusercontent.com/20905638/229994087-9f5f830a-6fa6-4cc1-92dc-a35a2e20cdba.png)

Example Output 
```
	XSharpTests.exe!TestMethod
	XSharpTests.exe!Start
```
[XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/11155710/XSharpTests.zip)

**Comment by cpyrgas** [comment]
@hpetriffer please confirm this when the new beta build becomes available
