### ISSUE TITLE
DBFCDX: Error when automatically closing RELATIONs

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1237]
If a workarea has an related workarea, an exception is thrown when the parent workarea is closed.

**Example solution:**
[TestConsoleApplication.zip](https://github.com/X-Sharp/XSharpPublic/files/11157399/TestConsoleApplication.zip)

**Environment:**
IDE: VS2019
X# 2.14.0.4
RDD: DBFCDX

**Comment by cpyrgas** [comment]
Confirmed fixed
