### ISSUE TITLE
Transform() function does not support the "Scroll" S picture

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1239]
https://www.xsharp.eu/forum/public-product/3449-transform-function#25863

sample cases:

? Transform(1234567890 , "@S5 999999999999") // "  123"
? Transform("1234567890" , "@S5") // "12345"
? Transform(Condate(2000,1,1) , "@S5") // "01/01"

**Comment by RobertvanderHulst** [comment]
Added small optimization in df70b6feae90044dc553a23f30dfa87c2dde3327
