### ISSUE TITLE
Cannot add VS reference to project, when one of previous references is missing

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#124]
Open the attached solution, go to the main project ConsoleApplication and select "Add Reference". Select any reference from the ".Net" tab and press OK, VS responds with

Object reference not set to an instance of an object.

and reference is not being added. Problem is because "ExistingProject" library is referenced also, but the .dll does not physically exist. If you d a build all, so that dll is created, now it is possible to add references.
[VS_references2.zip](https://github.com/X-Sharp/XSharpPublic/files/3477106/VS_references2.zip)

**Comment by RobertvanderHulst** [comment]
This is already fixed

**Comment by cpyrgas** [comment]
Issue reopened, problem still happens in the test 2.0 build
