### ISSUE TITLE
Difference in behavior of overridden methods in XBase++ and X#

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1244]
**Describe the bug**
X# compliler flag -vo3 isn't work. In addition, method modifiers such as `final`, `introduce`, `override` are not supported.

**To Reproduce**
```
procedure Main()
    local o
    
    o := DerivedExample():new()
    ? o:SayHello()
    
    return
    

class DerivedExample from Example
exported:
    inline method Name()
        return "DerivedExample"
endclass


class Example
exported:
    inline method Name()
        return "Example"

    inline method SayHello()
        return "Hello, I am " + ::Name()
endclass
```

**Expected behavior (xBase++ exe)**
Output
```
Hello, I am DerivedExample
```

**Actual behavior (with -vo3)**
X# compiler
```
warning XS9201: XPP The 'FROM' clause is interpreted as SHARING because variables in parent classes are always shared in the .Net Runtime.
warning XS0108: DerivedExample.Name(params usual[])' hides inherited member 'Example.Name(params usual[])'. Use the new keyword if hiding was intended.
```
X# exe output
```
Hello, I am Example
```
When I rewrote the `DerivedExample.Name()` method with a modifier `introduce`:
```
class DerivedExample from Example
exported:
    inline introduce method Name()
        return "DerivedExample"
endclass
```
I get X# compiler error:
```
error XS9002: Parser: unexpected input 'introduce'
```
The situation is similar with the other listed modifiers.

XBase++ with `introduce` outputs:
```
Hello, I am Example
```

**Additional context**
X# Compiler version 2.14.0.4 (release)
xsc.exe -dialect:xBase++ -xpp1 -lb -memvar -vo1 -vo3 -vo5 -vo10 -vo15 -vo16

**Comment by RobertvanderHulst** [comment]
I see that the /vo3 compiler option (all methods virtual) is not properly applied for Xbase++. This will also be fixed in 2.16.

**Comment by RobertvanderHulst** [comment]
I will also verify the other Xbase++ specific modifiers, such as final, introduce and override.

**Comment by cpyrgas** [comment]
Confirmed fixed
