### ISSUE TITLE
Cannot use NEW modifer on a PROTECT/EXPORT

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1246]
The code below produces 2 warnings 

```
warning XS0108: 'Child.e' hides inherited member 'Parent.e'. Use the new keyword if hiding was intended.
warning XS0108: 'Child.p' hides inherited member 'Parent.p'. Use the new keyword if hiding was intended.
```

but changing the code to use NEW EXPORT and NEW PROTECT results to `error XS9002: Parser: unexpected input 'e'`

In c#, this is working (I did not know that!).

Fun fact, in c#, if you specify `new public int nnn;` and there's no parent field with that name, the compiler only reports a warning that the "new" modifier is not needed (`warning CS0109: The member 'parent.nnn' does not hide an inherited member. The new keyword is not required.`), but no errors! Which is nonsense, considering how extremely strict c# is in so many other similar cases...

```
CLASS Child INHERIT Parent
	EXPORT e := 1 AS INT
	PROTECT p := 1 AS INT
END CLASS

CLASS Parent
	EXPORT e := 2 AS INT
	PROTECT p := 2 AS INT
END CLASS
```

**Comment by RobertvanderHulst** [comment]
Did you investigate this in relation to the Xbase++ example with a field with the same name in the parent class and the child class?

**Comment by cpyrgas** [comment]
Exactly!

**Comment by cpyrgas** [comment]
Confirmed fixed
