### ISSUE TITLE
Error in MemRealloc function

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1248]
As written in the X# documentation, when changing the size of the allocated memory by the MemRealloc function, if a smaller size is specified than already allocated, the function returns the same address. This is what happens when you first reduce the size. But if you reduce the size again, the MemRealloc function returns NULL_PTR.

**Example:**
```
LOCAL p1, p2, p3 AS PTR

TRY
	p1 := MemAlloc(1000) // OK: new address
	p2 := MemRealloc(p1, 800) // OK: the same address, as the new size is smaller than the old size
	p3 := MemRealloc(p2, 100) // ERROR: should return the same address, but returned NULL_PTR
FINALLY
	IF (p3 != NULL_PTR)
		MemFree(p3)
	ELSEIF (p2 != NULL_PTR)
		MemFree(p2)
	ELSEIF (p1 != NULL_PTR)
		MemFree(p1)
	ENDIF
END TRY
```
In the example, the address stored in p2 remains valid, but working with it starts causing memory problems (after the failed p3).

**Environment:**
X# 2.14.0.4
IDE: VS2019

**Comment by RobertvanderHulst** [comment]
Good catch. Fixed in next build.
When reducing the size from 1000 to 800 bytes, we were trying to clear the last 200 bytes. But there was a calculation error, and it was clearing from the wrong offset, overwriting memory after the allocated block.
Strictly speaking, there is no real need to clear this memory. We can remove that too if you think that is a good idea.

**Comment by leon-ts** [comment]
Robert,

> We can remove that too if you think that is a good idea.

In freed memory, it shouldn't matter if it's cleared or not. But if the same action was done in VO, then I suggest leaving the memory clearing. Who knows what tricks they envisioned with it.

**Comment by RobertvanderHulst** [comment]
I see that VO actually calls the Heap Reallocate and moves the block end marker for the block forward, when the block shrinks and adjusts the length byte in the block header to indicate the new size.
(Each block in VO and X# is marked with a header and footer with a magic number).
As a result, in your example code, after the MemRealloc(800), MemCheckPtr(p1,1000) returns false after p2 was allocated and MemCheckPtr(P1, 800) returns TRUE.
I will adjust our code to do something similar.

**Comment by cpyrgas** [comment]
Confirmed fixed
