### ISSUE TITLE
X# preprocessor incorrectly replaces UDC (dialect XBase++)

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1250]
**Describe the bug**
X# preprocessor incorrectly replaces UDC (dialect XBase++)

**Example 1. To Reproduce .prg**
```
/** 
 * enum EnumType {CONST1("desc1"), CONST2("desc2")}
 *      =>
 * class EnumType from Enum
 * exported:
 *      class var CONST1 readonly
 *      class var CONST2 readonly
 *      inline class method initClass()
 *          local i := 0
 *          ::CONST1 := EnumType():new(++i, "CONST1", desc1)
 *          ::CONST2 := EnumType():new(++i, "CONST2", desc2)
 *          ::setValues({::CONST1, ::CONST2})
 *      return
 * endclass
 */
#xtranslate enum <EnumType> { <var1>[(<desc1,...>)] [,<varN>[(<descN,...>)]] };
    =>;
class <EnumType> from Enum;;
exported:;;
    class var <var1> readonly;
    [;class var <varN> readonly];;
    inline class method initClass();;
        local i := 0;;
        ::<var1> := <EnumType>():new(++i, <"var1">[, <desc1>]);
        [;::<varN> := <EnumType>():new(++i, <"varN">, <descN>, nil)];; // [, <descN>] - error XBT0513; без NIL - warning XBT0124
        ::setValues({::<var1>[,::<varN>]});;
    return;;
endclass

#xtranslate enum <EnumType> { <var1>[(<desc1,...>)]  };
    =>;
class <EnumType> from Enum;;
exported:;;
    class var <var1> readonly;;
    inline class method initClass();;
        ::<var1> := <EnumType>():new(1, <"var1">[, <desc1>]);;
        ::setValues({::<var1>});;
    return;;
endclass

enum Quality {GOOD("Well"), BETTER("Stronger"), BEST("Great")}
```

**Expected behavior (xBase++ .ppo)**
Output
```
class Quality from Enum;exported:;class var GOOD readonly;class var  BETTER readonly;class var  BEST readonly;inline class method initClass();local i := 0;::GOOD := Quality():new(++i, "GOOD",  "Well");:: BETTER :=  Quality():new(++i, "BETTER",  "Stronger", nil);:: BEST :=  Quality():new(++i, "BEST",  "Great", nil);::setValues({::GOOD,:: BETTER,:: BEST});return;endclass
```

**Actual behavior (X# .ppo)**
```
class Quality from Enum; exported:; class var GOOD("Well") readonly ;class var BETTER("Stronger") readonly;class var BEST("Great") readonly ; inline class method initClass(); local i := 0; ::GOOD("Well") := Quality ():new(++i, "GOOD("Well")"  ) ;::BETTER("Stronger") := Quality ():new(++i, "BETTER("Stronger")" ,  , nil);::BEST("Great") := Quality ():new(++i, "BEST("Great")" ,  , nil) ; ::setValues({::GOOD("Well") ,::BETTER("Stronger"),::BEST("Great") }); return; endclass
```
If I write an enumeration in this way,
```
enum Quality {;
    GOOD("Well"), BETTER("Stronger"), BEST("Great");
}
```
then the X# preprocessor does not recognize it.

**Additional context**
X# Compiler version 2.14.0.4 (release)
-dialect:xBase++ -xpp1 -lb -memvar -vo1 -vo3 -vo5 -vo10 -vo15 -vo16

**Comment by RobertvanderHulst** [comment]
This example depends on an Enum class. Can you include the code for that class too?
Or are you trying to do this with the .Net enum class?

**Comment by DenGhostYY** [comment]
[enum.zip](https://github.com/X-Sharp/XSharpPublic/files/11369612/enum.zip)
Unfortunately, our Alaskan enum managed to acquire additional features

**Comment by RobertvanderHulst** [comment]
Which incoding are these source files in?

**Comment by DenGhostYY** [comment]
DOS 866

**Comment by RobertvanderHulst** [comment]
The problem in this case seems to be in the handl;ing of 
enum <EnumType> { <var1>[(<desc1,...>)] [,<varN>[(<descN,...>)]] };

when matching the <var1> token we encounter the '(' token and we do not match that with the '(' inside the optional description part. I'll see if I can fix that.
If I remove the descriptions, then it compiles.
Btw: we do not support readonly class variables (.Net does not support that). Would it be an idea to compile these into auto properties with only a getter

**Comment by RobertvanderHulst** [comment]
In the base class Enum I see a problem that you have instance variables with the same name as methods.
That is not allowed in .Net,

**Comment by DenGhostYY** [comment]
I agree about the same names for variables and class methods. But not about readonly class variables. Example in C#:

**Comment by RobertvanderHulst** [comment]
We have added support for readonly in the 2.16 compiler

**Comment by cpyrgas** [comment]
I'm not entirely sure of the correct behavior after the fix (compiler currently gives an error on the original code "error XS0644: 'Quality' cannot derive from special class 'System.Enum'"), so I will let @DenGhostYY confirm this one.

**Comment by RobertvanderHulst** [comment]
Chris,

> I'm not entirely sure of the correct behavior after the fix (compiler currently gives an error on the original code "error XS0644: 'Quality' cannot derive from special class 'System.Enum'"), so I will let @DenGhostYY confirm this one.
The Enum type is a class that Leonid's company created themselves.

**Comment by cpyrgas** [comment]
OK, it's confirmed fixed then!
