### ISSUE TITLE
Different by default behavior in various dialects

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1252]
As mentioned in

https://www.xsharp.eu/forum/welcome/3491-inconsistent-str-evaluation-when-decimal-not-specified#26194

apparently Harbour initializes with SetDecimal(0), so by default 

`Str(123.456,10)`

prints "       123" in it, while in VO (and currently in X#) it prints "    123.46"

Maybe we should automatically insert some initialization code in $AppInit(), which initializes various setting depending on the dialect?

**Comment by RobertvanderHulst** [comment]
Chris,
I think it is better to start working on a XSharp.Harbour project/DLL (XSharp.HB?) and add initialization code like that in this DLL.
Then the language specific settings are visible in the runtime solution.
We can then use that project for other Harbour specific things too.

**Comment by cpyrgas** [comment]
Agreed. I had suggested the above only because there's no XSharp.Harbour dll currently, but it's better to introduce it.

**Comment by RobertvanderHulst** [comment]
So, shall we go for XSharp.HB or for XSharp.Harbour ?
I'll have to introduce this name in the compiler too, because we're handling "our" DLLs a bit different than other DLLs

**Comment by cpyrgas** [comment]
XSharp.Harbour sounds better to me

**Comment by cpyrgas** [comment]
Looks like the new dll was not included in the installer

**Comment by cpyrgas** [comment]
Confirmed done
