### ISSUE TITLE
Intellisense problem typing unknown File class

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1255]
If you write "File." (unknown class here because there is no using for System.IO) in the following example, you get the following results for intellisense
![image](https://github.com/X-Sharp/XSharpPublic/assets/20905638/04f6dc98-ba14-4fae-9a68-3a7518cdbb0a)

Pressing ESC and the CTRL+ SPACE there are the following results
![image](https://github.com/X-Sharp/XSharpPublic/assets/20905638/0a83e841-fa18-4419-81e7-4f9c5127e2ae)

The strange thing here is that I get suggenstions, that are not in this solution (and also not in the folder of the solutions, not in included assemblies and also not in assemblies from the GAC). It seems that it displays results from other open Visual Studio instances.

In the first case, selecting e.g. CompareTo and then "Go to definition" the result is:
![image](https://github.com/X-Sharp/XSharpPublic/assets/20905638/b323c2ac-c3af-4ea5-9450-2376c8af29e9)

[XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/11463524/XSharpTests.zip)

**Comment by RobertvanderHulst** [comment]
The language service resolves the word 'File' incorrectly with the File function and then offers completion for the return type of that function (LOGIC) show it shows the members of the System.Boolean type

**Comment by hpetriffer** [comment]
An additional information to the entries that are not in the solution. It seems that sometimes entries from a previous opened solution are added. Today I hat an case with a  small solution, where first the .vs directory does not exist. First I opened another solution and after that the small one. After that I had all entries from the first solution in the database. It is not always reproducable.

**Comment by cpyrgas** [comment]
Confirmed fixed
