### ISSUE TITLE
Coloring of Text .. EndText incorrect in sample below

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1257]
```
FUNCTION Start() AS VOID STRICT
    local lcString as string
    local test := 2 as long
    IF test == 1 THEN
        TEXT TO lcString NOSHOW TEXTMERGE FLAGS 1+2 PRETEXT 1+2+4
        INSERT INTO employees (FULLNAME,SALARY,ADDATE, ADTIME)
        VALUES (?vlFULLNAME,?vlSALARY,?vlADDATE, ?vlADTIME)
        ENDTEXT
    ELSE
        TEXT TO lcString NOSHOW TEXTMERGE FLAGS 1+2 PRETEXT 1+2+4
        UPDATE employees SET FULLNAME = ?vlFULLNAME, SALARY = ?vlSALARY
        WHERE ID = ?vlId
        ENDTEXT
    ENDIF 
    ? lcString
    WAIT
    RETURN
```

**Comment by RobertvanderHulst** [comment]
Fixed in https://github.com/X-Sharp/XSharpDev/commit/83e4c39d8b1f3497cbbef3f9b092457ff6f3c990
See image:
![image](https://github.com/X-Sharp/XSharpPublic/assets/14240939/23a45708-7ac8-4461-bc67-b3e07f792ae6)

**Comment by cpyrgas** [comment]
Doesn't look corr3ect here, but I'm not suew if I have the VS integration version that fixes this

**Comment by cpyrgas** [comment]
Robert, this is how it looks here at the moment, doesn't look right to me:

![TEXT_TO_coloring](https://github.com/X-Sharp/XSharpPublic/assets/14542129/8cea300c-12b6-4d06-9994-e6892da66a1d)

**Comment by RobertvanderHulst** [comment]
Chris,
Are you sure you have the FoxPro dialect enabled and that you are including the standard header file?
The NOSHOW, TEXTMERGE etc are FoxPro specific options of the TEXT ENDTEXT command

**Comment by cpyrgas** [comment]
Robert,
No I am not sure, problem confirmed fixed :)
