### ISSUE TITLE
VS Integration: incorrect tooltip for some generic classes

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1258]
The description of the problem is illustrated in the screenshots below:

**Mouse cursor hovered over the word Dictionary**
![Screenshot1](https://github.com/X-Sharp/XSharpPublic/assets/64518775/f32dd86c-6e69-4040-b15a-22a96fc25c1d)
Expected: `public class System.Collections.Generic.Dictionary<TKey, TValue> ...`

**Mouse cursor hovered over the word SortedList**
![Screenshot2](https://github.com/X-Sharp/XSharpPublic/assets/64518775/3ec99bae-215a-42ec-a3de-0cbf3d7bfb9a)
Expected: `public class System.Collections.Generic.SortedList<TKey, TValue> ...`

**Environment:**
X# 2.16.0.5
IDE VS2019

**Comment by leon-ts** [comment]
Robert,
Hovering over the word Dictionary now displays the correct hint. But there is a discrepancy when hovering the mouse cursor over local variables and class fields.

**Example:**
```
FUNCTION Start() AS VOID STRICT

	LOCAL dic AS Dictionary<STRING, INT>
	LOCAL sl AS SortedList<STRING, INT>

	RETURN

CLASS TestClass

	PRIVATE dic AS Dictionary<STRING, INT>
	PRIVATE sl AS SortedList<STRING, INT>

END CLASS
```

If you hover over the 'dic' and 'sl' fields in the TestClass class, then the correct generic class types are displayed (in the example, these are the STRING and INT types). This is right. But if you hover over the local variables 'dic' and 'sl' in the Start function, the general help hint for TKey and TValue is displayed.

This is another problem that I did not describe in this ticket. So let me know if I need to create a new ticket or should we continue with this?

**Comment by cpyrgas** [comment]
Problem reported here confirmed fixed, but there are several other related problems with generic methods, logged them as https://github.com/X-Sharp/XSharpPublic/issues/1300
