### ISSUE TITLE
COPY TO ARRAY should shrink the array when needed

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1262]
See https://www.xsharp.eu/forum/public-vfp/3511-copy-to-array#26422

**Comment by RobertvanderHulst** [comment]
This was wrong

**Comment by cpyrgas** [comment]
Robert, this was discussed to be wrong, but the change already made for this ticked in the code in https://github.com/X-Sharp/XSharpPublic/commit/c31cdb025e7b5add333a3fd1ae07304ba4e5dcda#diff-756849248cb0c363072a857399d491a3b7f9231224cc4faadfd7fed9c227398c is still active, is this intended?

**Comment by RobertvanderHulst** [comment]
Chris,
This was rolled back in 744c99d1c5fad26e9fe51ef6ac2e7aec8393b5c7

**Comment by cpyrgas** [comment]
Ahhh, right, I saw the new line of code (`aFox:__Fill(NIL)`) that was inserted in the new commit, but did not notice it also deleted the previous added line.
