### ISSUE TITLE
VS Integration: delegate signature not showing in Intellisense tooltips

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1265]
Example on the screenshot:
![Screenshot1](https://github.com/X-Sharp/XSharpPublic/assets/64518775/5c16ebe6-ad5d-41bf-9e3a-548bc305b0d1)

**Environment:**
X# 2.16.0.5
IDE VS2019

**Comment by leon-ts** [comment]
Robert,
The issue described in this ticket has been fixed. But the hint is no longer displayed when the mouse cursor is hovered over the place where the delegate is defined. That is, if you move the mouse cursor over the name TestDelegate in this line:
```
/// <summary>
/// Test delegate.
/// </summary>
/// <param name="a">A</param>
/// <param name="b">B</param>
DELEGATE TestDelegate(a AS INT, b AS INT) AS INT STRICT
```
then there will be no hint. At the same time, hints for other types are displayed in the places where they are defined. For example, for classes.

I did not describe this problem in this ticket (but, perhaps, it was not in the previous version, and I have 2.16.0.6 now). Therefore, please let me know if I need to create a new ticket and close this one as fixed?

**Comment by cpyrgas** [comment]
Confirmed fixed
