### ISSUE TITLE
In some cases the compiler shows the wrong line number with an error

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1268]
In the following example, the SWITCH statement is closed incorrectly (ENDIF is used instead of the END SWITCH keyword):

```
LOCAL x := 0 AS INT
	
BEGIN SEQUENCE
	
	IF (x > 0)
		IF (x < 10)
			SWITCH x
			CASE 1
			CASE 2
			CASE 3
				? "1 or 2 or 3"
			ENDIF
		ENDIF
	ELSE
		? "else"
	ENDIF

END SEQUENCE
```

But the compiler reports this error:
> XS9002 Parser: unexpected input 'ELSE'

and points to the line with the last ELSE.

**Environment:**
X# 2.16.0.5
IDE VS2019

**Comment by RobertvanderHulst** [comment]
Fixed with an earlier commit

**Comment by leon-ts** [comment]
Fixed!
