### ISSUE TITLE
Invalid entries with Intellisense after self.

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1270]
After "self." I get a lot of invalid entries:
![image](https://github.com/X-Sharp/XSharpPublic/assets/20905638/26a0c0a5-bba8-4e4e-b75a-696f453b0f08)

Attached is the solution with this behaviour.
[XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/11621768/XSharpTests.zip)

**Comment by hpetriffer** [comment]
May be it is a duplicate from #1255

**Comment by RobertvanderHulst** [comment]
I don't think this is a duplicate. For #1255, there is a match with the File function. Self is usually available inside methods.

**Comment by cpyrgas** [comment]
Confirmed fixed
