### ISSUE TITLE
VS Integration: Coloring is turned off when using some UDC calls

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1272]
The following screenshot illustrates the problem:
![Screenshot1](https://github.com/X-Sharp/XSharpPublic/assets/64518775/cc218dc2-d054-4ee8-9406-9ccea814e21f)

Here LOAD_BEGIN is the UDC into which the string was passed. After this line, all other lines lost their correct coloring (circled in red in the screenshot).

**UDC**
```
#command LOAD_BEGIN(<cKOD>) => ;; ;
IF DBSEEK(<cKOD>)

#command LOAD_COMPLETE() => ;; ;
ENDIF

#command LOAD_TEXT_PROPERTY(<sField>,<cControl>) => ;; ;
  <cControl>:TextValue := AllTrim(FieldGetSym(<sField>))

#command LOAD_INT_BOOLEAN_PROPERTY(<sField>,<oControl>) => ;; ;
  <oControl>:Checked := (FieldGetSym(<sField>) == 1)

#command LOAD_TEXT_BOOLEAN_PROPERTY(<sField>,<oControl>) => ;; ;
  <oControl>:Checked := (AllTrim(FieldGetSym(<sField>)) == "1")
```

UPDT: As it turned out, not only the colors stopped working, but Intellisense stopped working altogether.

**Example project:**
[TestConsoleApplication.zip](https://github.com/X-Sharp/XSharpPublic/files/11636711/TestConsoleApplication.zip)

**Environment:**
X# 2.16.0.5
IDE VS2022

**Comment by leon-ts** [comment]
UPDT: As it turned out, not only the colors stopped working, but Intellisense stopped working altogether.

**Comment by RobertvanderHulst** [comment]
You really like to stress the editor, don't you 😄 :

**Comment by leon-ts** [comment]
Robert,
I am not guilty :)
This is a real application that has been migrated from VO, and I am currently making changes to the code. To be honest, I don't really like UDC myself, as it makes it difficult to analyze unfamiliar code.

**Comment by RobertvanderHulst** [comment]
The problem seems to be the fact that there are some unneeded semicolons in your definition:
If you change 
```
#command LOAD_BEGIN(<cKOD>) => ;; ;
IF DBSEEK(<cKOD>)

#command LOAD_COMPLETE() => ;; ;
ENDIF
```

to 
```
#command LOAD_BEGIN(<cKOD>) =>  ;
IF DBSEEK(<cKOD>)

#command LOAD_COMPLETE() =>  ;
ENDIF
```
then it works correctly.

The extra `;;` inserts an empty statement in the output and that seems to confuse the editor parser. Why did you add these?

**Comment by leon-ts** [comment]
Robert,
I don't know why there are multiple semicolons. I didn't add them. So it was in VO, from where it migrated to X# in its original form (except for bringing it to the new X # syntax). In VO, my other colleagues did it.

**This is how it looked in VO:**
```
****************************************************************************
* LOAD_BEGIN(<cKOD>)
****************************************************************************
LOAD_BEGIN(<cKOD>) => ;; ;
IF DBSEEK(<cKOD>)

****************************************************************************
* LOAD_COMPLETE()
****************************************************************************
LOAD_COMPLETE() => ;; ;
ENDIF

etc.
```

**Comment by RobertvanderHulst** [comment]
Ok, understood. I have made a change to handle this correctly. The output now looks like this:
![image](https://github.com/X-Sharp/XSharpPublic/assets/14240939/18d1238c-fee1-4100-a08b-739152103a7c)

**Comment by leon-ts** [comment]
Fixed!
