### ISSUE TITLE
VS Integration: hint not showing for generic methods

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1273]
There is the following class example:

```
/// <summary>
/// TestClass class.
/// </summary>
CLASS TestClass

	/// <summary>
	/// DoSomething method.
	/// </summary>
	METHOD DoSomething() AS VOID STRICT
		RETURN

	/// <summary>
	/// DoSomethingGeneric method.
	/// </summary>
	METHOD DoSomethingGeneric<T>(x AS T) AS T STRICT
		RETURN x

END CLASS
```

Hovering over the DoSomethingGeneric method will not display the hint. On other members of the class, including the class definition itself, the hint is displayed.

**Environment:**
X# 2.16.0.5
IDE VS2022

**Comment by leon-ts** [comment]
Fixed!

**Comment by leon-ts** [comment]
Chris, I re-opened this ticket in case it's a related issue and in fixing it we also checked that the original issue didn't come back.

**Comment by RobertvanderHulst** [comment]
Guys,
`SELF:DoSomethingGeneric<INT>(1) ` 
was showing the tooltip.
`SELF:DoSomethingGeneric(1) ` 
not.
I have changed the code now that when the search for the non-generic method does not return results, then I will try to search for the generic method.

**Comment by cpyrgas** [comment]
Confirmed fixed
