### ISSUE TITLE
CToD returns wrong result with right spaces

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#1275]
Consider this:
```
	SetDateFormat("DD.MM.YYYY")
	SetEpoch(1940)
	
	? CToD("01.01.23")	// prints 01.01.2023 as it should
	? CToD("01.01.2023")	// prints 01.01.2023 as it should
	? CToD("01.01.23  ")	// prints 01.01.0023 while it should be 01.01.2023
```
This issue is a regression: fails in X# 2.16.0.5 and works in 2.14 as expected. Such an untrimmed string often comes from edit controls where user may enter a two-digit year as a shorthand.

Perhaps, here is the reason:
![image](https://github.com/X-Sharp/XSharpPublic/assets/9467830/41a09685-f307-4f5d-b7a9-bd4e4f58e7e5)

**Comment by cpyrgas** [comment]
Robert, if you'd like I can research (how VO behaves in various related cases) and fix this (adjust it to to work the same in X#). Just please tell me know what did this https://github.com/X-Sharp/XSharpPublic/commit/58813054ebd9aff7a8adaeb385dd4fe8bc658328 commit fixed, so I will cover this as well.

**Comment by RobertvanderHulst** [comment]
I created this change because of a problem that I saw in a customer code. The customer did this (date format MM/DD/YYYY)
CTOD("12/31/"+Str(nYear)) and this created a year number with 6 leading spaces, which was handled correctly in VO but not in X#. This resulted in an empty date in X#.

**Comment by RobertvanderHulst** [comment]
I created this change because of a problem that I saw in a customer code. The customer did this (date format MM/DD/YYYY)
CTOD("12/31/"+Str(nYear)) and this created a year number with 6 leading spaces, which was handled correctly in VO but not in X#. This resulted in an empty date in X#.

**Comment by cpyrgas** [comment]
OK, thanks, from what I see VO handles even this "correctly":

CToD("01.02.1*2-$ @ 2023   ")

and produces 01/02/2023, looks like it trims the string and then uses only the 4 last remaining characters from the year part, ignoring anything before those.

Will research it a bit more and will try to make the X# implementation as close as possible to VO. Will then send @Serggio an updated dll to give it a test as well

**Comment by cpyrgas** [comment]
Completely emulating VO's tremendously inconsistent behavior in all cases is simply impossible, so I added a special implementation only for the case where the year is specified last in the date format template. This makes this special (but most commonly used) case compatible enough (but still not 100%) to VO. In all other cases, the previous X# behavior is kept for now.

That should be good enough for the reported issues, @Serggio can you please give this updated dll a try?

[XSharp.Core_DToC() fix.zip](https://github.com/X-Sharp/XSharpPublic/files/11675929/XSharp.Core_DToC.fix.zip)

**Comment by Serggio** [comment]
> @Serggio can you please give this updated dll a try

It works fine! Thank you!
