### ISSUE TITLE
Missing constructor parameter list lint on generic class

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1277]
There's no parameter list tooltip shown when instantiating a gereic type:

```
LOCAL dic AS Dictionary<STRING, INT>
dic := Dictionary<STRING, INT>{  // no parameter list

List<INT>{ // no parameter list

```

**Comment by leon-ts** [comment]
Chris,
In this example, I have a tooltip displayed (new build 2.16.0.6).

**Demo video:**
[ScreenRecorderProject1.zip](https://github.com/X-Sharp/XSharpPublic/files/11685572/ScreenRecorderProject1.zip)
