### ISSUE TITLE
Internal Compiler Error with DO CASE statement missing CASE/OTHERWISE

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1281]
Following causes an ICE, instead of reporting a proper error:

/*
warning XS9076: Empty CASE statement
error XS9999: An internal compiler error has occurred: 'Object reference not set to an instance of an object.',    at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpTreeTransformationCore.ExitConditionalStatement(XSharpParserRuleContext context, IList`1 conditions, StatementBlockContext elseBlock)
   at LanguageService.CodeAnalysis.XSharp.SyntaxParser.XSharpParser.CaseStmtContext.ExitRule(IParseTreeListener listener)
   at LanguageService.SyntaxTree.Tree.ParseTreeWalker.ExitRule(IParseTreeListener listener, IRuleNode r)
   at LanguageService.SyntaxTree.Tree.ParseTreeWalker.Walk(IParseTreeListener listener, IParseTree t)
   at LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.XSharpLanguageParser.ParseCompilationUnitCore()

*/
FUNCTION Start( ) AS VOID
DO CASE

ENDCASE

**Comment by cpyrgas** [comment]
Doesn't seem right to me, now the original code reports "warning XS9076: Empty CASE statement", but isn't that incorrect? There's no empty CASE statement, there's no CASE statement at all, so this should be an error, shouldn't it?

Also there are no warnings at all reported for empty CASE, IF etc statements, I think there used to be one in previous builds:


```
FUNCTION Start( ) AS VOID

// warning XS9076: Empty CASE statement
DO CASE
END CASE

// no warnings at all below:
DO CASE
CASE FALSE
CASE TRUE
ENDCASE

IF TRUE
ELSE
ENDIF
```

**Comment by RobertvanderHulst** [comment]
Chris,
It depends on what you call a `CASE Statement`
For me, that is the total `DO CASE .. CASE .. OTHERWISE .. ENDCASE` construct.
`CASE something` is a clause in the CASE statement.
I will change the message to 'DO CASE' statement and will also try to produce a message for the empty statement lists inside a CASE clause and inside IF, ELSEIF and ELSE.

**Comment by cpyrgas** [comment]
Robert,
I think there used to be a warning for empty clauses and that's why we introduced the NOP instruction, didn't we? 

Just checked and our runtime code is full of NOPs, I assume for that reason. Apparently this warning stopped being reported in one of the previous builds.

Btw, same goes for TRY...END and empty CATCH and FINALLY clauses

**Comment by RobertvanderHulst** [comment]
I have added warnings for empty blocks, and now many of our compiler tests produce a warning. 
I will add NOP statements in the tests to take care of this.

**Comment by cpyrgas** [comment]
Confirmed fixed
