### ISSUE TITLE
AdsSQLServer Error 7200 when parameters are used.

### ISSUE THREAD

**Issue by christianschmid200272** [X-Sharp/XSharpPublic#1282]
When I use AdsSQLServer class with SQL parameters, I get an exception when AdsSQLServer constructor is called. I have tested some cases, parameter type as number or string, named and unnamed parametersas defined on https://devzone.advantagedatabase.com/dz/WebHelp/Advantage11.1/index.html?web_connection_pooling.htm.

**Message:**
Description :      Open error
Subsystem :       AXSQLCDX
GenCode :          EG_OPEN Open error
SubCode :           7200 Open error
FuncSym :           INIT
Severity :             ES_ERROR
Can Default :      False
Can Retry :          False
Can Substitute : False
ADSRDD:ADSERROR (Line: 0)
ADSRDD:_CHECKERROR (Line: 0)
AXSQLRDD:OPEN (Line: 0)
COREDB:DO (Line: 0)
COREDB:USEAREA (Line: 0)
COREDB:DO (Line: 0)
COREDB:USEAREA (Line: 0)
VODBUSEAREA (Line: 0)
DBSERVER:.CTOR (Line: 0)
ADSSQLSERVER:.CTOR (Line: 59)

**//Code sample console app:**
USING VO
USING System
USING System.Collections.Generic
USING System.Linq
USING System.Text
USING XSharp.ADS
USING XSharp.RDD

FUNCTION Start() AS VOID STRICT
   ? "Hello World! Today is ",Today()
   LOCAL oDB              AS AdsSQLServer
   LOCAL dwRet AS DWORD
   LOCAL hConn AS System.IntPtr
   LOCAL sql AS STRING

//Tested with different *.dbf files.
   dwRet := AdsConnect60( "\\myserver\mydata",  XSharp.ADS.ACE.ADS_REMOTE_SERVER, NULL_PSZ, NULL_PSZ, 0, hConn )
   
   //this sql works
   //sql := "select  *  FROM AUFTRAG where AUFNR = 366590" 
   
   //this sql does NOT work
   sql :=   "SELECT  *  FROM AUFTRAG WHERE (AUFNR = ? )" 
   
   AX_SetConnectionHandle( hConn )
   oDB := AdsSQLServer{sql, , , "AXSQLCDX", ,{{1, 366590} }}
   oDB:Close()
   WAIT
   RETURN

 - OS: Windows10Pro
 - Browser [e.g. chrome, edge, firefox]
 - Version Windows 19045.3086, 
 - Version XSharp: first reported with 2.14.0.4 and current 2.16.0.5

**Comment by christianschmid200272** [comment]
I see that the comments are mixed up, the correct one is
**//this sql works** 
//sql := "select * FROM ORDER where ORDER = 366590"

**//this sql works not**
sql := "SELECT * FROM AUFTRAG WHERE (AUFNR = ? )"

**Comment by cpyrgas** [comment]
Thanks Christian, I have updated also the original code sample, to avoid confusion

**Comment by cpyrgas** [comment]
Christian, will send you a preview beta of the new build as soon as it is available (before public release), so you can confirm if the problem is indeed fixed for you.

**Comment by cpyrgas** [comment]
Confirmed fixed by Christian
