### ISSUE TITLE
The preprocessor puts an excess parenthesis (Xbase++ dialect)

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1289]
**Describe the bug**
The preprocessor puts an excess parenthesis in the wrong place

**To Reproduce .prg**
```
#xtranslate ORA_DRV(<Method>([<arg_list,...>])) => ;
    (__oraResult := ORA_<Method>([<arg_list>]),;
     iif(ISOBJECT(__oraResult) .and. __oraResult:isDerivedFrom(Error()),;
         (Eval(ErrorBlock(), __oraResult), nil),;
         __oraResult))

#xtranslate ORA_DRV_LOCALS => local __oraResult := nil

class dbTableOra
exported:
    method FileName

hidden:
    var nHandle
endclass

method dbTableOra:FileName()
    ORA_DRV_LOCALS
    return Upper(ORA_DRV(Alias(::nHandle)))
```

**Expected behavior (xBase++ ppo)**
Output
```
method dbTableOra:FileName()
    local __oraResult := nil
    return Upper((__oraResult := ORA_Alias( ::nHandle),iif(( VALTYPE(__oraResult)=="O" ) .and. __oraResult:isDerivedFrom(Error()),(Eval(ErrorBlock(), __oraResult), nil),__oraResult)))
```

**Actual behavior (X# ppo)**
```
method dbTableOra:FileName()
local __oraResult := nil
return Upper( ;
    (__oraResult := ORA_Alias(::nHandle)),;
     iif(  ( VALTYPE(__oraResult)=="O" ) .and. __oraResult:isDerivedFrom(Error()),;
         (Eval(ErrorBlock(), __oraResult), nil),;
         __oraResult)))
```

**Additional context**
X# Compiler version 2.16.0.5 (public)
-dialect:xBase++ -xpp1 -lb -memvar -vo1 -vo3 -vo5 -vo10 -vo15 -vo16

**Comment by cpyrgas** [comment]
Confirmed fixed. 

Note that the output is not the same as in the "Expected Behavior" section of the report, because there it is mentioned that `VALTYPE(__oraResult)=="O" )` should be output, while the code in the report is actually using `ISOBJECT(__oraResult)` instead. Having said that, the output does look correct.

**Comment by DenGhostYY** [comment]
> Confirmed fixed.
> 
> Note that the output is not the same as in the "Expected Behavior" section of the report, because there it is mentioned that `VALTYPE(__oraResult)=="O" )` should be output, while the code in the report is actually using `ISOBJECT(__oraResult)` instead. Having said that, the output does look correct.

Yes, `ISOBJECT()` is another macro I forgot to mention. But the preprocessor in this example began to work correctly.
