### ISSUE TITLE
X# compiler doesn't support init/exit procedures (Xbase++ dialect)

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1290]
**Describe the bug**
X# compiler doesn't support init/exit procedures

**To Reproduce .prg**
```
init procedure Input()
    ? "Input"
return

procedure Main()
    ? "Main"
    return

exit procedure Output()
    ? "Output"
    wait
return
```

**Expected behavior (xBase++ exe)**
Output
```
Input
Main
Output
```

**Actual behavior (X# compiler)**
```
error XS9002: Parser: unexpected input 'init'
```

**Additional context**
X# Compiler version 2.16.0.5 (public)
-dialect:xBase++ -xpp1 -lb -memvar -vo1 -vo3 -vo5 -vo10 -vo15 -vo16

[init procedure](https://doc.alaska-software.com/content/stmt_xpplrm_init_procedure.html)
[Exit procedure](https://doc.alaska-software.com/content/stmt_xpplrm_exit_procedure.html)

**Comment by RobertvanderHulst** [comment]
We support it with a bit different syntax:

`PROCEDURE MyProc _Init1 | _Init2 | _Init3 | Exit`

I will see if I can also add INIT PROCEDURE and EXIT PROCEDURE

**Comment by cpyrgas** [comment]
Confirmed done
