### ISSUE TITLE
Some questions about migrating from Xbase++

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1291]
Hello. Please answer my questions.

1. [Here](https://www.xsharp.eu/help/cmd_cat_terminal.html) you write that commands like `@...BOX`, `@...CLEAR` and etc are not supported. But there is a link to the documentation of the command [SET CONSOLE.](https://www.xsharp.eu/help/command_set_console.html) Do you plan to implement these commands? What other function do you plan to implement? What Xbase++ documentation do you rely on? We need to know about this in order to migrate from Xbase++ to X#.
2. There is function `Int()` in Xbase++. I found a X# function [Integer()](https://www.xsharp.eu/runtimehelp/html/M_XSharp_RT_Functions_Integer.htm), read the tip, however questions remain. What happens if the number is greater than the short?
What is the best way to get around this error?
X# Compiler version 2.16.0.5 (public)
-dialect:xBase++ -xpp1 -lb -memvar -vo1 -vo3 -vo5 -vo10 -vo15 -vo16
```
procedure Main()
    ? int(12.4) // error XS0103: The name 'int' does not exist in the current context
    return
```
Let me know where is the best place to post questions like this.

**Comment by RobertvanderHulst** [comment]
The best place for discussions like these is our forum on xsharp.eu.
We do have SET CONSOLE because we support `?` and `??` for simple console output, and we also allow these to write to the ALTERNATE stream.

**Comment by DenGhostYY** [comment]
I posted a questions [here](https://www.xsharp.eu/kunena-2023-01-26/public-xpp/1094-xbase-forum#26754).
