### ISSUE TITLE
The global MEMVARs hide local variables

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1294]
In the example, the TestFunc function has an argument named 'myArg'. When compiled, if you look at the IL code, you can see that instead of outputting the value of the local variable 'myArg', the value of the global memvar with the same name is used.

Example:
```
MEMVAR myArg

FUNCTION Start() AS VOID STRICT
	TestFunc(1, 2, 3)
	RETURN

FUNCTION TestFunc(a, myArg, b)
	? a
	? myArg
	? b
	RETURN NIL
```
I found this problem in real code when I got an error at runtime saying that some MEMVAR was not found.

**Comment by RobertvanderHulst** [comment]
At this moment the parser "sees" that there is a memvar and translates 
`? myArg`
to
`? M->myArg`

Now, you may think that the compiler could 'see' that there is a parameter or local with the same name. And that is correct.
But there could also be a field or property in the class and that would be much more difficult to diagnose at parse time.
So I will have to fix this in the binder (a later step in the compiler)
What I will do is this:
- if the original code was `m->myArg` then always use the memvar
- if the original code was `myArg` and there is both a local, parameter or field and a memvar as well, then give precedence to the field and report an "ambiguous" warning, so you are aware of the issue and can decide to rename the local or parameter for example.

**Comment by RobertvanderHulst** [comment]
I have changed the compiler. I am now generating a warning when this happens, and the local or parameter will have preference over the file wide memvar. If you want to access the memvar you need to prefix it with `memvar->`, `m->` or `m.` (in the FoxPro dialect).

**Comment by cpyrgas** [comment]
Confirmed fixed
