### ISSUE TITLE
Accessing dictionary on an Object (late bound)

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1296]
A colleague of mine discovered a late bound issue with Dictionary Fields. This is the code to illustrate the problem:

```csharp
using System
using System.Collections.Generic

function Start() as void strict
  local myContainer := Container{} as object

  myContainer:Data:Add("Key", 0)
  local xxx := myContainer:Data["Key"] as int  // <- throws System.InvalidCastException: 
                  // 'value in USUAL does not support indexed operations. The value needs to be an 
                  // X# Array or implement the interface 'XSharp.IIndexedProperties'.'

  return

class Container
  public Data := Dictionary<string, int>{} as Dictionary<string, int> 
end class
```

Maybe it is possible to add support for this, if it is not to complicated. It is a very rare case and can be fixed by casting myContainer:Data to the dictionary.

Here's the example solution: [XSharpTestsLateBoundDictionary.zip](https://github.com/X-Sharp/XSharpPublic/files/11966525/XSharpTestsLateBoundDictionary.zip)

**Comment by cpyrgas** [comment]
Confirmed fixed

**Comment by cpyrgas** [comment]
I understand this is more tricky to implement, but maybe those should be supported as well?
(I'm not sure personally)
Otherwise it's confirmed fixed.


Following throws a System.Reflection.AmbiguousMatchException:

```
FUNCTION Start() AS VOID STRICT
LOCAL f AS System.Windows.Forms.Form
f := System.Windows.Forms.Form{}
f:Controls:Add(System.Windows.Forms.CheckBox{})
? f:Controls[0] // OK

LOCAL u AS USUAL
u := f
? u:Controls[0] //
```

Also this is throwing a System.NullReferenceException:

```
FUNCTION Start() AS VOID STRICT
LOCAL a AS System.Collections.ArrayList
a := System.Collections.ArrayList{}
a:Add(123)
? a[0] // OK
? a:Item[0] // OK

LOCAL u AS USUAL
u := a
? u[0] // OK
? u:Item[0] // System.NullReferenceException
```
