### ISSUE TITLE
FOXPRO TEXT .. ENDTEXT

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#13]

**Comment by RobertvanderHulst** [comment]
Moved to X-Sharp/XSharpDev#3

**Comment by RobertvanderHulst** [comment]
Moved to X-Sharp/XSharpDev#4

**Comment by RobertvanderHulst** [comment]
For this language construct I want to convert the FoxPro TEXTMERGE syntax (with the embedded expressions) into Interpolated string syntax so I can use the normal Interpolated string support in the compiler to resolve the expressions and embed them in the string.
There are some challenges because Foxpro allows to change some settings for TEXTMERGE at runtime. You can tell Foxpro to always use TEXTMERGE for TEXT .. ENDTEXT by setting a global flag, or use a TEXTMERGE modifier for the TEXT command.
You can also change the TEXTMERGE delimiters at runtime.

My intention for this feature is the following:
- Ignore SET TEXTMERGE DELIMITERS command. Always use the default delimiters. Otherwise we can't resolve this at compile time and that would mean that we could not allow local variables as expressions
- At compile time convert the text delimiters to curly braces and use the interpolated string support from the compiler.
- Create a temporary local that gets this value. This local is passed to a function (see below)
- When the TEXTMERGE clause is used then I will only convert the string to an interpolated string and assign its result to the local
- When that clause is not used then I will embed 2 literal strings in the code. One is the interpolated string and the other is the original string. The temporary local gets assigned a value with an IIF expression that depends on the global SET TEXTMERGE setting.
- This string is sent to  function in the runtime that takes care of the other options in the TEXT command, such as removing whitespace and writing the string to the filehandle in the _TEXT variable (FLAGS, PRETEXT, NOSHOW etc).
- I am not sure yet what the role of the TEXTMERGE() function in the runtime plays in all of this. Will look at that later

**Comment by JohanNel** [comment]
Hi Robert,
Matt probably need to jump in here...

- This string is sent to function in the runtime that takes care of the other options in the TEXT command, such as removing whitespace and writing the string to the filehandle in the _TEXT variable (FLAGS, PRETEXT, NOSHOW etc)

From my understanding TEXT/ENDTEXT does not remove whitespace characters.  What I could not detect yet from looking at examples is if the Last e"\n" before the ENDTEXT is included in the string, but my guess is it is.  This is also confirmed by the _PRETEXT help in the docs:
See the MS VFP Docs:
If you store a character expression to _PRETEXT, the character expression is added to the beginning of the output text line. To facilitate program indentation, you can store a tab or tabs to _PRETEXT.

- I am not sure yet what the role of the TEXTMERGE() function in the runtime plays in all of this. Will look at that later

TEXTMERGE() from my understanding is the same as TEXT/ENDTEXT but it has the option of recursively resolving placeholders until none is left.

**Comment by RobertvanderHulst** [comment]
Johan,
The PRETEXT clause allows you to specify a numeric value which indicates that certain whitespace needs to be removed. That is why I will pass this pretext value to the function in the runtime along with the string. When the PRETEXT value is numeric then it can be a combination of:
```
Value | Description
1 | Eliminate spaces before each line.
2 | Eliminate tabs before each line.
4 | Eliminate carriage returns, for example, blank lines, before each line.
8 | Eliminate line feeds.
```
