### ISSUE TITLE
AsHexString does not work as expected

### ISSUE THREAD

**Issue by ecosSystem** [X-Sharp/XSharpPublic#1301]
Hi Robert,

Following Code:

LOCAL cKey
cKey := CHR(85)+CHR(192)+CHR(180)+CHR(80)+CHR(54)+CHR(229)+CHR(149)+CHR(106)+CHR(194)+CHR(99)+CHR(187)+CHR(116)+CHR(33)+CHR(221)+CHR(189)+CHR(40)
? cKey
? AsHexString(cKey)

VO:
UÀ´P6å•jÂc»t!Ý½(
55 C0 B4 50 36 E5 95 6A C2 63 BB 74 21 DD BD 28 

X#:
UÀ´P6å•jÂc»t!Ý½(
55 C0 B4 50 36 E5 2022 6A C2 63 BB 74 21 DD BD 28

So x# gives 2022 instead of 95, which would be correct

Karl

**Comment by ecosSystem** [comment]
This would give the correct result, may however be optimized:

FUNCTION _C2Hex(cSource AS STRING, lAddSpace AS LOGIC) AS STRING
LOCAL sb			AS System.text.Stringbuilder
LOCAL pSource	AS PSZ
LOCAL p			AS BYTE PTR
LOCAL x			AS BYTE

pSource	:= StringAlloc(cSource)		
p			:= pSource
sb			:= System.text.Stringbuilder{cSource:Length*2}

WHILE(TRUE)
	x := p[1]
	IF x = 0
		EXIT
	ENDIF
	IF sb:Length > 0 .AND. lAddSpace
		sb:Append(' ')
	ENDIF
	VAR s := String.Format("{0:X2}",(INT) x)
	sb:Append(s)
	p++
ENDDO

//FOREACH c AS CHAR IN cSource
//	IF sb:Length > 0 .AND. lAddSpace
//		sb:Append(' ')
//	ENDIF
//	VAR s := String.Format("{0:X2}",(INT) c)
//	sb:Append(s)
//NEXT

RETURN sb:ToString()

**Comment by cpyrgas** [comment]
Karl, for such strings to be used in keys etc (not necessary printable ones), you need to use ChrW() instead of Chr(), which does a ansi->unicode conversion. If you use ChrW() (which simply returns the exact char that you specified), it should work well with AsHexString().

**Comment by ecosSystem** [comment]
Chris, the string is just an example that there is a difference between VO and x#. The string originally comes from an MD5-encryption. I need this MD5-string as hexstring. In VO this worked with AsHexString(), in x# it doesnt't. And I also doubt, that "2022" is a valid hex-value :) regardless whether Ansi or unicode.
I have several calls to AsHexstring() in my (very big) application. I really consider this as a bug...

**Comment by cpyrgas** [comment]
Karl, it really is a hex-value, it's the hex value of decimal 8226. Try this:

? AscW( Chr(149) )

and it will give you exactly that, the unicode value 8226. This happens because the Chr() function in X# converts values >128 to their equivalent unicode value (at least for those ascii values that represent a character that belongs in the currently used codepage by windows - the "System Locale"). If it didn't do that, then international characters like Greek characters would not be represented correctly in the unicode strings that .Net/X# uses.

This is just something to always keep in mind when dealing with strings in X#. In VO things were much simpler since STRINGs and PSZs were essentially the same thing, both simple 8bit per char strings, but in .Net strings are unicode.

**Comment by ecosSystem** [comment]
So what should I do in my case (Web-Api-Call) ?
I have a merchant-ID. I have to post this merchant-ID for authentication as md5-hash (hex-string)
Problem is, that the customer versions of our ERP-System are still VO, I convert every new version to x#.  Internally we are working with the x#-Version, we plan to migrate our customers one by one. Development is still in VO.
So i have to use #IFDEF __XHARP__ in every incidence of AsHexstring() and convert the given string from Unicode to Ansi before I call AsHexstring() ?

**Comment by cpyrgas** [comment]
It depends on the details. How do you construct this string than you later convert to hex? Is it something that the user types in a text control? Is it generated automatically from another process? And how do you put it to the cKey var? Is it read form a dbf (which unfortunately adds another layer of complexity again due to ansi<->unicode conversions) ?

**Comment by ecosSystem** [comment]
In this case the original merchant-Id is in a DBF (ADS)

This Id is converted to MD5:

`FUNCTION MD5(cdata AS STRING,cHashValue REF STRING) AS LOGIC
        LOCAL lresult AS LOGIC
        LOCAL hCryptProvider AS DWORD
        LOCAL hHash AS DWORD
        LOCAL dwDataLen AS DWORD
        LOCAL pHashData AS PTR
        LOCAL dwHashLen AS DWORD
        LOCAL cError AS USUAL

        dwDataLen := Len(cdata)
        BEGIN SEQUENCE
                // Acquire handle to default provider
                IF !CryptAcquireContext( ;
                        @hCryptProvider, ; // PTR for CSP
                        NULL_PTR, ;   // Container name
                        NULL_PTR, ;   // Provider name
                        PROV_RSA_FULL, ; // Provider type
                        0)     // Flags
                        cError := "Could not acquire crypto context."

                        IF      !CryptAcquireContext( ;
                                @hCryptProvider, ; // PTR for CSP
                                NULL_PTR, ;   // Container name
                                NULL_PTR, ;   // Provider name
                                PROV_RSA_FULL, ; // Provider type
                                CRYPT_NEWKEYSET)     // Flags
                                cError := "Could not acquire crypto context."
                                BREAK
                        ENDIF

                ENDIF
                // MessageBox(0, PSZ("Crypto context acquired"), PSZ("Success"),MB_OK)

                // Create a hash object
                IF !CryptCreateHash(;
                        hCryptProvider, ; // CSP provider
                        CALG_MD5, ;   // Which hash algorithm
                        0, ;    // Key
                        0, ;    // Must be zero
                        @hHash)    // Hash object handle
                        cError := "Could not create hash object"
                        BREAK
                ENDIF
                // essageBox(0, PSZ("Hash object created"), PSZ("Success"), MB_OK)

                // Add the data you want hashed to the hash object
                IF !CryptHashData(;
                        hHash, ;    // Hash object handle
                        String2Psz(cdata), ; // Ptr to data
                        dwDataLen, ;   // Length of data
                        0)      // Flags
                        cError := "Could not add data to hash object"
                        BREAK
                ENDIF
                // MessageBox(0, PSZ("Data added to hash object"), PSZ("Success"),MB_OK)

                // Get size of hash value and allocate memory for it
                IF !CryptGetHashParam( ;
                        hHash, ;              // Hash object handle
                        HP_HASHSIZE, ;   // We want hash size
                        NULL_PTR, ;
                        @dwHashLen, ;   // Length filled in here
                        0)
                        cError := "Could not get hash size"
                        BREAK
                ENDIF
                // MessageBox(0, PSZ("Hash size is "+AsString(dwHashLen)),PSZ("Success"),MB_OK)
                pHashData := MemAlloc(dwHashLen)

                // Now get hash value
                IF !CryptGetHashParam( ;
                        hHash, ;              // Hash object handle
                        HP_HASHVAL, ;   // We want hash value
                        pHashData, ;   // Hash value filled in here
                        @dwHashLen, ;   // Hash length
                        0)
                        IF GetLastError() == ERROR_MORE_DATA
                                // Allocate more memory
                                MemFree(pHashData)
                                pHashData := MemAlloc(dwHashLen)
                                IF !CryptGetHashParam( ;
                                        hHash, ;              // Hash object handle
                                        HP_HASHVAL, ;   // We want hash value
                                        pHashData, ;   // Hash value filled in here
                                        @dwHashLen, ;   // Hash length
                                        0)
                                        cError := "Still can't get hash value"
                                        BREAK
                                ENDIF
                        ELSE
                                cError := "Could not get hash value"
                                BREAK
                        ENDIF
                ENDIF
                // MessageBox(0, PSZ("Hash value is "+Mem2String(pHashData,dwHashLen)),PSZ("Success"), MB_OK)
                cHashValue:=Mem2String(pHashData, dwHashLen)
                lresult:=TRUE

        RECOVER
                #IFDEF __DEBUG__

                         MessageBox(0, PSZ(cError), PSZ("Error"), MB_OK)

                #ENDIF
        END SEQUENCE

        // Clean up

        IF pHashData != NULL_PTR
                MemFree(pHashData)
        ENDIF

        IF hHash > 0
                CryptDestroyHash(hHash)
        ENDIF

        // Release the CSP
        IF hCryptProvider > 0
                CryptReleaseContext(hCryptProvider, 0)
        ENDIF

RETURN lresult

`
I need cHashValue as hex-string

**Comment by cpyrgas** [comment]
I assume that the value passed to that function is a string with simple "standard" language characters is that right? If yes, then I think all you need to do is replace the Mem2String() call in the code with __Mem2StringRaw(). Mem2String() again does a ansi->unicode conversion, while __Mem2StringRaw() (new in X#) just uses the raw byte values of the PSZ. Then AsHexString() should give you the expected results.

**Comment by ecosSystem** [comment]
Just tried it, but __Mem2StringRaw() gives a string starting with char 0, nothing even close to what I need...

**Comment by cpyrgas** [comment]
Thanks, I see the problem, it's a bug in the function in the X# runtime, maybe has to do with the compiler options used (in our runtime project), will look into it.

In the meantime, please redefine the function in your own code and it should work fine:

```
USING System.Text

FUNCTION __Mem2StringRaw( p AS PSZ, len AS DWORD ) AS STRING
   LOCAL sb AS StringBuilder
   LOCAL x  AS DWORD

   IF len > 0
       sb  := StringBuilder{ (INT) len }

       FOR x := 0 UPTO len - 1
          sb:Append( (CHAR) p:Item[(INT)x] )
       NEXT

       RETURN sb:ToString()
    ELSE
       RETURN ""
    ENDIF

```

**Comment by ecosSystem** [comment]
With this version I get:
55 C0 B4 50 36 E5 3F 6A C2 63 BB 74 21 DD BD 28

so 2022 changed to 3F

However it should be 95:
55 C0 B4 50 36 E5 95 6A C2 63 BB 74 21 DD BD 28

**Comment by cpyrgas** [comment]
If you get 3F, it's because this is the byte that is contained inside the pHashData data produced by the crypting tool. I don't see any conversion happening afterwards, so it must be a 1-1 copy of the produced output.

If that's not the value you would expect, then maybe it's because there's already a problem with the cData argument passed to MD5()? What is the exact value of that string?

**Comment by cpyrgas** [comment]
If the original value is read from a dbf and it is binary data (not printable), then it makes sense that it is not the intended one, because there's again a conversion from ansi->unicode when reading from the dbf field. It's a mess, I know, but absolutely necessary in order to bring dbfs to the unicode string world of .Net.

Btw, if your own version of Hex2String() gives you the exact results that you need, then there's absolutely nothing wrong of course with using it in your applications, defining it in one of your base libraries will make it automatically available (replacing the default function from the X# runtime) to all your code. It's just that we cannot modify the function in the X# runtime to suit your specific needs, because it will break the behavior for other people with different usage of the function..

**Comment by ecosSystem** [comment]
The original string is 
5YvM5V4WzyF0gzRT
No difference if hardcoded or DBF-field
I already implemented my version of AsHexstring, so I will keep it at least as long as we still develop in VO.

**Comment by cpyrgas** [comment]
Indeed. Only possible source of unneeded conversion that I see is that the code in MD5() uses String2Psz(cdata), but this will give no issues for a string like yours, which only has regular ascii <128 characters. So I'm very surprised that your version of AsHexString() gives different results than by using the __Mem2StringRaw() function, will have another look to try to spot what causes this. 

But in any case, there definitely exists a problem with this function as included in XSharp.RT.dll, will log a separate issue about it.

**Comment by wriedmann** [comment]
Hi Chris, hi Karl.
PMFJI: IMHO the correct use in X# would be to use FieldGetBytes()/FieldPutBytes() to exclude all conversions and use that string as source for the crypting functions.

**Comment by cpyrgas** [comment]
Wolfgang, you are right, but in this particular case it makes no difference, since the text in the dbf field consists only of standard ascii < 128 alphanumeric characters, there's no binary data at all.

**Comment by ecosSystem** [comment]
Hi Chris,
this more compact replacement of _C2Hex(...) is working as expected:

`
FUNCTION _C2Hex(cSource AS STRING, lAddSpace AS LOGIC) AS STRING
LOCAL p	AS BYTE[]
LOCAL cHash	AS STRING
p		:= System.Text.Encoding.Default:GetBytes(cSource)
cHash	:= BitConverter.ToString(p):Replace("-", String.Empty)
return cHash
`
Of course this is only ok, if cSource is "Default"-encoding...

**Comment by ecosSystem** [comment]
So this is my final version:

`FUNCTION AsHexString(uValue AS USUAL) AS STRING
LOCAL cHex	AS STRING

IF uValue IS STRING	//isstring(uValue)
	LOCAL bValue	AS BYTE[]
	bValue	:= System.Text.Encoding.Default:GetBytes((STRING)uValue)
	cHex		:= BitConverter.ToString(bValue):Replace("-", String.Empty)
ELSE
	cHex := XSharp.RT.Functions.AsHexString(uValue)
ENDIF

RETURN cHex`

**Comment by cpyrgas** [comment]
Karl, glad you have a working solution! Although I would like to understand why the __Mem2StringRaw() solution didn't work as well, but it's not really that important

**Comment by cpyrgas** [comment]
Logged __Mem2StringRaw() bug in https://github.com/X-Sharp/XSharpPublic/issues/1302

**Comment by RobertvanderHulst** [comment]
Can I close this issue?

**Comment by cpyrgas** [comment]
Robert, yes I think so, the original report is related to general ansi<->unicode conversions and Karl has a working solution for this and also the problem with __Mem2StringRaw() is fixed as well.
