### ISSUE TITLE
__Mem2StringRaw() gives incorrect results

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1302]
Function __Mem2StringRaw() returns a string with first char 0 and next chars are correct but shifted by one place:

```
FUNCTION Start() AS VOID
	LOCAL c := "test" AS STRING
	LOCAL p AS PSZ
	
	p := __String2MemRaw(c)
	? p // "test", OK
	
	c := __Mem2StringRaw(p, (DWORD)c:Length)
	? c // " tes", wrong
	
	? AsHexString(c)
	// 00 74 65 73
RETURN

```

**Comment by cpyrgas** [comment]
What really puzzles me, is that when I define the function in my own code, using the same compiler options as the runtime project, then it works as expected. The code of the function is:

```
FUNCTION __Mem2StringRaw( p AS PSZ, len AS DWORD ) AS STRING
   LOCAL sb AS StringBuilder
   LOCAL x  AS DWORD

   IF len > 0
       sb  := StringBuilder{ (INT) len }

       FOR x := 0 UPTO len - 1
          sb:Append( (CHAR) p:Item[(INT)x] )
       NEXT

       RETURN sb:ToString()
    ELSE
       RETURN ""
    ENDIF
```

The difference between the compiled code in the runtime and in a test app is retrieving the element from the PSZ:

```
ldloc.1
ldc.i4.1
sub
call instance uint8 XSharp.__Psz::get_Item(int32)
callvirt instance class [mscorlib]System.Text.StringBuilder [mscorlib]System.Text.StringBuilder::Append(char)
```

vs

```
ldloc.1
call instance uint8 XSharp.__Psz::get_Item(int32)
callvirt instance class [mscorlib]System.Text.StringBuilder [mscorlib]System.Text.StringBuilder::Append(char)
```

So there's a missing subtraction by one. But why this happens with the same compiler options..

**Comment by RobertvanderHulst** [comment]
There is a different between the Vulcan dialect and the VO dialect:
The PSZ indexer for Vulcan is 0 based. For VO it is 1 based.
See https://www.xsharp.eu/help/dialects.html

**Comment by RobertvanderHulst** [comment]
Maybe you should cast the psz to a byte ptr  to make it always 1 based?

**Comment by cpyrgas** [comment]
Robert, that's what I had thought as well at first, but both the runtime project (XSharp.RT) and my test app use the VO dialect!

**Comment by RobertvanderHulst** [comment]
Well, the function is no longer used by Crypt().
So I think there is not really a problem.
We may want to look into this later...

**Comment by cpyrgas** [comment]
Yeah, it's nothing urgent, I just discovered this (very handy) function while dealing with a different issue and got puzzled why the compiler compiles is differently in different cases.

**Comment by cpyrgas** [comment]
Robert, can you please check if there's a hardcoded hack in the compiler, and when the output assembly is named XSharp.RT, then the compiler treats differently the char index dereferencing in a PSZ (and/or in PTR) (subtracting by one)? 

That's the only logical explanation I can think of, for the different compiler IL generation for the same code in a standalone app vs the runtime dll.

**Comment by RobertvanderHulst** [comment]
The only PSZ specific handling that I can find is related to the Vulcan dialect. In the Vulcan dialect the index is expected to be 0 based, where in the other dialects the index is expected to be 1 based.
But I will run the debugger on the compiler later today to check the compilation of the XSharp.RT assembly to see if I can explain this.
But maybe we can work around this by adding the pragma to force this code to be zero based?

**Comment by cpyrgas** [comment]
Yes, the fix is easy, but since this function is not used anywhere, I think it's more important to understand why there is this compiler behavior.

**Comment by RobertvanderHulst** [comment]
I debugged the compiler for XSharp.RT and what I see is that the code is compiled with 1 based arrays.
As a result some of the code inside Functions\Psz.prg is incorrect.

```
FUNCTION Bin2Logic(pszLogical AS PSZ) AS LOGIC
		IF pszLogical != NULL_PSZ
			RETURN pszLogical:Item[0] != 0
		ENDIF
		RETURN FALSE
```
This compares array element -1

```
FUNCTION __Mem2StringRaw( p AS PSZ, len AS DWORD ) AS STRING
   LOCAL sb AS StringBuilder
   LOCAL x  AS DWORD

   IF len > 0
       sb  := StringBuilder{ (INT) len }

       FOR x := 0 UPTO len - 1
          sb:Append( (CHAR) p:Item[(INT)x] )
       NEXT

       RETURN sb:ToString()
    ELSE
       RETURN ""
    ENDIF
```
This code uses a counter that starts at zero, but the compiler subtracts one, so the real counter starts at -1.

**Comment by RobertvanderHulst** [comment]
And these are the only 2 locations where XSharp.RT uses the array syntax on a PSZ

**Comment by cpyrgas** [comment]
Robert, OK, but then why when you compile the same code with the same compiler options in a standalone exe or dll, the code generated is different? The compiler is having this different behavior only for the runtime dlls (as described in https://github.com/X-Sharp/XSharpPublic/issues/1302#issuecomment-1630262170)? Or is this strange matter just not important so we just let it rest in peace?

**Comment by RobertvanderHulst** [comment]
The problem seems to be the fact that the source code type "__Psz" (when compiling the runtime) exposes the indexed property with the name "this", where the external type "__Psz" (when compiling your app) exposes the indexed property as "Item".
As a result the compiler follows a different route through the code, which causes a difference in the subtraction of the index parameters.

**Comment by RobertvanderHulst** [comment]
I have changed the compiler. For indexed PSZ access it now follows the "az" logic, except the Vulcan dialect, which always assumes you have 0 based PSZ indexes.

**Comment by RobertvanderHulst** [comment]
I have also added a compiler pragma to the PSZ functions module and adjusted the indexes accordingly.

**Comment by cpyrgas** [comment]
Hmm, that's strange, but I still get the previous wrong behavior of __Mem2StringRaw()

**Comment by RobertvanderHulst** [comment]
I have recompiled the runtime with 2.18.1.
The code for __mem2stringRaw is now 
```
       FOR x := 0 UPTO len - 1
          sb:Append( (CHAR) p:Item[(INT)x] )
       NEXT
```
The file contains 
``
#pragma options("az",on)
```
at the start.
This produces the following c# code for the loop in ILSpy
```
		for (uint x = 0u; x <= len - 1; x++)
		{
			sb.Append((char)p[(int)x]);
		}
```
This looks OK to me

**Comment by cpyrgas** [comment]
Robert,
Ah right, when I had compiled the new runtime, I was still using the old compiler. Confirmed fixed now, but you made a small typo in the other function, __String2MemRaw(), which was replicating only the first char. I fixed that, your turn to confirm the ticket :)
