### ISSUE TITLE
VOXporter: Add options to comment, uncomment and delete lines from the original VO code

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1303]
https://www.xsharp.eu/forum/public-product/3577-longtime-vo-code-migration-to-x

Since I'm in the migration process of my VO applications and will be there for a few years (if I'm ever able to exit from it): my main VO library has some code that is incompatible with X# not only in the code part, but also in the function/method declarations.
The VO version of the library is changed sometimes on the VO side, so I need to port it over to X# every few months or so to be compatible.

For differences in the code itself, the #ifdef statement works very well:

// not supported 
#ifdef __XSHARP__   
NOP 
#endif endcase

But what can I do with code like this?

VO:
method GetPage( nPage ) class DynamicTabControl
X#:
method GetPage( nPage as usual ) as VO.Window strict

to be compatible between X# and VO?
It would need some tag in the VO code so that the XPorter knows that this VO line has to be commented out, and another tag so that XPorter knows to remove the commend lines.

**Comment by cpyrgas** [comment]
Now VOXporter searchs for those tags in the VO code:

// {VOXP:COM} // comment out line
// {VOXP:UNC} // uncomment line
// {VOXP:DEL} and // {VOXP:REM} // remove line

**Comment by RobertvanderHulst** [comment]
Ok
