### ISSUE TITLE
Implement TEXT TO FILE 

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1304]
The TEXT UDC calls functions that do not exist

**Comment by RobertvanderHulst** [comment]
The functions _TextRestore() and _TextSave() need to be written.
Something like this should work

```
FUNCTION _TextRestore() AS VOID 
	SetAlternate(FALSE)
   SetAltfile( "" , FALSE)
	RETURN
FUNCTION _TextSave(cFile AS STRING) AS VOID
	SetAltfile( cFile , FALSE)
	SetAlternate(TRUE)
	RETURN
```

**Comment by cpyrgas** [comment]
Robert, how does this need to be used? I tried the following, but I see no file created:

FUNCTION Start() AS VOID STRICT

TEXT TO FILE c:\output\test.txt
	some
	text in here
	!!!!
ENDTEXT

**Comment by RobertvanderHulst** [comment]
This should indeed create the file c:\output\test.txt and write the 3 lines of text to it.
I see that if the path does not exist, then no exception is thrown. I'll change that.

**Comment by cpyrgas** [comment]
That was by accident :)
I was probably very dizzy, meant to write c:\test\output.txt and was expecting the file in the test folder..
Not that I have fixed the typo, indeed the file gets created
