### ISSUE TITLE
RDD should throw an error when tagname > maximum length

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1305]
At this moment the RDD does not warn when a tagname is longer than the maximum length (for example 10 for CDX).
There should be an error when the user tries to do that.
Also the OrdSetFocus() should throw an error when the user passes a tag name that is too long.

**Comment by RobertvanderHulst** [comment]
Also try to "unwrap" exceptions in the DbServer error handling code.

**Comment by cpyrgas** [comment]
Robert, are you sure this is a good idea? In VO, orders with longer tag names seem to work ok, so I'm afraid this will break existing apps..

**Comment by RobertvanderHulst** [comment]
Creating a tag with a longer name in VO truncates the name to 10 characters. If you then later try to switch to the long name, then it fails. Karl Faller reported this. I think it is best to throw the error, so people are aware that the name that they use when creating the tag is too long.

**Comment by cpyrgas** [comment]
Robert, I understand, but the following in VO runs and works correctly with no errors, while in X# now it shows an error dialog. So it is very possible that X# developers will not notice it, but suddenly users of applications will start getting those error dialogs (if there are such tag names, by accident or not). I'm not usre, maybe we should ask people what they think about it?

```
FUNCTION Start() AS INT
LOCAL cDbf AS STRING
cDbf := "c:\dbf\testing"
DbCreate(cDbf, {{"FLD1","N",5,0}})

DbUseArea(TRUE,"DBFCDX",cDbf)
DbAppend();FieldPut(1,1)
DbAppend();FieldPut(1,2)

DbCreateOrder("VERYVERYBIGNAME1", cDbf + "1", "FLD1")
DbCreateOrder("VERYVERYBIGNAME2", cDbf + "1", "-FLD1")

DbSetOrder(1)
? DbGoTop()
? FieldGet(1)

DbSetOrder(2)
? DbGoTop()
? FieldGet(1)
```

**Comment by RobertvanderHulst** [comment]
Chris,
This works, but
OrdSetFocus("VERYVERYBIGNAME")
does not work

Robert

**Comment by cpyrgas** [comment]
Indeed, but I think in 99% of the cases, orders are set by number. At least I have never ever used the order name in my VO apps.
(which I agree, it is silly, but that's what I've always seen being used)

**Comment by wriedmann** [comment]
Unfortunately in my applications the number is used only in very rare cases - at least 99% are set by name. Setting them by number is too risky as this may change. And in any VO applications I have seen it is the same.

**Comment by cpyrgas** [comment]
That's interesting, different people, veeery different perceptions! :)
OK, let's leave the error dialog then, but we need to give a really big red bold warning to the X# developers
