### ISSUE TITLE
The output window may contain more errors/warnings than the error browser when several errors have the same location

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1308]
The following example generates two warnings about unused variables in the "Output" window and only one warning (about the first variable 'x') in the "Error List" window:
```
FUNCTION Start() AS VOID STRICT
	LOCAL x, y AS INT
	RETURN
```

**Test project:**
[XSharpBetaTest.zip](https://github.com/X-Sharp/XSharpPublic/files/12237803/XSharpBetaTest.zip)

**Environment:**
X# 2.17.0.2b
IDE VS2022

**Comment by cpyrgas** [comment]
Confirmed fixed
