### ISSUE TITLE
Feature request: Positioning the cursor at the location of a variable definition

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1310]
Compiling the following code generates a warning about unused variables 'x' and 'y':
```
FUNCTION Start() AS VOID STRICT
    LOCAL x, y AS INT
    RETURN
```

If you double-click on the warning line, the cursor will be placed on the line where the variable is declared, but not on the variable itself, but on the beginning of the entire line (usually the LOCAL keyword). I would like the cursor to be positioned on a variable. In this example, there are few variables and there is no particular problem in finding them. But in real code, the variable declaration area can be large with a lot of variables and it can be difficult to find them at a glance.

**Environment:**
IDE VS 2022
X# 2.17.0.3

**Comment by RobertvanderHulst** [comment]
At this moment the error points to the statement and not the identifier. That was also why 2 same errors for variables in the same line were suppressed in the error browser.
I will change this in build 2.18

**Comment by cpyrgas** [comment]
Confirmed fixed
