### ISSUE TITLE
FFirst function does not see all files by mask

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1315]
The FFirst function does not find some files by mask.
For example, there are two files in a folder: "file.txt" and "file1.txt".
If we search for FFirst("file*.txt")/FNext, only "file1.txt" will be found, not "file.txt". This is different from VO's FFirst function (finds both files), as well as the FindFirstFile function, which also finds both files.

**Detailed test project with example attached:**
[XSharpBetaTest.zip](https://github.com/X-Sharp/XSharpPublic/files/12379884/XSharpBetaTest.zip)

**Environment:**
Compiler/RT X# 2.17.0.3
IDE VS 2022

**Comment by cpyrgas** [comment]
Confirmed fixed
