### ISSUE TITLE
Generated XML Comment for methods inside the <Module> class contain characters that are not allowed.

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1316]
The characters '<' and '>' should be replaced with "&lt;" and "&gt;", but better is probably to simply suppress generating the XML comments.

**Comment by RobertvanderHulst** [comment]
See https://www.xsharp.eu/forum/public-product/3618-minor-issue-with-xml-comments-with-embedded-brackets

**Comment by cpyrgas** [comment]
Unfortunately the link is no longer valid, so I can see the original problem, Robert can you please update it?

**Comment by RobertvanderHulst** [comment]
https://www.xsharp.eu/forum/topic?p=3398&hilit=XML+Comment#p3398

**Comment by cpyrgas** [comment]
Thanks, confirmed fixed
