### ISSUE TITLE
XSharp.VOSystemClasses: add DataServer:LockCurrentRecord() method

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#1321]
The DataWindow :Server access returns an object of type DataServer, and code like this is common in VO:
`if self:Server:LockCurrentRecord()
  self:Server:Commit()
  self:Server:Unlock()
endif`
When code is migrated to the XSharp.VOGUIClasses, then this line throws an error.

**Comment by RobertvanderHulst** [comment]
The DataServer class does indeed not have a LockCurrentRecord method, but it does have a RLock() method.
I did a quick comparison between DbServer:LockCurrentRecord() and DbServer:RLock(). 
The last one wants a record number and uses __DBSRLock() to lock the record , which performs a number of retries when needed. The first locks the current record and does not do a retry. When the lock fails then the Status of the area is set and FALSE is returned. RLock() also returns false when the lock fails but tries a few times.

This makes me wonder if we should not simply rewrite DbServer:LockCurrentRecord() and call DbServer:RLock(Recno()) instead.
The only difference would be that the changed version would retry several times (as specied in the nTries field, that is initialized with LockTries() in the DbServer constructor.
I suggest that I make the following changes:
- Add a LockCurrentRecord() method to DataServer and call Rlock(SELF:Recno) inside that method
- Redirect DbServer:LockCurrentRecord() and call DbServer:Rlock() from that method

**Comment by wriedmann** [comment]
Hi Robert,
I would agree with the proposed changes. Sincerely, I'm using only LockCurrentRecord() everywhere.

**Comment by wriedmann** [comment]
confirmed fixed
