### ISSUE TITLE
XSharp.VOGUIClasses: DataWindow:Show() method should not be typed

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#1325]
Since this method currently is typed, eventual methods in subclasses are not called when the method is called without parameter.
To explain it better:
in my code I nearly never call the Show() method of windows with parameters. Therefore my own Show() methods don't get called.
Maybe this is another thing that should be changed with a transporter tool: change Show() calls without a parameter to Show( SHOWNORMAL )

**Comment by RobertvanderHulst** [comment]
I changed the Show method back to CLIPPER calling convention again

**Comment by wriedmann** [comment]
confirmed fixed
