### ISSUE TITLE
XSharp.VOGUIClasses: exception when using a ComboBox on a VO Window

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#1328]
when a ComboBox exists on a VO window, an exception is thrown (in German on my machine):
Das Objekt des Typs "XSharp.VO.SDK.VOComboBox" kann nicht in Typ "XSharp.VO.SDK.IVOControl" umgewandelt werden.
   bei XSharp.VO.SDK.GuiFactory.CreateControl(ControlType type, Control owner, Int32 liStyle, Int32 liExStyle) in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\WinForm\_Factory.prg:Zeile 121.
   bei XSharp.VO.SDK.Control.__CreateControl(Int32 liStyle, Int32 liExStyle) in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\Controls\Control.prg:Zeile 82.
   bei XSharp.VO.SDK.Control.CreateWindowEx(Int32 dwExStyle, String sCaption, Int32 dwStyle, Int32 nX, Int32 nY, Int32 nWidth, Int32 nHeight, Window oOwner) in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\Controls\Control.prg:Zeile 414.
   bei XSharp.VO.SDK.Control.Create() in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\Controls\Control.prg:Zeile 495.
   bei XSharp.VO.SDK.TextControl.Create() in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\Controls\TextControl.prg:Zeile 169.
   bei XSharp.VO.SDK.ListBox.Create() in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\Controls\ListBox.prg:Zeile 186.
   bei XSharp.VO.SDK.ComboBox.Create() in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\Controls\ComboBox.prg:Zeile 110.
   bei XSharp.VO.SDK.Control..ctor(__Usual[] Xs$Args) in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\Controls\Control.prg:Zeile 951.
   bei XSharp.VO.SDK.TextControl..ctor(__Usual[] Xs$Args) in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\Controls\TextControl.prg:Zeile 260.
   bei XSharp.VO.SDK.BaseListBox..ctor(__Usual[] Xs$Args) in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\Controls\BaseListBox.prg:Zeile 235.
   bei XSharp.VO.SDK.ListBox..ctor(__Usual[] Xs$Args) in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\Controls\ListBox.prg:Zeile 369.
   bei XSharp.VO.SDK.ComboBox..ctor(__Usual[] Xs$Args) in C:\DevNET\XSharpPublic-main\src\Runtime\VOSdkTyped\Source\VOSdk\GUI_Classes_SDK\Controls\ComboBox.prg:Zeile 133.
   bei TestDialog..ctor(__Usual[] Xs$Args) in C:\XSharp\XIDE\Projects\XSharpSummit.2023\Applications\Password.XGUI\TestWin.Designer.prg:Zeile 12.
   bei AppShellWindow.TestWin(__Usual[] Xs$Args) in C:\XSharp\XIDE\Projects\XSharpSummit.2023\Applications\Password.XGUI\AppShellWindow.prg:Zeile 42.

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by wriedmann** [comment]
confirmed fixed
