### ISSUE TITLE
Error installing xsharp  v2.17.0.3 into VS 2022 v17.7.3

### ISSUE THREAD

**Issue by RWooters** [X-Sharp/XSharpPublic#1330]
One of my programmers has problems installing Xsharp v217.0.3 into a newly installed version of Visual Studios 2022 **v17.7.3**. 

My version of VS 2022 is **v17.7.1**, and xsharp v2.17.0.3 installed just fine for me.

1. Upgrade VS 2022 to v17.7.3
2. Install Xsharp v2.17.0.3

**Comment by RobertvanderHulst** [comment]
Richard,
Can you elaborate what the problem is?
- can you install into VS?
- if so, does VS start and / or does it display an error?
- If there is an error, then there most likely is a log file in the c:\Users\<yourname>\AppData\Roaming\Microsoft\VisualStudio\17<uniqueId> folder wih the name ActivityLog.xml  ?

**Comment by RWooters** [comment]
ActivityLog

**Comment by RWooters** [comment]
[ActivityLog.zip](https://github.com/X-Sharp/XSharpPublic/files/12528772/ActivityLog.zip)

**Comment by RWooters** [comment]
I could not reproduce the problems installing xsharp v2.17.0.3 that my programmer told me about, so there is something wrong with the workstation.
Any help would be great.

**Comment by RobertvanderHulst** [comment]
Richard,
A quick look on the ActivityLog shows that there are several problems with this VS installation.
I see error messages with the typescript package, the XamlLanguagePackage, the VCProjectEngine (C++ support) and with the XtraReports package. 
I would recommend to reinstall this VS installation (remove and install again)

**Comment by RobertvanderHulst** [comment]
This is not an issue of X#
