### ISSUE TITLE
Commenting a code snippet in VS 2022

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1336]
Just so you don't forget.
At the beta test stage of X# 2.17, it was discovered that the functionality of commenting on a selected code fragment stopped working. Before version 2.17 and in its first builds, this worked, and then, starting somewhere with build 2.17.0.2b, it stopped working.

![Screenshot](https://github.com/X-Sharp/XSharpPublic/assets/64518775/ea484d47-93e3-4a6b-8e09-8d5a91eb622a)

Now, when selecting a code fragment, the entire line is commented. But only the selected fragment should be commented. If there is no selection, then the entire line should be commented.

**Comment by cpyrgas** [comment]
Doesn't seem to work, at least not as requested. When selecting only a few chars in the line and pressing the comment button, the entire line gets commented (with //), instead of surrounding the selected chars with a block comment /*...*/

**Comment by RobertvanderHulst** [comment]
The wrong version of the DLL was inluded. Please retest in the next installer

**Comment by cpyrgas** [comment]
Block commenting in a single line works ok now, but when I comment a few lines instead (so with double slashes) and then hit the uncomment button to remove the comments, VS (any version) freezes.

Btw, regarding single line and block commenting, I think it's better to have separate buttons/commands for block commenting and for single line commenting. This way the programmer can select a few lines and choose easily if they want to block or line comment them, and also for a single line, can choose to block comment a part of comment the whole line.

**Comment by RobertvanderHulst** [comment]
Chris,

I'll review the issue that the uncomment is hanging.
The other issue (different buttons / commands for commenting styles) is something different. Please create a new issue for that.

**Comment by cpyrgas** [comment]
Confirmed fixed

**Comment by leon-ts** [comment]
Robert, Chris,
Uncommenting a block (`/*...*/`) doesn't work.

**Comment by cpyrgas** [comment]
Leonid, it seems to work ok here, but probably I'm doing it differently than you. I put the cursor between the block comment markers, press the uncomment button and the markers are gone. Maybe you are selecting the text first instead? Is it happening in all cases, with every code that you try to uncomment?

**Comment by leon-ts** [comment]
Hi Chris,
It's best if I demonstrate on video how this is provided in VS. Any C# project will do for this. Even without my video, you can take any C# project and see how it works. I note that before version 2.17.0.2b it worked the same way in X# (I can’t claim that the behavior is an exact match, but the basic behavior worked as expected).

**Example video:**
[ScreenRecorderProject1](https://1drv.ms/u/s!AlzZH96rHaSP6RhGid3NP6ZETihy?e=GzCDD5)

**Comment by cpyrgas** [comment]
Hi Leonid,

Ah, I think I see what you mean, that you cannot select the commented text and then uncomment it. But it works more simply in X#, you just need to put the cursor anywhere inside the block comment (without selecting the text), press the uncomment button and it will do it. Isn't this much better and easier this way? 

Having said that, I agree it wouldn't hurt to support uncommenting also while having selected the commented region

**Comment by leon-ts** [comment]
Hi Chris,
Indeed, it works this way and is more convenient. I did not know about it. Thanks for the tip! But it also wouldn’t hurt to implement uncommenting the selected text, as this action is simply logical.

**Comment by cpyrgas** [comment]
Well, it works in X# as it does in XIDE, so for me it was the only way I expected it to be working :)

**Comment by RobertvanderHulst** [comment]
Guys,
This was changed in 2.17 because we were using an older (most likely soon to be abandoned) API.
I will see if I can restore the old behavior too.

Robert
