### ISSUE TITLE
Preprocessor bug in WP (XBase++ dialect)

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1337]
**Describe the bug**
Hello. Preprocessor version 2.17.0.3 (release) still does not process [WP](https://github.com/X-Sharp/XSharpPublic/issues/1288) correctly.
I duplicated the ticket, since it was closed a long time ago, and I was only able to test it recently. I also have suspicions that notifications about messages in closed tickets are not sent.

**Comment by cpyrgas** [comment]
See https://github.com/X-Sharp/XSharpPublic/issues/1288#issuecomment-1729038158

**Comment by cpyrgas** [comment]
Confirmed fixed
