### ISSUE TITLE
Generating incorrect MSIL code

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1339]
There is a serious bug.
The following X# code generates a double function call instead of just one:
```
FUNCTION Start() AS VOID STRICT

    LOCAL cTmpDir AS STRING
    
    IF SLen(cTmpDir := JoinFiles()) == 0
		RETURN
    ENDIF

    RETURN

FUNCTION JoinFiles() AS STRING STRICT
    RETURN ""
```

**Resulting MSIL code:**
![Screenshot](https://github.com/X-Sharp/XSharpPublic/assets/64518775/d850c803-0cdb-4a0f-93d6-b36562d9e273)
The JoinFiles function is called twice instead of once.

**Test project:**
[XSharpBetaTest.zip](https://github.com/X-Sharp/XSharpPublic/files/12596032/XSharpBetaTest.zip)

**Environment:**
Compiler X# 2.17.0.3
IDE VS 2022 17.7.4

**Comment by RobertvanderHulst** [comment]
This seems to be the result of the fact that we "inline" calls to SLen() in the compiler. I will change the compiler to store the result of JoinFiles() in a temporary local in this case or to no longer inline SLen() but call the runtime function instead.

**Comment by RobertvanderHulst** [comment]
I am calling SLen() in the runtime now. When compiling in the core dialect then the compiler generates a static function SLen() in the current module.

**Comment by Serggio** [comment]
> I will change the compiler to store the result of JoinFiles() in a temporary local

This would be the best solution, IMHO. Something like what C# does with `BigFunction()?.Length ?? 0`

**Comment by RobertvanderHulst** [comment]
> > I will change the compiler to store the result of JoinFiles() in a temporary local
> 
> This would be the best solution, IMHO. Something like what C# does with `BigFunction()?.Length ?? 0`

I have chosen for a different solution, that was easier to implement:
- when the assembly references XSharp.Core then the SLen() inside XSharp.Core is used
- when the assembly does not reference XSharp.Core then the compiler generates an (internal) SLen() function and includes that. 
That was easier to implement than the temporary local.

**Comment by cpyrgas** [comment]
Robert, is it even necessary to generate that internal SLen(), if XSharp.Core is not referenced (so it's core dialect)? In this case, it would make sense to me to simply use c:Length, why introduce this intrinsic function? In the case that someone has already used that, then it's easy to define  in the code:

FUNCTION SLen(c) AS INT
RETURN c:Length

**Comment by RobertvanderHulst** [comment]
Chris,
If I do not do that, then some of our test cases will not compile again with the Vulcan runtime....
And your code does not:
- type c as STRING
- check for null
- return a DWORD like VO

**Comment by cpyrgas** [comment]
Confirmed fixed
