### ISSUE TITLE
Variablename is taken for a typename in a LINQ query - Error XS0119

### ISSUE THREAD

**Issue by pemo11** [X-Sharp/XSharpPublic#1342]
**A variable c is taken for type name in a LINQ query**

The following LINQ query in a WinForms applications results to an

`Error	XS0119	'c' is a type, which is not valid in the given context`

```C#
LabelList:AddRange((FROM c AS Control IN ((GroupBox)Container):Controls:OfType<Label>() SELECT (Label)c):ToList())
```

If I rename the variable to *d* or *c1* there is no error.

But there is definitely no type called *c* in the whole project.

The strange is that I cannot reproduce the error outside the project. The query compiles for a console application for example. Other developers on the team don't get the error, but when I did a git clone from the source repo on another computer I'll get the error again.

Renaming the variable is not an option at the moment. There should be no reason for this error in the given context.

I am using the X# Compiler 2.14.04

**Comment by RobertvanderHulst** [comment]
Peter,
are you sure that there is no type `c` in your project?

**Comment by pemo11** [comment]
No, there is definitely no type with the name c (or C).

And it only occurs within a LINQ query and not within a regular loop in the same scope.

// OK
ForEach c As Control In oDCrbgPKH:Controls:OfType<RadioButton>()
                
 Next

// OK 
Var test := oDCrbgPKH:Controls:OfType<RadioButton>():Where({ c => c:Checked == True}):ToList()

// Not OK, have to change the name from c to something else like co

pkhCode := (From co In oDCrbgPKH:Controls:OfType<RadioButton>() Where ((RadioButton)co):Checked == True Select ((RadioButton)co):Tag:ToString()):SingleOrDefault()

It has something to do the scope of c but I have no clue what it could be since the error message says that c is a type.

**Comment by pemo11** [comment]
I will try out the command in a WinForms application. Where I could compile it without error was a console application so far.

**Comment by pemo11** [comment]
I works in a WinForms app with no problems:

Local LabelList := List<Label>{} As List<Label>
LabelList:AddRange((From c In ((GroupBox)Container):Controls:OfType<Label>() Select (Label)c):ToList())

So, its application specific. But since there is no type definition with the name c it has to be something else...

**Comment by RobertvanderHulst** [comment]
Peter,
I really need to see the code and the referenced libraries to explain this.

**Comment by pemo11** [comment]
Thats difficult due (and not worth the effort) due to the size of the project. But there should be no type called c in any referenced assemblies and I as wrote,, even a class with the name c in the same scope does not give the error. So it must be something else.

I close the ticket for now.

**Comment by pemo11** [comment]
The error still persists within my project (not in the project of the other developers on the team who use the same X# version)

I had to change the name from c to c1 to be able to build the project.

I found out by listing all current types of the assembly that they are lot of types with the name **<>c** (and <>c_DisplayClass8_0 for example. 

May this could cause the error. Is <> a prefix for internal types?

**Comment by RobertvanderHulst** [comment]
Peter, yes `<>` is used by Roslyn to prefix certain compiler generated types, such as the types for Lambda expressions and anonymous types. Our codeblock is a combination of these two, so this type also uses this prefix.

**Comment by pemo11** [comment]
The only difference between the development environment of my colleagues and me is that I had to install the X# extension for VS 2022 on two PCs by starting XSharpProject2022.vsix directly because the extension was not installed through the X# installer. I got an error in both cases but the Visual Studio log file did not contain any useful information.

(and I haved installed X# on the D drive)

**Comment by RobertvanderHulst** [comment]
This problem can't be caused by the VS Integration.

**Comment by pemo11** [comment]
OK, than its the cosmics rays or the climate change.

On my Laptop I could build the same project mit VS 2022 und X# 2.14.04.
