### ISSUE TITLE
Error message when building for .Net Framework Target "CreateGeneratedAssemblyInfoInputsCacheFile" does not exist.

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1344]
See https://www.xsharp.eu/forum/topic?p=27316#p27316

**Comment by RobertvanderHulst** [comment]
This can be reproduced by adding the property 
`<GenerateAssemblyInfo>True</GenerateAssemblyInfo>`
to the project file.

**Comment by cpyrgas** [comment]
Confirmed fixed
