### ISSUE TITLE
VS Integration: The hint for Exception in the CATCH block stopped working

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1345]
There is a TRY...CATCH block:
```
TRY
CATCH e AS Exception
    ? e: // Nothing
END TRY
```
If you hover mouse over the variable 'e', the tooltip 'UNDECLARED e' will be displayed. And if you enter a colon after 'e', the list of methods is not displayed.
I remember this bug was fixed once before. But now it is there again. Maybe the VS version affects it?

**Environment:**
X# 2.17.0.3
IDE VS 2022 17.7.4

**Comment by cpyrgas** [comment]
Confirmed fixed
