### ISSUE TITLE
DBReindex(), DBZap() and DBPack() problems with custom orders

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#135]
Attached are two prg that show some problems if DBReindex(), DBZap() and DBPack() uses a CDX with more than one order.

DBReindex() - TestReindex.prg

during a DBReindex() VO and X# falsely fill the custom order - "ORDER3" - with the content of the first order. While VO keeps the Custom order flag in the CDX - very strange, that VO fills the custom order anyway - X# falsely removes the custom order flag. In the TestReindex.prg you´ll see that only if the X# created CDX is closed and reopened,  the second DbOrderInfo(DBOI_CUSTOM) call returns FALSE

DBPack() and DBZap() - TestPackandZapOrders.prg

- a X# DbPack() and DBZap() removes the  custom order flag, so the “ORDER3” is falsely no longer a custom order.

- after a X# DBZap() the OrdKEycount() value of the order "ORDER1" shows still 6 instead of 0

- after a x# DBPack() the OrdKEycount() value of the order "ORDER1" shows still 6 instead of 5,  and only 3 records are listed.

regards
Karl-Heinz

[tests.ZIP](https://github.com/X-Sharp/XSharpPublic/files/3530340/tests.ZIP)

**Comment by RobertvanderHulst** [comment]
Fixed
