### ISSUE TITLE
::new() doesn't work in class methods (Xbase++)

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1350]
**Describe the bug**
Сalling constructor in class methods doesn't work.

**To Reproduce**
```
procedure Main()
	local o := Parent():Create(6)
//	local o := Child():Create(6) // runtime error BASE/Code 2242;_nCat;Access to member-variable not allowed in this context

    ? o:GetCat()
    wait
return


class Child from Parent
endclass


class Parent
exported:
	inline class method Create(nCat)
        local o := ::new()

        o:_nCat := nCat
	return o

    inline method GetCat();    return ::_nCat

hidden:
    var _nCat
endclass

```

**Expected behavior (XBase++ exe)**
Output
```
6
```

**Actual behavior (X# compiler)**
```
warning XS9201: XPP The 'FROM' clause is interpreted as SHARING because variables in parent classes are always shared in the .Net Runtime.
error XS0117: 'Parent' does not contain a definition for 'new'
warning XS0649: Field 'Parent._nCat' is never assigned to, and will always have its default value
```

**Additional context**
X# Compiler version 2.17.0.3 (release)
-dialect:xBase++ -lb -memvar -enforceself -xpp1 -vo1 -vo3 -vo5 -vo10 -vo15 -vo16

**Comment by RobertvanderHulst** [comment]
Confirmed. This needs a compiler change. For now you can work around this by writing

`local o := Parent{}`
instead of
`local o := ::new()`

If you want you can surround the code with

#ifdef __XSHARP__
#else
#endif

to use the same code in both Xbase++ and X#

**Comment by RobertvanderHulst** [comment]
> If the class method was called from a child class, then the `::new()` in the class method will return an object of the child class. Therefore, the commented line does not work in XBase++

In my current implementation, we detect that the assignment `o:_nCat := nCat` was called from a method in the Parent class. And since the _nCat field is hidden, so only visible in the Parent class, then we can access that field, even when the Create() method was called from the Child() class. The Create() method belongs to the Parent class, so it can access everything from the Parent class.

**Comment by DenGhostYY** [comment]
```

**Comment by DenGhostYY** [comment]
Did I understand correctly that such code in XSharp will write `Parent` although XBase++ writes the `Child`?
```
procedure Main()
    local o := Child():Create(6)

    ? o:ClassName()

    wait
return


class Child from Parent
endclass


class Parent
exported:
        inline class method Create()
        return ::new()
endclass
```

**Comment by RobertvanderHulst** [comment]
Yes, in my current implementation, the object returned with ::new() inside the class method Create() is an object of type Parent.

**Comment by DenGhostYY** [comment]
This can also break code that expects an object of a child class.

**Comment by RobertvanderHulst** [comment]
Yes, this can break code. But creating an object in class method like this, is a pattern that is VERY uncommon. And expecting to create an object of the derived type is even more uncommon. I have never seen a pattern like that before.

**Comment by DenGhostYY** [comment]
I can't agree that this is an unusual pattern. How can you provide multiple constructors with different parameters without using a methods class? Statically typed languages such as C# and Java have overloading. But in XBase++ there is no overload, since its typing is dynamic. Therefore, you have to use class methods.

In addition, in XBase++ all methods, including class methods, are virtual. In a class method, a `::` means a reference to the current class-object. If you don't take this feature, we will not be able to migrate to XSharp

**Comment by RobertvanderHulst** [comment]
In X# we DO have overloading. 
And in our implementation of the XBase++ dialect, `::` also means the current class-object.
However, static/class methods are not virtual. That is not supported by the .Net framework.
So inside the Create() method of the Parent class `::` is always the parent object and never an object of a derived class.
I recommend that in the rare cases where you need this, you use conditional compilation and start using the overloading that X#/.Net supports.

**Comment by cpyrgas** [comment]
Confirmed fixed
