### ISSUE TITLE
StrZero does not work with nLength > 30

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1352]
In X# 2.17.0.3 StrZero returns an unexpected length of string, if the nLength argument is greater than 30

e.g.
`var test := StrZero(1234, 35, 0)`
This results to an string with length 30

In VO the length of the string was 35

**Comment by cpyrgas** [comment]
Fixed, but breaks Str(u,-1). The code

```
   IF SLen(result) < dwOriginal
        result := result:PadLeft((INT) dwOriginal)
    ENDIF
```

needs to be changed to 

```
   IF SLen(result) < dwOriginal .and. .not. (dwOriginal == UInt32.MaxValue .or. dwOriginal == UInt32.MaxValue - 1)
        result := result:PadLeft((INT) dwOriginal)
    ENDIF
```

in both _Str3() and _Str2()

**Comment by cpyrgas** [comment]
Confirmed fixed
