### ISSUE TITLE
"View Source" button in documentation doesn't work

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1353]
When you click the "View Source" button in the documentation, you get a 404 error. 

Example: Click on the Button on this page:

https://www.xsharp.eu/runtimehelp/html/M_VOGUIClasses_Functions_DIBCreateFromFile.htm

The following URL will be opened:

https://github.com/X-Sharp/XSharpPublic/blob/feature/Runtime/Runtime/VOSDK/Source/VOSDK/GUI_Classes_SDK/CAPAINT.prg#L2

The correct URL is:

https://github.com/X-Sharp/XSharpPublic/blob/feature/Runtime/src/Runtime/VOSDK/Source/VOSDK/GUI_Classes_SDK/CAPAINT.prg#L2

(the src/ part is missing)

**Comment by RobertvanderHulst** [comment]
Volkmar,
We have reorganized the Git repo since build 2.17.
The source has been moved into the src folder.
We will fix this with build 2.18

**Comment by RobertvanderHulst** [comment]
Fixed
