### ISSUE TITLE
RDD does not always take into account the presence of WrapperRDD

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1355]
If the workarea is wrapped in the WrapperRDD class and a RELATION is established with it, then in the DBFCDX class in the ForceRel method an error occurs when casting the WrapperRDD type to the DBFCDX type (see screenshot):
`VAR oParent := (DBFCDX) currentRelation:Parent`

**Screenshot:**
![Screenshot](https://github.com/X-Sharp/XSharpPublic/assets/64518775/c29e0f01-03ed-4f76-adc9-33ee4b39ef27)

**Comment by RobertvanderHulst** [comment]
That cast is not needed and should be removed. The EoF property from the next line exists in IRdd.
I will remove the cast for the next build

**Comment by cpyrgas** [comment]
I don't have a sample for this, so will let Leonid confirm it

**Comment by leon-ts** [comment]
Confirmed fixed (2.18.0.1).
