### ISSUE TITLE
Incorrect processing of the return value from the method (XBase++ dialect)

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1357]
**Describe the bug**
XSharp doesn't allow to skip the return value in methods. Also the compiler throws an error on the return value `super:Init()` in the method `Init()` although other return values, for example 123, are ignored.

**To Reproduce**
```
procedure Main()
    local o := SomeClass():new()

    o:Hello()
    wait
return


class SomeClass from Base
exported:
    inline method Init()
        ::a := "abc"
    return super:Init()

    inline method Hello()
        ? "Hello", ::a
    return

    var a
endclass


class Base
endclass
```

**Expected behavior (XBase++ exe)**
Output
```
Hello abc
```

**Actual behavior (X# compiler)**
```
warning XS9032: This entity type cannot return a value. Return value ignored.
warning XS9201: XPP The 'FROM' clause is interpreted as SHARING because variables in parent classes are always shared in the .Net Runtime.
error XS0815: Cannot assign void to an implicitly-typed variable
error XS0126: An object of a type convertible to 'usual' is required
```

**Additional context**
X# Compiler version 2.17.0.3 (release)
-dialect:xBase++ -lb -memvar -enforceself -xpp1 -vo1 -vo3 -vo5 -vo10 -vo15 -vo16

**Comment by RobertvanderHulst** [comment]
Compiler option -vo9 should allow missing return values and missing return statements (xs0126 and xs9032).
Init methods (constructors) in .Net do not return a value. So super:Init() calls the parent constructor, but that does not return a value.
If you change 
```
return super:Init()
```
to
```
super:Init()
```
then it should work as expected.

I will see if I can make the compiler convert
```
return super:Init()
```
to 
```
super:Init()
return SELF
```

**Comment by DenGhostYY** [comment]
Yes, the `-vo9` helped remove the error from the method `:Hello()`, but not for the `:Init()`

**Comment by RobertvanderHulst** [comment]
For the Super:Init() (for now) you will have to remove the return

**Comment by cpyrgas** [comment]
Confirmed fixed
