### ISSUE TITLE
Error not returned when automatically opening a structural index

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1358]
When opening a DBF file, if the RuntimeState.AutoOpen setting is set to True, then the structural index is also opened. If there is an error in the index file being opened, the RDD detects it and throws an exception, but the exception is not translated back to where the DBF file was opened. As a result, the VODBUserArea function returns the success of the operation, despite the fact that the index file is corrupted. In the future, this undetected problem generates strange (from the user's point of view) errors. For example, NullReferenceException.

The problem was found in a real application. But I made a small example based on it, which clearly demonstrates the problem.

The following example has two files: FILE1.DBF and its structure index FILE1.CDX. An error was intentionally (for example) introduced into the index file. There was a typo in the saved index expression `STR(COL1,4)`: the first character 'S' was replaced with 'R'. The result was an invalid expression with an unknown RTR function: `RTR(COL1,4)`.

The VODBUseArea function opens FILE1.DBF and FILE1.CDX without errors. But then, when executing the VODBAppend function, a NullReferenceException is thrown. I took the debug XSharp.Rdd.dll and determined that this is happening due to the fact that some of the data in the classes, such as CdxTag, etc., was not initialized.

**Example project** (the file is opened from the 'Debug\Files\' folder):
[XSharpBetaTest.zip](https://github.com/X-Sharp/XSharpPublic/files/12792412/XSharpBetaTest.zip)

**Environment:**
Compiler X# 2.17.0.3
IDE VS 2022

**Comment by cpyrgas** [comment]
I am not sure that this change is a good idea, as it makes the behavior incompatible to VO, in which DBUSeArea() returns true with this file. Maybe it would be better to keep returning TRUE (since the dbf itself was opened), but also show an error dialog or raise some other flag indicating the corrupted index?

**Comment by cpyrgas** [comment]
Robert,
Yeah, I understand the implications, it's just that I'm pretty sure there will be existing code that depends on the VO behavior... Btw, in VO, issuing a SetOrder(1) after opening the file returns FALSE, so that's also some indication that something went wrong.

**Comment by leon-ts** [comment]
The issue described in this ticket has been resolved. The VODBUseArea function returns False and RuntimeState.LastRddError contains the correct error description. But given the point Chris made, I'll leave the ticket closure to his discretion.

**Comment by cpyrgas** [comment]
Thanks Leonid, let's close it then! Will open it again in case anyone complains.
