### ISSUE TITLE
Problem opening DBFCDX index file

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1360]
Attached dbf/cdx file can be opened fine from VO and the following code finds the correct record. In X#, it fails with:

ERROR: 
Description :	Workarea not indexed (Datatype error)
GenCode :	EG_NOORDER Workarea not indexed
SubCode :	1120 Datatype error

Interestingly, when the file is opened with a dbf utility (written in VO), then no records are shown, so there must be some problem with the index. But after doing a reindex from the tool, it now works fine. Still, the X# program again gives the above error.

```
FUNCTION Start() AS VOID
? DbUseArea(,"DBFCDX","C:\...\INIFILE")
? RecCount()
? LastRec()
? DbSeek("BASE    CONNECT STRING")
? RecNo(), FieldGet(1), FieldGet(2)
? DbCloseArea()
```

[DBF_Index.zip](https://github.com/X-Sharp/XSharpPublic/files/12818325/DBF_Index.zip)

**Comment by RobertvanderHulst** [comment]
The index has the character '8' on the location in the index header where FoxPro stores the Collation (0x7EE). This causes the opening of the index to fail. I am now throwing an error when the DBFCDX driver opens a file with that character

**Comment by cpyrgas** [comment]
Robert, the problem though was reported by a VO programmer (or a programmer who inherited a VO program) and apparently this index was created from VO: https://www.xsharp.eu/forum/topic?p=27525#p27525

Looks like VO totally ignores this header location, or uses it for storing something else?

**Comment by RobertvanderHulst** [comment]
Chris, VO ignores this location in the header. That is why VO works "just fine". But in X# we monitor this area, because FoxPro uses it to store the collation.

**Comment by cpyrgas** [comment]
Would it then be an idea to ignore this also in X#, when the VO dialect is used (at runtime)?

_(like Nikos said...ducking for cover :))_

**Comment by RobertvanderHulst** [comment]
> Would it then be an idea to ignore this also in X#, when the VO dialect is used (at runtime)?
> 
> _(like Nikos said...ducking for cover :))_

What happened to the Greeks. Ducking for cover is very unlike you <g>.
I think I can ignore this in the VO dialect.

**Comment by cpyrgas** [comment]
It's the crisis...we were taught to not complain anymore and suffer silently..:)

**Comment by cpyrgas** [comment]
Confirmed fixed. And after doing a DBReindex() (from X#), now the index seems to work properly.
