### ISSUE TITLE
VS Integration: Intellisense incorrectly determines namespaces for classes of the same name

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1363]
In the following example, even though the Timer class is defined with a full namespace, Intellisence shows the tooltip and constructor arguments from another class. This occurs if the file specifies 'using' with a namespace where another class of the same name is defined.

**Example:**
```
USING System.Threading

FUNCTION Start() AS VOID STRICT
	LOCAL oTimer AS System.Timers.Timer // Invalid tooltip
	oTimer := System.Timers.Timer{ // Invalid arguments
	RETURN
```

**Screenshot 1 (tooltip):**
![Screenshot1](https://github.com/X-Sharp/XSharpPublic/assets/64518775/2bc99c7e-52e4-4475-bc96-75baa713c8fb)

**Screenshot 2 (constructor arguments):**
![Screenshot2](https://github.com/X-Sharp/XSharpPublic/assets/64518775/7a3009e1-28c9-4074-9c11-028ef507a4fa)

**Environment:**
X# 2.17.0.3
IDE VS 2022

**Comment by cpyrgas** [comment]
Confirmed fixed
