### ISSUE TITLE
Add new warning for assigning to local obj or usual variables

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#1364]
This is a proposal for a new warning, that would help reduce unnecessary late-bound calls.

We have the following situation in our code base:

```
property SomePropertyWithALongName as StringBuilder get set

method SomeMethod() as void
  local o as object
  o := self:SomePropertyWithALongName
  o:SomeMethod()
  o:SomeMethod()
  o:SomeMethod()
  // ...
``` 

In this example, the return value of the property (of type StringBuilder) is assigned to a local variable of type object (or usual). This has the effect, that every method call or property access on the local variable is done as late bound call, when late bound is enabled in the project. 

An easy way to get rid of these unnecessary late-bound calls is to change the type of the local variable 

```
property SomePropertyWithALongName as StringBuilder get set

method SomeMethod() as void
  local o as StringBuilder
  o := self:SomePropertyWithALongName  // or even simpler var o := self:SomePropertyWithALongName
  o:SomeMethod()
  o:SomeMethod()
  o:SomeMethod()
  // ...
``` 

IMHO it would be very helpful to get a warning for the line of the assignment. Something like "Assignment to a local variable of type object/usual will cause late bound calls". 

I would limit this warning with the following conditions:
* Only when late bound calls are allowed active in the project file
* Only for assignments to local variables of type object or usual
* An explicit conversion to object would disable the warning

I created an example, that contains various assignments with comments, if a warning would be expected or not: 
[XSharpTestsLateBoundWarning.zip](https://github.com/X-Sharp/XSharpPublic/files/12872004/XSharpTestsLateBoundWarning.zip)

**Comment by RobertvanderHulst** [comment]
Volkmar,
You can do this yourself by writing an analyzer and including the analyzer as part of the compiler.
There are examples of Roslyn analyzers on the web. As long as you change the namespaces to our namespace (that you know because you have used our parser) and link to XSharp.CodeAnalysis.DLL then it should work.
