### ISSUE TITLE
Problem with listview:ensurevisible()

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#137]
VO dialog window with a ListView.
Add some items to the ListView.
Call ListView:EnsureVisible(x,FALSE) where x is within the range of items and it throws an exception.

Its OK in VO and under Vulcan runtime.

Screenshot and code below.
 
![image003](https://user-images.githubusercontent.com/14542129/63519494-c146f880-c4fb-11e9-9035-348ee61212c3.png)

Leigh

```
METHOD SetDefaults()
LOCAL oLVColumn AS ListViewColumn
LOCAL oLVItem AS ListViewItem
LOCAL i AS DWORD
LOCAL oTB AS TextBox

// Create ListViewColumns
oLVColumn            := ListViewColumn{}
oLVColumn:NameSym    := #SREF
oLVColumn:CAPTION    := "Reference"
oLVColumn:Width           := 9    

SELF:oDCListView1:AddColumn( oLVColumn )
 
FOR i:=1 UPTO 10
       oLVItem := ListViewItem{}
       oLVItem:SetValue( NTRIM(i), #SREF )
       SELF:oDCListView1:AddItem( oLVItem )
NEXT

IF( SELF:oDCListView1:ItemCount==10 )
       TRY
              SELF:oDCListView1:EnsureVisible(5,FALSE) // same error if called with an integer or dword variable
       CATCH oE AS Exception
              oTB:=TextBox{SELF,"error",oE:ToString(),}
              oTB:Show()
       END TRY
ENDIF
RETURN TRUE
```

**Comment by RobertvanderHulst** [comment]
Aarg.
EnsureVisible casts the second parameter to a WORD:
`RETURN LOGIC(_CAST, ListView_EnsureVisible(SELF:Handle(), INT(nItem - 1), WORD(_CAST, lPartiallyVisible)))`
- No check for NIL
- Why not IIF (lPartiallyVisible, -1, 0)

**Comment by cpyrgas** [comment]
Robert, yeah, it's bad code, but because of this exists in the VOSDK, it has been reused multiple times in users' code as well, so we need to make this work in a compatible way to VO, otherwise a lot of existing code will break.

Small sample that reproduces the problem:

	LOCAL u AS USUAL
	u := TRUE
	? WORD(_CAST, u) // exception

**Comment by RobertvanderHulst** [comment]
Chris, Casting a logical to a number is handled by the compiler. Casting a logical inside a usual is really dirty and especially casting a NIL to a word.
We can do this in the runtime (simply add cases to the switch inside the implicit converters) but I am afraid that will have negative side effects in other places...
I think if better to properly fix this code and to teach people how they should do this.
so that method will become:
```
LOCAL nResult as LONG
DEFAULT(@lPartiallyVisible, FALSE)
nResult := ListView_EnsureVisible(SELF:Handle(), INT(nItem - 1), iif( lPartiallyVisible,-1,0)))
RETURN nResult != 0
```

**Comment by cpyrgas** [comment]
OK let's see how it goes, if there are enough people reporting similar things. Yeah, I agree, those cases are too dirty indeed.

**Comment by cpyrgas** [comment]
Fixed as discussed.
