### ISSUE TITLE
DBF: Deleted() is true on a table with all records deleted

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#1370]
If table consists of deleted records (and no undeleted) then it has Deleted() = true even in EOF, so that after opening it we have:
```
? BOF()		// prints TRUE
? EOF()		// prints TRUE
? Deleted()	// prints TRUE
```

SetDeleted() is TRUE, meaning that deleted records must be ignored.

**Comment by RobertvanderHulst** [comment]
It looks like in this special case the "physical" record pointer is on a deleted record. Although logically there are now rows, the RDD still sees the deleted flag.
With which RDD did you see this?

**Comment by Serggio** [comment]
DBFCDX, but it doesn't matter whether table has indexes.

**Comment by cpyrgas** [comment]
Confirmed fixed
