### ISSUE TITLE
TransRec (RDD) operation throws exception if some fields are missing

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1372]
The TransRec operation in X# is incompatible with VO in terms of the requirements for the presence of fields declared for copying. In VO, if the target table did not have a copied field, then such a field was simply silently skipped. And in X# the exception 'Invalid Field Index' occurs. At the same time, judging by the X# program code in Runtime, skipping missing fields is also provided, but this is not fully taken into account.

**Specifically:**

The CoreDb class has a TransRec method. It calls the BuildTrans method to build row copy information:
```
        j := 0
        FOR i := 0 UPTO lpfn:FieldCount -1
            uiSrc := src:FieldIndex( lpfn:Fields[i] )       // returns a 1 based index
            uiDst := dst:FieldIndex( lpfn:Fields[i]  )
            IF uiSrc == 0 || uiDst == 0
                fMatch := FALSE
            ELSE
                dbti:Items[j]:Source       := uiSrc
                dbti:Items[j]:Destination  := uiDst
                j++
                IF fMatch
                    LOCAL srcFld AS RddFieldInfo
                    LOCAL dstFld AS RddFieldInfo
                    srcFld := src:GetField(uiSrc)
                    dstFld := dst:GetField(uiDst)
                    if srcFld:IsMemo .or. dstFld:IsMemo
                        fMatch := FALSE
                    else
                        fMatch := uiSrc == uiDst && srcFld:SameType( dstFld )
                    endif
                ENDIF
            ENDIF
        NEXT

        dbti:ItemCount := j
```

The dbti:Items array has a length equal to the user-specified number of fields to copy. But during the BuildTrans method, missing fields are discarded and the special property dbti:ItemCount takes on a value equal to the number of fields present in the source and destination. That is, the value of the dbti:ItemCount property may be less than the actual length of the dbti:Items array.

Next, the TransRec method is called in the Workarea class, where the dbti:ItemCount property is ignored, and the loop goes along the entire length of the dbti:Items array (in the TransRec method this is info:Items).
```
	VIRTUAL METHOD TransRec(info AS DbTransInfo) AS LOGIC
                LOCAL oDest  AS IRdd
                LOCAL result AS LOGIC
                LOCAL oValue AS OBJECT
                oDest := info:Destination
                result := oDest:Append(TRUE)
                IF info:Flags:HasFlag(DbTransInfoFlags.CanPutRec)
                    VAR buffer  := SELF:GetRec()
                    result      := oDest:PutRec(buffer)
                ELSE
                    FOREACH oItem AS DbTransItem IN info:Items
                        oValue := SELF:GetValue(oItem:Source)
                        result := oDest:PutValue(oItem:Destination, oValue)
                        IF ! result
                            EXIT
                        ENDIF
                    NEXT
                ENDIF
                IF result .AND. SELF:Deleted
                    result := oDest:Delete()
                ENDIF
                RETURN result
```
Here is this line:
`FOREACH oItem AS DbTransItem IN info:Items`
This causes us to eventually reach an iteration where the array value contains the value 0, which is passed to the GetValue method, which throws an exception.

**Example project where the error is reproduced:**
[XSharpBetaTest.zip](https://github.com/X-Sharp/XSharpPublic/files/13175514/XSharpBetaTest.zip)

**Environment:**
Compiler X# 2.18.0.3
IDE VS 2022

**Comment by RobertvanderHulst** [comment]
Thanks for the report. I will look into this after the 2.18 release.

**Comment by leon-ts** [comment]
UPDT: Added a test project to the main (first) message of this ticket.

**Comment by leon-ts** [comment]
Robert,
Let me offer you a small but important optimization to the new code. The fact is that the TransRec method is executed for each line of the copied file, and in each line it copies all specified fields. If the file has a lot of fields and lines, then it is important that the TransRec method is executed without doing unnecessary operations.

The optimization is that in the TransRec method the guaranteed number of valid fields is already known (the CoreDb.BuildTrans method took care of this) and this value is stored in the DbTransInfo.ItemCount property. In this regard, it is not necessary to do the following check for each field in each copied line: `oItem:Source > 0 .AND. oItem:Destination > 0`. It is enough to simply iterate through the elements of the info:Items array from the first element to info:ItemCount (adjusted for zero-based). Up to ItemCount, all elements are guaranteed to contain valid values. And the remaining elements after ItemCount are guaranteed to be invalid.

**Example of proposed optimization:**
```
	VIRTUAL METHOD TransRec(info AS DbTransInfo) AS LOGIC
                LOCAL oDest  AS IRdd
                LOCAL result AS LOGIC
                LOCAL oValue AS OBJECT
                oDest := info:Destination
                result := oDest:Append(TRUE)
                IF info:Flags:HasFlag(DbTransInfoFlags.CanPutRec)
                    VAR buffer  := SELF:GetRec()
                    result      := oDest:PutRec(buffer)
                ELSEIF info:ItemCount > 0
                    // FOREACH oItem AS DbTransItem IN info:Items
                    LOCAL i, nCount AS INT
                    LOCAL oItem AS DbTransItem
                    nCount := info:ItemCount - 1
                    FOR i := 0 UPTO nCount
                        oItem := info:Items[i]
                        oValue := SELF:GetValue(oItem:Source)
                        result := oDest:PutValue(oItem:Destination, oValue)
                        IF ! result
                            EXIT
                        ENDIF
                    NEXT
                ENDIF
                IF result .AND. SELF:Deleted
                    result := oDest:Delete()
                ENDIF
                RETURN result
```
