### ISSUE TITLE
Feature request: Dark theme in new debugger tabs (VS 2022)

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1375]
Recently, new useful tabs appeared in the X# debugger in VS: "Globals", "Workareas", "Public and Privates". But they don't take into account the current VS theme and are always displayed on a white background. This has a negative effect on the eyes (one bright white area among the rest of the dark background around), especially when working in the evening. Please enable dark theme support on these tabs.

**An example of what debug mode looks like, where only standard tabs are active:**
![Screenshot1](https://github.com/X-Sharp/XSharpPublic/assets/64518775/60dbd64a-e527-4026-a7b1-94ff04355cdf)

**An example of what debug mode looks like with the "Workareas" tab selected:**
![Screenshot2](https://github.com/X-Sharp/XSharpPublic/assets/64518775/c5c890d5-1e18-4c2d-87ab-7decb9b92837)

**Environment:**
X# 2.17.0.3, 2.18.0.2a
IDE VS 2022

**Comment by RobertvanderHulst** [comment]
Leonid,
We had that (theming support) working, but then the column headers become invisible.
We have not found a way to tell VS to use the theme and not touch the listview headers.
It must be possible but requires advanced XAML knowledge.
You can see that (for now) we have disabled styling:
https://github.com/X-Sharp/XSharpPublic/blob/main/src/VisualStudio/Debugger.UI/Controls/MemvarsControl.xaml#L8

**Comment by RobertvanderHulst** [comment]
Partially fixed in 2.18.0.4

**Comment by RobertvanderHulst** [comment]
I have changed the Listview in these windows into a DataGrid. I have also linked the colors for the various elements to the colors of the current theme.

**Comment by RobertvanderHulst** [comment]
I have no also added a panel to the Workarea window with Status / Fields

**Comment by cpyrgas** [comment]
Looking good!
