### ISSUE TITLE
Asc() is ignoring RuntimeState.Ansi

### ISSUE THREAD

**Issue by TOchse** [X-Sharp/XSharpPublic#1376]
**Describe the bug**
The behavior of Asc() in not considering the current runtime setting. This leads to unexpected results when setANSI(false) is used.
While Chr() chooses the encoding (WinEncoding or DosEncoding) based on RuntimeState.Ansi, Asc() does not.

**To Reproduce**
I included some testcode (VO-Dialect) that shows the different behavior. 
[Testcode.txt](https://github.com/X-Sharp/XSharpPublic/files/13163191/Testcode.txt) (its .txt because .prg isn't allowed)

**Expected behavior**
I expect the result of Asc() to be the same number, that I entered into the Chr() (while using the same RuntimeState).

**Screenshots**
Here is a screenshot of the testcode:
![grafik](https://github.com/X-Sharp/XSharpPublic/assets/97807594/8a59b056-2a06-42f7-b8e7-f7fecf51815b)
This is the result of this testcode:
![grafik](https://github.com/X-Sharp/XSharpPublic/assets/97807594/c8fb12c6-3e42-4904-8d48-4e5d6baf9a14)

**Additional context**
There are 3 versions of Chr():
1. Chr(): depends on RuntimeState.Ansi
2. ChrA(): Always uses Ansi codepage
3. ChrW(): Always uses Unicode

Asc() only has 2 versions:
1. Asc(): Always uses Ansi codepage
2. AscW(): Always uses Unicode

In my opinion the current version of Asc() is actually AscA().

**Comment by RobertvanderHulst** [comment]
Can you include the test code as attachment?

**Comment by TOchse** [comment]
Here's a complete solution with the test code:
[Testcode.zip](https://github.com/X-Sharp/XSharpPublic/files/13166813/Testcode.zip)

**Comment by TOchse** [comment]
Is there anything else I can provide to you?

Here's a picture of the Chr() and Asc() next to each other (from [XSharp.Core/Functions/String.prg](https://github.com/X-Sharp/XSharpPublic/blob/main/src/Runtime/XSharp.Core/Functions/String.prg))
![grafik](https://github.com/X-Sharp/XSharpPublic/assets/97807594/c4a2accd-c262-4fac-ac3c-086072d8f2ad)
As you can see, the Chr() uses the encoding according to RuntimeSate.Ansi.
Asc() on the other side always uses WinEncoding.
Currently the Asc() actually looks like a (currently not available) AscA() as counterpart for ChrA().

In my opinion, the highlighted part on the right side should be replaced with the highlighted part of the left side.

It looks like you fixed it in 2019 for Chr() in [this Commit](https://github.com/X-Sharp/XSharpPublic/commit/3431c7f564c49b845c360f3b38c8830e380d8ced).

**Comment by RobertvanderHulst** [comment]
This information is enough to solve it. We'll look into this asap.

**Comment by cpyrgas** [comment]
Confirmed fixed
