### ISSUE TITLE
Exception when starting X# app from UNC path with AdsSQLServer

### ISSUE THREAD

**Issue by christianschmid200272** [X-Sharp/XSharpPublic#1378]
We deploy our X# application to a shared directory on a central server. If we start the application from the share and try to execute a SQL query via AdsSQLServer we get an error. If we have the application locally and run it from a normal path everything is ok, but if we run the application on a share of the local system we get the same error.  The problem occurs only in connection with AdsSQLServer, normal *.dbf accesses have no problem.

Sample:
FUNCTION Start() AS VOID STRICT
   LOCAL oDB  AS VO.AdsSQLServer
   LOCAL dwRet AS DWORD
   LOCAL hConn AS System.IntPtr

   dwRet := AdsConnect60( "C:\MyPgm\Kabel\DATEN",  XSharp.ADS.ACE.ADS_LOCAL_SERVER, NULL_PSZ, NULL_PSZ, 0, OUT hConn )
   AX_SetConnectionHandle( hConn )
   oDB := VO.AdsSQLServer{"SELECT  AUFTRAG.aufnr  FROM AUFTRAG WHERE (AUFNR = 366590)", , , "AXSQLCDX", ,}
   Console.WriteLine(String.Format("Rows: {0}",oDB:RecCount) )
   oDB:Close()
   WAIT
   RETURN

Description :	Exception raised by CLR or external code: Der Pfad hat ein ungültiges Format.
Subsystem :	mscorlib
GenCode :	EG_ARG Argument error
FuncSym :	INIT
Severity :	ES_ERROR
Can Default :	False
Can Retry :	False
Can Substitute :	False
Stack Trace :	
 PATH:LEGACYNORMALIZEPATH (Line: 0)
 PATH:NORMALIZEPATH (Line: 0)
 PATH:INTERNALGETDIRECTORYNAME (Line: 0)
 _SPLITPATH (Line: 0)
 __SPLITPATH (Line: 0)
 FILESPEC:__DEFAULTFULLPATH (Line: 0)
 FILESPEC:FIND (Line: 0)
 FILESPEC:.CTOR (Line: 0)
 DBSERVER:.CTOR (Line: 0)
 DBSERVER:.CTOR (Line: 0)
 ADSSQLSERVER:.CTOR (Line: 0)
 START (Line: 25)

**Comment by christianschmid200272** [comment]
One more insight on this topic, if I map the network share as drive, AdsSQLServer works as expected. I think somewhere it splits at a colon.

**Comment by RobertvanderHulst** [comment]
Fixed in 2.18.0.4
