### ISSUE TITLE
VS Integration: Intellisense offers static methods to call an instance

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1379]
There is a class in which there are instance methods (overloads) of the same name and static methods. When I enter a colon after the name of the variable representing the class, it opens a drop-down list that offers only instance methods. This is right. I choose one of them. Then, on the same line, I remove the parentheses and re-enter the opening parenthesis to get a hint on the method parameters. But this time Intellisense shows me static methods, although the call is made for the instance. It is not right.

**The following video demonstrates the problem:**
[ScreenRecorderProject1_1](https://1drv.ms/u/s!AlzZH96rHaSP6SW4Q27C1UBdl6SF?e=Zx11US)

**Example project:**
[XSharpBetaTest.zip](https://github.com/X-Sharp/XSharpPublic/files/13205860/XSharpBetaTest.zip)

**Environment:**
X# 2.18.0.4
IDE VS 2022

**Comment by cpyrgas** [comment]
Confirmed fixed
