### ISSUE TITLE
ARRAY{n} creates array of n items, not of n capacity

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#138]
I was wondering about a different behaviour between Vulcan and XSharp:

LOCAL testArray := Array{10} AS Array
In Vulcan testArray is an array of size 0.
In XSharp testArray is an array of size 10 with 10 default elements (NIL). 

Did you change that by purpose?

Thomas

**Comment by RobertvanderHulst** [comment]
I do not remember that this was done on purpose. I changed the behavior to make it the same as Vulcan, so an empty array is now created with a capacity of 10 and a count of 0

**Comment by cpyrgas** [comment]
Robert, it's not as simple as changing the constructor, there's now other code in the X# runtime that depends on the previous behavior. I could find at least ArrayCreate(), __ArrayNewHelper() and AReplicate() that depend on the intialization of the array items in the constructor, but maybe there are also more, so I did not risk changing this myself right now. 

I think better revert this change for now and look into it more closely after the fixed 2.01 build, in order we make sure we avoid introducing other issues right now.

**Comment by cpyrgas** [comment]
Fixed by introducing an alternative constructor for generating an ARRAY with either capacity or size as specified (https://github.com/X-Sharp/XSharpPublic/commit/b31ea665f47f616343015cb29971627a6213e0b0)
