### ISSUE TITLE
VS Integration: Editor freezes when encountering certain code

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1380]
In my real project, I came across code where VS 2022 freezes if you hover your mouse over a certain line in the code.
I created an example project where I reproduced this problem:
[XSharpBetaTest.zip](https://github.com/X-Sharp/XSharpPublic/files/13241256/XSharpBetaTest.zip)

In this project, open "Class1.prg" and hover over line 92 (on the "GetDB" method). The editor will freeze.
If you have line numbering turned off, then the searched line 92 looks like this:
`oDB := oEntries:GetDB(cKey, { x =>`

**Environment:**
X# 2.18.0.4
IDE VS 2022 17.7.6

**Comment by cpyrgas** [comment]
I confirm the problem in all 3 VS versions

**Comment by RobertvanderHulst** [comment]
The problem seems to be related to looking up the type of DbFileCache.oEntries.
The compiler enters an endless loop there.
If you move (for now) the nested type out of the DBFileCache class then the problem is gone.
Or course I will try to fix this.

**Comment by cpyrgas** [comment]
Confirmed fixed
