### ISSUE TITLE
Problem with opening and writing to a file with the FO_EXCLUSIVE flag

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1382]
Following code does not write anything to the disk file, when opening with the FO_EXCLUSIVE flag. Omitting this, it works fine. Also in VO it works as expected in all cases.

```
FUNCTION Start() AS VOID
	LOCAL hPtr AS PTR
	LOCAL sText AS STRING
	
	LOCAL sFile AS STRING
	sFile := "c:\test\_test.txt"
	
	IF File(sFile)
		hPtr := FOpen(sFile,FO_WRITE + FO_EXCLUSIVE )
		sText := "Add some text" // no text written
	ELSE
		hPtr := FCreate(sFile) // or FO_EXCLUSIVE, still works fine
		sText := "Create" // OK
	ENDIF
	
	? FError()
	
	FSeek(hPtr, 0, FS_END)
	
	? FWrite(hPtr, sText), FError()
	
	FClose(hPtr)
```

**Comment by cpyrgas** [comment]
This is due to a logic problem in the XsBufferedFileStream which is used, when the file is opened in exclusive and write only mode as in the sample code. When writing via FWrite(), the class still needs to read from the file, in order to fill the page buffers, but this fails, because it is opened in write only mode. I'd better not touch that code since it's also used for DBFs, will let you guys decide about this.

**Comment by cpyrgas** [comment]
There's also a related problem, when using instead an unbuffered stream (by specifying FO_UNBUFFERED), FWrite() always returns 0 for the bytes written. This is an easy fix, will do that.

**Comment by cpyrgas** [comment]
Robert, what would you like me to do about this? Surely I should not touch the code inside the caching inside the XsBufferedFileStream class, to avoid reading of data!

Personally I would simply make the file runtime functions always use the standard file access win32 api functions, instead of the new buffered stream classes (exclusive mode or not), but I am not sure if you like this idea!

**Comment by RobertvanderHulst** [comment]
Chris,
I think about adding a new constant for the mode in FOPen and FCreate. Something like FO_CACHED.
When this constant is used then the file is opened in cached mode. Otherwise in "plain API" mode.
We an add this constant to the code inside the RDD system that opens the files to enable the caching.

**Comment by cpyrgas** [comment]
Robert, there's already the FO_UNBUFFERED constant, which when applied, opens the file unbuffered. It just had a small problem that I fixed with the commit above. Maybe we should change that, remove the FO_UNBUFFERED constant, open the file unbuffered by default and instead introduce the FO_CACHED constant as you suggest and then only when this is specified, open the file cached?

**Comment by RobertvanderHulst** [comment]
Yes, something like that. Let me look at this carefully tomorrow.

**Comment by RobertvanderHulst** [comment]
The simplest solution for this was to check for files that are opened with FO_WRITE and then set the Unbuffered property for the VOFileMode class to TRUE.

**Comment by cpyrgas** [comment]
Confirmed fixed
