### ISSUE TITLE
DBF and Codepage 866

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1386]
One of my customers, from whom I replaced the old VO application with its new version transported to X#, gave me a DBF file where he indicated the problem that he could not import it with the correct character encoding (Cyrillic character set). On Windows this is encoding 1251, and on DOS it is 866. This customer imported such files in an old VO application without any problems. I have studied this file. This file does not indicate the encoding value (29th byte). The actual encoding of this file is DOS 866. In the old VO application, such files could be converted by enabling SetAnsi(False) before opening the original file, and then transferring records from it to a new file with SetAnsi(True) enabled. This approach doesn't work in X#. Having studied the X# Runtime, I saw that when opening a DBF, the CodePageExtensions.ToCodePage method is executed. In my case, the value CP_DBF_DOS_OLD (0) is passed to it and with this value we go to the OTHERWISE branch, where the CP_INI_DOS_US (437) encoding is enabled. As a result, the DBF driver returns strings that I cannot convert even using the Oem2Ansi function. The old VO for such a DBF file (encoding 0) somehow understood that it was necessary to enable encoding 866. Perhaps the Windows regional settings were used.

Now I manually set the value 0x65 in the 29th byte in this file, which corresponds to the 866 encoding, and the customer accepted this file normally.

This file is provided to the customer by a third party (utility company). Most likely there is some old software and it is unlikely that they will be able to change their exports. Therefore, I need to offer my customer some kind of solution. Is it possible that the DBF driver in X# will recognize the DBF encoding when it is not specified, just like VO did?

**Example file:**
[RAB_KV.zip](https://github.com/X-Sharp/XSharpPublic/files/13412933/RAB_KV.zip)

**Environment:**
X# 2.18.0.4

**Comment by leon-ts** [comment]
As one of the options, it would be enough (but I’m not 100 percent sure of this) to add something like RuntimeState.DefaultCodePage (conventional name, just for example). Of course, the best option would be to understand how VO "understood" which encoding to choose when the value 0 was specified in the DBF. But if this cannot be done, then perhaps RuntimeState.DefaultCodePage could help.

**Comment by RobertvanderHulst** [comment]
Thanks for the suggestion, but I am sure that we will be able to discover how VO did this.

**Comment by RobertvanderHulst** [comment]
The VO DBF driver checks for the DBF codepage, and when it does not recognize it, then it assumes it is an OEM file, so it sets the Ansi flag for the DBF to false and uses the lock offset for DOS DBF files.
In VO that means that when data is written to disk and SetAnsi() is TRUE then the function Ansi2OemBuff is called to convert the bytes to OEM. This will use the current OEM codepage.
In X# we have now indeed hardcoded code page 437 for unrecognized codepages. 
We should replace that with the current OEM codepage. That should not be a problem I think.

**Comment by RobertvanderHulst** [comment]
Chris, can you create a test RDD and send that to Leonid?

**Comment by leon-ts** [comment]
Robert, Chris,
My customer and I have now temporarily solved the problem by manually writing the encoding code in the 29th byte into the DBF file before importing it from a third party. Therefore, now for me there is no urgent need for a new RDD. I'll test it in the general beta test when it happens.

**Comment by cpyrgas** [comment]
Leonid, OK, but in case you have time to give it a test in advance, here are the newer rutnime dlls:

https://www.dropbox.com/scl/fi/xeto4gqy5xe433xf6j3cs/RuntimeUpdate_2020_11_30.zip?rlkey=n9zm582l8flb6ubjoo7zm52xx&dl=0

**Comment by leon-ts** [comment]
Confirmed fixed!

**Comment by leon-ts** [comment]
Confirmed fixed!
