### ISSUE TITLE
Multiple type constraints in a generic type

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1389]
When compiling the following code, an error occurs:
```
CLASS TestClass<K, T> WHERE K IS STRUCT WHERE T IS NEW()
END CLASS
```

**The compiler reports the error:** 
> Error XS9002 Parser: unexpected input 'WHERE'

**Tip from Chris:**
> It does work if you switch the order of the WHERE expressions!

**Environment:**
Compiler X# 2.18.0.4

**Comment by RobertvanderHulst** [comment]
There is a rule in the lexer that expects an ID after the STRUCT keyword. This causes the WHERE keyword to be treated as an ID.
This is a rare location where the STRUCT keyword is followed by another keyword. 
Btw: in the core dialect you would have to use the full keyword STRUCTURE:  `WHERE K IS STRUCTURE WHERE T IS NEW()`

**Comment by cpyrgas** [comment]
Robert, trying the new compiler from the latest actions still shows the previous behavior. Do you need to force an update or something?

**Comment by RobertvanderHulst** [comment]
I have not merged the changes into the main branch yet. If you want it then you need to run the workflow in te XSharpCompiler branch. If you can wait, then I will merge the changes today.

**Comment by cpyrgas** [comment]
Yeah, it's not urgent, I was just wondering. It can wait, I will look into the runtime issues for now

**Comment by cpyrgas** [comment]
Confirmed fixed
