### ISSUE TITLE
Would it be possible to disable line-comments with && by a compiler option

### ISSUE THREAD

**Issue by HSteinmair** [X-Sharp/XSharpPublic#1394]
It would be great to be able to use the && logical operator together with the || logical opertor.
For now it is not possible since && is recognised as line-comment.

**Comment by RobertvanderHulst** [comment]
Holger, The `&&` operator is recognized as line-comment in the VO, FoxPro, Harbour and XBase++ dialects, in the Core and Vulcan dialect that `&&` operator is the logical operator.
`||` is recognized as OR operator in all dialects, except when it is inside a codeblock

**Comment by RobertvanderHulst** [comment]
But we could add a compiler option to suppress the use of `&&` a Single Line comment.

**Comment by HSteinmair** [comment]
Yes exactly since I was switching between projects where we have different settings/configurations (X# core and X# VO)
I noticed that the function of the &&-operator changes like you have stated.
The compiler option would be a great solution!
Thank you.

**Comment by RobertvanderHulst** [comment]
Ok, do you have a suggestion for the "name" of the option?

**Comment by RobertvanderHulst** [comment]
Holger,
We are thinking of the following commandline option:
`/modernsyntax`
This would enable the following options:
- && token would be seen as logical AND (and no longer be the start of a single line comment)
- remove the support for the `*` character at the start of the line to turn the whole line into a comment
- remove the support for bracketed strings `[somestring]`. This will make it easier for the compiler to support attributes.
- remove the support for parenthesized expressions (so it will be easier for the compiler to support tuples, like in 
   `(a,b) := SomeFunctionThatReturnsATuple()`)

What do you think of this?
Can you discuss that in your team ?
Or should we only change the && token? In that case our suggestion is `/ampampislogical`

**Comment by HSteinmair** [comment]
I like the idea of the modernSyntax-option.
I will discuss this as you suggested and come back to you with a feedback.
In any case the naming is precise and would be great.
Thanks again for your considerations.

**Comment by RobertvanderHulst** [comment]
What I meant was not Parenthesized expressions, but Parenthesized expression lists. These are things like this:
` x := (y := 10, y ++, y++) `
where x gets the last value of the expression list inside parentheses.
This is not supported in Roslyn. We have had to add some dirty code to implement this.
We are working on tuple support at this momentm, and an expression like
`(a,b) := SomeFunctionThatReturnsATuple()`
is parsed as an parenthesized expressionlist at this moment.
We have seen this used by people in (macro compile) codeblocks, especially inside IIF() where each branch can only contain one expression. People have (ab) used parentesized expression lists for this.

`x := {| l, serv,result| iif (l, (serv := DbServer{}, result := serv:FieldGet(1), serv:Close(), result), NIL)}`

And we have seen much more complex codeblocks in real code!
If you find this difficult to read, consider how complicated it was for us to implement this,

**Comment by RobertvanderHulst** [comment]
Holger,
Do you have any feedback on this: https://github.com/X-Sharp/XSharpPublic/issues/1394#issuecomment-1842531406

**Comment by HSteinmair** [comment]
> Holger, Do you have any feedback on this: [#1394 (comment)](https://github.com/X-Sharp/XSharpPublic/issues/1394#issuecomment-1842531406)

Hi Robert,
sorry that I kept you waiting on this!
For us, it  would not be problematic since we don't use parenthesized expression lists.
At least we are pretty sure that we don't have any.

Thanks you for your patience.

**Comment by cpyrgas** [comment]
It's mostly done, except for that the /modernsyntax option breaks support for tuple deconstruction. Following samples from the help file compile fine without this option, but with /modernsyntax+ they cause an error XS9002: Parser: unexpected input '('

```
FUNCTION Start() AS VOID
  LOCAL oCustomer AS TUPLE(Name AS STRING, Age AS INT)
  oCustomer := TUPLE{"Nikos", 47}
 
  LOCAL name AS STRING
  LOCAL age AS INT
 
  (name, age) := oCustomer
  ? name, age // "Nikos", 47
```


```
FUNCTION Start() AS VOID
  LOCAL oCustomer AS TUPLE(Name AS STRING, Age AS INT)
  oCustomer := TUPLE{"Nikos", 47}
 
  LOCAL (name AS STRING, age AS INT) := oCustomer
  ? name, age // "Nikos", 47
  // You can also deconstruct into existing local variables without the LOCAL keyword:
  (name, age) := oCustomer
```

**Comment by cpyrgas** [comment]
Confirmed
