### ISSUE TITLE
Use Microsoft.Data.Sqlite instead of System.Data.Sqlite

### ISSUE THREAD

**Issue by baramuse** [X-Sharp/XSharpPublic#1397]
**Is your feature request related to a problem? Please describe.**
System.Data.Sqlite only supports x86 and x64 platforms so would not work on a windows-arm machine (or emulated windows-arm on Apple silicon) thus intellisense is not working on ARM platforms.

**Describe the solution you'd like**
Microsoft released an ADO.net compliant SQLite provider based on SQLitePCLRaw supporting way more platforms.
[https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite](https://learn.microsoft.com/en-us/dotnet/standard/data/sqlite)
That's actually the provider they use in the Roselyn project, or in the UAP/MAUI/Xamarin space.
As both are ADO.net providers, replacement _should_ be easy.

**Describe alternatives you've considered**

**Additional context**
I know it's a pretty edgy case - and most probably I'm the only one running XSharp on a mac - but if it's a very light change that would still be a nice addition.
I tried to do it on mly own but I guess asking the dev how to setup the whole build/intstallation/test process for the VSIntegration project would take more time than just trying to replace  System.Data.Sqlite with Microsoft.Data.Sqlite

Regards.

**Comment by RobertvanderHulst** [comment]
Basile,
Thanks for the suggestion. I have given it a try in an internal build and it seems to work. There are some subtle differences in the handling of null values and the connection string paramerters for example. But I'll try to use this for the next build of our VS integration.

**Comment by baramuse** [comment]
Hi Robert, this is awesome news ! How can I test it ? 
Wait for the next beta ?

**Comment by RobertvanderHulst** [comment]
Basile,
Before the next beta I will send a set of file to test.

**Comment by RobertvanderHulst** [comment]
In 32 bits VS we use the "old" System.Data.SQLite, for 64 bits VS we use the Microsoft.Data.SQlite.

**Comment by baramuse** [comment]
> In 32 bits VS we use the "old" System.Data.SQLite, for 64 bits VS we use the Microsoft.Data.SQlite.

For x64 and ARM64?
https://devblogs.microsoft.com/visualstudio/arm64-visual-studio-is-officially-here/

**Comment by RobertvanderHulst** [comment]
Yes for both. Please test the beta that I just released.

**Comment by baramuse** [comment]
So I tried the beta and I have this error : 
```
SetSite failed for package [XSharp Project System]Source: 'XSharp.CodeModel' Description: The type initializer for 'XSharpModel.XDatabase' threw an exception.
System.TypeInitializationException: The type initializer for 'XSharpModel.XDatabase' threw an exception. ---> System.Exception: Library e_sqlite3 not found
plat: win
suffix: DLL
possibilities (2):
    1) c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\runtimes\win-arm64\native\e_sqlite3.dll
    2) c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\e_sqlite3.dll
win TryLoad: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\runtimes\win-arm64\native\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
win TryLoad: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
NOT FOUND

   at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   at XSharpModel.XDatabase.Initializex64() in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\Database\XDatabase.prg:line 30
   at XSharpModel.XDatabase..cctor() in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\Database\XDatabase.prg:line 53
   --- End of inner exception stack trace ---
   at XSharpModel.XDatabase.CreateOrOpenDatabase(String cFileName) in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\Database\XDatabase.prg:line 65
   at XSharpModel.XSolution.Open(String cFile) in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\ProjectSystem\XSolution.prg:line 121
   at XSharp.Project.XSharpShellLink.SolutionEvents_OnAfterOpenSolution(Solution solution) in E:\XSharp\Dev\src\VisualStudio\ProjectPackage\XSharpShellLink.cs:line 375
   at XSharp.Project.XSharpShellLink.<<-ctor>b__4_0>d.MoveNext() in E:\XSharp\Dev\src\VisualStudio\ProjectPackage\XSharpShellLink.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at XSharp.Project.XSharpShellLink..ctor() in E:\XSharp\Dev\src\VisualStudio\ProjectPackage\XSharpShellLink.cs:line 32
   at XSharp.Project.XSharpProjectPackage.<InitializeAsync>d__13.MoveNext() in E:\XSharp\Dev\src\VisualStudio\ProjectPackage\XSharpProjectPackage.cs:line 174
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)System.Exception: Library e_sqlite3 not found
plat: win
suffix: DLL
possibilities (2):
    1) c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\runtimes\win-arm64\native\e_sqlite3.dll
    2) c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\e_sqlite3.dll
win TryLoad: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\runtimes\win-arm64\native\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
win TryLoad: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\e_sqlite3.dll
thrown: System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
   at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
NOT FOUND

   at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
   at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
   at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
   at XSharpModel.XDatabase.Initializex64() in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\Database\XDatabase.prg:line 30
   at XSharpModel.XDatabase..cctor() in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\Database\XDatabase.prg:line 53
```

**Comment by RobertvanderHulst** [comment]
Basile,
I do not have an machine with Arm and Windows on Arm to test.

Can you create a small C# console test app, add a nuget reference to Microsoft.Data.SQlite and then try the following code in the main() function?

```
using Microsoft.Data.Sqlite; // this should go to the start of the file.
.
.
// this goes inside the main function.

SQLitePCL.Batteries.Init()

var con = new Microsoft.Data.Sqlite.SqliteConnection("Data source=:memory:");
con.Open();
string stm = "SELECT SQLITE_VERSION()";
using var cmd = new SqliteCommand(stm, con);
string version = cmd.ExecuteScalar().ToString();
Console.WriteLine($"version: {version}");
```
Does this work?
Can you mail me the output folder. I'd like to see which files there are in the output folder.

**Comment by baramuse** [comment]
> Basile, I do not have an machine with Arm and Windows on Arm to test.
> 
> Can you create a small C# console test app, add a nuget reference to Microsoft.Data.SQlite and then try the following code in the main() function?
> 
> ```
> using Microsoft.Data.Sqlite; // this should go to the start of the file.
> .
> .
> // this goes inside the main function.
> 
> SQLitePCL.Batteries.Init()
> 
> var con = new Microsoft.Data.Sqlite.SqliteConnection("Data source=:memory:");
> con.Open();
> string stm = "SELECT SQLITE_VERSION()";
> using var cmd = new SqliteCommand(stm, con);
> string version = cmd.ExecuteScalar().ToString();
> Console.WriteLine($"version: {version}");
> ```
> 
> Does this work? Can you mail me the output folder. I'd like to see which files there are in the output folder.

I've added the platform as output : 
`Console.WriteLine($"platform: {System.Runtime.InteropServices.RuntimeInformation.ProcessArchitecture}");``
```
version: 3.41.2
platform: Arm64
```

Maybe I could provide you with some time with a remote desktop on my machine so you can run a few tests ?

**Comment by baramuse** [comment]
> So I tried the beta and I have this error :
> 
> ```
> SetSite failed for package [XSharp Project System]Source: 'XSharp.CodeModel' Description: The type initializer for 'XSharpModel.XDatabase' threw an exception.
> System.TypeInitializationException: The type initializer for 'XSharpModel.XDatabase' threw an exception. ---> System.Exception: Library e_sqlite3 not found
> plat: win
> suffix: DLL
> possibilities (2):
>     1) c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\runtimes\win-arm64\native\e_sqlite3.dll
>     2) c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\e_sqlite3.dll
> win TryLoad: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\runtimes\win-arm64\native\e_sqlite3.dll
> thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
>    at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
> win TryLoad: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\e_sqlite3.dll
> thrown: System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
>    at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
> NOT FOUND
> 
>    at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
>    at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
>    at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
>    at XSharpModel.XDatabase.Initializex64() in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\Database\XDatabase.prg:line 30
>    at XSharpModel.XDatabase..cctor() in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\Database\XDatabase.prg:line 53
>    --- End of inner exception stack trace ---
>    at XSharpModel.XDatabase.CreateOrOpenDatabase(String cFileName) in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\Database\XDatabase.prg:line 65
>    at XSharpModel.XSolution.Open(String cFile) in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\ProjectSystem\XSolution.prg:line 121
>    at XSharp.Project.XSharpShellLink.SolutionEvents_OnAfterOpenSolution(Solution solution) in E:\XSharp\Dev\src\VisualStudio\ProjectPackage\XSharpShellLink.cs:line 375
>    at XSharp.Project.XSharpShellLink.<<-ctor>b__4_0>d.MoveNext() in E:\XSharp\Dev\src\VisualStudio\ProjectPackage\XSharpShellLink.cs:line 54
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
>    at XSharp.Project.XSharpShellLink..ctor() in E:\XSharp\Dev\src\VisualStudio\ProjectPackage\XSharpShellLink.cs:line 32
>    at XSharp.Project.XSharpProjectPackage.<InitializeAsync>d__13.MoveNext() in E:\XSharp\Dev\src\VisualStudio\ProjectPackage\XSharpProjectPackage.cs:line 174
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.VisualStudio.Shell.AsyncPackage.<>c__DisplayClass21_0.<<Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize>b__1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
>    at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)System.Exception: Library e_sqlite3 not found
> plat: win
> suffix: DLL
> possibilities (2):
>     1) c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\runtimes\win-arm64\native\e_sqlite3.dll
>     2) c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\e_sqlite3.dll
> win TryLoad: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\runtimes\win-arm64\native\e_sqlite3.dll
> thrown: System.ComponentModel.Win32Exception (0x80004005): The specified module could not be found
>    at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
> win TryLoad: c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\e_sqlite3.dll
> thrown: System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
>    at SQLitePCL.NativeLibrary.TryLoad(String name, Loader plat, Action`1 log, IntPtr& h)
> NOT FOUND
> 
>    at SQLitePCL.NativeLibrary.Load(String libraryName, Assembly assy, Int32 flags)
>    at SQLitePCL.Batteries_V2.MakeDynamic(String name, Int32 flags)
>    at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
>    at XSharpModel.XDatabase.Initializex64() in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\Database\XDatabase.prg:line 30
>    at XSharpModel.XDatabase..cctor() in E:\XSharp\Dev\src\VisualStudio\XSharpCodeModelXs\Database\XDatabase.prg:line 53
> ```

From the error there is a small difference in the path of the arm dll folder :
it's looking here :  
`c:\program files\microsoft visual studio\2022\preview\common7\ide\extensions\xsharp\project\runtimes\win-arm64\native\e_sqlite3.dll`
but it's there - on my machine at least - : 
`C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\Extensions\XSharp\Project\runtimes\win-arm\native\e_sqlite3.dll`

**Comment by RobertvanderHulst** [comment]
Yes, remote access to your machine may help. It could be as simple as a missing DLL.
Please send me the access data by mail. I have time tomorrow during office hours.

**Comment by baramuse** [comment]
I tried to duplicate the folder with win-arm64, but still got issues while loading 
You'll see that tomorrow I guess then.

**Comment by baramuse** [comment]
As of 2.19.0.1 it works as expected.
Tested on win11-arm, VS2022 community.
