### ISSUE TITLE
Call of DBServer.Deleted in X# 2.18.04 significantly slower than in 2.17.03.

### ISSUE THREAD

**Issue by christianschmid200272** [X-Sharp/XSharpPublic#1399]
Hello,
we use the bBrowser and bServer from bbrowser.net. After the last update of the X# Runtime from 2.17.03 to 2.18.04 we noticed that the runtime of several actions like e.g. SELF:oDCbBrowser:Server:Notify(NOTIFYFILECHANGE) has worsened significantly.

In the meantime, I have been able to limit the deterioration and reduce it to a specific call 
"SELF:auData[iColumn - SELF:iFirstColumn + 1, iCacheRowPos, BDI_DELETED] :=** oColumn:Deleted"**
in \bBrowser\Controls\bBrowser (Control).prg method CahceUpdadte. For each column the server of the column is asked for Deleted, the server we use is a bServer which is derived from DBServer.

If I reset to X# version 2.17.03 or delete the call to .... := oColumn:Deleted when using X# version 2.18.04, then the runtime is the same as with X# version 2.17.03. After the rest of the code of bTools as well as our code is unchanged.  Since only by changing the X# version the problem is gone I think the problem is also in the X# Runtime.

Examples:		
Runtime of the code line "SELF:auData[iColumn - SELF:iFirstColumn + 1, iCacheRowPos, BDI_DELETED] := oColumn:Deleted" with...
X# Runtime 2.17.03 - **one millisecond**												
X# Runtime 2.18.04 with oColumn:Deleted call- **15 to 18 milliseconds**
X# Runtime 2.18.04 without oColumn:Deleted call, only with constant := False - **one millisecond**
![DataColumnDeleted](https://github.com/X-Sharp/XSharpPublic/assets/123379297/671166eb-86bd-4e6c-8e2e-09b54e020879)

The variable oServer in bDataColumn is of type Object, this may be another hint that helps.

Creating a sample application for these cases is extremely time-consuming, which is why I won't do it for the time being. It may be possible to determine something about the history in GIT between the two versions.

I hope my explanations are reasonably understandable and you can make sense of them.

Greetings

**Comment by RobertvanderHulst** [comment]
The only change that I can find that can cause this, is that we have added a call to IF !SELF:Used .... ENDIF in several DbServer properties inside the DbServer RDD. The DbServer:Used property selects the workarea and calls Used() in the workarea.
After that the Deleted property is read and this also selects the workarea. 
I will change the code to directly call Used() in the body of the code and to not call the Used property. This should reduce the # of workarea switches.

Btw: What is the setting of DbSetRestoreWorkarea() in your app?

If this change does not fix it, then we really need an example. Otherwise, it will be too time consuming for us to hunt this down.
And of course calling the deleted property to a variable of type object is not optimal.
I would recommend to change the oServer field to the type DataServer. That shoukd speed up things a lot.

**Comment by christianschmid200272** [comment]
The setting of  DbSetRestoreWorkarea is DbSetRestoreWorkarea(FALSE).

**Comment by cpyrgas** [comment]
And here's an updated dll for Christian to try out:

[VORDDClasses.zip](https://github.com/X-Sharp/XSharpPublic/files/13578000/VORDDClasses.zip)

**Comment by christianschmid200272** [comment]
Thanks for the file, but unfortunately the customization did not improve the runtime. I will now try to create a sample application that will reproduce the problem.
One more hint, for testing I simply replaced the VORDDClasses.dll of version 2.18.04 with the VORDDClasses.dll of version 2.17.03 (I am surprised that the application starts at all) and the runtime was ok again.

**Comment by RobertvanderHulst** [comment]
Christian,
If there is a VORDDClasses.dll in the GAC then this must be replaced as well!
And the compatibility (so you can swap DLLs) is intentional.

**Comment by christianschmid200272** [comment]
Robert,
I ran the test on a system without installed X# Runtime, only with the installation directory which is created for distribution including all references.

**Comment by christianschmid200272** [comment]
Included is a sample application to reproduce the performance problem. No attention was paid to creating a clean application, but to reproducing the problem with as little effort as possible.
The example is based on a very small table "WAEHRUNG.dbf" (Currency) and the dependencies necessary for the test.

1. start application, select menu File -> Currencies. A shell window is created and a browser with the specified table is created. The browser is a control derived from bTools.bBrowser with various extensions.

2. in the open browser, the focus should be on the column "Kennz", the key input "u" executes a search in the column "Kennz" via an event handler, in the output window of Visual Studio the integrated measured values are displayed as debug outputs.
![test](https://github.com/X-Sharp/XSharpPublic/assets/123379297/f80e84a3-9d80-4247-adf6-13ae9e0277f9)
[Performance_Test_1399.zip](https://github.com/X-Sharp/XSharpPublic/files/13600947/Performance_Test_1399.zip)

Here is a summary of the contents of the Performance_Test_1399.zip file.
- Project folder bSample - SensitiveSearch.sln
- Project bSample - SensitiveSearch.xsproj which originates from a sample application by Joachim Bieler.
- In ... \Bin\Debug contains all files necessary for execution, the bSample_SensitiveSearch.exe contained therein can be executed directly.
- The file Time_measurements.txt contains measurement times for the DLL versions used and the code blocks where the debug outputs are implemented. 3 variants were measured
1. installed X# Runtime 2.18.04, the file VORDDClasses.dll replaced with the version from 03.08.2023. The code block of the measurement was run with the original oColumn:Deleted call in 24 milliseconds.
2. installed X# Runtime 2.18.04, replaced the file VORDDClasses.dll with the version from 06.12.2023. The code block of the measurement was run with original oColumn:Deleted call in 245 milliseconds.
3. installed X# Runtime 2.18.04, replaced the file VORDDClasses.dll with the version from 06.12.2023. The code block of the measurement was run with a constant false instead of the oColumn:Deleted call in 55 milliseconds.

I hope this solves the problem :-)

**Comment by RobertvanderHulst** [comment]
Christian,
The sample code contains the shell window, but not the source code for the server classes or the window.
I also do not see how collected the data with the CacheUpdate log from Time_measurements.txt.
It will be difficult to diagnose the problem if we do not have that code.

**Comment by christianschmid200272** [comment]
Good morning Robert,
I have now included all projects required for debugging in the project folder. I want to point out that the sources of the bBrowser and bServer with the debug outputs are also included, but there is no explicit release from Joachim Bieler. 
Since the zip file is too big for the upload from GitHub please use the following OneDrive link: 
https://1drv.ms/u/s!Ah_k4pwG65BAhlhsoSTFRTwlwE-Q?e=P0PyyD

**Comment by christianschmid200272** [comment]
Robert,
I have found a commit that I can use to determine the behavior. https://github.com/X-Sharp/XSharpPublic/commit/59526f19e39d99879889d62cc412486f85b2c9cb
If I undo the changes from the commit for src/Runtime/VOSDK/Source/VOSDK/RDD_Classes_SDK/DBServerA.prg, the runtimes are again as in runtime version 2.17.03. I have integrated a counter within my test setup to determine how often DbServer.Used is called. Without the change by the mentioned commit DbServer.Used is called 109 times, with the change from the commit DbServer.Used is called 2022 times.

**Comment by RobertvanderHulst** [comment]
Christian,
That change in the DbServer code was made to prevent exceptions in the debugger when looking at instances of an ADS based DbServer after the server was closed.
The current implementation of DbServer:Used cannot explain the speed differences that you see. The code in there is this:
```
    ACCESS Used
        RETURN SELF:wWorkArea != 0 .and. SELF:oRDD != NULL
```
I can't believe that this will slow down your code so much.

**Comment by christianschmid200272** [comment]
Robert,
when I debug this, a different code is executed than the one you describe.
![DBServerA](https://github.com/X-Sharp/XSharpPublic/assets/123379297/9c3eef76-0386-44e2-95af-a8858e9d23d6)

**Comment by cpyrgas** [comment]
Robert, I think there has been some sort of missed synch between repos?

In my DevRT branch, I see the code you posted for ACCESS Used
In my DevPublic branch, I see Christian's version of the code for ACCESS Used

**Comment by christianschmid200272** [comment]
The code I use for debugging comes from the XSharpPublic-main.zip which I get offered on GitHub. This code corresponds to what I see in the public repo.

**Comment by RobertvanderHulst** [comment]
Christian,
The changed code is still in the Runtime branch and has not been merged in the main branch.

**Comment by RobertvanderHulst** [comment]
Chris,
> Robert, I think there has been some sort of missed synch between repos?
> 
> In my DevRT branch, I see the code you posted for ACCESS Used In my DevPublic branch, I see Christian's version of the code for ACCESS Used

You did not miss anything, maybe only the concept of how branches work.
The changed code is in the runtime branch. Your Devpublic folder has the VSIntegration branch.

**Comment by christianschmid200272** [comment]
Does this mean that there will be a new release in which the branches have been merged correctly?

**Comment by RobertvanderHulst** [comment]
Each time we release a new build, then we'll merge all the relevant branches into the main branch.

**Comment by cpyrgas** [comment]
Robert, so that could indeed explain the performance issues that Christian is seeing? Because in the VORDDClasses.dll, indeed the long version of the code is included in the 2.18 release.

**Comment by christianschmid200272** [comment]
Hello, I would like to continue testing the topic and have created and cloned a fork of "XSharpPublic-main". Unfortunately I don't see the branch "feature/runtime" to integrate the last changes of Robert in my repo. It is not enough to get the latest version of "DBServerA.prg" files, the files alone are not compatible. Is there a possibility that I can create a testable code version for me?

**Comment by RobertvanderHulst** [comment]
Christian,
If you change the code in the Access to this
```
ACCESS Used
        RETURN SELF:wWorkArea != 0 .and. SELF:oRDD != NULL
```
do you still see the speed problem?

**Comment by RobertvanderHulst** [comment]
Christian,
There is a branch remotes/origin/feature/Runtime. You will have to switch to that branch and create a local copy of that branch.

**Comment by leon-ts** [comment]
**Just an idea to note:**
You can add a special event that will be raised when the workarea is closed. For example, in the CoreDb.CloseArea method, as well as in other places where IRdd.Close is called directly (if any). Further, in classes that are wrappers for workareas, such as DbServer, you can add a subscription to this special event and, when it occurs, reset a certain field to False, for example, lUsed (logic). Next, in all the places where the Used property is currently checked, you can simply check the lUsed field.

P.S. X# has an event system for workareas, but it would be cumbersome for this situation because when you enable it, it works for all operations in the workarea. And this can cause an additional decrease in application performance.

P.S.2 I also have a class similar to DbServer. I don't check Used in it, but sometimes there is a problem when the workarea that this wrapper class is associated with is closed without going through the Close method. For example, someone called the VODBCloseAll function. Further, another file may be opened with the workarea number that this class managed, but my class will not know anything about this and will continue to work with it. The special event idea I proposed would help solve such problems.

**Comment by RobertvanderHulst** [comment]
Leonid,
Who is the "You" in your comment? Christian or the DevTeam?

**Comment by leon-ts** [comment]
Robert,
I apologize for my English. Perhaps I am not accurately translating my thoughts into another language. By “You” I meant the development team, since the idea I proposed involves making changes to the official Runtime. This is just an idea to consider.

**Comment by leon-ts** [comment]
Robert,
When I have a little more free time from my day job, I will try to implement this and make a pull request.

**Comment by cpyrgas** [comment]
Christian, any chance you can prepare a small sample showing the problem, so we can also try it here and run back to back tests with the previous runtime? I see that previously you mentioned one, but forgot to include the download link maybe? Just please not that it needs to be easily compilable and runnable from us, so no external dependencies etc.

**Comment by christianschmid200272** [comment]
Chris,
as the example mentioned contains internal code from us, I only gave the link to Robert and have already deleted it. I will try to provide a simpler example with the latest findings.

**Comment by christianschmid200272** [comment]
Hello,

the problem is not the implementation of DbServer.Used per se, but the multiple use of it compared to earlier versions. In bServer as well as in our classes, DbServer is derived from and also overwritten by Used. Each of these overrides is now included in the chain of multiple calls to DbServer.Used, which ultimately leads to the degraded behavior. Adjustments to our code in the classes derived from bServer/DbServer have now brought an improvement.

What irritates me a little, in the course of the many tests I have of course checked the "Access Used" overwritten in our code, but the debugger never reached the location, even the analysis tools from Visual Studio always showed me DbServer.Used. I removed an existing Visual Studio 2019 from my system and completely removed and reinstalled XSharp. I cannot say whether it is a coincidence that the debugger now runs through the chain of calls or whether it is due to the software cleanup. 

As far as I am concerned, the issue can be closed.

Many thanks for your support
Christian

**Comment by RobertvanderHulst** [comment]
Chirstian,
Thanks for your comments. I will close the issue.
