### ISSUE TITLE
NoIVarget wrong behaviour when using IDynamicProperties

### ISSUE THREAD

**Issue by fforay** [X-Sharp/XSharpPublic#1401]
In a LateBound context, when using a Class that implements IDynamicProperties, the NoIVarget method only run against the IDynamicProperties, and the PropertyContainer class; not looking for other properties in the Class

**To Reproduce**
The attached solution shows the trouble.
When commenting the IMPLEMENTS, the sample runs fine.

**Expected behavior**
If the PropertyContainer don't find the LateBound property, we should also have a lookup in the "standard" properties.

Using XSharp 2.18.0.4 and FoxPro Dialect.
[VFPLateBound.zip](https://github.com/X-Sharp/XSharpPublic/files/13688786/VFPLateBound.zip)

**Comment by RobertvanderHulst** [comment]
The problem was not that the properties of the type were not included in the PropertyContainer, but the Fields of the type.
