### ISSUE TITLE
Hex2C() gives different results with lower case letters than with upper case

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1402]
https://www.xsharp.eu/forum/topic?t=3553&p=28161#p28161

Both in VO and X#, Hex2C() gives different results when using lower case hex letters:

? Hex2C ( "4A" ), Hex2C ( "4B" ) // J K
? Hex2C ( "4a" ), Hex2C ( "4b" ) // @ @
? Hex2C ( "3A" ) // :
? Hex2C ( "3a" ) // 0

**Comment by cpyrgas** [comment]
Robert, what do you think, should we change it in X#, to return the same thing for both lower and upper case hex letters? It looks like a bug, on the other hand it is compatible with VO and (possibly) existing code.

**Comment by RobertvanderHulst** [comment]
I think we should fix it. It does not make sense that the lower case characters are ignored. And maybe we should also throw an error when the string contains anything other than a hex character?

**Comment by cpyrgas** [comment]
OK, fixed now. Didn't make it throw an error on invalid characters, because you never know and anyway VO functions are full of allowing invalid arguments, for example Left("test",100) or even CharPos("test",100) do not throw an error.
