### ISSUE TITLE
VOXporter converts attributes to string literals

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1404]
The VOXporter converts this 

function Start()                        // VXP-COM
//[STAThread];                   // VXP-UNC
// function Start() as void             // VXP-UNC
LOCAL n AS INT

to

e“STAThread“;              
function Start() as void
LOCAL n AS INT

Problem is that the attribute is seen by the VOXporter as a string literal, delimited with []

**Comment by wriedmann** [comment]
VOXPorter also prefixes reserved words when uncommenting:
`// delegate ListViewHeader_NewProc_delegate(hWnd as ptr, msg as dword, wParam as dword,lParam as long) as longint		// VXP-UNC`
is converted to 
`@@delegate ListViewHeader_NewProc_delegate(hWnd as ptr, msg as dword, wParam as dword,lParam as long) as longint`

**Comment by cpyrgas** [comment]
Fixed, now after commenting/uncommenting/deleting lines with VOXP/VXP tags, VOXporter does not further touch them anymore.
