### ISSUE TITLE
UDCs not completely or at all implemented

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1407]
There are several UDCs that are missing, or are partially implemented, even though they are documented to work. Will do a thorough check and will be updating this list.

Missing:
(general:)
- CANCEL (equivalent to QUIT which is defined)
- CLEAR ALL

(file:)
- DELETE FILE f
- ERASE f
- COPY FILE f1 TO f2
- RENAME f1 TO f2

(database:)
- DELETE TAG
- INDEX ON
- SET DRIVER TO
- SET MEMOBLOCK TO
- SET OPTIMIZE 
- SET DESCENDING
- SET SCOPE TO
- SET SCOPEBOTTOM TO 
- SET SCOPETOP TO 

(set:)
- SET DIGITFIXED 
- SET DIGITS TO
- SET COLLATION TO
- SET INTERNATIONAL TO

Missing, but obsolete (?):
- DIR
- CLEAR
- BROWSE (FoxPro)

Partially implemented:
- SET INDEX TO xcIndexFileList ADDITIVE (ADDITIVE clause missing)
- SET ORDER TO TAG "tag" (TAG clause missing)

**Comment by cpyrgas** [comment]
I went through the full list of UDCs specified in the help file and updated the list above. Robert, please scan through the list, do you have any comments? Should I defined the missing UDCs (and update the incomplete ones) based on their VO definitions? What about the obsolte(?) ones?

**Comment by RobertvanderHulst** [comment]
Chris,
I have adjusted SET INDEX TO and SET ORDER TO.
INDEX ON is defined. Or are you missing some clauses?
And can you add the other ones?

**Comment by cpyrgas** [comment]
Robert,

VO allows also a single 
INDEX ON abc
without a TAG clause specified (X# requires it), but this does not make sense as it gives a runtime error, so it's fine in X# now.

Yes, I will add the other ones, I guess VO is the most reliable source?

**Comment by RobertvanderHulst** [comment]
Yes, use VO as source. But you may also want to look in std.ch from XBase++ and std.ch from Harbour include folder.  I am attaching these to this message.
[std_ch.zip](https://github.com/X-Sharp/XSharpPublic/files/13816723/std_ch.zip)

**Comment by cpyrgas** [comment]
I have now implemented them all, except for the obsolete ones and the CLEAR ALL one. This is supposed to "Release all public and private variables" (in addition to closing workareas), do we have something like that in X#?

**Comment by RobertvanderHulst** [comment]
Chris,
Yes, there is a function call to release memory variables. We can do that conditionally in the UDC becauze there is also a preprocessor macro variable that is set when compiling with memory variables enabled. I will add this.
