### ISSUE TITLE
/initlocals compiler option also initializes class fields

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1408]
https://www.xsharp.eu/forum/topic/3569

When using /initlocals, in the following code the field nTest1 (and nTest2) gets reset to 0, when calling the parent constructor. The initlocals compiler option should only initialize local varts as the name suggests and not class fields.

```
FUNCTION Start() AS VOID
	LOCAL o := Child{} AS Child
	? o:nTest1 // 0, should be 1
	? o:nTest2 // 2, OK

CLASS Parent
	EXPORT nTest1 AS INT
	EXPORT nTest2 AS INT
END CLASS

CLASS Child INHERIT Parent
	CONSTRUCTOR()
		SELF:nTest1 := 1
		SUPER()
		SELF:nTest2 := 2
END CLASS
```

**Comment by cpyrgas** [comment]
Robert this still fails here, but I'm not sure has this change made it to the latest action?

**Comment by RobertvanderHulst** [comment]
No this was not merged into the main branch yet. I have done that now.

**Comment by cpyrgas** [comment]
Thanks, confirmed fixed!
