### ISSUE TITLE
UDCs do not allow all possible orders of optional clauses

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1410]
https://www.xsharp.eu/forum/topic?p=28270#p28270

In VO, UDCs generally allow clauses to be supplied in any order, while in X# there are limitations. For example for the COUNT command, VO allows all variations:

```
(1) COUNT TO a FOR f WHILE wh NEXT 1
(2) COUNT TO a FOR f NEXT 2 WHILE wh 
(3) COUNT TO a WHILE FALSE FOR f NEXT 3 
(4) COUNT WHILE wh TO a FOR f NEXT 4 
(5) COUNT FOR f NEXT 5 WHILE wh TO a
```

while X# throws parser errors for (4) and (5)

Note that in VO the UDC is defined as

```
 COUNT  [TO <var>]  ;
    [FOR <fo>]      ;
    [WHILE <wh>]    ;
    [NEXT <nx>]     ;
    [RECORD <rec>]  ;
    [<rs:REST>]     ;
    [ALL]   ;
    ;
    => <var> := 0 ;;        ;
       DBEVAL( {|| <var>:=<var> + 1 }, <{fo}>, <{wh}>, <nx>, <rec>, <.rs.> )

```

while in X# it is defined as

```
#command COUNT TO <xvar>                                                ;
         [FOR <lfor>]                                                   ;
         [WHILE <lwhile>]                                               ;
         [NEXT <nnext>]                                                 ;
         [RECORD <rec>]                                                 ;
         [<rest:REST>]                                                  ;
         [<noopt: NOOPTIMIZE>]                                          ;
         [ALL]                                                          ;
                                                                        ;
      => <xvar> := 0                                                    ;
       ; DbEval(                                                        ;
               {|| <xvar> += 1},                                        ;
               <{lfor}>, <{lwhile}>, <nnext>, <rec>, <.rest.>, <.noopt.>;
               )

```

**Comment by cpyrgas** [comment]
Similarly for COPY STRUCTURE, VO allows both those:

```
(1)COPY STRUCTURE TO a FIELDS b,c 
(2)COPY STRUCTURE FIELDS b,c TO a
```

while X# reports a parser error on (2).

VO has the command defined as

```
 COPY [STRUCTURE] [TO </file/>] [FIELDS <flds,...>] ;
    => DBCOPYSTRUCT( <(file)>, { <(flds)> } )
```
while in X# it is defined as

```
#command COPY STRUCTURE TO <(file)> [__DBFIELDLIST__ <fields>]          ;
      => DbCopyStruct( <(file)>, <fields> )
```

**Comment by cpyrgas** [comment]
Personally I prefer the X# way, makes more sense. But as pointed out in https://www.xsharp.eu/forum/topic?p=28248#p28248, there might exist existing code (mostly in VFP or other dialects) that depends on the more loose definitions.

**Comment by RobertvanderHulst** [comment]
The errors are indeed caused by the fact that
- For the COUNT command the TO clause is optional in VO and mandatory in X#.
- For the COPY command the TO clause is optional in VO and mandatory in X#.
I am not sure if we should make the STRUCTURE keyword optional. If we make that mandatory there could be a conflict with the normal COPY command.

**Comment by cpyrgas** [comment]
I thought that, too, better let's keep STRUCTURE mandatory as it is now.

**Comment by cpyrgas** [comment]
Confirmed fixed
