### ISSUE TITLE
Problems with COMMIT command

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1411]
In VO, COMMIT results to DBCommit(), while in X# it results to DBCommitAll().

Also COMMIT ALL (which trnaslates to DBCommitAll() in VO) does not exist at all in X#.

VO definition:

```
COMMIT     => DBCommit()
COMMIT ALL => DBCommitAll()
```

X# definition:

`#command COMMIT                 => DbCommitAll()`

**Comment by cpyrgas** [comment]
Should be fixed now

**Comment by cpyrgas** [comment]
Robert, actually the help file indicates that the previous behavior (comitting all) is on purpose https://xsharp.eu/help/command_commit.html

Was that really intended or a mistake in the docs as well?

**Comment by RobertvanderHulst** [comment]
I checked other dialects.
XBase++ declares commit as
`#command  COMMIT             =>  dbCommitAll()`
Harbour declares commit as 
`#command COMMIT                  => dbCommitAll()`
Clipper declares commit as 
`#command COMMIT                 => dbCommitAll()`
VO declares commit as
```
 COMMIT     => DBCommit()
 COMMIT ALL => DBCommitAll()
```

The VO docs however state that COMMIT works on all occupied workareas, like you found.

Vulcan declares commit as 
```
#command COMMIT ;
   => DBCommit()

#command COMMIT ALL ;
   => DBCommitAll()
```

FoxPro does not have a COMMIT command

So it seams that VO and Vulcan are the only dialects that has a difference between the COMMIT and COMMIT ALL command. 

I think the best solution is:
- declare COMMIT like VO and Vulcan does in std.xh
- add an overload for COMMIT inside an #ifdef command for the XBase++ and Harbour dialects that maps COMMIT to DbCommitAll().
