### ISSUE TITLE
REINDEX command incompatibilities

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1412]
In VO, the REINDEX command is defined as 

```
 REINDEX    => ORDLISTREBUILD()

 REINDEX [EVAL <ev>] [EVERY <evr>]  ;
    => ORDCONDSET(,,,, <{ev}>, <evr>,,,,,,,)     ;; ;
       ORDLISTREBUILD()
```

In X#, only the single token version is defined and it calls DBReindex() instead of OrdListRebuild():

`#command REINDEX                => DbReindex()`

There's also an alternative version for use with IN/ALIAS, is that one used for FoxPro compatibility? (still using DBReindex()):

`#command REINDEX          <x:IN,ALIAS> <(a)>          => (<(a)>) -> (DbReindex())`

**Comment by RobertvanderHulst** [comment]
The DbReindex() function calls OrdListRebuild(), so that is not a problem. The missing EVAL .. EVERY clause is.

**Comment by cpyrgas** [comment]
Confirmed fixed
