### ISSUE TITLE
"Go to definition" not working for local function in 2.19 (and maybe also older versions)

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1415]
In the following code "Go to definition" is not working for AppendStyle

```
public class Test
   public method TestMethod() as void
      local function AppendStyle(firstStyle as logic, sb as StringBuilder) as logic
            if firstStyle
               sb:Append(' '):Append("abc"):Append('="')
            else
               sb:Append(';')
            endif
            return false
      end function

      AppendStyle(true, null)
end class
```

Also there are no hints displayed when the mouse is over "AppendStyle". 
If you input AppendStyle also no hint is displayed after the "("
[XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/13963563/XSharpTests.zip)

**Comment by RobertvanderHulst** [comment]
At this moment, Goto definition operates at the entity level. Local functions are not really entities. They are compiled into a kind of lambda expressions. They are also not included in the Members Combobox in the editor.
I will see what I can do to make this work.

**Comment by RobertvanderHulst** [comment]
The local functions/procedures WERE in the combobox. The only problem was that they had the wrong classname (the class in which they are defined) in the database. They are now written in the (GlobalType) class.

**Comment by cpyrgas** [comment]
Confirmed fixed
