### ISSUE TITLE
ErrorDialog when using Return key

### ISSUE THREAD

**Issue by baramuse** [X-Sharp/XSharpPublic#1417]
**Describe the bug**
From time to time, I have a strange error dialog when editing .prg source file.
It's just an error dialog with an ok button and message being "key" everytime I use the `return` key.
I can type code but just not use a return !
<img width="170" alt="image" src="https://github.com/X-Sharp/XSharpPublic/assets/1180901/e0ec06e5-287e-43fa-bb8d-e6dda570d858">

On XS 2.19.0.1
Windows11-arm
VS 2022 17.8.5

I never had that happenning before 2.19

**Comment by RobertvanderHulst** [comment]
Basile,
I have no idea where this messagebox is coming from. It is not from our extension as far as I can tell. 
Which extensions are loaded inside your VS?

**Comment by baramuse** [comment]
Well a pretty fresh install so not third part extensions.
But it never happened again I can I close that one as it really does not seems to be XSharp related !
