### ISSUE TITLE
Intellisense does not pickup extensions methods

### ISSUE THREAD

**Issue by baramuse** [X-Sharp/XSharpPublic#1421]
If I add an extention method to an existing type, intellisense does not pick it up for code completion.
System extensions are pickedup though :

```
PUBLIC STATIC CLASS ArrayExtensions
	PUBLIC STATIC METHOD AAdd<T>(SELF source AS ARRAY OF T , item AS T) AS VOID
		AAdd<T>(source, item)
	RETURN
	END CLASS
```

<img width="658" alt="image" src="https://github.com/X-Sharp/XSharpPublic/assets/1180901/f6379f63-fd96-4c0f-a200-997c45885f4f">

**Comment by cpyrgas** [comment]
Confirmed fixed
