### ISSUE TITLE
which-rdd-class-should-be-used-for-dbf-dbz-dbv

### ISSUE THREAD

**Issue by Saranjit-Kaur** [X-Sharp/XSharpPublic#1423]
which rdd class should be used for dbf,dbz,dbv

**Comment by Saranjit-Kaur** [comment]
Hi Robert,
Below is the link 
https://www.xsharp.eu/forum/topic?p=28510#p28510

Could you please update on the release of DBFBlob and DBFMemo support?

Thanks

**Comment by cpyrgas** [comment]
Done in https://github.com/X-Sharp/XSharpPublic/issues/604 and https://github.com/X-Sharp/XSharpPublic/issues/605. Not fully implemented yet though.
