### ISSUE TITLE
Function Utf82Ansi is missing from System Lib

### ISSUE THREAD

**Issue by benjamin-lochmann-riedmann** [X-Sharp/XSharpPublic#1424]
Function Utf82Ansi is missing from System Lib.
Tested with XSharp Cahors 2.19.0.2

**Comment by RobertvanderHulst** [comment]
Benjamin,
In what context are you using this?

**Comment by benjamin-lochmann-riedmann** [comment]
Hi Robert,
I am using this function in a VO application, which I have to migrate

**Comment by cpyrgas** [comment]
Benjamin, Robert is asking what is the context in the VO code where you are using this function. Where and how are you reading the input string, where and how are you using the output string etc. In .Net, there are no ansi strings, they are always unicode, so possibly you don't even need to call Utf82Ansi() at all, but it depends on the context where it is used.

**Comment by benjamin-lochmann-riedmann** [comment]
Got it, I will check this

**Comment by cpyrgas** [comment]
OK, thanks for your feedback Benjamin!
