### ISSUE TITLE
XPorter: Possibility to put a line in the beginning of a prg file

### ISSUE THREAD

**Issue by benjamin-lochmann-riedmann** [X-Sharp/XSharpPublic#1425]
We need the possibility to add lines at the beginning of a .prg file while porting code from VO to XSharp.  
  
Example: We need a "using" statement in XSharp, but not in VO.  
It is not possible to do this with  {VOXP:UNC} because in VO we cannot insert a line before a class declaration.   
The commented line would be turned into a textblock:  

```
TEXTBLOCK MyTest_TestClass
//using rdm.GoogleAdsLib {VOXP:UNC}
 
class MyTestClass
declare Access MyProperty

```

**Comment by wriedmann** [comment]
maybe a textblock with a special name could be solution.
For example: when the XPorter/VO finds a textblock with the name "xporter_topoffile" or similar puts its content in the top of the resulting prg file. That could also permit the declaration of special code like using, define, or even entire classes

**Comment by cpyrgas** [comment]
Wolfgang, I like the idea of a special texblock, let me give it a try and will get back to you.

**Comment by cpyrgas** [comment]
Guys, can you please check this new VOXporter version to see if it works as you expected? You can now use TEXTBLOCKs with names VXP-TOP and {VOXP:TOP} (to be consistent with the already existing tags) that you can use for top statements:

```
TEXTBLOCK {VOXP:TOP}
USING System
USING System.Collections.Generic

TEXTBLOCK VXP-TOP
USING System
USING System.Collections
```

I have also done some major refactoring, hope I did not break something else...

[VOXporter_top_statements.zip](https://github.com/X-Sharp/XSharpPublic/files/14122886/VOXporter_top_statements.zip)

**Comment by benjamin-lochmann-riedmann** [comment]
Works perfect, thank you!
