### ISSUE TITLE
String functions with PSZ argument throw runtime error

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1429]
A lot of runtime functions throw a runtime error (Argument type error) when passed a PSZ argument. In VO they give the expected results.

```
FUNCTION Start() AS VOID
	LOCAL p AS PSZ
	p := String2Psz("testing")
	? SubStr(p,2,3)
	? Left(p,4)
	? StrTran(p,"e","E")
RETURN
```

**Comment by cpyrgas** [comment]
There is one more problem now, IsString(psz) in VO returns TRUE, but now (after build 2.17) in X# it returns FALSE:

```
FUNCTION Start() AS VOID
	LOCAL p AS PSZ
	LOCAL u AS USUAL
	p := String2Psz("testing")
	u := p
	? IsString(p) // TRUE in VO, FALSE in X#
	? IsString(u) // TRUE in VO, FALSE in X#
```

So I think it's probably better to revert the above change. Robert, what do you think?

**Comment by cpyrgas** [comment]
usual:IsString is also used in the various USUAL operators, so now also this gives different results to VO:

```
FUNCTION Start() AS VOID
LOCAL p1 AS PSZ
LOCAL p2 AS PSZ
LOCAL u1,u2 AS USUAL
p1 := String2Psz("testing")
p2 := String2Psz("test")
u1 := p1
u2 := p2
SetExact(FALSE)
? p1 != p2 // FALSE in both VO and X#
? u1 != u2 // FALSE in VO, TRUE in X#

```

**Comment by RobertvanderHulst** [comment]
Chris, ok, revert the change.
But if we change the constructor with PSZ parameter to set the type to STRING, then we also need to change the constructor with the OBJECT parameter where the object contains a PSZ to do the same.
And then this means that we are no longer setting the type to PSZ, so we can also remove the checks for the PSZ type from the various operators ...

**Comment by cpyrgas** [comment]
Robert,
OK, I am only afraid of breaking something else you fixed, because there were a lot of changes in that commit. Do you remember the reason why you made this change in the usual class?

**Comment by RobertvanderHulst** [comment]
Chris,
I'll look at this
