### ISSUE TITLE
VS : Project setting "enable named arguments" checkbox does not reflect xsproj

### ISSUE THREAD

**Issue by baramuse** [X-Sharp/XSharpPublic#1431]
If you check "enable named arguments" in the project settings in VS, the setting gets written in the .xsproj as `<NamedArgs>True</NamedArgs>`
Now if you close the project settings and open again, the checkbox is not checked, although the compiler switch is still on.
Also VS tells you your project settings are not saved yet (the * on the tab), and saving it does not change anything

**Comment by RobertvanderHulst** [comment]
I'll look into this.

Robert
