### ISSUE TITLE
Problem with OrdKeyVal() and ADS/ADT

### ISSUE THREAD

**Issue by ecosSystem** [X-Sharp/XSharpPublic#1434]
Hi Robert,

there seems to be a problem with the OrdKeyVal()-function and ADT-Tables (ADI-Index-files)

with ADSCDX (correct):
oTable:orderinfo(DBOI_KEYVAL,,1)	-> 100001
ordkeyval(1)					-> 100001
oTable:orderinfo(DBOI_KEYVAL,,2)	-> FUNK
ordkeyval(2)					-> FUNK

with ADSADT:
oTable:orderinfo(DBOI_KEYVAL,,1)	-> 100001
ordkeyval(1)					-> **wssssw&&&&**
oTable:orderinfo(DBOI_KEYVAL,,2)	-> FUNK
ordkeyval(2)					-> **©çÂ¼&&&&&&&&&&&**

Karl

**Comment by RobertvanderHulst** [comment]
Karl,
There is a difference in how DbOrderInfo(DBOI_KEYVAL) works and how OrdKeyVal works.
DbOrderinfo(DBOI_KEYVAL) calls AdsGetIndexExpr ()behind the scenes and macro compiles and evaluates that expression.
OrdKeyVal() calls AdsExtractKey() behind the scenes. It looks like this function returns the key values encoded.
I will change the RDD to also get the expression and then macro compile the expression to return the result.

**Comment by cpyrgas** [comment]
Will let Karl confirm this, as I don't have adt tables to test with

**Comment by ecosSystem** [comment]
Hi Chris,
attached a small solution you can test with...

[ADTTest.zip](https://github.com/X-Sharp/XSharpPublic/files/15126270/ADTTest.zip)

**Comment by cpyrgas** [comment]
Thanks Karl, I get "BAKER", "BAKER" for the ADS test, so it's problem confirmed fixed.
