### ISSUE TITLE
Harbour dialect FIELD statement not supported

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1436]
Found in a Harbour app:

FIELD fld1,fld2

FUNCTION Start() AS VOID
...
? fld1
LOCAL u
u := fld1
fld2 := fld1

**Comment by RobertvanderHulst** [comment]
Ok, so we need a file wide FIELD statement.
Does Harbour also support the `IN <area>` clause like in:
`FIELD LastName IN Customer`

**Comment by cpyrgas** [comment]
Yes, apparently it does:

https://harbour.github.io/doc/harbour.html#field-cmd

FIELD
Declares a list of database field names.
Syntax

FIELD <xField> [, <xFieldn...> [IN <cDatabase>]

Arguments
xField A valid field name
xFieldn Additional field name
cDatabase An valid alias name

Description
This command declares the names of fields xField (and xFieldn and following) with an optional alias identifier as cDatabase for each. This command allow Harbour to resolve any reference to a field specified in the field list by viewing it as a field when it is not referenced by an alias. If a field is not listed in this list and it is not explicitly tagged with an alias identifier, it may be viewed as a memory variable, which may cause run-time errors. This command has no effect on memory variables or on field reference buried within a macro expression.

**Comment by cpyrgas** [comment]
Robert, can you please force a compiler build so I can test this?

**Comment by cpyrgas** [comment]
Thanks, confirmed fixed!
