### ISSUE TITLE
Use of reserved word in x#/core

### ISSUE THREAD

**Issue by FrankMaraite** [X-Sharp/XSharpPublic#1443]
**Describe the bug**
Go these error messages
...(171,146): error XS0839: Argument missing
...(171,190): error XS0839: Argument missing
...(171,192): error XS0839: Argument missing
...(171,194): error XS0839: Argument missing
...(171,196): error XS0839: Argument missing

**To Reproduce**
		LOCAL Replace AS INT
		Replace:GetType()

**Expected behavior**
Standard behavior fpr int's or whatever type the variable is.

**Desktop (please complete the following information):**
 - OS: Win11
 - X# Compiler version 2.19.0.2 (release)

**Additional context**
Nothing more to reproduce needed.

**Comment by RobertvanderHulst** [comment]
I think the REPLACE at the start of the line is (incorrectly) matched with the REPLACE UDC.
If you do not need UDC's then you could enable the compiler option /nostddefs

**Comment by FrankMaraite** [comment]
A simple rename of the variable did the job.
BTW: The code worked since vulcan times until x# 2.17. I skipped 2.18. Maybe this helps

**Comment by cpyrgas** [comment]
Confirmed fixed
