### ISSUE TITLE
RP3 Invalid operation exception when printing from the preview window

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1447]
https://www.xsharp.eu/forum/topic?p=29179#p29179

We use Report pro 3 for X# (3.6.04).
I run a preview of the report.
The Preview Window is shown perfectly. The report is loaded. If the report consists of more than one pages when i hit the Print button and selecting where to print etc. the X# throws an exception

`'A callback was made on a garbage collected delegate of type 'Classmate.Gui!Classmate._AbortProc32Delegate::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.' `

**Comment by RobertvanderHulst** [comment]
Fixed
