### ISSUE TITLE
Lexer should recognize line continuation characters inside a string

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1453]
Foxpro recognizes the line continuation character in the following example:

```
cSource = "select ccaption, ncolumn, cfieldname, ckeyfield, csortorder, cfieldlen, cinputmask, lcmdadd, ;
	ctable, cfilter from lookuptable where ccode = llookup into cursor curordby order by ncolumn"
```
As you can see, the line continuation character is the last character on the first line, and the string continues on the next line.
FoxPro recognizes this and the white space before "ctable" becomes part of the string
Note: after the semicolon the && is recognized as an end of line comment

**Comment by cpyrgas** [comment]
Confirmed
