### ISSUE TITLE
Problem using symbol literals #NULL_STRING, #NULL_DATE etc

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1456]
https://www.xsharp.eu/forum/topic?p=29519#p29519

X# compiler reports an error when trying to use symbol literals #NULL_STRING, #NULL_DATE etc
VO allows them

```
// error XS9002: Parser: unexpected input '#'
FUNCTION Start() AS VOID
	LOCAL s AS SYMBOL
	s := #ABC // OK
	s := #NULL // OK
	s := #NULL_DATE // error XS9002
	s := #NULL_STRING // error XS9002
	s := #NULL_ARRAY // error XS9002
	? #NULL_DATE
```

**Comment by RobertvanderHulst** [comment]
Chris,
The compiler does not recognize these as symbols, to allow code like this:
```
LOCAL d as Date
d := Today()
? d #NULL_DATE
```

where `#` is equal to the `<>` or `!=1` operator.

**Comment by cpyrgas** [comment]
Confirmed fixed
