### ISSUE TITLE
Incorrect behavior when accessing hidden fields of another object

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1457]
**Describe the bug**
Unfortunately the [bug](https://github.com/X-Sharp/XSharpPublic/issues/1335) is not fixed

**Additional context**
X# Compiler version 2.19.0.2 (release)
-dialect:xBase++ -lb -enforceself -memvar -xpp1 -vo1 -vo3 -vo4 -vo5 -vo9 -vo10 -vo12 -vo13 -vo14 -vo15 -vo16 -vo17

**Comment by cpyrgas** [comment]
Confirmed fixed
