### ISSUE TITLE
VS parameters tip for constructors is offset by one param

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#146]
Type 

DataWindow{

the parameter tip shows, but it is offset be one param, second param is highlited, see picture.

![InstantiationTip](https://user-images.githubusercontent.com/14542129/63557617-33e2c300-c552-11e9-9101-21e31877548f.png)

Also, when typing

System.Exception{"message",

then none of the parameters get highlited, even after typing more of them.

**Comment by cpyrgas** [comment]
It's much better now, but there's still something strange about it. Type the following:

System.String{'a',

now the tooltip opens and an overload with 2 params is shown, with the 2nd param highlighted, correct.

But now press the up/down arrow keys, to view other overloads, now again the first param gets highlighted, although we are on the second. Delete the comma and re-type it, from now on it works correctly.

**Comment by fforay** [comment]
Thanks for the info, I will try to make it smarter.
I'm not sure of the type of info I will be able to retrieve in order to be at the right place, but btw we have the same behaviour in C#

**Comment by cpyrgas** [comment]
Fabrice, no in c# it works correctly, I just checked. But anyway, maybe just leave it as it is, it's a small thing really.
