### ISSUE TITLE
DBFMEMO: Cannot use the hidden RDD parameter in DBCreate()/DBUseArea() to specify the memo RDD, while using DBFCDX/DBFNTX for the index

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1463]
DbCreate() ignores the hidden RDD parameter and creates the memo file as dbt/fpt.
DbUseArea() does use the hidden RDD parameter, but does not open the dbf with the base RDD (ntx/cdx) that is specified.

```
FUNCTION Start() AS VOID
	LOCAL cFileName AS STRING
	LOCAL cBaseRdd AS STRING
	LOCAL cIndex AS STRING
	LOCAL lNtx AS LOGIC
	
	cFileName := "c:\test\rdd\dbmemo"
	lNtx := TRUE
	
	IF lNtx
		cBaseRdd := "DBFNTX"
		cIndex := cFileName + ".ntx"
	ELSE
		cBaseRdd := "DBFCDX"
		cIndex := cFileName + ".cdx"
	ENDIF
	
	FErase(cIndex)
	
	? DbCreate(cFileName, {{"CFIELD","C",10,0},{"NFIELD","N",8,2},{"MFIELD","M",10,0}},cBaseRdd,,,,,{"DBFMEMO"})

	? DbUseArea(TRUE,cBaseRdd,cFileName,,,,,,{"DBFMEMO"})
	DbAppend()
	FieldPut(1,"test1")
	FieldPut(2,1)
	FieldPut(3,"some text")
	DbAppend()
	FieldPut(1,"test3")
	FieldPut(2,3)
	FieldPut(3,"some text3")
	DbAppend()
	FieldPut(1,"test2")
	FieldPut(2,2)
	FieldPut(3,"some text2")
	DbGoTop()
	? DbCreateIndex(cFileName,"NFIELD")
	DbGoBottom()
	? RecNo(), FieldGet(1), FieldGet(2), FieldGet(3)
	DbCloseArea()
	
	? File(cIndex)

```

**Comment by cpyrgas** [comment]
Now DbCreate() works well, but DBUseArea() ignores the setting for the base RDD. Set "lNtx := FALSE" in the sample code, the .dbv file is correctly generated, but for the index, an .ntx file is generated, instead of a .cdx.

**Comment by RobertvanderHulst** [comment]
Chris, 
Using DBFCDX as Base RDD for DBFMEMO will not work in X#.
The DBFMEMO driver inherits from DBFNTX and DBF
In VO there is no real object orientation and the drivers do not inherit from each other. 
The tables with function pointers are merged at runtime.
In theory, I could do that too in X# but that would require a major rewrite of the RDD system.
By the way, the DBFCDX driver uses the same memo driver as DBFMEMO. 
So the FPT files have the same contents as the DBV files but just a different extension.

**Comment by cpyrgas** [comment]
Robert, that's fine about the memo file, but this means that it is not possible to use cdx indexes with dbv files and I suspect some of the people who use dbvs are using it together with cdx as well. Let's leave it open for a possible future solution, if there's enough request for this maybe you can come up with a hack or something to do this.

**Comment by RobertvanderHulst** [comment]
What I will do is to create a new RDD DBFMEMOCDX that inherits from DBFCDX. And then translate the combination of base RDD DBFCDX with DBFMEMO into this special RDD. The only problem would be that the RDDName() function would return DBFMEMOCDX for this area.

**Comment by cpyrgas** [comment]
I think that's a good enough solution!

**Comment by cpyrgas** [comment]
Confirmed fixed
