### ISSUE TITLE
The Use command triggers an error when the path to the dbf file contains spaces.

### ISSUE THREAD

**Issue by vfp9** [X-Sharp/XSharpPublic#1468]
**Describe the bug**
An error is triggered when using the Use command to open a dbf with a path that has spaces in it.
![bug](https://github.com/X-Sharp/XSharpPublic/assets/38008973/8b758f70-fcbd-447a-839b-3c40ec96b37f)
The Chinese description in the picture, translated into English should be: Formats in the path are not supported

**To Reproduce**
Please try:    
```foxpro
Use [E:\my test\test.dbf]
```
**Desktop (please complete the following information):**
 - OS: WIN10 22H2(19045.4291)
 - IDE: VS 2022 Community
 - Version : Ver 2.19.0.2 (Visual FoxPro dialect)

**Additional context**
The following commands are valid in VFP：
```foxpro
Use [E:\my test\test.dbf]
```

**Comment by RobertvanderHulst** [comment]
The error indicates that the USE command works, however the RDD fails to open the file.

**Comment by cpyrgas** [comment]
Xinje, please try putting the file in a similar folder in C:, does the error still occur? Also please check its properties, maybe it's blocked by the OS, as if it was downloaded from the web etc? Can you post the file(s) so we can have a look?

**Comment by vfp9** [comment]
Attached is the dbf file I used for testing. I simply changed the file name while testing.
[PY.zip](https://github.com/X-Sharp/XSharpPublic/files/15339214/PY.zip)

**Comment by cpyrgas** [comment]
Thanks, I see the problem, it's because of the use of brackets for the filename, the preprocessor has a problem with it. The USE command gets translated to

`DbUseAreaFox( , "[C:\xSharp\Users\Xinje\my test\py.dbf]", , iif(.F. .or. .F., !.F., NIL), .F.,......`

and fails of course. 

That's a bug, but for now please replace the [....] with "..." and it should work.

**Comment by cpyrgas** [comment]
Confirmed fixed
