### ISSUE TITLE
Linq Min/Max function of float wrong

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#1482]
The implementation of the Linq min/max function in [https://github.com/X-Sharp/XSharpPublic/blame/main/src/Runtime/XSharp.RT/Functions/ExtensionMethods.prg](https://github.com/X-Sharp/XSharpPublic/blame/main/src/Runtime/XSharp.RT/Functions/ExtensionMethods.prg) is wrong. It calculates always a sum

Hansjörg

**Comment by RobertvanderHulst** [comment]
Hansjörg,
Good catch. That's what happens if you copy-paste code, AND do not write unit tests for it.
I'll fix the issue and will write the unit tests.

**Comment by RobertvanderHulst** [comment]
I see that only the extension methods that take a selector are incorrect. We indeed did not have unit tests for these.

**Comment by cpyrgas** [comment]
Confirmed fixed
