### ISSUE TITLE
Problem with Extended Expression Match Marker (Xbase++)

### ISSUE THREAD

**Issue by DenGhostYY** [X-Sharp/XSharpPublic#1487]
**Describe the bug**
Unfortunately, the [problem](https://github.com/X-Sharp/XSharpPublic/issues/1073) with the extended expression match marker isn't resolved.

**To Reproduce**
```
#translate PN(<file>, <(field)>) => GF(<file>, <(field)>)

local f := PN(handle,F_NAME ) // one space before right paranthesis
```

**Expected behavior (XBase++ ppo)**
```
local f := GF(handle, "F_NAME")
```
**Actual behavior (X# ppo)**
```
local f :=  GF(handle, "F_NAME ") // space inside a string literal
```

**Additional context**
X# Compiler version 2.20.0.3 (public)
-dialect:xBase++
-codepage:866
-lb -enforceself -memvar -xpp1 -vo1 -vo3 -vo4 -vo5 -vo9 -vo10 -vo12 -vo13 -vo14 -vo15 -vo16 -vo17
-reference:XSharp.Core.dll
-reference:XSharp.RT.dll
-reference:XSharp.XPP.dll

**Comment by RobertvanderHulst** [comment]
Did this work before?

**Comment by DenGhostYY** [comment]
Yes, it worked before

**Comment by cpyrgas** [comment]
Confirmed fixed
