### ISSUE TITLE
Conversion INT to LOGIC

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#149]
Robert, in https://www.xsharp.info/forum/private-product/1414-type-conversion#10361 I think you implied that conversion from INT to LOGIC should be supported by the compiler? See the following, it doesn't, no matter the compiler options:

error XS0030: Cannot convert type 'int' to 'logic'

FUNCTION Start() AS VOID
	LOCAL n AS INT
	n := 1
	IF (LOGIC)n // error XS0030
		? "true"
	ENDIF
	n := 0
	IF (LOGIC)n // error XS0030
		? "should not come here"
	ENDIF
RETURN

**Comment by RobertvanderHulst** [comment]
For compatibility with VO the following syntax is supported:

```
LOCAL n AS INT
n := 1
IF LOGIC(_CAST,n) // error XS0030
? "true"
ENDIF

```

The new DotNet syntax for casting (LOGIC) is not supported with INT -> LOGIC casts

Robert

**Comment by RobertvanderHulst** [comment]
I will enable this for all cast operations when /vo7 is selected. After all this is an 'implicit conversion'.

**Comment by RobertvanderHulst** [comment]
And LOGIC(_CAST will work regardless of /vo7
