### ISSUE TITLE
Trouble with OldStyleAssignment with FoxPro dialect project

### ISSUE THREAD

**Issue by fforay** [X-Sharp/XSharpPublic#1495]
Create a "Visual FoxPro" project.
Open a source file
Add line with an Old Style Assignment, like x = 10
Build, everything is ok

Now, view the Project properties.
In the Language tab, the OldStyleAssignment  is un-checked (but it should be true, as it should be Checked per default for VFP dialect)
So, when closing the Properties, the unChecked state is saved, and Build will generate an error

**Comment by fforay** [comment]
In fact, after several tries, it seems that the OldStyleAssignment setting is always cleared when opening the settings

**Comment by cpyrgas** [comment]
Confirmed fixed
