### ISSUE TITLE
Documentation Errors

### ISSUE THREAD

**Issue by vfp9** [X-Sharp/XSharpPublic#1506]
topic: -i
original: Click the Build tab.
should: Click the Language tab.

**Comment by vfp9** [comment]
#1504 Missing -highentropyva
original: Add the option in the "User-Defined Command Line options" property
should: Add the option in the "Extra Command Line options" property。

**Comment by RobertvanderHulst** [comment]
Fixed.
I have also added an (embedded) topic __buildExtra that can be used for each of the options that are specified with the "Extra Command Line options" property. This reduces the size of the source and makes for more consistent texts.
