### ISSUE TITLE
Documentation Errors

### ISSUE THREAD

**Issue by vfp9** [X-Sharp/XSharpPublic#1514]
topic: -nostdlib
original: Add the option in the "User-Defined Command Line options" property
should: Add the option in the "Extra Command Line Options" property

topic: -ns
original: Click the General tab. 
should: Click the Application tab.

original: In the Application section, modify the Default Namespace property. 
should: Modify the Default Namespace property. 

topic: -out
original: Assembly name
should:  Application name

topic: -platform
original: Click the General property page.
should: Click the Application page.

topic: -ppo
original: In the Preprocessor section, modify the "Generate preprocessor output"property.
should: In the General section, modify the "Generate preprocessor output"property.

topic: -target
original: For more information about setting this compiler option programmatically, see OutputType.Enter topic text here.
should: For more information about setting this compiler option programmatically, see OutputType.

I've modified the description to be correct in the Simplified Chinese version of the document.

**Comment by RobertvanderHulst** [comment]
The -ns option is not the same as the Namespace field on the Application Tab.
The -ns option is the "Prefix classes with default namespace" option on the Language page. 
When you enable that option then the build system will combine that flag with the Default namespace on the application tab.
