### ISSUE TITLE
Add FieldGetBytes() and FieldPutBytes() methods to DBServer class

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#152]
Please add the methods FieldGetBytes() and FieldPutBytes() to the DBServer class.
Thank you very much!
Wolfgang

**Comment by RobertvanderHulst** [comment]
Added in next build. Please note that FieldGetBytes() and FieldPutBytes() ignore the 'optimistic locking' mechanism. So the value is NOT cached and to write the field the server must be locked or opened exclusively.

**Comment by wriedmann** [comment]
great, thank you very much!
