### ISSUE TITLE
Macrocompiler in some cases cannot resolve library function

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#153]
Following (see also VS solution attachment) results to XSharp.MacroCompiler.CompilationError: '(1,5): error XM0205: No suitable overload of ClassLibrary1.Functions.StrTran()'

------------EXE----------------
```
FUNCTION Start() AS VOID STRICT
// All 4 calls below are resolved by regular compiler to the functions declared in the user library and which should always get priority indeed

// But when any of the above calls is actually executed, then the error below does not happen!
// Maybe the problem has to do with the functions already being JITted or not?
IF FALSE
? StrTran("a","b")
? StrTran("a","b","c")
? StrTran("a","b",1)
? StrTran("a","b",1,2)
ENDIF
?
LOCAL c AS STRING
c := "{|| StrTran('a','b') }"
? Eval(&(c)) // ok
c := "{|| StrTran('a','b' ,1) }"
? Eval(&(c)) // ok
c := "{|| StrTran('a','b' ,1 , 2) }"
? Eval(&(c)) // ok

// XSharp.MacroCompiler.CompilationError: '(1,5): error XM0205: No suitable overload of ClassLibrary1.Functions.StrTran()'
c := "{|| StrTran('a','b' ,'c') }"
? Eval(&(c)) // error here

System.Console.ReadLine()
```
--------------------------------

------------LIBRARY----------------
```
FUNCTION StrTran(c1 AS STRING, c2 AS STRING) AS STRING
RETURN "1"
FUNCTION StrTran(c1 AS STRING, c2 AS STRING, c3 AS STRING) AS STRING
RETURN "2"
FUNCTION StrTran(c1 AS STRING, c2 AS STRING, n AS DWORD) AS STRING
RETURN "3"
FUNCTION StrTran(c1 AS STRING, c2 AS STRING, n AS DWORD, n2 AS DWORD) AS STRING
RETURN "4"
```
--------------------------------

[ConsoleApplication19.zip](https://github.com/X-Sharp/XSharpPublic/files/3551739/ConsoleApplication19.zip)

**Comment by nvkokkalis** [comment]
There is some code added by Robert in the method call binding (first appearing in commit 9e9055f6ce) that is supposed to give preference to user-declared functions. This code causes this issue, apparently due to incorrect filtering (removing it fixes the problem). I suppose though that it was added to fix some other issue.

More importantly, this code apparently causes the performance of the macro compiler to drop by half in macros with method calls (I had observed the performance drop and was wondering about it). So, I will remove it and work on an alternative.

**Comment by nvkokkalis** [comment]
I pushed a fix on Robert's code for this issue (so this bug can be closed now), but the performance problem is even worse now (it is most evident with methods that have several overloads, like Console.WriteLine). I will work on an alternative implementation.

**Comment by RobertvanderHulst** [comment]
Maybe you should have a look at the extension method IsInXSharpRuntime(). I am now using the following construct:
```
string asmName = s.Method.DeclaringType.Assembly.GetName().Name.ToLower();
            switch (asmName)
            {
                case "xsharp.core":
                case "xsharp.rdd":
                case "xsharp.rt":
                case "xsharp.vo":
                case "xsharp.vfp":
                case "xsharp.xpp":
                    return true;
            }
            return false;
```
It is probably better to cache the Assembly in a dictionary along with its logical value, so we don't have to repeatedly get the assembly name and do a switch.

**Comment by nvkokkalis** [comment]
I will implement the filtering offline (when constructing the lookup dictionaries), so it will be redundant at that point.
