### ISSUE TITLE
[VFP] SCATTER/GATHER MEMVAR MEMO not recognized

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1534]
MEMO clause is not supported in all SCATTER/GATHER variations
 
```
// error XS9002: Parser: unexpected input 'MEMVAR'
GATHER MEMVAR MEMO
SCATTER MEMVAR MEMO

// error XS9002: Parser: unexpected input '__FOXLIST__'
LOCAL a := ArrayCreate(10) AS ARRAY
SCATTER FIELDS FLD,FLD2 TO a MEMO
SCATTER FIELDS LIKE abc* TO a MEMO
```

**Comment by cpyrgas** [comment]
Should be fixed now. Note that SCATTER/GATHER still does not include "G" fields, as in https://github.com/X-Sharp/XSharpPublic/issues/1530

**Comment by RobertvanderHulst** [comment]
Isn't this the same as  #1510 ?

**Comment by cpyrgas** [comment]
Ah sorry, not sure how I missed that. It's probably my fault, I did my changes to the header file in the compiler branch, but you had done yours already in the runtime branch, so I did not notice them.

**Comment by cpyrgas** [comment]
Confirmed fixed
