### ISSUE TITLE
[VFP] Problems with the INDEX ON command

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1535]
With the following code:

1. When using Str(FLD1) for the index expression, a macrocompiler error is thrown "Method is overloaded, Cannot determine the right overload to call." Problem is that Str() is defined both in XSharp.RT.dll and XSharp.VFP.dll and the macrocompiler chokes on that.

2. When using the expression Str(FLD1,10,0), a different runtime error is thrown by the macro compiler: System.Security.VerificationException:Operation could destabilize the runtime. Not sure what might be causing that

```
FUNCTION Start( ) AS VOID
	LOCAL cDbf AS STRING
	cDbf := "test"
	FErase(cDbf+".cdx")
	DbCreate(cDbf,{{"FLD1","N",10,0},{"FLD2","C",10,0}},"DBFCDX")
	DbUseArea(TRUE,"DBFCDX",cDbf)
	DbAppend();	FieldPut(1,123);FieldPut(2,"Z")
	DbAppend();	FieldPut(1,456);FieldPut(2,"A")
	DbAppend();	FieldPut(1,1);FieldPut(2,"A")

	INDEX ON Str(FLD1) TAG ABC
	INDEX ON Str(FLD1,10,0) TAG ABC

```

**Comment by RobertvanderHulst** [comment]
`Str(FLD1,10,0) ` failes because FLD1 is a String and not a Number

**Comment by cpyrgas** [comment]
Ah, sorry! But it's the same also with a number, I will update the code

**Comment by cpyrgas** [comment]
It's simpler to reproduce, the following throws the same exception when run in VFP dialect:

// FoxPro dialect
FUNCTION Start()
? &("Str(123,7,2)") // System.Security.VerificationException:Operation could destabilize the runtime.

When run in VO dialect, it works as expected

**Comment by cpyrgas** [comment]
Also problem #1 happens only when /fox1+ is enabled. I'm adding a test in the suite now

**Comment by RobertvanderHulst** [comment]
Thanks. This works as expected.

**Comment by cpyrgas** [comment]
Will need to test this with the new macro compiler

**Comment by cpyrgas** [comment]
Confirmed fixed

**Comment by cpyrgas** [comment]
Hmm, when reading the resulting dbf from dbAdmin, teh index appears corrupted (only one record shown instead of 3), ut when opening the dbf from VO itself, it looks good. Strange, but will leave it for now.
