### ISSUE TITLE
VS-Integration - Indentation

### ISSUE THREAD

**Issue by ecosSystem** [X-Sharp/XSharpPublic#1541]
Settings:
[ ] Indent entities inside namespace
[ ] Indent multiline members inside types
[ ] Indent single line members inside types
[ ] Indent statements inside entities 
[ ] Indent case label
[x] Indent statements inside case block
[x] Indent continuing lines
[ ] Indent preprocessor lines

### First issue:

```
local n as dword
for n := 1 upto 10
	DoSomething()
next
```

works fine. If you use old style coding, "next n" stays indented:

```
local n as dword
for n := 1 upto 10
	DoSomething()
	next n

```

### Second issue:

a begin sequence .... end sequence inside a while loop confuses formatting totally:

```
CLASS test

CONSTRUCTOR() AS VOID
LOCAL n	AS DWORD

WHILE(n<100)
	n += 1
	BEGIN SEQUENCE
		IF n = 10
			BREAK
		ENDIF
	END SEQUENCE
ENDDO

RETURN

	METHOD foo() AS VOID
	LOCAL x AS STRING

	RETURN

END CLASS

```
Typing RETURN after Method foo() indents the current line and all following lines afterwards.
By commenting out BEGIN SEQUENCE and END SEQUENCE everything works fine.

Formatting the code via (sorry, I have a german VS):
[Bearbeiten]
[Erweitert]
[Auswahl formatieren]
always works fine even with BEGIN SEQUENCE ... END SEQUENCE

**Comment by RobertvanderHulst** [comment]
The problem is caused by the fact  that the preprocessor translates `NEXT x` to `NEXT `
As a result, the NEXT word in the buffer has the type 'UDC_KEYWORD' and that is not defined as a valid match for the FOR keyword.
I will change the indenting code to ignore the 'rubbish' after the first keyword

**Comment by ecosSystem** [comment]
Robert,
did you also see the second issue ?

**Comment by ecosSystem** [comment]
One more,
the if()-function also confuses formatting. iif() works...

**Comment by RobertvanderHulst** [comment]
> One more, the if()-function also confuses formatting. iif() works...

Do you have the IF() function at the start of a line?

**Comment by ecosSystem** [comment]
yes e. g.
`AAdd(aDir,;
					{fileInfo:Name,;
					fileInfo:Size,;
					Left(fileInfo:CreationTime:Date:Tostring(),10),;
					StrZero(fileInfo:CreationTime:Hour,2,0)+":"+;
					StrZero(fileInfo:CreationTime:Minute,2,0)+":"+;
					StrZero(fileInfo:CreationTime:Second,2,0),;
					IIF(fileInfo:IsDirectory,"d","f")})`

**Comment by RobertvanderHulst** [comment]
Ok, so IF is at the start of a continued line. I think I can understand why that fails.

**Comment by cpyrgas** [comment]
All work ok now, with the exception of Format Document. When having this code:

```
FUNCTION Start() AS VOID
LOCAL adir AS ARRAY
AAdd(adir,;
{1,;
2,;
IIF(FALSE,1,2),;
3,;
4,;
IF(FALSE,1,2),;
5,;
6})
```

after selecting Format Document, it formats as:

```
FUNCTION Start() AS VOID
    LOCAL adir AS ARRAY
    AAdd(adir,;
        {1,;
        2,;
        IIF(FALSE,1,2),;
        3,;
        4,;
    IF(FALSE,1,2),;
            5,;
            6})
```

**Comment by cpyrgas** [comment]
Confirmed fixed
