### ISSUE TITLE
Indentation problem with SCAN...END SCAN

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1549]
There's no indentation in the editor for SCAN...END SCAN.
Also SCAN/END SCAN does not get upper cased like INT, TRUE etc, is this by design?

```
FUNCTION test()
    LOCAL n AS INT

    scan for FALSE
    LOCAL M AS INT
    scan for TRUE
    end scan
    end scan

```

**Comment by RobertvanderHulst** [comment]
At this moment, SCAN .. END SCAN (and SCAN .. ENDSCAN) is implemented as a UDC.
The editor does not recognize it as a a valid BLOCK command.

**Comment by RobertvanderHulst** [comment]
A good solution is probably to have a file like the keyword.txt file for VO where you can add keyword pairs not already defined in the language.
That allows you to declare pairs of keywords for commands declared as UDC.
Similar to the .editorconfig files this file could be located in the solution folder.
We could even use .editorconfig for this?
```
[*.prg]
indent_style = space
keyword_case = none
udc_case = true
keyword_pair_1 = SCAN, ENDSCAN
keyword_pair_2 = FOR,ENDFOR
keyword_pair_3 = FOO, BAR
```

**Comment by cpyrgas** [comment]
In XIDE I have hardcoded them as pairs (although only ENDCSAN I see, not END SCAN - will fix that) for the FoxPro dialect only, which I think is the best solution. 

But if that's not possible due to the way that it works in VS, then the .editorconfig option sounds good. And then include that in all the VFP project templates.

**Comment by cpyrgas** [comment]
Indentation is fixed, but "SCAN" in "END SCAN" does not get highlighted neither uppercased. Same problem exists with END TEXT. END WITH works well.

**Comment by cpyrgas** [comment]
Confirmed fixed
