### ISSUE TITLE
Str( nNumber, -1, -1 ) does not works as in VO.

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#155]
VO 2.8:
```
oCon:WriteLine( Str( 9999999999999.78, -1, -1 ) )
oCon:WriteLine( Str( 9999999999999.78, 18, -1 ) )
oCon:WriteLine( Str( 9999999999999.78, 18, 4 ) )
Output:
9999999999999,78
  9999999999999,78
9999999999999,7793
```

X# Bandol 2.01:
**********
```
    10000000000000
9999999999999,7793
```

**Comment by cpyrgas** [comment]
Wolfgang, the 2nd and 3rd lines give identical results in both VO and X#:

  9999999999999,78
9999999999999,7793

maybe you were using different settings in your tests (SetDigits() etc) ? Can you please post a complete small sample showing the different behavior?

I do see the problem in the first line, it returns "*************" in X#, looking into it now.

**Comment by wriedmann** [comment]
Hi Chris,
my X# runtime sample, VO dialect, with this code:
```
Console.WriteLine( Str( 9999999999999.78, -1, -1 ) )
Console.WriteLine( Str( 9999999999999.78, 18, -1 ) )
Console.WriteLine( Str( 9999999999999.78, 18, 4 ) )

```shows the following:
**********
    10000000000000
9999999999999,7793
The 3rd line is correct, and I have added she only for reference. 
I have no SetDigit(), no other setting in the application itself. My system is using German collation, "," as decimal separator, and "." as thousand separator.
Please see the screenshot below:
![grafik](https://user-images.githubusercontent.com/19322359/63957577-f10c7800-ca88-11e9-8eee-43e113d557ce.png)
Wolfgang

**Comment by cpyrgas** [comment]
Wolfgang, please create a new app, and only add those three lines in the Start() function, without any other code. Do you still get the same results? Btw, I have sent you a newer dll, please also try with it afterwards.

**Comment by wriedmann** [comment]
Hi Chris,
done both, and nothing changes, unfortunately. 
Please see your mail for the exported application.
Wolfgang

**Comment by wriedmann** [comment]
Hi Chris,
fixed with the temporary runtime you sent me.
Wolfgang

**Comment by cpyrgas** [comment]
Thanks for your feedback Wolfgang!
