### ISSUE TITLE
[VFP] DEFINE CLASS AS CUSTOM not supported in VFP dialect

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1551]
Following results to error XS0246: The type or namespace name 'CUSTOM' could not be found (are you missing a using directive or an assembly reference?), no matter if /fox1 ins enabled or disabled

```
DEFINE CLASS BaseClass  AS CUSTOM
ENDDEFINE
```

**Comment by RobertvanderHulst** [comment]
The custom class is in the XSharp.VFP namespace.
Did you enable the /ins compiler option?

**Comment by cpyrgas** [comment]
Good point, no :)

It works now, but the original code had this as well below. In X# this results to an exception
"Variable loClass does not exist" on the RELEASE line, I assume because LOCALs are not LOCALs in VFP...(when I change it to PUBLIC in X# it works ok). CAn we do something about it? If yes, I will open a new ticket for it

FUNCTION Start() AS VOID
LOCAL loClass
loClass = CreateObject("BaseClass")
loClass.ShowMessage()
RELEASE loClass
RETURN

DEFINE CLASS BaseClass AS CUSTOM
   PROCEDURE ShowMessage
      WAIT "Hello from BaseClass" //WINDOW TIMEOUT 1
   ENDPROC
ENDDEFINE

**Comment by cpyrgas** [comment]
Maybe we need to introduce a new compiler option "treat locals as PUBLICS"? I am sure this thing has caused several problems already..

**Comment by cpyrgas** [comment]
Confirmed fixed, will open a new ticket for the other problem.
