### ISSUE TITLE
[VS Integration]The resx file for UserControl is in an incorrect location in Solution Explorer.

### ISSUE THREAD

**Issue by vfp9** [X-Sharp/XSharpPublic#1560]
In VS 2022 (version: 17.11.3), I created a UserControl in my project, and after I set its Localizable to true, and added a non-default Language, the resulting resx file is in an incorrect location in the Solution Explorer.
![demo](https://github.com/user-attachments/assets/eae03e46-e6ca-4aca-a864-fb48a9b6d309)

**Comment by RobertvanderHulst** [comment]
Xinjie,
If you close and reopen the project, does this get corrected?

**Comment by vfp9** [comment]
Robert,

Doesn't solve the problem after reopening the solution.

**Comment by cpyrgas** [comment]
Looks good to me, but will let @vfp9 confirm this. Robert, please make sure xinjie is in the list of beta testers to receive the next beta.

**Comment by vfp9** [comment]
Confirmed fix
