### ISSUE TITLE
[VS Integration]Snippets in VS 2022(Ver:17.11.3)

### ISSUE THREAD

**Issue by vfp9** [X-Sharp/XSharpPublic#1564]
The snippets is described in the help file as follows:
"You can look at the available code snippets for X# by choosing Edit > IntelliSense > Insert Snippet or right-click > Snippet > Insert Snippet or pressing Ctrl+K, Ctrl+X."

None of the options are available for VS 2022(Ver:17.11.3)

**Comment by RobertvanderHulst** [comment]
Microsoft seems to have disabled this option by default in VS2022. It was enabled before. We'll restore the functionality

**Comment by RobertvanderHulst** [comment]
Fixed in 2.21

**Comment by RobertvanderHulst** [comment]
> Snippets are being shown, but they are out of indentation, they are always inserted at the first colon in the editor. Not sure if this is something that can be addressed, leaving it for your consideration
That will not be easy, I am afraid.

**Comment by cpyrgas** [comment]
OK, confirmed fixed then!
