### ISSUE TITLE
[Documentation] Topic for DBOrderInfo() does not include available constants

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1565]
The documentation for DbInfo() includes the available DBI_ constants that can be used with it:
https://www.xsharp.eu/runtimehelp/html/M_XSharp_RT_Functions_DbInfo.htm

But the documentation for DBOrderInfo() does not include any:
https://www.xsharp.eu/runtimehelp/html/M_XSharp_RT_Functions_DbOrderInfo.htm

**Comment by cpyrgas** [comment]
Robert,

Oh, I thought it would be easy for me to add this in the documentation, but it's not in the help file, I assume it's generated automatically. 

I saw some related entries in the files \src\Docs\rdd.xml and \src\Docs\VoFunctionDocs.xml, do I need to add the info there as xml, or is there some visual way to do this?

**Comment by RobertvanderHulst** [comment]
The docs for the runtime function are generated in 2 steps:
- first I compile with a special compiler option to generate XML files per assembly
- Then I runtime Sandcastle HelpFile Builder with a special template (so static methods in the functions class are documented as FUNCTION)
- The xml files in the Docs folder are used when generating the XML files. 

In fact: the code for DbInfo() is not optimal. The same table is included in the topic for DbServer.Info (but there it is better formatted)
I will extract that table from DbInfo() and use the same table in both topics.
I will do the same for DbOrderInfo() and DbRecordInfo

**Comment by cpyrgas** [comment]
OK, sounds good!

**Comment by RobertvanderHulst** [comment]
Should be fixed in 2.21

**Comment by cpyrgas** [comment]
Confirmed fixed
