### ISSUE TITLE
/lb compiler option incorrectly affects vars of type ARRAY

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#157]
When /lb is disabled, then this works fine at runtime:

LOCAL a := {1,2,3} AS ARRAY
a:Add(1)

But when /lb is enabled, then it results to a runtime exception "XSharp.Error:No exported method".

The problem happens because when /lb is enabled, the compiler translates the call to Add() actually to a call to the runtime function ASend()! So it attempts to send "Add" to each element of the array, instead of the ARRAY object itself. Is there a reason for that?

**Comment by RobertvanderHulst** [comment]
The reason for this behavior is that Visual Objects does that. I would love to remove that (I think it is asking for problems) but I am sure that will break someone else his code.
Maybe we should generate a warning when we do this ?
And like you said to the customer: The Add() method on the Array class was never officially documented and supported. I have already made that method public for the next release. (and also Delete(), Insert(), RemoveAt() and Resize(). There are others that are still internal, such as Sort() and Swap().
The problem with exposing these methods is that we then need to document them. Insert() does not simply insert an item but it also deletes the last item (Like AIns() does). That may not be what they expect... The same for delete: It deletes the item and adds a blank at the end of the list.

**Comment by cpyrgas** [comment]
Oh, had no idea about that, thanks! Will inform the customer. Yeah, a warning would be probably helpful.

**Comment by cpyrgas** [comment]
But the "problem" still persists in 2.06. Even though the "Add" method is public, the compiler still translates it to ASend() when /lb+ is enabled

**Comment by RobertvanderHulst** [comment]
Ok,
That means that all method calls on Arrays will be translated to ASend() when late binding is enabled. 
So were are more compatible to VO than Vulcan.
I'll see if I can change that and will add a warning. 
Robert

**Comment by cpyrgas** [comment]
Maybe it would make sense to do that for the vulcan dialect only, or maybe do not bother at all. Let me check with the customer first, will tell him about the implications.

**Comment by RobertvanderHulst** [comment]
I have changed the compiler. In all but the Core and Vulcan dialect the following code
```
FUNCTION TestMe(aElements as array) AS VOID
	aElements:AddOne(1)  
RETURN
```
is compiled to a ASend() call with the warning:
`warning XS9087: 'ARRAY' does not have a method 'AddOne'. This code is converted to an 'ASend()' function call.`

In the Vulcan dialect this code now produces an error:
` error XS1061: 'ARRAY' does not contain a definition for 'AddOne' and no accessible extension method 'AddOne' accepting a first argument of type 'ARRAY' could be found (are you missing a using directive or an assembly reference?)`

**Comment by RobertvanderHulst** [comment]
And to be complete:
If you add the following extension method it does get called in the Vulcan dialect. In the VO dialect this is still resolved to a call to ASend()

```
static class ArrayExtensions
	static method AddOne(SELF aArray as ARRAY, uValue as USUAL) AS LOGIC
		AADD(aArray, uValue)
		RETURN TRUE
end class
```
