### ISSUE TITLE
File() throws an unhandled Argumentexception

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#158]
File() throws an unhandled Argumentexception ( illegal path char ) if the path contains e.g. "?"

```
FUNCTION Start() AS STRING 
LOCAL c AS STRING

c := "D:\t?est\FileDoesnotExist.txt"  


? File ( c ) 

RETURN
```

regards
Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,

`c := "D:\t?est\FileDoesnotExist.txt"  `

Really ?
Ok, I'll add an extra try catch to catch garbage like that and will always return FALSE when an exception occurs.
Why don't you join our team and start writing the unit tests (and fixing the code) directly ?

Robert
