### ISSUE TITLE
Cannot use SizeOf() on a structure containing a string in the Core dialect

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1594]
In the VO dialect, SizeOf() works without errors, but in Core dialect, the compiler reports an error:

```
// Core dialect
STRUCTURE MyStruct
	EXPORT n AS INT
	EXPORT c AS STRING
END STRUCTURE

FUNCTION Start() AS VOID
	? SizeOf(System.Drawing.Point) // OK
	? SizeOf(MyStruct) // error XS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('MyStruct')
RETURN
```

**Comment by RobertvanderHulst** [comment]
This makes sense. The string is a pointer and the size of the pointer is 32 bits when running in x86 mode. Else 64 bits.

**Comment by cpyrgas** [comment]
But then why does it work without errors in the VO dialect, even if the target is still AnyCPU?

Maybe it should work in both when the target is either x86 or x64, but report an error in both when using AnyCPU?

**Comment by RobertvanderHulst** [comment]
Most likely you have "allow unsafe" enabled for the app with the VO Dialect?

**Comment by cpyrgas** [comment]
No, it's disabled. But why should this make a difference, this is for using pointers (so it should affect VOSTRUCTs, not regular STRUCTUREs), isn't it?

**Comment by cpyrgas** [comment]
Ah, I see, c# requires an unsafe context for it. But it does so no matter the types used, they throw the same error even for the simplest structure with only one UInt16 member. I assume that's because due to alignment etc, the size it actually takes in memory can be different, even for a very simple number.

So if we bypass c#'s error detection and not report an error for structures in general, I think we should allow it also for structures holding reference types, at least when the target is not AnyCPU.

Or we need to disallow it, but I think it doesn't make sense for it to be different in different dialects, with the same compiler options.

Or could it be that /unsafe is actually always enabled for the non-core dialects? I wouldn't be surprised if that's the case..

**Comment by RobertvanderHulst** [comment]
Ok, here is the analysis:
Roslyn checks to see if the type is "managed". A type is considered "managed" when one of the fields in the structure is "Managed". In this case the string field is managed, so that is why the MyStruct type is considered "managed". System.Drawing.Point is NOT managed because both fields are unmanaged.
We have added code (probably because someone asked for it) that we do NOT report an error for this when the dialect is not Core.
Does this make sense? Probably not.

**Comment by cpyrgas** [comment]
Ah, I see now, c# has two different errors, one for when using sizeof with a structure in general (and this can be bypassed by using an unsafe context), and another when the structure also has a reference member and cannot be bypassed.

Yes, I understand why we did it, but indeed I don't think the way it works in c# makes sense. But that's not the first time something by MS does not make sense to me..
