### ISSUE TITLE
Windows Forms Designer : Crashes when editing a VFPXPorter generated Form

### ISSUE THREAD

**Issue by fforay** [X-Sharp/XSharpPublic#1595]
**Describe the bug**
The Designer is not able to open a VFP exported Form.

**To Reproduce**
With a simple Dialog Form in FoxPro, run VFPXPorter and export the app (one with a single, or some, CommandButton is enough)
Build to check its ok (and run!)

**Expected behavior**
When opening the Designer, it crashes with a message like:
Duplicate declaration of Member
[SimpleDialog.zip](https://github.com/user-attachments/files/17310321/SimpleDialog.zip)

**Comment by fforay** [comment]
Thanks closed by #1596

**Comment by cpyrgas** [comment]
Confirmed fixed
