### ISSUE TITLE
Resizable VO-Window Clone selection

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#1601]
**Is your feature request related to a problem? Please describe.**
I want to clone one of our VO-Windows. Unfortunately the names including the sub directories are so long so that I do not see the correct window name. 
I am using the beta version XSharpSetupFox2.21.0.2

**Describe the solution you'd like**
The window is already resizable, but the listbox does not resize. 

**Describe alternatives you've considered**
- 

**Additional context**
![image](https://github.com/user-attachments/assets/fed6ee05-5d7a-4490-9d92-52526dbb34cf)

**Comment by RobertvanderHulst** [comment]
This should be fixed in the latest 2.21.03 beta

**Comment by cpyrgas** [comment]
The listbox now resizes in width, but not in height. I will take care of this

**Comment by cpyrgas** [comment]
Should be fixed now
