### ISSUE TITLE
Error in the VS Exception dialog

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#1602]
The exception dialog shows this, which is not correct
![Screenshot-2024-10-16-073125](https://github.com/user-attachments/assets/6dee86d8-9d63-4ff6-885e-76c3574654df)

**Comment by RobertvanderHulst** [comment]
The problem was caused by the $ character in front of the identifier "$exception". Roslyn (and now also X#) allows this character as part of an identifier when running in Debugger Expression parsing mode.

**Comment by cpyrgas** [comment]
Confirmed fixed
