### ISSUE TITLE
[VS Integration]Problems with formatting documents when using the Foxpro dialect

### ISSUE THREAD

**Issue by vfp9** [X-Sharp/XSharpPublic#1609]
I've noticed that formatting documents still has some problems for the Foxpro dialect.

My development environment: VS2022(Ver:17.11.5) and X#(Ver:2.21.0.3)

Steps to reproduce the problem: In a project using the Foxpro dialect, create a new class and format the document, you should see results similar to the screenshot below:
![image](https://github.com/user-attachments/assets/e92b3cd1-86f8-4fc5-9d42-d27c5408f5f3)
The section marked by the red box is not indented correctly.

**Comment by vfp9** [comment]
In case the image upload fails (I can't see the image uploading successfully), I've pasted the formatted code here. Note the “Define Class Class1” and “Enddefine”, and the comments section.
```csharp
Using System
Using System.Collections.Generic
Using System.Text

Begin Namespace mytest
    
        /// <summary>
        /// The Class1 class.
        /// </summary>
        Define Class Class1
        Protected prop1         As String // X# allows types
        Hidden hiddenprop1      As Date
            // CONSTRUCTOR
        Procedure Init(p1 As String, p2 As Date)   // X# allows to type the parameters
            prop1 := p1
            hiddenprop1 := p2
            
            
        Function Compare (p1 As String, p2 As Date) As Logic
            ? p1, p2
            Return p1 == prop1 AND p2 == hiddenprop1
            
        Constructor()
            Return
            
Enddefine
End Namespace // mytest
```

**Comment by cpyrgas** [comment]
Confirmed fixed
