### ISSUE TITLE
[VFP] Problem defining properties when class inherits from system type

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1610]
Following results to 

error XS0115: '_InitProperties': no suitable method found to override

No matter the state of /fox1

This happens because the compiler defines an OVERRIDE METHOD _InitProperties() for the class, but the parent class (Form) has no such method to override.

This must be a new bug in 2.21, because apparently it worked before, see https://www.xsharp.eu/forum/topic?p=31610#p31610

```
DEFINE CLASS Class1 AS System.Windows.Forms.Label
   mytest = "myTest"    
ENDDEFINE
```

**Comment by RobertvanderHulst** [comment]
This is no longer supported in 2.21
