### ISSUE TITLE
[VFP] Documentation error about the /memvar option

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1621]
In the documentation about memvar: https://www.xsharp.eu/help/opt-memvar.html

it is mentioned: 

`The -memvar option tells the compiler to enable the support for  'memory variables'. This option is also needed in the FoxPro dialect if you want to make local variables visible to the macro compiler with the [-fox2](https://www.xsharp.eu/help/opt-fox2.html) compilation option.`

I think the second part of the text is wrong, /fox2 currently does not affect visibility of locals.

By looking at the compiler output, am I right assuming that locals become available to the macrocompiler, if the compiler detects a macrocompiler call (via "&", MExec() etc) within the entity body where the locals are defined? 

And that indeed still it is necessary for enabling /memvar for this to work, just not related to /fox2

**Comment by RobertvanderHulst** [comment]
I will adjust the docs.

> By looking at the compiler output, am I right assuming that locals become available to the macrocompiler, if the compiler detects > a macrocompiler call (via "&", MExec() etc) within the entity body where the locals are defined?

The compiler actually looks for a call to a function / method that is decorated with `[NeedsAccessToLocalsAttribute]`
At this moment, this is the case for
- __MemVarGet()
- __MemVarGetSafe()
- __MemVarPut()
- __VarGet()
- __VarGetSafe()
- __VarPut()
- Evaluate()
- MExec()
- Type()
- StrEvaluate()
- MAssign()
- MemVarGet()
- MemVarTryGet()
- MemVarPut()
- MemVarClear()
- MemVarRelease()
- VarGet()
- VarPut()
- VarGetSym()
- VarPutSym()
- MemVarGetSym()
- MemVarPutSym()
- _MClear()
- _MxRelease()
- _MRelease()
- __ScatterObject()
- __SqlInsertMemVar()
- SqlExec()
- SqlPrepare(()
- __TextEnd()
- TextMerge()

The parameter for this attribute is inspected by the compiler. When the parameter is TRUE then the function may have updated one or more local variables and then the compiler will output code that detects if locals were updated, and when they were, then the locals will be updated.

**Comment by cpyrgas** [comment]
Ah, thanks! That's very smart and also inspirational :)

**Comment by cpyrgas** [comment]
Confirmed fixed
