### ISSUE TITLE
Dynamic definition of generic types

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1623]
When I try to compile the following line of code, the compiler returns an error:

```
LOCAL generic AS System.Type
generic := TYPEOF(System.Collections.Generic.Dictionary<,>)
```
or
```
generic := TYPEOF(System.Collections.Generic.HashSet<>)
```

More details on the forum: [Type.MakeGenericType](https://www.xsharp.eu/forum/topic/4896?p=31764#p31764)

X# Compiler: 2.19.0.2

**Comment by RobertvanderHulst** [comment]
Note that in the second example 
` TYPEOF(System.Collections.Generic.HashSet<>)` the space between `<` and `>` is mandatory

**Comment by cpyrgas** [comment]
This still does not seem to work, even if using spaces between the characters. Will create a test for this.

**Comment by leon-ts** [comment]
> Note that in the second example ` TYPEOF(System.Collections.Generic.HashSet<>)` the space between `<` and `>` is mandatory

Robert,
Is it possible to implement it so that it has a standard notation, without spaces? It is easy to forget, and it will look unnatural.

**Comment by RobertvanderHulst** [comment]
> > Note that in the second example ` TYPEOF(System.Collections.Generic.HashSet<>)` the space between `<` and `>` is mandatory
> 
> Robert, Is it possible to implement it so that it has a standard notation, without spaces? It is easy to forget, and it will look unnatural.

Leonid,
Not in the build that we're about to complete. `<>` is defined as the Not Equals operator.

**Comment by cpyrgas** [comment]
Confirmed fixed
