### ISSUE TITLE
Feature Request: VO Window Editor - SEALED classes

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#1628]
Please implement saving of class modifier 'SEALED' when editing VO window classes. Now I manually specify this modifier, but after editing a window the editor deletes it.

In addition, if the 'SEALED' modifier is specified, then the automatic fields of the class should have the 'PRIVATE' access modifier, instead of 'PROTECTED'.

Example:

```
INTERNAL SEALED CLASS MyWindow INHERIT DialogWindow

	PRIVATE oDCGroupBox1 AS GROUPBOX
	PRIVATE oDCFixedBitmap1 AS FIXEDBITMAP
	PRIVATE oDCFixedText1 AS FIXEDTEXT
        ...

	// {{%UC%}} User code starts here (DO NOT remove this line)  
```

**Comment by cpyrgas** [comment]
Both should be working now
