### ISSUE TITLE
VS problem when trying to open .xsproj file directly

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1638]
I tried to copy the VOXporter project to a new folder, then opened the VOXPorter.xsproj (happens also with Fab_VO_Entities.xsproj) file, all VS versions respond with an error dialog and do not open it:

---------------------------
Microsoft Visual Studio
---------------------------
Invalid class string (Exception from HRESULT: 0x800401F3 (CO_E_CLASSSTRING))
---------------------------
OK   
---------------------------

Maybe it has to do with loading the references from a (missing now?) folder, or because of the missing solution file (is that a problem?), but the error message of course does not help to find the cause.

Here's the project I'm testing with:

[VOXporterTest.zip](https://github.com/user-attachments/files/17869221/VOXporterTest.zip)

**Comment by cpyrgas** [comment]
I also get the same error when I try to add the project to another solution

**Comment by cpyrgas** [comment]
Robert, thanks but no need to, I started from the full solution now and I am deleting the folders and files that are not needed. But I have seen this strange error message in VS also in other cases, I think this situation needs to be trapped and give a helpful error message if possible

**Comment by RobertvanderHulst** [comment]
This zip contains the source and also the right folder structure for the solution file (inside src) and output (inside Artifacts)
[Xporter.zip](https://github.com/user-attachments/files/17869569/Xporter.zip)

**Comment by RobertvanderHulst** [comment]
> Robert, thanks but no need to, I started from the full solution now and I am deleting the folders and files that are not needed. But I have seen this strange error message in VS also in other cases, I think this situation needs to be trapped and give a helpful error message if possible

This will be very difficult. The error comes from deep within MsBuild / VS

**Comment by cpyrgas** [comment]
OK, thanks a lot, I thought I had actually managed to do it myself, but failed miserably when I tried to open my solution for the last time before sending :). Yours works fine!
