### ISSUE TITLE
VOWED ToolBox window appears mangled when font scaling is used in the OS

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#1650]
https://www.xsharp.eu/forum/topic?p=32124#p32124

In Visual Studio 2022 (17.12.2) when editing a window the Toolbox has all characters messed up. I guess that this is due to the fact that I've a 4k monitor scaled at 150%. 

![VS_toolbox](https://github.com/user-attachments/assets/fc884aa2-88ce-454a-a640-53bde1528ff5)

**Comment by cpyrgas** [comment]
Should be fixed now, but needs testing with various OS font settings

**Comment by RobertvanderHulst** [comment]
Fixed as far as I can tell
