### ISSUE TITLE
VFP - DO Command with prgs / fxps

### ISSUE THREAD

**Issue by MarioV-GH** [X-Sharp/XSharpPublic#1657]
**Describe the bug**
We have prgs/fxps excluded and included in the project.
Excluded prgs are compiled into fxps and delivered to the application environment.
Included prgs are compiled into the application .exe file.
In code we have several options to adress/call those code-files via DO command:
DO mn_transformationrightclick.prg WITH thisObject,1,lSysTrans && prg as part of the exe
DO (<Path>+"\external.fxp") WITH ... && example for call of external fxp
With migration into xSharp I think it should be possible to remove those external files and make this code as part of the exe. But here is an example that does not work.

**To Reproduce**
example code in "example_do_prg.zip"

**Expected behavior**
prgs added to the project callable via DO

**Screenshots**
"call prg with do.jpg" in "example_do_prg.zip"
[example_do_prg.zip](https://github.com/user-attachments/files/18147249/example_do_prg.zip)

**Comment by RobertvanderHulst** [comment]
It will be very difficult to support this exactly like how it is supported in VFP.
This should indeed become part of the main exe, or part of an external DLL. When it is inside a DLL then this DLL can be loaded "on demand".
But can you explain why, in this case, this can't be part of the exe. I don't see that.

**Comment by MarioV-GH** [comment]
The support of the "DO command" would just reduce migration effort. Of course, it should be possible to migrate those prgs into classes with procedures and replace all DO calls by calling the code of those classes. There are some sideffects to be handled, such as public objects to be accessible within the class and ambiguous global function names in the project. I have seen, in the new version there is better support to distinguish ambiguous procedures/functions/methods.
