### ISSUE TITLE
Problem with ++/-- operators with DATE in USUAL

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#167]
```
FUNCTION Start() AS VOID
  LOCAL u AS USUAL
  LOCAL d AS DATE

  d := Today()
  ? ++ d // ok
  ? d ++ // ok
  ? d -- // ok

  u := Today()
  ? u 
  ? ++ u // exception
  ? u ++ // exception
  ? u -- // exception
  ? -- u // exception
RETURN
```

XSharp.Error
Value does not fall within the expected range.

Callstack : 
static __Usual XSharp.__Usual.op_Increment(XSharp.__Usual u)()   :  C:\xSharp\DevRt\Runtime\XSharp.RT\Types\Usual.prg  :  1130

**Comment by cpyrgas** [comment]
Damn, you made the commit just before mine!

**Comment by RobertvanderHulst** [comment]
Did you include the DateTime type as well ?

**Comment by cpyrgas** [comment]
No :)
But I had added the (SByte) cast as well!
