### ISSUE TITLE
Problem creating dbf wit international chars in field names

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#169]
DBCreate() generates dbfs with mangled field names, when they contain non-english characters. See the results of the code below and when opening the dbf with a dbf viewer.

I'm pretty sure that the cause of the problem is the DbfField:Name property in DBF.prg, it uses System.Text.Encoding.ASCII twice, instead of the encoding stored in the DBF object to make the translation, but Robert I'd better leave that to you to handle this.

Doing a global search for Encoding.ASCII in the runtime code reveals a few more places where this is used and probably also need attention:

NtxHeader:_GetString{}
CdxLeafPage:ReadTags()
FlexHeader:Signature

```
FUNCTION Start() AS VOID
	LOCAL c AS STRING
	LOCAL cDbf AS STRING
	cDbf := "C:\dbf\strasse"
	c := "STRAßE"
	? c //"STRAßE", ok
	DbCreate(cDBF,{{c,"C",10,0} ,{"AÖÄÜ","C",10,0}})
	DbUseArea(,,cDBF)
	? FieldName(1) // "STRA?E"
	? FieldName(2) // A???
	DbCloseArea()
RETURN
```

**Comment by RobertvanderHulst** [comment]
I will adjust this. Btw FlexHeader:Signature can /may only contain the text "FlexFile3". That is not a problem. When we allow 'special' characters in field names, then indeed the index expressions also may contain a special character.
I personally don't think it is a good idea to use such a character in a field name, but if this is allowed in other xBase dialects then we should allow this too. I checked and FoxPro allows this and so does VO. So I'll change that.
