### ISSUE TITLE
Alen() function has second parameter in FoxPro...

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#170]
In FoxPro, the `Alen()` function takes a second parameter.

I'm getting a compiler error with FoxPro dialect for this code:

```
For lnX := 1 To Alen(myArray, 1)

   lcFirstName := myArray[lnX, 1]

   lcLastName := myArray[lnX, 2]

   ? lcFirstName + " " + lcLastName

Next
```

![2019-09-09 03_45_17-Visual FoxPro 9 0 SP2](https://user-images.githubusercontent.com/309016/64517052-30bb3700-d2b5-11e9-8447-77d9a35364fe.png)

**Comment by RobertvanderHulst** [comment]
Matt,
I know. see my reply to #171.

**Comment by RobertvanderHulst** [comment]
Implemented
