### ISSUE TITLE
[Visual Studio] - Indent code when "End Method" is typed...

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#174]
When defining a Method in a PRG, if I have this code:

```
Method MyMethod() As VOID
Local lcMessage
lcMessage := "This is a HIDDEN method on a Class."
MessageBox(lcMessage)
```

Then I type `End Method` on the next line:
```
Method MyMethod() As VOID
Local lcMessage
lcMessage := "This is a HIDDEN method on a Class."
MessageBox(lcMessage)
End Method
```

I'd expect it to indent the code between Method and End Method, like Visual Studio does when you are coding in C# and you type the ending markers in code blocks for that language.

End result:

```
Method MyMethod() As VOID
    Local lcMessage
    lcMessage := "This is a HIDDEN method on a Class."
    MessageBox(lcMessage)
End Method
```

**Comment by RobertvanderHulst** [comment]
Matt,
End method (and other new end keywords like end procedure or endproc and end function) have been introduced recently to the compiler to make the language look more like FoxPro.
The VS integration, and especially the indenting, has not been updated for that.
Fabrice, our 'Mr Visual Studio', is working on making the VS integration use Asynchronous support which should result in better performance inside VS. He is also working on .Net core support for VS.
Fabrice will look at the VS integration for the FoxPro dialect once that dialect stabilizes in the compiler.

**Comment by mattslay** [comment]
Understood. Thanks.

**Comment by RobertvanderHulst** [comment]
Implemented
