### ISSUE TITLE
Add MessageBox() function and ALen() function with extra parameter

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#175]
FoxPro Dialect in Visual Studio:

Using the VFP method `MessageBox()`, I get a compiler error:

> Error XS1955:  Non-invocable member 'System.Windows.Forms.MessageBox' cannot be used like a method.	

Code:

```
Method CustomMethodOnContainer() As Void
	Local lcText As String
	Local lnX As Int
	lnX := 1
	lcText := "Sample text here."
	MessageBox(lcText)
 
End Method
```

**Comment by RobertvanderHulst** [comment]
MessageBox is a type in System.Windows.Forms
We'll add a MessageBox function in the VFP runtime 
And Matt, it is really too early to expect that existing code will work "unchanged".

Robert

**Comment by RobertvanderHulst** [comment]
Please give me a few weeks to complete the FoxPro class syntax. After that I'll have a look at the VFP runtime and add functions like this one and I will also add support for FoxPro compatible arrays and other things needed in the runtime.

**Comment by mattslay** [comment]
Robert - I am not expecting it. I understand the state of everything, lower level stuff for now. 

However, I still report these as I encounter them so they can go on the work list.

**Comment by RobertvanderHulst** [comment]
MessageBox has been added. ALen() with the changed VFP behavior will most likely follow later

**Comment by mattslay** [comment]
You should close this issue, because we already have #170 to address Alen()
