### ISSUE TITLE
The DBFCDX RDD changes the date of the DBF even when there is no change

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#176]
The following code changes the timestamp of the DBF file:
`	local cFileName		as string
	local oServer		as DbServer

	cFileName			:= "C:\CAVOWork\EasyFaktV3\tables.dbf"
	oServer				:= DbServer{ cFileName, true, false, "DBFCDX" }
	oServer:GoTop()
	oServer:Close()`

Without the :GoTop() call the timestamp is not changed.

**Comment by cpyrgas** [comment]
Hmm, I thought this was fixed, but seems this problem still exists, even by just opening and closing the dbf:


```
USING System.IO
USING System.Threading
FUNCTION Start() AS VOID
	LOCAL c AS STRING
	c := "c:\test\mytest.dbf"
	IF .not. File.Exists(c)
		DbCreate(c,{{"TEST","C",10,0}})
		DbUseArea(,,c)
		DbAppend()
		DbCloseArea()
		Thread.Sleep(1500)
	END IF
	? FileInfo{c}:LastWriteTime
	DbUseArea(,,c)
	DbCloseArea()
	? FileInfo{c}:LastWriteTime // different to above
RETURN
```

**Comment by wriedmann** [comment]
By just opening and closing the file I could not reproduce it I needed the GoTop(). When I first wrote about this issue, it was enough to open and close the file. But this was apparently fixed.

**Comment by RobertvanderHulst** [comment]
Confirmed. Will be fixed in next build

**Comment by RobertvanderHulst** [comment]
This was broken when I changed the rdd for another ticket. Chris can you add a unit test?

**Comment by cpyrgas** [comment]
Done, added tests for all files (dbf, cdx, ntx etc) and problem is confirmed fixed now. Wolfgang, I am using a newer runtime version than yours, probably this is why we were seeing slightly different results.
