### ISSUE TITLE
_DLL METHOD and ACCESS cause parser errors

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#178]
The following declarations lead to parser errors (can be 100s) that are not helpful for the user to understand what the problem. A normal compiler error (like "_DLL method not supported") should be reported instead and/or VOXporter should remove those declarations (is it ok doing that?).

CLASS SomeClass
_DLL METHOD SomeMethod(n AS INT) AS INT PASCAL CLASS SomeClass:VO27GUI.2261
_DLL ACCESS SomeAccess AS INT CLASS SomeClass:VO27GUI.2261
END CLASS

C:\XporterOutput\Basiccon2\Main.prg(3,1): error XS9002: Parser: unexpected input 'CLASS SomeClassCRLF_DLL'
C:\XporterOutput\Basiccon2\Main.prg(3,6): error XS9002: Parser: mismatched input 'METHOD' expecting {FUNCTION, PROCEDURE}
C:\XporterOutput\Basiccon2\Main.prg(3,63): error XS9002: Parser: unexpected input 'SomeClass:'
C:\XporterOutput\Basiccon2\Main.prg(4,6): error XS9002: Parser: mismatched input 'ACCESS' expecting {FUNCTION, PROCEDURE}
C:\XporterOutput\Basiccon2\Main.prg(4,46): error XS9002: Parser: unexpected input 'SomeClass:'
C:\XporterOutput\Basiccon2\Main.prg(6,1): error XS9002: Parser: unexpected input 'END'

**Comment by RobertvanderHulst** [comment]
If VOXporter can recognize this and tell the user to use the source of the DLL and not the AEF with the prototypes then that would be great.
I can (and will) also add a _DLL METHOD, _DLL ACCESS ad _DLL ASSIGN definition to the parser of the compiler so we can produce a meaningful error message in the compiler.
