### ISSUE TITLE
Incorrect overload used by the compiler for String.Format()

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#180]
Following results to an exception at runtime, because the compiler incorrectly resolves the call to one of the Format() overloads that accepts an IFormatProvider as first parameter (but none of those overloads accepts 2 arguments in total as in the calling code, all require 3 or more), instead of the overload that accepts a string and an object: (STATIC METHOD Format(format AS STRING, arg0 AS OBJECT) AS STRING)

FUNCTION Start() AS VOID
LOCAL u := "Test{0}" AS USUAL
? String.Format(u, "1") // System.InvalidCastException
RETURN

Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.IFormatProvider'.
   at xRuntime.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg:line 3

**Comment by RobertvanderHulst** [comment]
The compiler resolves this to 
public static string Format(IFormatProvider provider, string format, params object[] args)
and passes an empty list of objects for the args parameter.

**Comment by RobertvanderHulst** [comment]
Fixed in 2.2
