### ISSUE TITLE
Problem with setting the SpecificVersion property for References in VS 2017

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#182]
In the attached solution, select one of the XSharp.* references, go to properties and set the Specif Version from False to True. That works, but now try to set it back to False, this does not work (property stays True in the property editor).

[ConsoleApplication4.zip](https://github.com/X-Sharp/XSharpPublic/files/3623070/ConsoleApplication4.zip)

**Comment by RobertvanderHulst** [comment]
Fixed in 3cd45e382caa4019100abad5f3346892e0e8e0de
