### ISSUE TITLE
VS2015 activity log

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#187]
When editing the X# VSIntegration solution, when opening any of the .prg files of the project "XSharpVoEditors", there's no syntax highliting. When clicking with the mouse on one of those files for the first time, go this exception:

System.NullReferenceException: Object reference not set to an instance of an object

at XSharp.Project.Editors.BraceMatching.BraceMatchingTagger.&lt;GetTags&gt;d__20.MoveNext() in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\Editors\BraceMatching\BraceMatching.cs:line 137&

at 

Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__38.MoveNext()</description>

**Comment by RobertvanderHulst** [comment]
I am seeing this too every now and then. The Brace matching code seems to get confused by certain code. For example I have this code

```
FUNCTION Foo()
..
SCAN FOR ....
   ..
ENDSCAN
END FUNCTION

```
In this case it matches the FOR condition in the SCAN line with the END keyword from the function.
On another place I have this:

```
BEGIN NAMESPACE myNS
DEFINE PUBLIC CLASS MyFirstClass AS Custom
	PUBLIC cDbfName = "c:\download\setrela\xSharp_Test_Parent.dbf"
END DEFINE
END NAMESPACE
```
Here the BEGIN keyword from BEGIN NAMESPACE is matched with END DEFINE.

**Comment by RobertvanderHulst** [comment]
Fixed today
