### ISSUE TITLE
Strange behavior with (DWORD) conversion

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#189]
In the following sample, all calls to the overloaded function compile (and run) fine, except for the last one Test((DWORD) n). Note that "n" is already declared as a DWORD, so the conversion should make no difference.

// compiler with /vo7+
FUNCTION Start() AS VOID
	LOCAL n AS DWORD
	Test(n)  // ok, float
	Test(DWORD(n)) // ok, float
	Test(DWORD(_CAST, n)) // ok, float
	Test((DWORD) n) // compiler error XS0121
RETURN

FUNCTION Test(pfFloat AS FLOAT) AS VOID
	? "float"
FUNCTION Test(plLogic AS LOGIC) AS VOID
	? "logic"

error XS0121: The call is ambiguous between the following methods or properties: 'xRuntime.Exe.Functions.Test(XSharp.__Float)' and 'xRuntime.Exe.Functions.Test(logic)'

**Comment by cpyrgas** [comment]
Same problem exists with INT, so we probably need to get a quickfix out for this:

```
FUNCTION Start() AS VOID
	LOCAL u := 1 AS USUAL
	Test(1) // OK
	Test(INT(1)) // OK
	Test(INT(u)) // OK

	Test((INT)1) // error
	Test(u) // error
	Test((INT)u) // error
RETURN

FUNCTION Test(pfFloat AS FLOAT) AS VOID
	? "float"
FUNCTION Test(plLogic AS LOGIC) AS VOID
	? "logic"

```

**Comment by RobertvanderHulst** [comment]
This was a side effect of the change that I did which allows to cast an integer to a Boolean. I have fix this now.
