### ISSUE TITLE
VS Problem with moving files between folders

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#192]
Attached project has Folder1 and Project2, with one prg file in Folder1. The Build Action of the file is set to None.

- Move the file from Fodler1 to Folder2, instead of moving, the File gets duplicated. (that should happen only when the CTRL key is pressed as well.

- Note the properties of the new file, BuildAction is set to Compile instead of None. (when the file is moved, then definitely the BuildAction should remain the same).

[ConsoleApplication22.zip](https://github.com/X-Sharp/XSharpPublic/files/3658869/ConsoleApplication22.zip)

**Comment by RobertvanderHulst** [comment]
I cannot reproduce this in the current build anymore.

**Comment by cpyrgas** [comment]
Indeed it is working well now, already at least in 2.13
