### ISSUE TITLE
[FoxPro] EndFor is not syntax colorized in Visual Studio...

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#193]
In Visual Studio, syntax colorizing worka for `End For`, but it does NOT work for `EndFor`

```
For x = 1 To 100
	? x
End For


For x = 1 To 100
	? x
EndFor

```
![2019-09-27_10-15-14](https://user-images.githubusercontent.com/309016/65780699-e7217780-e10f-11e9-994b-e2f472acce3d.png)

**Comment by RobertvanderHulst** [comment]
It looks like the VS parser is not properly parsing the FoxPro header file.
If you include the contents of the header file in the beginning of the source file:
```
#xcommand ENDPROC <*any*> => END PROCEDURE
#xcommand ENDFUNC <*any*> => END FUNCTION
#xcommand ENDWITH <*any*> => END WITH
#xcommand ENDFOR  <*any*> => NEXT
```
then ENDFOR gets colorized as expected.

**Comment by mattslay** [comment]
okay, maybe it can get fixed at a lower level one day?

BTW - is it okay to use NEXT in place of ENDFOR?  They will both result in the same code underneath?

**Comment by RobertvanderHulst** [comment]
Matt,
ENDFOR is preprocessed into NEXT

**Comment by RobertvanderHulst** [comment]
Found the problem. When tokenizing the editor contents in VS we try to optimize and prevent needless preprocessing. The Vs editor tokenizer tries to determine if preprocessing is really needed and ignores the standard header files when determining this.
If you add something like this to your code then the preprocessor WILL run and as a result ENDFOR will be colored properly as a keyword.
`#translate SomeRulethatwillbenevermatched => 
`
