### ISSUE TITLE
Cannot invoke member completion when "inside" an expression

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#198]
If you have this code

```
LOCAL c AS STRING
c:Chars:ToString()
```

but you realize you want to change "Chars" to "Length", so delete this word and end up with

```
c:ToString()
 ^----- cursor here
```

so then you type ":" again to invoke the member list as in

```
c::ToString()
 ^----- cursor here
```

now the member completion window does not appear. In order to make it appear, you must put a space before the previous ":", then invoke member completion and after typing the new member, you must delete the space you added.

In c#, member completion opens in this scenario fine. Also in X#, when you have dots, it does work fine:

```
System..Forms
      ^----cursor here, type "." to bring up "Windows"
```

It's only when there's a ":" in the next caret position that member completion does not show.

**Comment by RobertvanderHulst** [comment]
Fixed
