### ISSUE TITLE
Initializers for complex collections are not supported

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#2]
// error XS9008: Untyped arrays are not available in the selected dialect 'Core'

```
USING System.Collections.Generic
FUNCTION Start() AS VOID
VAR l := List{} {1,2,3} // ok
? l[1]

VAR s := SortedList{} {{1,2},{3,4}} // error 9008
? s[1]
RETURN
```

**Comment by RobertvanderHulst** [comment]
THis also does not work:
`        VAR diction := Dictionary<STRING, STRING>{StringComparer.CurrentCultureIgnoreCase}{ {"ABC", "DEF"} }
`

Produces: XS7036, There is no argument given that corresponds to the required formal parameter 'value' of 'System.Collections.Generic.Dictionary<string, string>.Add(string, string)'

**Comment by nvkokkalis** [comment]
Note that `List{} {1,2,3}` does not work.
Instead, it was necessary to write it as `List<INT>{} {1,2,3}`
Did some other change cause that?

**Comment by RobertvanderHulst** [comment]
I am not sure if this never worked. It is very well possible that we "broke" this to allow support for literal VO style arrays.

**Comment by RobertvanderHulst** [comment]
C# also requires the type argument. This also produces the error message about the type being required:
var l = new List() { 1, 2, 3 };  // Using the generic type 'List<T>' requires 1 type arguments
I think this is solved now. Thanks !

**Comment by RobertvanderHulst** [comment]
I am sorry but I found one more thing.
Maybe it works, but I don't know the right syntax
The first sample below does NOT work, the second does.
The first sample generates the following (checked with ILSpy in C# mode):
`string[,] aMulti3 = new string[2, 2];`
If you omit the `{2,2}` in the assignment then compiler complains "Untyped arrays are not available in the selected dialect 'Core'". Maybe we need a `<STRING>` somewhere in this line, but I do not have clue where (and I don't think our customers would understand either).


```
FUNCTION Start( ) AS VOID       
	// this does not work
	LOCAL aMulti AS STRING[,]
	aMulti := STRING[,]{2,2}{ { "X#", "xsharp.info" }, { "C#", "microsoft.com" } }

	xAssert(aMulti[1,1] == "X#")
	xAssert(aMulti[1,2] == "xsharp.info")
	xAssert(aMulti[2,1] == "C#")
	xAssert(aMulti[2,2] == "microsoft.com")
	// this works
	LOCAL aMulti2 AS STRING[][]
	aMulti2 :=  <STRING[]>{ <STRING>{  "X#", "xsharp.info"}, <STRING> { "C#", "microsoft.com" } }
	xAssert(aMulti2[1][1] == "X#")
	xAssert(aMulti2[1][2] == "xsharp.info")
	xAssert(aMulti2[2][1] == "C#")
	xAssert(aMulti2[2][2] == "microsoft.com")
	
RETURN

PROC xAssert(l AS LOGIC)
IF l
	? "Assertion passed"
ELSE
	THROW Exception{"Incorrect result"}
END IF



```

**Comment by nvkokkalis** [comment]
Robert, support for array initializers was missing. Your sample should work now.

**Comment by RobertvanderHulst** [comment]
Tx, I will look at this tonight

**Comment by RobertvanderHulst** [comment]
Confirmed that this is fixed. And both the collection initializer for the first array and the constructor parameters for the second array can be written as simple as:
`{{ "X#", "xsharp.info" }, { "C#", "microsoft.com" } }`
So there are no type casts or anything needed. Great work !
