### ISSUE TITLE
VS designers generate keywords with incorrect casing

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#200]
When saving a form in VS (or any designer), the generated code has all keywords in lower case. That means, that when opening that prg file (or having it opened already before), it is marked as changed, because the editor then changes them to upper case (if that's the option enabled in the preferences). This happens every single time the designer is modified.

Solution, maybe it would be enough to make the editor generate code that repects the preferences setting? So if keywords->UPPERCASE is enabled, then all keywords should be generated in UPPER CASE as well.

**Comment by RobertvanderHulst** [comment]
Changed for the form editor. The other editors will follow shortly.

**Comment by RobertvanderHulst** [comment]
Fixed
