### ISSUE TITLE
PUBLIC problems with FOXPRO dialect

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#201]
- In the attached solution, PUBLICs are used and on building some errors are displayed:

error XS9007: Feature 'PUBLIC statement' is not available in the selected dialect FoxPro

the message is misleading, the problem is that the options /memvar and /undeclared were not enabled

- After enabling the options, the sample reports an error " not all code paths return a value"

[ConsoleApplication23.zip](https://github.com/X-Sharp/XSharpPublic/files/3666316/ConsoleApplication23.zip)

**Comment by RobertvanderHulst** [comment]
The 'not all code paths return a value' has been fixed.

**Comment by RobertvanderHulst** [comment]
The error message has now been changed to: "To use Dynamic variables (PUBLIC, PRIVATE, MEMVAR) you will have to pass the /memvar commandline option."
