### ISSUE TITLE
Problem opening CDX index in VFP RDD

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#203]
When opening the attached dbf from DBFVFP driver, an exception is thrown. Problem seems related with the index, because by deleting the .cdx file, then the code runs fine.

```
FUNCTION Start( ) AS VOID         
	LOCAL cDbf AS STRING
	cDbf := "C:\xSharp\Users\Matt\wwbusinessobjects\wwbusinessobjects.dbf"
	DbUseArea(TRUE,"DBFCDX",cDbf,"ALIAS")
	? FieldGet(1)
	DbCloseArea()
RETURN
```

Unhandled Exception: XSharp.RDD.RddError: Exception of type 'XSharp.RDD.RddError' was thrown. ---> XSharp.RDD.RddError: Exception of type 'XSharp.RDD.RddError'
was thrown.
   at XSharp.RDD.DBF._dbfError(Exception ex, UInt32 iSubCode, UInt32 iGenCode, String strFunction, String strMessage, UInt32 iSeverity)
   at XSharp.RDD.DBF.Compile(String sBlock)
   at XSharp.RDD.CDX.CdxTag.EvaluateExpressions()
   --- End of inner exception stack trace ---
   at XSharp.RT.Functions.DoError(String cSymFunc, Int32 nTries)
   at XSharp.RT.Functions.DbUseArea(__Usual[] Xs$Args)
   at FoxPro.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\FoxPro\Prg\FoxPro.prg:line 9

[wwbusinessobjects.zip](https://github.com/X-Sharp/XSharpPublic/files/3666327/wwbusinessobjects.zip)

**Comment by RobertvanderHulst** [comment]
This file fails to open because the first tag in the index contains the Visual FoxPro ICASE() runtime function.
After adding the following code to the app it works:
```
FUNCTION ICase(lCond1, uExp1, lCond2, uExp2) as USUAL
    for var nI := 1 to PCount()-1 step 2
        if nI < PCount()
            local cond := _GetFParam(nI) as LOGIC
            if cond
                return _GetFParam(nI+1)
            ENDIF
        endif
    next
    if PCount() % 2 == 1
        return _GetFParam(PCount())
    ENDIF
    RETURN NIL
```

By the way: when the file is really Visual FoxPro then the "DBFVFP" Rdd is recommended, since that also handles collations in indexes.

**Comment by mattslay** [comment]
Note that FoxPro ICASE() function can have MANY sets of lCondX and UExprX.

There are just *2* parameters pairs...  There could be dozens perhaps...

FUNCTION ICase(lCond1, uExp1, lCond2, uExp2, lCond3, uExp3, lCond4, uExp4, lCond5, uExp5, etc, etc, etc) as USUAL

**Comment by mattslay** [comment]
Further... with a FoxPro CDX, practically *ANY* of the FoxPro Functions() can be used, so there may be many more reports of CDX problems once more and more people start trying to use there wild CDX indexes.

**Comment by mattslay** [comment]
Oh yeah, one more thing... in the ICASE() function , there is actually an optional final parameter which is the value that will be returned when none of the preceding conditions are met.

**Comment by cpyrgas** [comment]
Matt, the important point is that this is not a problem, the dbf implementation is fine, it is just a matter of having the necessary function(s) available in the code. Of course all functions need to be implemented.

**Comment by RobertvanderHulst** [comment]
Matt,
The code in my application does nothing with the declared parameters but uses a loop to retrieve the parameters . And yes, I know about the last parameter. This is what I justed checked in:

```
function ICase(lCond1, uExp1, lCond2, uExp2) as usual
    for var nI := 1 to PCount()-1 step 2
        local cond := _GetFParam(nI) as logic
        if cond
            return _GetFParam(nI+1)
        endif
    next
    if PCount() % 2 == 1
        return _GetFParam(PCount())
    endif
    if PCount() >= 2
        var type := UsualType(_GetFParam(2))
        return EmptyUsual(type)
    ENDIF
    return NIL
```
When no conditions are met and the # of parameters is odd, then the last parameter is returned, when the number of parameters is even then it will check the type of the 2nd parameter and return an empty value of the same type.
When the function is called with < 2 parameters then NIL is returned.

And yes, I realize that there are more functions that we need to implement. I have improved the error handling in the RDD, so it will throw an error that makes more sense. The error for this file is now:

```
Description :	Could not compile epression 'IIF(EMPTY(cparent),ckey,cparent)+ICASE(ctype="P","1",ctype="R","9","2")'(error XM0223: ICASE is not a method)
Subsystem :	DBFVFP
GenCode :	EG_SYNTAX Syntax error
SubCode :	1022 Expression for macro compiler incorrect.
FuncSym :	DbUseArea
Severity :	ES_ERROR
FileName :	c:\download\vfp\wwbusinessobjects.dbf

```

**Comment by mattslay** [comment]
Robert - so when a Function is defined accept 4 parameters, as in your code sample, are you saying that you can actually pass *more* parameters to it when you call it? And that doesn't generate a compiler error?

Your ICase() function shows 4 parameters, but I could call it with 7 parameters?

`function ICase(lCond1, uExp1, lCond2, uExp2) as usual`

**Comment by RobertvanderHulst** [comment]
Matt,
Yes. This is what we call the "Clipper Calling convention". 
You can pass in less or more parameters. The parameters will be packaged an an array of Usuals. Inside the function you can use the following pseudo functions:
- PCount() returns the number of actual parameters
- ArgCount() returns the number of **defined** parameters (4 in your example)
- _GetFParam(nNum) returns the value of parameter nNum. VO also had a _GetMParam() for use inside methods, but in X# these two functions do exactly the same.
- _Args() returns the parameter array

**Comment by mattslay** [comment]
That's interesting... in FoxPro, if you pass more parameters than are defined, it will cause a runtime error.

**Comment by RobertvanderHulst** [comment]
Matt
X# will also report an error if the parameters are typed. Functions and methods with untyped parameters can be called with any arbitrary number of parameters. You can also skip parameters ( the will have a Nil value or false in the fox pro dialect). Untyped functions need to check the parameter types, to be safe.
