### ISSUE TITLE
Macrocompiler problem with INT64 and UINT64 values in usual

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#206]
See the last lines in the sample below:

```
FUNCTION Start() AS VOID
	LOCAL oCBTest AS CODEBLOCK
	oCBTest:= MCompile("{ |n| n == 1 }")
	
	// OK:
	? Eval(oCBTest, (INT)1) 	// TRUE
	? Eval(oCBTest, (DWORD)1) 	// TRUE
	? Eval(oCBTest, (SByte)1) 	// TRUE
	? Eval(oCBTest, (BYTE)1) 	// TRUE
	? Eval(oCBTest, (WORD)1) 	// TRUE
	? Eval(oCBTest, (DWORD)1) 	// TRUE
	? &("(INT)1 == (INT64)1")	// TRUE
	
	?

	// Problem:	
	? Eval(oCBTest, (INT64)1) 	// FALSE
	? Eval(oCBTest, (UInt64)1) 	// FALSE

	oCBTest:= MCompile("{ |x,y| x == y }")
	? Eval(oCBTest, (INT64)1 , (INT)1) 	// FALSE
	? Eval(oCBTest, (INT)1 , (UINT64)1) // FALSE	
RETURN
```

**Comment by nvkokkalis** [comment]
I see that the first 2 of the error cases now work correctly. This is probably due to some change Robert did, right?

**Comment by RobertvanderHulst** [comment]
Yes, most likely. I have added a cast to Usual in the macrocompiler to fix the issue that comparing an int with a logic would work. That may have affected this as well. I am now comparing both sides of a binary operation on usual or object types to usual, so the logic in the runtime gets used to decide which operations are allowed and which not.
I also made some other changes:
- when the macro compiler can't resolve a method then it may call a method that was registered by the user in the runtime to decide which overload to use
- when resolving a late bound call the macro compiler was resolving a call to the item method to the item property of the usual type. I am now preventing that.
- I saw an error in a multi threading example where both threads were calling the initialization code of the macro compiler. I have added a lock in the macro compiler to avoid that problem
- PCount() in a macro compiled codeblock was incorrect
- for ambigous methods I am now also including the signature in the error messages
- Some error messages were showing literal characters with double single quotation marks
The biggest thing that I could use your help on is allowing nested codeblocks.
I am now analysing the macro strings in the runtime and converting nested codeblocks to MCompile("{||..}") but it would be better if nested codeblocks are natively supported by the macro compiler. You can also resolve this to a call to Mcompile() if you want.  Right now the macro strings are parsed twice: once in the runtime and once in the macro compiler and that does cost a bit of performance. You can see my solution for nested macros in https://github.com/X-Sharp/XSharpPublic/blob/master/Runtime/XSharp.RT/Functions/Macro.prg and https://github.com/X-Sharp/XSharpPublic/blob/master/Runtime/XSharp.RT/Types/NestedMacros.prg.

**Comment by RobertvanderHulst** [comment]
O, I forgot, I have also added support for strings with block delimiters in the macro compiler.

**Comment by nvkokkalis** [comment]
OK, the comparison was resolving to the Object.Equals() method instead of a normal USUAL comparison. So, I loosed the rules to treat the operands as USUAL, which solves the issue.

**Comment by RobertvanderHulst** [comment]
Nikos,
Do you have a way to inspect the generated il from the macro compiler in the debugger?
I had something like that in the past but can’t remember how I did that.

**Comment by nvkokkalis** [comment]
Since I'm generating the IL, I can examine it at the moment of generation. I know there are some ways to examine the IL of dynamic methods after their creation, but I have not needed them yet. Besides, the relevant stuff is mostly old, from the days of .NET 2.0 (10 years or more). They may still work, though...

**Comment by nvkokkalis** [comment]
Just to give a couple of references on DynamicMethod debugging:
https://blogs.msdn.microsoft.com/haibo_luo/2005/10/25/debuggervisualizer-for-dynamicmethod-show-me-the-il/
https://blogs.msdn.microsoft.com/yirutang/2005/05/26/debugging-lcg/
