### ISSUE TITLE
Problem including native resource

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#208]
The attached solution has a standard manifest for control styles, but it does not seem to get embedded correctly, because when running the app, the buttons in the dialog window appear as "oldschool" visual style. The same recource and manifest in a vulcan project makes them appear with the newer visual styles.

Note that this seems to be a compiler issue, not a VS related one, because the exact same behavior is seen with XIDE and identical X#/vulcan test programs.

[ConsoleApplication24.zip](https://github.com/X-Sharp/XSharpPublic/files/3678953/ConsoleApplication24.zip)

**Comment by RobertvanderHulst** [comment]
Roslyn has several options:
-win32res:<file>              Specify a Win32 resource file (.res)
-win32icon:<file>             Use this icon for the output
-win32manifest:<file>         Specify a Win32 manifest file (.xml)
-nowin32manifest              Do not include the default Win32 manifest
-resource:<resinfo>           Embed the specified resource (Short form: -res)
-linkresource:<resinfo>       Link the specified resource to this assembly
                              (Short form: -linkres) Where the resinfo format
                              is <file>[,<string name>[,public|private]]

To include several resources (including the icon) and also a win32manifest you need to combine these and use -win32res and -nowin32manifest to suppress the default Win32 manifest.
If you only want to include a win32 manifest you use -win32manifest:  but then you also must suppress the default manifest. 
That does not make sense and I will see if I can change that,


To achieve

**Comment by RobertvanderHulst** [comment]
If you add the following line to your XsProj file in the first <propertrygroup> section then this already works:
<NoWin32Manifest>True</NoWin32Manifest>
I will add an option to the X# project system so you can set this option from the UI in the next build.
