### ISSUE TITLE
Problem with the "Creation Date" text added in new files in VS

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#210]
When creating a new file in VS, the date text is always generated in American format, no matter what is the setting in regional options:

// CodeFile1.prg
// Created by    : Cpc
// Creation Date : 10/23/2019 1:59:27 AM <----- should be dd/mm/yyyy
// Created for   : 
// WorkStation   : TheNameOfMyPC

**Comment by RobertvanderHulst** [comment]
Chris,
This is done by VS. And it is documented to be in this format:
The current time in the format DD/MM/YYYY 00:00:00.
See : https://docs.microsoft.com/en-us/visualstudio/ide/template-parameters?view=vs-2019

**Comment by cpyrgas** [comment]
Thanks, that's good enough info to explain to the customer.
