### ISSUE TITLE
VS Form Designer cannot read images in the source taken from Project Reource files

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#213]
- Create a new form project
- In the form, go to the Background Image property and click on the "..."
- The "Select resource" dialog opens, with the "Project resource file" option enabled. Click on the "Import" button below and select an image. The image gets added correctly in the designerand is shown in the form.
- Build and run, the image is shown correctly at rutnime
- Close form and reopen in the designer, now the image is not visible anymore and the Background Image property is empty.

[WindowsFormsApplication43.zip](https://github.com/X-Sharp/XSharpPublic/files/3692669/WindowsFormsApplication43.zip)

**Comment by RobertvanderHulst** [comment]
Fixed
