### ISSUE TITLE
Problem with RddInfo(_SET_AUTOORDER)

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#218]
The following casuses a runtime exception "Specified cast is not valid." due to the call to RddInfo(_SET_AUTOORDER, 0). Please see inline comments

```
FUNCTION Start() AS VOID
	LOCAL cDbf AS STRING
	cDbf := "c:\test\mytest"
	FErase(cDbf + ".cdx")
	DbCreate(cDbf, {{"FLD","N",10,0}})
	DbUseArea(,"DBFCDX",cDbf)
	DbCreateIndex(cDbf , "-FLD")
	DbAppend()
	FieldPut(1,10)
	DbAppend()
	FieldPut(1,20)
	DbAppend()
	FieldPut(1,30)
	DbCloseArea()
	
//	those 2 work fine and give the "expected" result, but it's not how VO works
//	In VO, you must pass numeric 1 to enable auto order and anything else disables it
//	So if you pass either TRUE or FALSE in VO, it actually always disables auto order
	RddInfo(_SET_AUTOORDER, FALSE)
	RddInfo(_SET_AUTOORDER, TRUE)
	
//	this should enable auto order
	RddInfo(_SET_AUTOORDER, 1)
	
//	this should disable auto order
	RddInfo(_SET_AUTOORDER, 0)
	
	DbUseArea(,"DBFCDX",cDbf)
	DbGoTop()
//	should print 10 if auto order is disabled, or 30 if it is enabled
	? FieldGet(1)
	DbCloseArea()
RETURN
```

XSharp.Error
Specified cast is not valid.

Callstack : 
static Object XSharp.RT.Functions.DoError(System.String cSymFunc, System.Int32 nTries)() 
static Boolean XSharp.RT.Functions.DbUseArea(XSharp.__Usual[] Xs$Args)() 
static System.Void xRuntime.Exe.Functions.Start()()   :  C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg  :  31

**Comment by RobertvanderHulst** [comment]
Vulcan uses logical values. I checked in VO and _SET_AUTOSHARE also expects a 0 and 1 value.
Will change this in the next build.
