### ISSUE TITLE
Preprocessor stops reading source after warnings (?)

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#219]
For the following code, the compiler reports some warnings about duplicate #defines, but apparently stops processing the code after some point, because the Start() function at the end is not parsed (ad syntax errors are not reported), instead the compiler reports error XS1558: 'Functions' does not have a suitable static Start method

```
#define BGFFCO_NONE 0x00000000U
#define BGFFCO_ALLCOLUMNS 0x00000001U
#define BGFFCO_OPENCOLUMNS 0x00000002U
#define BGFFCO_FORMAT_AUTOEDIT 0x00000004U
#define BGFFCO_FORMAT_EDITABLE 0x00000008U
#define BGFFCO_FORMAT_EDITCLOSEFLAGS 0x00000010U
#define BGFFCO_FORMAT_EDITSTARTFLAGS 0x00000020U
#define BGFFCO_FORMAT_FIELDSPEC 0x00000040U
#define BGFFCO_FORMAT_HEIGHTVARIABLE 0x00000080U
#define BGFFCO_FORMAT_MOVABLE 0x00000100U
#define BGFFCO_FORMAT_RESIZABLE 0x00000200U
#define BGFFCO_FORMAT_SELECTABLE 0x00000400U
#define BGFFCO_FORMAT_TOOLTIPTEXT 0x00000800U
#define BGFFCO_FORMAT_WIDTH 0x00001000U
#define BGFFCO_FORMAT_WIDTHMAX 0x00002000U
#define BGFFCO_FORMAT_WIDTHMIN 0x00004000U
#define BGFFCO_FORMAT_DATAVIEW 0x00008000U
#define BGFFCO_FORMAT_SUSPENDEMPTYVALUES 0x00010000U
#define BGFFCO_FORMAT_TEXTFORMAT 0x00020000U
#define BGFFCO_FORMAT_VALUETRANSFORMLIST 0x00040000U
#define BGFFCO_FORMAT_VIEWEMPTYVALUEAS 0x00080000U
#define BGFFCO_FORMAT_VIEWVALUEAS 0x00100000U
#define BGFFCO_FORMAT_CAPTION 0x00200000U
#define BGFFCO_FORMAT_CAPTIONVIEW 0x00400000U
#define BGFFCO_FORMAT_CAPTIONVISIBLE 0x00800000U
#define BGFFCO_FORMAT_FOOTER 0x01000000U
#define BGFFCO_FORMAT_FOOTERVIEW 0x02000000U
#define BGFFCO_FORMAT_FOOTERVISIBLE 0x04000000U
#define BGFFCO_FORMATSETTINGS_GENERAL 0x00007FFCU
#define BGFFCO_FORMATSETTINGS_DATA 0x001F8000U
#define BGFFCO_FORMAT_CAPTION 0x00200000U
#define BGFFCO_FORMAT_CAPTIONVIEW 0x00400000U
#define BGFFCO_FORMAT_CAPTIONVISIBLE 0x00800000U
#define BGFFCO_FORMATSETTINGS_CAPTION (BGFFCO_FORMAT_CAPTION+BGFFCO_FORMAT_CAPTIONVIEW+BGFFCO_FORMAT_CAPTIONVISIBLE)
#define BGFFCO_FORMAT_FOOTER 0x01000000U
#define BGFFCO_FORMAT_FOOTERVIEW 0x02000000U
#define BGFFCO_FORMAT_FOOTERVISIBLE 0x04000000U
#define BGFFCO_FORMATSETTINGS_FOOTER (BGFFCO_FORMAT_FOOTER+BGFFCO_FORMAT_FOOTERVIEW+BGFFCO_FORMAT_FOOTERVISIBLE)
#define BGFFCO_FORMAT_CAPTION 0x00200000U
#define BGFFCO_FORMAT_CAPTIONVIEW 0x00400000U
#define BGFFCO_FORMAT_CAPTIONVISIBLE 0x00800000U
#define BGFFCO_FORMAT_FOOTER 0x01000000U
#define BGFFCO_FORMAT_FOOTERVIEW 0x02000000U
#define BGFFCO_FORMAT_FOOTERVISIBLE 0x04000000U

CLASS InvisibleClass
END CLASS


this does not get parsed at all
FUNCTION Start() AS VOID
IF
RETURN
```

**Comment by RobertvanderHulst** [comment]
Chris,
The IF statement without condition, body and endif causes the FUNCTION rule to completely abort. 
The Start() entity is therefore not generated, but the InvisibleClass is.

I have added a limit to the # of errors returned from the compiler, like you suggested.
The error "Unexpected CRLF, are you missing a token' which is normally generated for the IF line is therefore now shown.
I think it is better if I rollback the change limits the # of errors produced by the compiler, so at least the error on the IF line will also be shown.

**Comment by cpyrgas** [comment]
Hmm, so this was a red herring, masking the problem I was seeing, will send you a solution to have a look. 

Btw, just to be completely clear, I only meant to limit the of _preprocessor_ only errors reported, for the _same_ file, not in general. But I guess the way I constructed this sample did not help, will send the complete solution in pm.

**Comment by RobertvanderHulst** [comment]
Chris,
With the changes Nikos did I am now seeing an error in bRtfDocument on line 133: ENDIF expected.
The problem is the PROTECT loFunctionPointer AS IntPtr on line 134. This should be  a LOCAL I think.
The compiler "thinks" that the PROTECT line is a new class member and aborts the compilation of __SetValue. After that change it compiles with the exception of the creation of the Deleate, because the prototype of the delegate is missing the PTR keyword for 2 parameters

**Comment by cpyrgas** [comment]
Oh, right, I could not spot this problem before, without the help from the compiler. OK, I think it's good now then.
