### ISSUE TITLE
Editor tooltips blinking in VS

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#225]
Editor tooltips blink a lot, appearing, disappearing and appearing again. For example in the code below, hover with the mouse over "SELF". The tooltip gets displayed, than after half a second it hides and another half second later it is displayed again and remains visible. Some times it does display correctly only once, bt most of the times it blinks.

FUNCTION Start() AS VOID STRICT

CLASS TestClass
	CONSTRUCTOR()
		SELF:ToString()
END CLASS

**Comment by RobertvanderHulst** [comment]
Which VS version ?
Ms has changed the "quickinfo" implementation in one of the VS 2017 builds from synchronous to asynchronous. We use the synchronous approach because that's the only thing that works in VS 2015. 

Ideally after we drop support for VS 2015 we can switch to "asynchronous" tooltips and get rid of this.

Robert

**Comment by cpyrgas** [comment]
Ok sounds good! Just for completion, this is the output of the debug window:

10:32:08.419 XSharp.QuickInfoSource :Triggerpoint: 71
10:32:08.419 XSharp.Codecompletion :--> FindIdentifier in TEstClass, SELF 
10:32:08.419 XModel.SourceWalker -->> Parse() C:\Users\Cpc\source\repos\ConsoleApplication25\ConsoleApplication25\Program.prg(# lines 2 locals True )
10:32:08.419 XModel.SourceWalker <<-- Parse() C:\Users\Cpc\source\repos\ConsoleApplication25\ConsoleApplication25\Program.prg
10:32:08.419 XModel.Project ConsoleApplication25 Lookup() TEstClass
10:32:08.419 XModel.Project ConsoleApplication25 Lookup()  found: TEstClass
10:32:08.419 XModel.Project ConsoleApplication25 Lookup() TEstClass
10:32:08.419 XModel.Project ConsoleApplication25 Lookup()  found: TEstClass
10:32:08.419 XSharp.QuickInfoSource :Found new help content: System.Windows.Documents.Inline[]
10:32:08.731 XSharp.QuickInfoSource :Triggerpoint: 71
10:32:08.731 XSharp.QuickInfoSource :Return last help content: System.Windows.Documents.Inline[]
