### ISSUE TITLE
Too many parser errors, part 2

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#226]
The following sample has one small syntax error (a ";" missing in one of the first lines) and produces 57 parser errors. In the actual code (longer file) where this is taken form, it was producing literally thousands of errors.

Maybe you can look into it, too, but I think a general solution is needed, because even if this specific case is improved, I assume there will be many others still causing the same problem. 

What I have done in XIDE is to read all the errors from the compiler and when there are two or more XS9002 errors, then display only one per file. Do the same for every other file. Also for error  XS1003, display only one per prg file. ALL other errors and warnings are always presented to the user unfiltered. This seems to be working perfectly, showing the user only what matters. Unless there are cases when the one _helpful_ parser error will not be the first parser error of the file?

```
CLASS Testing

	METHOD Test() 
		
		a := {1, 
		}
		
		DBUpdates:Close()
		IF ! File("abc.dbf")
			IF DbCreate("abd",AStruct, "DBFCDX", TRUE,,,FALSE)
				DbCloseArea()
				DbCreateIndex(e"abd", e"def", , )
				DbCloseArea()
			ENDIF
		ENDIF
		
		DBUpdates :=  DBServer{"Updates",TRUE, FALSE,,}
		DBUpdates:Locate("alltrim(Version)==1")
		
		IF DBUpdates:EoF
			SELF:oMD:Caption := "mycaption"
			FErase("Temp1.dbf")
			DBUpdates:Append()
			DBUpdates:Version:="UPDATE"
			DBUpdates:Update :=Today()
		ENDIF
		DBUpdates:Close()
	RETURN NIL
	
END CLASS
```

C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(5,12): error XS9002: Parser: unexpected CRLF, are you missing a  token ?
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(6,3): error XS9002: Parser: unexpected input '}'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(8,12): error XS9002: Parser: mismatched input ':' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(8,18): error XS9002: Parser: mismatched input '(' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(9,3): error XS9002: Parser: unexpected input 'IF'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(9,12): error XS9002: Parser: mismatched input '(' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(10,4): error XS9002: Parser: unexpected input 'IF'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(10,15): error XS9002: Parser: mismatched input '(' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(10,31): error XS9002: Parser: mismatched input '"DBFCDX"'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(10,41): error XS9002: Parser: mismatched input 'TRUE'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(10,46): error XS9002: Parser: mismatched input ','
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(10,47): error XS9002: Parser: mismatched input ','
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(10,48): error XS9002: Parser: mismatched input 'FALSE'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(11,16): error XS9002: Parser: mismatched input '(' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(12,18): error XS9002: Parser: mismatched input '(' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(13,16): error XS9002: Parser: mismatched input '(' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(14,4): error XS9002: Parser: unexpected input 'ENDIF'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(15,3): error XS9002: Parser: unexpected input 'ENDIF'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(18,12): error XS9002: Parser: mismatched input ':' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(18,19): error XS9002: Parser: mismatched input '(' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(20,3): error XS9002: Parser: unexpected input 'IF'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(20,15): error XS9002: Parser: mismatched input ':' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(21,4): error XS9002: Parser: unexpected input 'SELF'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(21,12): error XS9002: Parser: mismatched input ':' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(22,10): error XS9002: Parser: mismatched input '(' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(23,13): error XS9002: Parser: mismatched input ':' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(23,20): error XS9002: Parser: mismatched input '(' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(24,13): error XS9002: Parser: mismatched input ':' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(25,13): error XS9002: Parser: mismatched input ':' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(26,3): error XS9002: Parser: unexpected input 'ENDIF'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(27,12): error XS9002: Parser: mismatched input ':' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(27,18): error XS9002: Parser: mismatched input '(' expecting EOS
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(28,2): error XS9002: Parser: unexpected input 'RETURN'
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(8,3): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(8,13): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(9,8): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(10,7): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(10,22): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(11,5): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(12,5): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(13,5): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(17,3): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(18,3): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(18,13): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(20,6): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(20,16): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(21,9): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(21,13): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(22,4): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(23,4): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(23,14): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(24,4): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(24,14): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(25,4): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(25,14): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(27,3): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg(27,13): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected

**Comment by RobertvanderHulst** [comment]
Fixed.
The error handler that Nikos created was recursive when there is more than one error in the block. In this case the single curly brace will be seen as a second error. I have seen situations where this recursion would lead to stack errors, so I prevented it from recursing, and this was having this side effect. I am now allowing it to recurse 25 times, so it will report 25 error properly and then abort. After the change the errors reported are now:

```
Start.prg(5,12): error XS9002: Parser: unexpected CRLF, are you missing a  token ?
Start.prg(6,3): error XS9002: Parser: unexpected input '}'

```
