### ISSUE TITLE
Compiler loop in Bandol 2.08

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#227]
This code keeps the compiler in an endless loop:

```
function CompilerCheck() as void
	local sum 			as long
	sum := 0
	return
```
Wolfgang

**Comment by RobertvanderHulst** [comment]
Wolfgang,
Thanks for reporting. This seems to be a side effect of the SUM UDC in dbcmd.xh. This should not happen of course, since the SUM UDC is looking to a TO keyword after SUM. Your code does not have this keyword, so it should not preprocess this.

**Comment by RobertvanderHulst** [comment]
Oh, renaming the variable will fix this for now.

**Comment by wriedmann** [comment]
Hi Robert,
I don't know how many people has such variable names in their code - but I suspect many. I don't use this normally (I'm used to write nSum) - it is code moved over from C#.  
And maybe other keywords are affected too.
It took me a while to find it out.
Maybe it is better to release a 2.08a or 2.09.
Wolfgang

**Comment by cpyrgas** [comment]
Robert, is now dbcmd.xh automatically included in every app? Because I was getting that problem also in prg files that did not have an #include to that file.

**Comment by cpyrgas** [comment]
Oh I see, there's an include for it inside XSharpDefs.xh. Ok, that's good, so it can all be enabled or disabled at will with just one compiler option.

**Comment by RobertvanderHulst** [comment]
Wolfgang,
You can solve the problem by "patching" dbcmd.xh. The SUM udc should start with 
`#command SUM  <x1> [, <xn>]  TO  <v1> [, <vn>]                          ;`
Note that there was originally an open bracket before `<x1>` and a second closing bracket after `<vn>`

**Comment by RobertvanderHulst** [comment]
I have also fixed this in the preprocessor. See cdadcb01525360cb165f7da4081f36b2d9424130
