### ISSUE TITLE
The X# RDD corrupts DBFCDX tables with memo fields when used with VO

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#233]
After suspecting that for several times, we have been able to reproduce that.
You need the following: 
- a VO application
- a X# application
- a DBFCDX table with memo fields
The following steps lead to the corruption:
1) open the table with the X# application
2) change a record in the table (any change is enough, but a change is needed
3) open the table with the VO application
4) add a record in the VO application
5) close the database in the VO application
6) close the vo application
7) close the database in the X# application
8) close the X# application
After that the record added in step 4 is not more present in the table.

**Comment by cpyrgas** [comment]
Confirmed, can be reproduced also with just 2 separate X# programs. Run #1 below, then when prompted run #2, which appends a record to the same dbf. No continue back to #1, indeed the new record is not visible. 

The index file does not seem to have an impact, problem happens also with it. it also happens without a memo field, but I have included both in the samples, just in case.


```
// app #1
FUNCTION Start() AS VOID
	LOCAL cDbf AS STRING
	cDbf := "c:\test\testVO"
	RddSetDefault("DBFCDX")
	DbCreate(cDbf, {{"CFIELD","C",10,0},{"MFIELD","C",10,0}})
	FErase(cDbf+ ".cdx")
	DbUseArea(TRUE,  , cDbf)
	DbCreateIndex(cDbf, "CFIELD")
	DbAppend()
	FieldPut(1,"asdf")
	FieldPut(2,"efgh")
	DbAppend()
	FieldPut(1,"ADJKSHA")
	FieldPut(2,"YUWED")
	DbCloseArea()
	
	DbUseArea(TRUE, , cDbf , , TRUE)
	RLock()
	FieldPut(1 , "aaaaa")
	? "Records in dbf", RecCount()
	WAIT "Now append a record from another app and press enter"
	DbCloseArea()
	
	DbUseArea(TRUE, , cDbf , , TRUE)
	? "Records in dbf", RecCount()
	DbCloseArea()
RETURN
```


```
// app #2, run when prompted
FUNCTION Start( asCmdLine AS STRING[] ) AS VOID
	LOCAL cDbf AS STRING
	cDbf := "c:\test\testVO"
	RddSetDefault("DBFCDX")
	DbUseArea(TRUE, , cDbf , , TRUE)
	? "Records in dbf", RecCount()
	DbAppend()
	FieldPut(1,"new")
	FieldPut(2,"newer")
	? "Records in dbf after Append()", RecCount()
	DbCloseArea()
	WAIT "program finished, now check records in first app"
RETURN
```

**Comment by cpyrgas** [comment]
Oh, don't bother with the above, it can be reproduced also in a single program:


```
FUNCTION Start() AS VOID
	LOCAL cDbf AS STRING
	cDbf := "c:\test\testVO"
	RddSetDefault("DBFCDX")
	DbCreate(cDbf, {{"CFIELD","C",10,0}})
	FErase(cDbf+ ".cdx")
	DbUseArea(TRUE,  , cDbf)
	DbAppend()
	FieldPut(1,"asdf")
	DbAppend()
	FieldPut(1,"ADJKSHA")
	DbCloseArea()
	
	DbUseArea(TRUE, , cDbf , "alias1" , TRUE)
	alias1->RLock()
	alias1->FieldPut(1 , "aaaaa")
	? "Records in dbf", alias1->RecCount() // 2, OK


		DbUseArea(TRUE, , cDbf , "alias2" , TRUE)
		? "Records in alias2", alias2->RecCount() // 2, OK
		alias2->DbAppend()
		alias2->FieldPut(1,"new")
		? "Records in alias2 after Append()", alias2->RecCount() // 3, OK
		alias2->DbCloseArea()
	

	alias1->DbCloseArea()
	
	DbUseArea(TRUE, , cDbf , , TRUE)
	? "Records in dbf", RecCount() // 2, should be 3
	DbCloseArea()
RETURN
```

**Comment by wriedmann** [comment]
Hi Robert,
could you try to fix this as soon as possible, please? We have data losses in production apps.
Thank you very much!
Wolfgang

**Comment by RobertvanderHulst** [comment]
Wolfgang 
Will look at this asap. However a conference is not the right place to do this kind of coding....

**Comment by wriedmann** [comment]
I know.... Thank you very much and good flight back!

**Comment by wriedmann** [comment]
I don't know if this is connected to this issue:
`FUNCTION Start() AS VOID
            LOCAL cDBF AS STRING
            LOCAL oDBF1 AS Vo.DbServer
            LOCAL oDBF2 AS Vo.DbServer

            cDbf := "c:\temp\testVO"
            FErase(cDbf+ ".cdx")
            FErase(cDbf+ ".dbf")

            RddSetDefault("DBFCDX")
            DbCreate(cDbf, {{"CFIELD","C",10,0}})
            DbUseArea(TRUE,  , cDbf)
            DbCreateOrder("CFIELD", cDbf, "CFIELD", &( "{|| CFIELD}" ),)

            DbAppend()
            FieldPut(1,"AAAA")
            DbCommit()
            DbAppend()
            FieldPut(1,"BBBB")
            DbCommit()
            DbCloseArea()
                        
            ? "TestDB"  
            oDBF1  := Vo.DbServer{ cDbf + ".dbf", TRUE, FALSE, "DBFCDX" }
            oDBF2  := Vo.DbServer{ cDbf + ".dbf", TRUE, FALSE, "DBFCDX" } 
            //odbf2:SetOrder( 0 ) // without order no missing record during while
            
            oDBF1:Append()
            oDBF1:FieldPut( 1, "CCCC" ) 
            oDBF1:Commit()
            oDBF1:Close()
            oDBF1  := null_object
            
            ? "DBF2"  
            oDBF2:GoTop()
            WHILE ! oDBF2:EoF
                        ? oDBF2:FieldGet( 1 ) 
                        oDBF2:Skip()
            ENDDO
            //? oDBF2:FieldGet( 1 )             // record found after EoF
            oDBF2:Close()
            
            ? ""
            ? "DBF2 New"  
            oDBF2  := Vo.DbServer{ cDbf + ".dbf", TRUE, FALSE, "DBFCDX" } 
            oDBF2:GoTop()
            WHILE ! oDBF2:EoF
                        ? oDBF2:FieldGet( 1 ) 
                        oDBF2:Skip()
            ENDDO
            oDBF2:Close()
            
            RETURN`
VO behaves correctly here.
Wolfgang

**Comment by RobertvanderHulst** [comment]
Wolfgang,
Ok, I can reproduce the problems and I am looking into it. It has to do with the fact that the second area does not "see" that the index file was updated and therefore it does not reload the index from disk.
