### ISSUE TITLE
Why does Type() function return "UE" when it should be "L"

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#240]
In this code, a local LOGIC var is created from the return of the File() function, but then when you test the data type of lFound, it returns "UE" which means "Error syntactical" according to the online Runtime help, but yet it return be "L" for Logic

`

	Local oObject = myNS.MyFirstClass{} As myNS.MyFirstClass
	
	Local lFound = File(oObject.cDbfName) As Logic
	
	If lFound
		? "File found: " + oObject.cDbfName
	else
		? "File NOT found: " + oObject.cDbfName
	Endif
	
	
	?Type("lFound")
	Wait
	

`

![2019-10-21_12-02-03](https://user-images.githubusercontent.com/309016/67226606-f5a33c00-f3fa-11e9-932f-28deafead7e0.png)

**Comment by RobertvanderHulst** [comment]
Matt,
This makes perfect sense. Locals are not visible to the Type() function. That is the whole idea of Locals, so you can be sure that a function that you are calling cannot corrupt your locals.
Dynamic memory variables (Private & Public) ARE visible to Type().

**Comment by mattslay** [comment]
That's fine, and I get it, but it is also not how FoxPro code operates. So, I guess just get ready to deal with this issue, somehow, when people begin to throw existing VFP code against X#.

```
Local cName

cName = "Matt"

?Type("cname") && Prints "C" in FoxPro
```

**Comment by mattslay** [comment]
I get that custom functions I write or include from a non-native libraries should not be able to change, or even see Local vars, but I'd think that official X# RunTime functions should at least get read-only access to Local vars.  I guess that is the mechanism that must be at work presently in the VFP language.

It will be interesting to see if we find other VFP Functions() that become affected this way.

**Comment by RobertvanderHulst** [comment]
X# runtime functions ARE normal functions. There is no way they could get access to local vars. That would violate all rules of normal programming.
The FoxPro help says the following about locals:

```
You can use and modify local variables and variable arrays only within the procedure or function in which they are created and cannot be accessed by higher or lower-level programs. After the procedure or function containing the local variables and arrays completes execution, local variables and arrays are released.
```
So if the Type() function can access the local then the FoxPro runtime is violating its own rules.

**Comment by cpyrgas** [comment]
Robert, unless Type() is only sort of an intrinsic function in VFP?

**Comment by RobertvanderHulst** [comment]
I suspect that LOCAL variables in FoxPro are implemented as "special" dynamic memory variables with limited scope. That also explains why they both "listen" to the `M.VarName` syntax

**Comment by RobertvanderHulst** [comment]
Fixed
