### ISSUE TITLE
Incorrect namespace handling by the compiler

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#241]
See the following sample, for the 3rd class, it somehow resolves it to the NS3.TestClass3 class, but the namespace of this class in not specified nor implied anywhere, so it should be a compiler error reported.

If the namespace/declaration is moved to another file, then the compiler does correctly report an error also for this.

```
FUNCTION Start() AS VOID
	LOCAL o1 AS TestClass1 // no error, corect!

	LOCAL o2 AS TestClass2 // error, correct!

	LOCAL o3 AS TestClass3 // No Error! Should be an error, we are not inside the NS3 namespace
RETURN

CLASS TestClass1
END CLASS

CLASS NS2.TestClass2
END CLASS

BEGIN NAMESPACE NS3
	CLASS TestClass3
	END CLASS
END NAMESPACE
```

**Comment by RobertvanderHulst** [comment]
Chris,
At this moment the parser adds an automatic USING <namespace> for the file where BEGIN NAMESPACE <namespace> is found. That is why this code compiles. When I remove that then several of our test cases, such as C063 and C564 fail to compile.
So what should we do ?
I think we better leave this the way it is.

**Comment by cpyrgas** [comment]
Robert, OK, understood! I think it's definitely still wrong behavior though, so I think just mark it as a known issue that will not be fixed.
