### ISSUE TITLE
Foxpro - argument skipping

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#243]
The value of the skipped param is .f. and ValType( b) shows correctly "L",  but Type ( "b" ) returns "O" instead of "L" 

```
// 1. <Foxpro> dialect
//
// 2. used compiler switches: 
//    -memvar+  -undeclared+  
// 


FUNCTION Start() AS VOID 

 	Test ( 1 , , "test" ) 	
 	
	RETURN

FUNCTION Test  
PARAMETERS a , b , c  

? b   // ok, .f. 
? Type ( "b" )  // "O" instead of "L"
? ValType ( b ) // ok, "L" 

// ? "a" , a , Type ( "a" ) , ValType ( a ) 
// ? "c" , c , Type ( "c" ) , ValType ( c )
        
RETURN .t.


```

**Comment by RobertvanderHulst** [comment]
Karl Heinz,
Yes the type() function is a bit complicated here, just like when you take the type of a local.
In VO we would check for IsNil(b) and this should return TRUE if you have skipped it.
At this moment we compile the "skipped" variables into a USUAL with a property "Initialized" = FALSE and a value of FALSE (FoxPro dialect) and VOID (other dialects). IsNil() checks for the "initialized" flag.
You can see this flag in the debugger as well when you change PARAMETERS to LPARAMETERS. Unfortunately we can't show you the Dynaimic Memory variables in the debugger at this moment.
If you want to see them in the debugger add a watch with the valuie "XSharp.MemVar".
If you open that watch you will see 2 important properties:
Publics, which is a list of all the publics, and Privates which is a list of the private "scopes" and inside each scope you see the privates that were declared or created at that level.
Each level has a collection of NAME - Variable pairs (called Variables). Each variable is a combination of a name (a string in uppercase) and a value (the actual USUAL). You should see that the variables A and C are initialized and B is not initialized.
