### ISSUE TITLE
Implement "EMPTY" class for [FoxPro]

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#244]
The current `CUSTOM` class in X#.VFP has several properties on it that are undesirable if one needs a truly *empty* class to use for DTO purposes (no properties on it at all).  In native FoxPro they have the `EMPTY` class for this usage.  You cannot even subclass from Empty with Define Class. The only way you can add properties to an instance of it is with the AddProperty() function.

We need this in X#.VFP please.

See code example here:

```
loData = CreateObject("Empty")

AddProperty(loData, "FirtName", "Matt")
AddProperty(loData, "State", "Alabama")

```

**Comment by lazy-fox** [comment]
Seconding Matts description of need and usage.
The Empty Object does not even have the "typical" vfp members Class, BaseClass, ParentClass or Name - which is 1 of the quick checks if it really is an "Empty Object", safest but more costly is checking for absence of methods. 
There is no reason to fear any name clashes with existing properties or methods, as only AddProperty Function or Scatter Name [additive] will modify Object signature/footprint.

**Comment by RobertvanderHulst** [comment]
At this moment the AddProperty() and RemoveProperty() methods are declared as public. 
We will change that so the class is really empty.
The only methods that will remain are NoIVarGet() and NoIVarPut() which are the support methods that X# uses for late bound property access, but we may be able to make these Private as well so the class will look just like the VFP Empty class.
