### ISSUE TITLE
Implement CREATE CURSOR command [FoxPro]

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#247]
Command needed: `CREATE CURSOR`

In FoxPro, it is very common to create a local working cursor from scratch (no DBF), and then we can use all the regular Xbase commands like `Scan`, `Locate`, `Append`, `Replace`, etc in the Work Area for data processing, screen display, report generation, save to DBF, etc. 

Note: This is a **Runtime** command that is common to use in production apps, so it should be viewed differently than `CREATE FORM`, or `CREATE REPORT`, and many other of the `CREATE` commands.

See below a code sample.  Note that the cursor name (MyCursor) can be wrapped in quotes, or it can be just typed as a name without quotes.

```

CREATE CURSOR MyCursor ;
  ( staff_no CHAR(6) NOT NULL, ;
    lastname CHAR(15) NOT NULL, ;
    firstname CHAR(10), ;
    hiredate DATE, ;
    location CHAR(15), ;
    supervisor CHAR(6), ;
    salary DECIMAL(6,0), ;
    picture VARBINARY, ;
    history VARCHAR(50), ;
    commission DECIMAL(4,1) ;
  )
```

See FoxPro HELP file for full info `CREATE CURSOR`
 
![2019-10-28_10-29-34](https://user-images.githubusercontent.com/309016/67692275-eded1580-f96d-11e9-9edc-2784aad4be44.png)

**Comment by RobertvanderHulst** [comment]
This requires:
- Support from the compiler to detect certain SQL statements
- Runtime support to translate this to creating a workarea etc.
