### ISSUE TITLE
Compiler error for SELECT command with Macro Substitution  [FoxPro]

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#250]
See code below for testing the `SELECT` command. Cases 1 through 4 work just fine, but I get 2 compiler errors with Case 5, but in VFP that case works just fine.

`Select &lcAlias1`

> Error 1:  XS0019	Operator '&' cannot be applied to operands of type 'method' and 'string'	
> Error 2:  XS0201	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement
> 

Run this code in VFP and you will see that they all run and do what the in-line comments say they will, but paste this code in X#.VFP and you will get a compiler error for Case 5.

```
Local lcAlias1, lcAlias2, lcDBF

lcDBF = "C:\Work\LM5\AppData\wwBusinessObjects.DBF"

Close Databases && Close all open Work Areas
Clear
Use (lcDBF) Alias "WA1" Shared In 0

Use (lcDBF) Alias "WA2" Again Shared In 0

lcAlias1 = "WA1"
lcAlias2 = "WA2"

Clear  && Clears VFP IDE desktop area

*-- In the code below, I alternate between WA1 and WA2 using various code techniques to show how
*-- VFP works with the Select() function

*-- Case 1
*-- Using a string literal
Select WA2
? Alias() && Prints/Returns "WA2"
? Select() && Prints/Returns 2 (integer)

*-- Case 2
*-- Using a string literal
Select "WA1"
? Alias() && Prints/Returns "WA1"
? Select() && Prints/Returns 1 (integer)

*-- Case 3
*-- Using integer value
Select 2
? Alias() && Prints "WA2"
? Select() && Prints/Returns 2 (integer)

*-- Case 4
*-- Using a string var that references an alias name
Select (lcAlias1)
? Alias() && Prints/Returns "WA1"
? Select() && Prints/Returns 1 (integer)

*-- Case 5
*-- Causes Compiler Error in X#, works in VFP
*-- Using Macro Substition
Select &lcAlias1
? Alias() && Prints "WA1"
? Select() && Prints/Returns 1 (integer)
```

![2019-10-28_13-32-02](https://user-images.githubusercontent.com/309016/67706870-8c39a500-f987-11e9-9885-ced51aed25e2.png)

**Comment by RobertvanderHulst** [comment]
Most likely this can be fixed with a small change to a UDC

**Comment by mattslay** [comment]
Please add FoxPro tag to this Issue.
