### ISSUE TITLE
VO-xPorter 2.0.0.0 System.OutOfMemoryException

### ISSUE THREAD

**Issue by JamalAPI** [X-Sharp/XSharpPublic#252]
Environment: VS Pro 2019. Version 16.3.7
X# version 2.08a.
Windows 10 Pro 64bit, 16.0 GB (available 8.3GB)

May be I pushed it to the limit. I was XPorting 317 AEFs in one step.

![xPorter_OutOfMemoryException](https://user-images.githubusercontent.com/35046731/67878694-2168a500-fb12-11e9-9f6c-a3247f851d73.png)

Xport 

`
************** Exception Text **************
System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at System.String.Split(String[] separator, Int32 count, StringSplitOptions options)
   at ApplicationDescriptor.AddModule(String cName, String cCode)
   at ApplicationDescriptor.CreateFromAef(String cAefFile, VOProjectDescriptor oProject, String cAppName)
   at xPorter.xPort_AppsFromAefsInFolder(String cSourceFolder, String cOutputFolder, String cSolutionName)
   at xPorterUI.xPortButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
VOXPorter
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.8.1
    CodeBase: file:///C:/Program%20Files%20(x86)/XSharp/VOXPorter/VOXporter.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4001.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
SDK_Defines
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/XSharp/VOXPorter/SDK_Defines.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4018.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3752.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
Fab_VO_Entities
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.8.1
    CodeBase: file:///C:/Program%20Files%20(x86)/XSharp/VOXPorter/Fab_VO_Entities.DLL
----------------------------------------
XIRES
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/XSharp/VOXPorter/XIRES.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
`

**Comment by cpyrgas** [comment]
Hi Jamal,

Yeah, indeed I was not anticipating VOXporter to be used against 317 aefs in one go :), but still I would not expect it to run out of memory either. Maybe something in the aef reading library is using memory that it never releases. Please try exporting those again, while having the task manager open, so you can see live how much memory VOXporter uses. Does it always go up, without reducing (GC kicking-in) at all at any time? And how much memory does it use when it fails?

**Comment by JamalAPI** [comment]
Hi Chris,

The memory kept going up until about 1477 MB and it keeps working at around this level, then it crashes.

**Comment by cpyrgas** [comment]
OK, thanks! I could not reproduce it here, the GC always kicks in and does not allow memory to go higher, but there is probably something specific in one of your aefs that it cannot handle. I will look into improving memory consumption, it shouldn't be going that high in the first place. 

But in any case, even when VOXporter handles it, I hope you will not try to open the solution containing all 317 projects! :)

**Comment by RobertvanderHulst** [comment]
We will not fix this

**Comment by JamalAPI** [comment]
It's better to say you cannot duplicate and close the issue rather than say "We will not fix this"!

**Comment by cpyrgas** [comment]
Jamal, I think what Robert means is that since this is such an extremely edge case scenario (well, 300+ projects in one solution! :)), it's difficult to justify putting much effort on it. Maybe it would be better to actually not allow VOXporter to port such huge solutions, because it would then cause all sorts of problems opening this anyway.

Btw, have you had any trouble with porting a smaller amount of your projects in one go?

**Comment by JamalAPI** [comment]
Chris, 
It works with smaller number of projects. Honestly, all I am doing now is testing X# and contributing via bugs reports as much as I can, even donating a small amount to the X# efforts. It's just the response is not positive in nature when I showed that there is definitely a bug. Anyway, it's all up to you guys.

**Comment by RobertvanderHulst** [comment]
Jamal,
Sorry my comment was a bit too harsh. But seriously converting 317 aefs is a bit too much.
When given the choice I'd rather see Chris work on something that affects more people.

**Comment by JamalAPI** [comment]
Ok. Case is closed.
