### ISSUE TITLE
Error XS9999 An internal compiler error has occurred

### ISSUE THREAD

**Issue by JamalAPI** [X-Sharp/XSharpPublic#253]
VS Pro 19.3.7
X# 2.08a

I xPorted the bServer Classes (Source Code) which is part of the bBrowser 4.0 library, upon compiling I got the following error:

Error XS9999	An internal compiler error has occurred: 'Unable to cast object of type 'LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.EmptyStatementSyntax' to type 'LanguageService.CodeAnalysis.XSharp.Syntax.InternalSyntax.ExpressionSyntax'.',    at LanguageService.CodeAnalysis.XSharp.SyntaxParser.RuleExtensions.Get[T](IXParseTree t) in C:\XSharp\Dev\XSharp\src\Compiler\XSharpCodeAnalysis\Parser\XSharpParserCode.cs:line 951	bServer Classes	C:\XporterOutput\bServer Classes\bDBServer (Server).prg	1	

Clicking the error, it point to:

`class bDBServer inherit DBServer

![2019-10-30_13-23-47](https://user-images.githubusercontent.com/35046731/67882426-9ccd5500-fb18-11e9-8bb5-34b3146ce82f.png)
`

**Comment by cpyrgas** [comment]
Jamal, can you please zip and send me the solution exactly as is now, so I can try to reproduce the problem? Please do not upload here,as it is a 3rd party code.

Btw, you will not need to port the bBrowser code yourself, I have been in very close contact with Joachim the last days, we're working on some final details and the X# version of bBrowser is almost finished now. I think it's only a matter of days now for Joachim to officially release it. But still, of course we should find and fix what's causing the internal compiler error.

**Comment by JamalAPI** [comment]
Please check your email.

**Comment by cpyrgas** [comment]
Jamal, sorry I did not receive it, to which address did you send it? Please use chris@xsharp.eu or maybe better info@xsharp.eu so Robert has access to the sample as well.

**Comment by JamalAPI** [comment]
Sorry, email was stuck on Outbox. Resent to both.

**Comment by cpyrgas** [comment]
Thanks Jamal, got it now, problem is because the class bDBServer has a DESTRCTOR() which ends with "return super:Axit()", the compiler does not handle this well. If you remove that line, it will compile and report regular errors.

Robert, repro codefor this problem: 

// /vo1+ enabled
CLASS TestClass
	DESTRUCTOR()
	RETURN SUPER:Axit() // ICE here
END CLASS

**Comment by JamalAPI** [comment]
Hi Chris,

That was it. Thanks!
