### ISSUE TITLE
VS Exception in activity log

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#255]
I think this one is different from the previous I reported, I got while I was building, but I assume I had moved the mouse somehwere, but did not realize exactly where.

```
System.NullReferenceException: Object reference not set to an instance of an object.   
at XSharp.Project.Editors.BraceMatching.BraceMatchingTagger.&lt;GetTags&gt;d__20.MoveNext() in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\Editors\BraceMatching\BraceMatching.cs:line 137   
at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__39.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
```

**Comment by RobertvanderHulst** [comment]
This is the same error as we have seen before.

**Comment by cpyrgas** [comment]
FYI, today I received the following report from Arne which looks like the same as this. Will let you know if I see this problem again in the new build.

 System.NullReferenceException: Object reference not set to an instance of an object.at XSharp.Project.Editors.BraceMatching.BraceMatchingTagger.<GetTags>d__20.MoveNext() in C:\XSharp\DevPublic\VisualStudio\ProjectPackage\Editors\BraceMatching\BraceMatching.cs:line 137at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__39.MoveNext() --- End of stack trace from previous location where exception was thrown --- at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)   Editor or Editor Extension 2019/11/11 08:06:29.455
