### ISSUE TITLE
Incorrect error message by Macrocompiler for nested macros

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#256]
When compiling the following code the macro compiler reports:
`(1,18): error XM0101: Unexpected ''''`
This is not correct.

`MCompile("{|| eval({||true}) }")`

We should either support nested macros, or correct the error message

**Comment by RobertvanderHulst** [comment]
I have fixed the error message and also added some info to the error message about ambiguous constructors and ambiguous methods. Do you think it is possible to support nested codeblocks. or should I detect these in the MCompile() function and replace nested codeblocks with a variable that gets passed to te codeblock. I could create a subclass of the Codeblock class and change te codeblock to the following 2 blocks:

```
1) {||true}
2) {|_cb| eval(_cb) }
```
and store codeblock 1 as property/field inside codeblock 2

**Comment by cpyrgas** [comment]
VO does support it, the expressions evaluates into a new codeblock that can be also evalueated, so ideally X# should support this as well. But I wouldn't put it into high priority.

Btw, just found that interestingly the VO macrocompiler does not support "true" for a logic literal, only ".t."

**Comment by RobertvanderHulst** [comment]
I have added a "macro precompiler' in the runtime that converts nested codeblocks to calls to MCompile(). For now that is sufficient to help my customer. It would be great if the macro compiler could handle this internally.

**Comment by nvkokkalis** [comment]
Preliminary support for nested macros is working now, although I have to do some cleanup and check the memvar support before pushing. To make it work I had to add a reference to XSharp.RT in the macro compiler (for the _Codeblock type).

Besides being cleaner and more elegant, the main advantage of native support for nested macros is that the nested macro is actually compiled during the external MCompile() invocation and any error is thrown at that time. With the pre-processed macro approach, any errors in nested macros will be thrown when the macro is actually evaluated. There should be some gain in evaluation speed as well, if the macro is compiled beforehand.

**Comment by nvkokkalis** [comment]
One question: do you need the nested macro to be able to access arguments of the parent macro, e.g.: "{|o| eval({||o}) }" ?

**Comment by RobertvanderHulst** [comment]
Nikos
No the nested macro should define its own parameters

**Comment by nvkokkalis** [comment]
OK, I have pushed the code. Nested macros should now be supported and memvars should be handled correctly. I don't like that it was necessary to wrap them in codeblocks inside the macroCompiler, but that's life... Please try it!

**Comment by RobertvanderHulst** [comment]
I will run some tests on Thursday with my customers code and will let you know if it works for them.
I will also comment out the macro "precompilation" in the runtime.

**Comment by RobertvanderHulst** [comment]
I found no problems (so far), so I am closing this issue. I am also removing the prepare phase from the runtime
