### ISSUE TITLE
Problem calling a constructor with PARAMS parameter with a USUAL

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#26]
In the following code, calling a method with a [ParamArray] parameter by
passing it a (string inside a) USUAL works fine at runtime. But when
using the same exact code for calling a constructor with the exact same
parameters causes a runtime exception.

Both cases did work without errors in vulcan and I have a LOT of
existing code which makes use of that.

```
FUNCTION Start() AS VOID
LOCAL u AS USUAL
u := "asd"
DoTest(u)
RETURN

PROCEDURE DoTest(u AS USUAL)
TestClass.Test(u) // ok

LOCAL o AS TestClass
o := TestClass{u} // runtime exception

CLASS TestClass
CONSTRUCTOR([ParamArray] s AS STRING[])
? s:Length
? s[1]
RETURN
STATIC METHOD Test([ParamArray] s AS STRING[]) AS VOID
? s:Length
? s[1]
RETURN
END CLASS
```

System.InvalidCastException
Unable to cast object of type 'System.String' to type 'System.String[]'.

Callstack :
```
static System.Void xRutnime.Exe.Functions.DoTest(XSharp.__Usual u)() :
C:\VIDE\Projects\TestProject\Applications\xRutnime\Prg\xRuntime.prg : 10
xRutnime.Exe.Functions+>c.System.Void
xRutnime.Exe.Functions+>c.b__2_0()() :
C:\VIDE\Projects\TestProject\Applications\xRutnime\Prg\xRuntime.prg : 4
static System.Void xRutnime.Exe.Functions.Start()() :
C:\VIDE\Projects\TestProject\Applications\xRutnime\Prg\xRuntime.prg : 1
```

**Comment by nvkokkalis** [comment]
Note that passing a single USUAL argument to a PARAMS parameter was only handled correctly for method calls if there were no non-PARAMS arguments. Otherwise, even the method call fails with a runtime exception. Now all cases have been fixed.

**Comment by RobertvanderHulst** [comment]
This also fixes Compiler test C677.
