### ISSUE TITLE
Too many parser errors #5

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#261]
Also those two code snippets (one syntax error in each) result to 14 parser errors, for 14 lines of code each:

```
STATIC CLASS WinFormsConverter
	INTERNAL STATIC METHOD AdjustContainers(oWindow AS WedDescriptor) AS WedDescriptor
			FOREACH oContainer AS WedDescriptor IN aContainers
				IF oRectangle:Contains(
				END IF
			NEXT
			IF oCurrent != NULL
				oControl:SetParent(oCurrent)
			ELSE
				nControl ++
			END IF
		END DO
	RETURN NULL
	STATIC METHOD Quoted(cText AS STRING) AS STRING
	RETURN e"\"" + cText + e"\""
END CLASS
```

```
STATIC CLASS WinFormsConverter
	INTERNAL STATIC METHOD AdjustContainers(oWindow AS WedDescriptor) AS WedDescriptor
			FOREACH oContainer AS WedDescriptor IN aContainers
				IF oRectangle:Contains() .and. 
				END IF
			NEXT
			IF oCurrent != NULL
				oControl:SetParent(oCurrent)
			ELSE
				nControl ++
			END IF
		END DO
	RETURN NULL
	STATIC METHOD Quoted(cText AS STRING) AS STRING
	RETURN e"\"" + cText + e"\""
END CLASS
```

test.prg(4,36): error XS9002: Parser: unexpected CRLF, are you missing a  token ?
test.prg(5,9): error XS9002: Parser: unexpected input 'IF'
test.prg(5,9): error XS9002: Parser: mismatched input 'IF' expecting CLASS
test.prg(6,4): error XS9002: Parser: unexpected input 'NEXT'
test.prg(7,4): error XS9002: Parser: unexpected input 'IF'
test.prg(8,5): error XS9002: Parser: unexpected input 'oControl'
test.prg(9,4): error XS9002: Parser: unexpected input 'ELSE'
test.prg(10,5): error XS9002: Parser: unexpected input 'nControl'
test.prg(11,4): error XS9002: Parser: unexpected input 'END'
test.prg(12,3): error XS9002: Parser: unexpected input 'END'
test.prg(13,2): error XS9002: Parser: unexpected input 'RETURN'
test.prg(16,5): error XS9002: Parser: unexpected input 'CLASS'
test.prg(15,2): error XS9002: Parser: unexpected input 'RETURN'
test.prg(16,1): error XS9002: Parser: unexpected input 'END'

**Comment by RobertvanderHulst** [comment]
This no longer generates dozens of error but a simple error XS9002: Parser: unexpected CRLF, are you missing a  token ?
