### ISSUE TITLE
Add ADS defines to the X# RDD

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#263]
Please add the following defines to the RDD classes:
`define AX_BEGIN_TRANSACTION := 1
define AX_COMMIT_TRANSACTION := 2
define AX_ROLLBACK_TRANSACTION := 3
define AX_ISACTIVE_TRANSACTION := 4
define DBFAXS_ADS_LOCAL_SERVER := 1
define DBFAXS_ADS_REMOTE_SERVER := 2
define DBFAXS_ADS_AIS_SERVER := 4
`

**Comment by RobertvanderHulst** [comment]
Wolfgang,
I had the same idea. I have also added the functions from functions Ace.AEF in VO

See https://github.com/X-Sharp/XSharpPublic/blob/feature/Runtime/Runtime/XSharp.Rdd/Advantage/Functions.prg

Robert
