### ISSUE TITLE
Problem installing X# in a PC with a non-stadard Users folder loaction

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#265]
https://www.xsharp.info/forum/public-product/1593-failed-to-expand-shell-folder-constant-userdocs-x-public-installer-win10#11793

I'm trying to install X# on my machine through the public installer and I keep getting this error (Failed to expand shell folder constant "userdocs"). I've tried the 207, 208a and RC1 installers, but got the same error on all of them. Any ideas on why this might be happening?

Hi! A quick google search reveals that maybe this has to do with using a non-standard location for your user folder? Have you made any change in your windows settings regarding this? See some similar cases (with suggestions) for reference:

www.iliumsoft.com/support/article/AA-013...llet-on-a-Windows-PC
answers.microsoft.com/en-us/windows/foru...74-8168-11e101d37671
www.valentina-db.com/en/valentina-develo...er-constant-userdocs
www.unifiedremote.com/tutorials/how-to-f...er-constant-userdocs

**Comment by RobertvanderHulst** [comment]
The new installer no longer installs in the Users Documents folder
