### ISSUE TITLE
Incorrect entry for CRLF in the help file

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#270]
From https://www.xsharp.info/forum/private-product/1631-2-10a-crlf-help-file#11965

Had a look in help to reread about the change with CRLF introduced in 2.07, did a search for it, first hit shows definition (incorrectly) as:

DEFINE CRLF := "" AS STRING

Further, there's a "View source" button there, which leads to "Convert.prg" on Git (https://github.com/X-Sharp/XSharpPublic/blob/feature/Runtime/Runtime/XSharp.Core/Functions/Convert.prg) - but in this file there's no CRLF at all.

The correct file where CRLF is defined is

https://github.com/X-Sharp/XSharpPublic/blob/feature/Runtime/Runtime/XSharp.Core/Defines.prg

**Comment by RobertvanderHulst** [comment]
Sandcastle gets the location for source from the PDB file. Unfortunately there is no source location for FIELDs in the PDB file (also not for types), so Sandcastle uses the location for the first method in the type. So Sandcastle falls back to the file where it finds the first method in the type.
I will change the tool so it no longer generates a source button for fields.

**Comment by RobertvanderHulst** [comment]
I have added a comment to clarify things
