### ISSUE TITLE
Make sure macro compiler handles function calls to Date(), DateTime() and Array()

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#273]
I have added some runtime functions with the names Date(), DateTime() and Array() because these are used in several dialects. I have changed the compiler to detect these.
We have to make sure that the macro compiler will also allow this. 
I created a separate rule in the compiler for the keywords that are allowed as function (xbaseFunc) and a separate entry in the expression rule (xFunctionExpression).
When Date is called with 0 or 3 parameters then it is resolved to the function. When Date() is called with 1 parameter then this gets compiled the same way as in the voConversionExpression rule.

**Comment by zdenekkrejci** [comment]
Test in 2.20 - vfp:
`? date()  && OK - current date `
`? datetime()  && error - should be current date + time`

**Comment by RobertvanderHulst** [comment]
@zdenekkrejci The code you tested is not about the macro compiler, but you are right. We should also add a DateTime() function that takes no arguments and returns DateTime.Now.

**Comment by RobertvanderHulst** [comment]
Fixed
