### ISSUE TITLE
VS editor uppercases "keywords" inside TEXT...ENDTEXT

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#275]
Type in the following in a FoxPro prg file

TEXT
if this is text
next to the text keyword
it should stay in lower case
ENDTEXT

the editor converts it to (if keyword case is enabled):

TEXT
IF THIS IS text
NEXT TO the text keyword
it whould stay IN lower CASE
ENDTEXT

**Comment by RobertvanderHulst** [comment]
Fixed
