### ISSUE TITLE
Automate COM Visible Assembly setup

### ISSUE THREAD

**Issue by JamalAPI** [X-Sharp/XSharpPublic#276]
In C# it very easy to create a COM visible assembly (DLL). I go into project properties, Application, click **Assembly Information** and click **Make assembly COM-Visible**. It has the **GUID** created and populated. 
Then I click Build tab, and turn on Register for COM interop.

The above needs to be added to X#. Please take at a C# project properties.

For ease of TLB generation, In the Build Event, Post-build Event Command Line:
I used .NET regasm.exe to register the assembly. For example:  C:\Windows\Microsoft.NET\Framework\v4.0.30319\regasm.exe "C:\test\XSharpVOClassLibraryCOM\bin\Release\XSharpVOClassLibraryCOM.dll" /tlb

Now in the C#, I add:
[ClassInterface(ClassInterfaceType.AutoDual)]

Make the class public and also any methods I want exposed.

Then build project for release.

Now the I can access the COM from VO as an automation class.

In X#, I had to **manually** add the following to the AssemblyInfo.prg.

using System.Runtime.InteropServices

[assembly: ComVisible(true)]
[assembly: Guid("BAEB8513-5171-4AF7-A963-7508A4C0E00E")]

**Comment by RobertvanderHulst** [comment]
Jamal,
If you add the following to your project file then this will automatically run the code to register the dll
<RegisterForComInterop>true</RegisterForComInterop> (in the projectgroup without conditions or in one of the propertygroups with a condition).
I will add this property to the VS Project Property dialog in one of the next build.

Robert

**Comment by RobertvanderHulst** [comment]
Fixed in next build
