### ISSUE TITLE
VS VOWED, there is no way to adjust the grid size and if grid should be visible by default

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#279]
Maybe an option about this can be added in the VS options for X#? The VOWED itself does support adjusting the grid size.

**Comment by RobertvanderHulst** [comment]
Chris,
That would certainly be an option. Which settings need to be saved. I can think of:
- show/hide grid
- grid size
Anything else ?

**Comment by cpyrgas** [comment]
Robert,
I think those are enough. Grid on/off and Grid-X and Grid-Y sizes.

**Comment by RobertvanderHulst** [comment]
I have added a dialog in the new VS integration
