### ISSUE TITLE
Add separator lines in the source code editor

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#280]
Roslyn contains an example of how this is implemented for Visual Basic and C#.
The generic code is in:
https://github.com/dotnet/roslyn/tree/master/src/EditorFeatures/Core.Wpf/LineSeparators
The C# code is in
https://github.com/dotnet/roslyn/tree/master/src/EditorFeatures/CSharp/LineSeparators

I think it should not be too much work to change this code to work for X# as well.
We can probably set the appropriate tags at the same time when we are setting the tags for collapsing and expanding  our IF, DO WHILE, FOR NEXT etc statements.

**Comment by cpyrgas** [comment]
Confirmed, very nicely done!
