### ISSUE TITLE
VS editor indentation problem with "Block" setting

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#288]
Not sure what is the correct behavior with it, but when you set the "Indenting" option to "Block" (not "Smart"), every new line doubles the indentation of the previous one. For example:

```
|  n := 1<enter>
|    <-cursor here
```

```
|   n := 1<enter>
|      n := 2<enter>
|            n := 3<enter>
|                        <-cursor here
```

**Comment by RobertvanderHulst** [comment]
I think this is fixed now. Chris can you confirm ?

**Comment by fforay** [comment]
Yes, it should be fixed in one of my latest commit.

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by cpyrgas** [comment]
Yeah, I think it's good now. What it does now is to always put the cursor at the same column as the first word of the previous line, without any other extra indentation, even after IF etc statements, I assume this is the intended behavior.
