### ISSUE TITLE
VS Problem with autocomplete and indenting

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#293]
Type the code below:

```
FUNCTION Start() AS VOID
LOCAL n AS INT
DO WHILE TRUE
    n:
ENDDO
RETURN 0
```

And press ":" on "n" to invoke code completion.

Pick one of the methods in the list (like "CompareTo") and hit <enter> to select it. This will type indeed the method name with the parens, but will re-indent the whole line of code incorrectly, it will allign it with the position of the "DO" keyword above as in:

```
DO WHILE TRUE
n:CompareTo()
ENDDO
```

**Comment by RobertvanderHulst** [comment]
Fixed
