### ISSUE TITLE
 DBReindex() and shared mode

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#3]
Regarding DBReindex(), the VO docs say that it can be used no matter if
the dbf is opened shared or not:

"Although this operation will work in both shared and exclusive mode,
exclusive mode is highly recommended. See both SetExclusive() and
"Concurrency Control" in the Programmer's Guide for more information."

But that´s not correct (as usual...). If a dbf is opened shared VO
throws an "Shared error" Error Code: 37[EXCLUSIVE REQUIRED]

X# allows a DBReindex() in both modes. Not sure what we should do with
that, but at least without a full file lock, a shared file reindex
sounds a bit dangerous?

```

FUNCTION Start() AS VOID
LOCAL cDBF, cPfad, cIndex, cDriver AS STRING
LOCAL aFields, aValues AS ARRAY
LOCAL i AS DWORD
LOCAL lSHared AS LOGIC

lSHared := TRUE

cDriver := RDDSetDefault ( "DBFCDX" )

aFields := { { "LAST" , "C" , 20 , 0 }}
aValues := { "b" , "d" , "c", "e" , "a" }

cPfad := "C:\test\"
cDBF := cPfad + "Foo"
cIndex := cPfad + "Foox"

FErase ( cIndex + IndexExt() )

DBCreate( cDBF , AFields)
DBUseArea(,"DBFCDX",cDBF , , lSHared )
FOR i := 1 UPTO ALen ( aValues )
DBAppend()
FieldPut ( 1 , aValues [ i ] )
NEXT

? DBCreateOrder ( "ORDER1" , cIndex , "upper(LAST)" , { || Upper (
_Field->LAST) } )

? DBSetOrder ( 1 )

// DBReindex()
//
// When the DBF is opened shared VO throws an "Shared error",
// while X# seems to allow a reindex , no matter if the DBF is opened
shared or not.

? "Reindex", DBReindex()

DBCloseAll()
RETURN

**Comment by wriedmann** [comment]
Hi Robert,

I would ignore that VO documentation and execute the reindex only when the file is opened exclusively.

Doing a reindex is IMHO too dangerous.

Wolfgang

Von: Robert van der Hulst [mailto:notifications@github.com]
Gesendet: Donnerstag, 28. März 2019 19:37
An: X-Sharp/XSharpPublic
Cc: Subscribed
Betreff: [X-Sharp/XSharpPublic] DBReindex() and shared mode (#3)


Regarding DBReindex(), the VO docs say that it can be used no matter if
the dbf is opened shared or not:

"Although this operation will work in both shared and exclusive mode,
exclusive mode is highly recommended. See both SetExclusive() and
"Concurrency Control" in the Programmer's Guide for more information."

But that´s not correct (as usual...). If a dbf is opened shared VO
throws an "Shared error" Error Code: 37[EXCLUSIVE REQUIRED]

X# allows a DBReindex() in both modes. Not sure what we should do with
that, but at least without a full file lock, a shared file reindex
sounds a bit dangerous?





FUNCTION Start() AS VOID



LOCAL cDBF, cPfad, cIndex, cDriver AS STRING



LOCAL aFields, aValues AS ARRAY



LOCAL i AS DWORD



LOCAL lSHared AS LOGIC







lSHared := TRUE







cDriver := RDDSetDefault ( "DBFCDX" )







aFields := { { "LAST" , "C" , 20 , 0 }}



aValues := { "b" , "d" , "c", "e" , "a" }







cPfad := "C:\test\"



cDBF := cPfad + "Foo"



cIndex := cPfad + "Foox"







FErase ( cIndex + IndexExt() )







DBCreate( cDBF , AFields)



DBUseArea(,"DBFCDX",cDBF , , lSHared )



FOR i := 1 UPTO ALen ( aValues )



DBAppend()



FieldPut ( 1 , aValues [ i ] )



NEXT







? DBCreateOrder ( "ORDER1" , cIndex , "upper(LAST)" , { || Upper (



_Field->LAST) } )







? DBSetOrder ( 1 )







// DBReindex()



//



// When the DBF is opened shared VO throws an "Shared error",



// while X# seems to allow a reindex , no matter if the DBF is opened



shared or not.







? "Reindex", DBReindex()







DBCloseAll()



RETURN

**Comment by JohanNel** [comment]
Good day Robert,

I am not going to answer you directly, but here goes....:

An idea that I had for a long time based on work we did when Class(y) came along with Clipper 5.0.  A DBF and the Index are two separate files. During a Reindex in shared mode, is it not possible to have a flag, to indicate a DBF lock is required to not allow updates to the table, but reads are still fine.

Maybe I will try and plant the seed here...

I think the whole Functional approach of DBF is wrong, it should be designed from a class level upwards and and the Functions are wrappers around DbServer.

Here is the logic, what is currently in Db<Function>() should be the code inside of DbServer:MethodName()

Same, there should be a class DbIndex with all the index functions in as Methods, note not static methods.

Workareas should be managed by a Singleton class Workareas with the Db<FunctionName> as static methods of this class. Immediately the 1024 workareas as was implemented in VO, where the workarea for Function created interfaces started from 1, while DbServer started at 1024.  Workareas should be allocated sequential.  A workarea is just a list with a unique number

We can then provide for a Network enabled RDD starting from the base class.

Going back a long time to Clipper days, I had a FUNCTION NetTry to poll for the required states for e.g. exclusive locks etc.  I think this can become part of the Runtime as a DbServer/WorkArea feature actually, with a lot less trouble than what I had in Clipper days.  This was company code, so I don't have it with me, but I can still remember the logic:

FUNCTION NetTry(cb AS CODEBLOCK, nTries AS INT) AS LOGIC
    VAR lSuccess := FALSE
    VAR iTry := 0
    WHILE !(lSuccess := Eval(cb)) .AND. (iTry++ < nTries)
        Sleep(1 second)
     ENDO
RETURN lSuccess
               

If the DBF is opened in shared mode, it implies we need to try and get to a stage that at least an Exclusive Lock for the index is granted, people can Read, but not Insert/Update/Delete.  A "DbAdmin" function where say the Index was corrupted in a multi user application, had the following logic, maybe this can be implemented in the RDD itself now that you have full control...

Our DBF's were wrapped as follows:

class NetworkDBF inherit DbServer
    protect iTries as int
    constructor(iT as int)
        super()
        iTries := iT
    return
    method GetExclusiveIndexLock() as logic
        var lLocked := false
        if NetTry({|| self:Lock()}, iTries)
            // Fire what is needed on recreating the index file(s)
        endif
    return
end class

Administrators had an AdminConsole that they use to fire Admin tasks on the database.  In this they would schedule tasks, but the main difference was their NetworkDBF was created as oDbServer := NetworkDBF{1000}, normal users had a oServer := NetworkDBF{5}

With this approach one can easily at RDD core, implement all these self managing admin tasks.

You want as user to get more than a read access, NetTry(5), ask user to abandon, etc.  If he retries hopefully the admin task is completed and the DBF is available again.  You can easily then write in the base RDD the necessary for a thinking RDD.  If I don't get the required permission, how about reopening the DBF from scratch.  Reindexing can actually create "temp" indexes and once they created kept in a hold state, while exclusive locks are polling on the Index table, when the lock is required, rename index to *.<idx>.bak and rename the temp created index to the correct name, e.g. indexname.<idx>.tmp

I think such an approach and rework of the code, might bring DBF to the level of RDBMS servers.  To then write a Foxbase Relational DBF server can be achieved in a fraction of time.  The DBF manages these all by itself, the "RDBMS" just wraps those in 'n higher level.

If you feel this might be a good basis, I am willing to get the ball rolling.  I need just another week, then Matt can almost take over the VFP integration that we started, with minimal input from my side.

Sorry, probably not the type of answer that you wanted to hear, but these type of questions will not feature in my idea.  It is a mere wrapper around the existing code base and swap DbServer methods with the matching Functions.  Bit of "Network" logic inserted where needed.

Johan

**Comment by JohanNel** [comment]
To answer your question directly, I believe X# is doing it correctly.  If the runtime can get exclusive rights to the Indexes and just limit updating of the indexed fields of the DBF, there should be no reason why an exclusive lock is required on the DBF.  The index [re]create have nothing that will update the DBF in such a way (Structure) that the DBF have to be recreated.
