### ISSUE TITLE
 Problem with generating source code in winforms with no namespace

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#30]
- Create a new winforms project

- Edit the form.prg and designer.prg files and remove the BEGIN...END
NAMESPACE declarations, so the form is now created in the default namespace

- Building and running the project should still work fine.

- Open form.prg in the editor and add some comments before the form
declaration and after the form declaration as in the attached sample.

- Open the form in the designer (it opens fine), make some dummy change
and save.

- Open form.prg in the editor again, now the comments at the end of the
file are missing and the comments before the class declaration are
duplicated in the beginning of the file.

**Comment by cpyrgas** [comment]
[WindowsFormsApplication24.zip](https://github.com/X-Sharp/XSharpPublic/files/3296851/WindowsFormsApplication24.zip)
