### ISSUE TITLE
FoxPro allows parentheses for accessing aray elements

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#302]
https://www.xsharp.info/forum/public-vfp/1707-couple-of-foxpro-incompatibilities#12682

Foxpro uses square brackets or parentheses interchangeably for arrays. This is valid VFP:
DIMENSION gaArrayOne[10], gaArrayTwo(2,4), gaArrayThree[3,3]

**Comment by lazy-fox** [comment]
A few more things on vfp arrays:
Vfp allows assigning 1 value to all elements by assign without normal or square parenthesis
laArrayWhatever = 0
will iterate over all elements currently dimensioned.
Used quite often to quickly initialize all elements of an array by those knowing about it, as all arrays in vfp are usuals defaulting to .f.
Personally I think that such behaviour should be left for "Store", where 1 value can be set in multiple targets, but it is vfp documented behaviour.
Passing Array without "ref" marker @ to functions results in only first element passed.
As such behaviour can be expressed in vfp by 
= myFunc(taArrayWhatever[1])
here my 2 cents would argue for issueing a warning on different behaviour, asking to add [1] in xSharp if old behaviour wanted, as this would work identical in vfp.
Then there is the hiding of private arrays passed by reference - best read the discussion in Wiki:
https://fox.wikis.com/wc.dll?Wiki~PassingArrays
http://fox.wikis.com/wc.dll?Wiki~ParametersByValueOrReference
the "hiding" IIRC was one of the very few things changing from FPW/D to vfp.

**Comment by RobertvanderHulst** [comment]
Visual Basic parses Foo(1,2) as an invocation expression, and when the binder detects that Foo is a variable and it is an array then it converts the InvocationExpression to an ArrayAccessExpression
