### ISSUE TITLE
VS debugger shows array indexes as zero based

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#304]
https://www.xsharp.info/forum/public-vfp/1713-one-based-array-and-vs-debugger

VFP uses one-based arrays, which is the default setting for the Foxpro dialect in X#. However, when viewing an array in the Visual Studio debugger, the first element is listed as the 0th element. For a 2-dimensional array, the first element is 0,0 rather than 1,1. This would not be too much of a problem if one were viewing an entire array in the debugger since it would be obvious it was starting with 0. However, if one had a watch on something like MyArray[1] or MyArray(i) the watch window would report an incorrect value for that particular item for any one-based array.

**Comment by RobertvanderHulst** [comment]
I have implemented this.
