### ISSUE TITLE
Problem evaluating macro with alias expressions

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#305]
The first 4 of the following macros get executed correctly and return expected results.

The next one (which is the most important to fix, for RP2) produces a

System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at { ||  (1) -> (CFIELD) == (1) -> (CFIELD)  }(Object[] )
   at XSharp.RuntimeCodeblock.EvalBlock(Object[] args)
   at XSharp._Codeblock.Eval(__Usual[] args)

The last one (not very improtant at the moment), produces a

Unhandled Exception: XSharp.MacroCompiler.CompilationError: Macrocompiler (1,42): error XM0101: Unexpected ')'
   at XSharp.Runtime.MacroCompiler.Compile(String macro, Boolean lAllowSingleQuotes, Module module, Boolean& isCodeblock, Boolean& addsMemVars)
   at XSharp.RT.Functions.MCompile(String cString, Boolean lAllowSingleQuotes)
   at XSharp.RT.Functions.Evaluate(String cString, Boolean lAllowSingleQuotes)
   at XSharp.RT.Functions.Evaluate(String cString)

```
FUNCTION Start() AS VOID
	LOCAL cDbf AS STRING
	cDbf := "c:\test\mytest.dbf"
	DbCreate(cDbf , {{"CFIELD" , "C" , 10, 0}})
	DbUseArea(TRUE,,cDbf)
	DbAppend()
	FieldPut(1, "TEST")
	
	EvalMacro(" (1) -> (CFIELD) ")				// "TEST", OK
	EvalMacro(" (1) -> (CFIELD) == 'TEST' ")		// FALSE, OK
	EvalMacro(" (1) -> (CFIELD) == 'TEST      ' ")	// TRUE, OK
	EvalMacro(" (1) -> (CFIELD) = 'TEST' ")		// TRUE, OK
	EvalMacro(" (1) -> (CFIELD) == (1) -> (CFIELD) ")	// EXCEPTION, should be TRUE
	EvalMacro(" AllTrim( (1) -> (CFIELD)) == 'TEST') ") // EXCEPTION, should be TRUE
RETURN

FUNCTION EvalMacro(cMacro AS STRING) AS USUAL
	LOCAL oCodeBlock AS CODEBLOCK
	LOCAL u := NIL AS USUAL
	? "Evaluating ", cMacro
	cMacro := "{ || " + cMacro + " }"
	oCodeBlock := &(cMacro)
	TRY
		u := oCodeBlock:Eval()
//		u := Eval(oCodeBlock)
		? "Result:", u
	CATCH e AS Exception
		? e:ToString()
	END TRY
	?
RETURN u
```

**Comment by RobertvanderHulst** [comment]
Nikos,
Can you look into this ?

**Comment by cpyrgas** [comment]
Bump, Nick please give this priority please, it causes big trouble in the reporting engine

**Comment by RobertvanderHulst** [comment]
Nikos
I solved a similar problem in the compiler by adding a rul that consists of the alias operator, lparen, expression, rparen. This makes sure that the parser is not too greedy and does not include the rest of the binary expression as part of the first aliased expression.

**Comment by nvkokkalis** [comment]
The last example macro has actually an extra ')'. Is this valid?

Also, I could not compile the runtime with the latest sources in the repo (in a previous commit everything worked).

**Comment by RobertvanderHulst** [comment]
Nikos,
Did you download all the changes ? It compiles over here (I'll check again tomorrow morning).

Please note that I added new projects to the solution. One for XSharp.Data and a test project for the Macro compiler with the FoxPro macros. I did that last one to make sure that the macro compiler is initialized the right way and that FoxPro settings do not disturb the VO macros and vice versa.

And the extra RPAREN seems like a typo in the sample code. This should not compile and produce a macro compiler error. There should be no RPAREN after 'TEST'

**Comment by nvkokkalis** [comment]
Robert, what do you mean by "all the changes"? Is not everything included in the git repo? (I'm at the last commit since I pushed, obviously)

With the 2.2.2.0 compiler I cannot even compile XSharp.Core. With an earlier version I could compile it, but Xsharp.RT was failing. Am I doing something wrong?

**Comment by RobertvanderHulst** [comment]
Are you compiling with the latest release build or with the latest commit of the development build of the compiler ?

**Comment by RobertvanderHulst** [comment]
Are you getting problems with the "VALUE" keyword in property setters ?

**Comment by nvkokkalis** [comment]
Yes (I'm compiling with the last release build).

**Comment by cpyrgas** [comment]
Oh right, about that extra paren it was a typo in the code.

Interesting thing is that this was taken from real code that was working fine in VO though. Apparently in VO, the macro compiler just ignores any extra parens and does compile the macro...actually I just tried with 10 extra parens and it still works...

I am sure we will get more reports about this, but then again I don't think it's a good idea making the macro compiler ignore extra parens to make it compatible with VO. And the error message in the exception text is descriptive of the problem enough, so I think we are fine.

**Comment by cpyrgas** [comment]
Robert, I am getting the same errors with VALUE

**Comment by RobertvanderHulst** [comment]
Chris, Nikos,
I will create a new compiler and VS integration today and will remove VALUE from the keywords list. This should prevent VS from uppercasing the VALUE keyword in the future. Of course this needs to be changed in XIDE as well .

**Comment by cpyrgas** [comment]
Robert, XIDE does not touch the casing of VALUE, only colors it as a keyword, so no changes needed for me :)

**Comment by nvkokkalis** [comment]
Btw, did you manage to check the fix for this issue?

**Comment by RobertvanderHulst** [comment]
Yes, it looks ok. I will upload a new setup tonight, that fixes the compiler problem and that will no longer change the case of “value” in the vs editor.

**Comment by cpyrgas** [comment]
Tested the fix in RP2 and it works fine now (well, at least this part), good job!
