### ISSUE TITLE
CATCH exceptions in FoxPro dialect

### ISSUE THREAD

**Issue by atlopes** [X-Sharp/XSharpPublic#306]
In VFP, the catching mechanism has the following syntax

CATCH [TO VarName] [WHEN Condition]

In X#.VFP implementation, the parser complains at the TO, does not accept the "mdot" prefix for the variable reference, and does not implement the WHEN clause.

**Comment by RobertvanderHulst** [comment]
The CATCH mechanism in X# is modeled on the CATCH mechanism in C#. 
```
TRY 
   .. statements
CATCH e1 as SpecificException
  .. statements
CATCH e2 as AnotherTypeOfException
  .. statements
CATCH e3 as Exception
  .. statements
END TRY
```
A Catch clause without type would always mean the "Exception" type. Is that correct ?
And we are planning to add support for Exception filters (the WHEN clause) in one of the next release.

**Comment by atlopes** [comment]
> A Catch clause without type would always mean the "Exception" type. Is that correct ?

Yes. In VFP you can't register another type of exceptions. When an exception occurs, the referenced variable is reset afresh as an unsubclassed Exception. The AS clause is not supported.

Ignoring the TO particle of the VFP dialect would make porting more comfortable.

**Comment by RobertvanderHulst** [comment]
The compiler now supports the optional TO clause for the CATCH block.
The mdot prefix is now also accepted on all possible locations where this may be useful (let's hope I did not forget one)

```
FUNCTION Test
    TRY        
        LOCAL m.x = 0
        LOCAL m.y = 1/x
        ? m.y
    CATCH TO m.e WHEN Dow(DATE()) = 1
        ? "Dow == 1"
        ? m.e:ToString()
    CATCH TO m.e WHEN Dow(DATE()) != 1
        ? "Dow != 1"
        ? m.e:ToString()
    ENDTRY
    RETURN
```
