### ISSUE TITLE
Binary string literals not supported in FoxPro dialect

### ISSUE THREAD

**Issue by atlopes** [X-Sharp/XSharpPublic#307]
Binary string literals like 0h0123456789abcdef or 0h (the empty binary string) are not supported, yet.

Varbinary and Blob are regular VFP data types and have the same literal representation.

**Comment by RobertvanderHulst** [comment]
FoxPro is an ANSI environment. X# is Unicode. 
Is it correct to assume that 0hAA represents a single byte with hex value AA ?

**Comment by atlopes** [comment]
Yes, Robert. It's used for binary storage/representation of anything (an image, for instance).

**Comment by RobertvanderHulst** [comment]
According to the VFP Docs "Binary literals are limited to 255 encoded bytes. " Do you have an example of how you use this ?

**Comment by atlopes** [comment]
The 255 limit applies to character literals, also. In VFP, anything you enclose inside "" or '' must fit in 255 bytes. The same applies to binary strings. Anything starting with 0h must not be longer than 255 bytes. But binary variables and expressions, as character variables expressions, can be longer or result longer than that.

A real-life example:
`

			m.BOM = FREAD(This.HFile, 2)

			DO CASE
			* UNICODE LE
			CASE m.BOM == "" + 0hFFFE
				This.UTF = 1
				FSEEK(This.HFile, 1, 0)
			* UNICODE BE
			CASE m.BOM == "" + 0hFEFF
				This.UTF = 2
			* UTF-8?
			CASE m.BOM == "" + 0hEFBB AND FREAD(This.HFile, 1) == "" + 0hBF
				This.UTF = 3
			* UTF-8 no BOM?
			CASE !ISNULL(m.TempBuffer) AND !(LEN(STRCONV(m.TempBuffer, 9)) == LEN(m.TempBuffer)) AND STRCONV(STRCONV(m.TempBuffer, 12), 10) == m.TempBuffer
				This.UTF = 4
				FSEEK(This.HFile, 0, 0)
			* leave the UTF property as it was set
			OTHERWISE
				FSEEK(This.HFile, 0, 0)
			ENDCASE
`

**Comment by RobertvanderHulst** [comment]
### From the VFP Help:

To store binary data of any kind, such as ASCII text, an executable (.exe) file, or a stream of bytes, and with indeterminate length, use the Blob data type. Blob data types are particularly useful for storing Image data from SQL Server.
You can assign values to a Blob field using binary literals. Binary literals begin with a prefix, 0h, followed by a string of hexadecimal numbers and are not enclosed with quotation marks (""), unlike character strings. The following list includes examples of binary literals: 
```
0h202020
0h6ABCDEF
0h (empty binary literal)

```
Binary literals are limited to 255 encoded bytes. 

I would like to add support for these binary literals to the compiler and macro compiler.
I first thought that it would make sense to convert them to strings and let each pair of bytes form a Unicode character.
However that would mean that the # of bytes always has to be even, and the VFP examples clearly show examples of odd numbers (like the first example).
So my current thinking is now to convert them to System.Byte arrays of the proper length. The last example would become a zero length byte array.

**Comment by atlopes** [comment]
Robert,

An additional point I would like to make is that VFP accepts binary strings where a character string is expected. For instance, ASC(0h40) is the same as ASC('@').

Binary strings can also be operands in string expressions. Their placement determines the type of the final expression (binary or character).

`? VARTYPE('@' + 0h40) && displays C`
`? '@' + 0h40  && displays @@`
`? VARTYPE(0h40 + '@') && displays Q`
`? 0h40 + '@' && displays 0h4040`
`? 0h + '@' && displays 0h40`

**Comment by RobertvanderHulst** [comment]
Antonio,

In your examples you are using 0h40 as an alias for the '@' character.
That means that 0h40 is the same as Ansi character 0h40 right ?
In that case we cannot represent binaries as byte arrays but should simply translate them to strings.
However that will introduce the problem that the numbers above 0h7F will have a different 'meaning' on machines with a different codepages.

So if I would translate 0hD1 to "Ñ" on a machine with codepage 1252, that same value should have a different meaning on for example a Chinese or Japanese version of windows. In Japanese it would probably be "ﾒ" and in Chinese it is the lead byte of a multi byte character. 
So we can't really handle this as a literal at compile time but would have to compile it into something like Chr(0xD1) which takes the current codepage at runtime to generate a character.

**Comment by atlopes** [comment]
Robert,

As I see it, binary strings should be handled as single-byte sequences and not subject to any kind of encoding transformation when processed on their own.

For instance, 0h20 + 0hD1 + 0h40 should return 0h20D140.

But if binary and character strings are mixed, then a VFP-turned-X# developer should expect potential encoding transformations affecting the final result.

Someone else may step in with other ideas, but even this will lead to a code revision, I would accept that

a) binary strings are always treated as single-byte sequences;

b) except when concatenated to character strings (via + or - string operators), in which case

b1) each byte in a binary string is transformed into a Unicode character, when the final result is of type 'C',

b2) and each character in the character string is transformed into a two-byte or four-byte sequence before concatenation when the final result is of type 'Q'.

**Comment by RobertvanderHulst** [comment]
Antonio,
I think the best solution is then to create a special Binary type which wraps an array of bytes and has operators so you can add a string to a binary and a binary to a string. In this operator the various individual bytes can then be translated into unicode characters. 

We can also add comparison operators ( greater than, less than, greater than equal, less than equal, equal, not equal etc) and implicit conversion operators (from byte[], to byte[], from string, to string etc). 

This also means that we have to extend the UsualType enum and add a Binary type and add switches to several of the usual operators to handle operations on binaries stored inside a usual (similar to the operators that we'll add for the binary type itself).

I assume that the result of 
- Binary + Binary = Binary (concatenate the byte arrays)
- String + Binary = String 
- Binary + String = String (Or should this  operation return a Binary?)

In the core dialect the compiler can translate the binary literal to a byte array  then and in the VFP and other dialects the binary literal can then be a byte array wrapped inside the binary type.

**Comment by RobertvanderHulst** [comment]
See 51935dc3e0d7ad91e60298cece15a57b316fd4ad for the implementation of the Binary type.
Please note that we are NOT storing the binary as a literal string because the conversion of upper Ascii characters is codepage dependent.
The binary type has an implicit converter to string and operators that allow to add a binary to a string and vice versa.
We have also implemented comparison operators.

**Comment by atlopes** [comment]
Robert, sorry to come to this a bit too late, but Binary + String = Binary (I noticed that the current implementation returns a String).

That said, I think that your considerations regarding the implementation of this type seem quite sensible.

**Comment by RobertvanderHulst** [comment]
Antonio,
No problem, this is work in progress.
The only problem that I see with binary + string = binary is that in .Net the string may contain Unicode characters that are not part of the current codepage. These will then be translated to a ? character.

And for multi byte Ansi codepages (such as Chinese, Thai and Japanese) a string of for example 10 Unicode characters may return more than 10 bytes. I'll use Encoding:GetBytes() to get the bytes
I will also change the byte -> string routine to take multi byte codepages into account by using Encoding:GetString(Byte[]) for the conversion.
