### ISSUE TITLE
ASSERT support in FoxPro dialect

### ISSUE THREAD

**Issue by atlopes** [X-Sharp/XSharpPublic#309]
ASSERT should, at least, be ignored by the parser.

It would be nice if it could have some interaction with the debugger, though.

**Comment by RobertvanderHulst** [comment]
We will implement the ASSERT command by mapping it to the Debug.Assert() functionality in the .Net runtime.

**Comment by RobertvanderHulst** [comment]
We have added an ASSERT command and dialog. Also the SET ASSERTS ON/OFF command. The [Debug] button is only enabled when the debugger is running and the text of the [Cancel] button has been changed to [Quit] to better represent what this button is doing.
