### ISSUE TITLE
Currency data type not supported in FoxPro dialect

### ISSUE THREAD

**Issue by atlopes** [X-Sharp/XSharpPublic#310]
Expressing currency data is not yet supported in the VFP dialect.

Currency literals are preceded by the $ symbol and have a range of $-922337203685477.5807 to $922337203685477.5807. Currency precision is of 4 decimal places.

Calculations and processing involving currency data are not exactly the same as with other numeric data.

For instance,

$45.78593 = $45.7859 -> .T., currency is rounded to the 4th decimal place
$100 / 3 = $33.3333 -> .T.
while
100 / 3 = 33.3333 -> .F.

**Comment by RobertvanderHulst** [comment]
Antonio,
The currency type in X# is called Decimal. It maps to System.Decimal. The literal format for currency is the number followed by a m (like in C#): 1.23m We will check to see if we can also add the foxpro format for currency literals

**Comment by RobertvanderHulst** [comment]
To emulate the 4 digit precision we would have to assign the value with System.Decimal.Round(value,4)

**Comment by RobertvanderHulst** [comment]
Fixed
