### ISSUE TITLE
Workarea events enhancement

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#312]
The workarea events are a very nice feature. But there´s one problem: i receive a notify when i do a "commit all", but there´s no notify when i do a "commit".

```
FUNCTION TestDbNotify() AS  VOID
LOCAL cDBF, cPfad AS STRING  
LOCAL aFields AS ARRAY

  	CoreDb.Notify += NotifyRDDOperations 
 
   	cPfad := "D:\test\"
	cDBF := cPfad + "towns.dbf"  
	aFields := { { "TOWN" , "C" , 20 , 0 } } 
    // -------------------  

	DbCreate( cDBF , AFields)
	DbUseArea( ,,cDBF )	

	DbAppend() 
	FieldPut ( 1 , "London" )
	
	DbCommit() // sends no notification
//	DbCommitAll()  // sends notification
	
	// -------------

	DbCloseArea() 	 

  	CoreDb.Notify -= NotifyRDDOperations     	
	
	RETURN 	

FUNCTION NotifyRDDOperations(oRDD AS XSharp.RDD.IRdd, oEvent AS XSharp.DbNotifyEventArgs) AS VOID
   IF oRDD != NULL
        ? oRDD:Alias, oEvent:Type:ToString(), oEvent:Data
   ELSE
        ? "(no area)",oEvent:Type:ToString(), oEvent:Data
   ENDIF

```
-  what´s needed is another DbNotificationType enum member 

	e.g. FileCommit := 19
	
-  now the coredb.prg Commit() might look like:

```
 STATIC METHOD Commit() AS LOGIC
        RETURN CoreDb.Do ({ =>
        LOCAL oRDD := CoreDb.CWA(__FUNCTION__) AS IRDD
        LOCAL lOk := oRDD:Skip(0) AS LOGIC
        IF lOk
            lOk := oRDD:Flush()
        ENDIF 
        
        RAISE FileCommit  oRDD:Info(DbInfo.DBI_FULLPATH,NULL) // <----
        
        RETURN lOk

```

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
I'll have a look, but this should not be a big problem I think. Btw did you see that you can also subclass every RDD and intercept the methods from the RDD: 

https://www.xsharp.info/runtimehelp/html/T_XSharp_RDD_WrapperRDD.htm

Robert

**Comment by Karl1155** [comment]
Robert,

Thanks for the already made notify enhancement ! And yes, because i always read the "what´s new" docs from the beginning to the end ;-),  i already noticed the possibility to subclass a rdd. I didn´t try it yet, but i´ll take a closer look when i get the time.

Karl-Heinz
