### ISSUE TITLE
VS Editor problem identing with comment in next line

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#314]
Paste the following in VS, then move the cursor after "FALSE" and hit <enter>. New line gets created, but the cursor gets positioned at the first column, with no indentation. Without the commented line there, indentation works as expected.

```
FUNCTION Test() AS VOID
IF FALSE<enter>
// some comment here
ENDIF
```

**Comment by RobertvanderHulst** [comment]
Fixed
