### ISSUE TITLE
AT*() functions not working as Visual FoxPro specifications

### ISSUE THREAD

**Issue by atlopes** [X-Sharp/XSharpPublic#317]
The AT() functions are not returning results according to VFP specifications.

? AT("b", "abcabc") -> 1 instead of 2
? AT("b", "abcabc", 2) -> 1 instead of 5
? AT("b", "abcabc", 3) -> 1 instead of 0
? AT("d", "abcabc") -> 4244967295 / -1 instead of 0

Strings in VFP are one-based and no match should be denoted with zero.

The subsequent occurrences are not being properly fetched I think because the IndexOf method is not advancing on the string (it keeps searching from the beginning).

A rewriting adhering to the VFP specifications could be something like

`FUNCTION At (cSearchExpression AS STRING, cExpressionSearched AS STRING, nOccurrence := 1 AS DWORD) AS DWORD

    LOCAL position := -1 AS DWORD

    IF ( cExpressionSearched != NULL .AND. cSearchExpression != NULL )
        IF cExpressionSearched:Length != 0 .AND. cSearchExpression:Length != 0
            DO WHILE nOccurrence  > 0
                position := (DWORD) cExpressionSearched:IndexOf(cSearchExpression, (int) position + 1, StringComparison.Ordinal)
                IF position >= (DWORD) cExpressionSearched:Length AND nOccurrence > 1
                    position = -1
                    EXIT
                ENDIF
                nOccurrence -= 1
            ENDDO
        ENDIF
    ENDIF

    RETURN position + 1
`

**Comment by Karl1155** [comment]
i would avoid all -1. Try this instead:

```
FUNCTION At(cSearch AS STRING,cTarget AS STRING , dwOccurrence := 1 AS DWORD ) AS DWORD
LOCAL position, steps := 0 AS DWORD
 

	IF ( cTarget != NULL .AND. cSearch != NULL )

		IF cTarget:Length != 0 .AND. cSearch:Length != 0             
			
			WHILE steps != dwOccurrence 
				
				position := (DWORD) cTarget:IndexOf(cSearch, (INT) position , StringComparison.Ordinal) +1
				
				IF position == 0
					EXIT
					
				ELSE	 
					steps ++ 
		
				ENDIF	
				
			ENDDO	
			
		ENDIF
		
	ENDIF 
	
	RETURN position	
```


The questions is what to do with such VO similar Fox function. Add it to the VFP dll or add it as an "offical" At() overload to the Core dll ?


Karl-Heinz

**Comment by cpyrgas** [comment]
Guys, also in VO terms, strings are 1-based, and this is how all At() and other string functions are designed, to return 1-based results. I tried your samples and I do not get those results, instead I get "2" for AT("b", "abcabc") etc.

Can't think why you are getting different results, maybe it's because a project setting that I am not thinking about. Can you please add to the report a zipped small sample project that we can build and run that shows this behavior?

Btw, regarding functions that have different behavior in different dialects, two things can be done about this:

- Remove them from XSharp.Core and create one version in XSharp.VO and another in XSharp.VFP
- Leave them in XSharp.Core as one function and add an IF/CASE statement to implement different behavior based on the "active" dialect (by testing for the value of RuntimeState.Dialect)

**Comment by Karl1155** [comment]
Chris,

Of course At() results can only be >= 0.  It´s atlopes that talks about < 0 results , not me. :-)

Karl-Heinz

**Comment by cpyrgas** [comment]
Yes, but you did not mention either that you are getting different results :-)

**Comment by atlopes** [comment]
Sorry, I didn't make myself clear.

I was referring to the VFP AT() implementation at Runtime/XSharp.VFP/StringFunctions.prg. The X# AT() current implementation is not returning wrong results, as Chris noted, but it does not support the occurrence parameter, either (if I'm not mistaken).

**Comment by RobertvanderHulst** [comment]
Antonio,
This code is work in progress and untested, it will not be included in the next build. We ( my son and me) have started adding empty functions and extracted the vfp help for these functions. 
If you want to help by implementing one or more functions that would be great. And we can also use test cases for “edge” cases like looking for an occurrence that does not exist.

**Comment by atlopes** [comment]
Ok, Robert, point taken. Sorry to have rushed into your WIP - I just read the code and thought that some cases would not fit the VFP specs.

I'm willing to help, of course, as for sure others are, especially in reviewing and testing.

**Comment by mattslay** [comment]
Let me remind everyone about the Visual FoxPro Toolkit for .NET project (available here on GitHub at link below), has (essentially) *every* VFP Runtime function implemented in C#...  It should be a great reference, and even sometimes cut-paste way, to punch out these VFP Functions in X#, or at least see how they were implemented in C#.

[https://github.com/mattslay/Visual-FoxPro-Toolkit-for-.NET](https://github.com/mattslay/Visual-FoxPro-Toolkit-for-.NET)

**Comment by RobertvanderHulst** [comment]
Fixed in https://github.com/X-Sharp/XSharpPublic/commit/1f188eb524e5b440607c6ad70d1ab4934f696785
