### ISSUE TITLE
Problem with signed / unsigned arithmetic results

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#325]
From https://www.xsharp.info/forum/public-product/1765-add-dword-to-int-v-2-2-1-vulcan-dialect#13224

Following code in X# gives the exact opposite results than it does in VO (and in Vulcan). Looks like it is the right hand side of the operations that dictates the result type in X#, while in VO and Vulcan it's dictated by the type of the left hand side operand.

```
FUNCTION Start() AS VOID
	LOCAL n AS INT	
	LOCAL d AS DWORD
	LOCAL u AS USUAL
	n := -2
	d := 1
	u := n + d
	? u // UInt32.MaxValue in Χ#, -1 in VO & Vulcan
	
	u := d + n
	? u // -1 in Χ#, UInt32.MaxValue in VO & Vulcan
	
	?
	? (n + d) // UInt32.MaxValue in Χ#, -1 in VO & Vulcan
	? (n + d):GetType():tostring() // DWORD in X#, INT in Vulcan (and in VO)
	
	? (d + n) // -1 in Χ#, UInt32.MaxValue in VO & Vulcan
	? (d + n):GetType():tostring() // INT in X#, DWORD in Vulcan (and in VO)
RETURN 
```

**Comment by RobertvanderHulst** [comment]
Vulcan seems to produce different results than VO here. I will make sure that we emulate the VO behavior here: when 2 different integral types of the same size are added/subtracted then the result will have the type of the left hand size. However, when the types have a different size (SHORT + LONG, SHORT+DWORD, WORD+INT etc) then the result type will be the type of the largest of the 2 types.

**Comment by RobertvanderHulst** [comment]
The result in Vulcan seems to depend on the /vo11 compiler flag. 
Without /vo11 u := n + d produces a UInt32.MaxValue in Vulcan. 
With /vo11 u := n + d produces a Int32 with the value -1

**Comment by RobertvanderHulst** [comment]
Shall I do the same: with /vo11 emulate the VO behavior and without /vo11 keep the current behavior ?

**Comment by cpyrgas** [comment]
Yes, I think it's the best way to emulate VO only with /vo11 enabled
