### ISSUE TITLE
open a "dbfcdx" created dbf via "dbfvfp"

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#326]
When you create a dbf via "dbfcdx" and open the dbf via "dbfvfp" an "illegal path char" exception is thrown.  Note:

- the created dbf doesn´t have any vfp specific fields.
- the error doesn´t happen with the previous 2.2a build.

```
FUNCTION Start( ) AS VOID
LOCAL aFields AS ARRAY
LOCAL cDbf, cPfad AS STRING  

    // create the dbf via "dbfcdx"                  
    RddSetDefault( "dbfcdx" )


	cPfad := "D:\TEST\"	

	cDBF := cPfad + "Foo.dbf"
	

	aFields := { { "LAST" , "C" , 10 , 0 } } 
		
	? cdbf	
	? DbCreate( cDBF , AFields)
	? DbCloseArea()
		
 
	// now open the dbf via "dbfvfp" and you should see 
	// the "illegal path char" exception. 
	 	
    RddSetDefault( "dbfvfp" )    
	 
	? DbUseArea( TRUE ,,cDBF )	
	
	DbCloseArea()

RETURN
```
Karl-Heinz

**Comment by Karl1155** [comment]
In this sample the "dbfvfp" driver throws a "path / filename too long" exception. The attachment contains the required small.dbf 

Unbehandelte Ausnahme: XSharp.RDD.RddError: Der angegebene Pfad und/oder Dateiname ist zu lang. Der vollständig qualifizierte Dateiname muss kürzer als 260 Zeichen und der Pfadname kürzer als 248 Zeichen sein.

```
FUNCTION OpenVFP2() AS VOID	
LOCAL cPfad, cDBF AS STRING

	cPfad := "D:\TEST\"	

	cDBF := cPfad + "small.dbf"				
	
//	RddSetDefault( "dbfcdx" )
    RddSetDefault( "dbfvfp" )    
    

	? DbUseArea( TRUE ,,cDBF )	
	
	DbCloseArea() 	
	
	RETURN
```

Karl-Heinz
[small.zip](https://github.com/X-Sharp/XSharpPublic/files/4219133/small.zip)

**Comment by RobertvanderHulst** [comment]
The problem only occurs when opening a file that does not have a DBFVFP header (1st byte 0x30, 0x31, 0x32). This will be fixed in the next build.
