### ISSUE TITLE
Problem with SHORTINT cast arithmetic

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#330]
VO returns -1, TRUE, TRUE in the following, but X# returns -1, FALSE, FALSE. This is code taken from the SDK.

// /vo4+
FUNCTION Start() AS VOID
	LOCAL w AS WORD
	w := 65535
	? SHORTINT(_CAST, w) // -1, correct
	? SHORTINT(_CAST, w) == -1 // FALSE, wrong!
	? SHORTINT(_CAST, w) < 0 // FALSE, wrong!
	
	xAssertTrue(SHORTINT(_CAST, w) == -1)
	xAssertTrue(SHORTINT(_CAST, w) < 0)
RETURN

**Comment by RobertvanderHulst** [comment]
Fixed
