### ISSUE TITLE
Math.prg: DToR and RToD broken

### ISSUE THREAD

**Issue by FFF-xs** [X-Sharp/XSharpPublic#331]
**Describe the bug**
Line 54 ff:
FUNCTION DToR(nDegrees as USUAL) AS REAL8
    RETURN (Real8) nDegrees / 360 * Math.PI

FUNCTION RToD(nRadian as USUAL) AS REAL8
    RETURN ((REAL8) nRadian / Math.PI) * 360.0

both using wrong formula

**To Reproduce**

**Expected behavior**
FUNCTION DToR(nDegrees as USUAL) AS REAL8
RETURN (REAL8) nDegrees / 180.0 * Math.PI

FUNCTION RToD(nRadian as USUAL) AS REAL8
RETURN (REAL8) nRadian*180.0 / Math.PI

**Comment by RobertvanderHulst** [comment]
Fixed
