### ISSUE TITLE
PRIVATE &cVarname &cVarname := uValue

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#334]
https://www.xsharp.info/forum/public-product/1798-voscript#13495

Following compiles and runs fine in VO, showing the expected results. In X#, compiler reports error XS9002: Parser: unexpected input '&'

```
FUNCTION Start() AS VOID
LOCAL cVarname AS USUAL
cVarname := "abc"
PRIVATE &cVarname
&cVarname := 123
? &cVarname // 123
? abc // 123

```

**Comment by RobertvanderHulst** [comment]
This is implemented now, including the syntax with the DOT in the name:
```
LOCAL cVarName := "SomeVar"
// this declares the PUBLIC with the name "SomeVar1"
PUBLIC &cVarName.1  
// SomeVar1 is set to 42
&cVarName.1 :=42     
? &cVarName.1           
```
