### ISSUE TITLE
erratic XS9021 warning

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#340]
The following code 
`local nLen as dword
nLen := SLen( cStringToMask )`
leads to the warning
`warning XS9021: Signed/unsigned conversions from 'dword' to 'int' may lead to loss of data or overflow errors`
This is clearly an error since the SLen() function returns a dword and nLen is declared as dword.
And since /VO4 is also active (Implicit signed/unsigned conversions), there should no warning at all even when a dword/int conversion would be in place.
X# Compiler version 2.3.1.0 (Release)

**Comment by wriedmann** [comment]
Another issue connected with the /VO4 switch: the code
`local nInt as int
 local nInt64 as int64

 nInt := 1
 nInt64 := nInt`
gives the warning
`warning XS9020: Narrowing conversion from 'int64' to 'int' may lead to loss of data or overflow errors`
Assigning an int to an int64 will never lead to any loss of data or overflow error since int64 is always a larger datatype than an int (until we have systems with more than 64 bit where the int may be larger that 64 bit).

**Comment by cpyrgas** [comment]
Thanks Wolfgang, problem(s) confirmed. But the warning itself would be correct, if you were trying to do a INT<->DWORD conversion. Doing that without /vo4 would be a compiler error, with /vo4+ is indeed a warning, because it is still a possibly dangerous thing to do.

**Comment by RobertvanderHulst** [comment]
Fixed
