### ISSUE TITLE
Compiler Error in Vfp Dialect: Trailing ";" line continuation significant even on comment

### ISSUE THREAD

**Issue by lazy-fox** [X-Sharp/XSharpPublic#342]
";" as line continuation works  both xSharp and Vfp in normal code lines.
in vfp a multi-line statement (not compilable in Bandol 2.2) like
	replace dt WITH DATETIME(), runs WITH lnStop ;
		, searchLen WITH LEN(lcWhite) ;
		, Test WITH "GetwWordNum" ;
		, Algorim WITH "Vfp9" ;
		, machine WITH "Life" ;
		, Whitesp WITH lcWhiteStr ;
		, Cnt1 WITH laErg[1, 2], ms1 WITH laErg[1, 1] ;
		, Cnt2 WITH laErg[2, 2], ms2 WITH laErg[2, 1] ;
		, Cnt3 WITH laErg[3, 2], ms3 WITH laErg[3, 1] ;
		, Cnt4 WITH laErg[4, 2], ms4 WITH laErg[4, 1] ;
		, CntA WITH laErg[5, 2], msA WITH laErg[5, 1] ;

will be commented in toto by applying a single "*" in first line before first char:

*	replace dt WITH DATETIME(), runs WITH lnStop ;
		, searchLen WITH LEN(lcWhite) ;
		, Test WITH "GetwWordNum" ;
		, Algorim WITH "Vfp9" ;
		, machine WITH "Life" ;
		, Whitesp WITH lcWhiteStr ;
		, Cnt1 WITH laErg[1, 2], ms1 WITH laErg[1, 1] ;
		, Cnt2 WITH laErg[2, 2], ms2 WITH laErg[2, 1] ;
		, Cnt3 WITH laErg[3, 2], ms3 WITH laErg[3, 1] ;
		, Cnt4 WITH laErg[4, 2], ms4 WITH laErg[4, 1] ;
		, CntA WITH laErg[5, 2], msA WITH laErg[5, 1] ;

making the multi-line statement comment due to line continuation working on comments as well.

xSharp line like like
            return      (((DWord) tc2Check>=Asc_A .and. (DWord) tc2Check<=Asc_Z) ;
                    or  ((DWord) tc2Check>=97 .and. (DWord) tc2Check<=122) ) ;
                    and Self:hcCmp:ContainsKey(tc2Check)

marked with "*" before return like
            * return      (((DWord) tc2Check>=Asc_A .and. (DWord) tc2Check<=Asc_Z) ;
                    or  ((DWord) tc2Check>=97 .and. (DWord) tc2Check<=122) ) ;
                    and Self:hcCmp:ContainsKey(tc2Check)

does not compile,
Fehler	XS9002	Parser: Expecting end of statement, found ')'	XSharp.VFP	D:\xS\RT\Runtime\XSharp.VFP\GetWord.prg	417	
Fehler	XS9002	Parser: mismatched input 'and' expecting EOS	XSharp.VFP	D:\xS\RT\Runtime\XSharp.VFP\GetWord.prg	418	

on the 2 lines following out-commented return.

regards
thomas

**Comment by RobertvanderHulst** [comment]
Thomas,
I will see what I can do.
However this is not how it works for the other XBase dialects: 
the '*' at the beginning of the line makes EVERYTHING in that line a comment, including the semi colon line, so that is no longer seen as the line continuation character.
I will discuss this in the team, but I am afraid that changing that will lead to side effects for other users.

**Comment by lazy-fox** [comment]
Hi Robert,
IMO this is one of the things to put on aseparate list "Will look at it if most other things run".
Those Vfp-ers already coding new stuff in xSharp will shrug and out comment other lines.
Porting large code basis is out of the question, as long as TableUpdate, Buffering, Cursoradapter etc are missing, so no loss.
In case "everything else" works, on a 50000 line program fixing this issue manually will take a bit, but is helped by compiler pointing out lines, on a 1000000 line progam somebody will write a short program doing nothing but fixing this issue.
In forum voicing such ideas might turn off lurkers - but if you keep such a list/specially flagged vfp oddities here, a porting program might make more sense than overburdening the compiler.

my 0.02€
thomas

**Comment by RobertvanderHulst** [comment]
This is indeed documented in the VFP help file:

`Place a semicolon (;) at the end of each comment line that continues to a following line.`

but I am afraid that changing this will cause side effects for others, like code that is accidentally excluded from the compiler.

In our VFP Exporter we will try to detect these cases and prefix the succeeding lines with * as well.
