### ISSUE TITLE
Vfp has 3 String delimiters - with feature not clearly spelled out in docs

### ISSUE THREAD

**Issue by lazy-fox** [X-Sharp/XSharpPublic#343]
Square Brackets can also delimit a string.

As special vfp pet trick, you have to savoir the line in Docs on #Define:
Note
Compile time constants are not recognized when placed within quotation  marks.

So fire up trusty vfp, create new program, insert
CLEAR
#define BEHAPPY FacePalm
? "Don_t worry - BEHAPPY"
? 'Don_t worry - BEHAPPY'
? [Don_t worry - BEHAPPY]
return

and Execute (the program - not the order printed on screen)
***Exactly*** following the wording of that liiitle line in documentation...

Please put also on List of things to revisit if everything else works - even if this one is NOT easy to fix in user code if used a lot, but the coders knowingly using that feature probably are good enough to offer solutions for the special use case(s) in their programs. Problem surfaces if the good coders left the company...

Don_t worry - ;-))
thomas

**Comment by RobertvanderHulst** [comment]
OMG, so even when VFP has bracketed string delimiters, its preprocessor ignores those delimiters and replaces the define inside the string. I am not sure if I would call that a "special vfp pet trick". This looks more like a bug in the vfp preprocessor to me. 
Of course you can take advantage of this bug, but that does not change its nature.

**Comment by RobertvanderHulst** [comment]
I have added support for the bracketed strings ? [somestring].
However the example above will show the same results for all three strings. So the preprocessor will NOT replace defines in either of the string constants. I really do not want to reproduce this FoxPro bug in our preprocessor.

**Comment by atlopes** [comment]
Robert, the behavior is documented, and it is not a bug. The token set in a #define directive will be replaced by the expression at compile time wherever it appears in code _except_ if placed inside quotation marks.

**Comment by RobertvanderHulst** [comment]
@atlopes 
When the open and close bracket are used to declare a literal string, then these brackets are used like quotation marks and in my opinion the preprocessor should follow the same rules as for the single and double quotation marks: 
The whole string including the open and closing brackets are then handled as a string constant by the lexer and I see no (easy) way to substitute defines inside these strings in the preprocessor without breaking other parts of the compiler.

**Comment by atlopes** [comment]
Robert, I understand that this may be quite tricky or difficult or even undesirable to implement, and I believe, seconding what Thomas said, that you won't see a rush of people asking for it. But regarding this, VFP is actually working as documented (that was the main point of Thomas' initial message, I think).

**Comment by RobertvanderHulst** [comment]
Antonio,
I did a comparison with Clipper, Visual Objects, (X)Harbour and XBase++ and all of these XBase compilers behave the same: they do not touch the contents of ANY string literal in the preprocessor. So none of these replaces defines inside a bracketed string. That is why I do not plan to support this.

**Comment by lazy-fox** [comment]
I am with Robert insofar as the "indirect" or "subdued" description of replacement of constants only between [] points to a feature either not put high on a change list or borderline support when discussing the feature. I don't think it was a bug - too specific to be reached probably - but I could envision a coder seeing the option to realize it with little effort in existing code, doing it and later selling it as a feature (which it can be - for instance as easy way to track constants for logging).
I am 100% with Antonio insofar as I classify the feature as documented vfp - just not shouting about it, more like introducing silently.
Usefulness: if values are in strings already, putting all of them inside a singleton will give you more and better options via string functions. BUT: in first decade I worked on a multi-million € project DEPENDING on constants for object path shortcuts in all subprojects, with accompanying strings for each path (as to sidestep eval() or GetPem()). They had so many #includes, that building whole project for release was taking nearly 1H (on HD and slower CPUs) - as a side task I streamlined those includes into project specific layers, cutting time down to less than a third of previous time (doable, but not that easy as count of levels of #include is severly limited in vfp). If such a project exists, it would make business sense to sponsor that feature, as changing their sources wold be more costly.

In my description I wrote that implementing it should be put on a back burner, as there are more important things to implement. But setting it aside early as a bug with a "will not implement" decision sends out the wrong message IMHO: xSharp dev team decides what is a bug and what is not. When more than 1 possible customer of xSharp depending on the feature comes around, he should argue his specific use case. I think the "constant replacement in []" should be marked as a known defect with lowest priority and left there, similar to FileToStr() on the bug list even if FileToStr is not-too-difficult to implement.
Putting myself in the position of someone encountering xSharp first time and thumb-guessing at probable cost of porting, finding all currently found divergences from documentation and/or vfp behaviour in the "open issue" list is beneficial, as this would be the list to scan first (and perhaps make an offer if a feature needed to implemented sooner). Telling people there is stuff more important to implement is less "door in the face" and leaves room for discussion (aka customer threatening with money).
So "partial implementation" documented as only square brackets as delimiter (currently) *without* constant  replacement  while acknowledging in the bug list a different behaviour might be better way to handle in my book.

my 0.22 €
thomas

**Comment by atlopes** [comment]
Thomas, fully agreed.

One more point: when the VFP documentation says a #defined constant will be replaced "wherever it appears" in code, except between quotation marks, it really means it.

Take a deep breath and...

```
#DEFINE FOLLOWING NEXT

LOCAL f AS Integer
LOCAL FOLLOWING AS String

CREATE CURSOR FOLLOWING (V Int)

FOR m.f = 1 TO 10

	INSERT INTO Next VALUES (m.f)

FOLLOWING

GO TOP IN FOLLOWING

REPLACE v WITH 0 FOLLOWING 5

SCAN

	TEXT TO m.NEXT NOSHOW TEXTMERGE
		FOLLOWING: <<RECNO()>> -> <<NEXT.V>> ("FOLLOWING", FOLLOWING)
	ENDTEXT

	? m.FOLLOWING

ENDSCAN
```

Disclaimer: I've never read - or wrote, until now - code like this. I'm just pointing out that the behavior corresponds to what is documented, and that [] delimiters is the way to implement the inclusion of #defined constants inside regular strings. It really is a feature.
