### ISSUE TITLE
Preprocessor enhancement - missing file pattern

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#347]
VO knows the file pattern </file/>. Therefor a VO command like

`COPY FILE </src/> TO </dest/>  => FCOPY(<(src)>, <(dest)>)`

allows to use - beside expressions - literal fullpath filenames. 

`
COPY FILE  D:\test\Foo.dbf  TO  D:\test\Foo2.dbf`

When i look at the VO STD.UDC, all file related commands use the </file/> pattern.
see also: https://www.xsharp.info/forum/private-product/1813-use

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Fixed without adding a new match marker.
The extended match marker now also checks for:
- Filenames
- String constants


The following compiles without problems now:

```
FUNCTION Start( ) AS VOID
 local cTest
 cTest := "Test"
 use (cTest)
 USE Test
 USE C:Test
 USE C:\Test
 USE C:\Test\Test
 USE C:\Test\Test.Dbf
 USE .\Test\Test.dbf
 USE ..\Test\Test.dbf
 USE \\Computer\Test\Test.dbf
 USE C:\Date\String\test.dbf    // path names match keywords
 USE "C:\String\Date\test.dbf"
 USE Foo Alias Bar
 USE ("somestring")
 USE Date        // file name matches keyword
 USE MyFile.Date // extension matches keyword
 CLOSE
```

**Comment by Karl1155** [comment]
great, i will try it as soon it becomes available.

Another dream of mine is to enter in XSI a command line like:

`use d:\test\foo.dbf alias FooFoo new via "dbfcdx" index d:\test\foo1.cdx EXCLUSIVE`

;-)
