### ISSUE TITLE
Problem with BYTE arithmetic in RETURN expressions

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#354]
When doing byte arithmetic inside the method body, it works correctly. But when doing BYTE arithmetic on a RETURN statement, compiler complains:

error XS0266: Cannot implicitly convert type 'int' to 'byte'. An explicit conversion exists (are you missing a cast?)

Note that the behavior is the same with /vo11 either enabled or disabled

```
FUNCTION Start() AS VOID
	? GetByte1(1)
	? GetByte1(255)
RETURN

FUNCTION GetByte1(b AS BYTE) AS BYTE
	b := b + 1  // ok
	b := b + (BYTE)1 // ok
RETURN b  // ok

FUNCTION GetByte2(b AS BYTE) AS BYTE
RETURN b + 2 // error XS0266

FUNCTION GetByte3(b AS BYTE) AS BYTE
RETURN b + (BYTE)2 // error XS0266

```

**Comment by RobertvanderHulst** [comment]
Fixed in https://github.com/X-Sharp/XSharpDev/commit/b45b64faa32652562f7a2ce45c4e9ade0ed6fc33
