### ISSUE TITLE
SetDecimal() setting incorrectly affects number of decimal digits returned by DBServer:Sum()

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#358]
The following prints 123,45600 in X#, while in VO it prints 123,456, since the data field has 3 decimal places.

```
FUNCTION Start() AS VOID
	LOCAL cDbf AS STRING
	LOCAL oServer AS DBServer
	LOCAL uSum AS USUAL
	
	cDbf := "c:\test\sumtest.dbf"
	
	DbCreate(cDbf , {{"NFIELD" , "N" , 8 , 3}})
	DbUseArea(TRUE,,cDbf)
	DbAppend()
	FieldPut(1,123.456)
	DbCloseArea()
	
	SetDecimal(5)
	oServer := DBServer{cDbf}
	uSum := oServer:Sum(#NFIELD)[1]
	oServer:Close()
	
	? uSum
	? Str(uSum)
	? AsString(uSum)	
RETURN
```

Old report:

The following in X# prints 12,34000 and 12,34500, while in VO it prints 12,34 and 12,345

```
FUNCTION Start() AS VOID
	SetDecimal(5)
	u := 12.34
	? AsString(u)
	? Str(u)
	u := 12.345
	? AsString(u)
	? Str(u)
RETURN

```

**Comment by RobertvanderHulst** [comment]
The result of this depends on the setting of /vo14 (Float literals). When this is enabled then the literals are stored as floats with the # of decimals that were defined in the source. With this is NOT enabled then the value is stored as System.Double and then the decimals are taken from the SetDecimal() setting.
On my machine this works as expected with /vo14 enabled and produces numbers with 5 decimals when /vo14 is not enabled.

**Comment by cpyrgas** [comment]
Yeah, that was a bad sample when I tried to create a small repro sample. The problem does exist with DBServer:Sum() though, I have updated the original text.

**Comment by cpyrgas** [comment]
Here's a simple cut down repro sample, seems to have with ARRAYs in general. Gonna look further into it.

Note that when using AAdd(a,0.0) instead of AAdd(a,0), then the result is shown with one decimal digit. VO always displays 3 decimal digits.


```
FUNCTION Start() AS VOID
	LOCAL a AS ARRAY
	LOCAL u AS USUAL

	SetDecimal(5)

	u := 123.456
	? u // 123.456, OK
	a := {}
	AAdd(a,0)
//	AFill( a, 0) // same behavior
	a[1] += u
	? a[1] // 123.45600
	u := a[1]
	? u // 123.45600
RETURN
```

**Comment by cpyrgas** [comment]
Nah, nothing to do with ARRAYs, it's a problem in the + (and other) operators of USUAL. See this sample:


```
FUNCTION Start() AS VOID
	LOCAL u1,u2 AS USUAL
	SetDecimal(5)

	u1 := 0
	u2 := 123.456
	? u1 + u2 // 123.45600
	
	u1 := 0.0
	u2 := 123.456
	? u1 + u2 // 123.5
RETURN
```

This happens because of the code 

STATIC OPERATOR +(lhs AS __Usual, rhs AS __Usual) AS __Usual
...
RETURN lhs:_intValue + rhs:_r8Value // for adding INT and FLOAT
...
RETURN FLOAT{lhs:_r8Value + rhs:_r8Value, lhs:_width, lhs:_decimals}

So when the lhs is an INT (in a usual), then a new float is implicitly generated and this takes the decimal places setting from SetDigit()

When the lhs has a FLOAT, then the addition results explicitly to a new FLOAT with decimal places taken solely from the lhs. In VO, it seems that the highest decimals number of the two operands is used instead.

So all operators of the USUAL structure need a review and update, but need to be very careful not to break something..

**Comment by cpyrgas** [comment]
Fixed.
