### ISSUE TITLE
Wrong interpretation of interpolated strings

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#360]
Please see this code:
`function TestInterpolated() as void
local cVar as string
local cVar2 as string

cVar := "Hi"
cVar2 := "X#"
System.Console.WriteLine( i"{cVar}/{cVar2}" )
System.Console.WriteLine( String.Format( "{0}/{1}", cVar, cVar2 ) )`

The first one shows "Hi\\/X#", the second "Hi/X#".

This behavior was introduced sometimes in the last year because it worked in a DLL I built in the last summer, but does not worked when the DLL was rebuild in February this year.

**Comment by RobertvanderHulst** [comment]
Fixed in next build
