### ISSUE TITLE
Problem passing virtual REF variable to function

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#363]
In the code below, the OUT version compiles fine, but the compiler for the REF syntax complains:

error XS9002: Parser: unexpected input '_'

```
FUNCTION Start() AS VOID
	MyFuncOut(1, 2, OUT VAR _ )
	MyFuncOut(1, 2, OUT _ AS STRING)
	MyFuncOut(1, 2, OUT NULL)
	
	MyFuncRef(1, 2, REF VAR _ )
	MyFuncRef(1, 2, REF _ AS STRING)
	MyFuncRef(1, 2, REF NULL)
RETURN

FUNCTION MyFuncOut(n AS INT,m AS INT,c OUT STRING) AS VOID
c := "asd"
FUNCTION MyFuncRef(n AS INT,m AS INT,c REF STRING) AS VOID
c := "asd"
```

**Comment by RobertvanderHulst** [comment]
I did some reading and Roslyn does not support this for REF variables. The idea behind this is that REF variables HAVE to be initialized before they are used. In theory we could still support this and initialize the variables automatically by the compiler, but I think we have more important things on our todo list

**Comment by cpyrgas** [comment]
Agreed!
