### ISSUE TITLE
VS Editor intellisense stop working problem

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#369]
There's something strange going on with intellisense. Please open the attached solution, it only contains this code:

```
FUNCTION Start() AS VOID
LOCAL n AS List<INT>
VAR v := n
```

Now go to the top of the prg, insert an empty line and start typing:

USING System.Collections.Generic

as you will see, after every dot you press there is no code completion shown.

Now go to the end of the prg and type

n:
v:

you will not get member completion for either of them.

If you close VS and restart, then it works in the very first go. Bu after messing a bit with USINGs, adding code etc, it stops working again, until restarting VS. I hope the first step is reproducible in your machines, fixing this will likely fix all cases.

[ConsoleApplication38.zip](https://github.com/X-Sharp/XSharpPublic/files/4528671/ConsoleApplication38.zip)

**Comment by RobertvanderHulst** [comment]
Fixed in 2.4a
