### ISSUE TITLE
Cannot reference properties added to Empty class...

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#373]
Can add properties to an Empty class, but when you try to reference them in code it gives an error at run time.

```
Function TestEmptyClass As Void

	Var loData = Empty{}

	loData.AddProperty("FirstName", "Matt")
	loData.AddProperty("State", "Alabama")

	? "Empty object created, poperties added:"
	? loData.FirstName
	? loData.State

End Function
```

![2020-04-26 22_24_54-VPF Xsharp test app 1 (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/309016/80331178-f6cf7e80-880c-11ea-9499-27887d6bcbfe.png)

**Comment by RobertvanderHulst** [comment]
Matt,
You need to give is more Info. I copied your code to a VFP console app and changed the Start() function to 
```
FUNCTION Start() AS VOID STRICT
    TestEmptyClass()
    WAIT
	RETURN	
```
and then it works OK. So I guess it has to do with one of more of your Projects' Settings.

**Comment by mattslay** [comment]
Robert - attached is a full solution that demos this error.


[VPF Xsharp test app 2.zip](https://github.com/X-Sharp/XSharpPublic/files/4540355/VPF.Xsharp.test.app.2.zip)

**Comment by mattslay** [comment]
Okay, so setting "Allow Late Binding" setting to True on the Project properties makes this problem go away.

So, us VFP devs are going to have to learn all the pros and cons of this magic "Allow Late Binding".  It seems to take away a lot of strongly typed checking, and basically takes us all the way back to a fully dynamic language, and we miss the goodness of strong typing.

I guess all we can do is just make sure the Help file addresses this on the AddProperty() and Empty class ion the docs.

**Comment by mattslay** [comment]
There is a BUG in Text/EndText when Allow Late Binding is enabled, and there are TextMerge reference to undefined local vars or object properties  

I have code in a Text/EndText/TextMerge that references a non-existing property on an object reference, and at run-time it does not even give an error and Text/EndText generated a text string while totally skipping over the referenced (bad/missing) property. This can certainly lead to big problems in a running app.


See this thread in message board for all the discussion:  https://www.xsharp.info/forum/public-vfp/1894-error-xs0656-missing-compiler-required-member

![2020-04-27 10_10_19-VPF Xsharp test app 2 (Running) - Microsoft Visual Studio](https://user-images.githubusercontent.com/309016/80515213-37331780-8947-11ea-9089-bd5bcf56a7eb.png)

**Comment by mattslay** [comment]
As reported above, setting "Allow Late Binding" setting to True on the Project properties makes this problem go away.

**HOWEVER**, it also introduces a new error wherein at runtime if you reference a property on the object that does not actually exist on the object it does not generate a run-time error (like FoxPro will do), and you code keeps on running but uses a value of .F. for the referenced property. This will definitely cause problems in a running app.  

**This needs to cause a Run-Time error.**

Example:

```
Function TestEmptyClass As Void

	Var loData = Empty{}

	loData.AddProperty("FirstName", "Matt")
	loData.AddProperty("State", "Alabama")

	? "Empty object created, poperties added:"
	? loData.FirstName
	? loData.State
	? loData.BadPropertyName
	
	Wait

End Function
```

![2020-04-28 11_58_34-Window](https://user-images.githubusercontent.com/309016/80516403-07850f00-8949-11ea-8c4b-be488f04f830.png)

**Comment by RobertvanderHulst** [comment]
This is fixed in the next build. You will either:
- have to enable Late Binding. In this case you get NO warnings at all at compile time
- disable Late Binding. Certain types, such as the Empty class, can then be compiled like this and will produce a warning such as 

`warning XS9098: Type 'XSharp.VFP.Empty' does not have a property 'FirstName'. This gets resolved to a late bound property access.`

**Comment by RobertvanderHulst** [comment]
And `loData.BadPropertyName` will now also generate a runtime error.
