### ISSUE TITLE
Add #xtranslate command to map FoxPro VarType() function to X# ValType() function.

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#375]
On message board post referenced below, I asked for using #command syntax to make VFP VarType() function calls to use the X# ValType() function.  Robert responded that #xtranslate would work best for this case. So I entered following #xtranslate command in my .prg and it now adds support for FoxPro VarType() function by mapping it to the X# ValType() function.

Can you please add this to X# .xh file in a future release?

`#xtranslate VarType(<uValue>) => ValType(<uValue>)`

From: https://www.xsharp.info/forum/public-vfp/1897-how-to-wrap-x-valtype-function-to-use-for-vfp-vartype-function

**Comment by RobertvanderHulst** [comment]
Matt,
I will not add this #xtranslate. I prefer to add the function, because when I do then this will also work in codeblocks, and also in the Evaluate() function.

**Comment by mattslay** [comment]
Okay.

**Comment by RobertvanderHulst** [comment]
The VarType() function is now part of the X# runtime
