### ISSUE TITLE
An exception occurs when debugging a DATE type in VS 2019

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#377]
Found a strange exception in debug mode (XSharp in VS 2019) when working with the "DATE" type.
Wrote the simplest example:
#
```
FUNCTION Start() AS VOID STRICT
    LOCAL d AS DATE
    d := ConDate(2020, 04, 28)
    RETURN
```

When executing the line "d := ..." step by step, an exception occurs:

> System.Threading.ThreadAbortException

I can not understand why this is happening?

P.S. Project type: VO Console Application (with default settings)

**Comment by RobertvanderHulst** [comment]
Fixed in https://github.com/X-Sharp/XSharpPublic/commit/422bc8c9b8302ae7bf424b423e08c6fc510aa34d
