### ISSUE TITLE
Cannot DELETE a record from work area of SHARED DBF... [FoxPro]

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#380]
This bug report originated as a message post on the forum: https://www.xsharp.info/forum/public-vfp/1898-cannot-delete-a-record-from-work-area

In FoxPro, DELETE command works once a DBF is opened, whether it was opened as Shared or Exclusive.

In X# if you USE a DBF in SHARED mode, then try to DELETE a record, you run-time error "Lock required (Record has to be locked)"

```
Function TestDelete()
	
	Close Databases
	Set Exclusive Off
	Var lcDbfName =  "C:\Work\lm5\AppData\xSharp_Test_Parent.dbf"

	Use (lcDbfName) Alias WA1 Shared In 0
	Set Deleted On
	Delete Next 1
	
	Field cFilename 
	
	Scan For !Deleted()
		? Recno()
		? cFilename 
	Endscan
	
	Wait

End Function
```

(Robert acknowledged the issue in a reply to that post and reported some of his findings, ans seems to have a plan in his head to address this issue).

**Comment by RobertvanderHulst** [comment]
We now automatically lock records like FoPro

**Comment by cpyrgas** [comment]
Confirmed fixed
