### ISSUE TITLE
VS 2019 Intellisense does not show member list for some situations

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#383]
**1. Intellisense does not show COM-reference members.**
Sample:
Add a new reference to ADODB (Microsoft ActiveX Data Objects 2.8 Library) in the project.
Then write the code:
```
FUNCTION Start() AS VOID STRICT
	ADODB. // nothing happens after typing a dot character ( ADBODB namespace is not displayed)
	RETURN
```

**2. Intellisense does not display nested (inner) classes.**
Sample:
```
FUNCTION Start() AS VOID STRICT
	A. // after typing a dot character, the list of displayed members (combobox) of class A does not contain class B

STATIC CLASS A
	STATIC CLASS B
		STATIC PROPERTY MyProp AS INT
			GET
				RETURN 1
			END GET
		END PROPERTY
	END CLASS
END CLASS
```
Also, in the case of nested classes, their hierarchy is not displayed in the upper part of the code editor window (see "screenshot for sample 2.png" in attachment).
![screenshot for sample 2](https://user-images.githubusercontent.com/64518775/80687130-8063a280-8ad2-11ea-8d2b-2198435093f8.png)

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by leon-ts** [comment]
Robert,
The problems described in this ticket have not been resolved, despite the fact that the ticket is marked as resolved.

1. ADODB. // nothing happens after typing a dot character (ADODB namespace is not displayed)
2. A. // nothing happens after typing a dot character, the list of members (combobox) is not displayed
3. the hierarchy of class members is not displayed correctly (see screenshot in attachment) 
![3_hierarchy](https://user-images.githubusercontent.com/64518775/86747027-263c0c00-c044-11ea-9783-44a87b073c1c.png)


Best regards,
Leonid
