### ISSUE TITLE
Fox: Behavior of Val() and numeric->string operations

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#386]
https://www.xsharp.info/forum/public-vfp/1913-couple-of-items-about-val#14400

In the following sample we are retrieving a numeric value with Val("123.456"). When running the sample in the VFP IDE:
When printing it simply with ? uVal, then
-When SET DECIMAL = 2, VFP prints 123.46
-When SET DECIMAL = 4, VFP prints 123.4560

So it looks like it sets the "visible decimals" of the returned number to the SET DECIMAL value.

But then again, a simple STR(uVal) or STR(uVal,10) shows no decimal digits!
And when you assign a literal value (123.456) to the var, then in this case printing the value with a simple "?" always prints 123.456, no matter the SET DECIMALS setting!!! Not to mention that Str(uVal , 15) always prints zero digits, no matter the SET DECIMALS setting...

Not sure what to make of this behavior... Maybe Val() is doing something else to the return value special in VFP?

```
CLEAR
SET POINT TO "."
SET DECIMALS TO 2
LOCAL uLiteral,uVal
uLiteral = 123.456
uVal = VAL("123.456")
? uLiteral,uVal
? STR(uLiteral), STR(uVal)
? STR(uLiteral , 15), STR(uVal , 15)
? STR(uLiteral , 10 , 5), STR(uVal , 10 , 5)
?
SET DECIMALS TO 4
uLiteral = 123.456
uVal = VAL("123.456")
? uLiteral,uVal
? STR(uLiteral), STR(uVal)
? STR(uLiteral , 15), STR(uVal , 15)
? STR(uLiteral , 10 , 5), STR(uVal , 10 , 5)
```

VFP returns:
123.456 123.46
123 123
123 123
123.45600 123.45600

123.456 123.4560
123 123
123 123
123.45600 123.45600

currently X#, VFP dialect returns:
123.46 123.456
123.46 123.456
123.46 123.456
123.45600 123.45600

123.4560 123.456
123.4560 123.456
123.4560 123.456
123.45600  123.45600

**Comment by atlopes** [comment]
Chris,

In case this was not made clear from the discussions in the X# VFP forum, in the VFP dialect:

- STR(x) must be strictly equivalent to STR(x, 10, 0),
- STR(x, y) must be strictly equivalent to STR(x, y, 0),
- the STR() returned value must be rounded to the nearest decimal place set or presumed in its 3rd parameter,
- and STR() does not depend on any global setting other than SET("Point").

**Comment by RobertvanderHulst** [comment]
I think it is best that we add a new STR() function to the XSharp.VFP library

**Comment by cpyrgas** [comment]
Added it and seems to do the trick, but then apparently also Val() needs to be reimplemented, because it gives different behavior when then printing the number returned by Val() with Str(). Will look into it.

**Comment by cpyrgas** [comment]
Silly me, I had the /vo14 (FLOAT literals) compiler option disabled. When this is enabled, then X# now has the same behavior as VFP, Val() of course was already taking into account the number of decimal digits in the string.
