### ISSUE TITLE
Implement EVL() function in FoxPro dialect

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#389]
See this thread for initial early communication amongst several people discuss various points about implementing the EVL() function in FoxPro Dialect.

https://www.xsharp.info/forum/public-vfp/1923-let-s-write-the-evl-function-for-x

**Comment by mattslay** [comment]
Bump...

(Can you do that here???)

**Comment by cpyrgas** [comment]
Confirm fixed.
