### ISSUE TITLE
Incompatible PSZ arithmetic

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#396]
PSZ type arithmetic is not compatible with VO. For example, pszAddr + 5 or pszAddr + **i** (where **i** AS DWORD) gives an incorrect result (does not work as expected). In VO, pointer arithmetic of type PSZ works the same as for type BYTE PTR. PSZ is essentially a pointer to a byte array (a character memory area) whose end is a zero byte (0). Therefore, the expression pszAddr + 1 is an address increment of 1 byte. But this does not happen in XSharp.

Example:
```
LOCAL p AS PSZ
LOCAL i AS DWORD

p := MemAlloc(100)
MemCopyString(p, "abc", 3) // ok
i := 3
MemCopyString(p + i, "de", 2) // it gives an incorrect result
MemCopyString(p + 3, "de", 2) // it gives an incorrect result also
MemFree(p)
```

**Comment by RobertvanderHulst** [comment]
The PSZ class does not have an operator for a PSZ and a Numeric value. This needs to be added.
One potential problem here is that VO and Vulcan have a different behavior for PSZ indexers: VO has 1 based indexers and Vulcan 0 based (that is a bug in Vulcan).
We'll look at the current dialect to decide whether the indexer needs to be 0 (Vulcan) or 1 (Other dialects) based.

**Comment by leon-ts** [comment]
Robert,

Yes, there was such a problem with Vulcan, and I ran into it (a long time ago) when I transferred one of my applications from VO to Vulcan. Later, I encountered the same problem in XSharp, about which I wrote to you on the forum.

https://www.xsharp.info/forum/public-vo-vn/363-incompatible-indexing-in-case-of-access-to-psz-bytes-between-vo-and-xsharp

And you fixed it.

Best regards,
Leonid

**Comment by RobertvanderHulst** [comment]
Check if the Dialect test can be done at compile time instead of inside the runtime

**Comment by RobertvanderHulst** [comment]
Leonid,
In retrospect I was wrong in my code. Nothing has to be changed in the compiler as well.
In VO :
```
p := StringAlloc("abc")
? p[1]  // shows 97
```
In Vulcan
```
p := StringAlloc("abc")
? p[1]  // shows 98, first char in psz = p[0]
```

However the operation 
`MemCopyString(p + 3, "de", 2)`

can be the same in both dialects. They both operate on the 4th character. In Vulcan that is the 0 based character (0+3) and in VO the 1 based character (1+3).
Inside the PSZ operator that adds a number to a PSZ we do not have to make a distrinction. when we add 3 we want to have the 4th character always

**Comment by leon-ts** [comment]
Robert,
It's great!

Best regards,
Leonid
