### ISSUE TITLE
PtrLen

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#397]
Currently PtrLen function is marked as obsolete.
I've inspected the code of XSharp.FixedMemory static class and found that the size of an allocated buffer is kept inside its description block, so it may be not a big problem to retrieve it with PtrLen.
May I reckon that it will be implemented?

**Comment by RobertvanderHulst** [comment]
Serggio,
PtrLen in VO uses an api function (VirtualQueryEx) and can examine any pointer.
We could implement PtrLen for pointers allocated with MemAlloc() and return 0 for pointers that are not allocated by the X# runtime. 
Would that be OK with you ?

Robert

**Comment by Serggio** [comment]
> Serggio,
> PtrLen in VO uses an api function (VirtualQueryEx) and can examine any pointer.
> We could implement PtrLen for pointers allocated with MemAlloc() and return 0 for pointers that are not allocated by the X# runtime.
> Would that be OK with you ?
> 
> Robert

Yes, absolutely! Thank you in advance!

**Comment by Karl1155** [comment]
Serggio,

isn´t MemLen() what you´re looking for ?

https://github.com/X-Sharp/XSharpPublic/blob/00112234f8b936afa513558869ad29d7ab4dceef/Runtime/XSharp.RT/Functions/Memory.prg#L342


```
p1 := memalloc ( 4 )
? memlen ( p1 ) // 4
memfree ( p1)

p2 := stringalloc ( "Test" )
? memlen ( p2 )  // 4 + 1  
memfree ( p2 )
```

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
Yes, that would work too.
But it does not hurt to add a function that checks to see if the pointer was allocated by us and to return 0 when it is not. Or we could  try to call the VirtualQueryEx (like VO) when running on Windows. I'll check what I can do.

Robert
