### ISSUE TITLE
LOGIC/DWORD ambiguity with some Win32 API function calls

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#401]
I know that LOGIC type is implemented as System.Boolean, so if it is casted from DWORD and back to DWORD, and if there was something > 1 in original DWORD, it would turn to 1.
And that makes a problem with function **TrackPopupMenuEx** which is described as having LOGIC return type. But when working with TPM_RETURNCMD flag, this return value should be treated as a DWORD which is an ID of the selected menu item.
I've made another _DLL prototype for such a case:

```
_DLL FUNCTION TrackPopupMenuExDWord(hMenu AS PTR, fuFlags AS DWORD, x AS INT, y AS INT,;
	hwnd AS PTR, lptpm AS _winTPMPARAMS);
	AS DWORD PASCAL:USER32.TrackPopupMenuEx
```

But maybe you have a better solution for it. There is also an option to change the prototype for the original **TrackPopupMenuEx** as returning DWORD, but this time those who expect LOGIC as a result type should do a cast, though quite a simple and unambiguous one.
Would accept any your decision on how this should be done.

**Comment by RobertvanderHulst** [comment]
Serggio,
The prototypes in the Windows SDK library follow the prototypes in the Windows SDK;
This function is documented to return a BOOL As you can see here:
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-trackpopupmenuex

You are right that the docs say that in case of TPM_RETURNCMD  the return value should be treated as a DWORD.
Your solution (adding a separate function that returns a DWORD) is a good solution I think.
Casting the logic to a dword is not what I would recommend.
