### ISSUE TITLE
Feature request: Support syntax cString := "abc""def""ghi"

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#407]
https://www.xsharp.info/forum/public-product/1965-escaping-quotes-like-in-c

In c#, this is supported:

string sString;
sString = @"abc""def""ghi";
System.Console.WriteLine(sString);

prints:
abc"def"ghi

Maybe it should be supported in X# as well? For all dialects probably?

**Comment by RobertvanderHulst** [comment]
I don't think we should add this.
