### ISSUE TITLE
DEFINEs with _CHR()

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#408]
Consider these examples:
```
DEFINE TEST1 := "Test"
DEFINE TEST2 := "Test" + _CHR(9) + "123"
DEFINE TEST3 := _CHR(ASC_TAB)
DEFINE TEST4 := "Test" + _CHR(ASC_TAB) + "123"		// XS0133 error
DEFINE TEST5 := ASC_TAB
DEFINE TEST6 := _CHR(TEST5)
DEFINE TEST7 := "Test" + _CHR(TEST5) + "123"		// XS0133 error
```

TEST4 and TEST7 are not compiled and issue errors:
Error XS0133	The expression being assigned to '....Exe.Functions.TEST4' must be constant
Error XS0133	The expression being assigned to '....Exe.Functions.TEST7' must be constant

**Comment by RobertvanderHulst** [comment]
Serggio,
The _CHR() pseudo function is compiled as a string literal when its argument is also a literal.
ASC_TAB is a define in the XSharp.Core assembly and therefore the compiler (at parse time) does not recognize that this is a literal.
I'll see what I can do.

Robert

**Comment by leon-ts** [comment]
Robert,

I faced the same problem.

For example:
DEFINE MyDef := "MyDef" + _CHR(100)

In the latest version, the compilation of the above expressions works as follows:
- works with values from 1 to 127, for example _CHR(100)
- does not work with other values, for example _CHR(0) or _CHR(200)
- the compiler interrupts without a clear error message if the value is negative, for example _CHR(-10)

Best regards,
Leonid

**Comment by RobertvanderHulst** [comment]
Leonid,
Values between 1 - 127 are the same for all code pages.
Values > 128 are code page dependent and cannot be calculated at compile time. 
Chr(0) should work. I'll reopen the ticket.

**Comment by RobertvanderHulst** [comment]
For now this works:
DEFINE MyDef := e"MyDef \u00FF" 
DEFINE MyDef := e"MyDef \u0000" 
DEFINE MyDef := e"MyDef \u4e01"  // Chinese Han character

**Comment by leon-ts** [comment]
Robert, thanks!

**Comment by RobertvanderHulst** [comment]
Using a _Chr() with a number between 0 and 127 now works as expected. Numbers between 128 and 255 now produce a warning:  warning XS9100: Literal value for define has an Ansi character between 128 and 255 which depends on the current codepage. Consider to use a Unicode literal inside the string instead.
