### ISSUE TITLE
There may be an error in the BLOBGet method of the DbServer class.

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#411]
The DBFFPT driver, when processing a DBFFPT:Info(BLOB_GET) request, expects the oNewValue parameter to be of type OBJECT[] (an array of objects). But the DbServer class passes it an ARRAY type.
`uRetVal := { wPos,nStart,nCount } // uRetVal AS USUAL`
And finally, checking the type of the oNewValue parameter inside DBFFPT:Info(BLOB_GET):
`IF oNewValue IS OBJECT[] VAR oArray`
will not work.

In this case, a separate function BLOBGet() passes parameters correctly: `<OBJECT>{...}`

**Comment by cpyrgas** [comment]
Thanks Leonid, but from what I see that should be ok, because DbServer:BLOBGet() does not call DBFFPT:Info(BLOB_GET) directly, it instead calls VoDbInfo( BLOB_GET ), which in turn calls VoDb.Info() and this converts the ARRAY to OBJECT[] (line 56 of Vodb.prg). I tested it with the debugger and indeed DBFFPT:Info() does get the correct arguments.

Did you look into this while trying to diagnose a problem? If yes, can you please give some info about the problem itself and a sample please?

**Comment by leon-ts** [comment]
Chris,
I did not reproduce the problem using a real test. Therefore, I wrote "There **may be** an error". As I mentioned in the XSharp forum, I was involved in transporting my SQL RDD from VO to XSharp (I had already completed it successfully), and when I got to the processing Info(BLOB_GET), I found that it began to accept not ARRAY as before, but OBJECT[]. To better understand the changes, I looked at the XSharpPublic sources and came across the problem that I described initially. I went to the "GoTo Definition" menu from VoDbInfo to VoDb.Info, but the transition was not performed further (clicking the "GoTo Definition" menu on VoDb.Info did not work). This is another XSharp integration issue in VS 2019. Some of the "GoTo Definition" transitions work, and some do not. Well, since part of the RDD functions is located in XSharp.Core, part in XSharp.RDD, and part in XSharp.RT, I was completely confused :)) and did not look further. And just in case, I wrote in Issues, may be an error.
I apologize for the vain concern!

**Comment by cpyrgas** [comment]
No, no, no need to apologize at all and thanks for posting this, it could had indeed been a problem needing fixing! I only misunderstood your intentions, but got it now. Please do not hesitate to report anything else also in the future, even if it turns out not to be a real problem at the end!
