### ISSUE TITLE
Wrong shortname for Wednesday - Internet SDK

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#412]
In the GetMailTimeStamp() function there´s the line 

`cRet := SubStr("SunMonTueWenThuFriSat",(3*nTmp)-2,3)`

The substring "Wen" must be changed to "Wed"

https://github.com/X-Sharp/XSharpPublic/blob/master/Runtime/VOSDK/Source/VOSDK/Internet_SDK/FUNCS.prg#L725

Karl-Heinz

**Comment by cpyrgas** [comment]
Thanks, fixed. Karl-Heinz, in case you'd like an updated dll, please send me a PM.
