### ISSUE TITLE
Incompatible behaviour of VODBSeek with two parameters

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#414]
XSharp implements overloading the VODBSeek function with three parameters (in VO, this function has two parameters). Through the third parameter of the overloaded function, you can pass the value of lLast. But since this parameter is not in the VODBSeek function in VO, the behavior of this parameter was determined through the fLast field in the _DbScopeInfo structure (set via VODBSetScope). But in XSharp, the VODBSeek function with two parameters does not use information from this structure and always passes the lLast parameter equal to FALSE. This situation has been verified since I encountered an error in my program.

**Comment by cpyrgas** [comment]
Hi Leonid, can you please also include a small code sample showing this problem?

**Comment by leon-ts** [comment]
Sample code:
```
	LOCAL scopeInfo AS DbScopeInfo
	LOCAL lFound AS LOGIC
	LOCAL xSearchValue := <some value> AS USUAL

	scopeInfo := DbScopeInfo{}
	scopeInfo:Last := lLast
	VODBSetScope(scopeInfo)

	IF !VODBSeek(xSearchValue, FALSE) // two parameters version
		THROW Exception{"some error"}
	ENDIF

	lFound := VODBFound()

	scopeInfo:Clear()
	VODBSetScope(scopeInfo)
```
This approach was used in VO if you need to find the last value. You could also use DBSeek, which internally did similar code. But now we are talking about cases where the program immediately performs direct VODBSeek.

The best solution, of course, is to find all such places in the program and replace them with the new version of VODBSeek with three parameters. But most of this code has not yet been translated into XSharp (waiting in line for a very large VO project). And since most of this code was not written by me, in order not to make additional mistakes, I would like the old approach with Seek to be available in XSharp as an alternative to the new one. And later, it will be possible to carry out the necessary replacements and optimization.

**Comment by cpyrgas** [comment]
Thanks! I think you will not need to make any changes in your code for that, I guess Robert will be able to make it VO compatible.

**Comment by RobertvanderHulst** [comment]
I will change the VoDbSeek with 2 parameter and will let it take the value from the scopeinfo for the lLast parameter.

**Comment by RobertvanderHulst** [comment]
Fixed
