### ISSUE TITLE
Problem opening Windows Form in the designer

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#419]
When a form prg contains any of the following, it cannot be opened in the designer:

PROTECT n := -1 AS INT
PROTECT n2 := +123 AS INT
PROTECT o := NULL_OBJECT AS OBJECT

Robert's negative number hatred strikes back :)

[WindowsFormsApplication52.zip](https://github.com/X-Sharp/XSharpPublic/files/4814003/WindowsFormsApplication52.zip)

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
Robert, the problem with the INT PROTECTs is fixed now, but the problem with 

PROTECT o := NULL_OBJECT AS OBJECT

still exists, the form does not open. Changing NULL_OBJECT to NULL does take care of it.

**Comment by RobertvanderHulst** [comment]
I cannot reproduce this. Can you verify that the folder
c:\Windows\Microsoft.NET\assembly\GAC_MSIL\XSharpCodeDomProvider has assembly version 2.1 and file version 2.5.0.0 ?

**Comment by cpyrgas** [comment]
Yeah, that's it. If you re-download the solution, to make sure there's not something else changed, you do not get the problem? Here the form does not open, but if I adjust the NULL_OBJECT line, it's all ok. Anyway, it isn't very important, it's an edge case I guess

**Comment by RobertvanderHulst** [comment]
Which VS version (include the build number, so 2019 16.6.2 or something like that)?
It works here in all builds that I have installed/
And maybe you can delete the hidden .vs folder in your solution before retrying ?

**Comment by cpyrgas** [comment]
Good point, it's probably due to my older VS. It's VS 2017, 15.9.11

I tried in another PC with the latest VS 2017 and VS 2019 and it works fine with NULL_OBJECT! Sounds very weird to me that this has to do with the VS version, but I think issue is closed now!
