### ISSUE TITLE
Member completion showing only one parent iVar

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#420]
Member completion below only displays the "nnn" member.

```
CLASS Parent
EXPORT nnn AS INT
EXPORT mmm AS INT
EXPORT ppp AS INT
END CLASS

CLASS Child INHERIT Parent
END CLASS

FUNCTION Start() AS VOID
LOCAL o AS Child
o:
```

**Comment by RobertvanderHulst** [comment]
The EXPORT keyword is an alias for PUBLIC just like HIDDEN is a keyword for PRIVATE.
The parser was confusing the variable declaration with a PUBLIC/PRIVATE statement, so it was not parsing the 2nd and 3rd instance variables. This would not have happened for PROTECTED instance variables.
