### ISSUE TITLE
Indenting not working correctly in some cases

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#421]
I cannot reproduce this in standalone files, but try opening the Runtime solution and open DBServer.prg, of the VORDDClasses. Go for example in line 46, which contains this code of the __AcceptSelectiveRelation() method:

	LOCAL dwCurrentWorkArea AS DWORD

Now put the caret at then end of this line and press enter. A new line is inserted and the caret is correctly placed directly below the "L" charaacter of the above line. Now press enter again, a new line is created but this time the caret is placed at the very beginning of the new line.

Doing the same thing in other projects does not reproduce the problem.

**Comment by RobertvanderHulst** [comment]
I cannot reproduce it. What is the setting on TextEditor\XSharp\Tabs for Indenting ?

**Comment by cpyrgas** [comment]
I am on "Smart", 4, 4, Keep tabs

**Comment by cpyrgas** [comment]
This is still happening here. I am getting similar strange indenting behavior in other projects as well.

**Comment by cpyrgas** [comment]
This still happens here. After the new build is out, I will try to figure out why it happens in some projects and not in others.

**Comment by cpyrgas** [comment]
Still happening here as before. Apparently VS does not like me for some reason :)
Robert, please feel free to completely close those similar tickets if you estimate that I'm the only one experiencing this behavior, I really have no idea what I might be doing wrong.

**Comment by cpyrgas** [comment]
This time I can confirm it is fixed!
