### ISSUE TITLE
Member completion not working in some cases

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#422]
Open the attached solution, it has this code (do not just type it manually!):

FUNCTION Start() AS VOID
IF FALSE
	LOCAL nnn AS INT
	nnn
ENDIF

now go a the end of the "nnn" line and type a colon. Member completion is not invoked.

[ConsoleApplication40.zip](https://github.com/X-Sharp/XSharpPublic/files/4842433/ConsoleApplication40.zip)

**Comment by RobertvanderHulst** [comment]
Fixed in next build
