### ISSUE TITLE
Tag(), TagCount() and Order() problems - FP dialect

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#423]
While trying out some Tagxx() functions i noticed some problems. The sample uses a structural and a non-structual compound index. Each CDX has 3 Tags.

-TagCount () does not differentiate whether a CDX is specified or not. The func always returns the number of all available (6) TAGs.

-The Tag() function needs a parameter check since I always have to type e.g. Tag ( , 1) instead of Tag (1)

-My FP-DOS Order() results are different than the X# Order() results. I created a Order_Fix() function that shows the same results as FP-DOS. Maybe someone from the VFP community verifies that ?

code to reproduce it and the required DBF and CDX files can be found here:

https://www.xsharp.info/forum/public-vfp/2023-tagxxx-functions

Karl-Heinz

**Comment by Karl1155** [comment]
a note about die cdx()/mdx() functions:

the current cdx() implementation works differently than the Fox one. Let´s say i do this:


use small  // 3 auto open tags 
set index to small1x  // 3 tags
set index to first additive  // 1 tag 
set index to last additive // 1 tag

// in total there are 8 Tags 

The Fox `Cdx( <nIndexNumber>) `results are:


1 D:\TEST\SMALL.CDX
2 D:\TEST\SMALL1X.CDX
3 D:\TEST\FIRST.CDX
4 D:\TEST\LAST.CDX
5
6
7
8

and not:

1 D:\TEST\SMALL.CDX
2 D:\TEST\SMALL.CDX 
3 D:\TEST\SMALL.CDX 
4 D:\TEST\SMALL1X.CDX 
5 D:\TEST\SMALL1X.CDX
6 D:\TEST\SMALL1X.CDX
7 D:\TEST\FIRST.CDX
8 D:\TEST\LAST.CDX

**Comment by RobertvanderHulst** [comment]
Fixed
