### ISSUE TITLE
XML output file name does not match project configuration

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#424]
When compiling a XSharp project, a documentation file (XML) is always created with the project name in the solution, instead of using the name of the file from the project properties (section <DocumentationFile> SomeFile.Xml </DocumentationFile>).

For example,
the project is called "001 - MyCompany.MyProject"
output file name: MyCompany.MyProject.dll
in the project properties the documentation file is set as "MyCompany.MyProject.xml"

after Build, the file "001 - MyCompany.MyProject.xml" is created on the disk instead of the file "MyCompany.MyProject.xml"

**Comment by RobertvanderHulst** [comment]
Copy the attached file to one or all of the following folders to fix this:
VS 2015 : "c:\Program Files (x86)\MSBuild\XSharp\" for VS 2015
VS 2017 : "c:\Program Files (x86)\Microsoft Visual Studio\2017\\**Version**\MSBuild\XSharp" 
VS 2019 : "c:\Program Files (x86)\Microsoft Visual Studio\2019\\**Version**\MSBuild\XSharp" 

**Version** can be Enterprise, Professional, Community or BuildTools

[XSharp.CurrentVersion.zip](https://github.com/X-Sharp/XSharpPublic/files/4870133/XSharp.CurrentVersion.zip)

**Comment by leon-ts** [comment]
Robert, thanks!
Now it works correctly!

**Comment by leon-ts** [comment]
Robert,
There was a strange situation (not critical). Now, when assembling the DLL, the XML doc file is copied not only to the Output folder (bin\Release), but also to the project source folder (Project folder), where the PRG files are located.
