### ISSUE TITLE
Form designer cannot resolve custom controls that do not belong to the default namespace

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#426]
Attached form uses a control defined in the same assembly  named WindowsFormsApplication55.MyButton. When trying to open the form, an error is reported: 

"Could not find type 'MyButton'. Please make sure that the assembly that contains  this type is referenced. If this type is a part of your development project,  make sure that the project has been successfully built using settings for your  current platform or Any CPU."

IF the MyButton class is moved to the default namespace, then the form opens fine.

[WindowsFormsApplication55.zip](https://github.com/X-Sharp/XSharpPublic/files/4869681/WindowsFormsApplication55.zip)

**Comment by RobertvanderHulst** [comment]
Fixed
