### ISSUE TITLE
XML documentation file is created twice

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#432]
When building an assembly, an XML documentation file is created not only in the output folder (bin\Release), but also in the project source folder. As a result, with each execution of the Build or Rebuild command, the GIT system displays the presence of a new commit (a new XML file), although there really were no changes in the source code. Even if you commit of this XML, then with the next Build or Rebuild the GIT system will again show that there is a new XML file.

Previously, the XML documentation file was only created in the output folder (bin\Release).

**Comment by RobertvanderHulst** [comment]
Leonid,
Can you  test the attached targets file.
It should be copied to:
```
VS2015: c:\Program Files (x86)\MSBuild\XSharp
VS2017: c:\Program Files (x86)\Microsoft Visual Studio\2017\<edition>\MSBuild\XSharp
VS2019: c:\Program Files (x86)\Microsoft Visual Studio\2019\<edition>\MSBuild\XSharp
where <edition> is Professional, Enterprise, Community or BuildTools
[XSharp.CurrentVersion.zip](https://github.com/X-Sharp/XSharpPublic/files/4902081/XSharp.CurrentVersion.zip)


```

**Comment by leon-ts** [comment]
Robert,

This file broke my Visual Studio :))
All projects in all solutions are marked as Unloaded and do not load.

**Comment by RobertvanderHulst** [comment]
Did you use Windows Explorer to extract the file ?
And did you "unblock" the file after extracting ?

**Comment by leon-ts** [comment]
Robert,
I prefer Far Manager :))
The XSharp.CurrentVersion.targets file was extracted correctly and does not have the "Downloaded from Internet" property.
I repeated the action again. This time I extracted the file using Explorer. The result is the same.

**Comment by RobertvanderHulst** [comment]
Ok, I found it. I must have touched the file accidentally before zipping and I have added a '=' char where it did not belong. Here is a new version.
[XSharp.CurrentVersion.zip](https://github.com/X-Sharp/XSharpPublic/files/4902951/XSharp.CurrentVersion.zip)

**Comment by leon-ts** [comment]
Code compilation fails:
`File name '<my project path>\obj\Release\' is empty, contains invalid characters, has a drive specification without an absolute path, or is too long`

**Comment by RobertvanderHulst** [comment]
Leonid,
Can you mail me your xsproj file ?

Robert

**Comment by leon-ts** [comment]
Robert,
in attachment
[xsproj.zip](https://github.com/X-Sharp/XSharpPublic/files/4903349/xsproj.zip)

**Comment by RobertvanderHulst** [comment]
[XSharp.CurrentVersion.zip](https://github.com/X-Sharp/XSharpPublic/files/4911853/XSharp.CurrentVersion.zip)
Leonid,
Can you test the attached targets file.
It should be copied to:

VS2015: c:\Program Files (x86)\MSBuild\XSharp
VS2017: c:\Program Files (x86)\Microsoft Visual Studio\2017\<edition>\MSBuild\XSharp
VS2019: c:\Program Files (x86)\Microsoft Visual Studio\2019\<edition>\MSBuild\XSharp
where <edition> is Professional, Enterprise, Community or BuildTools

**Comment by leon-ts** [comment]
Robert,

After compilation, the XML file:
- created with the correct name - this is correct
- in the correct location (output folder) - this is correct
- the second XML file is not created in the source code directory  - this is correct

The problem described in the ticket has been fixed. I do not observe other problems.
Many thanks!

Best regards,
Leonid
