### ISSUE TITLE
Realy need a database event filter (for DbNotifyEventHandler)

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#436]
I started applying database event notifications (a very cool thing in XSharp). But I realized that the event type filter is very lacking. For example, I need to track table opening and table creation. In the event handler function I check the type of operation, but the problem is that the handler itself is always called (for any operation with a table). And if I have 100500 FieldPut calls and other operations that I don’t need to monitor, then a handler will be called for each call. This reduces application performance.

One possible solution I see is the following:
- assign bit values ​​(or values ​​to the power of two) to the members of the DbNotificationType enumeration
- implement a function (or method) to which the user can pass a filter of types of operations of interest (mask, for example, DbNotificationType.FileOpen | DbNotificationType.FileCreate | ...)
- check the specified filter in the CoreDb.RaiseEvent method and do not call the event handler if the filter does not match.
- add the attribute [MethodImpl(MethodImplOptions.AggressiveInlining)] to the CoreDb.RaiseEvent method

Best regards,
Leonid

**Comment by RobertvanderHulst** [comment]
Leonid,

This was not designed to be used during production, but only to be used during testing.
If you want to use this for production and want to suggest improvements then please clone the repo and change the code until you get the result that you want and then send us a pull request.

Robert

**Comment by leon-ts** [comment]
Robert,

In multi-user HR systems, administrators are very much in demand for tracking problematic data changes. Thus, all these are demanded things at the productive level, and it is very good that this is available in XSharp. Earlier, for these purposes, we at VO implemented a special logging driver, which, via RddList, is attached to the standard list of drivers. When transporting the project into XSharp, we noticed that the WrapperRDD class in conjunction with the notification system (DbNotifyEventHandler) is suitable for these purposes.

I'm not sure that the solution I proposed above (filter by mask) is successful. Because this filter will be common for everyone who registers an event listener (if several DbNotifyEventHandler are installed). And it is necessary that it is possible for each individual DbNotifyEventHandler to configure its own filter. But I understand you. I need to propose a solution and implement it. And then pass it to you for revision.

Best regards,
Leonid

**Comment by RobertvanderHulst** [comment]
Leonid,

Exactly. This was developed for a customer (who paid for it). So it does what they wanted / needed. 
If you want more or different behavior then you either do it yourself or you hire us to add the functionality.
Without external "sponsorship" we will most likely not touch this code ourselves.

Robert
