### ISSUE TITLE
VOGUI form editor lacks important functionality

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#437]
The VOGUI form editor in XSharp does not display additional properties of user-created controls inherited from _VOCutsomControl.
The project is imported into XSharp from VO using VOXporter.
The cavowed.inf file has a description like this:
```
[CONTROL:CUSTOMCONTROL:ILINK]
Assign01=Use for Tooltip,UseHLforToolTip(BOOL)
WindowStyle01=Alignment,SS_LEFT:SS_CENTER:SS_RIGHT(ILINKALIGN)
ContTitle=ILink
Name=ILink
ClassName=Static
OptClassName=_VOCustomControl
...
```
The line:
**WindowStyle01=Alignment,SS_LEFT:SS_CENTER:SS_RIGHT(ILINKALIGN)**
allows you to set control's alignment in the editor.

VO understands this line and displays the corresponding combobox in the editor (see screenshot 1).
![scr1](https://user-images.githubusercontent.com/64518775/87059453-022e2580-c212-11ea-9515-7ce262c6a8c2.png)
XSharp ignores this line (see screenshot 2)
![scr2](https://user-images.githubusercontent.com/64518775/87059464-05c1ac80-c212-11ea-965e-d59d8752e7c8.png)

**Comment by cpyrgas** [comment]
Leonid, can you please attach the full cavowed.inf file together with any additional files it may need?

Also can you please attach an aef of a small VO test app that demonstrates how you use such a control and styles?

**Comment by leon-ts** [comment]
Chris,

I can give cavowed.inf, but I'm not sure I can pass the demo application. The implementation of the components I mentioned is contained in several large commercial libraries. Additionally, there are still resources without which it either will not compile or run.

What I described in this ticket is not something that I invented. This is a standard feature that is present in VO. There is a special CustomControl control on the basis of which you can create your own graphic components (for example, using OWNERDRAW technology). Also, such components can be placed in the editor of VOGUI forms, describing them in the file cavowed.inf. This is also a standard feature.

[cavowed.zip](https://github.com/X-Sharp/XSharpPublic/files/4898005/cavowed.zip)
[NotCompiledApplication.zip](https://github.com/X-Sharp/XSharpPublic/files/4898014/NotCompiledApplication.zip)

**Comment by cpyrgas** [comment]
I asked for a (just a very small) test VO app just to make it easier for me to compare between the VO and the X# version of the Window editor and locate the problem more easily. Thanks for the cavowed file, will look into it and if I need additional help will get back to you.

**Comment by cpyrgas** [comment]
Hi Leonid,

It seems to work fine here, see screenshot: 

![ILink control](https://user-images.githubusercontent.com/14542129/87069411-cef29300-c21f-11ea-8495-59c69c3b5ad4.png)

but I am most likely doing something different than you, so can you please post a sample:

-Please create a new VOMDI sample app in VO
-Create a window and add such a control to it
-Make sure that it does show the custom properties
-Port this app to X# with VO Xporter. 

Is also this sample showing the same problem in the X# version? If yes, please zip the solution and attach it together with the aef

**Comment by leon-ts** [comment]
Chris,

I did as you wrote, and all user properties are displayed and working. And I understood why this does not work in my working application. In the test case, I placed the ILink control on the form as ILink (from the toolbar). And in my working project, it was a CustomControl, which indicated the property "Inherit from Class" as ILink. And I did not pay attention to it. VO in this case also does not show user properties. Therefore, the question is being removed. Thanks!

**Comment by leon-ts** [comment]
Chris,

Do you plan to make a grid in the form editor to make it more convenient to align controls? How it is implemented in VO.

Best regards,
Leonid

**Comment by cpyrgas** [comment]
OK, thanks for the info Leonid, glad it is working for you now!

**Comment by leon-ts** [comment]
Chris, thanks!
