### ISSUE TITLE
Slow Solution Explorer

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#44]
From Trevor:

1. In the Solution Explorer in our large projects, when we have a folder
that has a substantial number of .prg branches under it. If we expand
the folder and then just want to scroll through the solution in the
solution explorer window using the scroll bar – it is quite sluggish and
has quite noticeable lags when scrolling. When we collapse any folders
with large numbers of branches under them – then the scrolling returns
to the normal speed that you would expect

More info: with the Solution Explorer being laggy when scrolling when a
branch with a number of sub-branches is expanded - I just tested now and
we have some with lots of subbranches, but I just opened on with 30
sub-branches and it had the same issue.

This happens consistently is in our largest project which I believe I
have sent to you before for testing - if you cant replicate it let me
know and I am happy to resend that to you if you need as that one,
though not a show stopper is the biggest issue we have as far as day to
day operating goes.

2. Solution Explorer (Screen Shot Example below) – we used to use the
Pending Changes filter in Vulcan/VS 2012 to be able to see items in the
solution that had pending changes using the button highlighted in the
screen shot below. This still works in X# - but is quite slow compared
to how it used to work in Vulcan and per second screen shot below on our
large projects results in the message that X# has caused excessive
unresponsiveness

**Comment by RobertvanderHulst** [comment]
Can you test this with the current build

**Comment by cpyrgas** [comment]
That was reported by Trevor when working himself in his own solution, it's not something I could reproduce in my machine. How can we tag him here so he looks into it?
