### ISSUE TITLE
Refinement of the VOGUI window editor in XSharp

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#440]
The XSharp form editor (VOGUI) lacks some convenient things that were in the VO form editor:
- grid and grid settings (step) for easy alignment of controls. Now, without a grid, in a complex window with a large number of controls, their alignment is becoming a very difficult task.
- saving the position of the windows "Window Editor Properties" and "Toolbox" between Visual Studio sessions. Now, if you close Visual Studio, the next time you open it, the XSharp window editor will open the windows in default positions. This is not critical, but all the time you have to move them.
- Control Order (menu in VO)

Best regards,
Leonid

**Comment by cpyrgas** [comment]
Hi Leonid:

-Grid: You can use CTRL+G (while the WED has focus) in order to show/hide the grid. But I agree there should be a toolbar button to do this as well and there should be a way to chose grid size. Will need help from Robert to add those options in the VS options page for X#

-Tool windows: Agreed, would be nice to be able to save their positions. Although there's always the fear they get saved in a bizarre position and then it's difficult to find them to drag them back in :).

-Control Order: You should have access to this one via the VS menu View->Tab Order

**Comment by leon-ts** [comment]
Hi Chris,

Excellent! It turns out that all this is available!
When you pointed me to the menu "View" (control order), then I even found the item "View X# Grid" (if I forget the key combination CTRL+G). Many thanks for the info!

But the settings (step) of the grid is very necessary. I would even be happy with the ability to set this value manually, without a menu, in some configuration file or registry.

Regarding window position: the position of the window can always be checked and adjusted programmatically, if, for example, it goes beyond the limits of the main application window :)) I often have to do this control in my projects. For example, a user may transfer to another computer with a different screen resolution. In this regard, I prefer to do not only control, but also save such settings in the registry in the HKEY_CURRENT_USER branch.

Best regards,
Leonid

**Comment by RobertvanderHulst** [comment]
There is already a X# Toolbar in VS (right click on the toolbar and you can "show" it) with a Show X# Grid and Test X# dialog button.
The buttons on this toolbar should be enabled when the Window editor is open and then also in the View menu there are 2 menu items for these buttons.

![image](https://user-images.githubusercontent.com/14240939/87150378-33f6c900-c2b2-11ea-887d-d7ea721bf811.png)

The View menu also has a "Tab Order" entry (this is a normal VS menu option for the Windows Forms editor) which brings up the Control order dialog

I'll try to change the properties of the X# Toolbar, so it will appear automatically when the VO Window editor is opened. I can probably also add a button for the Tab Order to that toolbar.
Saving positions and grid setting and other options is on my todo list. I'll add a dialog in the Tools/Options window for this. I have listed the following settings:

**Form Editor**
- Grid X + Y + Grid enabled Yes/No
- Paste OffSet X and Y
- Partial Lassoing Yes/No
- Default Controlname prefix
- External Anchors
- Position and size for Property Window
- Position and size for Toolbox

**DbServer editor**
- Default RDD
- Default Parent Class

**Menu editor**
- Default Parent Class menu
- Default Parent Class Toolbar

**FieldSpec editor**
- Default Parent Class

**All editors**
- Add code to the ProjectSystem to return a list of types that inherit from a certain parent type (for the "Inherit From" comboboxes)
- Add code to the ProjectSystem to list files in the solution of a certain "binary" type (so you can open a form and clone it for example)

**Comment by leon-ts** [comment]
Wow! ))

**Comment by RobertvanderHulst** [comment]
And would you like it if the Toolbox of the Window Editor is replaced by the standard Toolbox of Visual Studio ?

https://github.com/microsoft/VSSDK-Extensibility-Samples/tree/master/Editor_With_Toolbox has an example of an editor with custom buttons on the VS Toolbox.
We need to implement IVsToolboxUser on the EditorPane, query for IVsToolbox and call IVsToolbox.AddItem with the data for the buttons/images
The editorpane will get events when an toolbox item is selected and also events to control of an item is enabled/disabled

**Comment by leon-ts** [comment]
Hard to say. I think this question should be asked on the general forum. After all, it will affect everyone. If at the same time the possibilities of VO are not lost, then I personally do not mind.

**Comment by RobertvanderHulst** [comment]
I have just implemented Saving/Restoring positions of the Properties and Toolbox windows

**Comment by RobertvanderHulst** [comment]
And the toolbar for the WED is now also visible by default.

**Comment by leon-ts** [comment]
Robert,

var keyName := "VOED_"+name

Maybe you mean: VO**W**ED_ ?

**Comment by RobertvanderHulst** [comment]
Leonid, no I meant VOED_ because the properties window is also used by the DED, FED and MED (DbServer Editor, FieldSpec editor and Menu Editor). The Toolbox on the other hand is only used by the window editor.
Btw the toolbar for the window editor looks like this:
![image](https://user-images.githubusercontent.com/14240939/87412040-ce178380-c5c8-11ea-84dd-a340d912dd9c.png)
From Left to Right:
Grid Settings
Test Window
Control Order

**Comment by cpyrgas** [comment]
Robert, will need to check if updating the registry while the tool window is still being moved causes any problems/slow downs in the motion.

**Comment by RobertvanderHulst** [comment]
On my machine there is no noticeable delay. 
I'll zip the extension folder so you can test it at your side.

**Comment by leon-ts** [comment]
An ideal option would be to use something like **LocationChanged** instead of **Move**. If there is such an opportunity.

**Comment by leon-ts** [comment]
In the version with LocationChanged, it is important to verify that this is not called programmatically, for example, from your own RestoreLocation method. An alternative would be to maintain a position in the Closed event.

**Comment by RobertvanderHulst** [comment]
Leonid,
This does not make a different. This is the code for LocationChanged:
```
protected virtual void OnLocationChanged(EventArgs e)
	{
		OnMove(EventArgs.Empty);
		(base.Events[EventLocation] as EventHandler)?.Invoke(this, e);
	}
```

**Comment by leon-ts** [comment]
Robert,
Apparently in the NET events, OnLocationChanged and OnMove are analogues in the Win32 behavior WM_WINDOWPOSCHANHGED and WM_MOVE. If WM_WINDOWPOSCHANHGED is not processed (reaches the default handler), then WM_MOVE is generated. My idea was to maintain a position at the end of an event (like a DragEnd). Otherwise, the whole process of dragging the window will cause the procedure to save the position (many times in a row and can really cause friezes). In VO, I do this in the Window:Close method. This approach has one drawback - if the window closes abnormally, then the Close method may not be called. But this is an emergency situation and therefore it can be neglected.

**Comment by cpyrgas** [comment]
Robert, my CPU goes to 20% usage when moving the window around, but indeed it does not make a noticeable difference.

**Comment by RobertvanderHulst** [comment]
Chris, 20% is Ok, I think. I doubt that you will be dragging the window all the time. I checked with switching between a desktop with multiple screens and then a single screen and when I have moved the windows to a secondary screen then later on the single screen desktop the windows are nicely positioned on the monitor.

**Comment by cpyrgas** [comment]
Robert, yeah, that's what I meant, it's OK. I do not notice any slowdown even in my slow machine, so it should be fine.
