### ISSUE TITLE
OrdDescend( ,,true) and skip(1)

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#442]
There´s a problem when the sort direction is changed via OrdDescend ( , , TRUE ) to descending. The problem is only reproducable if no "DO..WHILE" loop is used ! 

- When you run the code unchanged the scope "G" is active and OrdKeycount() returns correctly 5. All seems to be fine if the content is listed inside a DO..WHILE loop. If you´re using skip(1)s only the key "o2" becomes visible and the hits are shown again and again ..
![wrap](https://user-images.githubusercontent.com/49241218/87218737-abc9ff80-c355-11ea-9ac9-d2707c2ec18b.gif)
. The attached gif (*) shows the DataBrowser behaviour if only skip(1)s are used. I set the scope to "G" and after a GoBottom() the key "Goethe" is selected. From this point on i continuously click on a Skip(1) button.    

- When you change the scope to "X", ordkeyCount() returns correctly 0, but the key "o2" is still shown.

(*) The gif was created by Screen2Gif - a cool tool ;-)

```
FUNCTION OrdDescTest2() AS VOID 
LOCAL cDBF, cPfad, cIndex   AS STRING 
LOCAL aFields, aValues AS ARRAY 
LOCAL i AS DWORD


	RddSetDefault ( "DBFCDX" )
   
   
    cPfad := "D:\test\" 
 
	cDBF := cPfad + "Foo"
	cIndex := cPfad + "Foox" 
	
	? FErase ( cIndex + IndexExt() )	

	//  ------------------
	    
	aFields := { { "LAST" , "C" , 20 , 0 } } 
	
	aValues := { "g6" , "o2", "g2" , "g1" , "g3" , "g5" , "A1" , "a2"  }	
	
	
	? DbCreate( cDBF , AFields)

	? DbUseArea( ,,cDBF)
	
	FOR i := 1 UPTO ALen ( aValues )
		
		DbAppend() 
		FieldPut ( 1 , aValues [ i ] )
		
	NEXT			

	? DbCreateOrder ( "ORDER1" , cIndex , "upper(LAST)" , { || Upper ( _Field->LAST) } )
	? DbSetOrder ( 1 ) 
	?	 
	
	// Set the scope to "G" or "X" 
	OrdScope(BOTTOMSCOPE, "G")   
	OrdScope(TOPSCOPE, "G")      

	// ------------

/*			
	DbGoTop() 
	? "Ascending" , "OrdKeyCount()" , OrdKeyCount() 
	?
	DO WHILE !Eof() 
		? "*Do while" , FieldGet ( 1 ) , Eof() 
		DbSkip ( 1 )
	ENDDO 	
	
    ?
   	DbGoTop()
   	FOR i := 1 UPTO 8 
		? "*" , FieldGet ( 1 ) , Eof()
		DbSkip ( 1 )
   	NEXT	
*/ 		
	// ----------------		
	OrdDescend ( , , TRUE )
	// ----------------		 		
	?
		
	DbGoTop() 
	? "Descending" , "OrdKeyCount()" , OrdKeyCount() 
    ?
	
	DO WHILE !Eof() 
		? "*Do while" , FieldGet ( 1 ) , Eof() 
		DbSkip ( 1 )
	ENDDO  	

	?	
	? "--- skip(1) only results ---"  
    ?
    FOR i := 1 UPTO 30
		? "*" , FieldGet ( 1 ) , Eof() 
		DbSkip ( 1 )
    NEXT
    ? "etc."	
		
	DbCloseArea() 
		
	RETURN		 

```

Karl-Heinz

**Comment by Karl1155** [comment]
Robert,

forgot to mention: When i continuously click on the skip(1) button this code is excecuted:

```
METHOD PshNext()

	SELF:server:Skip ( 1 )  
	
	IF SELF:Server:Eof 
		SELF:server:GoBottom()  		
	ENDIF 
```

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
See email from Karl Heinz on July 14, 2020
