### ISSUE TITLE
Tooltip Display Notes: Truncated Text

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#443]
If the hint text is longer than a certain length, then it is does not wrap words to the next line, but cut off.
See screenshot: 
![trunctext](https://user-images.githubusercontent.com/64518775/87637500-00e98500-c74b-11ea-875c-583e53b0ebd9.png)

**Comment by RobertvanderHulst** [comment]
When we target VS2017 and later then this is possible by putting the various elements of the prototype line in a ContainerElement with Wrapping style.
