### ISSUE TITLE
Tooltip Display Notes: Proposal for styling the Source Path

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#444]
The latest versions of XSharp (VS2019) display nicely and stylishly hints: Returns, Remarks and very useful information about SourcePath. Thanks to the developers! But the SourcePath is drawn on one line (at the end) with the method signature, which can make the resulting text rather long and confusing information.
![before](https://user-images.githubusercontent.com/64518775/87640690-c3d3c180-c74f-11ea-8a2c-0fb87dfd0665.png)

Please consider my proposal for a slight styling change. Perhaps you already have an even better solution that you have not yet added to the version.
![after](https://user-images.githubusercontent.com/64518775/87640890-0b5a4d80-c750-11ea-945f-bde3f89e6b16.png)

Best regards,
Leonid

**Comment by RobertvanderHulst** [comment]
Thanks for the suggestion. Implemented and will be included in the next build.
