### ISSUE TITLE
RC files do not open for editing (2.5b)

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#447]
As of 2.5b, VS2019 projects do not open resource files (RC extension) by double-clicking.
The error is displayed: 

> _There is no editor available for [path of file]. Make sure the application for the file type (.rc) is installed._

Now the file can be opened only using the "Open" context menu.
Tested on different computers and solutions.

**Comment by RobertvanderHulst** [comment]
We have never explicitly registered Rc files as "ours". Most likely you had c++ integration installed in vs before and they were taking care of this.

**Comment by leon-ts** [comment]
Robert,
I only installed XSharp 2.5b
At the same time, only double-clicking on the RC-file in the repository stopped working. Through the menu, the file opens without problems. Is there a chance that when integrating into VS you have some sort of double click handling and something has changed there? At first I thought that I had lost some settings. But on my other computer in another project the same thing started happening. There, too, XSharp was updated to version 2.5b.

**Comment by leon-ts** [comment]
For clarity, I will attach a screenshot:
![RCErr](https://user-images.githubusercontent.com/64518775/87683578-eb478000-c789-11ea-9fb1-f55f9c18c31e.png)

**Comment by RobertvanderHulst** [comment]
Leonid,
I will have to check. 
But that will have to wait a while. I am going on a holiday tomorrow.

Robert

**Comment by leon-ts** [comment]
Robert, ok.
Happy holidays!

Best regards,
Leonid

**Comment by RobertvanderHulst** [comment]
Fixed. Also added "view code" implementation for VO binary items, which will open the XML editor for the file.
