### ISSUE TITLE
ADSADT driver truncates field names to 10 chars

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#450]
See https://www.xsharp.info/forum/public-product/2050-ads-connect-60-and-rdd-s

When using ADT tables, advantage apparently allows field names to be longer than 10 characters long, but this is not supported in X#. I do not have ADS to test it here, but I attempted to fix this by changing the code of _checkFields() below in AdsRDD.prg and remove the adjustment of field names (see below) and the customer confirmed that this fixed the problem.

I did not commit my change, because that would make ALL ADS-related drivers would not truncate field names anymore and I think this is not correct? Is it only ADSADT that indeed supports field names longer than 10 chars? If so, the code should be changed to reflect this.

```
PROTECT OVERRIDE METHOD _checkFields(info AS RddFieldInfo) AS LOGIC
    // FieldName
    info:Name := info:Name:ToUpper():Trim()
//    IF info:Name:Length > 10  // commented this out
//        info:Name := info:Name:Substring(0,10)
//    ENDIF
    IF ! info:Validate()
        SELF:ADSERROR(ERDD.CREATE_FILE, XSharp.Gencode.EG_ARG )
    ENDIF
    RETURN TRUE
```

**Comment by wriedmann** [comment]
As per ADS documentation, the Advantage proprietary file format allows field names upto 128 characters. The same applies to the order name length: 128 characters of maximal length.

**Comment by cpyrgas** [comment]
Thanks for the info Wolfgang!
