### ISSUE TITLE
The transported VOGUI form does not match the original

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#451]
An annoying problem was suddenly discovered. The dialog forms transported from VO do not correspond to the original ones. The window size is correct, it matches the original, but the layout of the controls does not take into account the window Caption zone. Because of this, all controls are shifted higher than they should be. Resource files (.rc) immediately after converting from VO are correct. But as soon as I make changes to the new form (.xsfrm), for example, I just changed the text without moving the controls, then the newly created resource already corresponds to the initially incorrect description in the xsfrm file.

Original VO form:
![Original_VO_form](https://user-images.githubusercontent.com/64518775/88149294-8c11c180-cc08-11ea-8e91-34411deac56a.png)
Transported XSForm:
![Transported_XSharp_form](https://user-images.githubusercontent.com/64518775/88149327-9764ed00-cc08-11ea-8154-d9fad404be66.png)

The problem is very annoying due to the fact that I have already translated a lot of windows and code into XSharp from VO before I noticed the problem (in forms of windows without Caption this problem is not visible). Now, if I need to make changes to these windows, I need to be very careful and re-arrange the controls correctly. But there are still many conversions of window forms ahead. I really hope that the devteam will fix this problem.

An example of the original AEF and the resulting project in attachment.
[VOBasicDialogApplication.zip](https://github.com/X-Sharp/XSharpPublic/files/4958589/VOBasicDialogApplication.zip)
[WindowFormTransporterTest.zip](https://github.com/X-Sharp/XSharpPublic/files/4958590/WindowFormTransporterTest.zip)

**Comment by cpyrgas** [comment]
Hi Leonid,

I have also seen this problem in dialog windows, not sure what's causing it, but will try to fix it. But is it really this serious? At least here, the difference I see is very small, a quick resize of the window in the editor seems to take care of it...

**Comment by leon-ts** [comment]
Hi Chris,

My team has transported to XSharp and adapted about 15% of the VO code so far (just over three months of work). And it already contains 189 window forms (I counted the number of xsfrm files). And these are only projects of internal system libraries. Аbout the fact that syslibs have more functional parts than window forms. After the completion of the system libraries, we will start transporting the main applications, where there are a lot of window forms (roughly over a thousand in total). Thus, it is a huge amount of routine work. Although xPorter could do this automatically.

Best regards,
Leonid

**Comment by cpyrgas** [comment]
Leonid, do you mean you are seeing this problem in all windows? So far I have only seen it in some dialog windows.

**Comment by leon-ts** [comment]
Chris,

At the moment, I only see this problem with dialog windows that have a Caption. The system libraries that I am currently transporting are mostly only dialog windows. MDI forms are included in the main applications. But as I mentioned earlier, my team hasn't made it to apps yet. I don't know yet if there will be a problem with MDI. But if consider that the problem is observed with forms that have a Caption in the VOGUI form editor, then there should be no problem with MDI.

**Comment by cpyrgas** [comment]
Leonid, OK will look into it. I had tried to solve it also in the past with not much success, but your pointer about dialog captions makes sense, maybe I had overlooked that...Will try again.

**Comment by leon-ts** [comment]
Chris, thanks!

**Comment by cpyrgas** [comment]
Found the problem, after so many years I now realized that for dialog windows the WED in VO displays also the dialog caption in the visual designer itself (unless the dialog is set to no caption), which makes the actual space for controls smaller. One possible fix for that, is to automatically decrease the height of windows in the VS editor when generating teh resource, which will work for freshly ported dialogs, but will further decrease the size of dialogs that have already been edited... Will try to find a better solution.

**Comment by cpyrgas** [comment]
Fixed. The VOWED now checks when opening dialog windows if their height is much larger than the area actually occupied by controls, and in this case it automatically decreases it, This happens only in the first load/save cycle of the window, not in subsequent ones, to prevent modifying windows that are actually on purpose designed with a lot of empty space at the bottom.
