### ISSUE TITLE
The INTERNAL class modifier is not saved after editing the VOGUI form

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#458]
If the VOGUI window class has the INTERNAL modifier (set manually), then after editing the form in the window editor and saving the changes, the INTERNAL modifier is reset.

**Comment by cpyrgas** [comment]
Robert, I will need information from the project system, about which modifiers the window class has in the existing code. When I have this information, then it is easy to adjust the code generation accordingly

**Comment by RobertvanderHulst** [comment]
Chris,
Can't you read the modifiers from the source ?

**Comment by cpyrgas** [comment]
Oh, I still have access to that myself? Let me check...

**Comment by cpyrgas** [comment]
Fixed. Also PARTIAL and also PRIVATE and PROTECTED modifiers are maintained (for method/constructors)
