### ISSUE TITLE
Improvements request for VOGUI window editor

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#463]
Hi,

After converting the VO code to XSharp and then working with the already converted code, we (XSharp users) use the new advanced features of the XSharp language. One of these possibilities is the implementation of interfaces. But when you edit VO GUI windows through the form editor and then save them, the manually specified interfaces (IMPLEMENTS) are not saved. This problem is in the same category as I previously described for the INTERNAL modifier. Is it possible to implement in the VO GUI form editor the window property "Implements Interfaces" after the item "Inherit from Class"?

P.S. In the same way, you can add the "Access modifiers" item, where we can select the class access modifiers (INTERNAL etc). In this case, the whole setting will be uniform and understandable.

Best regards,
Leonid

**Comment by RobertvanderHulst** [comment]
See also ticket #440

**Comment by cpyrgas** [comment]
Fixed, now the editors retain also the IMPLEMENTS clause! Doing that through new visual properties is something I had also thought about, but it would require adjusting the cavowed.inf file and would only apply to the WED. Now this is automatically supported in all VO binary editor types.
