### ISSUE TITLE
Changing NAMESPACE in WinForms

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#464]
When creating a new form (WinForms), a NAMESPACE with the name specified in the project properties is automatically generated. If I open the PRG of the created form and change the name of the namespace, then the next time I open it in the form editor, make changes and save, the PRG file is emptied (corrupted).

**Comment by RobertvanderHulst** [comment]
Leonid,
Did you change the namespace in both the Form.prg and the Form.designer.prg ?
Can you upload an example ?

**Comment by leon-ts** [comment]
Robert,
I only make changes to Form.designer.prg
In the attachment is a short video of my actions.
[WinFormsRenamespacing.zip](https://github.com/X-Sharp/XSharpPublic/files/5055524/WinFormsRenamespacing.zip)

**Comment by RobertvanderHulst** [comment]
Leonid.
If you rename the namespace in the Form.prg then it works as expected.
But you are right, it would be nice if some kind of warning was produced.
Btw: if I do the same with C# then the namespace change in the designer file gets lost when saving, without warning.
We can also do that if you want.

**Comment by leon-ts** [comment]
Robert, you're right.

If I change the namespace in both Form.prg and Form.designer.prg, then everything is ok. I just did not take into account immediately after creating the window that it was necessary to make changes to two files. But in this case, you really need some kind of warning or behavior like in C #. Otherwise, you can easily lose your code.

I think C # behavior would be preferred. After all, we work in the NET ecosystem, where C # behavior can be used as a reference.

**Comment by RobertvanderHulst** [comment]
In the next build our "CodeDomParser" will ignore differences in the namespace of the Form.prg and Form.Designer.prg.
So if you change the namespace in the form.prg then the form will still load.
When you then later save changes in the designer then the namespace in the form.Designer.prg will be synchronized with the namespace of the form.prg, just like C# does.

**Comment by cpyrgas** [comment]
Confirmed fixed
