### ISSUE TITLE
Problems with macro substitution

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#470]
See following code, there's a compile time and a runtime error with macro substitution:

```
error XS0131: The left-hand side of an assignment must be a variable, property or indexer

System.Security.VerificationException
Operation could destabilize the runtime.

Callstack : 
Object XSharp.RuntimeCodeblock.EvalBlock(System.Object[] args)
XSharp._Codeblock.__Usual XSharp._Codeblock.Eval(XSharp.__Usual[] args)
Object XSharp.Codeblock.EvalBlock(System.Object[] args)
static __Usual XSharp.RT.Functions.Evaluate(System.String cString, System.Boolean lAllowSingleQuotes)
static __Usual XSharp.RT.Functions.Evaluate(System.String cString)
static System.Void fox.Exe.Functions.Start()


FUNCTION Start() AS VOID
LOCAL obj
obj = createobject("empty")
AddProperty(obj,"MyName","Loy")
? obj.MyName  // prints "Loy" - this works

LOCAL macrovar
macrovar = "obj.MyName"
? &macrovar // Unhandled Exception: System.Security.VerificationException: Operation could destabilize the runtime.
	
//This one works when you get the value of the property
LOCAL prop
prop = "MyName"
? obj.&prop // prints "Loy" - OK

//But, this one errors out when setting the value of the property
obj.&prop = "Jack" // error XS0131: The left-hand side of an assignment must be a variable, property or indexer\
? obj.&prop


```

**Comment by RobertvanderHulst** [comment]
Chris,
For this to work:
```
macrovar = "obj.MyName"
? &macrovar
```
you must set the /fox2 compiler options to make the local obj visible to the compiler.
But at this moment it does not work because the macro compiler does not recognize the "." character as send operator.
If you change it to 
```
macrovar = "obj:MyName"
? &macrovar

```
and enable /fox2 then this works.
I'll ask Nikos to change the macro compiler to recognize the "." as instance send operator as well.

**Comment by RobertvanderHulst** [comment]
The expression
`obj.&prop = "Jack"`
was already working with the `:= ` operator but not with the `=` operator.
Background:
The `=` operator is overloaded and can be both an assignment and a comparison.
There is special code that checks to see if a line of code starts with a binary expression and that changes the first `=` token into an assignment. This takes care of code that looks like `a=b=c` which will be translated to `a := b=c `.
This code was not working correctly for this kind of late bound member access
