### ISSUE TITLE
Slow looping through records

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#474]
The attached dbf contains 10 million records, with a single numeric field that has values 1...10 million. Try the code below with it, which does a simple iteration of all records and checking for a single value in the dbf (sort of simulating what locate does). 

The file is opened in exclusive mode and there's only a single iteration of the data, so there's no caching involved (except for that of the OS). In X#, this takes around 4-5 times longer than it does in VO.

```
FUNCTION Start() AS VOID
LOCAL cDbf AS STRING
LOCAL uTime AS USUAL
LOCAL u AS USUAL
cDbf := "C:\test\huge2.dbf"
DbUseArea(,,cDbf,,FALSE)
DbGoTop()
uTime := Time()
DO WHILE !Eof()
	u := FieldGet(1)
	IF u == 9000000 // 9 million
		EXIT
	END IF
	DbSkip()
ENDDO
? "Time elapsed:", ElapTime(uTime, Time())
DbCloseArea()

```

[HUGE2.zip](https://github.com/X-Sharp/XSharpPublic/files/5083968/HUGE2.zip)

**Comment by RobertvanderHulst** [comment]
The X# code has about the same speed as the Vulcan code.

**Comment by cpyrgas** [comment]
I know, I deliberately did not mention vulcan :)

It's just that the OP mentioned this big speed difference as a prohibiting reason for not moving to X# from VFP (which is even faster than VO I think). If it's simply just completely impossible to go somewhat closer to that speed, due to the managed nature of X#, I think we should then just accept and document this and explain to the users why that is.

**Comment by cpyrgas** [comment]
Also, using a single LOCATE to find the same record in VFP (again in exclusive mode, single iteration - so no caching) is also a lot faster than VO (like 4-5 times!). Maybe they are using low level OS tricks available only to MS, or they are using some other optimizations (caching is not relevant here though), but in any case this makes it more than 20 times faster than vulcan/X#. It's something that needs to be considered.

**Comment by RobertvanderHulst** [comment]
The new buffered filestream class improves this a lot. On my machine the VO code takes ~ 9 seconds, the new buffered filestream takes 16 seconds. Still slower than the VO code, but much faster.

**Comment by RobertvanderHulst** [comment]
With the current build in Release mode this test takes ~ 7 seconds in VO and ~10 seconds in X#. For now I would like to close this

**Comment by cpyrgas** [comment]
In my machine VO takes 6 seconds, while X# takes 15 seconds. Not too good, but not too bad, either, so I agree on closing it.

Btw, I did not expect it, but indeed Debug/Release makes an improtant speed difference, in (compiling the Runtime) Debug mode X# was taking 24 seconds. Robert, never thought about this before, but I guess in the X# installers you install the release binaries to the GAC?
