### ISSUE TITLE
Displaying language resources in the VOGUI form editor

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#477]
VO has a special way of writing the text of controls so that when the form is saved, they are converted to loading language resources.

For example, if in the Caption property (button) write:
`<'Close', IDM_CLOSE, GPLANG>`
then the prg file will contain
`LoadResString("Close", IDM_CLOSE, GPLANG)`

The VO form editor in XSharp also supports this.
But there is a difference in the display of such an expression in the form editor itself. The form editor in VO understands such an expression and shows on controls only the text from the expressions (see the screenshot of VisualObjects.png). And the XSharp form editor shows the expression as it is (see screenshot XSharp.png)

I would like the XSharp form editor to also be able to select text from a language expression when displaying controls.

Visual Objects:
![VisualObjects](https://user-images.githubusercontent.com/64518775/90650107-21be6200-e244-11ea-9e7c-30a05724a70b.png)
XSharp:
![XSharp](https://user-images.githubusercontent.com/64518775/90650110-2256f880-e244-11ea-8714-8f1f3bcfd583.png)

**Comment by cpyrgas** [comment]
Fixed! Please note that the problem only affected PushButton controls, other types of controls were already working as expected.
