### ISSUE TITLE
VS extension error callstack with WPF project

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#48]
Got the callstack below when trying to investigate a user report on WPF.
Error happened while I had opened the .xaml file in the editor. I am
including both the .xml file and the project.

System.ArgumentException: Absolute path expected.
Parameter name: path
at Roslyn.Utilities.CompilerPathUtilities.RequireAbsolutePath(String
path, String argumentName)
at Microsoft.CodeAnalysis.FileTextLoader..ctor(String path, Encoding
defaultEncoding)
at
Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DocumentProvider.StandardTextDocument..ctor(DocumentProvider
documentProvider, AbstractProject project, DocumentKey documentKey,
Func`2 getFolderNames, SourceCodeKind sourceCodeKind, IVsFileChangeEx
fileChangeService, ITextBuffer openTextBuffer, DocumentId id,
EventHandler updatedOnDiskHandler, EventHandler`1 openedHandler,
EventHandler`1 closingHandler)
at
Microsoft.VisualStudio.LanguageServices.Implementation.ProjectSystem.DocumentProvider.TryGetDocumentForFile(AbstractProject
hostProject, String filePath, SourceCodeKind sourceCodeKind, Func`2
canUseTextBuffer, Func`2 getFolderNames, EventHandler
updatedOnDiskHandler, EventHandler`1 openedHandler, EventHandler`1
closingHandler)
at
Microsoft.VisualStudio.LanguageServices.Xaml.XamlTextViewCreationListener.TryCreateXamlDocument(AbstractProject
project, String filePath, IVisualStudioHostDocument& vsDocument)
at
Microsoft.VisualStudio.LanguageServices.Xaml.XamlTextViewCreationListener.VsTextViewCreated(IVsTextView
vsTextView)
at
Microsoft.VisualStudio.Editor.Implementation.SimpleTextViewWindow.<>c__DisplayClass423_0.<SendVsTextViewCreated>b__0()
at
Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object
errorSource, Action call)
--- End of stack trace from previous location where exception was thrown ---
at
Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception
exceptionObject)
[WpfMapUserControl-1.zip](https://github.com/X-Sharp/XSharpPublic/files/3296943/WpfMapUserControl-1.zip)
[ActivityLog.zip](https://github.com/X-Sharp/XSharpPublic/files/3296944/ActivityLog.zip)

**Comment by RobertvanderHulst** [comment]
Cannot reproduce this. I also do not have the Microsoft.Maps.MapControl.WPF control library

**Comment by cpyrgas** [comment]
And it looks like MS completely killed it, what s surprise https://www.microsoft.com/download/en/details.aspx?displaylang=en&id=27165 so I can't test it again either. Let's just close this.
