### ISSUE TITLE
Compiler error without details

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#483]
Encountered another error in the compiler where it does not provide information about the cause and location of the error. The reason is again in overloads of entities (functions, methods).

The following code generates error
> MSB4181 The "Xsc" task returned false but did not log an error

```
FUNCTION Test(cErr OUT STRING) AS VOID
    cErr := NULL_STRING
    RETURN
	
FUNCTION Test() AS VOID
    Test(OUT NULL)
    RETURN
```

**Comment by RobertvanderHulst** [comment]
Leonid,
This seems to be a side effect of the /vo5 compiler option. If you declare the second function as 
`FUNCTION Test() AS VOID STRICT`
then the code compiles without problems.

Without this option the second method is silently compiled as 

`FUNCTION Test(xsArgs PARAMS USUAL[]) AS VOID `

And this seems to cause a problem later during compilation.

You can see the same problem if you disable /vo5 and declare the second function as 
`FUNCTION Test() AS VOID CLIPPER`

**Comment by RobertvanderHulst** [comment]
The error message that was supposed to be shown is
`error XS0663: 'R739.Exe.Functions' cannot define an overloaded method that differs only on parameter modifiers 'params' and 'out'`

**Comment by leon-ts** [comment]
Robert,

Yes, I agree that this is an ambiguity in the code. But due to the lack of a correct error message, it was difficult for me to figure out what was wrong. Please make the error message clearer, indicating the problematic method.

Best regards,
Leonid
