### ISSUE TITLE
Problem opening WPF windows in the designer, with the 2.5 public build

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#484]
From https://www.xsharp.info/forum/public-product/2132-public-2-5b

When trying to open a WPF window in either VS2017 or VS2019 with the Public 2.5 build, an error dialog is shown:

---------------------------
Microsoft Visual Studio
---------------------------
There is no editor available for 'C:\Users\cpc\source\repos\WpfApplication2\WpfApplication2\WPFWindow1.xaml'.

Make sure the application for the file type (.xaml) is installed.
---------------------------
OK   
---------------------------

By instead selecting "Open With" and then "XAML Designer", the window does open correctly.

**Comment by RobertvanderHulst** [comment]
Fixed
