### ISSUE TITLE
Macro compiler does not properly handle methods with REF or IN parameters

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#485]
Try the following code

```
FUNCTION TestByRef(s REF STRING) AS STRING
   RETURN s

FUNCTION Start as VOID
   LOCAL cMacro := "{|a| TestByRef(a) }"
   local cbMacro := &(cMacro)
   ? Eval(cbMacro, "123")
    RETURN
```

By the way adding REF or @ in front of the parameter is not recognized by the macro compiler.

I discovered this after adding support for IN parameters (REF READONLY parameters)  in the compiler and changing the parameter modifiers of some of the runtime functions.
I will have to wait with making these changes until the macro compiler is fixed.

**Comment by nvkokkalis** [comment]
REF params were supported only if the param type matched the argument (and considering that the macro compiler only really supports OBJECT params/locals, only REF OBJECT params were possible).

The fix allows a USUAL/OBJECT to be passed as REF argument by declaring a typed local, assigning the value to it and passing that instead. Not very nice but solves the problem.

Note 1: the fix still does not allow REF or @ in fron of the argument.

Note 2: any value assigned back  to the USUAL by the function called is discarded.

**Comment by RobertvanderHulst** [comment]
Nikos,
I know we have designed the Macro compiler with a dependency on XSharp.Core only so it was obvious that the types of the variables inside the compiler had to be objects. That was also the case for the Vulcan macro compiler.

However we have recently added a reference to XSharp.RT to allow nested codeblocks.
Would it be possible to make the internal type inside the macro compiler USUAL and to also add and implement a new ICodeBlock interface where the parameters are an array of usuals and the return value a usual. That would also make solving of #418 easier. If we do that we can also save a lot of conversions for parameters and return values. And we can still support the old interfaces with an extra method that converts from and to objects.

**Comment by nvkokkalis** [comment]
Yes Robert, it would be trivial to support USUAL parameters and return values as the macro compiler internally already supports it. In fact, I believe the only thing needed would be to modify the delegate prototype used to specialize the generic macro compiler, but let me check it.
