### ISSUE TITLE
VS2017 Rename file results in crash

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#49]
From Otto:

How to reproduce: The solution is under TFS source control. I added a XSharp MsUnit project directly from the solution explorer. I tryed to rename the standard prg. (Same issue occures when adding a new prg file and try to rename that from the solution treeview) This resulted in messages "The item -old filename- was not renamed in the source controld atabase because there is already an item with this name in the destination folder." This can be repeated. It even resulted in crashes of Visual Studio. At reopening the solution the project refered to the old file name. The new file was in the folder on disk. I finally edited the project on disk by hand to fix this.

**Comment by cpyrgas** [comment]
I don't have a source control system for VS, will let Otto maybe confirm this

**Comment by RobertvanderHulst** [comment]
> I don't have a source control system for VS, will let Otto maybe confirm this

I have thoroughly tested this. I am sure this is fixed. When Otto reports otherwise we will reopen this one or create a new ticket.
