### ISSUE TITLE
AddProperty() should cause compiler issue in this case...

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#492]
Here, it seems like this function call to AddProperty() function should cause a compiler error.

The first parameter should be an object reference, but I put a string, and it compiles fine, but causes a runtime error (as it should).

```
Function CreateEmptyObject()

	Var loData = Empty{}

	AddProperty("State", "Alabama")
	
	Return loData
	
End Function

```

The correct code should have been `AddProperty(loData, "State", "Alabama")` so what I put was wring, but shouldn't the compiler be able to see this and give an error?

**Comment by RobertvanderHulst** [comment]
Matt,
In FoxPro the AddProperty function is defined as:
`ADDPROPERTY(oObjectName, cPropertyName, [, eNewValue ])`

So the third parameter is optional.
At this moment we have implemented the function as:

`FUNCTION AddProperty (oObjectName AS OBJECT, cPropertyName AS STRING, eNewValue := NIL AS USUAL) AS LOGIC`

The problem with this is that in .Net *everything* is an object. So the string "State" is also an object.
I am not sure how to solve this.
We have considered to add 2 overloads for this function but that would not solve your problem:

`FUNCTION AddProperty (oObjectName AS OBJECT, cPropertyName AS STRING) AS LOGIC`
`FUNCTION AddProperty (oObjectName AS OBJECT, cPropertyName AS STRING, eNewValue AS USUAL) AS LOGIC`

Robert
