### ISSUE TITLE
Problem passing vars by reference when calling strongly typed methods late bound

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#494]
In the following code, there are no compiler errors, but the vars passed by reference do not get updated when returning to the caller code

```
FUNCTION Start() AS VOID
	LOCAL u AS USUAL
	u := TestClass{}

	LOCAL n AS INT
	n := 1
	u:TestInt(REF n)
	? n // 1, should be 123
	n := 1
	u:TestInt(@n)
	? n // 1, should be 123

	LOCAL l AS LOGIC
	l := FALSE
	u:TestLogic(REF l)
	? l // false
	l := FALSE
	u:TestLogic(@l)
	? l // false

	LOCAL c AS STRING
	c := ""
	u:TestString(REF c)
	? c // ""
	c := ""
	u:TestString(@c)
	? c // ""
RETURN

CLASS TestClass
	METHOD TestInt(n REF INT) AS VOID
	n := 123
	METHOD TestLogic(l REF LOGIC) AS VOID
	l := TRUE
	METHOD TestString(c REF STRING) AS VOID
	c := "changed"
	
END CLASS
```

**Comment by RobertvanderHulst** [comment]
Chris,
I can see that the code in the runtime that handles these late bound calls, converts the variables from the USUAL[] to OBJECT[]. This is done inside MatchParameters() in OOP.PRG.
But it does not recognize that the parameters are by reference and does not write the new values back to the USUAL[] array.

I'll try to adjust that.

**Comment by RobertvanderHulst** [comment]
Chris, I have fixed this code in the runtime. Can you add the tests to the runtime unit tests, since this was entirely a runtime issue.

**Comment by cpyrgas** [comment]
Robert, will do!
