### ISSUE TITLE
FileToStr

### ISSUE THREAD

**Issue by JohanNel** [X-Sharp/XSharpPublic#5]
Working with VFP a function that is used quite frequently is FileToStr.

This is implemented as MemoRead in X#.

Can the following be added to the RunTime functions?

FUNCTION FileToStr(cFileName AS STRING) AS STRING
RETURN MemoRead(cFileName)

**Comment by RobertvanderHulst** [comment]
I will add that asap.
Is there also a StrToFile() for the reverse operation ?
Robert

**Comment by mattslay** [comment]
Robert - you can find a complete list of all VFP functions here:
https://docs.microsoft.com/en-us/previous-versions/visualstudio/foxpro/f2x2b62b(v%3dvs.71)

In particular, the StrToFile function is well documented on that site at this url:

https://docs.microsoft.com/en-us/previous-versions/visualstudio/foxpro/ak1w859c%28v%3dvs.71%29

`STRTOFILE(cExpression, cFileName [, lAdditive | nFlag])`

**Comment by RobertvanderHulst** [comment]
I will add both functions to the FoxPro runtime. I will start with this runtime (as well as the dialect support in the compiler) after the next release.

**Comment by mattslay** [comment]
Robert, once you begin this VFP runtime, will I be able to pull your incremental commits to it from this public repo? Hoping I can test them locally, even before the future release(s) come out.

Once something is alive in this area of this public repo, I am hoping I could learn how to implement any missing functions, then I can fork the repo, add mode in my fork, then submit pull requests.  Isn't that how open-source is supposed to work?

**Comment by RobertvanderHulst** [comment]
Matt,
Yes you are right, that how it is supposed to work.
However so far we have only lurkers that download changes but no pull requests yet.

**Comment by JohanNel** [comment]
Hi Robert,
Browsing some articles on CodeMag, I came upon the "FileToStr" as was written by a VFP developer Markus Egger.  I know it don't have all the overlays but at least it gives an idea of the internals of VFP.
protected virtual void StrToFile(string sExpression,  string sFileName)
 {
 FileStream oFs = new FileStream(sFileName, FileMode.CreateNew,FileAccess.ReadWrite);
 StreamWriter oWriter = new StreamWriter(oFs);
 oWriter.Write(sExpression);
 oWriter.Flush();
 oWriter.Close();
 oFs.Close();
 }
 }

**Comment by mattslay** [comment]
Remember, pretty much *every* VFP function was already written for .Net years again, with exactly the same implementation that VFP uses. I think I've already shared that before...

Some people have already done all the work for us in C#. Find it here:

https://github.com/mattslay/Visual-FoxPro-Toolkit-for-.NET

**Comment by RobertvanderHulst** [comment]
We have adopted the code contributes by Antonio and Karl-Heinz.
