### ISSUE TITLE
 error XS0121: The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by FrankMaraite** [X-Sharp/XSharpPublic#503]
**Describe the bug**
Until the version 25b the following worked:
 CLASS SomeViewModel INHERIT GalaSoft.MvvmLight.ViewModelBase
..
	SELF:@@Set<STRING>( REF _LinksObenLeer, VALUE )

Now, 2.6.1.0 (Release), I get the error:

The call is ambiguous between the following methods or properties: 'GalaSoft.MvvmLight.ViewModelBase.Set<T>(ref T, T, logic, string)' and 'GalaSoft.MvvmLight.ObservableObject.Set<T>(ref T, T, string)'

From ILSpy:

GalaSoft.MvvmLight.ObservableObject
protected bool Set<T>(ref T field, T newValue, [CallerMemberName] string propertyName = null)

GalaSoft.MvvmLight.ViewModelBase.
protected bool Set<T>(ref T field, T newValue = default(T), bool broadcast = false, [CallerMemberName] string propertyName = null)

For me the signatures of these methods are different. No reason for an error.

**To Reproduce**
IF you have MvvmLight I could try an example.

**Expected behavior**
No error like the years before

**Desktop (please complete the following information):**
 - OS: Win10 prof. 64 bit
 - Browser FireFox 80.0.1
 - MvvmLight 5.0.5.2 from 25. Apr. 2015

**Comment by cpyrgas** [comment]
Hi Frank!
Well, the 2 signatures are different, but both are perfectly good choices for the specific call, why would the compiler choose one over the other? It's similar to this code, which gives the same compiler error (also with previous builds):

```

PROCEDURE Test(n REF INT, l AS LOGIC, s := "" AS STRING)
PROCEDURE Test(n REF INT, l := FALSE AS LOGIC, ll := TRUE AS LOGIC, s := "" AS STRING)

FUNCTION Start() AS VOID
LOCAL n AS INT
Test(REF n, FALSE)
```

Which is the "correct" overload to call? Which one would you choose manually and why?

**Comment by FrankMaraite** [comment]
Hi Chris!
Hm, intersting. It worked for years now. May be I gave not enough imormation. The class hierarchy is (from ILSpy):
public class ObservableObject : INotifyPropertyChanged{
protected bool Set<T>(ref T field, T newValue, [CallerMemberName] string propertyName = null)
{
	return Set(propertyName, ref field, newValue);
} }

public abstract class ViewModelBase : ObservableObject, ICleanup{
protected bool Set<T>(ref T field, T newValue = default(T), bool broadcast = false, [CallerMemberName] string propertyName = null)
{
	if (EqualityComparer<T>.Default.Equals(field, newValue))
	{
		return false;
	}
	T oldValue = field;
	field = newValue;
	RaisePropertyChanged(propertyName, oldValue, field, broadcast);
	return true;
} }

From this, it should call the latter one as it should in fact. It is the first, the compiler would find on its way to the base class. I don't know is there a 'official' rule for this. Or can we see this as an overload?

I know Nick Friend is using MvvmLight (I learned from him!). How does he use it? Nick?

We should ask the C# compiler too.

HTH
Frank

**Comment by cpyrgas** [comment]
Hi Frank! Oh Thanks, I had not realized the two methods are in different classes in the hierarchy. It still does not make sense to me choosing one over the other, but you are right this used to work like that before in previous builds, also c# does compile it without errors. So I guess this needs to be changed in X# back to how it was, at least for the Core dialect. New sample showing this:


```
// error XS0121: The call is ambiguous between the following methods or properties: 'Child.Test(ref int, int, logic, string)' and 'Parent.Test(ref int, int, string)'
// Previous builds than 2.6 compiled this without errors and called the "child" method.
// c# does the same thing (calls the child method)
PUBLIC CLASS Parent
METHOD Test(n REF INT, n2 AS INT, c := NULL AS STRING )AS VOID
? "Parent"
END CLASS

CLASS Child INHERIT Parent
METHOD Test(n REF INT, n2 := 0 AS INT, l := FALSE AS LOGIC, c := NULL AS STRING) AS VOID
? "Child"
END CLASS

FUNCTION Start() AS VOID
LOCAL n AS INT
LOCAL o AS Child
o := Child{}
o:Test(REF n,1)

```

**Comment by FrankMaraite** [comment]
Thanks al lot!

**Comment by RobertvanderHulst** [comment]
Chris,
Do you remember the test case where there were two overloads in a hierarchy, a parent with a date and a child with a datetime.
(test R732), https://github.com/X-Sharp/XSharpPublic/issues/181
You argued then that when calling with a date the method in the parent should be called, even when there was a method in the child that could be called because there is an implicit conversion from date to datetime.
Nikos applied that change, and I think this is a side effect of that change,

**Comment by cpyrgas** [comment]
Aarghhh, right! Yeah, I think the behavior of c# does not make sense and the current behavior of X# is the correct one (well, it makes more sense IMO). But OTOH, some standard .Net classes like the ones Frank pointed out are designed with this bizarre c# behavior in mind... Frank, can you easily use a workaround for this? I think it's probably better to leave it as it is for now, unless more people do report the same thing in the future..

**Comment by FrankMaraite** [comment]
Hi Chris,
after Robert's reply I thought about already. And yes, there might be a good solution for that. Will back to you soon.
Regards
Frank

**Comment by FrankMaraite** [comment]
Hi Chris,
here my solution:
```
USING GalaSoft.MvvmLight
USING System.Runtime.CompilerServices

BEGIN NAMESPACE ViewModels

PARTIAL ABSTRACT CLASS BaseViewModel INHERIT GalaSoft.MvvmLight.ViewModelBase

	CONSTRUCTOR()
		SUPER()
	RETURN

	PROTECTED METHOD SetX<T>( field_ REF T , newValue := Default(T) AS T , [CallerMemberName] propertyName := NULL AS STRING ) AS LOGIC

		RETURN SELF:SetX<T>( field_, newValue, FALSE, propertyName )

	PROTECTED METHOD SetX<T>(field_ REF T , newValue AS T , broadcast AS LOGIC , [CallerMemberName] propertyName := NULL AS STRING ) AS LOGIC

	 RETURN SUPER:@@Set<T>( field_, newValue, broadcast, propertyName )


END CLASS

END NAMESPACE
````

I put an extra class in the middle. Then I did two methods with different name than 'Set' This is to avoid '@@'.
I like this way to handle default: a set of different signatures and calling self:xxx with default value.

Finally replaced '@@SET' with 'SetX' at all occurences. The compiler shows me were. (Lean on the compiler. One advantage of strong typing.)
Had to add some additional references like System.Core and System.Linq.Expressions. The compiler tells were. No problem.

After an hour all's running fine.

As I understand right this was a side effect of using defaults in method declaration. I always preferred a set of overloads to do the same:

```
method test( a as string) as logic
   return self:test( a, "defB" )
method test( a as string, b as string, c as string) as logic
   return self:test( a, b, "defC" )
method test( a as string, b as string, c as string) as logic
...
```

instead of
```
method test( a as string, b := "defB" as string, c := "defC" as string) as logic
...
```

Robert, Chris: thanks

Frank

**Comment by cpyrgas** [comment]
Frank, yeah, the problem comes from the default parameters, which make both overloads good matches. Glad you have a solution, so I think we should just leave this as is for now.

**Comment by FrankMaraite** [comment]
Chris, of course. A good example why not to use defaults. After a few months of doing other things but programming an interesting investigation. It was worth the time. Learned a lot.
Greetings to the team
Frank
