### ISSUE TITLE
Problem opening form in the designer

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#505]
The attached solution has a X# and a c# WinForms app, each with a window with the same infragistics control in them (a ChartControl). In the c# version, there's a line generated in the code:

this.chartControl1.SeriesSerializable = new DevExpress.XtraCharts.Series[0];

in the X# version, the same line is generated as:

SELF:chartControl1:SeriesSerializable := DevExpress.XtraCharts.Series[0]

and this causes an error both when compiling: error XS0119: 'DevExpress.XtraCharts.Series' is a type, which is not valid in the given context

and also when trying to open the form again in the designer (form cannot be opened).

I have no idea what that above c# syntax means, but indeed the respective generated text in X# is not correct. Looking at the definition of the DevExpress.XtraCharts.Series class, I see this:

```
namespace DevExpress.XtraCharts
{
    //
    // Summary:
    //     Represents an individual series within a chart control.
    [DesignerSerializer("DevExpress.XtraCharts.Design.ChartItemSerializer,DevExpress.XtraCharts.v20.1.Extensions", "System.ComponentModel.Design.Serialization.CodeDomSerializer,System.Design")]
    [DXDisplayName(typeof(XtraChartsResFinder), "DevExpress.XtraCharts.Series")]
    [TypeConverter(typeof(SeriesTypeConverter))]
    public class Series : SeriesBase, IDisposable, ISupportInitialize, ICustomTypeDescriptor, ISeries, ISeriesBase, ISeriesPointFactory, IXtraSerializable, ISupportID, IDataSourceChangedEventHandlerProvider
    {
        // Summary:
        //     For internal use only. Initializes a new instance of the DevExpress.XtraCharts.Series
        //     class with the default settings.
        public Series();
        // Summary:
        //     Initializes a new instance of the DevExpress.XtraCharts.Series class with the
        //     specified series name and view type used to represent this series.
        public Series(string name, ViewType viewType);
...

```

[WindowsFormsApplication9.zip](https://github.com/X-Sharp/XSharpPublic/files/5401680/WindowsFormsApplication9.zip)

**Comment by RobertvanderHulst** [comment]
The right syntax would have been:
`SELF:chartControl1:SeriesSerializable := <DevExpress.XtraCharts.Series>{}`
I'll change the codegenerator to take care of this.

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
Robert, nice! Oh it's the array instantiation, it did not even cross my mind!!

**Comment by cpyrgas** [comment]
> 
> 
> The right syntax would have been:
> `SELF:chartControl1:SeriesSerializable := <DevExpress.XtraCharts.Series>{}`
> I'll change the codegenerator to take care of this.

Robert, on second thought, shouldn't that be generated as

DevExpress.XtraCharts.Series[]{0}

instead? Because it is possible that some other control generates an array with more than zero elements..

**Comment by RobertvanderHulst** [comment]
Chris,
The code generator looks at the arguments.
I have seen another example where it generates
`<Type>{element1, element2}`
which is correct too.
