### ISSUE TITLE
Problem with macro on left side of equation with the single "=" operator (VFP)

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#510]
https://www.xsharp.info/forum/public-vfp/2223-macro-on-left-side-of-equation

 I get a compile error if I use a macro on the left side of an equation, like this:

```
local variable1, macrostring as string
variable1="This is a string"
macrostring="variable1"
&macrostring="This is a new string" // error
&macrostring :="This is a new string" // this works
```

That is valid in Foxpro and assigns "This is a new string" to variable1. In X# I get the error "The left-hand side of an assignment must be a variable, property or indexer"

**Comment by RobertvanderHulst** [comment]
Fixed
