### ISSUE TITLE
Runtime error with nullable values and /vo11+

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#511]
Following code compiles with no errors, but crashes with an ExecutionEngineException. It only happens when /vo11+ is enabled and only when the target is set to x86 (not in AnyCPU). The generated IL lookslike
 
IL_0026: ldloc.0
IL_0027: call int32 [mscorlib]System.Convert::ToInt32(float64)
IL_002c: stloc.1
IL_002d: ldloc.1
IL_002e: call valuetype [XSharp.RT]XSharp.__Usual [XSharp.RT]XSharp.__Usual::op_Implicit(valuetype [mscorlib]System.Decimal)

which does not seem to make sense to let USUALs or System.Convert() have an involvement in this code

```
// Problem happens only with /vo11+ enabled
FUNCTION Start( ) AS VOID
	LOCAL dNullable AS Nullable<Decimal>
	LOCAL dValue AS Decimal

	dNullable := 1m

	dValue := dNullable:Value // ok
	? dValue
	dValue := (Decimal)dNullable // ok
	? dValue

	// Note that c# does not allow this syntax at all, requires a cast or using :Value
	dValue := dNullable // System.ExecutionEngineException
	? dValue
RETURN
```

**Comment by RobertvanderHulst** [comment]
I think it is best when we choose the C# behavior. There is no risk of being incompatible with VO, since nullable types do not exist in VO.

**Comment by cpyrgas** [comment]
Agreed!
