### ISSUE TITLE
Add FoxPro compatible array support to the compiler and runtime

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#523]
- Dimension and Declare statement should define FoxArray
- AS ARRAY declares a "normal" array
- Dimension for an existing array should change the rows/columns without clearing the array 
- FoxArray inherits from normal array
- Is implemented as a single dimensional array. Has rows/colums property to store the dims with which it was declared
- Allow single and double indexes to access elements. Translate row/column to single dimension
- Do not allow array values as elements to prevent nesting.
- Implement Foxarray compatible functions, such as ALen(), ASubscript() etc.

**Comment by RobertvanderHulst** [comment]
See also #170

**Comment by cpyrgas** [comment]
Looks good to me.
