### ISSUE TITLE
SetSelectiveRelation() child never moving out of EoF after entering it once

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#526]
In the following code, 2 servers are used with SetSelectiveRelation(). Once the parent moves to EoF, then the child goes to Eof as expected. But even when the parent moves out of EoF, child gets always stuck still at EoF.

```
FUNCTION Start() AS VOID
LOCAL parent , child AS dbserver
LOCAL cParent,cChild AS STRING
LOCAL cPath AS STRING

cPath := "c:\test\"
RddSetDefault("DBFCDX")

cParent := cPath + "parent"
cChild := cPath + "child"

DbCreate(cParent , {{"FLD","C",5,0}})
DbUseArea(TRUE,,cParent)
DbAppend()
FieldPut(1,"ABC")
DbAppend()
FieldPut(1,"DEF")
DbCloseArea()

DbCreate(cChild , {{"FLD","C",5,0}})
DbUseArea(TRUE,,cChild)
DbCreateIndex(cChild , "FLD")
DbAppend()
FieldPut(1,"ABC")
DbAppend()
FieldPut(1,"DEF")
DbCloseArea()

parent := DbServer{cParent,TRUE,,"DBFCDX"}
child := DbServer{cChild,TRUE,,"DBFCDX"}
child:SetOrder( 1 )
parent:SetSelectiveRelation(child, #FLD )


// those results are correct:
parent:GoTop()
? "Child EOF after parent GoBottom():", child:EOF, child:RECNO // FALSE, 1 (OK)
parent:GoBottom()
? "Child EOF after parent GoBottom():", child:EOF, child:RECNO // FALSE, 2 (OK)
parent:Skip(+1)

// Skip() past eof causes child to go to eof as well, correct:
? "Child EOF after parent Skip(+1):", child:EOF, child:RECNO // TRUE, 3 (OK)

// After moving parent back to real records, child always still remains at eof:
parent:Skip(-1)
? "Child EOF after parent Skip(-1):", child:EOF, child:RECNO // TRUE, 3 (WRONG)
parent:gotop()
? "Child EOF after parent GoTop():", child:EOF, child:RECNO // TRUE, 3 (WRONG)
parent:gobottom()
? "Child EOF after parent GoBottom():", child:EOF, child:RECNO // TRUE, 3 (WRONG)

parent:Close()
child:Close()

```

**Comment by cpyrgas** [comment]
I have not managed to reproduce this in code using plain DB commends yet, so I am suspecting the problem could actually be in the SDK DBServer class. I checked older X# builds, this problem started happening after the 2.4a and before the 2.5 release, so the culprit is in a commit between May 10th and July 1st of 2020

**Comment by RobertvanderHulst** [comment]
Most of the changes in between these versions were:
- SELF:__OptimisticFlush() was sometimes in the wrong location (before the workarea was selected with VODbSelect()). Wolfgang detected this in VO and I changed it in X# too.
- I also changed an ASend() in __NotifyBufferFlush() to a FOREACH loop

**Comment by cpyrgas** [comment]
Yeah, I saw them as well, reverted those changes just in case, but the problem remains. Also almost all of those changes are (slightly) outside the time window when the problem started happening. So I guess the problem is actually in the RDD code after all, I just have not managed yet to reproduce it without using the DBServers.

**Comment by cpyrgas** [comment]
Btw, I reviewed some a bit older changes, did not see something affecting this problem, but I noticed this: In DBServer3.prg, lines 999 and 1008, the previous code was:

999: IF ! ( uRetValue := Send(aClients[w],#Notify, kNotification ) 
1008: IF ! ( uRetValue := Send(aRelationChildren[nChild],#Notify, kNotification ) )

and now it has been changed to

999: uRetValue := Send(oClient,#Notify, kNotification, uDescription )
1008: uRetValue := Send(oChild, #Notify, kNotification , uDescription)

so in those two cases, the "uDescription" param was not being passed to Send() before, but now it does. Not sure which one is the intended/correct way though.

**Comment by RobertvanderHulst** [comment]
That is probably the reason:
In DbServer3 line 1048 the code checks for uDescription == NIL .OR. uDescription == DBSELECTIONNULL
https://github.com/X-Sharp/XSharpPublic/blob/master/Runtime/VOSDK/Source/VOSDK/RDD_Classes_SDK/DBServer3.prg#L1048

I think we may be giving a different value for uDescription when a Skip() occurs:

`SELF:Notify( NOTIFYRECORDCHANGE, iRecords )`

Also NOTIFYFIELDCHANGE and NOTIFYCOMPLETION will get a asymbol for uDescription, but I do not think these trigger a relation change.

And also the check for `uDescription == DBSELECTIONNULL` is BS.

uDescription is either NIL or a symbol. For a Symbol this will cause an error since DBSELECTIONNULL is numeric.

This code fragment should probably be `siSelectionStatus == DBSELECTIONNULL`
And this has been in the code since VO 2.5 !

**Comment by cpyrgas** [comment]
This is what I thought as well at first, but I had changed that code to what it was before and the problem (of this report) still remained. Also this change in the code was done much earlier (late 2019) than when the problem started happening in X# (summer 2020). So it must be something else, I now think most likely it's something in the RDD/runtime functions. Will try again tomorrow to pinpoint it.

**Comment by cpyrgas** [comment]
OK, I managed to reproduce it, it is indeed a problem in the RDD, not in the SDK. The critical part in order to reproduce the problem was to issue a GoTop() to the child workarea, after setting the scope (the DBServer class does this):


```
#define DBOI_SCOPETOP 39
#define DBOI_SCOPEBOTTOM 40
FUNCTION Start() AS VOID
LOCAL cPath AS STRING
cPath := "C:\test\"

RddSetDefault("DBFCDX")

DbCreate(cPath + "parent" , {{"FLD" , "N" , 3 , 0}})
DbCreate(cPath + "child" , {{"FLD" , "N" , 3 , 0}})


DbUseArea(TRUE,"DBFCDX", cPath + "parent", "parent" , TRUE)
parent->DbAppend()
parent->FieldPut(1,1)
parent->DbAppend()
parent->FieldPut(1,2)

DbUseArea(TRUE,"DBFCDX", cPath + "child", "child" , TRUE)
child->DbCreateIndex(cPath + "child","FLD")
child->DbAppend()
child->FieldPut(1,1)
child->DbAppend()
child->FieldPut(1,2)

DbCloseAll()

DbUseArea(TRUE,"DBFCDX", cPath + "child", "child" , TRUE)
DbUseArea(TRUE,"DBFCDX", cPath + "parent", "parent" , TRUE)
parent->VoDbSetRelation("child" , &( "{ ||FLD}") ,"FLD")

// In the next two, child EoF() is false as expected
? "move parent to first record"
parent->DbGoTop()
DoRelation()

? "move parent to second record"
parent->DbSkip(+1)
DoRelation()

// Here, child EoF() becomes true, correct
? "move parent to EoF"
parent->DbSkip(+1)
DoRelation()

// In all the below, child EoF() remains TRUE, should had turned to false. Also ReCno remains at 3 (above the last rec)
? "move parent back to last record"
parent->DbSkip(-1)
DoRelation()

? "move parent to top"
parent->DbGoTop()
DoRelation()

? "move parent to bottom"
parent->DbGoBottom()
DoRelation()

DbCloseAll()
RETURN

PROCEDURE DoRelation()
LOCAL u1,u2 AS USUAL
? "Parent value:", u1 := u2 := parent->FieldGet(1)
child->VoDbOrderInfo( DBOI_SCOPETOP	 , "", NIL, REF u1 )
child->VoDbOrderInfo( DBOI_SCOPEBOTTOM, "", NIL, REF u2 )
child->DbGoTop() // <---------- this is what makes the problem manifest itself
//child->DbGoBottom() // no problem with this instead
? "Child Eof, RecNo:", child->Eof(), child->RecNo()
?

```

**Comment by RobertvanderHulst** [comment]
Chris I have checked in a fix. Can you check it too ?

**Comment by cpyrgas** [comment]
Robert, that's excellent! All related tests pass now and the original problem in Karl's app is fixed now, too!
