### ISSUE TITLE
VS intellisense issues for  xbase++ dialect

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#53]
Raffaele,

You are right. Some XPP class elements, such as the Inline method are not properly supported for intellisense inside VS. We will try to add that for the next build.

[TestXpp.zip](https://github.com/X-Sharp/XSharpPublic/files/3297067/TestXpp.zip)

**Comment by RobertvanderHulst** [comment]
Fixed in one of the last builds.
