### ISSUE TITLE
AsHexString function does not process PTR values

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#539]
In VO, the following expression is executed without problems:
```
LOCAL p AS PTR
LOCAL c AS STRING
p := 0x01020304
c := AsHexString(p)
```
**Returns:** c = "01020304"

In XSharp, the above expression returns an empty string.

**Comment by cpyrgas** [comment]
Fixed. Also adjusted AsString() to return result in hex format for PTR values.
