### ISSUE TITLE
No member completion with Project References

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#540]
The attached solution contains a console app and two references, one is added as a Project Reference and another as a direct reference (via browse). For the project reference, the editor shows no member completion:

FUNCTION Start() AS VOID STRICT

VAR oVar := ClassLibrary1.Class1{}
LOCAL oLocal AS ClassLibrary1.Class1
	
oLocal: // no list
oVar:   // no list

[CheckIntellisense.zip](https://github.com/X-Sharp/XSharpPublic/files/5687481/CheckIntellisense.zip)

**Comment by RobertvanderHulst** [comment]
Fixed in next build
