### ISSUE TITLE
Cannot use index file at all, when there's a problem in one of its orders

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#542]
The attached dbf/cdx has an index file with two orders. Order 1 is defined correctly, but order 2 (created in VO, maybe with some tool) has a syntax error in the condition expression.

In VO, using (the valid) order 1 works without any issues. Trying to set the order to the problematic 2, DBSetOrder() actually still returns TRUE, but the record pointer is moved at EoF and no records are visible.

In X#, trying to set the active order to either 1 or 2 has the same result, DBSetOrder() returns false and the control order remains the natural one.

Not sure if the Vo behavior regarding using order 2 must be replicated, but at least order 1 should be still usable without issues, like in VO.

[Test.zip](https://github.com/X-Sharp/XSharpPublic/files/5708897/Test.zip)

```
FUNCTION Start() AS VOID

? DbUseArea(TRUE,"DBFCDX","c:\test\test",,FALSE)

? "using order 1"
? DbSetOrder(1) // FALSE
DbGoTop()
? Eof()
? RecNo() // 1, OK
DbGoBottom()
? RecNo() // 3, wrong, should be 2

?

? "using order 2"
? DbSetOrder(2) // FALSE, VO returns TRUE!!!
DbGoTop()
? Eof() // FALSE, VO returns TRUE
DbGoTop()
? RecNo() // 1, VO returns 4
DbGoBottom()
? RecNo() // 3, VO returns 4

DbCloseArea()

```

**Comment by RobertvanderHulst** [comment]
When the RDD detects an error in the expression then the Tag is now opened with an "invalid" state and all operations (go top, skip, gobottom, seek) result in the record pointer being moved to EOF. The keycount = 0.
