### ISSUE TITLE
VODate CompareTo in reverse?

### ISSUE THREAD

**Issue by ochristiaanse** [X-Sharp/XSharpPublic#543]
**Describe the bug**
It seems that VODate CompareTo returns the wrong value if I compare it to DateTime.
If I make a List<__Date> and ask for the maximum value, I get the minimum.

**To Reproduce**
I added a simple solution demonstrating the problem.

**Expected behavior**
I would expect the same return value for the VODate CompareTo as for the DateTime CompareTo.

**Screenshots**

**Desktop (please complete the following information):**
Windows 10, Windows 7
XSharp 2.1 and 2.7
[Tests.zip](https://github.com/X-Sharp/XSharpPublic/files/5710718/Tests.zip)

**Comment by cpyrgas** [comment]
Robert, problem is that the offsets in the fields of the DATE type are in the opposite order:

[FieldOffset(00)] PRIVATE _ymd   AS System.Int32

[FieldOffset(00)] PRIVATE _year  AS System.UInt16
[FieldOffset(02)] PRIVATE _month AS System.Byte
[FieldOffset(03)] PRIVATE _day   AS System.Byte

this should be instead

[FieldOffset(02)] PRIVATE _year  AS System.UInt16
[FieldOffset(01)] PRIVATE _month AS System.Byte
[FieldOffset(00)] PRIVATE _day   AS System.Byte

I will change this, unless you'd like ot have a look yourself.

**Comment by RobertvanderHulst** [comment]
Chris,
Well, that depends on the platform where the code runs: little endian versus big endian. I don't think we should make assumptions about this. On Intel you are right but on other platforms this code may be right.
So the best solution would be:
Either compare the 3 elements separately
IF _year > rhs:_year
  ..
ELSEIF _year < rhs:_year
.. 
ELSEIF  _month > rhs:_month
..
ELSEIF  _month < rhs:_month

etc
or 

Compare _year * 10000+_month*100+_day 

or (the least code): convert LHS and RHS to DateTime (with the Value property) and compare these.

Which one do you think is best ?

**Comment by RobertvanderHulst** [comment]
I have created a property for this:
```
INTERNAL PROPERTY YMD AS DWORD GET ;
                (SELF:DYear * 0xFFFF)  + (SELF:DMonth *0xFF) + _day
```
And the CompareTo now looks like this:

```
METHOD CompareTo(o AS OBJECT) AS LONG
	VAR rhs := (DATE)o
        RETURN SELF:YMD:CompareTo(rhs:YMD)
```

**Comment by cpyrgas** [comment]
Robert, I agree, this is the best solution.

**Comment by ochristiaanse** [comment]
Nice that you fixed it already!
Is it possible to get this RT fix out on the field early?
Or are there plans for a new XSharp build?

**Comment by RobertvanderHulst** [comment]
I will mail you the new DLLs later today.
Btw: your subscriptions needs renewal end of this month!
Maybe Visma wants to consider to become corporate sponsor? 
I know that we are not as "sexy" as an Ice scating team or a Cycling team but we could really use the support and we are happy with a fraction of what these teams get ;).

**Comment by ochristiaanse** [comment]
I notified my superiors about the subscriptions. I hadn't looked at the corporate sponsorship program before, but I'll notify them about this possibility.

**Comment by RobertvanderHulst** [comment]
Otto,
https://1drv.ms/u/s!An3aSY_HolAD4QSpxYqys_GeHIu3?e=YjH6gI
Copy the DLL files to the "c:\Program Files (x86)\XSharp\Assemblies"  folder
Copy the DLL and PDB files to the "c:\Program Files (x86)\XSharp\Redist" 
Open a VS command prompt in Administrator mode and execute the following command in the "c:\Program Files (x86)\XSharp\Redist"  folder to register the new files in the GAC
for %i in (XSharp*.dll) do gacutil /nologo /i %i
