### ISSUE TITLE
Compiler doesn't recognize _SIZEOF(SomeVOStruct) as a constant value

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#545]
Compiler doesn't recognize _SIZEOF(SomeVOStruct) as a constant value.
For example, such a definition:
`DEFINE REGION_BUF_SIZE := _SIZEOF(_winRECT) * 16`
leads to XS0133 The expression being assigned to '...REGION_BUF_SIZE' must be constant

PS. That happens only if _SIZEOF() is part of an expression, i.g. being multiplied. Though one may hope for a possible workaround, but it doesn't compile either:
```
DEFINE REGION_BUF_SIZE1 := _SIZEOF(_winRECT)
DEFINE REGION_BUF_SIZE16 := REGION_BUF_SIZE1 * 16
```
Same XS0133 error on REGION_BUF_SIZE16.

**Comment by RobertvanderHulst** [comment]
Serggio,
The problem with _SizeOf() is that some types, such as PTR types, do not have a fixed size. In x86 mode these types have a size of 4 bytes and in x64 mode they have a size of 8 bytes.
However the _WINRECT structure consists of 4 32 bit integers, so its size does not depend on the processor mode.
I'll see what we can do. Maybe we can detect at compile time if a structure has a fixed size (like _winRECT) and then allow _SIZEOF() for these types.

**Comment by RobertvanderHulst** [comment]
Serggio,
I checked and I found that I can change the code that handles _SizeOf(), so that for VOSTRUCT and UNION it will return the size that like VO does. 
This will be included in the next build.
