### ISSUE TITLE
Syntax highlighting error

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#556]
The syntax highlighting for comments after semicolons is not correct. The comments should be coloured green instead of white.

Screenshot that shows the problem:
![image](https://user-images.githubusercontent.com/9860916/104853125-19f01000-58ff-11eb-95e6-96f613ad0d94.png)

**Comment by RobertvanderHulst** [comment]
Volkmar,
Confirmed.
The Lexer translates the semi colon followed by comments or whitespace until the end of line into one "line continuation" token.
And the syntax highlighter therefore does not recognize this as comment. I'll see if I can change that.

Robert
