### ISSUE TITLE
ARRAY OF STRING

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#559]
Those typed arrays are nice and convenient, but there is a problem declaring an **ARRAY OF STRING**.
It leads to:
```
Error XS0310	'string' must be a non-abstract type with a public parameterless constructor
in order to use it as parameter 'T' in the generic type or method 'XSharp.__ArrayBase<T>'
```

It would be very nice if there was a way around this problem to be able to declare arrays of strings.

**Comment by RobertvanderHulst** [comment]
Serggio,
The recommended way to do this in .Net is with the Generic List class:
List<String>
The ARRAY OF follows the same syntax that our "normal" dynamic array does, and supports an AAdd()  operation which adds an empty object of the right type to the end of the list. 
Therefore we told it that the elements in the array must support a constructor with parameters.
The .Net string class does not have this (https://docs.microsoft.com/en-us/dotnet/api/system.string.-ctor?view=netframework-4.6)
We could change ARRAY OF to not require this and add a DEFAULT<T> to the array.
Actually that is not a bad idea at all.

**Comment by Serggio** [comment]
> The recommended way to do this in .Net is with the Generic List class

I do understand that, but it may somehow mix indexation: arrays are usually 1-based while IList and other .net generics are zero-based, so it may lead to confusions. Sure, that is the way it will be done if no solution of ARRAY OF STRING will be found.
The idea to use default(T) to fill new elements of array after ArrayCreate or ASize is quite fine!

**Comment by Serggio** [comment]
Maybe if there is /vo2 (Initialize strings) option switched on then you may recognize when T is STRING and use String.Empty to initialize new items of ARRAY OF STRING and not Default(T) which is null.

**Comment by RobertvanderHulst** [comment]
Serggio, 
I will see what I can do.

**Comment by RobertvanderHulst** [comment]
Serggio,
I checked if this was possible, and unfortunately I see no way to implement this without breaking other things...
