### ISSUE TITLE
X# extension 2.7.0.0 slows the Visual Studio 2019 Code Editor

### ISSUE THREAD

**Issue by pemo11** [X-Sharp/XSharpPublic#560]
I am not sure if this behavior qualifies as a bug but its definitely something that has to be adressed for the next release.

On many occasions the X# extension slows the Visual Studio 2019 Code Editor to the extend that code editing is not possible anymore.

The "freezing time" is sometimes up to 30 seconds or even longer.

But this bevahior is not consistent. On other days everything works fine without any delay or freezing. But its always the same (huge) project I am working on.

Restarting Visual Studio might help sometimes.

X# Version 2.7.0.0

Visual Studio Version Version 16.8.3 Community Edition

I have deactivated most of the other extensions, especially Live Share.

The option **Show completion list after a character is typed is deactivated**.

Kind regards,
Peter

**Comment by Serggio** [comment]
> The "freezing time" is sometimes up to 30 seconds or even longer.

Not an authoritative answer, but nonetheless: switch off option "Shared compiler" on the "Projects settings/Build" tab page, and restart Studio.

**Comment by RobertvanderHulst** [comment]
Serrgio,
We are reviewing the issue. The problem does NOT seem to be the shared compiler.

**Comment by RobertvanderHulst** [comment]
This is fixed in the upcoming (2.8) release
