### ISSUE TITLE
Cannot re-open a test project of type "Class Library with Ms Test Support project"

### ISSUE THREAD

**Issue by pemo11** [X-Sharp/XSharpPublic#563]
Its not possible to reopen a Class Library with Ms Test Support project. The project is automatically unloaded in the solution explorer.

To Reproduce

Create a Class Library with Ms Test Support project for X#
Close the project
Re-open it
It cannot be loaded and used anymore
This happens only with this project type.

All the other project types are ok.

This happens with Visual Studio 2017 Community Edition and Visual Studio 2019 Community Edition.

Tested on two different computers with Windows 10.

![XSharpMstestProjectProblem_1002](https://user-images.githubusercontent.com/1217960/107539649-76281600-6bc5-11eb-947e-d9d2af6252d3.png)

**Comment by RobertvanderHulst** [comment]
Fixed in next build.
