### ISSUE TITLE
Unexprected result when collapsing last method in class 

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#564]
**Describe the bug**
When collapsing the last method in class, then the _end class_ gets collapsed to.

**Screenshots**

Not collapsed:
![image](https://user-images.githubusercontent.com/9860916/107659626-9d471c00-6c87-11eb-9896-de78b22b2596.png)

Collapsed - end class and comment are collapsed as part of the method
![image](https://user-images.githubusercontent.com/9860916/107659792-d54e5f00-6c87-11eb-864d-feed0bdaec86.png)

**To Reproduce**
1: Collapse the last method in a class

**Expected behavior**
_End class_ should not be collapsed with the method

**Comment by RobertvanderHulst** [comment]
Fixed in next build
