### ISSUE TITLE
Go to definition (F12) from the Object Browser window doesn't work

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#565]
After making a search for a class/method/function in object browser I expect to be able to go to its definition. It doesn't work, just nothing happens. VS 2019.

**Comment by RobertvanderHulst** [comment]
Serrgio,
I cannot confirm this issue. I tried this in VS 2019 and it works. 
Can you produce an example ?

**Comment by Serggio** [comment]
Here is the smallest project to reproduce the problem:
[TestObjectBrowser.zip](https://github.com/X-Sharp/XSharpPublic/files/5998117/TestObjectBrowser.zip)

Press Ctrl+Alt+J to open the Object Browser and then type _test_. As there are two functions in the project (named _test1_ and _test2_) the Object Browser will show something like this:
![image](https://user-images.githubusercontent.com/9467830/108257472-e0196000-716f-11eb-822a-181d563009d3.png)

And there is no way to go to definition of any of these function from here.

**Comment by RobertvanderHulst** [comment]
Serrgio,
Thanks. This indeed confirms the problem. On a "normal" window (without the seek) it works:
![image](https://user-images.githubusercontent.com/14240939/108274444-35a43b80-7175-11eb-8a76-0fd50ee800e4.png)
If you select test1() in the window on the right hand side and press F12 then it goes to the source.
I'll see what VS does different from the search window

**Comment by RobertvanderHulst** [comment]
Fixed
