### ISSUE TITLE
WinFroms designer problem with control named after keyword

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#566]
Attached WinForm has a control named "Currency". When opening the prg file in the code editor, it changes the line

PRIVATE Currency AS System.Windows.Forms.Label

to

PRIVATE CURRENCY AS System.Windows.Forms.Label

so next time it is not possible to open the form in the designer. Prefixing the name with @@ as in

PRIVATE @@Currency AS System.Windows.Forms.Label

did not make the trick, either

[WindowsFormsApplication17.zip](https://github.com/X-Sharp/XSharpPublic/files/5976243/WindowsFormsApplication17.zip)

**Comment by RobertvanderHulst** [comment]
The form editor no longer allows to name a control after a Keyword.
