### ISSUE TITLE
ADS Function parameters not set as IN/OUT 

### ISSUE THREAD

**Issue by IanB-Ulysses** [X-Sharp/XSharpPublic#568]
**Describe the bug**

Parameters set for AS CHAR[] in ADS Function definitions should have InAttribute] [OutAttribute]  added.

e.g.

```
	[DllImport("ace32.dll", CharSet := CharSet.Ansi)];
        PUBLIC STATIC EXTERN METHOD AdsGetServerName(hConnect AS IntPtr, pucName AS CHAR[] , pusLen REF WORD ) AS DWORD 
```

Should be [InAttribute] [OutAttribute] pucName AS CHAR[]

```
	[DllImport("ace32.dll", CharSet := CharSet.Ansi)];
        PUBLIC STATIC EXTERN METHOD AdsGetServerName(hConnect AS IntPtr, [InAttribute] [OutAttribute] pucName AS CHAR[] , pusLen REF WORD ) AS DWORD 
```

Another example is 

```
 [DllImport("ace32.dll", CharSet := CharSet.Ansi)];
        PUBLIC STATIC EXTERN METHOD AdsGetServerTime(hConnect AS IntPtr,  pucDateBuf AS CHAR[], pusDateBufLen REF WORD , plTime OUT INT , [InAttribute] [OutAttribute] pucTimeBuf AS CHAR[] , pusTimeBufLen REF WORD ) AS DWORD 
```
	
Should be [InAttribute] [OutAttribute] pucDateBuf AS CHAR[]   (pucTimeBuf  is ok !)
	
```
    [DllImport("ace32.dll", CharSet := CharSet.Ansi)];
        PUBLIC STATIC EXTERN METHOD AdsGetServerTime(hConnect AS IntPtr,  [InAttribute] [OutAttribute] pucDateBuf AS CHAR[], pusDateBufLen REF WORD , plTime OUT INT , [InAttribute] [OutAttribute] pucTimeBuf AS CHAR[] , pusTimeBufLen REF WORD ) AS DWORD 
```

**Expected behavior**
Without the above change, the call to each function passes nothing back in the Reference Value.

**Additional context**
There are quite a few wrong, but some ok e.g. AdsGetLastError() is ok.

**Comment by RobertvanderHulst** [comment]
Confirmed. I will have a look, but apart from the ones that you reported: if you have suggestions then please let us know.

**Comment by IanB-Ulysses** [comment]
Thanks....

I've started moving our Web App (the VO ASP Bit) to X# slowly (only taking me this long to start looking at it) and it fantastic how i can copy / paste code straight from VO into Visual Studio and it just works !.  I will send you a list of all the other ADS Functions that are declared with missing IN/OUT which i find.  Thanks for all your hard work.
