### ISSUE TITLE
Wrong tooltip when creating an instance of .net array

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#569]
Situation 1:

![image](https://user-images.githubusercontent.com/9467830/108254464-194fd100-716c-11eb-969d-2b98454eb076.png)
The hint is as if I'm creating a string, not an array of strings.
And if it is an array of INTs, BYTEs, etc. there is a NullReferenceException in X# plugin after typing "{".

Situation 2:

![image](https://user-images.githubusercontent.com/9467830/108255424-4fda1b80-716d-11eb-881b-dcb218710a56.png)
Wrong "onMouseOver" hint for a local variable which is one-dimensional .net array.

Situation 3:

![image](https://user-images.githubusercontent.com/9467830/108255806-c37c2880-716d-11eb-8f02-ec4feb384881.png)

Wrong for VAR either.

**Comment by RobertvanderHulst** [comment]
Thanks for the report.
We are actually inspecting the intellisense at this moment. We will try to fix these issues too. 

Which language version of VS are you using (I see strange characters (N3 ?)  in the first image between 1 and 8 :) )

**Comment by Serggio** [comment]
> Which language version of VS are you using (I see strange characters (N3 ?) in the first image between 1 and 8 :) )

Russian. That word means among/of: 1 of 8.

**Comment by cpyrgas** [comment]
Mostly working now, except for the VAR version, see comments below:

FUNCTION Start() AS VOID
	LOCAL locString := STRING[]{123} AS STRING[]
	VAR varString := STRING[]{123} 
	locString[1]: // shows members of STRING, correct
	varString[1]: // shows members of System.Array, wrong
// also hovering over varString shows "System.Array", instead of STRING[]

**Comment by cpyrgas** [comment]
Confirmed fixed
