### ISSUE TITLE
Val() incompatibility with VO with more than one decimal places

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#572]
Val("21.02.2021") returns 0 in VO, but 21.02 in X#. Need to obviously test many other similar cases.

Some more cases of Val() madness in VO:

```
FUNCTION Start() AS INT
SetDecimalSep(Asc("."))
? Val("21.02.2021")   // 0
? Val("21.02,2021")   // 21.02
? Val("21,02.2021")   // 21
? Val("21,0220.21")   // 21
? "---"
SetDecimalSep(Asc(","))
? Val("21.02.2021")   // 0
? Val("21.02,2021")   // 0
? Val("21,02.2021")   // 0
? Val("21,0220.21")   // 21.0220

? "---"
SetDecimalSep(Asc(","))

? Val("12,3.0") // 0
? Val("12,34.0") // 0
? Val("12,345.0") // 12,456 !!!

```

**Comment by cpyrgas** [comment]
Forgot to further comment on this one, after more close inspection I think the behavior of VO in this area is way too random and makes no sense at all, so I am afraid it's not worth trying to reproduce any of this. Probably let's just let it be as it is now in X# and in case we get other reports on this, decide what we can do.

**Comment by RobertvanderHulst** [comment]
Ok, so shall I close this ticket then ?

**Comment by cpyrgas** [comment]
Yes, I made a final attempt, to maybe at least just make it always return zero when there more than one decimal points in the string, but even this is not consistent at all:

```
SetDecimalSep(Asc("."))
? Val ("12.3.0")   // 0
? Val ("12.3.")    // 12.3
? Val ("12..1")    // 12
? Val ("12.13.22") // 0
? Val (".3.1")     // 0.3

```
