### ISSUE TITLE
VOWindows Designer displays CheckBoxes incorrectly

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#573]
**Describe the bug**
The VOWindows Designer in Visual Studio displays CheckBoxes incorrectly. Even if the Multiline property is set to False, the text wraps to multiple lines. If you run the application, the text doesn't wrap, as it is explected

![image](https://user-images.githubusercontent.com/9860916/109341993-839efa80-786b-11eb-83c4-7db3ce8159a8.png)

**To Reproduce**
1. Open a form in the VOWindows Designer
2. Add a CheckBox to the form
3. Set the caption to "CheckBox with Multiline = False", the width to 120 and the height to 40
4. The text wraps to multiple lines which not expected, if Multiline = False

**Desktop (please complete the following information):**
 - OS: Win10
 - VS: 2019

**Comment by cpyrgas** [comment]
Thanks for the detailed report, problem is fixed now!
