### ISSUE TITLE
.editorconfig is ignored in VS2017 for XSharp

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#58]
Otto:

It looks like .editorconfig is ignored in VS2017 for the XSharp languages. I tried setting the tabsize and indent size to a different value, but it doesn't effect the CTRL-K CTRL-D output. Same goes for the trailing spaces setting: the spaces stay... I put the file at the level where the .sln file is. The content is: root = true [*.{cs,csx,vb,vbx,prg,prgx,vh.xh,xs,rc}] # use utf8 with byte order mark charset = utf-8-bom indent_style = space indent_size = 4 tab_width = 4 trim_trailing_whitespace = true

**Comment by mattslay** [comment]
BTW - FoxPro also has "pass by reference".

From VFP Help:


> By default, variables and arrays pass to user-defined functions by value. Therefore, changes made in the function to passed variables and arrays are not passed back to the calling program. However, you can pass variables and arrays by reference by prefacing variables and arrays with the at sign (@) as shown in the following line of code:



`myFunction(@var1, @var2, ...)`

**Comment by RobertvanderHulst** [comment]
Matt,
I don't see what the relation is to the original topic. I have moved your comment to #51

**Comment by mattslay** [comment]
Oops, yes, that is where I intended to post my comment, I was just on the wrong issue when I commented. Sorry for the confusion.

**Comment by RobertvanderHulst** [comment]
Fixed in next build
