### ISSUE TITLE
No intellisence for delegate instances

### ISSUE THREAD

**Issue by LeonidLevenshtein** [X-Sharp/XSharpPublic#581]
If there is a variable of type DELEGATE, you expect to see a hint for its arguments when you call it. The tooltip is not displayed either after typing "(" or when hovering over it.

![image](https://user-images.githubusercontent.com/36951726/110808043-b1853580-8294-11eb-92bd-91b2932c83ca.png)

**Comment by RobertvanderHulst** [comment]
I am working on several editor issues at this moment. I'll make sure this will be fixed as well.

**Comment by RobertvanderHulst** [comment]
Fixed in next build
