### ISSUE TITLE
WinForms designer doesn't support DWord properties

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#588]
When I add a Control with a DWord Property to a Form in the WinForm designer, I'll get the error 

_Invalid Primitive Type: System.UInt32. Consider using CodeObjectCreateExpression._

1. Open a WinForms Project
2. Add the following Class
```
class DWordTest inherit System.Windows.Forms.TextBox
    public property Dummy as DWord auto get set
end class
```
3. Compile the project
4. Open a Windows Form and add the DWordTest Control
5. Save the Control and you'll get the error

**Comment by RobertvanderHulst** [comment]
This is documented (we overlooked that):
https://docs.microsoft.com/en-us/dotnet/api/system.codedom.codeprimitiveexpression?view=net-5.0
Primitive data types that can be represented using CodePrimitiveExpression include null; string; 16-, 32-, and 64-bit signed integers; and single-precision and double-precision floating-point numbers.

**Comment by RobertvanderHulst** [comment]
Fixed
