### ISSUE TITLE
Problem in _DbThrowErrorOnFailure()

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#594]
When a problem occurs in a function like DBSkip() (in my case it happened probably due to corruption because of https://github.com/X-Sharp/XSharpPublic/issues/585), a runtime exception is thrown inside the code of 
_DbThrowErrorOnFailure(), when trying to use the result of DoError(). Problem can be reproduced with a DBSkip() with no open workarea:

```

FUNCTION Start() AS VOID
DbSkip()

System.InvalidCastException
Specified cast is not valid.

Callstack : 
static Boolean XSharp.RT.Functions._DbThrowErrorOnFailure(System.String funcName, System.Boolean resultToCheck)()   :  C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Dbfunctions.prg  :  36
static Boolean XSharp.RT.Functions.DbSkip(XSharp.__Usual[] Xs$Args)()   :  C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Db.prg  :  661
static System.Void xRuntime.Exe.Functions.Start()()   :  C:\VIDE\Projects\Project3\Applications\xRuntime\Prg\xRntime.prg  :  2

```

**Comment by RobertvanderHulst** [comment]
In one of my last changes (for the error with DbUseArea()) I have added the VO error handling behavior including logging. This had the side effect that you report. I have fixed that.

I am now using a standard MessageBox() to display the VO error message. Unfortunately I cannot control the messagebox to only show an Abort and Ignore button. So it shows Abort, Retry, Ignore even when the error does not hate the CanRetry property set. VO used a custom dialog for this.
I think it is better if we replace this in X# too with a custom dialog. Chris, maybe you can quickly design a dialog with XIDE and include the code to create this dialog into the Runtime ?

**Comment by RobertvanderHulst** [comment]
> I think it is better if we replace this in X# too with a custom dialog. 
> Chris, maybe you can quickly design a dialog with XIDE and include the code to create this dialog into the Runtime ?

We can / should (re) use the existing ErrorDialog for this purpose.

**Comment by cpyrgas** [comment]
Robert, OK, I am working on updating the ErrorDialog class to also accept an Error object in its constructor

**Comment by cpyrgas** [comment]
Ahh, I just updated the ErrorDialog to handle this, only to realize that this class is defined in XSharp.VO, while it needs to be used from XSharp.RT (DefError() function). 

Should I move the ErrorDialog to the RT assembly? Problem is that also references to System.Windows.Forms and System.Drawing need to be added to it.

**Comment by RobertvanderHulst** [comment]
Mmm, maybe you can check if the ErrorDialog class exists with `IsClass(#ERRORDIALOG)` and then use that class (with CreateInstance). 
Otherwise you can default to using the MessageBox just like what I am doing at this moment

**Comment by cpyrgas** [comment]
I used a delegate instead and that gets set from an _INT procedure in XSharp.VO, so it will be used if available. Tested it and seems to work well, but If you'd like anything changed in this approach, please feel free to change!

**Comment by RobertvanderHulst** [comment]
I merged the two constructors ( with e as Exception and oError as Error) and added code that disable the Copy To Clipboard button when the start function does not have the [STAThread] attribute

**Comment by cpyrgas** [comment]
OK, looks good!

**Comment by cpyrgas** [comment]
So this is great, another great step to providing even better compatibility to VO!!

There's a problem though, what if someone does not want VO compatibility? :)
I mean if I am building a new app and do not want to have those error windows show, but instead handle errors and exceptions the .Net way (through normal exception handling), how can I do this now?
I tried using ErrorBlock({||}), but this makes the original code completely eat the error:

ErrorBlock({||})
DBCloseAll()
DbSkip()
? "no error at all!"

I tried re-throwing the error with ErrorBlock({|o| THROW o}) but this leads to a compiler parser error. Maybe we should introduce a runtime setting (enabled by default in VO dialect) to control if RDD errors should be VO-compatible showing the Abort/Ignore dialog or if they should throw an exception as they did before in X#?

Also there is a problem when nulling the errorblock as above. The following runs with no errors in VO, but throws an exception in X#:


```
FUNCTION Start() AS VOID
ErrorBlock({||})
DbUseArea(,,"c:\nonexistant")

System.NullReferenceException
Object reference not set to an instance of an object.

Callstack : 
static Boolean XSharp.RT.Functions.DbUseArea(XSharp.__Usual[] Xs$Args)()   :  C:\xSharp\DevRt\Runtime\XSharp.RT\RDD\Db.prg  :  688

```

**Comment by wriedmann** [comment]
PMFJI: It is very important that the error handling can also work in a Windows service application or a WPF application.
If this can be accomplished only assigning a new errorblock IMHO the .NET compatible exception handling is not needed, but it should be clearly documented.

**Comment by cpyrgas** [comment]
Also should clicking "Abort" stop execution of the program? At this moment, program execution continues when either "Abort" or "Ignore" is pressed.

FUNCTION Start() AS VOID
DbSkip()
? "program continues here"

**Comment by RobertvanderHulst** [comment]
I do not see this.
When I create a new console app with the following code 
```
FUNCTION Start() AS VOID
DbSkip()
? "program continues here"
wait
```
Then pressing Ignore on the dialog will show the text and "press any key". pressing Abort will close the program.

**Comment by cpyrgas** [comment]
Robert, ah ok, found what's causing this, it's that _Quit() uses GetCurrentProcess():CloseMainWindow() which indeed closes the app console window as created by VS, but it does not close the one created by XIDE. So it's a completely different matter.

What about the issue with not being possible now to override the VO-compatible behavior and generate exceptions instead of displaying Abort/Retry dialogs? Should I create a separate feature request for this?

**Comment by RobertvanderHulst** [comment]
Chr,s,
Yes create a new ticket for this and close the current one.
We'll fix this in the next sprint.
Robert

**Comment by cpyrgas** [comment]
OK, problem confirmed fixed. Also it's actually easy enough to trap and throw the exception, with something like

ErrorBlock( { |e| DoThrow(e) } )

PROCEDURE DoThrow(oError AS Exception)
THROW oError
