### ISSUE TITLE
Interpolated Strings with dotnet objects don't work as expected

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#598]
The following code should create the same output, but doesn't:

```
var keyValue := KeyValuePair<string, string>{"A", "B"}

Console.Writeline(i"Interpolated string: {keyValue:Key} = {keyValue:Value}") 
Console.Writeline(string.format("String.Format: {0} = {1}", keyValue:Key, keyValue:Value)) 
```

The output is

```
Interpolated string: [A, B] = [A, B]
String.Format: A = B
```

I tried to replace  `{keyValue:Key}` with  `{keyValue.Key}` but that gives me the error error `XS0118: 'keyValue' is a variable but is used like a type`.

I prepared a sample project to reproduce this problem: [XSharpConsole.zip](https://github.com/X-Sharp/XSharpPublic/files/6303596/XSharpConsole.zip)

**Comment by RobertvanderHulst** [comment]
Volkmar,
The problem with the colon (":") inside the interpolated string is that this character is also used to specify formatting options:
`{<interpolationExpression>:<formatString>}`
That is why this does not work the way you expect it to work. I think the expression that we pass to Roslyn is
```
<interpolationExpression> = keyValue
<formatString> = Key
```

Roslyn does not warn that Key is an incorrect format string but simply does the ToString() on keyValue which results in the display of `[A, B]`

The solution would be indeed to use the dot as instance operator but that produces the error that you mention. I'll see what I can do about that.

**Comment by RobertvanderHulst** [comment]
We have change the handling of interpolated strings now.
When "allowdot" is enabled then the ":" character is used as prefix for format strings.
When "allowdot" is disabled then the ":" character is the normal send operator and then you need to prefix format strings with "::" (double colon), like in the following example:

```
#pragma options("AllowDot", OFF)
FUNCTION TestColon AS VOID
	LOCAL i AS LONG
	i := 42
	? i"i = {i:ToString()}"     // when AllowDot = OFF then the colon = send operator
	? i"i = {i::F2}"            // and "::" is used as Format separator
RETURN
#pragma options("AllowDot", ON)    
FUNCTION TestDot AS VOID
	LOCAL i AS LONG
	i := 42
	? i"i = {i.ToString()}"     // when AllowDot = OFF then the DOT = send operator
	? i"i = {i:F2}"             // and ":" is used as Format separator
RETURN

```

**Comment by cpyrgas** [comment]
Confirm fixed
