### ISSUE TITLE
Wrong string comparison with Windows collation in Exact mode

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#601]
Illustrated here:
```
	SetCollation(#WINDOWS)
	SetExact(TRUE)

	? "AB" >= "A"	// TRUE - ok
	? "AB" <= "A"	// TRUE - ??? <- here is the problem
	? "AB" == "A"	// FALSE - ok
	? "AB" = "A"	// FALSE - ok
```

As far as I see the problem is in StringHelpers.CompareWindows function. If left string is longer than the right one, it compares common parts and if they are equal it just returns 0, while should return 1.

**Comment by cpyrgas** [comment]
Indeed this does not look right and VO does return the expected result. Will look into it, thanks.
Btw, /vo13+ needs to be enabled to reproduce the problem.
