### ISSUE TITLE
Methods combobox is badly synced in some cases

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#602]
If there are two classes with methods of the same name in one prg you would likely get a situation when methods combobox will show the first occurence of the method and not the one you stand at.

![image](https://user-images.githubusercontent.com/9467830/115300810-14f26500-a169-11eb-93bf-6564ce472a38.png)

**Comment by RobertvanderHulst** [comment]
This is most likely already fixed with the build that will be released end of this week.

**Comment by cpyrgas** [comment]
I cannot reproduce the problem with the latest build, but I could not reproduce it before either. I will not confirm it as fixed yet, maybe better wait for Serggio to confirm this when the new build comes out. In this case we would need a sample file/project reproducing this problem.

**Comment by RobertvanderHulst** [comment]
Serrgio, are you still seeing this, or can we close the issue ?

**Comment by Serggio** [comment]
Yes, everything's fine now! Thank you!
