### ISSUE TITLE
Small problems with the "automatic conversion to PSZ" warning XS9068

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#603]
See the following code, there are two problems:

- It should report 4 warnings for automatic PSZ conversion, but instead reports only 3
- The first warning, points to line 10, which is a LOCAL declaration. The other 2 warnings point correctly to the correct lines where PSZ() is used.

```
FUNCTION Start() AS VOID
TestClass{}:foo()
RETURN

CLASS TestClass
EXPORT something AS PSZ
CONSTRUCTOR()
SELF:something := String2Psz("something")
METHOD foo() AS VOID
LOCAL uObj := TestClass{} AS USUAL  // line 10, first warning incorrectly points here
LOCAL uPsz := String2Psz("abc") AS USUAL

? PSZ(uObj:something)
? PSZ(uObj:something)

? PSZ(uPsz) // line 16, correct
? PSZ(uPsz) // line 17, correct

RETURN

END CLASS


Start.prg(10,1): warning XS9068: The compiler generated an automatic conversion to PSZ. This may create a memory leak in your application. Please use String2Psz() to let the compiler manage the lifetime of the PSZ or use StringAlloc() and manage the lifetime of the PSZ yourself.

Start.prg(16,1): warning XS9068: The compiler generated an automatic conversion to PSZ. This may create a memory leak in your application. Please use String2Psz() to let the compiler manage the lifetime of the PSZ or use StringAlloc() and manage the lifetime of the PSZ yourself.

Start.prg(17,1): warning XS9068: The compiler generated an automatic conversion to PSZ. This may create a memory leak in your application. Please use String2Psz() to let the compiler manage the lifetime of the PSZ or use StringAlloc() and manage the lifetime of the PSZ yourself.

```

**Comment by RobertvanderHulst** [comment]
I suspect that both warnings for uObj:Something point to line 10 and that the compiler eliminates the duplicate warning

**Comment by RobertvanderHulst** [comment]
This code cannot work correctly.
```
CONSTRUCTOR
SELF:something := String2Psz("something")

```
This allocates a temporary PSZ in the String2Psz() function, assigns it to the field and then when the constructor is done this temporary psz will be released. I will test this with the following code
```
CONSTRUCTOR()
SELF:something := StringAlloc("something")
DESTRUCTOR
    MemFree(something)
    RETURN
```
I think the missing error message is due to the fact the (compiler generated) code to handle the late bound call is linked to the line when the uObj variable is created. There will be 2 identical error messages for the same line and the second of these messages is suppressed.

**Comment by cpyrgas** [comment]
Nice, will test with the new compiler once it's available.

How about the problem with the code that assigns a String2Psz() to an iVar? Can this be somehow detected, so that the user can be earned with a compiler warning? It's not critical of course, especially since from what I see VO also does not report a warning either, would be just nice to have if possible.

**Comment by RobertvanderHulst** [comment]
Chris,
I'll see if I can detect the warning. That would require some analysis for all assign statements where the Right side is String2Psz(). I would have to detect if the left side is a Field and then issue a warning. 
Can you create a new ticket for that ?

**Comment by cpyrgas** [comment]
Confirmed fixed
