### ISSUE TITLE
Macro compiler cannot find functions from dynamically loaded assemblies

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#607]
If an assembly is loaded at runtime, the macro compiler will not find functions in it. I think there is an assembly cache that needs to be updated. I agree to update it manually upon loading the assembly, if there is such a way.

PS. Yes, it's inside Binder class which has internal static fields serving as a cache and **BuildIndex** method to fill them on the first occasion. If some DLL is loaded afterwards it stays beyond macro compiler's observation. There should be a way to manually call some reset for this cache.

**Comment by RobertvanderHulst** [comment]
Serrgio,
Do you have an example ?

**Comment by Serggio** [comment]
I've made a small solution to illustrate the problem:
[TestMacro.zip](https://github.com/X-Sharp/XSharpPublic/files/6356062/TestMacro.zip)

**Comment by RobertvanderHulst** [comment]
Thanks. I see it too. We'll have a look at it.

**Comment by nvkokkalis** [comment]
This is expected. Recreating the type cache when an assembly is loaded dynamically is not implemented. I will work on it.

**Comment by cpyrgas** [comment]
Robert, I am having trouble building the macro compiler, will wait till you create a new set of runtime dlls to test this.

**Comment by cpyrgas** [comment]
Confirmed fixed.
