### ISSUE TITLE
Endless data reading using a DBF file handle

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#608]
Sometimes the program requires direct reading of data from an open DBF file. In this case, we can get the handle of the open workarea using DBInfo(DBI_FILEHANDLE) and then use it in file functions: FRead, FSeek, etc. It works well in VO.

But there was a problem with this approach in X#. The FRead function, after reaching the end of the file, continues to endlessly read data (zeros) as if it were, returning the number of bytes read equal to the requested amount, and the file pointer is constantly increasing.

Small test project in attachment.
[TestConsoleApplication.zip](https://github.com/X-Sharp/XSharpPublic/files/6358159/TestConsoleApplication.zip)

**Comment by RobertvanderHulst** [comment]
Fixed in edf6bd4a84f85089d976094b55a0927ee11d0312

**Comment by cpyrgas** [comment]
Confirmed fixed. Note though that in the sample provided, reading does not start at byte 1, but at byte 65, apparently that's where the RDD has left the file pointer at. Just to make sure that this is taken in account in the real code!

**Comment by leon-ts** [comment]
Chris,
This is just a quick example to illustrate the problem.
In real code, the DBF File header is skipped and the cursor is positioned on the first data record.

The code looks like this:
```
VODBSetSelect(nArea)
hSrcFile := DBInfo(DBI_FILEHANDLE)
nHeadSize := DBInfo(DBI_GETHEADERSIZE)
nSrcRecSize := DBInfo(DBI_GETRECSIZE)
lAnsi := DBInfo(DBI_ISANSI)
...
FSeek3(hSrcFile, nHeadSize, FS_SET)
// FRead3() loop
...
VODBCloseArea()
```

**Comment by cpyrgas** [comment]
Leonid, that's perfect, this should be working correctly now!
