### ISSUE TITLE
VFP Command MKDIR and a VFP function named MkDir()

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#614]
The VFP help doesn t know a MkDir() function, but in the XSharp.VFP.dll such a function exists. While searching for a VFP MkDir() function i found a site that mentions such a function.

https://documentation.help/MS-Visual-FoxPro/confoxtools.htm

Only the functions marked in red have been added to VFP, and these functions are documented in the VFP9 Help

I think the MkDir() function should be removed, or at least renamed. A similar naming problem would arise if the functionality of 
the "foxtools" function RMDIR() would be added to the XSharp.VFP.dll, because the name of the Fox delete dir command is - beside RM - RMDIR

Karl-Heinz

**Comment by Karl1155** [comment]
in addition:

in the forum a VFP user answered yes to my question about whether a runtime error is thrown when a dir command fails. Now, the idea is to implement e.g MKDIR in this way. 

```
#command MD <(dir)> => CommandDirMake (<(dir)>  ) 
#command MKDIR <(dir)> => CommandDirMake (<(dir)>  ) 

FUNCTION CommandDirMake(pszNewDir AS STRING) AS INT
	LOCAL result AS INT 
	
	TRY
		XSharp.IO.File.ClearErrorState()
		Directory.CreateDirectory(pszNewDir)
	CATCH e AS Exception
		XSharp.IO.File.SetErrorState(e)
		result := (INT) RuntimeState.FileError
	END TRY

	IF RuntimeState.FileError != NULL
		THROW RuntimeState.FileException		
	ENDIF 			
	
	RETURN result
```


Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
Thanks for the contribution.
I think it makes sense to introduce functions with the name "CommandDoSomething" for missing commands.
I would probably prefix the function name with an underscore, to indicate that these are not created for "normal use" but are used in code generated by the compiler. But that is a minor detail.

Robert

**Comment by cpyrgas** [comment]
Confirmed done
