### ISSUE TITLE
Incorrect Todo parsing

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#617]
The parsing of the comments to extract the items for the task list doesn't work as expected. 

Try to add the following comments to a prg file. 

```
// TODO: Should be listed in task list
// This is a comment containing the word todo, which should not be listed in the task list
// Chackbox (Checkbox with typo) should not be listed in the task list
```

This creates the following task entries

![image](https://user-images.githubusercontent.com/9860916/116096215-6474eb80-a6a9-11eb-9eac-b996f7ea6580.png)

It seems, that every comment containing the substring Todo, Hack or Undone is added to the task list. But only comments beginning with Todo, Hack or Undone should be used.

**Comment by RobertvanderHulst** [comment]
Volkmar,
The tokens that we scan for are configurable in VS:
Tools/Options
Environment/Tasklist
I checked what C# does and it will:
- include TODO:
- include todo, 
- NOT include hackbox

So it apparently C# makes sure that the text is a whole word and not part of another word. 
We'll change our implementation to follow that model.

**Comment by VolkmarR** [comment]
Hello Robert,

I did some additional tests. It seems, that for cs files, visual studio creates a task item for every comment-line, that begins with one of the defined tokes (if the token is not part of another word). It makes no difference if the comment is a single line or multi line comment.

![image](https://user-images.githubusercontent.com/9860916/116110324-e10dc700-a6b5-11eb-85e7-54a69cb5b7cc.png)

I personally never created a Todo entry inside a multi-line comment, so i wouldn't mind, if that would not work.

**Comment by RobertvanderHulst** [comment]
Volkmar,
Thanks for the research. I'll adjust our task items accordingly.

**Comment by cpyrgas** [comment]
Confirmed fixed
