### ISSUE TITLE
Compiler crash with a very specific namespace name

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#618]
Following code produces 2 identical assertion failed dialogs:

```
BEGIN NAMESPACE xsharp.BackupService // compiler crash here
// BEGIN NAMESPACE XSharp.BackupService // this works ok
CLASS Anything
END CLASS
END NAMESPACE

```

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
   at LanguageService.CodeAnalysis.XSharp.Symbols.NamespaceOrTypeSymbol.LookupMetadataType(MetadataTypeName& emittedTypeName)
   at LanguageService.CodeAnalysis.XSharp.Symbols.NonMissingModuleSymbol.LookupTopLevelMetadataType(MetadataTypeName& emittedName)
   at LanguageService.CodeAnalysis.XSharp.Symbols.NonMissingAssemblySymbol.LookupTopLevelMetadataTypeWithCycleDetection(MetadataTypeName& emittedName, ConsList`1 visitedAssemblies, Boolean digThroughForwardedTypes)
   at LanguageService.CodeAnalysis.XSharp.Symbols.AssemblySymbol.LookupTopLevelMetadataType(MetadataTypeName& emittedName, Boolean digThroughForwardedTypes)
   at LanguageService.CodeAnalysis.XSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(AssemblySymbol assembly, MetadataTypeName& metadataName, AssemblyIdentity assemblyOpt)
   at LanguageService.CodeAnalysis.XSharp.Symbols.AssemblySymbol.GetTopLevelTypeByMetadataName(MetadataTypeName& metadataName, AssemblyIdentity assemblyOpt, Boolean includeReferences, Boolean isWellKno......
<truncated>
---------------------------
Abort   Retry   Ignore   
---------------------------
```

**Comment by RobertvanderHulst** [comment]
Chris,
These "assertion failed" dialogs only appear when you run the debug version of the compiler and not when you run the release version of the compiler.
Was Danilo also using the debug version of the compiler ? And if so, do you know why ?
When I check this code with the version of the compiler that is included in the 2.8 installer then there is no assertion error and the code compiles and runs without problems.

Robert

**Comment by cpyrgas** [comment]
Robert,
I have not sent anything related to Danilo, so I am sure he is using the version that comes with the latest installer. So do I, I have not replaced it with anything else, I'm on the compiler as created by the latest installer. Maybe the wrong files were included in the installer? Or maybe a setting was present accidentally which causes assertions to show?

**Comment by Karl1155** [comment]
i checked the content of the XIDE [Output] tabpage, and it seems that the debug version is used ?   

X# Compiler version 2.8.0.10 (debug)
Copyright (C) XSharp BV

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
That is odd. You should see X# Compiler version 2.8.0.11 (release)
If you open the properties of "c:\Program Files (x86)\XSharp\Bin\xsc.exe" , which time stamp do you see on the "Digital Signatures" page ?

**Comment by Karl1155** [comment]
Robert


The [Digital Signatures] time stamp is

Mittwoch, 21. April 2021 20:45:44

and the file version - [Details] - shows

2.8.0.11 

?

i verified in XIDE the compiler location, and it's ok. It points to my install dir

C:\XSharp\BIN\xsc.exe

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Just to be clear: the file C:\XSharp\BIN\xsc.exe has 
```
The [Digital Signatures] time stamp is
Mittwoch, 21. April 2021 20:45:44
and the file version - [Details] - shows
2.8.0.11
```
but displays 
`X# Compiler version 2.8.0.10 (debug)`

I think I need a holiday.

**Comment by Karl1155** [comment]
yes, i even started the compiler in the C:\XSharp\Bin

```
C:\XSharp\Bin>xsc.exe
X# Compiler version 2.8.0.10 (debug)
Copyright (C) XSharp BV

warning XS2008: No source files specified.
error XS1562: Outputs without source must have the /out option specified
```

**Comment by Karl1155** [comment]
i installed 2.7 and then 2.8 again, but still the same. 
i started the xsi.exe and it also shows the same msg

```
C:\XSharp\Bin>xsi.exe
X# Interactive Compiler version 2.8.0.10 (debug)
Copyright (C) XSharp BV. All rights reserved.

Type "#help" for more information.
>


```

**Comment by RobertvanderHulst** [comment]
Ok, I see now what has happened:
an older debug version of the XSharp.CodeAnalysis.DLL was copeid to XSharp\Debug folder and registered in the GAC.
The version info that you see is coming from the resources inside this DLL. 
I'll recheck the installer to make sure:
- that the right version number of XSharp.CodeAnalysis.DLL is installed in the debug folder
- that the file in the debug folder does not get added to the GAC,
-

**Comment by cpyrgas** [comment]
Confirm fixed
