### ISSUE TITLE
VS intellisense error callstack

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#62]
Got the following error log when I typed the dot in line 60 of
Form1.Designer.prg:

o := ClassLibrary1.

-----------------------------------
Error
Editor or Editor Extension
System.InvalidOperationException: Unable to get
TextViewLine containing insertion point.
at
Microsoft.VisualStudio.Text.MultiSelection.Implementation.SelectionUIProperties.get_ContainingTextViewLine()
--- End of stack trace from previous location where exception
was thrown ---
at
Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception
exceptionObject)

[WindowsFormsApplication37.zip](https://github.com/X-Sharp/XSharpPublic/files/3297291/WindowsFormsApplication37.zip)

**Comment by fforay** [comment]
Sorry, but I'm not able to reproduce the error, even using the attached sample.
FYOI, the ClassLibrary1 library is not referenced by the application...but I suspect it is not related with the error that you have.

**Comment by cpyrgas** [comment]
Fabrice, I get this error every time after I use VS for the first time after I install a new X# build, I assume this happens because the new installation resets something and allows this problem to be reported again. I thought it wouldn't happen at your end, but was hoping the callstack might give an idea of what is going wrong, and maybe a TRY...END TRY would take care of it. For the same reason I post all the callstacks I get from time to time. ANyway, not a big deal, I think this is probably a rare issue.
