### ISSUE TITLE
Interpolated string and formatting delimiters in dialects that use ":" for send operator

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#622]
We will have to come up with an alternative for the delimiter that is used to delimit the expressions and formatstring inside interpolated strings. For Core and FoxPro we can assume "." as universal send operator and ":" as delimiter between expression and formatstring. For the other dialects we should define an alternative separator, such as for example "::".

**Comment by RobertvanderHulst** [comment]
When we are busy here, make sure that the Full macro sets the option "AllowDotForInstanceMembers" according to the dialect. It does not do that at this moment.

**Comment by RobertvanderHulst** [comment]
Implemented this in commit 682d8de6d176756e2b95c213ab3b83b0ab846853. This also takes care of AllowDotForInstanceMembers in macro compiler was implemented in

**Comment by cpyrgas** [comment]
Confirmed fixed.
