### ISSUE TITLE
Problems with Transform() and symbol arguments

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#628]
In VO, when Transform() is called with a symbol argument, it seems to always return an empty string.

In X#:
- Transform(#something,"") returns "SOMETHING", which is incompatible to VO
- Transform(uSymbolInUsual) throws an exception

```
FUNCTION Start() AS VOID
LOCAL u AS USUAL
u := #somesymbol
? Transform(#somesymbol,"") // SOMESYMBOL, should be empty string
? Transform(u,"") // rutnime exception

XSharp.Error
Invalid argument type

Callstack : 
static String XSharp.RT.Functions.Transform(XSharp.__Usual uValue, System.String cSayPicture)()   :  C:\xSharp\DevRt\Runtime\XSharp.RT\Functions\Transform.prg  :  796

```

**Comment by cpyrgas** [comment]
I fixed the runtime exception, now Transform(uSymbolInUsual) returns "" as in VO.

But now when called with a literal symbol instead of a symbol in usual, as in Transform(#SomeSymbol), it returns different results than when using the same argument in a usual, because the compiler directly calls the STRING overload of Transform() and then there's no way that the original argument was a symbol, in order to return "".

Maybe the compiler needs to be adjusted (hardcoded) to always prefer a usual overload instead of a string one, when using a SYMBOL argument?

**Comment by RobertvanderHulst** [comment]
Chris, such as hard coded exception will most likely cause other problems.
I personally think that the code in bBrowser that was using Transform for a symbol should be changed. This was relying on the fact that the Symbol type was not handled in VO. 
The Transform code was inherited from Clipper where it was used to handle pictures for @ SAY .. GET.
Clipper did not know SYMBOL so therefore the original developers never implemented a transform for symbols.

**Comment by cpyrgas** [comment]
Robert, I agree, the best solution would be to adjust the original code, but then again we do not know if there's code also in other people's apps that relies (on purpose or not) on this behavior of VO.

Anyway, the big problem was that the version with a usual argument was throwing an exception and this is fixed now, waiting for Joe's confirmation that this has fixed the problem in his app.

**Comment by cpyrgas** [comment]
Haha, some times the simplest and easiest solution is also the best and most straightforward!

Should be working fine, but a quick test I did failed, looks like the (both file and assembly) version of the runtime dlls has now accidentally increased to 2.80 ?

**Comment by RobertvanderHulst** [comment]
Sorry about that. I'll roll that change back.

**Comment by cpyrgas** [comment]
Robert, I don't see any related change you did that could be affecting this. In fact, I am a bit at a loss, because I tried changing the contents of BuildNumber.h, but whatever values I put there, the dlls still always keep reporting the 2.8 version strings. Really puzzled...

**Comment by cpyrgas** [comment]
Oh, and this happens only when I compile from VS. I just tried building the runtime from XIDE, and dlls do correctly get the version strings I am giving them in BuildNumber.h. This is really strange...

**Comment by cpyrgas** [comment]
Confirmed fixed.

**Comment by RobertvanderHulst** [comment]
Chris,
Inside VS I have set the RUNTIME define in the project files This gets set in the Runtime.Targets file.
The code inside buildnumber.h is:
#ifdef RUNTIME
    #define VERSION_NUMBER     "2.6.0.0"
#else
    #define VERSION_NUMBER     "2.8.0.0"
#endif

I had to do this because the header file is also used in the VS Integration.
I have pushed this change on April 19 in changeset 89ddc6df0eb7f2593bf79722e0d0b36fae6f5a90

**Comment by cpyrgas** [comment]
Yeah, I have seen that, and I have added the same defines also in XIDE. But for some reason here in XIDE it works (dlls get the intended version number), but it does not in VS, since a week ago or so. It is really strange, but it's not a problem for me currently, since I can compile the runtime in XIDE. Except for the macro compiler, this one does not compile in XIDE :).
