### ISSUE TITLE
DBFVFPSQL Index creation problem

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#630]
From https://www.xsharp.eu/forum/public-vfp/2495-2-6a-vs-2-8-index-creation-problem-why#18309
[Note that with plain DBFVFP driver, I could not reproduce the problem, so it must have to do with the SQL driver]

Before the index creation and DbGoTop() the record pointer is in EOF ignoring the DBGoTop().

Less important but diferent in foxpro, when a record pointer is in eof, It never lose its data type. If a field is char(xx), the value in EOF is space(xx), if a field is numeric, the value in EOF is 0, etc.

```
USING System
USING System.Collections.Generic
USING System.Linq
USING System.Text

FUNCTION Start() AS VOID STRICT
    ? "Hello World! Today is ",Date()
    private _handle
    STORE SqlConnect("MSSQLTEST") to _handle
    LRESULT = SqlExec(_handle , "select m03codoper, m03vigente from m03oper","w03oper")
    DbSelectArea("w03oper")
    ? "After DbCreateIndex", "DbGoTop:", DbGoTop(), "Eof:",Eof() , "RecCount():", RecCount(), "Recno:", RecNo()
    ? w03oper->m03codoper
    ? w03oper->m03vigente
    ?DbCreateIndex("key1",,{|| m03vigente + m03codoper } ,FALSE)
    ? "Before DbCreateIndex", "DbGoTop:", DbGoTop(), "Eof:",Eof() , "RecCount():", RecCount(), "Recno:", RecNo()
    ? w03oper->m03codoper
    ? w03oper->m03vigente
```

```
Output:
Hello World! Today is  04/05/2021
After DbCreateIndex DbGoTop: .T. Eof: .F. RecCount(): 5568 Recno: 1
$ 01 BI
N
.T.
Before DbCreateIndex DbGoTop: .T. Eof: .T. RecCount(): 5568 Recno: 5569
.F.   ???  What happend with DbGoTop in prior line ?  End of file value is Logical y a character field? 
.F.
```

**Comment by RobertvanderHulst** [comment]
Fixed. The RDD was not handling NULL values for strings properly. And as a result the index tag was seen as "invalid".
We had added code that allows invalid tags to be opened (to be compatible with VO) but no index operations were supported.
Also the NULL values for the Phantom record were not handled properly as well. They were returned as NIL which has a value of FALSE for the FoxPro dialect

**Comment by cpyrgas** [comment]
Robert, that's great, but how did you know that there were NULL values involved ???

**Comment by RobertvanderHulst** [comment]
Deduction, and a little luck.
I tested it against a local SQL server and I also had columns in the table that were allowed to be null. Creating an index on a non nullable column worked, but creating the index on the nullable column failed just like the code from our customer.

**Comment by cpyrgas** [comment]
Robert, I'll just trust you on this one and mark it as confirmed fixed :)
