### ISSUE TITLE
Problem with IRdd:OrderInfo(DBOI_RECNO) in VFP dialect

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#631]
This was found with testing with Robert's dbfs from https://github.com/X-Sharp/XSharpPublic/issues/625. 

With the specific attached dbf file (and none of the others), the following code throws an exception, when run in VFP dialect. When the exact same code is run in VO dialect, then it runs with no errors, but appears to return incorrect results for DBOI_RECNO and DBOI_POSITION (both 0)

[orders.zip](https://github.com/X-Sharp/XSharpPublic/files/6436373/orders.zip)

I am attaching also a full VS solution containing both a VO and VFP version of the same code reproducing this behavior.

[DBFVFP_test.zip](https://github.com/X-Sharp/XSharpPublic/files/6436370/DBFVFP_test.zip)

```
FUNCTION Start() AS VOID

? DbUseArea(TRUE,"DBFVFP","C:\xSharp\_Robert\data\orders.dbf")

LOCAL oRdd AS XSharp.RDD.IRdd
oRdd := XSharp.RuntimeState.Workareas:GetRDD(1)

LOCAL oInfo AS XSharp.RDD.Support.DbOrderInfo
oInfo := XSharp.RDD.Support.DbOrderInfo{}
oInfo:Order := 1

? oRdd:OrderInfo(DBOI_EXPRESSION, oInfo) // customerid, correct
? oRdd:OrderInfo(DBOI_CONDITION, oInfo) // false, correct
? oRdd:OrderInfo(DBOI_ISDESC, oInfo) // false, correct

? oRdd:OrderInfo(DBOI_RECNO, oInfo)  // exception in VFP, 0 in VO dialect
? oRdd:OrderInfo(DBOI_POSITION, oInfo) // exception in VFP, 0 in VO dialect

? DbCloseArea()



XSharp.RDD.RddError


Callstack : 
XSharp.RDD.DBFVFP.System.Void XSharp.RDD.DBF._dbfError(System.Exception ex, System.UInt32 iSubCode, System.UInt32 iGenCode, System.String strFunction, System.String strMessage, System.UInt32 iSeverity, System.Boolean lThrow)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\Dbf\DBF.prg  :  1419
XSharp.RDD.DBFVFP.System.Void XSharp.RDD.DBF._dbfError(System.UInt32 iSubCode, System.UInt32 iGenCode, System.String strFunction, System.String strMessage, System.Boolean lThrow)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\Dbf\DBF.prg  :  1389
XSharp.RDD.CDX.CdxTag.System.Void XSharp.RDD.CDX.CdxTag._UpdateError(System.Exception ex, System.String strFunction, System.String strMessage)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagUpdate.prg  :  27
XSharp.RDD.CDX.CdxTag.Int32 XSharp.RDD.CDX.CdxTag._locate(System.Byte[] keyBuffer, System.Int32 keyLength, XSharp.RDD.SearchMode searchMode, System.Int32 pageOffset, System.Int32 recNo)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagNavigation.prg  :  794
XSharp.RDD.CDX.CdxTag.Int32 XSharp.RDD.CDX.CdxTag._locate(System.Byte[] keyBuffer, System.Int32 keyLength, XSharp.RDD.SearchMode searchMode, System.Int32 pageOffset, System.Int32 recNo)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagNavigation.prg  :  877
XSharp.RDD.CDX.CdxTag.Int32 XSharp.RDD.CDX.CdxTag._locateKey(System.Byte[] keyBuffer, System.Int32 bufferLen, XSharp.RDD.SearchMode searchMode, System.Int32 recNo)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagNavigation.prg  :  649
XSharp.RDD.CDX.CdxTag.Int32 XSharp.RDD.CDX.CdxTag._locate(System.Byte[] keyBuffer, System.Int32 keyLength, XSharp.RDD.SearchMode searchMode, System.Int32 pageOffset, System.Int32 recNo)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagNavigation.prg  :  868
XSharp.RDD.CDX.CdxTag.Int32 XSharp.RDD.CDX.CdxTag._locateKey(System.Byte[] keyBuffer, System.Int32 bufferLen, XSharp.RDD.SearchMode searchMode, System.Int32 recNo)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagNavigation.prg  :  649
XSharp.RDD.CDX.CdxTag.Int32 XSharp.RDD.CDX.CdxTag._goRecord(System.Byte[] keyBytes, System.Int32 keyLen, System.Int32 gotoRec)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagNavigation.prg  :  612
XSharp.RDD.CDX.CdxTag.Boolean XSharp.RDD.CDX.CdxTag._GoToRecno(System.Int32 recno)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTagNavigation.prg  :  625
XSharp.RDD.CDX.CdxTag.Boolean XSharp.RDD.CDX.CdxTag._getRecPos(System.Int32 record)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\Tag\CdxTag.prg  :  607
XSharp.RDD.DBFVFP.Object XSharp.RDD.DBFCDX.OrderInfo(System.UInt32 nOrdinal, XSharp.RDD.Support.DbOrderInfo info)()   :  C:\xSharp\DevRt\Runtime\XSharp.Rdd\DbfCdx\DbfCdx.prg  :  177

```

**Comment by RobertvanderHulst** [comment]
Please note that to properly test this you also need the DBC file. See attachment
[NORTHWIND.ZIP](https://github.com/X-Sharp/XSharpPublic/files/6523646/NORTHWIND.ZIP)

**Comment by RobertvanderHulst** [comment]
There is something strange with this file. It seems that the VFP file format has changed a bit and this change was never documented (I googled for hours). 
In this file the CustomerId field is "Nullable" and has a length of 5 characters. In the CustomerId tag which is indexed on "CustomerId" there are 6 bytes for each key. Every key is prefixed with a byte with the value 0x80. This probably has to do with the "not null" status of the field. 
I'll have to adjust the CDX driver to properly handle this.

**Comment by RobertvanderHulst** [comment]
This issue demonstrates several problems:
- The orders.dbf /cdx was part of a FoxPro Database (Northwind.dbc). Several columns in this table have a longer fieldname in the DBC, such as ShippedDate. The index expression is on the longer field name. When you open this table as "free table"  (so when the DBC is not in the same folder) then this index expression is invalid.
- This table contains fields that can be NULL. You can see that in the structure because there is a field with the name _NullFlags.
- The field CustomerId can be null and there is an index on this field
- The CustomerId field is 5 bytes but because the field can be null the index keys are 6 bytes long. The first byte for each key value is either 0 (for fields that are NULL) or 128 (for non null fields). For null keys all the bytes are set to 0, but it is also possible to have a field that contains 5 x chr(0). This is not null and will therefore be represented as a key with the value 128 followed by 5 x 0.
- The DBOI_Recno operation in the current build is calculating a key to seek the index and does not properly handle the Nullability and therefore seeks with keys of 5 bytes which obviously does not work.
I'll adjust the CDX driver to:
- to ignore indexes with incorrect key expressions
- recognize nullable indexes and allocate an extra byte
- set the correct first byte for index keys in these indexes and for search expressions for these indexes
- correctly handle comparison between null values and non null values

**Comment by cpyrgas** [comment]
The exception has been fixed, but the sample gives different results when run in VO and in VFP dialect, is this as intended?

See code below, in VFP dialect the results are:
<empty>
<empty>
FALSE
1
1

and in VO dialect
customerid
<empty>
FALSE
0
0

```
FUNCTION Start() AS VOID

DbUseArea(TRUE,"DBFVFP","C:\xSharp\_Robert\data\orders.dbf")

? DbOrderInfo( DBOI_EXPRESSION )	// empty in VFP, "customerid" in VO dialect
? DbOrderInfo( DBOI_CONDITION ) 	// empty in both
? DbOrderInfo( DBOI_ISDESC ) 		// false in both
? DbOrderInfo( DBOI_RECNO )  		// 1 in VFP, 0 in VO dialect
? DbOrderInfo( DBOI_POSITION ) 		// 1 in VFP, 0 in VO dialect

DbCloseArea()

```

**Comment by RobertvanderHulst** [comment]
This is fixed now

**Comment by RobertvanderHulst** [comment]
The difference between FoxPro and VO is explained by the fact that FoxPro does NOT automatically activates the first tag in the index and VO does.

**Comment by cpyrgas** [comment]
Hmm, I am getting a runtime exception (Unable to cast object of type 'System.String' to type 'System.Byte[]'.) when trying to open the dbf. Robert, you included a zip file above, which contains northwind.dbc and northwind.dct, are those indeed the files that I need to include as well, or did I not understand you correctly?

**Comment by cpyrgas** [comment]
To be precise, this is the error I'm getting when I try a DbUseArea(TRUE,"DBFVFP","C:\...\orders.dbf")


```
---------------------------
ERROR
---------------------------
Description :	Unable to cast object of type 'System.String' to type 'System.Byte[]'.
Subsystem :	XSharp.Core
GenCode :	EG_WRONGCLASS Wrong class
FuncSym :	DbUseArea
Severity :	ES_ERROR
Can Default :	False
Can Retry :	False
Can Substitute :	False
Tries :	1
Stack Trace :	
   at XSharp.RDD.DbcOther.Read()
   at XSharp.RDD.DbcObject.<>c__DisplayClass54_0.<LoadChildren>b__0()
   at XSharp.RDD.DbcManager.DoForDatabase[T](Func`1 action)
   at XSharp.RDD.DbcObject.LoadChildren(UInt32 nArea)
   at XSharp.RDD.DbcDatabase.GetData()
   at XSharp.RDD.DbcManager.<>c__DisplayClass14_0.<Open>b__0()
   at XSharp.RDD.DbcManager.DoForDatabase[T](Func`1 action)
   at XSharp.RDD.DbcManager.Open(String cFileName, Boolean lShared, Boolean lReadOnly, Boolean lValidate)
   at XSharp.RDD.Dbc.Open(String cFileName, Boolean lShared, Boolean lReadOnly, Boolean lValidate)
   at XSharp.RDD.DBFVFP._ReadDbcFieldNames()
   at XSharp.RDD.DBFVFP._ReadDbcInfo()
   at XSharp.RDD.DBFVFP.Open(DbOpenInfo info)
   at XSharp.CoreDb.<>c__DisplayClass114_0.<UseArea>b__0()
   at XSharp.RT.Functions.DbUseArea(__Usual[] Xs$Args)
   at fox.Exe.Functions.Start() in C:\VIDE\Projects\Project3\Applications\fox\Prg\fox.prg:line 11


---------------------------
Abort   Retry   Ignore   
---------------------------

```

**Comment by cpyrgas** [comment]
Confirmed fixed
