### ISSUE TITLE
compiler exit code -2146232797

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#632]
i made a typo in the function name and get the error

Compiler has returned exit code -2146232797

Dumping info before call to failfast
Exception info
Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
etc.

```
BEGIN NAMESPACE Foo

CLASS Test 
		
	STATIC METHOD Message.from_Dll() AS STRING
	RETURN "Message from dll"
		
END CLASS

END NAMESPACE
```

doing the same mistake with a pure function, throws the expected error "Parser: mismatched input '.'" 

```
FUNCTION Message.from_Dll() AS STRING 
	RETURN "Message from dll"
```
Karl-Heinz

**Comment by cpyrgas** [comment]
Confirmed, previous compiler versions were reporting

error XS0538: 'Message' in explicit interface declaration is not an interface

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
Confirmed fixed.
