### ISSUE TITLE
Incorrect calculation of the size of the VOSTRUCT

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#635]
In the following example, DARRAYLEN should be 16 (32-bit application, 4 four-byte fields) instead of 8:

```
STATIC DEFINE DARRAYLEN := _SIZEOF(DARRAY_ROW)

STATIC VOSTRUCT DARRAY_ROW
	MEMBER dwSize AS DWORD
	MEMBER pData AS BYTE PTR
	MEMBER pTop AS DARRAY_ROW PTR
	MEMBER pBottom AS DARRAY_ROW PTR

FUNCTION Start() AS VOID STRICT

	? DARRAYLEN
	WAIT

	RETURN
```

As far as I was concerned, the problem is in calculating the size of the **`AS <VOSTRUCT> PTR`** fields.

**Comment by RobertvanderHulst** [comment]
Leonid,
The problem with this code is that the sizes of the BYTE PTR and DARRAY_ROW  PTR depends on how the program is run. for 32 bits apps the size for each pointer is 32 bits, for 64 bits apps the size is 64 bits.

In earlier builds of X# we were not calculating the size at compile time, but then code like your DEFINE could not be determined at compile time but had to be calculated at runtime. That worked, but then someone else reported that they could not use the define with the _sizeof() in the declaration of a VOSTRUCT or UNION.
I will correct this but I will also add code that throws a compiler error when compiling in AnyCpu mode that the size cannot be reliably determined at compile time.

**Comment by leon-ts** [comment]
Robert,
the calculation of the size of the above structure does not work correctly not only with DEFINE, but also directly in the code:

```
? DARRAYLEN
? _SIZEOF(DARRAY_ROW)

LOCAL dwSize AS DWORD
dwSize := _SIZEOF(DARRAY_ROW)
? dwSize

WAIT
```
This code displays the following result:

> 8
> 8
> 8
> Press any key to continue...
>

**Comment by RobertvanderHulst** [comment]
Leonid,
I know. The same code is calculating the value of _SIZEOF() everywhere.

**Comment by RobertvanderHulst** [comment]
I have made the following change to the compiler for the _sizeof() operator.
for platform x86 it calculates the size at compile time and assumes the size of ptr types = 4
for platform x64 it calculates the size at compile time and assumes the size of ptr types = 8
for platform anycpu it does not calculate the size at compile time but at runtime

for the special [VoStruct(..)] attribute the compiler now has the following logic
for platform x86 it assumes size of ptr = 4  . So the attribute for the structure in the example becomes [VoStruct(16, 4)]
for all other platforms it assumes size of ptr = 8. The attribute becomes [VoStruct(28, 8)]

**Comment by cpyrgas** [comment]
Confirmed fixed.
