### ISSUE TITLE
Error compiling typed array of strings (DIM)

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#638]
The following code, using DEFINE to determine the size of an array, generates a compiler error:

```
STATIC DEFINE ARRAYLEN := 5 AS INT

FUNCTION Start() AS VOID STRICT
	LOCAL DIM cItems[ARRAYLEN] AS STRING
	RETURN

```

> Error XS9999 An internal compiler error has occurred: 'Input string was not in a correct format.',    at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)

**Comment by leon-ts** [comment]
I will add that the main problem here is not even the support for compiling the code **`DIM [...] AS STRING`**, which can be replaced with another code, but the fact that the compiler does not point to the line with the error. When you double-click on an error, the editor opens the PRG on the first line and it is not clear which line of code is causing the error. As a result, the programmer has to search for the error by sequentially deleting the code. If the PRG is large, then this leads to serious difficulty.

**Comment by cpyrgas** [comment]
Confirmed fixed.
