### ISSUE TITLE
ADel() behaviour - Foxpro

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#640]
1. The current header of the ADel() function looks like:

`FUNCTION ADel(ArrayName AS __FoxArray, nElementNumber AS DWORD, nDeleteType := 2 AS LONG) AS DWORD`

https://github.com/X-Sharp/XSharpPublic/blob/feature/Runtime/Runtime/XSharp.VFP/ArrayFunctions.prg#L64

but 'nDeleteType' should default to 1 instead of 2.

`FUNCTION ADel(ArrayName AS __FoxArray, nElementNumber AS DWORD, nDeleteType := 1 AS DWORD ) AS DWORD`

Now ADel ( a , 1 ) removes the row of a two dim array . Otherwise ADel ( a, 1 , 1 ) must be used to achieve this.

2. Another problem is that i can´t remove a row in one dim array. Trying this ends up in the exception

```
/*	
Unbehandelte Ausnahme: XSharp.Error: The FoxPro ARRAY type does not support the Add functionality becaus
e it cannot dynamically grow. You will have TO use the DIMENSION statement TO change its size ---> Syste
m.NotSupportedException: The FoxPro ARRAY type does not support the Add functionality because it cannot
dynamically grow. You will have TO use the DIMENSION statement TO change its size	
*/

	DIMENSION aOneDim ( 8 ) 
	
	STORE .t. TO aOneDim


	XSharp.VFP.Functions.ADel( aOneDim , 1 )  //exception
	   
	((__FoxArray)aOneDim):Delete((LONG) 1) // exception

```

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl,
The Foxpro docs say this about the first argument of ADel():

Specifies the number of the element, row, or column to delete from the array. 
If the array is multidimensional, nElementNumber will specify the row. 
You must include the optional 2 argument to delete a column from the array.

And the code is this:
 ```
IF ! ArrayName:MultiDimensional
        ArrayName:Delete((LONG) nElementNumber)
    ELSE
        IF nDeleteType == 2
            ArrayName:DeleteColumn( (LONG) nElementNumber)
        ELSE
            ArrayName:DeleteRow((LONG) nElementNumber)
        ENDIF
    ENDIF
```
So I think the code is correct, or the FoxPro docs are incorrect...

**Comment by Karl1155** [comment]
Robert,

sorry, but i don´t understand what you mean. I mentioned two points, which point are you referring to ? 

- The function header and the current 'nDeleteType := 2' default setting ? 
- or to the second point where i describe that i see a exception when i try to remove a row in a `*one*` dim array ?

Both points are completely different things. Point one is about `*two*` dim arrays, and point two is about `*one*` dim arrays. 

This code tries to remove the first row in a `*one*` dim array. 

`XSharp.VFP.Functions.ADel( aOneDim , 1 ) `

and because aOneDim is `not `a `"two"` dim array, the line 

`ArrayName:Delete((LONG) nElementNumber) `

is triggered.


```
IF ! ArrayName:MultiDimensional
       ArrayName:Delete((LONG) nElementNumber)  // <----- causes a exception
   ELSE
       IF nDeleteType == 2
           ArrayName:DeleteColumn( (LONG) nElementNumber)
       ELSE
           ArrayName:DeleteRow((LONG) nElementNumber)
       ENDIF
   ENDIF
```

That´s the same as the "short cut" 

((__FoxArray)aOneDim):Delete((LONG) 1)   // <--- causes a exception


Do you really get no exception when you try this code ?

```
DIMENSION aOneDim ( 8 ) 
	
//	STORE .t. TO aOneDim


	XSharp.VFP.Functions.ADel( aOneDim , 1 )  //exception
	   
	((__FoxArray)aOneDim):Delete((LONG) 1) // exception


```
Karl-Heinz

**Comment by cpyrgas** [comment]
Not sure if this was closed on purpose, but indeed I still do get the exception with the sample code.

**Comment by cpyrgas** [comment]
Confirmed fixed
