### ISSUE TITLE
DIMENSION command - Foxpro

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#642]
it seems it's not possible to create a two dim array if the number of columns is 1

These are the Foxpro results.

```
dimension arr1(1,1), arr2(3,1), arr3(1,3)

ARR1        Priv   A                                         
  (   1,   1)     L  .F.
Alen(arr1,0) = 1    Alen(arr1,1) = 1    Alen(arr1,2) = 1

ARR2        Priv   A                                         
  (   1,   1)     L  .F.
  (   2,   1)     L  .F.
  (   3,   1)     L  .F.
Alen(arr2,0) = 3    Alen(arr2,1) = 3    Alen(arr2,2) = 1

ARR3        Priv   A                                         
  (   1,   1)     L  .F.
  (   1,   2)     L  .F.
  (   1,   3)     L  .F.
Alen(arr3,0) = 3    Alen(arr3,1) = 1    Alen(arr3,2) = 3

```
And the X# code 

```
DIMENSION arr1(1,1), arr2(3,1), arr3(1,3)
?
ShowFoxArray (arr1)
? "Alen(arr1,0) = " + AllTrim(Str(ALen(arr1,0)))  + "   ", "Alen(arr1,1) = " + AllTrim(Str(ALen(arr1,1)))  + "   ", "Alen(arr1,2) = " + AllTrim(Str( ALen(arr1,2)))
?
ShowFoxArray (arr2)
? "Alen(arr2,0) = " + AllTrim(Str(ALen(arr2,0)))  + "   ", "Alen(arr2,1) = " + AllTrim(Str(ALen(arr2,1)))  + "   ", "Alen(arr2,2) = " + AllTrim(Str( ALen(arr2,2)))
?
ShowFoxArray (arr3)                      
? "Alen(arr3,0) = " + AllTrim(Str(ALen(arr3,0))) + "   " , "Alen(arr3,1) = " + AllTrim(Str(ALen(arr3,1))) + "   " , "Alen(arr3,2) = " + AllTrim(Str( ALen(arr3,2))) 
?
```
results in 

```
a[1] = .F. (Nil)
Alen(arr1,0) = 1    Alen(arr1,1) = 1    Alen(arr1,2) = 0

a[1] = .F. (Nil)
a[2] = .F. (Nil)
a[3] = .F. (Nil)
Alen(arr2,0) = 3    Alen(arr2,1) = 3    Alen(arr2,2) = 0

a[1] [1,1] = .F. (Nil)
a[2] [1,2] = .F. (Nil)
a[3] [1,3] = .F. (Nil)
Alen(arr3,0) = 3    Alen(arr3,1) = 1    Alen(arr3,2) = 3

```
Because i want a different Fox-Array view than the ShowArray() function offers, i created the ShowFoxArray() function. And since its now possible, i also took the chance and added a LOCAL FUNCTION to the ShowFoxArray () :-)

```
FUNCTION ShowFoxArray ( aTest AS __FoxArray , cPrefix := "" AS STRING ) AS VOID
LOCAL i, j, dwCounter AS DWORD 
    
// todo: If AElement() works as expected, remove the dwCounter var
	
	IF cPrefix:Length == 0
		cPrefix := "a"
	ENDIF 
	
	
	IF aTest:MultiDimensional
		
		dwCounter := 0 

		FOR i := 1 TO ALen ( aTest , 1 ) 
			
			FOR j := 1 TO ALen ( aTest , 2 ) 
				
				dwCounter ++
				
				? cPrefix + "[" + dwCounter:ToString() + "] [" + i:ToString() + "," + j:ToString() + "] = " + AsString ( aTest [i,j] ) + ;
					 " " + GetElementValueType ( aTest[i,j] )   
				
				// todo: If AElement() works as expected, remove the code above and use the code below instead: 	 
				//
				// ? cPrefix + "[" + AElement ( aTest , i , j ):ToString() + "] [" + i:ToString() + "," + j:ToString() + "] = " + AsString ( aTest [i,j] ) + ;
				//	 " " + GetElementValueType ( aTest[i,j] ) 
							 
			NEXT	
		    
		NEXT 			
		
	ELSE
		
		FOR i := 1 TO ALen ( aTest , 0 ) 
			
			? cPrefix + "[" + i:ToString() + "] = " + AsString ( aTest [i] ) + " " + ;
				GetElementValueType ( aTest[i] ) 
			
		NEXT	
		
	ENDIF 
	
	LOCAL FUNCTION GetElementValueType( uValue AS USUAL ) AS STRING
	
	IF IsNil ( uValue ) 
		RETURN "(Nil)"
	ELSE
		RETURN "(" + ValType ( uValue ) + ")" 
	ENDIF 
			 
END FUNCTION		
				
RETURN 
	
END FUNCTION 

```

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
What's the use of a 2 dimensional array with 1 column?

**Comment by Karl1155** [comment]
Robert,

I don t know. I have found such dim arrays in published Fox code. Maybe the VFP community should be asked ?

btw I. with Foxpro arrays you can do strange things. There's nothing wrong with this code  

```
dime a[4]

a[1] = 1
a[2] = 2 
a[3] = 3
a[4] = 4

for i = 1 to Alen ( a )

    ? a [ i ]

next
```


but at least with my old Foxpro this is also possible  ... 


```
for i = 1 to Alen ( a )

    ? a [ 1 , i ]

next

```

Maybe - for compatibility reasons ;-) - this still works with VFP ?


btw II. I found an interesting link about VFP arrays. But because it is about VFP7, some things are probably done a bit different with VFP9.

http://www.tomorrowssolutionsllc.com/ConferenceSessions/You%20Need%20Arrays.pdf 

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
FoxPro is really weird here:  ? a [ 2 , i ],  ? a [ 3 , i ] etc all work. For a single dimensional array the row index is simply ignored.

**Comment by Karl1155** [comment]
It´s getting even better  - i hope the copy and paste works :-)

```
? a [ 1	, "a" ,	.f.	, 123		, left("123" ,1)]
? a [ 2	, -34 ,	234 * 2	, Val("123")	]
? a [ 3	, 2^2 ,	2	, -34		]
? a [ 4	, .f. ,	-2	]
```
Now, to prove that something is going on under the hood, change Val("123") to Val(123), and you should see a runtime error.

:-)

**Comment by RobertvanderHulst** [comment]
The Val() function is documented as:
Convert a string containing a numeric value to a numeric data type. 
And Val(123) produces the following error in VFP 9:
![image](https://user-images.githubusercontent.com/14240939/119708982-fc0e5b00-be5c-11eb-87b6-8d55ae6a6c3d.png)
So there is no problem.

**Comment by Karl1155** [comment]
Yes, i see the same runtime error when i change Val("123") to Val (123) - but that´s not the point  ;-) , 

Using the unchanged code :  Do you see the same output as i see ?

1
2
3
4

**Comment by RobertvanderHulst** [comment]
So FoxPro allows to pass garbage as array index. I hope you don't mind that I do not plan to reproduce this nonsense in X#. 
If someone has code like this, then this is most likely an error.

**Comment by Karl1155** [comment]
i don´t expect that i can do the same nonsense with X#  ;-)

**Comment by cpyrgas** [comment]
This is partially fixed, but there's still an incompatibility with ALen(). Based on the original sample, the code below produces in X#

1 1 0
3 3 0
3 1 3

while VFP produces

1 1 1
3 3 1
3 1 3

if this makes sense is another matter :)


```
FUNCTION Start() AS VOID STRICT
DIMENSION arr(1,1)
? ALen(arr,0), ALen(arr,1), ALen(arr,2) // 1 1 0, should be 1 1 1

DIMENSION arr(3,1)
? ALen(arr,0), ALen(arr,1), ALen(arr,2) // 3 3 0, should be 3 3 1

DIMENSION arr(1,3)
? ALen(arr,0), ALen(arr,1), ALen(arr,2) // 3 1 3 correct

END FUNCTION

```

**Comment by RobertvanderHulst** [comment]
Have you been able to figure out the algorithm behind this ?

**Comment by cpyrgas** [comment]
If I have understood it correctly, given:

DIMENSION arr (a , b)

then:

ALen(arr , 0) == a * b
ALen(arr , 1) == a
ALen(arr , 2) == b

**Comment by cpyrgas** [comment]
Looks like that's correct. Based on https://hackfox.github.io/section4/s4g214.html :

nReturnValue = ALEN( ArrayName [, nElemRowOrCol ] )

ArrayName: The array whose elements, rows or columns are to be counted. Can be either one- or two-dimensional.

nElemRowOrCol:
- 0 or Omitted: Returns the number of elements in the array
- 1: Returns the number of rows in a two-dimensional array. For a one-dimensional array, returns the number of elements.
- 2: Returns the number of columns in a two-dimensional array. Returns 0 for a one-dimensional array.

**Comment by cpyrgas** [comment]
Oh, I think I see where the confusion lays. In VFP terms, it looks like for DIMENSION arr(100,1) the arr is considered to be multidimensional, while DIMENSION arr(100) is considered single dimension. In the X# rutnime, the MultiDimensional property returns FALSE also in the case when columns == 1

**Comment by RobertvanderHulst** [comment]
I can change the behavior and keep track of a separate logic variable to remember the "multidimensional" state of the array. That should not be too difficult I think.
I do have to change the prototype for the __FoxRedim() function, the __FoxArray:Redim() method to use a different value (0) for the second parameter. Otherwise I cannot see the difference between a value of 1 that was passed in by code and a default value of 1 that was added by the compiler.

**Comment by cpyrgas** [comment]
Would it make sense to use columns == 0 for single dim?

**Comment by RobertvanderHulst** [comment]
Yes, that would make sense. We don't need a second field then. I'll try to do that.

**Comment by cpyrgas** [comment]
Confirmed fixed.
