### ISSUE TITLE
Source code editor does not show parameter tips for constructor calls

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#645]
Source code editor does not show parameter tips for constructor calls

**Comment by RobertvanderHulst** [comment]
Fixed in a17b27d25b186f31ea0a18d047cb992a3c127d86

**Comment by cpyrgas** [comment]
This does not seem to work. In the following sample, the first case shows no parameter tip at all, while the second one does show it, but it includes a return value which is wrong of course, see screenshot:

![VS_constructor_parameter_tips](https://user-images.githubusercontent.com/14542129/117991389-a9a24a00-b346-11eb-904f-23ce935316e1.png)


```
FUNCTION Start() AS VOID
LOCAL o AS MyClass
o := MyClass{  // no parameter list at all here
MyClass{  .. this shows tip: {n AS INT} AS USUAL

WAIT

CLASS MyClass
CONSTRUCTOR (n AS INT)
END CLASS 
```

**Comment by cpyrgas** [comment]
...and it's working correctly now!
