### ISSUE TITLE
Code editor doesn't show parameter types

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#647]
If you hover the mouse over a method or function in the linked libraries (non-solution DLLs, system libraries), the parameter types are not displayed in the tooltip (see screenshot):

![изображение](https://user-images.githubusercontent.com/64518775/117997899-13712280-b34c-11eb-9248-8129ba9ab453.png)

Also, all tooltips display some kind of non-printable line before the **Location** line.

**Comment by RobertvanderHulst** [comment]
I was just working on this :)
The extra character is a extra CRLF to create a blank line.
For now I'll remove the blank line before Location.

**Comment by cpyrgas** [comment]
Confirmed fixed.
