### ISSUE TITLE
 VS ActivityLog error

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#65]
Customer says this activity log happens from time to time. Maybe you can see something from the callstack.

[ActivityLog.zip](https://github.com/X-Sharp/XSharpPublic/files/3297346/ActivityLog.zip)

**Comment by RobertvanderHulst** [comment]
This callstack does not have any XSharp code in it, but a reference to Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
This does not really help...
