### ISSUE TITLE
Wrong type hints for locals

### ISSUE THREAD

**Issue by LeonidLevenshtein** [X-Sharp/XSharpPublic#651]
If there are several local variables declared through comma with type written at the end of the line, then type hint for all of them but the rest shows they are of type USUAL instead of the written one:

```
LOCAL d1, d2, d3 AS DATE
```

If you hover mouse over d1 or d2 it shows USUAL, over d3 - DATE.

**Comment by cpyrgas** [comment]
I also see the problem. Actually it seems that only the first a last variables invoke member completion:

LOCAL n1, n2, n3,n4 AS INT
n1: // member completion for type USUAL, wrong
n2: // nothing
n3: //nothing
n4: // correct member completion on INT
