### ISSUE TITLE
Macro compiler does not handle parameters by reference correctly.

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#653]
Assume the following macro and function
`        TestMacro(mc, e"{|a,b| S_EnforceType(@a,b), a}", Args(NIL,"N"), 0, typeof(INT))

(See the code below for the S_EnforceType function)

This does not compile. It gives an error

```
XSharp.MacroCompiler.CompilationError
  HResult=0x80131500
  Message=Macrocompiler (1,22): error XM0218: Operator '' on type 'object' could not be resolved
  Source=XSharp.MacroCompiler
  StackTrace:
   at XSharp.MacroCompiler.Binder.BindUnaryOperation(UnaryExpr expr, UnaryOperatorKind kind, BindOptions options) in C:\XSharp\DevRt\Runtime\MacroCompiler\Binder\Binder.UnaryOp.cs:line 37
```
If you omit the @ sign then the macro compiles but does not work. correctly.

Replacing the @ with REF also does not work:

```
XSharp.MacroCompiler.CompilationError
  HResult=0x80131500
  Message=Macrocompiler (1,22): error XM0101: Unexpected 'REF'
  Source=XSharp.MacroCompiler
  StackTrace:
   at XSharp.MacroCompiler.Parser.RequireEnd[T](T n, ErrorCode error, Object[] args) in C:\XSharp\DevRt\Runtime\MacroCompiler\Syntax\Parser.cs:line 169

```

I have also tried it with a function with CLIPPER calling convention and that does not make a difference.

```
FUNCTION S_EnforceType(uVar REF USUAL,cTyp AS STRING) AS VOID
    IF ValType(uVar) <> cTyp
        SWITCH cTyp
            CASE "C"
                uVar := ""
            CASE "N"
                uVar := 0
            CASE "D"
                uVar := NULL_DATE
            CASE "L"
                uVar := FALSE
            CASE "A"
                uVar := {}
            CASE "O"
                uVar := NULL_OBJECT
            CASE "#"
                uVar := NULL_SYMBOL
            CASE "U"
                uVar := NIL
        END SWITCH
    ENDIF
    RETURN


```

**Comment by RobertvanderHulst** [comment]
Please note that OUT parameters also do not seem to be implemented.

**Comment by ecosSystem** [comment]
In addition I found another incompatibility to VO:
ARTIKLDB->VERF_BEST<1.or.ARTIKLDB->VERF_BEST<FILBEST->OFFEN
gives an error because of the missing spaces before and after ".or. "
We store such conditions outside the code (in tables) so the user can adapt certain things. Existing expressions can therfore not be adapted by us and will give a runtime-error...

**Comment by RobertvanderHulst** [comment]
Karl,
I will see what I can do. The problem here is that the DOT (.) can also be part of a namespace or typename.
But maybe we can preprocess the macro and detect ".or.", ".and." and ".not." and surround these with spaces when needed.

**Comment by ecosSystem** [comment]
strangely enough in ReportPro a "print when" expression like
Reportdb.Lfd_Nr="1".or.Reportdb.Lfd_Nr="2"
works fine without the spaces.  These expressions are evaluated with <CODEBLOCK>:eval()
If you preprocess the macro, you might also have to check for .t. and .f.

**Comment by RobertvanderHulst** [comment]
Karl,
ReportPro is a "dirty beast". Since it also uses the DOT between alias and fieldname, it does its own expression parsing before passing the expression to the macro compiler.
Something like 
`Reportdb.Lfd_Nr="1".or.Reportdb.Lfd_Nr="2"`
will become
`RpFieldGet(1,2)="1".or.RpFieldGet(1,2)="2"`

and on top of that: after the quote character the Dot cannot be a namespace delimiter. 
And after the 1 it can be a namespace delimiter for code such as `Class1.DoSomething()`

**Comment by nvkokkalis** [comment]
REF arguments are partially supported with commit cd77bcd3. They are correctly handled only if the type exactly matches the parameter type (in this case the USUAL macro compilation method needs to be used, so that the macro variables are USUAL).

**Comment by nvkokkalis** [comment]
With commit d9565ad1 some non-type-exact variables can also be passed to REF parameters, and the result is assigned back to the variable if possible. This allows the code sample to work even with the object macro compiler.

The REF keyword is still not supported.

**Comment by ecosSystem** [comment]
in x# 2.8.3.15 I still get the error
Exception ausgelöst durch CLR oder externen Code:Macrocompiler (1,9): error XM0218: Operator '' on type 'usual' could not be resolved
when executing the following code:

function MakroTest() as void
LOCAL x AS STRING
LOCAL bBlock	AS _Codeblock

x := "a"
bBlock := &( "{||test(@x)}" )

return

FUNCTION test(y REF STRING) AS VOID
y := "b"
RETURN

What am I doing wrong ? The Whatsnew said:
Macro compiler
•	**Added support for passing variables by references (not yet for functions with Clipper calling convention) (#653)**

**Comment by RobertvanderHulst** [comment]
Karl,
In this case you are referring to the variable x inside the macro that is defined as a local in the surrounding code and you are not passing that variable to the codeblock as parameter.
So the variable x is (because of the normal visibility rules) not visible to the codeblock.
What are you trying to achieve ?

**Comment by ecosSystem** [comment]
I'm testing our scripting-Tool again. In our scripts we have to pass parameters by reference (to functions and methods). In my example above I had a typo, x is a private in this case and therefore it should (might) be visible.
If you remember, we compile script-lines to codeblocks and execute these codeblocks later on (original source-code was VO-Script). All variables in this scripting-environment are privates. It is really essential for us that these scripts are working like in VO, as we have thousands of them running at our customers...

**Comment by cpyrgas** [comment]
Additional note, the syntax with REF does (macro) compile and run with no errors, but the private does not get updated:


```
FUNCTION Start() AS VOID
LOCAL bBlock AS CODEBLOCK
PRIVATE x

x := "a"
? x // a
bBlock := &( "{||test(ref x)}" )
Eval(bBlock)
? x // a again, should be b

FUNCTION test(y REF STRING) AS VOID
? y // a
y := "b"

```

**Comment by nvkokkalis** [comment]
This should be working after commit 00760973.

Sorry, the '@' syntax does not work correctly for by-ref parameters (there are complications in supporting it - needs further consideration). The REF syntax should work. It should also work without it (e.g. "{||test(x)}"), although the REF syntax is recommended.
