### ISSUE TITLE
XML documentation file is not generated

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#654]
Enabling the "Generate XML doc comments file" option in the project configuration has no effect. The research has shown that the "<DocFile ... />" entry is generated in the xsproj file, instead of the "<DocumentationFile ... />" entry. If you manually change the xsproj file by replacing DocFile with DocumentationFile, then the output XML file is generated.

**Comment by RobertvanderHulst** [comment]
Confirmed.

**Comment by cpyrgas** [comment]
It's working fine now. Cannot edit the xml filename though, looks like the editbox is read only. Is that as intended?

**Comment by RobertvanderHulst** [comment]
Yes, that is intended. The name of the XML is the same as the name of the EXE or DLL
