### ISSUE TITLE
Incorrect display of Cyrillic characters (reproducable)

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#655]
There is a problem with displaying Cyrillic characters (Ukraine, Russian, Belarusian) from XML documentation in hints in the code.

I already addressed this problem in ticket 504. But at that time I could not provide a reproducible example. The problem appeared and disappeared, for reasons I did not understand. Now the problem was reproduced. I attach the small archives of the test project for VS2019 and a step-by-step video on how to reproduce the problem.

**VS2019 Project:** 
[CyrillicCharsVS2019Project.zip](https://github.com/X-Sharp/XSharpPublic/files/6494870/CyrillicCharsVS2019Project.zip)

**How to reproduce the problem (mp4):** 
[CyrillicCharsReproduceVideo.zip](https://github.com/X-Sharp/XSharpPublic/files/6494875/CyrillicCharsReproduceVideo.zip)

**Comment by RobertvanderHulst** [comment]
Leonid,
The source file in your project is saved in Ansi. On my machine it looks like this:
![image](https://user-images.githubusercontent.com/14240939/118517107-38dca280-b737-11eb-812f-ddf199008202.png)

Does it make a difference is you save your source as UTF8  (File Save-As, choose dropdown button for Save and choose 'Save as Encoding'
And what is your windows codepage ?

**Comment by leon-ts** [comment]
Robert,

I am using Ukrainian version of Windows.
Codepage: Cyrillic (Windows) 1251.

When saving a PRG file in UTF8 encoding, the problem is not reproducible.

**Comment by RobertvanderHulst** [comment]
Leonid,
Thanks. I will try to setup a VM with windows codepage 1251 and will see if I can reproduce it there.

**Comment by leon-ts** [comment]
The problem does not arise if the PRG is stored in unicode. So it will be more correct and I will follow this.
