### ISSUE TITLE
Member completion problems with enums

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#656]
** small problem, no need to fix this right now **

There are problems with member completion with enums:

```
USING System

ENUM LocalEnum
    MEMBER Foo
    MEMBER Bar
END ENUM

FUNCTION Start() AS VOID STRICT
    LOCAL e1 AS LocalEnum
    LOCAL e2 AS System.ConsoleKey
    e1:
    e2:
```       

1. With a local enum:

![IntellisenseEnums1](https://user-images.githubusercontent.com/14542129/118514143-fddd6d80-b73c-11eb-8c65-a8f6de390bcb.png)

"Finalize", "Member1" and "Member2" should not appear in the list. Also missing from the list are items from the System.Enum class like "HasFlag()" and "CompareTo".

2. With an enum in a dll:

![IntellisenseEnums2](https://user-images.githubusercontent.com/14542129/118514670-5f054100-b73d-11eb-8c58-0d72a0f4f7c9.png)

"value__" is incorrectly shown, instead of the correct members from (1)

**Comment by cpyrgas** [comment]
The local enum works fine now, but member completion on the system enum includes several members like ToDateTime(), ToDecimal() etc which are not part of it. Of course it is not a big issue!

![VS_system_enum](https://user-images.githubusercontent.com/14542129/120883091-eaa71a80-c5e3-11eb-8def-0bf0f681e1c4.png)

**Comment by RobertvanderHulst** [comment]
The methods ToByte(), ToChar() etc are part of the IConvertible interface which is supported by System.Enum as you can see here:
https://docs.microsoft.com/en-us/dotnet/api/system.enum?view=net-5.0&viewFallbackFrom=net-4.6
That is why they are added to the completionlist.
I checked and C# does not do this. I'll change the completion code to not do this as well.

**Comment by cpyrgas** [comment]
Hmmm, that's interesting, I see the interface indeed, but when I try to use e:ToDouble(), then the compiler says that this method does not exist. Maybe it's because this interface is explicitly implemented. I tried a few more tests, and it seems I have a brain stall moment...given an explicitly implemented interface method, how can I address it? I tried:

```

CLASS Foo IMPLEMENTS IDisposable
	METHOD IDisposable.Dispose( ) AS VOID
END CLASS

FUNCTION Start() AS VOID
LOCAL o AS Foo
o := Foo{}
o:Dispose()
o:IDisposable.Dispose()
```

for both lines above, the compiler complains that Dispose() and IDispose() do not exist.

**Comment by cpyrgas** [comment]
Similarly, delete everything and type

```
FUNCTION Start() AS VOID
System.Console.
```

For the first dot, the auotype list opens and shows members of System. But when you type the next dot, there's no member completion list shown.

**Comment by RobertvanderHulst** [comment]
If you declare the method with the IDisposable. prefix you will have to use a cast to the interface to call it:

`((IDisposable) o):Dispose()`

or do something like this
```
IF o IS IDisposable VAR iDisp
   iDisp:Dispose()
ENDIF
```

**Comment by cpyrgas** [comment]
Ah, thanks, apparently I had never used this in X# yet! IIRC, in vulcan it was possible to use the o:IDisposable.Dispose() syntax.
Anyway, so it makes sense that it should not be visible in the member completion. I guess the rule is that every member that is an explicit interface implementation, should not appear in the list. Obviously not a big issue in any case.

**Comment by cpyrgas** [comment]
Confirmed fixed. OK, actually there's still a small issue, the member list for local enums includes a couple members that it shouldn't, ("Finalize" and "MemberwiseClone", which are not public), but this is really minor.
