### ISSUE TITLE
Wrong methods list in "a := b:" expression

### ISSUE THREAD

**Issue by LeonidLevenshtein** [X-Sharp/XSharpPublic#658]
![image](https://user-images.githubusercontent.com/36951726/118617126-0086a400-b7cb-11eb-8c7c-25327ab6d672.png)

If there is an assignment operator (:=) then after typing ":" on some class on the right side of expression I see methods from the class which is on the left side of expression.
And the whole "a := b:" line when hovering over it shows a single hint "Local a of ClassA" instead of two different classes on the left and on the right side of expression.

**Comment by LeonidLevenshtein** [comment]
Attaching prg file with the same contents as on the screenshot above:

[test.zip](https://github.com/X-Sharp/XSharpPublic/files/6499609/test.zip)

**Comment by RobertvanderHulst** [comment]
Fixed in  f8a44a7fb7354faf6973d50c2fc4b986f349176e

**Comment by cpyrgas** [comment]
The first problem with member completion is completely fixed!

But the problem with the tooltip remains. It can be reproduced also like this:

```
FUNCTION Test()
LOCAL n1 , n2 AS INT
    n1 := n2
```

Hover over "n1", nothing happens. Hover over "n2", now a tooltip is shown, but it mentions n2, not n1:

![VS_tooltip](https://user-images.githubusercontent.com/14542129/123804798-318fe380-d8f6-11eb-8700-9be7f1fd307b.png)

This actually happens in both the LOCAL definition and in the assignment line. Also sometimes (like 1 out of 10), it works correctly, tooltip over n1 and n2 show the correct texts, but most of the time it has the behavior described above.

**Comment by cpyrgas** [comment]
Confirmed fixed.
