### ISSUE TITLE
XS0112 Error for Extension Method in X# 2.8a

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#660]
After switching to version 2.8a, i'll get the XS0112 error for the following extension method 

```
static class XXX
     public method AppendUsual(self sb as StringBuilder, value as usual) as void pascal 
         if (sb != null .and. value != nil) 
             sb:Append((string)value) 
      endif 
 end class 
```

Error: XS0112 - A static member 'XsCsInteropTests.XXX.AppendUsual(System.Text.StringBuilder, XSharp.__Usual)' cannot be marked as override, virtual, or abstract

The problem is related to this setting. Once I uncheck it, the error goes away.

![image](https://user-images.githubusercontent.com/9860916/118661152-2887fe80-b7ef-11eb-80fe-b4674972378d.png)

**Comment by cpyrgas** [comment]
Volkmar, you can also leave the "all virtual" setting enabled and mark the extension method as STATIC, this will also work.

**Comment by VolkmarR** [comment]
Ooops. I overlooked that. This was completely my fault.

**Comment by cpyrgas** [comment]
Still it needs to be fixed, the compiler should not silently generate incorrect code :)
Thanks for reporting!

**Comment by cpyrgas** [comment]
Summary of the compiler bug:

- When /vo3 is enabled, the following reports an error:
error XS0112: A static member 'Extensions.NonStatic(string)' cannot be marked as override, virtual, or abstract

- When /vo3 is disabled, the code compiles with no errors, but when running an exception is thrown:
System.TypeLoadException: Virtual Static Method.

So STATIC should either be always implicitly added by the compiler, or be always required and report an error if it isn't included. Also having /vo3 enabled or disabled should not make a difference.

```
FUNCTION Start() AS VOID
	LOCAL c := "abc" AS STRING
	? c:NonStatic()
RETURN


CLASS Extensions
	METHOD NonStatic(SELF c AS STRING) AS INT
	RETURN c:Length
END CLASS
```

**Comment by RobertvanderHulst** [comment]
So what do you want:
- require STATIC?
- implicitly add static when there is a SELF parameter?

**Comment by cpyrgas** [comment]
I'd say require STATIC, so it is also clear what is really happening with extension methods. 

Btw, I checked c# and it also requires it, but c# has the bug that Dick pointed out a few days ago, if it reports an error for missing static in an extension method, it points to the class line, not the method line in the source. Let's make X# report the error correctly to the line of the method declaration and I will point Dick here to read about it :)

**Comment by VolkmarR** [comment]
I also would say that the compiler should give the error  "Extension methods must be static" (1105).

**Comment by RobertvanderHulst** [comment]
Chris, Volkmar, 
I hope you both realize that this will almost certainly also annoy people. Just like the warning that we introduced about ambigous code (methods and functions with the same name)
But I agree and we need to do this.

**Comment by cpyrgas** [comment]
Robert, I do not think there are a lot of people who have defined extension methods in their code. And those that have done this, I cannot imagine they have created too many of them!

**Comment by cpyrgas** [comment]
Confirmed fixed
