### ISSUE TITLE
Error in WinForms designer X#2.8 and X#2.8a

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#661]
After upgrading to X# 2.8, the WinForms designer shows the following Error for every Form

![image](https://user-images.githubusercontent.com/9860916/118662091-05aa1a00-b7f0-11eb-99cc-fffe3071f0cb.png)

**Steps to reproduce the behavior**
1. Create a new Windows Forms Application (X#) Project
2. Open the Designer for the Form1.prg file

**Versions**
X# 2.8 and X#2.8a 
Vistual Studio Version 16.9.5

**Comment by RobertvanderHulst** [comment]
I am sorry but I cannot reproduce it here. I tested it with VS 2017, VS 2019 16.9.5 and VS 2019 Preview (16.10.0 Preview 3).
Could this be related to a VS extension that you have installed ?

**Comment by cpyrgas** [comment]
Volkmar, can you also please zip and upload here this test solution you show above? Just in case there is something generated in the project file that causes the problem and is reproducible also in our machines.

**Comment by VolkmarR** [comment]
This is the Solution...
[WindowsFormsApplication1.zip](https://github.com/X-Sharp/XSharpPublic/files/6502380/WindowsFormsApplication1.zip)

**Comment by cpyrgas** [comment]
Thanks, but unfortunately it works fine here. Did you try completely restarting your PC? I have seen such issues with VS getting fixed with a restart... Worth a try also uninstalling/resinstalling X#, just in case something went wrong before.

If not of that helps, then I guess it's what Robert said, something else in VS maybe causing this. Do you have anything "exotic" installed?

**Comment by VolkmarR** [comment]
This issue is very strange. The problem happens only on one Pc. It works fine on my Pc. My colleague tried to disable all the extensions but no change. When downgrades he to x#2.7, the designer works correctly. When he reinstall's x#2.8a the error re-appears. Can he activate some kind of logging in Visual Studio?

**Comment by RobertvanderHulst** [comment]
Volkmar,
This is what you can do:
add an environment variable to the machine with the name XSHARPDEV. The contents is irrelevant. For example XSHARPDEV=TEST.
Then start VS and goto the Tools/Options/TextEditor/X# page. Select the Intellisense treenode. You should see a pushbutton with the text "Open Sesame".
You will see this page
![image](https://user-images.githubusercontent.com/14240939/118702826-b5de4980-b815-11eb-8d69-e578a8913985.png)
On that page select all the log options and enable the output pane.
Many of the operations done by X# in VS will then be logged to a new pane in the Output Window (View Output Window).
Open the solution and open the form.
After the error occurs select the contents of the output pane and attach it to this ticket so we can see what happened.
Then go back to that window and disable all checkboxes.

**Comment by VolkmarR** [comment]
This is the log.
[xsharp_form_log.txt](https://github.com/X-Sharp/XSharpPublic/files/6506755/xsharp_form_log.txt)

**Comment by RobertvanderHulst** [comment]
Volkmar,
Thanks for the file. It seems that somehow the wrong version of Mono.Cecil gets loaded by VS:

`09:27:08.599 XModel.XAssembly System.TypeLoadException: Could not load type 'Mono.Cecil.GenericParameterConstraint' from assembly 'Mono.Cecil, Version=0.10.0.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'.
`

We are using Mono.Cecil version 0.11.2.0. This file is located in the folder c:\Program Files (x86)\XSharp\Extension\Project
Maybe your colleague can check to see which extension on his machine is loading Mono.Cecil and replace the version of Mono.Cecil for this extension with our version ?

I'll make the necessary changes to our project system to force VS to load our version of Mono.Cecil for the next build.

**Comment by VolkmarR** [comment]
I checked in the Process Explorer. I'll try to uninstall Xamarin to see, if this fixes it.
![image](https://user-images.githubusercontent.com/9860916/118782706-aa7b3480-b88e-11eb-9ed6-acacb8fa1d08.png)

**Comment by VolkmarR** [comment]
I can confirm: Removing Xamarin and all it's connected Packages solved the Problem.

**Comment by RobertvanderHulst** [comment]
Volkmar, Thanks for the confirmation. 
I checked the release notes and there was a breaking change between Mono.Cecil 0.10 and 0.11. That explains why it did not work.

**Comment by RobertvanderHulst** [comment]
I have removed the dependency to Mono.Cecil and included the Mono.Cecil source code in our VS solution. This now gets compiled into XSharpMonoCecil.DLL

**Comment by cpyrgas** [comment]
Will need Volkmar's confirmation on this one, once the update is released.

**Comment by VolkmarR** [comment]
For us, the problem is already solved, because we deinstalled Xamarin for the developer, that are working with x#. But I can reinstall it, to verify if the problem is fixed, if you want.

**Comment by cpyrgas** [comment]
If it's not much of a bother, that would be helpful Volkmar, thanks!

**Comment by RobertvanderHulst** [comment]
VolkmarR ,
Can you confirm that this is fixed ?

**Comment by VolkmarR** [comment]
I now have reinstalled Xamarin and I can confirm, that I was not able to reproduce this problem with the version 2.8b.

**Comment by RobertvanderHulst** [comment]
Great, Thanks !
