### ISSUE TITLE
creating public arrays - Foxpro

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#662]
using the Foxpro dialect i´m trying to create a public Foxpro array. But either a none Foxpro array is created, or a
compiler error is thrown.

Karl-Heinz

/memvar+ /undeclared+
```
FUNCTION Start( ) AS VOID 

	CreatePublicArray()
	
	IF IsArray ( c )
 
		? "i am a public "

		IF c IS __FOXARRAY 
			?? "fox array - "
		ELSE 
			?? "none fox array - "		
		ENDIF		             
		
		?? ClassName ( c )
		
	ENDIF 

	RETURN 

FUNCTION CreatePublicArray() AS VOID 
PUBLIC ARRAY c [2,2] // AS __FOXARRAY 	//  creates always a none fox array
// PUBLIC c [2,2] // AS __FOXARRAY 	//  creates always a none fox array
// PUBLIC DIMENSION c [2,2] 	// 'PUBLIC' causes an [XS9002: Parser: unexpected input 'c'] error 
// PUBLIC DECLARE c [2,2]  	// 'PUBLIC' causes an [XS9002: Parser: unexpected input 'c'] error 

	RETURN 	
```

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
I see that we are not properly supporting the PUBLIC ARRAY syntax. I am sorry about that. I'll add that to the next version of the compiler. We ARE parsing PUBLIC ARRAY MyArrayName, but the dimension suffixes are not support and the parser is not doing anything with the ARRAY keyword.

**Comment by RobertvanderHulst** [comment]
LOCAL ARRAY should be working

**Comment by Karl1155** [comment]
Yes,

something like 

LOCAL ARRAY d [2,2] 

creates a __FOXARRAY

**Comment by cpyrgas** [comment]
Mostly fixed, but seems there are some issues here. The syntax:

FUNCTION CreatePublicArray() AS VOID 
 PUBLIC c [2,2] 
RETURN

results to error XS9002: Parser: unexpected input 'RETURN'. By removing the RETURN command, it does compile without errors.

I will open a separate ticket for some other issues.

**Comment by RobertvanderHulst** [comment]
In the current implementation you need the ARRAY keyword to declare the array:
`PUBLIC ARRAY c[2,2]`
The FoxPro docs say this:
```
PUBLIC MemVarList
PUBLIC [ ARRAY ] ArrayName1( nRows1 [ , nColumns1 ] ) [, ArrayName2( nRows2 [, nColumns2 ] ) ] ... 
   [AS type [OF ClassLib]]
```
The angled brackets around the ARRAY keyword seems to indicate that this is optional.
I can change the compiler rule to allow that too. In that case the presence of the `()` or `[]` should differentiate this rule from the rule with the MemVarList

**Comment by cpyrgas** [comment]
Indeed, FoxPro does support also the PUBLIC arrayname[] syntax as well, I did check it and it works at runtime.

**Comment by cpyrgas** [comment]
Confirmed fixed.
