### ISSUE TITLE
Inconsistency between IsMethod and Send

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#663]
I'm not sure, if this is expected or not. The following Code gives an error at runtime "No exported method". This is, because the method is hidden. The question is: why does IsMethod return true, if I can not call the method.

```
[STAThread] ;
FUNCTION Start() AS VOID
   local obj := ClassWithHiddenMethod{} as object;
        
   if isMethod(obj, #Test)  // Returns true
      Send(obj, #Test)  // Throws "No exported method"
      obj:test()  // Throws "No exported method"
   endif 
return
    
class ClassWithHiddenMethod
     hidden method Test() as void strict
         console:WriteLine("Hello")
         return
end class    
```

**Comment by cpyrgas** [comment]
Vokmar, this is a very good question, but this is how VO behaves in the same scenario, so we had to implement it the same way also in X#.
