### ISSUE TITLE
"Abort" in the standard VO error dialog does not really abort the program

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#665]
See the following code, after clicking "Abort" on the error dialog, a new error dialog appears, clicking Abort still lets the app continue executing and another dialog appears etc etc. We need to find a better way to ensure that the app does terminate, after clicking Abort and does not continue exection until the app window can be closed. Currently the attempted exit is done by calling _Quit(), which calls :

System.Diagnostics.Process.GetCurrentProcess():CloseMainWindow()

Note that this does not happen only in this simple console app test, but also in real apps. When an error happens inside a loop, then clicking Abort does not help, the error dialog continues displaying again and again multiple times, until the loop is ended and only then the app closes.

```
FUNCTION Start() AS VOID
LOCAL oServer AS DBServer
oServer := DBServer{"c:\nonexistent.dbf"}
oServer:Info(DBI_ALIAS)
oServer:OrderInfo(DBOI_IndexExt)
IF .not. oServer:Used
	oServer := DBServer{"c:\nonexistent.dbf"}
	IF .not. oServer:Used
		oServer := DBServer{"c:\nonexistent.dbf"}
		? "Still executing"
	ENDIF
END IF
oServer:Close()

```

**Comment by cpyrgas** [comment]
Well, the user has already selected "Abort", so expects the app to terminate, so I don't think it's rude.
Another option could be to simply re-THROW the exception which triggered the error dialog to show..

**Comment by RobertvanderHulst** [comment]
I will replace the contents of the _Quit() function with 
System.Diagnostics.Process.GetCurrentProcess().Kill()

**Comment by cpyrgas** [comment]
Confirmed fixed, looks good in a few GUI tests that I tried.
