### ISSUE TITLE
DbOrderInfo(DBOI_INDEXEXT) returns "" or NIL when index file is not opened

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#666]
https://www.xsharp.eu/forum/private-product/2527-dbserver-bug-in-2-8a#18547

In VO, DbOrderInfo(DBOI_INDEXEXT) and DbOrderInfo(DBOI_BAGEXT) return the index extension for the given RDD ".CDX"/".NTX", no matter if an index file has actually been opened or not (but there exists an active database open). In X#, this returns en empty string for DBFCDX and DBFCDX, while AXDBFCDX returns NIL

```
FUNCTION Start() AS VOID
LOCAL cDbf AS STRING
cDbf := "c:\test\testext"
FErase(cDbf + ".cdx")
DbCreate(cDbf,{{"FLD","C",10,0}})


DbUseArea(TRUE , "DBFCDX" , cDbf)
? DbOrderInfo(DBOI_INDEXEXT) // empty string
? DbOrderInfo(DBOI_BAGEXT)   // empty string
DbCloseArea()

DbUseArea(TRUE , "DBFNTX" , cDbf)
? DbOrderInfo(DBOI_INDEXEXT) // empty string
? DbOrderInfo(DBOI_BAGEXT)   // empty string
DbCloseArea()

AdsSetServerType(1)
DbUseArea(TRUE , "AXDBFCDX" , cDbf)
? DbOrderInfo(DBOI_INDEXEXT) // NIL
? DbOrderInfo(DBOI_BAGEXT)   // NIL
DbCloseArea()
```

**Comment by RobertvanderHulst** [comment]
DBOI_INDEXEXT and DBOI_BAGEXT both evaluate to the value 8 and now return:
- either the default extension when no index is open
- the extension of the current open index file

There is also a DBOI_DEFBAGEXT which ALWAYS returns the default extension

**Comment by cpyrgas** [comment]
Robert, this is fixed, but:

After I remind you that "rage" is one of the seven deadly sins, I will tell you that I noticed there's still a mismatch between VO and X# in this area: 
- When there is no workarea open, then DbOrderInfo(DBOI_NAME) returns NIL in both VO and X#. Same for DBOI_BAGNAME, DBOI_INDEXNAME etc.
- When there's a workarea open, VO still returns NIL, but X# now returns an empty string.

See sample;

```
FUNCTION Start() AS VOID
LOCAL cDbf AS STRING
RddSetDefault("DBFNTX")
cDbf := "C:\test\sometest"
DbCreate(cDbf, {{"FLD","C",10,0}})

? "no dbf open"
? DbOrderInfo(DBOI_NAME)      // NIL in both VO and X#
? DbOrderInfo(DBOI_BAGNAME)   // NIL in both VO and X#
? DbOrderInfo(DBOI_INDEXNAME) // NIL in both VO and X#
? DbOrderInfo(DBOI_FULLPATH)  // NIL in both VO and X#
? DbOrderInfo(DBOI_BAGEXT)    // NIL in both VO and X#
? DbOrderInfo(DBOI_INDEXEXT)  // NIL in both VO and X#
DbUseArea(TRUE,"DBFNTX",cDbf)
? "dbf open"
? DbOrderInfo(DBOI_NAME)      // NIL in VO, empty string in X#
? DbOrderInfo(DBOI_BAGNAME)   // NIL in VO, empty string in X#
? DbOrderInfo(DBOI_INDEXNAME) // NIL in VO, empty string in X#
? DbOrderInfo(DBOI_FULLPATH)  // NIL in VO, empty string in X#
? DbOrderInfo(DBOI_BAGEXT)    // .NTX in both VO and X#
? DbOrderInfo(DBOI_INDEXEXT)  // .NTX in both VO and X#
```

Honestly no idea if it's worth adjusting this in X# and if such difference will ever be found and affect a X# programmer, but I am adding it for your consideration. I also know that some tests in the suite incorrectly assume empty strings instead of NIL for the above scenario.

**Comment by RobertvanderHulst** [comment]
Chris, I know:
1. Superbia 
2. Avaritia
3. Luxuria 
4. Invidia 
5. Gula 
6. **Ira** 
7. Acedia

**Comment by cpyrgas** [comment]
Ah, it's "wrath," not "rage" - Ira. My favorite is usually Acedia :)

**Comment by RobertvanderHulst** [comment]
I'll fix this anyway. Btw: I am considering to return DBNull.Value from the RDD (which gets converted to NIL in the USUAL type) instead of NULL to indicate that this is intended to return a NIL. The RDD cannot return NIL because it has no reference to the XSharp.RT assembly.

**Comment by cpyrgas** [comment]
Makes sense to me!

**Comment by cpyrgas** [comment]
Robert, I cannot confirm the runtime fixes yet, because I get errors compiling the runtime, for example:

```
Error XS1503: Argument 2: cannot convert from 'byte[]' to 'System.IntPtr'	

FUNCTION FRead4(ptrHandle AS IntPtr, ptrBufferVar AS IntPtr,dwBytes AS DWORD, lAnsi AS LOGIC) AS DWORD
	// use Buffer associated with file handle
    VAR bData := FGetBuffer(ptrHandle, (INT) dwBytes)
	VAR dwResult := FRead4(ptrHandle, bData, dwBytes, lAnsi) // Error XS1503
	Marshal.Copy(bData, 0, ptrBufferVar, (INT) dwResult)
	RETURN dwResult
```

This code is in XShartp.RT. There's an appropriate overload in XSharp.Core, but the compiler seems to regard only this definition itself in XSharp.RT.

**Comment by cpyrgas** [comment]
Confirmed fixed. The devil is no more.
