### ISSUE TITLE
Generic class and the settings /memvar+ and /undeclared+

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#668]
While looking in a problem, i found another one. It doesn't matter if you choose the [VO] or [Foxpro] dialect, important is to use the compiler settings: 

/memvar+
/undeclared+

When you compile the code you get - as expected - the warning that the var 'var_does_not_exist' does not exist ;-) Ignore it, run the code and wonder why it works ...  

How is it possible that ValType() returns "C" and "N" when in the constructor the passed value is assigned to a protect var that does not exist ? 

Karl-Heinz

```
CLASS DataStore <T> 
PROTECT _xValue AS T

CONSTRUCTOR ( value AS T )
	
	var_does_not_exist := value 
	
PROPERTY Data AS T GET _xValue
	
END CLASS 		

FUNCTION Start( ) AS VOID
LOCAL a AS DataStore <STRING> 	
LOCAL b AS DataStore <INT> 

	a := Datastore <STRING> { "One" } 
	? ValType ( a:Data ) // "C"
	
	b := Datastore <INT> {1}
	? ValType ( b:Data ) // "N"
	
RETURN

```

**Comment by RobertvanderHulst** [comment]
Karl Heinz,
This makes perfect sense, because the Data property is typed correctly, so it is a string for a) and an int for b). a:Data is null string and b:Data is 0. 
When you call Valtype() then these values are converted to a usual first and then evaluated by ValType().

**Comment by Karl1155** [comment]
Robert,

Arrrrrrgh, i see the point. Thanks ! i was too focused on the var that doesn't exist. A simple

? a:Data

? b:Data

shows that the values are: "" and 0 

I think, the ticket can be marked as [makesnosence] ;-)
