### ISSUE TITLE
Feature request: make overloads for Empty for some strict types

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#669]
There are scenarios when Empty() function is used with typed variables. So in order to avoid unneccessary convertion to Usual such overloads are proposed:

```
FUNCTION Empty(cString AS STRING) AS LOGIC
RETURN String.IsNullOrWhiteSpace(cString)

FUNCTION Empty(dDate AS DATE) AS LOGIC
RETURN (dDate == NULL_DATE)

FUNCTION Empty(aArray AS ARRAY) AS LOGIC
RETURN ((aArray?:Length ?? 0) == 0)

FUNCTION Empty<T>(aArray AS XSharp.__ArrayBase<T>) AS LOGIC
RETURN ((aArray?:Length ?? 0) == 0)

FUNCTION Empty<T>(aT AS T[]) AS LOGIC
RETURN ((aT?:Length ?? 0) == 0)

FUNCTION Empty<T>(oList AS ICollection<T>) AS LOGIC
RETURN ((oList?:Count ?? 0) == 0)

FUNCTION Empty(oObject AS OBJECT) AS LOGIC
RETURN (oObject == NULL_OBJECT .OR. DBNull.Value:Equals(oObject)) // the latter clause is to be discussed

FUNCTION Empty<T>(something AS T) AS LOGIC WHERE T IS STRUCT
RETURN something:Equals(DEFAULT(T))

FUNCTION Empty(nInteger AS INT) AS LOGIC
RETURN (nInteger == 0)

FUNCTION Empty(dwUINT AS DWORD) AS LOGIC
RETURN (dwUINT == 0)

FUNCTION Empty(lLogic AS LOGIC) AS LOGIC
RETURN !lLogic

FUNCTION Empty(sSymbol AS SYMBOL) AS LOGIC
RETURN (sSymbol == NULL_SYMBOL)

FUNCTION Empty(pszString AS PSZ) AS LOGIC
RETURN (pszString == NULL_PSZ .OR. pszString:Length == 0)

FUNCTION Empty(pVar AS PTR) AS LOGIC
RETURN (pVar == NULL_PTR)

FUNCTION Empty(dtDateTime AS DateTime) AS LOGIC
RETURN (dtDateTime == DEFAULT(DateTime))
```

I guess the "Aggressive inlining" attribute would also be appropriate here.

**Comment by RobertvanderHulst** [comment]
Serrgio,
Thanks for the suggestion. We will certainly look at it.
But I am not really sure if this will make a big difference.
And if we do so, why not choose

```
FUNCTION Empty<T>(aVar as T) AS LOGIC WHERE T IS STRUCT
RETURN T == DEFAULT(T)

```
for all value types such as LOGIC, DATE, DWORD , SYMBOL etc

**Comment by cpyrgas** [comment]
Please remember that this is a breaking change, which will require a rebuild and re-distributionof all 3rd party products. We probably need to plan a build in which all such breaking changes will be done at once, for minimum disruption.

**Comment by RobertvanderHulst** [comment]
Chris,
If we keep the current empty (with the usual argument) then this does not have to be breaking. Of course "old" code would then never benefit of the new overloads.
Robert

**Comment by Serggio** [comment]
> FUNCTION Empty<T>(aVar as T) AS LOGIC WHERE T IS STRUCT
> RETURN T == DEFAULT(T)

if you mean here ```aVar == T``` that won't compile, because there is no default == operator for all value types. 
But there is a way to do it with Equals method, which I gave:
```
FUNCTION Empty<T>(something AS T) AS LOGIC WHERE T IS STRUCT
RETURN something:Equals(DEFAULT(T))
```

But I've made some research and found that using Equals method is a huge overhead - the method is very complex inside and should be used only for the user defined structs, so I suggest to use overloads for the built-in value-types at least.

**Comment by cpyrgas** [comment]
Robert, didn't we have trouble with another overloaded function with a usual and non-usual argument which was causing some trouble and we had to remove one of them? Can't remember the details now, dont' remember if it was a runtime or compile time problem, but will try to find this.

**Comment by RobertvanderHulst** [comment]
I will create an experimental version of this and will test it internally with typed, untyped and macro compiler code to see if this does not break anything. Will report back on this.

**Comment by Serggio** [comment]
And here is the solution. Change ```FUNCTION Empty(oObject AS OBJECT) AS LOGIC``` overload to such:

```
FUNCTION Empty(oObject AS OBJECT) AS LOGIC

	IF oObject == NULL_OBJECT .OR. Convert:IsDBNull(oObject)
		RETURN TRUE
	ENDIF

	VAR oType := oObject:GetType()
	IF oType:IsValueType
		SWITCH System.Type.GetTypeCode(oType)
		CASE TypeCode.Byte
			RETURN ((BYTE)0).Equals(oObject)
		CASE TypeCode.SByte
			RETURN ((System.SByte)0).Equals(oObject)
		CASE TypeCode.UInt16
			RETURN ((System.UInt16)0).Equals(oObject)
		CASE TypeCode.UInt32
			RETURN ((DWORD)0).Equals(oObject)
		CASE TypeCode.UInt64
			RETURN ((System.UInt64)0).Equals(oObject)
		CASE TypeCode.Int16
			RETURN ((System.Int16)0).Equals(oObject)
		CASE TypeCode.Int32
			RETURN ((INT)0).Equals(oObject)
		CASE TypeCode.Int64
			RETURN ((INT64)0).Equals(oObject)
		CASE TypeCode.Decimal
			RETURN ((System.Decimal)0).Equals(oObject)
		CASE TypeCode.Double
			RETURN ((System.Double)0).Equals(oObject)
		CASE TypeCode.Single
			RETURN ((System.Single)0).Equals(oObject)
		CASE TypeCode.String
			RETURN String.IsNullOrWhiteSpace((STRING)oObject)
		CASE TypeCode.DateTime
			RETURN ((DateTime)oObject == DEFAULT(DateTime))
		CASE TypeCode.Boolean
			RETURN !(System.Boolean)oObject
		CASE TypeCode.Object WHEN oType:Equals(TYPEOF(DATE))
			RETURN ((DATE)oObject == NULL_DATE)
		CASE TypeCode.Object WHEN oType:Equals(TYPEOF(FLOAT))
			RETURN ((FLOAT)oObject == 0.0)
		CASE TypeCode.Object WHEN oType:Equals(TYPEOF(SYMBOL))
			RETURN ((SYMBOL)oObject == NULL_SYMBOL)
		CASE TypeCode.Object WHEN oType:Equals(TYPEOF(System.IntPtr))
			RETURN ((System.IntPtr)oObject == NULL_PTR)
		CASE TypeCode.Object WHEN oType:Equals(TYPEOF(CURRENCY))
			RETURN ((CURRENCY)oObject == 0)
		END SWITCH
	ENDIF

RETURN FALSE
```

You should not be afraid of that big switch. It will work fast for all the primitive types. I've tested it thoroughly.

**Comment by leon-ts** [comment]
I ran into this problem in RDD (Empty for OBJECT type). Unlike VO, in the RDD model for X#, the USUAL type parameters have been replaced with OBJECT type, since in NET the OBJECT type plays a role similar to that of the USUAL type in VO. For example, the IRdd:OrderCreate method accepts an order name in an OBJECT field in the DbOrderCreateInfo class. This field can contain a string, a number, or an empty value (NIL, 0 or "").

I have my own SqlRdd (transported from VO) that derives from the Workarea class (implements the IRdd interface). In VO, I checked the empty value of the order field using the Empty function. In X#, I left the same check with the Empty function, since up to and including version 2.8c it returned a similar USUAL result for OBJECT-boxed value types. But in 2.9, this behavior has changed.

Question to developers: will you apply Serggio's suggested fix? Or this is the final version of the Empty function, and then I will modify my SqlRdd to check for empty values in a different way.

**Comment by RobertvanderHulst** [comment]
Leonid,
I will use your overload for Empty(oObject as OBJECT) with a small change:
- for the built-in types I will use the keyword
- I changed the code for the special types to (to make it more readable and cover more types)
```
           CASE TypeCode.Object WHEN oType is IDate VAR oDat
            RETURN oDat:IsEmpty
        CASE TypeCode.Object WHEN oType IS IFloat VAR oFl
            RETURN oFl:@@Value == 0.0
        CASE TypeCode.Object WHEN oObject IS SYMBOL VAR oSym
            RETURN oSym == NULL_SYMBOL
        CASE TypeCode.Object WHEN oObject IS System.IntPtr VAR oPtr
            RETURN oPtr == IntPtr.Zero
        CASE TypeCode.Object WHEN oObject IS Currency VAR oCur
            RETURN oCur:@@Value = 0.0m
        CASE TypeCode.Object WHEN oObject IS __WinBool VAR oWb
            RETURN ! (LOGIC) oWb
        CASE TypeCode.Object WHEN oObject IS __WinDate VAR oWd
            RETURN ((DATE) oWd):IsEmpty
```

What do you think of this ?

**Comment by leon-ts** [comment]
Robert,

> Leonid,
> I will use your overload for Empty(oObject as OBJECT) with a small change:

This is not my overload, but Serggio, as well as the ticket in general :)) Let's wait for his answer (at least he checked the function).

**Comment by leon-ts** [comment]
Robert,

> I changed the code for the special types to (to make it more readable and cover more types)
> What do you think of this ?

Personally, I like the version of the code you proposed.

**Comment by Serggio** [comment]
> Leonid, I will use your overload for Empty(oObject as OBJECT) with a small change:
> 
> * for the built-in types I will use the keyword
> * I changed the code for the special types to (to make it more readable and cover more types)
> 
> ```
>            CASE TypeCode.Object WHEN oType is IDate VAR oDat
>             RETURN oDat:IsEmpty
>         CASE TypeCode.Object WHEN oType IS IFloat VAR oFl
>             RETURN oFl:@@Value == 0.0
>         CASE TypeCode.Object WHEN oObject IS SYMBOL VAR oSym
>             RETURN oSym == NULL_SYMBOL
>         CASE TypeCode.Object WHEN oObject IS System.IntPtr VAR oPtr
>             RETURN oPtr == IntPtr.Zero
>         CASE TypeCode.Object WHEN oObject IS Currency VAR oCur
>             RETURN oCur:@@Value = 0.0m
>         CASE TypeCode.Object WHEN oObject IS __WinBool VAR oWb
>             RETURN ! (LOGIC) oWb
>         CASE TypeCode.Object WHEN oObject IS __WinDate VAR oWd
>             RETURN ((DATE) oWd):IsEmpty
> ```
> 
> What do you think of this ?

perfect! I do agree with it.

**Comment by RobertvanderHulst** [comment]
Guys,
Sorry for mixing up the names. I returned from a short trip and there were a gazillion messages in my inbox.

**Comment by cpyrgas** [comment]
Confirmed fixed
