### ISSUE TITLE
Allow '=' operator for assignments in FoxPro.

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#67]
We can detect the places in the language where the compiler expects a "conditional expression", such as the expression in IF statements, WHILE statements and DO CASE statements. On these places the '=' will always be treated as a comparison operator.
For example

`IF x = y`

or

```
DO CASE
CASE x = y

```

For simple binary expressions that are part of an expression statement we can assume that '=' is an assignment:

`x = y
`
For complex binary statements (chained binary statements) it is more difficult for the compiler to determine the meaning of the '=' operator:

`x = y = z.
`
In this statement x could become a logical or could also get the value of z.
I think I will mark the second operator in such a line with an warning. Something like "ambiguous operator detected. Could be assignment or comparison".

**Comment by mattslay** [comment]
In the case of 

`x = y = z`

What code would be required to satisfy the compiler for these 2 possible cases:

**Case 1:**

I want X to be a bool .T. or .F. based on if Y is equal to X.

Perhaps this??    `x := y = x`


**Case 2:**

I want to set X and Y equal to Z.

What syntax code would prevent this from causing a compiler error?  Perhaps just have to break it into two lines?

```
y = z
x = y
```





You could choose a "rule" that says the first = is considered an assignment, and the later is considered a comparison.

That would make the above interpreted as:

x = ( y = x )

**Comment by RobertvanderHulst** [comment]
**Case 1**:
The first assignment with := is not ambiguous, but the second still is. Of course we could hand-code a rule that says that when the statement contains mixed operators and the first is a `:=` and the second is `=`  then the `=` must be treated as a comparison. But that is still not ideal and could cause problems. How does FoxPro handle this ?
Not ambiguous is 
`x := y == z`
**Case 2**:
The best solution would be to change this to
`x := y := z`
but I realize that this requires a code change.
OTOH how often does a chained expression like this occur in a normal users code ?
I would personally tell my colleague to change his code if he coded `x = y = z`

**Comment by mattslay** [comment]
FoxPro treats 

`x = y = z`

like:

x : = y == z

I have code in my app like this, but notice how I wrap it in parentheses because I think it makes the mode more clear to follow:

lCancel = (nAftervalue = nBeforeValue)

**Comment by RobertvanderHulst** [comment]
I can probably 'teach' the parser to do the same.

In short: only the first (single equals) assignment on a line is treated as assignment. Subsequent single equals operators are a comparison. And on other places (IF, WHILE, DO CASE etc) the single equals is also a comparison operator.
And if the expression is surrounded with parentheses it is also a comparison, so 
`? (x = y) ` will be seen as `? (x == y)`
but this will be an assignment
`? x = y`  

And as parameters in method or function call it will also be treated as a comparison:
`DoSomething( x = y)  // this will pass TRUE or FALSE`

**Comment by mattslay** [comment]
I cannot find “ == “ in the X# help file...

Where will I find it referenced?

**Comment by RobertvanderHulst** [comment]
Will update the help for operators for the next build
