### ISSUE TITLE
VO XPorter generates two same lines in xsproj

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#672]
After converting the AEF file to X#, VO XPorter creates two identical lines with the **OutputPath** key in the xsproj file in the **Debug** configuration:
`<OutputPath>$(SolutionDir)$(Configuration)</OutputPath>`

![изображение](https://user-images.githubusercontent.com/64518775/119495893-93938100-bd6b-11eb-853c-61485c877206.png)

**Comment by cpyrgas** [comment]
Will confirm this when testing the new installer, to make sure all is good with the new files.

**Comment by cpyrgas** [comment]
Confirmed fixed.
