### ISSUE TITLE
VS2019 freeze when attaching a file to the main IDE

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#676]
- In VS 2019, open or create a solution, like the VO MDI sample.
- Open 2 .prg files in the editor
- Detach one of them, by dragging their caption, outside of the main IDE area, into a floating window
- Attach it back to the main IDE, again by dragging it's caption next tot he other file's caption
- Now VS2019 freezes

Problem happens only in VS2019. In VS2017, it all works fine.

**Comment by RobertvanderHulst** [comment]
I cannot reproduce this here with Version 16.10.2 of VS 2019

**Comment by cpyrgas** [comment]
Can't reproduce this either now, although it was 100% reproducible at the time I reported it. Maybe something else fixed it in the meantime. Let me test again with the latest VS integration again and will close it if I still can't reproduce it.

**Comment by cpyrgas** [comment]
Confirmed fixed.
