### ISSUE TITLE
Problem with GetObjectByHandle function

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#677]
There is one significant difference between the **GetObjectByHandle** function in VO and XSharp.
In VO, you can check the window handle that it is part of your VOGUI application. In this case, the **GetObjectByHandle** function will return a valid instance of the VOGUI Window object. If the window handle is invalid or not part of your VOGUI application, then the **GetObjectByHandle** function will return NULL_OBJECT, without any runtime errors.

In XSharp, if the window handle is valid but not registered in the VOGUI subsystem, the **GetObjectByHandle** function throws an exception. After examining the SDK, I realized that maybe the problem is that in XSharp the **MemCheckPtr** function is just a stub and always returns TRUE. As a result, inside the **__WCSelfPtr2Object** function, the pointer is checked and then crashes in the following code:
```
IF (p:ptrSelf != 0)
    oObject := GCHandle.FromIntPtr( p:ptrSelf ):Target
ENDIF
```

**Comment by cpyrgas** [comment]
Confirmed, problem can be reproduced by simply calling

`GetObjectByHandle(GetForegroundWindow())`

in a console app, or in a gui app before showing any windows.

The exception happens in the call to p:ptrSelf of the (removed unneeded stuff) __WCSelfPtr2Object() function:

```
FUNCTION __WCSelfPtr2Object( p AS SelfPtr) AS OBJECT
   LOCAL oObject AS OBJECT
   IF p != NULL_PTR .and. MemCheckPtr(PTR(_CAST, p), _SIZEOF(SelfPtr))
         IF (p:ptrSelf != 0) // <-------------  System.AccessViolationException
		     oObject := System.Runtime.InteropServices.GCHandle.FromIntPtr( p:ptrSelf ):Target
		   ENDIF
      RETURN oObject  
   ENDIF   
   RETURN NULL_OBJECT

System.AccessViolationException
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Callstack : 
static Object VOGUIClasses.Functions.__WCSelfPtr2Object(VO.SelfPtr* p)() 
static Window VOGUIClasses.Functions.__WCGetWindowByHandle(System.Void* hWnd)() 
static Object VOGUIClasses.Functions.__WCGetObjectByHandle(System.Void* hWnd)() 
static Object VOGUIClasses.Functions.GetObjectByHandle(System.Void* hwnd)() 

```

**Comment by RobertvanderHulst** [comment]
Most likely the easiest solution for this is to get rid of the SelfPtr completely and to use add a simple dictionary<intPtr, Object> in which the handle / object pairs are stored. 
What do you think of that ?

**Comment by cpyrgas** [comment]
It makes sense indeed! Only danger is to accidentally introduce a difficult to find bug in this area if we miss something while doing such changes..

**Comment by RobertvanderHulst** [comment]
Chris,
I made bigger changes without errors. But of course, sh*t can (and sometimes will ) happen.
If we delete the SelfPtr type from the SDK then we can be sure that no references will remain.

**Comment by cpyrgas** [comment]
Robert, yeah, I just don't feel comfortable enough myself in this area and would be afraid of making such changes, probably because I have not completely understood how this system works in VO. I am sure it will feel a lot more straightforward to you!

**Comment by leon-ts** [comment]
Robert,
I think using the dictionary <intPtr, Object> is a good idea, reliable.
Anything can be in DWL_USER for windows not created in VOGUI. Therefore, storing data there without the possibility of securely checking what kind of data it is will lead to the inoperability of the application.

**Comment by leon-ts** [comment]
You can also use a less radical idea, which is why Chris is worried.
The problem now is that we cannot safely validate the pointer (ours or not ours). Therefore, wherever SetWindowLong(hWnd, DWL_USER, ...) is called, it is possible to duplicate the pointer value in a special dictionary. This will be a directory of valid values. Then, wherever we call GetWindowLong(hWnd, DWL_USER), check the returned value against our valid values lookup. And if such a check passes, then we use the resulting pointer according to the already existing algorithm.

**Comment by RobertvanderHulst** [comment]
Guys,
I checked and I can fairly easy recreate what MemCheckPtr() in VO does to validate the pointers.
It would look like this:

```
UNSAFE FUNCTION MemCheckPtr( pMemory AS PTR, dwSize AS DWORD ) AS LOGIC
    STATIC LOCAL Is32Bits := IntPtr.Size == 4 AS LOGIC
    LOCAL i64 AS INT64
    IF pMemory == NULL_PTR
        RETURN FALSE
    ENDIF
    IF IsRunningOnWindows() .AND. Win32.IsBadWritePtr(pMemory, dwSize)
        RETURN FALSE
    ENDIF
    VAR pWork := (IntPtr) pMemory
    IF Is32Bits
        i64 := (pWork:ToInt32() - SIZEOF(FixedMemBlockStart))
    ELSE
        i64 := (pWork:ToInt64() - SIZEOF(FixedMemBlockStart))
    ENDIF
    VAR pMemBlockStart := (FixedMemBlockStart PTR) IntPtr{i64}:ToPointer()
    IF ! pMemBlockStart:IsValid()
        RETURN FALSE
    ENDIF
    IF pMemBlockStart:dwSize < dwSize
        RETURN FALSE
    ENDIF
    IF Is32Bits
        i64 := pWork:ToInt32() + pMemBlockStart:dwSize
    ELSE
        i64 := pWork:ToInt64() + pMemBlockStart:dwSize
    ENDIF
    VAR pMemBlockEnd := ( FixedMemBlockEnd PTR) IntPtr{i64}:ToPointer()
    RETURN pMemBlockEnd:IsValid()
```
It is a lot of code (it is in VO too) but it would definitely catch incorrect pointers.
And I think the Jit optimizer will quickly remove the unused branches in the Is32Bits code.
And Win32.IsBadWritePtr is declared as 
```
    [DllImport("kernel32.dll")] ;
    STATIC INTERNAL METHOD IsBadWritePtr(hMemory AS IntPtr, dwSize AS DWORD) AS LOGIC PASCAL
```

Shall I introduce that and leave the rest of the code alone?
Or do you think it is better to use a dictionary to check for validity of pointers.

**Comment by leon-ts** [comment]
Robert,
Personally, I like your new solution. Given that the problem was the impossibility of checking the pointer, and now it is possible, I think this will solve the problem. And also you don't have to touch the already tested VOGUIClasses library code.

**Comment by cpyrgas** [comment]
I agree that implementing the MemCheckPtr() function is the best solution indeed, because:

-It is a documented function in VO, so may be used in people's code already
-It will not require any changes in the SDK
-It is implemented also in vulcan, so X# will become more compatible with it, too.

Performance is a concern, because this function is called indirectly from dozens of places, including winprocs. But since this code executes every time also in VO, I guess it will not be a problem. Of course any optimization can be done to its code would be great!

**Comment by Karl1155** [comment]
Robert,

i compared the X# code with VO's MemCheckPtr() behaviour and noticed that the results are not always the same. Let's say 5 
bytes are allocated, but later *6* bytes are written. In this case VO returns .f. , but X# still returns .t. After changing the length of cValue to 10, X# finally returns .f. as well. It seems VO takes care if more bytes are written than allocated ?  

```
	LOCAL p AS PTR
	LOCAL cValue AS STRING 
	
	cValue := Replicate ( "a" , 6 ) // try 9 and then 10 if X# is used
	
	p := MemAlloc( 5 )
    
	MemCopyString( p , cValue , SLen ( cValue ) )  
 
	? "MemCheckPtr", MemCheckPtr ( p , 5 )

	MemFree ( p )

```

The cValue length thresholds seem to be:

NumberOfAllocatedBytes + 4   	//  within this range the X# MemCheckPtr() returns .t.
NumberOfAllocatedBytes + 4 + at least 1	//  from now on the X# MemCheckPtr() returns .f. 

- i tried the x86 and x64 mode, but the results are the same.
- i run the same code with the vulcan dlls and the results are equal to the X# results. 

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,

VO (and X#) allocate a "footer block" after the memory. The first DWORD in this footer block is set to 0 and the second DWORD in this block has a special value. The first DWORD is there in case someone wants to attach something special to a memory block (you could see it like a Cargo slot). Not many people know about these 4 bytes to be honest.
It is also there for people that forget to allocate an extra byte of memory when allocate memory for PSZ values.

My code is only checking the special value. So if you overwrite the block with upto 4 bytes my code will not report an error. Overwriting with more than 4 bytes will corrupt the special value and will cause MemCheckPtr() to return false.

I can add a check in FixedMemBlockEnd:IsValid() to  see that the zero has not been overwritten, if you think that is really needed. 
But I think in this case it is not important. Even if you overwrite these 4 bytes the block is still valid and safe.
You should also realize that MemFree() checks for this too. If we would check for the 0 and someone overwrites this extra dword then the block will no longer be freed by MemFree().

**Comment by Karl1155** [comment]
Robert,

Thanks for the inside view !  

To be honest, i never used MemCheckPtr(), and i doubt that more than one or two people ever used this function in the past  But i think you already know that i'm a big fan of looking at the details, and that my point of view is that "Testing" doesn't mean to simply verify if 1+1 results in 2 ;-)

btw. Do you know the "Final Destination" series that spread the common message: "watch out for the details" ;-)

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
I have heard about "Final Destination". But I don't see the relation with MemCheckPtr() ?
