### ISSUE TITLE
Several places with incorrect use of ?: operator in Runtime

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#678]
For example, here:
https://github.com/X-Sharp/XSharpPublic/blob/75ea5b5f6871a8b2d3ba13797cae157276f394ac/Runtime/XSharp.Core/RDD/Workarea.prg#L1145

instead of ```GET (LONG) _Fields?:Length``` it should be ```GET _Fields?:Length ?? 0```

There are some more:
https://github.com/X-Sharp/XSharpPublic/blob/75ea5b5f6871a8b2d3ba13797cae157276f394ac/Runtime/XSharp.Core/RDD/Workarea.prg#L562

https://github.com/X-Sharp/XSharpPublic/blob/75ea5b5f6871a8b2d3ba13797cae157276f394ac/Runtime/XSharp.Core/RDD/Workarea.prg#L1099

https://github.com/X-Sharp/XSharpPublic/blob/75ea5b5f6871a8b2d3ba13797cae157276f394ac/Runtime/XSharp.Core/Messages.prg#L161

https://github.com/X-Sharp/XSharpPublic/blob/75ea5b5f6871a8b2d3ba13797cae157276f394ac/Runtime/XSharp.VO/Functions/String.prg#L16

**Comment by cpyrgas** [comment]
Confirmed! Btw, instead of using GET _Fields?:Length ?? 0, there's also the more xBase like syntax GET _Fields?:Length DEFAULT 0

**Comment by cpyrgas** [comment]
Looks good, except in OOP.prg, where there a few spots with code like

```
FUNCTION ClassName(oObject AS OBJECT) AS STRING
    IF oObject != NULL
	    RETURN oObject?:GetType():Name:ToUpper()
    ENDIF
    RETURN ""
```

So there's both a test for oObject != NULL and then again the "?:" operator is used on oObject. Same happens in functions ClassTree(), IsAccess(), IsAssign() and IsMethod()

Robert, this is obviously minor, but maybe you'd like to have those adjusted as well. Apart from that, you can close the ticket.

**Comment by cpyrgas** [comment]
Confirmed fixed.
