### ISSUE TITLE
IntelliSense not working correctly when using dot instead of colon in VO Dialect with AllowDot = true

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#679]
After activating AllowDot for one of our VO Dialect projects, I noticed, that the IntelliSense seems to not work as expected, when using dot instead of colon. 

These two images show the difference:

With colon
![image](https://user-images.githubusercontent.com/9860916/120605750-b817e900-c44e-11eb-88a3-20a2005227a5.png)

With dot
![image](https://user-images.githubusercontent.com/9860916/120605810-c9f98c00-c44e-11eb-85da-856499f21ed6.png)

**Comment by cpyrgas** [comment]
Confirmed fixed.

**Comment by VolkmarR** [comment]
Hi. I tested this change and I noticed, that the Intellisence for "dot" only works, after I activated this option in the settings:

![image](https://user-images.githubusercontent.com/9860916/121398418-9e4a3a80-c955-11eb-933f-f934cc3d7c2d.png)

Is that by design?

**Comment by RobertvanderHulst** [comment]
Volkmar,
You are right and this is something that needs to be changed. We will make sure that the editor will follow the "AllowDot" setting from the project settings for this.

**Comment by cpyrgas** [comment]
That worked nicely, but with one problem: After setting or resetting the "Allow DOT" compiler option, the solution must be closed and reopened, for intellisense to respect the new setting.

**Comment by RobertvanderHulst** [comment]
This was not too complicated, so I fixed it.

**Comment by cpyrgas** [comment]
Excellent!
