### ISSUE TITLE
Recycle the name of a released Foxarray memvar

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#680]
if you run the code unchanged all works as expected.

```
PRIVATE a

//	DIMENSION a[4]  
    a = 12
    
    ? Type ( "a" ) // "A" or "N"
    RELEASE a  // <---------------------
    ? Type ( "a" ) // "U"    
    ?
    
	a = "test"  
	
    ? Type ( "a" ) // "C"
   	RELEASE a 
    ? Type ( "a" ) // "U"
    ?
```

But if you enable the "DIMENSION" line and disable the "a = 12" line, you should see an "Variable does not exist" error. This happens because the line. 

`a = "test"  `

is translated to 

`XSharp.VFP.Functions.__FoxFillArray(XSharp.RT.Functions.__MemVarGet(e"a"), e"test")`

though the former 'a' array was already released via the RELEASE Command.

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
This will be extremely difficult to fix / implement.
The compiler detects the DIMENSION a[4]  line and marks the variable with the name "a" as a FoxPro array.
It then knows that the like a = <somevalue> has to be interpreted as a array fill operation.
I will see if I can "teach" the compiler that after the RELEASE statement the name "a" is no longer a FoxPro array.
But I really do not like this code to be honest. 
There is no good reason to use the same variable for an array and for a number later.  
This kind of code can and will introduce problems, sooner or later.
