### ISSUE TITLE
BlobGet function returns LOGIC instead of the real field value

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#681]
It is coded like:
https://github.com/X-Sharp/XSharpPublic/blob/75ea5b5f6871a8b2d3ba13797cae157276f394ac/Runtime/XSharp.RT/RDD/Blob.prg#L39

and VoDb.Info returns LOGIC, while the value should be obtained via another overloaded version of ```Info``` method which has the second parameter as REF.

**Comment by Serggio** [comment]
PS. Sometimes there are quite obvious and simple fixes need to be made. And it may be too much to create a ticket for each case. I am quite new to git versioning but I feel there must be a way for me to fork (or make a branch?) of runtime repository to test these fixes which I make myself and propose them for your approval. So that if you agree you have to just press a button so that they merge and not waste your time to write something trivial.
If there is such a way, that would be an honor for me to participate.

**Comment by RobertvanderHulst** [comment]
Serggio,
This works just like you say:
- fork the repo
- make the changes locally and test them
- push the changes to your fork on github
- send us a pull request.

And we vert much welcome contributions that way !

Robert

**Comment by cpyrgas** [comment]
Confirmed fixed
