### ISSUE TITLE
Member completion not working in some cases

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#682]
- Create a new vo console app, or just add a new code file to an existing project, or use any prg open in the editor and delete all its contents. 
- Now copy paste the following code. 
- Try invoking member completion in any of e1, e2, o, no list is shown. 
- After playing around with the code, adding/removing code etc, at some point it starts working, but by clearing the .prg contents and pasting the code again, the problem resurfaces

```
ENUM LocalEnum
    MEMBER Foo
    MEMBER Bar
END ENUM


FUNCTION Start() AS VOID STRICT
    LOCAL e1 AS LocalEnum
    LOCAL e2 AS System.ConsoleKey
    LOCAL o AS System.Collections.ArrayList
    
```

**Comment by cpyrgas** [comment]
Similarly, delete everything and type

```
FUNCTION Start() AS VOID
System.Console.
```

For the first dot, the auotype list opens and shows members of System. But when you type the next dot, there's no member completion list shown.

**Comment by RobertvanderHulst** [comment]
This only happens if there is no CRLF after the last line.

**Comment by cpyrgas** [comment]
Confirmed fixed.
