### ISSUE TITLE
AccessViolationException with FRead()

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#686]
FRead() produces an AccessViolationException, when the string argument is passed with the @ operator and /vo7+ is enabled. When the REF keyword is used instead of "@", then the function works correctly.

```
// /vo7+
FUNCTION Start() AS VOID
LOCAL cFileName AS STRING
LOCAL hHandle AS PTR
LOCAL cText AS STRING
cFilename := "c:\test\abc.txt"

System.IO.File.WriteAllText(cFileName , "ABCDE1234567890")
hHandle := FOpen(cFileName)
FRead(hHandle , REF cText , 5) // ABCDE, OK
? cText
FRead(hHandle , @cText , 5) // System.AccessViolationException
? cText
FClose(hHandle)

System.AccessViolationException
Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Callstack : 
String XSharp.__Usual.ToString()() 
static String XSharp.__Usual.op_Implicit(XSharp.__Usual u)() 
static String XSharp.RT.Functions.AsString(XSharp.__Usual uValue)() 
static System.Void XSharp.RT.Functions.QOut(XSharp.__Usual uValueList)() 

```

**Comment by RobertvanderHulst** [comment]
Fixed in https://github.com/X-Sharp/XSharpDev/commit/aafe16d306a2b702d08b5e6980efd34b66d5d40c

**Comment by cpyrgas** [comment]
Robert, please force an update of the compiler dlls in actions so I can test this

**Comment by RobertvanderHulst** [comment]
This is already included in last nights build. C780 compiles and runs without issues.

**Comment by cpyrgas** [comment]
The latest compiler binaries I could find in https://github.com/X-Sharp/XSharpDev/actions do not seem to include this though

**Comment by cpyrgas** [comment]
Oh damn, had forgotten to put CodeAnalysis in the GAC... Confirmed fixed.
