### ISSUE TITLE
Slow response to typing in Visual Studio (tested with X# 2.8a and 2.8b)

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#689]
While working in our Winforms Solution, we noticed, that Visual Studio often reacts very slowly. This happens most of the time, when typing : or (. 

I analyzed this behavior and created the following videos. You can see my keystrokes on the bottom left of the screen. 

![CorrectDeclaration](https://user-images.githubusercontent.com/9860916/121542422-6c45e080-ca08-11eb-84e5-7a436d44a832.gif)

It the code contains errors (wrong parenthesis after StringBuilder), the situation get's worse.

![IncorrectDeclaration](https://user-images.githubusercontent.com/9860916/121542799-b6c75d00-ca08-11eb-8618-abcde4620063.gif)

I was able to connect this problem to the syntax colonisation. If I disable that feature, the reaction to my typing is nearly instant but I loose syntax highlighting and also code completion.

![SyntaxColloringDisabled](https://user-images.githubusercontent.com/9860916/121543398-2ccbc400-ca09-11eb-9ead-f5c49bbd5a13.gif)

**Comment by VolkmarR** [comment]
I also recorded the XSharp log. This output was generated for typing sb:Append("aaaaa")
[XSharpLog.txt](https://github.com/X-Sharp/XSharpPublic/files/6632442/XSharpLog.txt)

**Comment by VolkmarR** [comment]
Robert. If you need additional information like the X#Model.xsdb or the solution, let me know.

**Comment by RobertvanderHulst** [comment]
Thanks for the info. What I found so far:
- Some assemblies do not expose types. These are read over and over again (System.ValueTuple.dll)
- The parser correctly resolves sb to System.Text.StringBuilder
- Lookup of a namespace such as 'System' triggers a lookup of all global members in your project (29677 members). To process these the system needs ~ 1 second
I have made some improvements that will be included in the next build.

**Comment by cpyrgas** [comment]
Speed looks good to me, but will let Volkmar confirm this one!

**Comment by VolkmarR** [comment]
Thanks. Can you send me a test build? If yes, I'll test it on our test system. Otherwise I'll wait for the next version to be released.

**Comment by RobertvanderHulst** [comment]
https://1drv.ms/u/s!An3aSY_HolAD4Uv6af79T3WxJwNC?e=ijxou5.
Copy to the c:\Program Files(x86)\Xsharp\Extension\Project folder and run the deploy<n>.cmd file(s) (as admin) in the c:\Program Files(x86)\Xsharp\Uninst folder to install into VS.

**Comment by Tadas-Infominds** [comment]
After copying the files and running the CMD script VS shows this error:
![image](https://user-images.githubusercontent.com/86768099/124086851-c0fdd980-da51-11eb-8dde-61175894225c.png)

Using the latest version of Visual Studio (16.10.3). Any ideas? Thanks.

Error from the VS XML log file:
`  <entry>
    <record>1325</record>
    <time>2021/07/01 07:43:27.744</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [XSharp Project System]Source: &apos;mscorlib&apos; Description: Could not load file or assembly &apos;file:///c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\xsharp\project\XSharpProject.dll&apos; or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)&#x000D;&#x000A;System.IO.FileLoadException: Could not load file or assembly &apos;file:///c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\xsharp\project\XSharpProject.dll&apos; or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)&#x000D;&#x000A;File name: &apos;file:///c:\program files (x86)\microsoft visual studio\2019\enterprise\common7\ide\extensions\xsharp\project\XSharpProject.dll&apos; ---&gt; System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark&amp; stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)&#x000D;&#x000A;   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)&#x000D;&#x000A;   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)&#x000D;&#x000A;   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)&#x000D;&#x000A;&#x000D;&#x000A;System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.</description>
    <guid>{E299FB7B-D273-4678-9ACF-B37B4AF04A12}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo></errorinfo>
  </entry>`

**Comment by RobertvanderHulst** [comment]
Do you know how to enable "fusion logging" on your machine ?
https://stackoverflow.com/questions/255669/how-to-enable-assembly-bind-failure-logging-fusion-in-net
Can you enable that and upload the log that shows which dependency was missing ?

**Comment by Tadas-Infominds** [comment]
These are the only 2 relevant logs that I could find.

file:///C:/FusionLog/Default/devenv.exe/WhereRefBind!Host=(LocalMachine)!FileName=(XSharpProject.dll).HTM:
![image](https://user-images.githubusercontent.com/86768099/124096587-02df4d80-da5b-11eb-8df9-eb6e4de94873.png)

file:///C:/FusionLog/Default/devenv.exe/WhereRefBind!Host=(LocalMachine)!FileName=(XSharpLanguageService.dll).HTM
![image](https://user-images.githubusercontent.com/86768099/124097047-76815a80-da5b-11eb-9b8b-f1d7a4cb966f.png)

**Comment by hpetriffer** [comment]
For me the extension works. Now I have less problems. But e.g. for this code i have to wait about 25 sec until I can write.
`col.Summary.Add(GridColumnSummaryItem{SummaryItemType.Max, SummaryMode.AllRows, col.FieldName, String.Empty})`

If I move the cursort after String.Empty and i make a comma Visual Studio hangs for 25 sec
[xsharp.log](https://github.com/X-Sharp/XSharpPublic/files/6747775/xsharp.log)

**Comment by RobertvanderHulst** [comment]
Tadas,

> These are the only 2 relevant logs that I could find.
> 

These are successful loads. I was looking for failures...

**Comment by RobertvanderHulst** [comment]
col.Summary.Add(GridColumnSummaryItem{SummaryItemType.Max, SummaryMode.AllRows, col.FieldName, String.Empty})

From the log I see that:
- the program does not seem to recognize col from the For Loop
- it therefore has no idea what the type of 'Summary' is and it wastes 22 seconds looking for this.

And the worse thing is: 
In this case it would probably only need to lookup the constructor for GridColumnSummaryItem

I'll see what I can do. However this might not make it into the next (2.8c) build.

**Comment by hpetriffer** [comment]
I Have another issue with the new version. If I rename an folder I get the following exception:
![image](https://user-images.githubusercontent.com/20905638/124225283-750d6c00-db07-11eb-974c-397fbb343f2f.png)
The foldername is valid and has no special characters. Should I open another issue for that?

**Comment by RobertvanderHulst** [comment]
Yes, please create a new ticket with the _complete_ name of the new folder and the path to the solution.
