### ISSUE TITLE
Intellisense doesn't show function overloads

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#692]
If the function has overloads, then after opening the parenthesis, Intellisense only shows the parameters of the first signature.

![изображение](https://user-images.githubusercontent.com/64518775/122077235-3c317f80-ce04-11eb-9ff9-07cf8e9de79f.png)

**Comment by cpyrgas** [comment]
Both overloads are shown now, but not correctly. First overload is fine, but 2nd one is shown with no params:

```
FUNCTION Test(n AS INT) AS VOID
FUNCTION Test(n AS STRING) AS VOID
Test(
```

![VS_function_overloads](https://user-images.githubusercontent.com/14542129/123797699-21283a80-d8ef-11eb-91cf-c4a05a8fccbe.png)

Also, if there are 3 overloads, then only 2 are shown:

```
FUNCTION TestNew(n AS INT) AS VOID
FUNCTION TestNew(n AS STRING) AS VOID
FUNCTION TestNew(n AS DATE) AS VOID
TestNew(
```

![VS_function_overloads3](https://user-images.githubusercontent.com/14542129/123798001-72d0c500-d8ef-11eb-9970-f2129741f276.png)

**Comment by cpyrgas** [comment]
This is fixed, but with a small problem, the list for static members always includes "Equals", while this is a reference method. Try

System.AppDomain.
System.Int32.

both will include "Equals"

**Comment by cpyrgas** [comment]
Seems that also when there's only one overload, still 2 overloads are shown:

FUNCTION OnlyOne(n AS INT, s AS STRING)
   OnlyOne(

![VS_function_overloads1](https://user-images.githubusercontent.com/14542129/123801362-e3c5ac00-d8f2-11eb-8f15-96bc88ca8022.png)

**Comment by cpyrgas** [comment]
Confirmed fixed!
