### ISSUE TITLE
Intellisense doesn't show hints in negated conditions

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#693]
If the condition expression begins with a negation operator, Intellisense does not display the method description after opening the parenthesis:
![изображение](https://user-images.githubusercontent.com/64518775/122078346-2ff9f200-ce05-11eb-9fd1-9c0685bfbfc6.png)

Without the negation operator, hints work:
![изображение](https://user-images.githubusercontent.com/64518775/122078427-3f793b00-ce05-11eb-83fb-42f63b9b2714.png)

**Comment by cpyrgas** [comment]
This one is fixed, but apparently there are some similar issues. Try this:

`
IF ! System. // no completion list
`

`
IF .NOT. System. // no completion list
`

This one shows an incorrect completion list:
`
IF FALSE .AND. System.
`

![VS_completion_list](https://user-images.githubusercontent.com/14542129/123800285-cba15d00-d8f1-11eb-8fd1-e02888aba030.png)

**Comment by cpyrgas** [comment]
Confirmed fixed
