### ISSUE TITLE
Intellisense shows wrong methods of class

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#695]
If you have a function call and need Intellisense inside the brackets, the wrong methods may be displayed.

![image](https://user-images.githubusercontent.com/20905638/122395124-f8ab5280-cf76-11eb-9cfd-7b51252388d8.png)

**Comment by RobertvanderHulst** [comment]
This is fixed in my current development branch.

**Comment by cpyrgas** [comment]
Confirmed fixed.
