### ISSUE TITLE
Missing DEFINE request (Win32API)

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#696]
The **GetSystemMetrics** function has a metric **SM_CXPADDEDBORDER** that X# does not have.
Please add it: `DEFINE SM_CXPADDEDBORDER := 92 AS INT`
**Documentation:** https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics

This metric allows you to solve the problem that is present in NET, starting from version 4.5 and higher:
https://stackoverflow.com/questions/14725781/getsystemmetrics-returns-different-results-for-net-4-5-net-4-0

**Comment by RobertvanderHulst** [comment]
I will review the latest Windows SDK and will add (most of) the missing defines and structures

**Comment by cpyrgas** [comment]
The original requested define was not added, but I just added it, together with a couple more. So now it's Robert that needs to confirm and close the ticket :)

**Comment by RobertvanderHulst** [comment]
Ok
