### ISSUE TITLE
No intellisense for variables in foreach

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#697]
In the following Show method I get no Intellisense inside the foreach statement for the col variable. This is the case for : and . 

![image](https://user-images.githubusercontent.com/20905638/122560433-e39af600-d040-11eb-9be3-03855ee32323.png)

**Comment by RobertvanderHulst** [comment]
The editor apparently does not properly recognize "ARRAY OF BrwColumn"

**Comment by cpyrgas** [comment]
Confirmed fixed
