### ISSUE TITLE
Problems with Scope when updating dbf from another workarea

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#699]
The following code does not works as expected:

function Start() as void
local aStruct                           as array
local oDBServer1                   as DBServer
local oDBServer2                   as DBServer
local nI                                             as dword
local nScope                          as dword
local cFileName                                 as string

nScope                                     := 22
aStruct             := {}
cFileName                    := "C:\temp\test"
FErase(cFileName + ".cdx")

DbCreate( cFileName, {{ "FIELD1", "N", 4, 0 }, { "Field2", "C", 20, 0 }}, "DBFCDX", true)
DbCreateOrder( "ORDER1",, "FIELD1")
for nI := 1 upto 10
    DbAppend()
    FieldPut( 1 , int( nI / 2 ) )
    FieldPut( 2 , NTrim( nI ) )
next
DbCloseArea()

oDBServer1                  := dbServer{ cFileName, true, false, "DBFCDX" }
oDBServer2                  := dbServer{ cFileName, true, false, "DBFCDX" }
oDBServer1:SetOrder( "ORDER1" )
oDBServer1:OrderInfo( DBOI_SCOPETOP,, "ORDER1", nScope )
oDBServer1:OrderInfo( DBOI_SCOPEBOTTOM,, "ORDER1", nScope )

oDBServer1:GoTop()
? "List is empty"
while ! oDBServer1:EoF
            ? oDBServer1:FieldGet( "Field2" )
            oDBServer1:Skip()
enddo
? "END List"

oDBServer2:Append()
oDBServer2:FieldPut( "Field1", nScope )
oDBServer2:FieldPut( "Field2", "New Value" )
oDBServer2:Commit()
oDBServer2:Unlock()

oDBServer1:GoTop()
? "List ist empty but should not"
while ! oDBServer1:EoF
            ? oDBServer1:FieldGet( "Field2" )
            oDBServer1:Skip()
enddo
? "END List"

oDBServer1:OrderInfo( DBOI_SCOPETOP,, "ORDER1", nScope )
oDBServer1:OrderInfo( DBOI_SCOPEBOTTOM,, "ORDER1", nScope )
oDBServer1:GoTop()
? "List is not empty after new Scope"
while ! oDBServer1:EoF
            ? oDBServer1:FieldGet( "Field2" )
            oDBServer1:Skip()
enddo
? "END List"

oDBServer1:Close()
oDBServer2:Close()

return

BTW. this is another sample from Andreas.

**Comment by cpyrgas** [comment]
Thanks again, problem confirmed, the scope does not update when updating it from another workarea. Simplified sample:

```
FUNCTION Start() AS VOID
LOCAL cFileName AS STRING
LOCAL nScope AS DWORD
LOCAL nI AS DWORD

nScope := 22
cFileName := "C:\temp\test"
FErase(cFileName + ".cdx")

DbCreate( cFileName, {{ "FIELD1", "N", 4, 0 }}, "DBFCDX", TRUE)
DbCreateOrder( "ORDER1",, "FIELD1")
FOR nI := 1 UPTO 5
	DbAppend()
	FieldPut( 1 , nI )
NEXT
DbCloseArea()

? DbUseArea(TRUE, "DBFCDX" , cFileName , "one" , TRUE)
? DbUseArea(TRUE, "DBFCDX" , cFileName , "two" , TRUE)

one->DbSetOrder( "ORDER1" )
one->DbOrderInfo(DBOI_SCOPETOP ,NIL ,NIL ,nScope)
one->DbOrderInfo(DBOI_SCOPEBOTTOM ,NIL,NIL , nScope)

one->DbGoTop()
? "Eof with no records in scope should be TRUE", one->Eof()

two->DbAppend()
two->FieldPut( 1 , nScope )
two->DbCommit()
two->DbUnLock()

one->DbGoTop()
? "EoF after adding appending record in scope in another workarea should be FALSE:", one->Eof()

one->DbOrderInfo(DBOI_SCOPETOP ,NIL ,NIL ,nScope)
one->DbOrderInfo(DBOI_SCOPEBOTTOM ,NIL,NIL , nScope)
one->DbGoTop()
? "EoF after setting the scope again is now TRUE as expected:", one->Eof()
? "records:"
WHILE ! one->Eof()
	? one->FieldGet( 1 )
	one->DbSkip()
ENDDO

one->DbCloseArea()
two->DbCloseArea()
```

**Comment by RobertvanderHulst** [comment]
Chris,
Your test code is broken I am afraid. You are writing 22 to workarea "two" but I think you meant to write to area "one".

**Comment by cpyrgas** [comment]
Robert, "one" and "two" refer to the same physical file. I am putting the value to "two", but this is not updated within the scope of "one". It does only when the scope is re-applied. In VO, the change in workarea "two" becomes instantly available to "one", after a skip.

**Comment by RobertvanderHulst** [comment]
Chris, you are right. I found a problem: the RDD "optimizes" Empty scopes, so it will not have to check again (checking for an empty scope may be expensive). In Shared mode this causes the RDD to not see that a new record that matches the scope was added by another user. So this "optimization" should only be applied when the file is opened exclusively.

**Comment by cpyrgas** [comment]
Confirmed fixed.
