### ISSUE TITLE
Visual Studio - Add Exiting Item does not work properly for User Control...

### ISSUE THREAD

**Issue by mattslay** [X-Sharp/XSharpPublic#7]
If you have a Winforms app Project in Visual Studio, and you have a UserControl UI component that you have coded out manually in prg files, then you right click on the Project in VS, and click "Add Exiting Item", when you choose MyControl.prg, well, the first issue is that it does not automatically add the MyControl.Designer.prg file along with it, like it does when you add an existing Form to a project.   Okay, no big deal, so I go back and click Add Existing Item again, and choose the Designer file, and it gets added as well, and VS now sees the relationship between these two files, and displays the Designer file under the prg file, so it look mostly correct, but notice the icon for the Existing Item I just added does look like the other icon for the UserControl2 which as added as a New Item action earlier in my app design. 

Since VS does not recognize these two "Existing Item" files as a proper User Control, when you double-click on it, it does not open the Visual Designer like it should.

Again, this process works fine when adding an Existing *Form*, just not when adding an Existing *UserControl*.

So, I have discovered the reason for this the icon is not correct and the reasons the Visual Designer does not open when you double-click, and it has to do with a missing element in the xsproj xml...  If I manually add the missing xml markup tag to xsproj, everything begins to work as it should!  see screenshots below.

This feature of adding an Existing Item works properly for Forms, but does not work properly for User Controls:

![image](https://user-images.githubusercontent.com/309016/56276354-ff548b80-60c7-11e9-9a2c-edc84a8bb54c.png)

After adding files to Project:
![image](https://user-images.githubusercontent.com/309016/56277132-5c047600-60c9-11e9-8f93-a7cf50c5b79d.png)

Missing XML:

![image](https://user-images.githubusercontent.com/309016/56278483-ea79f700-60cb-11e9-83e1-f00df47d2bd6.png)

So this is what it *should* look like:

![image](https://user-images.githubusercontent.com/309016/56278542-08475c00-60cc-11e9-8d37-cf38194b2cec.png)

Fixed in Visual Studio:

![image](https://user-images.githubusercontent.com/309016/56278713-5b211380-60cc-11e9-921c-3f15d53eb718.png)

Now you can double click on it, and VS will open the Visual Designer for the user control:

![image](https://user-images.githubusercontent.com/309016/56278813-8ad01b80-60cc-11e9-9876-ca0bbdff7517.png)

**Comment by RobertvanderHulst** [comment]
Matt,
When including an item in a project we are scanning the source file for the INHERIT clause and we are looking for a parent class. Whenever we find (after lowercasing)  usercontrol or system.windows.forms.usercontrol then we set the subtype to "UserControl".
Did your source file inherit from "UserControl" or from another subtype of usercontrol ?

**Comment by mattslay** [comment]
No, sir... This SampleContainerJimmy is based on another class named <something else>, which is eventually based on .Net UserControl.  It's a matter of multiple inheritance.

I am building a set of FoxPro low-level classes from which all other UI classes will be based, so as the subclassed ones are added to a project, it will be nice if it can figure out that it is a UserControl.  But, they will likely never be based on the actual base UserControl.  That's too brittle.

Here's an idea:  Maybe we could add a decorator or some other comment or markup pattern/syntax that serves as a hint to tell your system what kind of item it is ultimately based on??

Here is the current code in the prg file:

```
Begin Namespace MyNamespace
    Public Partial Class SampleContainerJimmy ;
        Inherit _vxBaseClasses._vxContainerBase
        
        Public Constructor() Strict 
            InitializeComponent()
            Return

End Class
End Namespace
```

**Comment by mattslay** [comment]
Robert - what would you think if you could look for this comment patter:

// From: UserControl

or

// From: Form

?? that could tell you what you need to know, right???

![image](https://user-images.githubusercontent.com/309016/56313394-220e9080-6118-11e9-9301-99a9d8c748f5.png)

**Comment by RobertvanderHulst** [comment]
Matt,
That all  ( decorators) won't be necessary. We should be able to lookup the parent class name and use the built-in type lookup mechanism to find if the class ultimately inherits from UserControl or Form. That should not be too difficult I think. We are also doing that when loading the form/control in the editor.

**Comment by mattslay** [comment]
Robert - do you want me to send you a zip of this project as a ready-to-test ? Or do you prefer to build your own test scenario?

**Comment by RobertvanderHulst** [comment]
Yes please

**Comment by mattslay** [comment]
Robert - Any news on fixing this issue??

**Comment by RobertvanderHulst** [comment]
Still on the todo list.
