### ISSUE TITLE
Add compiler version as constant in VersionInfo and AssemblyInfo

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#70]
In VO there is a constant for the current compiler version that can be added to the VersionInfo resource.
In X#, a similar feature would be very welcome: replace some constants with values before passing the resource to the resource compiler.
An uppercase replacement is enough.
Please see the discussion here: 
https://www.xsharp.info/forum/public-product/1309-current-compiler-version-in-versionsinfo

**Comment by RobertvanderHulst** [comment]
Inside resources there is now a #define added __VERSION__. This #define contains the version number without DOTs. So Version 2.0.2.0 will be defined as 2020.
