### ISSUE TITLE
Slow response in VS2019 / X# 2.8b with double click

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#701]
Often when I double click on some source code it takes some seconds to show the selection

I created a video, where you can see this behaviour.

![2021-06-23_15h31_10](https://user-images.githubusercontent.com/20905638/123106034-964fc780-d438-11eb-89a6-ed87269e4135.gif)

**Comment by RobertvanderHulst** [comment]
This is most likely caused by the lookup mechanism for the QuickInfo tooltips when you hover the mouse over the code.
I've made some changes to improve this

**Comment by cpyrgas** [comment]
Looks good here, but will let @hpetriffer confirm this is fixed when the new VS integration version is released.
