### ISSUE TITLE
Compiler error with PRIVATE/PUBLIC class vars defined mid class in core dialect

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#702]
In the latest compiler version (as of 2021/06/24), it is no longer possible to define PRIVATE and PUBLIC (EXPORT) class fields mid class. This was possible previously.

```
CLASS Foo
	PRIVATE pre AS INT // ok
	PUBLIC pre2 AS INT // ok

	METHOD mid() AS VOID

	PRIVATE post AS INT // error
	PUBLIC post2 AS INT // error
END CLASS

core.prg(7,18): warning XS9230: The 'AS <DataType>' clause is not supported and ignored.
core.prg(7,2): error XS9007: Feature 'Dynamic Memory Variables' is not available in the selected dialect Core
core.prg(8,18): warning XS9230: The 'AS <DataType>' clause is not supported and ignored.
core\Prg\core.prg(8,2): error XS9007: Feature 'Dynamic Memory Variables' is not available in the selected dialect Core



```

**Comment by RobertvanderHulst** [comment]
Yes, I have seen that as well. If you change PRIVATE to HIDDEN and PUBLIC to EXPORT than it works. 
There is a conflict between the PRIVATE keyword for variables and the PRIVATE modifier for instance variables.
The compiler does not know that PRIVATE starts a new entity, and thinks that it is a PRIVATE statement inside METHOD mid().
This is a side effect of supporting the `AS <type>` clause for FoxPro

**Comment by cpyrgas** [comment]
Confirmed fixed.
