### ISSUE TITLE
Problem with "1." literal expression syntax

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#704]
Starting from today's (or the previous one) build, it is no longer possible to use the following. I know, this is ugly, but it was working previously and it is actually used in the SDK code, so very likely in user code as well.

```
FUNCTION Start() AS VOID
? 2/.1 // 20.0, OK

// for all the following: error XS9002: Parser: unexpected input '/'
? 2./1 
? 2./.1
? 2.*.1
? 2.*.1
? 2.+.1

```

**Comment by RobertvanderHulst** [comment]
Aargh. I changed the compiler to also allow the code that you reported for the macro compiler  `1>2.and.3<4` but I did not think of this specific case. This will most likely also be a problem in the Macro compiler

**Comment by RobertvanderHulst** [comment]
Interesting, try the following in FoxPro:
`? 1<2.and.3<.4`
and
`? 1<2. and .3<.4`
`? 1<2 .and. 3<.4`

Foxpro allows `and `instead of `.and.`
The first line is apparently read as the line with the `.and.` operator.
That is also what our lexer does now.

**Comment by cpyrgas** [comment]
OK, that's good, actually this is what I would think is the expected behavior!
And that's compatible with VO, so that's good news, no need to implement it differently in the two dialects.

**Comment by cpyrgas** [comment]
Confirmed fixed
