### ISSUE TITLE
Renaming file/directory error in beta Version of 2.8c

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#707]
If I rename an folder or a file I get allway the following exception:
![image](https://user-images.githubusercontent.com/20905638/124225283-750d6c00-db07-11eb-974c-397fbb343f2f.png)
The foldername is valid and has no special characters. 

The old foldername was
C:\Projects\XSharp\IM.Radix.WinForms.Playground\src\WinForms\BaseGuiWF\AcsBrwbb4\Calculator
the new 
C:\Projects\XSharp\IM.Radix.WinForms.Playground\src\WinForms\BaseGuiWF\AcsBrwbb4\SummaryCalculator

The solution file is located in:
C:\Projects\XSharp\IM.Radix.WinForms.Playground

**Comment by cpyrgas** [comment]
I confirm the problem, it is reproducible also by simply changing any File1.prg to File2.prg. The solution can be located anywhere on disk.

**Comment by cpyrgas** [comment]
Confirmed fixed.
