### ISSUE TITLE
Multiple DECLARE METHOD in the same line

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#708]
*** Not urgent issue of course. I'm just working on a user request about porting a library ("WinShell" from Graham McKechnie, provides painting on Shell windows) to X# ***

VO allows DECLAREing multiple methods in the same line, while X# throws a parser error (should ignore both instead):

```
CLASS TestClass
DECLARE METHOD aaa,bbb
END CLASS

(3,19): error XS9002: Parser: mismatched input ',' expecting EOS
(3,20): error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected

```

**Comment by RobertvanderHulst** [comment]
Good catch. The rule was defined as
```
vodeclare           : DECLARE (ACCESS | ASSIGN | METHOD )  (~EOS)? eos
                    ;
```
But the question mark after the closing parenthesis should have been a +, to indicate 1 or more. The question mark indicates 0 or 1. 
This rule should match the DECLARE keyword, followed by ACCESS, ASSIGN or METHOD and then all non EOS (End Of Statement) tokens followed by an eos (which is a rule that matches one or more EOS tokens).

**Comment by cpyrgas** [comment]
Confirmed fixed.
