### ISSUE TITLE
Multiple iVars of different types declared in the same line

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#709]
*** low priority also ***

VO allows multiple declaration of (different types of) iVArs in the same line, while the X# compiler throws syntax errors.
Personally I do not like this syntax at all, very difficult to read, so I am not suggesting to support it in X#. But maybe the parser error message can be improved to point to the problem?

```
CLASS TestClass
EXPORT n,m AS INT, c AS STRING
END CLASS

error XS9002: Parser: unexpected input ','
error XS1003: Syntax error, 'Classvar Modifier (EXPORT, PROTECTED, HIDDEN, PRIVATE, PUBLIC, INSTANCE, STATIC) expected' expected
```

**Comment by RobertvanderHulst** [comment]
I checked and Vulcan does not like this too. I can change this and implement it but that will take a few hours and a lot of testing to make sure that nothing gets broken.
I think it should be supported because the following compiles as well:

```
FUNCTION start AS VOID
LOCAL n,m AS INT, c AS STRING
RETURN
```

**Comment by cpyrgas** [comment]
OK, but better let's leave it for the next build then!

**Comment by cpyrgas** [comment]
Confirmed fixed.
