### ISSUE TITLE
"Array" needed in vfp local statement to work with vfp/Fox Arrays?

### ISSUE THREAD

**Issue by lazy-fox** [X-Sharp/XSharpPublic#710]
local laLines[2]
	? laLines[1]  
	laLines[2] := 2
	? laLines[2] 
        * both outcommented versions work ok allowing 1-Dim alternate manipulation
        * but the here active one is valid vfp code as well. Suspecting Ragged Array.
        * I thought "as Array" was supposed to be creating Ragged Arrays, see Antonios
        * hint that this syntax is often used (I use it as well). If troublesome to implement,
        *  better documentation needed - 
        * to retrofix existing vfp code perhaps with special scan on code
        * or perhaps type "RaggedArray" to mark new x# Array type
	* Dimension la2Dim[2,2]
	* local Array la2Dim[2,2]
	local la2Dim[2,2]
	la2Dim[1,1] := 1
	la2Dim[1,2] := "a"
	la2Dim[2,1] := 2
	la2Dim[2,2] := "b"
	? "Row 1", la2Dim[1,1],la2Dim[1,2]
	? "Row 2", la2Dim[2,1],la2Dim[2,2] 
        *-- this barfs on local la2Dim[2,2]
	? "as 1-Dim accessed", la2Dim[1], la2Dim[2], la2Dim[3], la2Dim[4] 
        *-- this deletes existing values on local la2Dim[2,2], works with other 2 declarations
	dimension la2Dim[3,2]
	? la2Dim[1,1],la2Dim[1,2]
	? la2Dim[2,1],la2Dim[2,2]
	? la2Dim[3,1],la2Dim[3,2]

**Comment by RobertvanderHulst** [comment]
Thomas
`local laLines[2]` will create a VO style (Ragged) array
`local array laLines[2]` wlll create a FoxPro compatible array, as well as `Dimension laLines(2)`

I am not 100% sure if the `LOCAL ARRAY` is working in the build that you have. We have made some changes in the handling of this in the last weeks. We will release a new build (2.8c) tonight that supports this.

**Comment by lazy-fox** [comment]
Hi Robert,
in the minimal testing shown in the code example Local Array worked as well.
I was referring to #16781 by Antonio as follow up on his great post ticking off most peculiar vfp array behaviours.
I was not really testing, more fooling around to see if implementing alines() might run into trouble early on - had installed most versions but not really done much in code after GetWord.

**Comment by cpyrgas** [comment]
Confirmed fixed.
