### ISSUE TITLE
Ambigouos Code can be created when using Params and no warning given...

### ISSUE THREAD

**Issue by lazy-fox** [X-Sharp/XSharpPublic#713]
This is not a bug in the traditional sense - the compiled stuff does NOT anything forbidden by the logic of the code. BUT here I have found a way to create ambiguity with method signatures, resulting in code paths not determined and going against original plan. Load the source given and run with different permutations of the 2 #defines to see what I mean 

**To Reproduce**
? test_Alines()

function test_alines() as Boolean
	local array laErg[1]
	local lcExp = "Vfp alines Test String zum Zerschneiden"
	= alinesT(laErg,lcExp)
	= alinesT(laErg,lcExp, 1)
	= alinesT(laErg,lcExp, 4)
	= alinesT(laErg,lcExp, 5)
	? "Char Parameters"
	= alinesT(laErg,lcExp, 5, c'\n')
	= alinesT(laErg,lcExp, 5, c'\r')
	= alinesT(laErg,lcExp, 5, c'\n', c'\r')

	? " Parameters"
	= alinesT(laErg,lcExp, 5, Chr(10))
	= alinesT(laErg,lcExp, 5, Chr(13))
	= alinesT(laErg,lcExp, 5, Chr(10)+Chr(13))
	= alinesT(laErg,lcExp, 5, Chr(10), Chr(13), Chr(10)+Chr(13))
	return .t. 

*#define twodef
#ifdef twodef
function alinesT(aResult ref __FoxArray, cExpression as string)  as dword
	? "Parameters", 2
	return alinesT(@aResult, cExpression, 1)

function alinesT(aResult ref __FoxArray, cExpression as string, nFlags as Int32)  as dword
	? "Parameters 3 nonoptional,  nFlags", nFlags
#else
function alinesT(aResult ref __FoxArray, cExpression as string, nFlags=1 as Int32)  as dword
#endif
	? "Parameters 3 (3. optional), nFlags", nFlags
	switch nFlags 
	    case 4
    	case 5
			*-- or even better optim targeting predined switch?
			return alinesT(aResult, cExpression, nFlags, c'\n', c'\r') 
	end switch
	return alinesT(aResult, cExpression, nFlags, Chr(10), Chr(13), Chr(13)+Chr(10)) 

*#define MOREPARA
#ifdef MOREPARA
*-- Coding this way 
function alinesT(aResult ref __FoxArray, cExpression as string, nFlags as Int32, c1String as string, cParseStr params string[])  as dword
	? "Parameter 4 + Params String[]", "nFlags", nFlags
	return ALen(aResult)

function alinesT(aResult as __FoxArray, cExpression as string, nFlags as Int32, c1Char as Char, cParseChar params Char[])  as dword
	? "Parameter 4 + Params char[]", "nFlags", nFlags
	return ALen(aResult)
#else
function alinesT(aResult ref __FoxArray, cExpression as string, nFlags as Int32, cParseStr params string[])  as dword
	? "Parameter 3 + Params String[]", "nFlags", nFlags
	return ALen(aResult)

function alinesT(aResult as __FoxArray, cExpression as string, nFlags as Int32, cParseChar params Char[])  as dword
	? "Parameter 3 + Params char[]", "nFlags", nFlags
	return ALen(aResult)

*--- optimizing premature ?
function alinesT(aResult ref __FoxArray, cExpression as string, nFlags as Int32, c1Char as Char)  as dword
	? "Parameter 4", "Char"
	return ALen(aResult)

function alinesT(aResult ref __FoxArray, cExpression as string, nFlags as Int32, c1String as string)  as dword
	? "Parameter 4", "String"
	return ALen(aResult)
#endif
********************************************************************
**WANted behavior**
Is always resulting if MOREPARA is defined - no matter how state of twodef is, program ALWAYS has only a single possible method signature to select and runs the way I planned. But needing a char/string first before the params looks unelegant ;-)

****************************************************************************
If  MOREPARA is NOT defined, the call sequence is NOT what I want to be, as it only calls the function with 3 parameters from function with 2 parameters, but the next 3 calls from test_alines() happen to branch into a function with 3 Parameters plus params when given only 3 parameters. BUT: this is clearly "defensible" from compiler POV, I cannot claim the code is doing something "forbidden"! 

Dunno if ***possibility*** of such an ambiguous state should be forwarded to MS to at least fire a warning at least - but you should mention such a risc in your documentation, as my logic center only rang a faint bell when following overload scenario mentally. I hope you can describe the problem better than me if trying to document.

regards
thomas

**Comment by RobertvanderHulst** [comment]
Thomas,
I tried to understand what the problem is but I am sorry but I don't understand your example.
