### ISSUE TITLE
Cannot use typed defines as default arguments (compile error)

### ISSUE THREAD

**Issue by LeonidLevenshtein** [X-Sharp/XSharpPublic#718]
```
DEFINE TEST_DEFINE := 10 AS DWORD

CLASS TextCompiler

	STATIC METHOD doSomething(cParam AS STRING, nParam := TEST_DEFINE AS DWORD) AS VOID
	RETURN

END CLASS
```

The error is:
Error XS0182	An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type

I'm using X# 2.8c

**Comment by RobertvanderHulst** [comment]
Confirmed. We'll try to fix this for the next build. This must have been introduced when we made another change in the area of defines and/or default parameters.

**Comment by cpyrgas** [comment]
Confirmed fixed.
