### ISSUE TITLE
sporadically occurring compile error XS9019

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#721]
We have noticed that sometimes happens sporadically (sometimes more than once a day) the following error during build 

```
XSC : error XS9014: The dialect 'VO' requires a reference to the runtime DLLs XSharp.Core.DLL and XSharp.RT.DLL or VulcanRT.DLL and VulcanRTFuncs.DLL. [C:\Projects\XSharp\Radix\src\Rx1339BasW\Rx1339BasW.xsproj]
XSC : error XS9019: Compiler option 'vo5' (Implicit CLIPPER calling convention) is not supported for dialect VO [C:\Projects\XSharp\Radix\src\Rx1339BasW\Rx1339BasW.xsproj]
XSC : error XS9019: Compiler option 'vo6' (Implicit pointer conversions) is not supported for dialect VO [C:\Projects\XSharp\Radix\src\Rx1339BasW\Rx1339BasW.xsproj]
XSC : error XS9019: Compiler option 'vo7' (Implicit casts and Conversions) is not supported for dialect VO [C:\Projects\XSharp\Radix\src\Rx1339BasW\Rx1339BasW.xsproj]
XSC : error XS9019: Compiler option 'vo13' (VO Compatible string comparisons) is not supported for dialect VO [C:\Projects\XSharp\Radix\src\Rx1339BasW\Rx1339BasW.xsproj]
XSC : error XS9019: Compiler option 'vo14' (Float literal Values) is not supported for dialect VO [C:\Projects\XSharp\Radix\src\Rx1339BasW\Rx1339BasW.xsproj]
XSC : error XS9019: Compiler option 'vo15' (Allow untyped Locals and return types) is not supported for dialect VO [C:\Projects\XSharp\Radix\src\Rx1339BasW\Rx1339BasW.xsproj]
XSC : error XS9019: Compiler option 'vo5' (Implicit CLIPPER calling convention) is not supported for dialect Core [C:\Projects\XSharp\Radix\src\Rx1059BW\Rx1059BW.xsproj]
XSC : error XS9019: Compiler option 'vo6' (Implicit pointer conversions) is not supported for dialect Core [C:\Projects\XSharp\Radix\src\Rx1059BW\Rx1059BW.xsproj]
XSC : error XS9019: Compiler option 'vo7' (Implicit casts and Conversions) is not supported for dialect Core [C:\Projects\XSharp\Radix\src\Rx1059BW\Rx1059BW.xsproj]
XSC : error XS9019: Compiler option 'vo13' (VO Compatible string comparisons) is not supported for dialect Core [C:\Projects\XSharp\Radix\src\Rx1059BW\Rx1059BW.xsproj]
XSC : error XS9019: Compiler option 'vo14' (Float literal Values) is not supported for dialect Core [C:\Projects\XSharp\Radix\src\Rx1059BW\Rx1059BW.xsproj]
XSC : error XS9019: Compiler option 'vo15' (Allow untyped Locals and return types) is not supported for dialect Core [C:\Projects\XSharp\Radix\src\Rx1059BW\Rx1059BW.xsproj]
```

When I restart the compile again, the error disapears mostly (sometimes happens again on another project).
This error happens with Visual Studio and comand line (msbuild). You can open the files using https://msbuildlog.com/
[msbuild_log.zip](https://github.com/X-Sharp/XSharpPublic/files/6799852/msbuild_log.zip)

**Comment by RobertvanderHulst** [comment]
It looks like there is a problem with the "Shared" compiler that it caches some settings that it should not cache.
Most likely you can suppress this by adding/changing `<UseSharedCompilation>false</UseSharedCompilation>
` to the project file. That will make the build a bit slower but each compilation run will get its own copy of the compiler.

**Comment by cpyrgas** [comment]
I am seeing this from time to time, too. Especially when I am compiling millions of lines of different code within a few minutes, I usually do get one error in one of the programs, which always goes away the second time I try to compile it. It is so extremely rare that is impossible to (so far) to find a way to reproduce it, but I would not consider removing the /shared option, it's just not worth losing the extra speed for an error that can happen so rarely.

**Comment by hpetriffer** [comment]
Sometimes we need a few builds, because we get the error also on the second run...

**Comment by RobertvanderHulst** [comment]
Will not fix this until I have an example
