### ISSUE TITLE
Compiler error when using DECIMAL type in SWITCH statement

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#725]
The following code throws a compiler error without specifying the problematic line of code:

```
LOCAL o AS OBJECT
o := (DECIMAL)1
	
SWITCH (DECIMAL)o
CASE 1
	? "1"
CASE 2
	? "2"
CASE 3
	? "3"
END SWITCH
```

**Compiler error:** 
> XS9999 An internal compiler error has occurred: 'Arithmetic operation resulted in an overflow.', at LanguageService.CodeAnalysis.XSharp.ValueSetFactory.DecimalTC.DecimalRep.get_Value()

**Comment by RobertvanderHulst** [comment]
See also https://www.xsharp.eu/forum/private-product/2596-error-xs9999-incl-sample#19085

**Comment by leon-ts** [comment]
Robert,
Yes, this is exactly the same problem as Stefan's. Begins to appear when adding a third CASE.

**Comment by RobertvanderHulst** [comment]
Leonid,
The # of cases is not actually relevant. It is the value of 3 that triggers the problem.

**Comment by RobertvanderHulst** [comment]
The problem is caused by the fact that our CodeAnalysis DLL is compiled with overflow checking on, while the Roslyn code that we use expects to be compiled with overflow checking off.

**Comment by cpyrgas** [comment]
Confirmed fixed
