### ISSUE TITLE
"Go To Definition" capability stopped working

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#726]
"Go To Definitions" for functions stopped working in X# 2.8c (IDE: VS2019 16.10.3)

**Demo video:**
[GoToDefinitionVS2019_16_10_3.zip](https://github.com/X-Sharp/XSharpPublic/files/6817218/GoToDefinitionVS2019_16_10_3.zip)

**Comment by RobertvanderHulst** [comment]
Problem reported is:
- Goto Definition for a function in the same file does not work
- Goto Definition for a function in another file in the same projects opens the correct file but sets the cursor at line 1 and not the line where the function is.

**Comment by LeonidLevenshtein** [comment]
Confirmed, I've seen this either.
By the way, Visual Studio build 16.10.3 reports this issue to be fixed:

![image](https://user-images.githubusercontent.com/36951726/126156561-ec326dfb-f42b-423c-8f45-1970e8450d9f.png)

Though I do have this version installed and the problem persists.

**Comment by RobertvanderHulst** [comment]
I hate to admit this, but this was a problem in _OUR_ code

**Comment by cpyrgas** [comment]
Confirmed fixed.
