### ISSUE TITLE
Different color for Symbols in source code editor

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#729]
In the VO editor the color of symbols was different for symbols. In Visual Studio it is always black

VS
![image](https://user-images.githubusercontent.com/20905638/125736986-cf8fcdaf-e972-4a54-b480-7d0fbba33d19.png)
VO
![image](https://user-images.githubusercontent.com/20905638/125737095-bc16d37f-2049-49ff-88f0-a2edd1311e84.png)

A different color would help to read the code

**Comment by RobertvanderHulst** [comment]
The symbols in the VS editor get their color from the "Literal" color setting:
![image](https://user-images.githubusercontent.com/14240939/125755118-320470ab-3a07-4a77-a049-8e9a83517a66.png)
The same color is used for NIL, and the _AND, _OR, _NOT and _XOR keywords.

**Comment by RobertvanderHulst** [comment]
We also use:
- Operator
- Number 
- Keyword 
- Comment 
- String 
- Identifier for all identifiers (variable, class, method and function names)
- Excluded code for the inactive preprocessor regions
- Preprocessor Keyword 
There are 2 special XSharp colors:
- for hightlighted words
- for text .. endtext sections
-

**Comment by hpetriffer** [comment]
For the moment this is okay for me
