### ISSUE TITLE
DEFINEs hints stopped working in X# 2.8c

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#730]
If the public DEFINE is located in another project of the same solution, then hovering over it with the mouse cursor does not show Intellisense hints. An example of the project is attached.

The problem is reproduced in the **TestConsoleApplication** project (Program.prg). When you hover the mouse cursor over **MYDEFINE1** define, the tooltip is displayed, and when you hover the mouse cursor over the **MYDEFINE2** define or **MYDEFINE3** define, tooltip is not displayed. It seems that the hints only work for the first define. Also, the "Go To Definition" to these defines does not work.

Test project:
[TestConsoleApplication.zip](https://github.com/X-Sharp/XSharpPublic/files/6820940/TestConsoleApplication.zip)

P.S. When I prepared a test project, it turned out that hints were no longer displayed even for the first MYDEFINE1 define.

**Comment by cpyrgas** [comment]
Confirmed fixed.
