### ISSUE TITLE
Intellisense stopped showing list of VOSTRUCT members in X# 2.8c (VS2019)

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#731]
**Code sample:**
```
VOSTRUCT MYSTRUCT
	MEMBER nParam AS INT
	MEMBER lParam AS LOGIC

FUNCTION Start() AS VOID STRICT

	LOCAL st IS MYSTRUCT
	st. // After typing a dot, nothing happens.

	RETURN
```

**Comment by RobertvanderHulst** [comment]
Leonid,

Does it work when you type a colon ?

**Comment by leon-ts** [comment]
Robert,
Yes, after typing the colon character the list of VOSTRUCT members is displayed.

**Comment by RobertvanderHulst** [comment]
I will restore the VO compatible behavior (that the "." operator shows members of VOSTRUCT and UNION) in the next build.

**Comment by cpyrgas** [comment]
Confirmed fixed.
