### ISSUE TITLE
Wrong Autoformatting during editing leads to compile error

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#732]
The following code will be automatically corrected during save
from
```
if (Enum:IsDefined(typeof(OdbcDataType), nODBCType))
```

to
```
if (enum:IsDefined(typeof(OdbcDataType), nODBCType))
```

If you compile now the project you get an error:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	XS0103	The name 'enum' does not exist in the current context	AcsSQL	C:\Projects\XSharp\AcsLib\src\AcsSQL\Helper\ParametersHelper.prg	75	
```

- Setting is "keyword case syncronization" lower
- editor.config  with
```
# All files
[*.prg]
indent_style = space
tab_width=3
indent_size=3
trim_trailing_whitespace=true
```

**Comment by RobertvanderHulst** [comment]
Apparently the editor has recognized Enum as a keyword and changed the case to lowercase. Are you compiling in case sensitive mode ?
I'll have to fix this in the lexer to make sure that the Enum keyword is not treated as a keyword when it is part of an expression but as an Identifier.

**Comment by hpetriffer** [comment]
This project is compiled in case sensitive modus

**Comment by RobertvanderHulst** [comment]
Hans Joerg,
There is also a problem in your code.
You are calling the IsDefined method of the Enum type. This is a STATIC method but you are using the `':'` operator.
The compiler is now looking for a local or field with the name 'enum'.
That is why it reports:
`Error	XS0103	The name 'enum' does not exist in the current context`
If you change the colon  `':' ` to a dot `'.'` then it knows that the left hand side of the expression can also be a type.

**Comment by hpetriffer** [comment]
you are right. Strange that with "Enum" it is not a compile error

**Comment by cpyrgas** [comment]
Hmm, that's very strange, indeed currently the compiler allows calling static members with the ":" operator, this also compiles and runs with no errors!

? System.Windows.Forms.Form:ActiveForm

This should be a compiler error instead. PS, cule did use this (and only this) syntax for calling static members!

**Comment by cpyrgas** [comment]
Confirmed fixed. Note that in this case:

```
    LOCAL enum AS INT // OK
    enum := 1 // this does get higlited and changed to ENUM
    IF enum == 1 // OK
    ENDIF
```

in the second line "enum" still does get converted to ENUM, but I think this is not a problem.
