### ISSUE TITLE
VODBAlias function returns NULL instead NULL_STRING

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#733]
The **VODBAlias** function in VO returns NULL_STRING if the workarea number passed is invalid (does not exist). This behavior is documented, including X#. But actually X# returns NULL in this situation. As a result, in already existing programs, where the result of the **VODBAlias** function is checked against NULL_STRING, the check fails.

P.S. NULL_STRING = empty string "" (/vo2)

**Comment by RobertvanderHulst** [comment]
The function (Actually the Workareas.GetAlias() method) now returns String.Empty in these cases.

**Comment by cpyrgas** [comment]
Confirmed fixed.
