### ISSUE TITLE
Difference in the size of structures in VO and X#

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#734]
In VO, the final structure size is determined taking into account the alignment described in the documentation: _STRUCTURE Statement (paragraph "Default Structure Alignment")_.

In applications transferred from VO to X#, in some cases, the sizes of the structures do not match. This causes problems, for example, when some binaries were created in VO over some structures. When reading these files in X#, the file pointers are offset incorrectly, because the size of the structure substituted during reading does not match the one with which the file was created.

**Code sample:**
```
FUNCTION Start() AS VOID STRICT

	? "EXCHG_PROTOCOL_HEAD: X# = " + _SIZEOF(EXCHG_PROTOCOL_HEAD):ToString() + ", VO = 28"
	? "EXCHG_PROTOCOL_DPT: X# = " + _SIZEOF(EXCHG_PROTOCOL_DPT):ToString() + ", VO = 16"
	? "EXCHG_PROTOCOL_RECORD: X# = " + _SIZEOF(EXCHG_PROTOCOL_RECORD):ToString() + ", VO = 28"
	WAIT

	RETURN

VOSTRUCT EXCHG_PROTOCOL_HEAD
	MEMBER DIM cPrefix[15] AS BYTE
	MEMBER nVersion AS DWORD
	MEMBER Creation IS VO._WINFILETIME

VOSTRUCT EXCHG_PROTOCOL_DPT
	MEMBER nCode1 AS INT
	MEMBER nCode2 AS INT
	MEMBER DIM cDptID[6] AS BYTE

VOSTRUCT EXCHG_PROTOCOL_RECORD
	MEMBER nType AS DWORD
	MEMBER Dpt IS EXCHG_PROTOCOL_DPT
	MEMBER cbSize AS DWORD
	MEMBER DIM bData[1] AS BYTE
```

**Result:**
> EXCHG_PROTOCOL_HEAD: X# = 28, VO = 28
> EXCHG_PROTOCOL_DPT: X# = 14, VO = 16
> EXCHG_PROTOCOL_RECORD: X# = 25, VO = 28

**Comment by RobertvanderHulst** [comment]
The VO docs say:
The total size of the structure is aligned to the size of the largest member. This is done to make sure that a dim array of structures (multiple structures adjacent in memory) also align properly 
We have apparently now applied that rule. We will fix that.

**Comment by leon-ts** [comment]
Robert,
Please also note that if you explicitly specify alignment in the structure using the ALIGN keyword, then ALIGN 1 in X# works correctly. But if you specify, for example, ALIGN 4, then in X# it has no effect.

**Comment by RobertvanderHulst** [comment]
Leonid,
I will review all of the code that calculates the size and alignment of vostructs and unions and make sure that it works just like in VO.

**Comment by leon-ts** [comment]
Robert,
Let me suggest some simple structures in this ticket to test. One of them was offered by Chris on another ticket.

1. **_struct1**: the fields with the maximum size are **a** and **b** (4 bytes). Therefore, the memory alignment must be a multiple of 4. The actual size of the **_struct1** structure is 12 bytes. This value is a multiple of 4. Therefore, no additional expansion is required and the VO-compatible size of the **_struct1** structure must be **12**.
```
VOSTRUCT _struct1
	MEMBER a AS LONG
	MEMBER b AS DWORD
	MEMBER c AS WORD
	MEMBER d AS SHORT
```

2. **_struct2**: the fields with the maximum size are **a** and **b** (4 bytes). Therefore, the memory alignment must be a multiple of 4. The actual size of the **_struct2** structure is 13 bytes. This value is not a multiple of 4. The closest larger multiple of 4 is 16. Therefore, an additional extension (+3 bytes) is required and the VO-compatible size of the **_struct2** structure must be **16**.
```
VOSTRUCT _struct2
	MEMBER a AS LONG
	MEMBER b AS DWORD
	MEMBER c AS WORD
	MEMBER d AS SHORT
	MEMBER e AS BYTE
```

3. **_struct3**: the field with the maximum size is **a** (8 bytes). Therefore, the memory alignment must be a multiple of 8. The actual size of the **_struct3** structure is 11 bytes. This value is not a multiple of 8. The closest larger multiple of 8 is 16. Therefore, an additional extension (+5 bytes) is required and the VO-compatible size of the **_struct3** structure must be **16**.
```
VOSTRUCT _struct3
	MEMBER a AS REAL8
	MEMBER b AS WORD
	MEMBER DIM c[1] AS BYTE
```

**Comment by cpyrgas** [comment]
Confirmed fixed.
