### ISSUE TITLE
Some peculiarities of the MExec function behavior

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#737]
The **MExec** function has a difference in behavior in X# and VO when a compiled expression that returns a CODEBLOCK is passed into it.

**Code sample:**
```
LOCAL cS AS STRING
LOCAL cbCompiledS AS CODEBLOCK // AS STRING in VO
LOCAL uResult AS USUAL
	
cS := "{|| STR(MY_DB_FIELD,1) }"
cbCompiledS := MCompile(cS)
uResult := MExec(cbCompiledS)
```

The workarea containing the MY_DB_FIELD field is not open yet. That is, the codeblock is pre-created before the opening of the workarea, in which it will be evaluated.
In VO, the MExec function does not generate an error, but "sees" that the code is a codeblock, creates it, and returns it to the calling program.
In X#, the MExec function throws an exception that the variable does not exist (as I understand it about MY_DB_FIELD).

**Comment by RobertvanderHulst** [comment]
Leonid,
What I see in VO is that:
- MCompile(cS) returns a string
- MExec(cbCompiledS) returns a _Codeblock
- Eval(uResult) throws the error when the table is not open

What we are doing in X# is
- MCompile(cS) already returns a _CodeBlock
- MExec() tries to evaluate the codeblock and throws the error
I will see if I can 'teach' MExec() to not evaluate the codeblock.
It will be difficult to make MCompile() return a string

**Comment by leon-ts** [comment]
Robert,

> Eval(uResult) throws the error when the table is not open

Yes, if you then call Eval when there is no workarea with the corresponding field, then an error occurs. And it is right. The question is precisely in the MExec function, when a codeblock is passed to it, which also generates a codeblock. It shouldn't crash, but should return the nested codeblock. This is how it worked in VO and this feature is used by existing programs.

> It will be difficult to make MCompile() return a string

This is not necessary. We have already successfully translated the VO code to X#, replacing the compiled codeblocks from STRING to CODEBLOCK. This works great and is even faster than VO!

**Comment by RobertvanderHulst** [comment]
Leonid,
Add this to your own project for now to solve the problem until you get the new runtime:

```
FUNCTION MExec(oBlock AS CODEBLOCK) AS USUAL
IF oBlock IS XSharp._Codeblock VAR cb .AND. cb:IsBlock
    RETURN oBlock
ENDIF
RETURN Eval(oBlock)
```

**Comment by leon-ts** [comment]
There the idea is that the MCompile function creates a codeblock, which creates another codeblock. If you look at my sample code above , then cbCompiledS contains code that can create a codeblock of the folowing type: "{|| STR(MY_DB_FIELD,1) }". And when the MExec(cbCompiledS) function is executed, a new codeblock is created, described in cbCompiledS.

**Comment by leon-ts** [comment]
Robert,

> Add this to your own project for now to solve the problem until you get the new runtime:

I'm not sure if this code is returning the correct result. In fact, it just returns a copy of the codeblock passed to it. In reality, a new codeblock should be created with different variable addresses. I'll give you a more visual example to show how this code works in VO. To do this, I will give its analogue without using MCompile/MExec:

```
LOCAL cS AS STRING
LOCAL cbCompiledS AS _CODEBLOCK
LOCAL uResult AS USUAL

cS := "{|| {|| STR(MY_DB_FIELD,1) } }" // Codeblock nested in another codeblock
cbCompiledS := &cS // Here we got the codeblock that when executed, can creates new codeblocks of the form {|| STR(MY_DB_FIELD,1) }
uResult := Eval(cbCompiledS) // New codeblock of the form {|| STR(MY_DB_FIELD,1) }
Eval(uResult) // Error. And it is right.
```

**Comment by leon-ts** [comment]
Robert,
I researched the issue further and ran some tests. Basically, if the _Codeblock type is immutable, then your proposed fix will not differ in behavior with VO. In the initial example, the MExec function in VO creates a new codeblock each time, so it always takes STRING as a parameter. That is, it has no choice but to create new objects. But in X#, the MCompile function and the MExec function initially work with codeblocks. I only worried about the immutability of the codeblock object to match the VO behavior.

**Comment by RobertvanderHulst** [comment]
Leonid,
At this moment the properties of the _CodeBlock class are not immutable.
For the next build I will make all of the properties INITONLY which makes the object immutable.

**Comment by RobertvanderHulst** [comment]
Implemented in f66a2ca815d9524b66d695a8805ec9b433e8b57f

**Comment by leon-ts** [comment]
Robert,
There is a suggestion for a small optimization. But to be honest, it can lead to some inconvenience in the application code. So I'll just leave it here as an idea for your consideration.

The MCompile and MExec functions are designed to work in pairs. At least that's how they were conceived in VO. Considering this, as well as the fact that in X# the MCompile function always returns the _Codeblock type (with an underscore at the beginning of the name), then the oBlock parameter in the MExec function can also be made of the _Codeblock type instead of CODEBLOCK. Then in the body of the MExec function there will be no need to check for `IF oBlock IS XSharp._Codeblock VAR cb`.

**Comment by leon-ts** [comment]
Addition to my previous post on optimization.
A better solution would probably be to simply add an overload for the MExec function.

For example:
```
FUNCTION MExec(oBlock AS CODEBLOCK) AS USUAL // original MExec
	IF oBlock IS XSharp._Codeblock VAR cb .AND. cb:IsBlock
		RETURN oBlock
	ENDIF
	RETURN Eval(oBlock)

FUNCTION MExec(oBlock AS _CODEBLOCK) AS USUAL // overloaded MExec
	IF oBlock:IsBlock
		RETURN oBlock
	ENDIF
	RETURN Eval(oBlock)
```

**Comment by RobertvanderHulst** [comment]
Leonid,
Thanks for the suggestion. However this will only work if the local variable is declared as _CODEBLOCK .
If the variable is declared as CODEBLOCK then the overload with the CODEBLOCK parameter will be called and if the local variable is declared as USUAL then the same overload will be called because USUAL has an implicit conversion operator for CODEBLOCK and not for _CODEBLOCK.

**Comment by leon-ts** [comment]
Robert,
Totally agree with you. Function overloading in this particular case will not play a special role, and may even confuse programmers.

I already thought, maybe you just need to write in the documentation for the MExec function that it is recommended to use the Eval function instead of MExec to improve performance? Let me explain what I mean. The VO docs say that the MCompile/MExec function pair is recommended for better performance than using Eval. But in X#, the MExec function essentially calls Eval. Therefore, in X#, after MCompile, it is better for perfomance call Eval instead of MExec. Otherwise, the VO programmers may not know that the MExec function in X# is just a wrapper over the Eval function.

**Comment by RobertvanderHulst** [comment]
Leonid,
That is a good suggestion.
As you know, or have seen, most of the documentation from the VO compatible functions has been "lifted" out of the VO Docs. So the original recommendations and comments were kept.
In this case I think it would be a good idea to update the docs.
Where did you see that MCompile/MExec is recommended ?

**Comment by leon-ts** [comment]
> Where did you see that MCompile/MExec is recommended ?

Robert,
Here is a quote from the VO documentation on the MExec function (the same quote is in the MCompile description):
> MExec() evaluates an expression that was previously macro-compiled.  Instead of  invoking the macro compiler each time an expression is evaluated, you could speed up your application by compiling an expression only once and executing the 
> compiled result as often as desired.

**Comment by leon-ts** [comment]
In the VO documentation, this text is located in the **Description** section, and in the X# documentation, in the **Remarks** section.

**Comment by leon-ts** [comment]
It does not explicitly say about the Eval function, but in VO the Eval function cannot receive the result of the MCompile function (compiled data of the STRING type). Therefore, it is implicitly implied that instead of using the creation of codeblocks and their execution using Eval, it is proposed to use the MCompile/MExec pair to increase the speed.
