### ISSUE TITLE
Some bugs in the VO-window editor

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#741]
1. The **RadioButton** control does not respond to toggling the **Multiline** property.
2. If the **Caption** property contains text in the resource format `(<'DefaultText',ID,HMODULE>)`, then when testing the window view, it is not converted to the default text. In addition, the text of the **CheckBox** resource is displayed along with the default text in the test window. 
![Screenshot1](https://user-images.githubusercontent.com/64518775/126616437-80c42e5a-f6c3-40da-997c-6c2b7eb7e638.png)
3. If the text in the **CheckBox** is not a resource, then in the test window it looks like this: 
![Screenshot2](https://user-images.githubusercontent.com/64518775/126616832-83244150-29d7-46dc-8593-f08c08c1a441.png)

**Comment by cpyrgas** [comment]
Thanks, all problems confirmed, will look into them.

**Comment by cpyrgas** [comment]
All fixed.
