### ISSUE TITLE
Sometimes opening files in solution results to an "empty" file

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#742]
Since version 2.8b it seems that sometimes opening a file from solution explorer results to an empty not editable file in the editor. 

In this case the file is always already open and the new "view code" event seems to open an new tab. If I close both tabs, then the next "view code" works as expected.
It happens about 5 times a day

**Comment by hpetriffer** [comment]
I'm not sure, but I think mostly it happens when Visual Studio is opened with a solution and the file is already opened. Now when the file is opened again the error happens

**Comment by RobertvanderHulst** [comment]
We are making some changes in this area for the next build.
We are changing parts of the VS integration to use https://github.com/VsixCommunity/Community.VisualStudio.Toolkit which offers support for several common VS tasks in a thread friendly way.

**Comment by cpyrgas** [comment]
Hansjoerg, can you please confirm if this is fixed now?

**Comment by hpetriffer** [comment]
I have tested it a minute ago and the error is also in this version (see the StatusBar file):
![image](https://user-images.githubusercontent.com/20905638/142625063-5053a9e6-8a8b-4846-8d01-742e12df0d33.png)
The file is opened 2 times and it is not possible to find something in this file

**Comment by cpyrgas** [comment]
How did you open the file? Both times from the solution explorer? Or maybe one time was from the search results or some other window? I think I remember having seen some strange behavior like that in the past

**Comment by hpetriffer** [comment]
It seems to not make any difference. I have tested it with both options -> same error.

**Comment by RobertvanderHulst** [comment]
Does this still happen?

**Comment by hpetriffer** [comment]
No. It does not happen anymore
