### ISSUE TITLE
Intellisense doesn't show constructor parameter hints (X# 2.8c)

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#744]
When typing code after entering an opening curly brace after the class name, Intellisence VS2019 does not show the class constructor parameters, as well as the signatures of its overloads (if any).

**Sample:**
```
LOCAL oTime AS DateTime
oTime := DateTime{ // nothing happens

LOCAL oStream AS System.IO.FileStream
oStream := System.IO.FileStream{ // nothing happens
```

**Comment by RobertvanderHulst** [comment]
Confirmed and fixed.

**Comment by cpyrgas** [comment]
Confirmed fix.
