### ISSUE TITLE
Intellisense doesn't correctly recognize classes that have nested classes

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#745]
There are the following class:
```
STATIC CLASS Class1

	STATIC METHOD DoSomething() AS VOID STRICT
		RETURN

	STATIC CLASS SubClass1

		STATIC METHOD DoSomething() AS VOID STRICT
			RETURN

	END CLASS

END CLASS
```

If type a dot symbol in the code after the class name, then its members are not displayed:
```
FUNCTION Start() AS VOID STRICT
	Class1. // nothing happens
	RETURN
```

If hold the mouse cursor over class name, a hint will be displayed that it is "NAMESPACE Class1" instead of a hint that this is a class.
![Screenshot1](https://user-images.githubusercontent.com/64518775/127295411-c44daaac-ab56-4a21-ab53-f487ffe9b7c3.png)

**Comment by cpyrgas** [comment]
Confirmed fixed
