### ISSUE TITLE
Feature request: Coloring keywords in Intellisense hints

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#748]
When VS2019 Intellisense displays function and method hints (on mouse hover), data type keywords are not colored with the same color as in the editor. This slightly reduces the readability of the entity signature.

![Screenshot1](https://user-images.githubusercontent.com/64518775/127610118-438b8d43-ec39-4c5f-9535-5b2949a9f442.png)

**Comment by RobertvanderHulst** [comment]
Leonid,
I'll see what I can do.

Robert
