### ISSUE TITLE
Intellisense doesn't show function parameters after type "ARRAY OF ..."

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#749]
If one of the function parameters is of type "ARRAY OF", then Intellisense does not display the function parameters following it. Neither when typing a parenthesis, nor when hovering the mouse cursor over a function.

**Code example:**
```
FUNCTION Start() AS VOID STRICT
	MyFunc( // Shows MyFunc(nParam AS INT, aParam AS ARRAY)
	RETURN

FUNCTION MyFunc(nParam AS INT, aParam AS ARRAY OF INT, cParam AS STRING, oParam AS OBJECT) AS VOID STRICT
	RETURN
```

**Screenshot (when typing a parenthesis):**
![Screenshot1](https://user-images.githubusercontent.com/64518775/127989599-2f7b79e0-1915-4182-88cc-0d064fba1318.png)

**Screenshot (when hovering the mouse cursor):**
![Screenshot2](https://user-images.githubusercontent.com/64518775/127989824-25eab0ad-5208-405f-b677-6f7c897761de.png)

**Comment by cpyrgas** [comment]
Confirmed.

**Comment by cpyrgas** [comment]
Confirmed fixed
