### ISSUE TITLE
Namespace is incorrectly defined in self-hints

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#754]
If the name of a method coincides with an existing name in another library, for example, in XSharp.RT, then when you hover the cursor over the name of the method in the place of its definition, VS Intellisense displays a hint for the function of the same name in another library, instead of its own description.

**Screenshot:**
![Screenshot1](https://user-images.githubusercontent.com/64518775/128519715-6d9745b5-54d8-4bf5-bae8-76068e37a61c.png)

**Sample code:**
```
BEGIN NAMESPACE MyNamspace
	STATIC CLASS MyClass
		/// <summary>Description of the DbCloseAll method of the MyClass class.</summary>
		STATIC METHOD DbCloseAll() AS VOID
			RETURN
	END CLASS
END NAMESPACE
```

P.S. The problem is very minor, since looking at the hints at the location of the entity definition might seem pointless. But in some cases, for example, it is so convenient to check whether the XML documentation is correctly formatted (summary, remarks, and so on).

**Comment by RobertvanderHulst** [comment]
Leon,
Are sure that when you call DbCloseAll() inside the code of MyClass, that it actually calls MyClass.DbCloseAll() and not the DbCloseAll() function. The compiler should give preference to functions (and so does the intellisense) over methods in the same class when they are not prefixed with SELF: or with the classname.

**Comment by leon-ts** [comment]
Robert,
Yes, I always specify the class name for static methods, and SELF for instance methods. So they cannot be confused with functions, and Intellisence is also available for selecting a method from the list. But thanks for the helpful comment. It will never be superfluous to check.

**Comment by cpyrgas** [comment]
Robert, actually for static methods, the compiler seems that it gives priority to the static method inside the same class, not to the external function. But this (very small indeed) intellisense problem happens also when hovering over the static method declaration itself, not only when hovering over the method call.

**Comment by RobertvanderHulst** [comment]
This also solves the problem that when there are overloads it would show the quickinfo for the first overload, even when you were inside the second overload. It will now return the quickinfo for the current overload:
![image](https://user-images.githubusercontent.com/14240939/215529429-cdb776a6-4ef0-467f-abe2-5b62d57fef51.png)

**Comment by cpyrgas** [comment]
Seems still a bit problematic, no showstopper by any means, but try this

FUNCTION MyTest()
    NothingHere.DBCloseAll()

if you hover over "DBCloseAll()", you still get an incorrect tooltip for the DBCloseAll() function in XSharpRT

**Comment by RobertvanderHulst** [comment]
I am really surprised that you see this. The Language Service only seeks functions when the cursor over an identifier that is the "start of an expression". And the DOT character in front of it sets the "startOfExpression" state to FALSE.

**Comment by RobertvanderHulst** [comment]
But I found it!

**Comment by cpyrgas** [comment]
COnfirmed fixed
