### ISSUE TITLE
Looping around the definition of constants confuses the compiler

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#755]
The following code causes problems in the X# compiler:
```
STATIC CLASS Class1
	PUBLIC CONST MyConst := Class1.MyConst AS STRING
END CLASS
```
The compiler displays a message that does not indicate an error, and when you double-click it, it goes to the wrong place at all.
> MSB4181 The "Xsc" task returned false but did not log an error.

P.S. I got the error on a real project (names have been changed).
The MyConst field looked like this:
`MyConst: = "MYCONST" AS STRING`
Then I did a bulk change of the text "MYCONST" to Class1.MyConst throughout the project. And I didn't notice how the text in the definition of MyConst was also replaced. Then the compiler started giving an error, and I found it with some difficulty.

**Comment by cpyrgas** [comment]
Confirmed, compiler crashes with a StackOverflowException.

**Comment by cpyrgas** [comment]
Confirmed fixed
