### ISSUE TITLE
Intellisense problem with non existent namespace

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#760]
In the following code, member list shows some members of a non existent namespace, while there should be no list at all:

BEGIN NAMESPACE MyNamespace
	STATIC CLASS MyClass
		STATIC METHOD Test() AS VOID
            SomethingRandom.
			RETURN
	END CLASS
END NAMESPACE

![NoNamespace_intellisense](https://user-images.githubusercontent.com/14542129/129081305-23f51e07-8daf-4954-976e-25474b8f401d.png)

**Comment by Serggio** [comment]
That happens every time when intellisence engine cannot find identifier that is on the left of a dot. Instead It shows a completion list for current class or something like that, which is of course wrong.
