### ISSUE TITLE
VS crash when alt+trabbing out of the VOWED editor

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#764]
In the VOWED editor, select any control and in the Properties window select a property that drops down and allows editing, like the Inherit From, Fieldspec etc properties. Make sure that the (empty for now) combobox is dropped down and press Alt+Tab to move to another app, now VS crashes. Same problem exists also in XIDE.

**Comment by cpyrgas** [comment]
Should be fixed now, I also fixed it in XIDE.

**Comment by RobertvanderHulst** [comment]
Fixed
