### ISSUE TITLE
Implementation of interfaces must be case sensitive, regardless of project settings

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#765]
It seems that the implementation of interfaces must be case sensitive, also if it is not set in the project settings

```
class Test implements ITest
property oImagelist as object get _oimageList
end class

interface ITest
   property oImageList as object get
end interface
```

In this case you get the error 
`Test ' does not implement interface member 'ITest.oImageList'. 'Test .oImagelist' cannot implement 'ITest.oImageList' because it does not have the matching return type of 'object'`

**Comment by cpyrgas** [comment]
Confirmed fixed (remains a compiler error, but with a better error message)
