### ISSUE TITLE
Late-bound method calls and OUT parameters

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#771]
When calling late-bound methods in X# (2.8c), OUT parameters do not return values to the calling code.
```
FUNCTION Start() AS VOID STRICT

	LOCAL oOwner AS OBJECT
	
	oOwner := TestClass{}
	oOwner:DoSomething(1, OUT cNum AS STRING)
	? cNum // empty instead "1"
	
	RETURN

CLASS TestClass
	METHOD DoSomething(nNum AS INT, cNum OUT STRING) AS VOID STRICT
		cNum := nNum:ToString()
		RETURN
END CLASS
```
I don’t know if this is supported in X#, but during the execution of this code I didn’t give an error, but returned an empty value in cNum. The type of the parameter does not matter. Any OUT parameter in such an example will return its empty value.

**Comment by RobertvanderHulst** [comment]
This apparently is an error in the Late bound code in the runtime.
However when compiling this with a debug version of the compiler I am also getting assertions, so there may also be a problem in the compiler...

**Comment by cpyrgas** [comment]
Confirmed fixed.
