### ISSUE TITLE
X# allows comparison of a DateTime structure with NULL_OBJECT

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#772]
The following code does not throw a compiler error on the "`IF (oDateTime != NULL_OBJECT)`" line:
```
FUNCTION Start() AS VOID STRICT
	TestFunc( DateTime.MinValue )
	RETURN

FUNCTION TestFunc(oDateTime AS DateTime) AS VOID
	IF (oDateTime != NULL_OBJECT)
		? oDateTime:ToString()
	ENDIF
	RETURN
```
Given that the DateTime type is a structure and cannot be NULL or NULL_OBJECT.

**Comment by RobertvanderHulst** [comment]
This seems to be allowed in C# too. Try the following:

```
namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            TestFunc(DateTime.MinValue);
        }
        static void TestFunc(DateTime oDateTime )
        {
            if (oDateTime != null)
            {
                Console.WriteLine( oDateTime.ToString());
            }
        }
    }
}
```
I checked the Roslyn code, and when you compare a DateTime with a null then it finds the operator that compares a DateTime with a Nullable<DateTime>.  That is why this is allowed.

**Comment by cpyrgas** [comment]
Robert, wow, you are right, although I think this is really bad (that c# allows it, especially since it's such a very hard on the rules language). When comparing an INT with a NULL, at least both c# and X# report a "warning XS0472: The result of the expression is always 'false' since a value of type 'int' is never equal to 'null' of type 'int?'", which is helpful.

I understand why there's no warning when comparing with DateTime. I do not like it, but I guess there's indeed nothing we can do about it.

**Comment by leon-ts** [comment]
Guys,
I didn’t know that C# allowed this too. If so, then this ticket can be closed.

P.S. I ran into this problem when I was transporting VO code that used the AdoDateTime class. The code has checks for AdoDateTime instances with NULL_OBJECT. In X#, I replaced AdoDateTime with DateTime and the checks escaped my attention. And the compiler did not prompt, and there were no errors in the runtime. As a result, the checks did not work correctly (found in debugging).

**Comment by RobertvanderHulst** [comment]
Chris,
If there is indeed a message for comparing an int with null then I will create some test code to see if I can do something similar for DateTime

**Comment by cpyrgas** [comment]
Re-opening this, since there's indeed no warning for comparing DateTime <> NULL, while there does exist a warning for comparing INT <> NULL. (Same behavior with c#):

```
// warning XS0472: The result of the expression is always 'false' since a value of type 'int' is never equal to 'null' of type 'int?'
FUNCTION Start() AS VOID
? 1 == NULL
? NULL == 1

```

**Comment by RobertvanderHulst** [comment]
If you compile with the option /warn:n and set n to a value of 5 then the warnings for the DateTime will be shown.
I will change the default for the compiler to compile with warning level 5

**Comment by cpyrgas** [comment]
Confirmed, the warning does show also for DateTime with warning level 5!
