### ISSUE TITLE
Create _WinDate structure that stored Date values in a VO struct just like VO does.

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#773]
See #735

**Comment by leon-ts** [comment]
Wow, great!

**Comment by leon-ts** [comment]
Robert,
There are new errors:

```
LOCAL nDays AS DWORD
LOCAL ts IS TEST_STRUCT
	
nDays := 10
ts.dDate := Today()
ts.dDate += ( nDays - 1 ) // Error XS0034 Operator '+=' IS ambiguous ON operands OF type 'XSharp.__WinDate' and 'dword'
ts.dDate -= ( nDays - 1 ) // Error XS0034 Operator '-=' IS ambiguous ON operands OF type 'XSharp.__WinDate' and 'dword'
ts.dDate += 1 // Error XS0029 Cannot implicitly convert type 'int' TO 'XSharp.__WinDate'
ts.dDate -= 1 // Error XS0029 Cannot implicitly convert type 'int' TO 'XSharp.__WinDate'
ts.dDate++ // Error XS0035 Operator '++' is ambiguous on an operand of type 'XSharp.__WinDate'
ts.dDate-- // Error XS0035 Operator '--' is ambiguous on an operand of type 'XSharp.__WinDate'
	
LOCAL dStart, dEnd AS DATE
dStart := Today()
dEnd := dStart
	
FOR ts.dDate := dStart UPTO dEnd // Error XS0029 Cannot implicitly convert type 'int' TO 'XSharp.__WinDate'
NEXT
```

**Comment by cpyrgas** [comment]
I am sure there are more. The code in the asbau project used that as well.

**Comment by RobertvanderHulst** [comment]
Leonid,
For now add a (DATE) cast in front of the Right Hand Side of the expression.
`ts.dDate := (DATE) u`
This will be fixed asap.

The LOGIC text in the debugger is a copy/paste error and very easy to fix.

**Comment by RobertvanderHulst** [comment]
Leonid,
Can you confirm that this works, with the exception of the assignment of the usual to the __WinDate element ?

**Comment by cpyrgas** [comment]
Robert, all the issues mentioned here https://github.com/X-Sharp/XSharpPublic/issues/773#issuecomment-938538992 still exist

**Comment by leon-ts** [comment]
Robert,
I have nothing to add to what Chris said. The errors I mentioned in the section "There are new errors" remained in the new 2.9 compiler.

**Comment by cpyrgas** [comment]
Confirm fized

**Comment by leon-ts** [comment]
Robert,
It works well now!
