### ISSUE TITLE
Strange problem with long filenames and DBF indexes

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#774]
This is an old issue. When using a filename with character length > 10, then an exception is thrown. When using 10 chars or less for the filename, then it runs fine! Also in VO it runs without errors (and with expected results), no matter the filename. I admit I am not really sure what's supposed to happen with the already existing cdx file (and why in VO it works fine), but in any case it is really starnage that the error happens only for longer filenames.

```
FUNCTION Start() AS VOID STRICT
	LOCAL cDbf AS STRING

	cDbf := "c:\test\A123456789" // with filename with 10 chars it works fine!
	cDbf := "c:\test\A1234567890" // 11 characters cause the error to happen!!!
	FErase(cDbf + ".cdx")

	? "first run..."
	DoTest(cDbf) // no error
	? "second run..."
	DoTest(cDbf) // exception in the next time

PROCEDURE DoTest(cDbf AS STRING)
	LOCAL n AS INT
	DbCreate(cDbf  , {{"FLD" , "N" , 3 , 0}})
	DbUseArea(TRUE,"DBFCDX", cDbf, , TRUE)
	DbCreateIndex(cDbf,"FLD")
	FOR n := 1 UPTO 5
		DbAppend()
		FieldPut(1,n % 3)
	NEXT	
	DbGoTop()
	? "indexed records:"
	DO WHILE ! Eof()
		? FieldGet(1), RecNo()
		DbSkip()
	END DO
	DbCloseArea()
	
	? "...finished"
RETURN
```	

```
Description :	Error performing action CdxAction: InsertKey PageNo: A00 PageNo2: FFFFFFFF Pos: 8 Recno: 2 ChildPage: FFFFFFFF Key: ........ for c:\test\A1234567890.CDX A123456789
Subsystem :	DBFCDX
GenCode :	EG_CORRUPTION Corruption detected
SubCode :	1106 Create indexfile
FuncSym :	DbGoTop
Severity :	ES_ERROR
Can Default :	True
Can Retry :	False
Can Substitute :	False
FileName :	c:\test\A1234567890.DBF
Stack Trace :	
CDXTAG:_UPDATEERROR (Line: 28)
CDXTAG:DOACTION (Line: 136)
CDXTAG:_KEYUPDATE (Line: 827)
CDXTAG:GOCOLD (Line: 334)
CDXORDERBAG:GOCOLD (Line: 337)
CDXORDERBAGLIST:GOCOLD (Line: 201)
DBFCDX:GOCOLD (Line: 619)
CDXTAG:GOTOP (Line: 98)
DBFCDX:GOTOP (Line: 566)
COREDB:<>C:<GOTOP>B__58_0 (Line: 1031)
COREDB:DO (Line: 234)
COREDB:GOTOP (Line: 1028)
DBGOTOP (Line: 313)
DOTEST (Line: 22)
START (Line: 11)

```

**Comment by RobertvanderHulst** [comment]
The problem with this code is that when using DbCreateIndex() to create an index tag in a CDX then the filename of the CDX is used to "compute" the tagname. Tag names can be maximum 10 characters long. The code in the CDX driver was not properly handling the longer filename.

**Comment by RobertvanderHulst** [comment]
On top of that the VO driver truncates the tag length to 8 characters. FoxPro allows 10 characters. I have changed the CDX driver to also allow 10 characters
I also see that when VO and FoxPro when recreating the only tag in the file, then they completely recreate the file. I'll change the CDX driver to do the same.
