### ISSUE TITLE
VS Form Designer problem with EXPORT ARRAY OF statement

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#778]
https://www.xsharp.eu/forum/public-chit-chat/2038-vs-replaces-tabs-by-spaces?start=20#19599

The attached solution includes this line in the form1.prg:

EXPORT test AS ARRAY OF Form1

after making a change in the form designer, this code is changed to:

PUBLIC test AS VOID

[WindowsFormsApplication20.zip](https://github.com/X-Sharp/XSharpPublic/files/7163383/WindowsFormsApplication20.zip)

**Comment by cpyrgas** [comment]
Robert, I am supposed to confirm and close such fixes, not yourself :)

The problem is fixed indeed, but the code is still being changed to use the PUBLIC keyword, instead of the original EXPORT one, is this as intended? It happens also for regular fields like

EXPORT n AS INT

becomes

PUBLIC n AS INT

**Comment by RobertvanderHulst** [comment]
Chris,

There is a new setting in the Tools/Options dialog that controls what is used (PUBLIC or EXPORT and HIDDEN or PRIVATE).
In theory I could also store the original keyword and use that. That might be a good idea.

Robert

**Comment by RobertvanderHulst** [comment]
Btw: the closing happened automatically when I merged the changes from the feature branch to the master branch. I think Github does that automatically.
