### ISSUE TITLE
Error writing to XML documentation file

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#783]
When compiling a library that contains XML documentation, an error occurs that does not point to a location in the code:
> XS1569: Error writing to XML documentation file: Failed to compare two elements in the array.
> File: XSC
> Line: 1

How do I find the problematic XML string in my code?

P.S. Unfortunately, I am unable to provide a test project to reproduce the problem. This is a real application with many related components.

**Comment by leon-ts** [comment]
Found the problematic XML string.
If there is a PARTIAL class in several PRG files, and documentation is described for each, then the error described in this ticket occurs.

**File1.prg**
```
/// <summary>Represents MyClass.</summary>
PARTIAL CLASS MyClass
END CLASS
```
**File2.prg**
```
/// <summary>Represents MyClass.</summary>
PARTIAL CLASS MyClass
END CLASS
```

**Comment by RobertvanderHulst** [comment]
The summaries will now be merged like in C#

**Comment by cpyrgas** [comment]
Confirm fixed
