### ISSUE TITLE
Add option to make OVERRIDE mandatory

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#786]
Suggested by Volkmar Rigo:

Following code compiler with no errors or warnings, and prints the "expected" result "child", as Test() in the Child class overrides the Parent class method. Even in core dialect though, the keyword OVERRIDE is not required, but it's probably a good idea to do that. Maybe introduce a /strict compiler option, which will require this and possibly other things that X# does not currently require?

Or maybe a warning should be reported (when such an option is used, or when compiling in core dialect), that the OVERRIDE warning was not supplied.

```
FUNCTION Start() AS VOID
LOCAL o AS Parent
o := Child{}
o:Test("A")
RETURN

CLASS Parent
	VIRTUAL METHOD Test(a AS STRING) AS VOID
		? "parent"
END CLASS

CLASS Child INHERIT Parent
	METHOD Test(a AS STRING) AS VOID
		? "child"
		
END CLASS
```

**Comment by RobertvanderHulst** [comment]
Chris,
> possibly other things

What do you have in mind?

**Comment by cpyrgas** [comment]
Robert, many times I've thought of similar stuff, but they do not come to mind right now. Will comment here as soon as I come across to them again

**Comment by RobertvanderHulst** [comment]
Should this "Strict" compiler option also affect the visibility. Should it make the default visibility "private" like in C# or should it not affect the visibility ?

**Comment by VolkmarR** [comment]
I would say no. A separate flag might be useful for the future.  And these options are a little bit related to the "all methods are virtual" flag.

**Comment by cpyrgas** [comment]
I would also say no...

**Comment by RobertvanderHulst** [comment]
See my comment for #846

**Comment by cpyrgas** [comment]
This looks very good to me now.
