### ISSUE TITLE
DateTimepicker control linked to a server field

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#79]
NOTE: The problem only occurs when a Timepicker is linked to a server field. 

A TimePicker doesn´t properly check or uncheck the checkbox because the _winSYSTEMTIME structure used in the method SetDateTime() doesn´t hold a valid date when the time string has changed. The enhancements i´ve made to the SetDateTime() Method are marked with "KHR". Now the TimePicker checkbox is properly checked or unchecked.

Attached you find a sample viaef

1. In the module "DTPickerClass" there´s the Define `_USE_CHANGED_SETDATETIME_METHOD__` . When you set the define to FALSE, you see the Timepicker default behaviour.

2. In the "Start" module you must change the path to the DBF if you use another path than d:\test.

`GLOBAL gcPfad :=  "D:\test\" AS STRING`

[DTP.ZIP](https://github.com/X-Sharp/XSharpPublic/files/3337605/DTP.ZIP)

**Comment by Karl1155** [comment]
In addition: I think there should be a validation of the current structure content before the Today() values are assigned. Using ConDate() it looks like:

```
      	// Start  KHR
        	
        // make sure that lateron DTM_SETSYSTEMTIME is always called with a valid date part ! 
        	
        IF ConDate ( sDate:wYear, sDate:wMonth , sDate:wDay   ) == NULL_DATE 
        		
		dToday := Today()
   				 
    	      	sDate:wDay       := Day ( dToday )   
   	        sDate:wMonth     := Month ( dToday ) 
       	    	sDate:wYear      := Year ( dToday )        		
        		
       	ENDIF 
        	
       	// End KHR	



```

**Comment by RobertvanderHulst** [comment]
Karl,
I'll integrate those changes in the GUI classes.
Thanks.
