### ISSUE TITLE
WinForm designer changes formatting in main-prg file

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#806]
If you use the Winforms-Designer and change there something (e.g. resize a control), The formatting of the main-prg file (not only the designer file) is changed. In my case the indent is now 1. 
I would expect, that the formatting of this file is not touched, because the whole autogenerated code is in the designer file. (Except the constructor).

Attached is an example. You have to change something in the designer and save it
[XsharpFormsTest.zip](https://github.com/X-Sharp/XSharpPublic/files/7330362/XsharpFormsTest.zip)

See also https://github.com/X-Sharp/XSharpPublic/issues/828

**Comment by hpetriffer** [comment]
Okay. I will check it in the new build

**Comment by cpyrgas** [comment]
In my tests so far, indeed now the indentation of the existing code in the main .prg file remains intact with the newer VS integration. But will let Hans Joerg confirm this once the new build is released.

**Comment by cpyrgas** [comment]
Confirm fixed

**Comment by hpetriffer** [comment]
I have tested this now. The formatting is better, but there are still some errors.
I noticed that the order of the class members are changed. This is problemetic by tracking changes in Git, especially in large classes. Can you change it, that the main form file is not changed other adding the new member at the end of the class.

**Comment by cpyrgas** [comment]
Hans Joerg, do you mean that the designers also still generates code that is invalid and does not compile, or that it just changes the order of some items?

Robert, I checked c# and its designer does not rearrange items, they all stay in the same place no matter how mixed up they are, so I assume it's possible to do this somehow in X# as well. But not for this build I am afraid.

**Comment by hpetriffer** [comment]
The code is correct. It just changes the order

**Comment by RobertvanderHulst** [comment]
I'll try to change this for a next build.

**Comment by RobertvanderHulst** [comment]
Chris confirms that this is now fixed

**Comment by cpyrgas** [comment]
Well, I did not confirm (or not not confirm) anything regarding this one yet :)

**Comment by cpyrgas** [comment]
Now I can confirm it indeed works very nicely!
