### ISSUE TITLE
Adding a decimal variable to a usual initialized with 0 looses precision when converting to string

### ISSUE THREAD

**Issue by ArneOrtlinghaus** [X-Sharp/XSharpPublic#808]
In the example below using the VO dialect the precision is lost when adding a decimal variable to a usual initialized with 0. 
This does not happen when adding a float to a usual initialized with 0. But we would like to begin to use decimals without changing all old code. 

function TestDecimalusual1()
local u as usual
local d := 100000.23M as decimal
local c as string
**u := 0.0** 
u += d
c := alltrim(str(u, 15,3)) 
Console.WriteLine("decimal/usual result init 0.0: " + c)   // <<< ok, it returns 100000.230
**u := 0**
u += d
c := alltrim(str(u, 15,3)) 
Console.WriteLine("decimal/usual result init 0: " + c)  // <<< not ok, it returns 100000.000
return n
[decimalusual.zip](https://github.com/X-Sharp/XSharpPublic/files/7339922/decimalusual.zip)
il

**Comment by RobertvanderHulst** [comment]
And of course for the (FoxPro) Currency type we need to do this as well

**Comment by ArneOrtlinghaus** [comment]
Thank you, that will help us a lot. The characteristics of the numeric type DECIMAL are really impressive. So using them for new developments can help reduce many rounding efforts.

**Comment by cpyrgas** [comment]
Confirm fixed
