### ISSUE TITLE
VODBOrdCreate function does not work if the cOrder parameter contains an empty string

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#809]
In VO, you can create a DBF file index (DBFCDX driver) using the VODBOrdCreate function without specifying the cOrder parameter. To do this, the name of the index file and the index expression are passed to the VODBOrdCreate function, and an empty string or NIL is passed instead of the order name. In X#, if you pass the cOrder parameter as an empty string (not NIL), then the VODBOrdCreate function returns an error.

After researching the Runtime Libraries I seem to have found the problem. This is the next line of code in the OrderCreate method of the XSharp.RDD.CDX.CdxOrderBag class:

```
IF info:Order IS STRING VAR strOrder
    cTag := strOrder
ELSE
    cTag := Path.GetFileNameWithoutExtension(info:BagName)
    info:Order := cTag
ENDIF
IF String.IsNullOrEmpty(cTag)
    // Exception ?
    RETURN FALSE
ENDIF
```
The order name is checked only for the required type (STRING), but its value is not checked for emptiness.
In this method, you can check that the string is empty and set the processing logic to it as for a NULL value, or somewhere earlier in the call hierarchy (CdxOrderBagList:Create or CoreDb.OrdCreate) check the order name for an empty string and convert it to NULL.

**Comment by cpyrgas** [comment]
Confirmed fixed.
