### ISSUE TITLE
Allow Access to Object for WITH .. ENDWITH in code called from within this block

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#811]
FoxPro allows this
```
FUNCTION Foo
LOCAL oFoo 
oFoo = CreateObject("SomeObject")
WITH oFoo
  .DoSomething()
  Bar()
ENDWITH

FUNCTION Bar
? .PropertyInsideSomeObject
RETURN
```

To emulate this (only in the VFP dialect) we need to push oFoo on a stack in the WITH line and pop it on the ENDWITH line.
Then the `.PropertyInsideSomeObject` will have to be translated to `GetObjectFromWithStack().PropertyInsideSomeObject` and GetObjectFromWithStack() should throw a runtime error when the stack is empty.
When compiling this the compiler should generate a warning that no WITH .. ENDWITH is active, so the code may fail at compile time.
Since we don't know the type of the object on the stack all property access will be late bound.

**Comment by cpyrgas** [comment]
Confirmed done
