### ISSUE TITLE
Global Strings in Class Libraries are not initialised with beta version of compiler (2.8.4.1 - 21.09.2021)

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#813]
With the beta version of the compiler (that I got to test the override warning), I noticed a difference with global strings in class libraries. Here is an example:

    global global_string as string

This variable is initialised with "" with the current compiler, but with the beta version, it is null.

![image](https://user-images.githubusercontent.com/9860916/137734285-720d753a-fb25-405a-b21d-66a57fa7b1c8.png)

![image](https://user-images.githubusercontent.com/9860916/137734319-2645f090-eb22-487f-ab77-95ea1d584b73.png)

I created a small demo project, that shows this behaviour. 

[XSharpConsoleGlobalVar.zip](https://github.com/X-Sharp/XSharpPublic/files/7364948/XSharpConsoleGlobalVar.zip)

@cpyrgas ... can you test, if this issue is still present?

**Comment by RobertvanderHulst** [comment]
Volkmar,
This was a side effect of the change where we allow multiple class variables of different types and multiple globals of different types to be placed on the same line:

```
GLOBAL foo AS STRING, bar as LONG
CLASS Test
   PROTECT foo AS STRING, bar as LONG
END CLASS
```
As a result the "rule hierarchy" in the compiler was changed and we did not test the code to set the initializers for Globals correctly.
I have just changed that and it will be included in the upcoming build.

Chris, when you are reading this. Can you create a compiler test for this, to make sure that this will not creep in again if / when we make a future change ?
