### ISSUE TITLE
XSFrm editor makes all classes in prg PARTIAL

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#814]
If there are multiple classes in a PRG, they all become PARTIAL when xsfrm is saved, although only one of them is being edited.

**Comment by cpyrgas** [comment]
Robert, this is being done by your code, in XSharp_EditorStream.prg you have implemented METHOD AddPartial(), which does exactly that, adds PARTIAL to every class in the .prg file.

Do you remember if that was on purpose (doing it for any class) and why?

**Comment by RobertvanderHulst** [comment]
You are right, I added that. I can see that in the "Blame" view of the code.
But I think it was only meant for the main class and not for the other classes in the code.

**Comment by cpyrgas** [comment]
OK, will look into adjusting it. But what is the "blame" view? I knew it was your code only because it uses extensively VAR, which I would never had used :)

**Comment by RobertvanderHulst** [comment]
If you open the source in GitHub :
https://github.com/X-Sharp/XSharpPublic/blob/main/VisualStudio/XSharpVoEditors/XSharp_EditorStream.prg
Press the [Blame] button on the top right of the source:

![image](https://user-images.githubusercontent.com/14240939/170862093-7c7264d7-b818-46a1-82dd-cb0824f74333.png)

The the l;eft margin shows who changed which line last and in which commit.
For AddPartial this looks like:
![image](https://user-images.githubusercontent.com/14240939/170862135-7b604b8f-c82e-4046-83d1-aa502990e996.png)
So it is obvious that "Robert was here"

**Comment by cpyrgas** [comment]
Oh, so it is literally called "Blame"! Hehe, that was a nice one! Thanks for the info!

**Comment by cpyrgas** [comment]
Fixed, by simply removing the code that manually adds the PARTIAL keyword. The code generator for the VO binaries already keeps the previous modifiers in CLASS and other entity type definitions (if they already exist) when it generates code, so no need to manually add PARTIAL. Only in new windows, if the PARTIAL keyword is needed, then the programmer must add it once for the class definition, same as they would do with any other new class in the code.

**Comment by RobertvanderHulst** [comment]
Confirmed fixed.
