### ISSUE TITLE
Error in ACopy function when there is nothing to copy

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#815]
The following example throws an ArgumentOutOfRangeException exception:
```
LOCAL aSrc, aDest AS ARRAY
aSrc := {}
aDest := {}
ACopy(aSrc, aDest, 1, 0, 1)
```
At the same time, this example works without problems in VO (it "understands" that the actual copying, taking into account the given length, will not cause the array to go out of bounds).

The real code where I found this problem is the following (the array is expanded with another array):
```
aSrc, aDest // some arrays
dwSrcLen := ALen(aSrc)
dwDestLen := ALen(aDest)
ASize(aDest, dwDestLen + dwSrcLen)
ACopy(aSrc, aDest, 1, dwSrcLen, dwDestLen + 1)
```

**Comment by cpyrgas** [comment]
Confirmed fixed
