### ISSUE TITLE
Macro compiler / parameters by reference in Methods

### ISSUE THREAD

**Issue by ecosSystem** [X-Sharp/XSharpPublic#818]
With 2.9 passing parameters by reference to functions in Macros seems to be fixed. However passing by reference to methods is still not working. I have attached an AEF (VO) and a SLN to reproduce the problem. The following code must work for us:

FUNCTION Start() AS VOID STRICT
LOCAL bBlock	AS _CODEBLOCK
LOCAL cVar		AS USUAL
LOCAL cClass   AS USUAL

cVar	:= "x"
PRIVATE &cVar
&cVar	:= "a"
? &cVar

bBlock := &( "{||MyTestFunc(@x)}" )
bBlock:Eval()
? &cVar      // this is ok now

cClass	:= "c"
PRIVATE &cClass
bBlock := &( "{||c := MyTestClass{}}" )
bBlock:Eval()

bBlock := &( "{||c:TestMethod(@x)}" )
bBlock:Eval()

? &cVar    // this still doesn't work

WAIT

RETURN

FUNCTION MyTestFunc(y)
y := "b"
RETURN TRUE

CLASS MyTestClass
DECLARE METHOD TestMethod

METHOD TestMethod(y REF STRING) AS VOID
y := "c"
RETURN

END CLASS

[Test.zip](https://github.com/X-Sharp/XSharpPublic/files/7387423/Test.zip)
[MakroTest.zip](https://github.com/X-Sharp/XSharpPublic/files/7387425/MakroTest.zip)

**Comment by ecosSystem** [comment]
Are there any news for this topic ? We really need this functionality urgently before we can go live with our application...

**Comment by RobertvanderHulst** [comment]
Karl,
I do not think this will be included in the 2.9a patch that we are finalizing.
It does have high priority and we will send you an updated macro compiler assembly once it is ready.

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by ecosSystem** [comment]
Seems to work fine now in 2.0a, thanks a lot!
