### ISSUE TITLE
SCATTER TO and APPEND FROM ARRAY- Foxpro

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#821]
the foxpro sample at the end of the msg uses SCATTER TO and APPEND FROM ARRAY. Trying to do the same with X# shows two problems

- Looking with ShowArray() at the aNewRec content it seems that after the creation the array is never touched. The array should be filled either with the content of the current record or the default field values. 

- Using APPEND FROM ARRAY fails with the error msg that a multi dimensional array is expected ?

Karl-Heinz

i hope the copy and paste worked 

```
//  /memvar+ /undeclared+ /Fox2+

FUNCTION Start( ) AS VOID 
LOCAL ARRAY aNewRec(3)  // to compile this line /fox2 must be enabled 
// Dimension aNewRec(3)
LOCAL cFile AS STRING 


	cFile = "d:\test\scatter.dbf"

    IF ! File ( cFile ) 
    	
     	DbCreate ( cFile , {{ "field1" , "C" , 10 , 0 } , { "field2" , "N" , 5,2 } , { "field3" , "L" , 1,0}}  )
     	
     	// btw. the create table command compiles ! 
     	//
	// create table (cfile) (field1 C(10), field2 N(5,2), field3 L(1) ) 
	//
	// Looking at the ppo content shows that it´s translated to 
     	// _DbCreate( "table (cfile) (field1 C(10), field2 N(5,2), field3 L(1) )" ,  ,  , .F. ,  )
     	// 
     	// But it seems the scatter.dbf isn´t cretaed because  the USE command fails with the msg
     	// that the file isn´t found. I will look at this problem separately ...  
    	
		
    ENDIF 	
    
	use (cFile ) exclusive
	
	zap
		
	append blank
	
	replace field1 WITH "Test"
	replace field2 WITH 11.11
	replace field3 WITH .t.  

	// ------------- 
	
	GO TOP
	
	
	SCATTER TO aNewRec 
	
	ShowArray ( aNewRec , "Scatter I " )
/*	
	Scatter I [1] = .F. (NIL)
	Scatter I [2] = .F. (NIL)
	Scatter I [3] = .F. (NIL) 
*/	

	aNewRec[1] := "new"
	
	?
	
	SCATTER TO aNewRec BLANK             
	
	// note: "new" is still shown
		
	ShowArray ( aNewRec , "Scatter II " )
/*	
	Scatter II [1] = new (C)
	Scatter II [2] = .F. (NIL)
	Scatter II [3] = .F. (NIL)	 		
*/
	?
	
	// These are the values a SCATTER ... BLANK should create	
	aNewRec[1] := ""
	aNewRec[2] := 0.00
	aNewRec[3] := .f.		
	                                  
	
	// APPEND FROM throws an runtime error because
	// the underlying DBAppendFromArray() expects a multidimensioal array ?

	APPEND FROM ARRAY aNewRec 
	
	go top
	
	DO WHILE !Eof()
		? a->field1, a->Field2 , a->Field3
		
		SKIP 1
	ENDDO
	
	use	 	
	
	RETURN 

```

scatter.prg  - Foxpro only
```
set safety off
set talk off


&& note: Foxpro redims the array automatically at runtime !
dimension aNewRec(1)

cFile = "d:\test\scatter.dbf"

if ! file ( cFile )
	create table (cfile) (field1 C(10), field2 N(5,2), field3 L(1) )
endif		

use (cFile) exclusive
zap

append blank

replace field1 with "Test"
replace field2 with 11.11
replace field3 with .t.

&& --------------------------

&& fills the array with default field values
SCATTER TO aNewRec BLANK
                  	
APPEND FROM  ARRAY aNewRec  

&& --------------------------
	
go top  

&& read the content of the first record
SCATTER TO aNewRec 

&& change the content of the array
aNewRec[1] = alltrim(a->field1) + "new"
aNewRec[2] = a->field2 + 0.01 
aNewRec[3] = ! a->field3 

APPEND FROM ARRAY aNewRec  	

&& --------------------------
	
BROWSE

USE
```

**Comment by RobertvanderHulst** [comment]
SCATTER TO array was working. 

But upon closer inspection the code that fills an array (which is part of /fox2) now interferes and this code

`aNewRec := __ScatterArray(...)`

which is the result of the SCATTER user defined command

is now replaced with 

`__FoxFillArray(aNewRec, __ScatterArray(...))`

And this does not do anything, since the second parameter to __FoxFillArray is the new array and assigning an array to the elements of a FoxPro array is not supported.

I'll make sure that the /fox2 option will not interfere with this kind of assignments.
What do you think, should __FoxFillArray() generate a runtime error when the second parameter is an array (like in this situation)?

**Comment by RobertvanderHulst** [comment]
I looked at this a bit more and found:
- Foxpro `COPY TO ARRAY` inspects the original array and only copies more than one record when the original array is multidimensional and will only copy as many columns as the original array has columns. If the original array has more rows or columns then these are left untouched
- When the original array is single dimensional, then FoxPro `COPY TO ARRAY` will only copy as many fields as there are elements in the original array. If the original array has more items then these are left untouched
- FoxPro `SCATTER `only copies one row and treats the FoxPro array as single dimensional, regardless of how it is declared.

To properly emulate this I will now changed the UDCs and function and pass the array as parameter to the DbCopyToArray() function and __ScatterArray() so these functions can limit the # of rows and/or fields that are copied based on the information from the original array and also update the original array when it already exists.

**Comment by cpyrgas** [comment]
Confirmed fixed
