### ISSUE TITLE
Slow response when clicking on code

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#829]
If I click on "self" within the brackets in the following example with the mouse, it then takes approx. 20-30 seconds until the editor reacts again.

```
public class TestGeneric
 export oMainForm as System.Windows.Form

method fileExit () as usual
        //self:EndWindow()
		self:oMainForm:CreateMenu(self)
        return nil
end class
```

With an empty project and only this class inside it is a lot faster. But you can see also a small delay, by clicking around...I think it depends from the included assemblies and so on
Attached it is the log of VS
[Output.txt](https://github.com/X-Sharp/XSharpPublic/files/7417112/Output.txt)

**Comment by cpyrgas** [comment]
Reopened, to let Hansjoerg confirm if this is fixed

**Comment by hpetriffer** [comment]
It seems to work
