### ISSUE TITLE
Missing ErrorExec function

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#830]
VO has an ErrorExec function that call the currently installed error function and error block. In fact, it is a wrapper for the following expression:
`Eval( ErrorBlock(), oError )`
Is it possible to add this function (ErrorExec) to X#?

P.S. We are using a modified error message box using X#'s built-in XSharp.ErrorDialog class. Therefore, the ErrorDialog function is not suitable for us.

**Comment by cpyrgas** [comment]
Added and seems to work correctly.

**Comment by leon-ts** [comment]
Robert,
The final implementation of this function causes the Error type to be instantiated three times!

```
FUNCTION ErrorExec(pErrInfo AS Exception) AS USUAL
    local cbError as CODEBLOCK
    local oError  as XSharp.Error
    cbError := ErrorBlock()
    oError := ErrorBuild(XSharp.Error{pErrInfo})
    RETURN cbError:Eval(oError)
```

**For example:**
```
RECOVER USING oError
    ErrorExec(oError)
```
1. Creation of an instance of type Error as a result of an exception.
2. Creating a new (second) instance of type Error: `XSharp.Error{pErrInfo}`
3. Creation of a new (third) instance of type Error: `ErrorBuild(...)`
In this case, step 2 is not needed at all, since the ErrorBuild function already creates an instance of type Error from type Exception. And if we take into account that pErrInfo can already be an instance of the Error type, then it can be immediately passed to cbError:Eval(oError)

**I suggest the following modification:**
```
FUNCTION ErrorExec(pErrInfo AS Exception) AS USUAL
    local cbError as CODEBLOCK
    local oError  as XSharp.Error
    cbError := ErrorBlock()
    IF ( pErrInfo IS Error )
        oError := (Error)pErrInfo
    ELSE
	oError := ErrorBuild(pErrInfo)
    ENDIF
    RETURN cbError:Eval(oError)
```

P.S. I also ask you to change the name of the 'pErrInfo' variable to something more like the type of the variable (Exception). For example, 'err' or 'info' or something else. Since the 'p' prefix no longer makes sense and can be confusing.
