### ISSUE TITLE
compiler problem with closing parenthesis 

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#831]
The code compiles,  but at runtime an error is thrown. This happens because the first closing parenthesis  is at the wrong position. The first closing parenthesis must be placed after the number 2. 

```
FUNCTION Start( ) AS VOID  
LOCAL n AS INT	

IF ( n := TestUntyped ( 1 ), 2 ) > 0 
// IF ( n := TestUntyped ( 1 , 2 )) > 0	 
	? n 	
ENDIF 

// throws as expected an compile error
//
//IF ( n := TestTyped ( 1 ) , 2 ) > 0
//	? n 	
// ENDIF 		

RETURN

FUNCTION TestUnTyped ( a , b ) 
	    ? a , b  // 1 , NIL 
	RETURN a + b 
	
FUNCTION TestTyped ( a AS INT , b AS INT ) AS INT 
	    ? a , b  
	RETURN a + b 	
```

so the line 

`IF ( n := TestUnTyped ( 1 ), 2 ) > 0`

must be changed to

`IF ( n := TestUnTyped ( 1 , 2 ) ) > 0`

As expected, trying the same with the typed function throws an compile error.

Karl-Heinz

**Comment by cpyrgas** [comment]
I confirm this will not be fixed :)
