### ISSUE TITLE
The compiler does not warn about the wrong assignment of a value to the ARRAY OF type

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#833]
There is the following code:
```
FUNCTION Start() AS VOID STRICT
	LOCAL oCBArray AS ARRAY OF CODEBLOCK
	TestFunc( OUT oCBArray )
	RETURN

FUNCTION TestFunc(oCBArray OUT ARRAY OF CODEBLOCK) AS VOID STRICT
	oCBArray := NULL_ARRAY
	RETURN
```
The code compiles without errors. But at runtime, it throws an exception NullReferenceException on the line:
`oCBArray := NULL_ARRAY`

Here either a compile-time error or an implicit assignment of NULL instead of NULL_ARRAY is needed.

**Comment by cpyrgas** [comment]
The sample code now compiles and runs with no errors, but then I tried adding a

? oCBArray == NULL_ARRAY

and got error XS0019: Operator '==' cannot be applied to operands of type 'ARRAY OF<XSharp.Codeblock>' and 'ARRAY'

If we're gonna support oCBArray := NULL_ARRAY, then shouldn't also oCBArray == NULL_ARRAY be supported?

**Comment by RobertvanderHulst** [comment]
To allow this we will have to add an Equals operator to the ARRAY OF class.
But the question then is: what do we allow in this Equals operator ?
- Do we only allow the comparison to NULL_ARRAY ?
- Do we also check for ReferenceEquals ?
- Do we check the contents of both sides of the comparison when they are not reference equal ? 
- And if so, should an ARRAY OF Foo be equal to an array when each of the elements in the array is a usual with a Foo object and these Foo objects match the elements inside the ARRAY OF Foo ?

**Comment by cpyrgas** [comment]
It would seem natural to me to make it work exactly as with regular ARRAY. A comparison to NULL_ARRAY should return true only when uninitialized or explicitly assigned NULL_ARRAY and the comparison between arrays should return true only when they are equal by reference (either both NULL_ARRAY, or both pointing to the same object)

**Comment by RobertvanderHulst** [comment]
Ok, I will add that comparison operator

**Comment by cpyrgas** [comment]
Robert, OK sounds good! Only if it's very easy though, otherwise please leave it for later. I have added a test for it for now.

**Comment by RobertvanderHulst** [comment]
I am going to delay the solution of the comparison issue to the next build

**Comment by RobertvanderHulst** [comment]
At this moment `NULL_ARRAY `is translated by the compiler to `Default(ARRAY)`.
In theory I could solve this by compiling `NULL_ARRAY `into `NULL`.
However I am afraid that will have side effects.
Therefore I am choosing an alternative solution:
When the compiler detects a binary operation (such as `==`,` !=` , `<`, `+` etc) it will check to see if they involve one side of type `ARRAY` and another side of type `ARRAY OF`. When it does and when the `ARRAY` side is actually `Default(ARRAY)`, then and only then will I replace that side with `NULL`.
The problem with assigning `NULL_ARRAY` to `ARRAY OF` is solved in the runtime in the code that handles the implicit conversion from `ARRAY `to `ARRAY OF`

**Comment by cpyrgas** [comment]
Confirmed fixed
