### ISSUE TITLE
Creating a codeblock inside a codeblock using the & syntax does not work

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#835]
Working example from VO:
```
LOCAL cS AS STRING
LOCAL cb AS STRING // CODEBLOCK in X#
	
PUBLIC cExpr
m->cExpr := "STR(10, 2)"
	
cS := "&(cExpr)"
cb := MCompile(cS)
cS := MExec(cb)
```

Running this code in X# throws an exception: Invalid runtime identifier (&) expression

**Comment by RobertvanderHulst** [comment]
I looked at this and will try to include it in today's build

**Comment by cpyrgas** [comment]
Having trouble compiling the macro compiler, will test this with the new installer

**Comment by cpyrgas** [comment]
Confirm fixed

**Comment by leon-ts** [comment]
Robert,
Still doesn't work in some situations:
```
LOCAL cS AS STRING
LOCAL cb AS CODEBLOCK

PUBLIC cExpr, lCond
m->cExpr := "STR(10,2)"
m->lCond := FALSE

cS := "IIF(lCond,,&(cExpr))"
cb := MCompile(cS)
cS := MExec(cb)
```
**Error:**
`Macrocompiler (1,12): error XM0224: Expression '&(( <Unknown type> ){Var:''})' not found`

**Comment by RobertvanderHulst** [comment]
leon,

That error is most likely caused by the fact that there is no TRUE expression between the commas in the macro.
What happens if you try this:

`cS := "IIF(lCond,'',&(cExpr))"`

Robert

**Comment by leon-ts** [comment]
Robert,
There will be the same error:
`Macrocompiler (1,14): error XM0224: Expression '&(( <Unknown type> ){Var:''})' not found`

 Before sending my previous message, I substituted explicit values between commas: NIL, STR (20,2), etc. But it did not help.

**Comment by cpyrgas** [comment]
Robert, it seems to be a general problem with the & operator within an expression. Also this throws an error:

MCompile("Left( &(cExpr) , 1)")

**Comment by cpyrgas** [comment]
Confirm fixed

**Comment by leon-ts** [comment]
Guys,
It works well now!
