### ISSUE TITLE
Incorrect assignment of values and return of parameters in some situations

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#837]
There is the following code:
```
FUNCTION Start() AS VOID STRICT
	TestClass.DoSomething()
	RETURN

CLASS TestClass

	STATIC METHOD DoSomething() AS VOID STRICT
		
		LOCAL cTime AS STRING
		LOCAL nH, nM, nS AS INT
		
		cTime := Time()
		_ToHMS(cTime, OUT nH, OUT nM, OUT nH)
		
		LOCAL FUNCTION _ToHMS(cTimeString AS STRING, nH OUT INT, nM OUT INT, nS OUT INT) AS LOGIC PASCAL
			nH := Val(Left(cTimeString, 2))
			nM := Val(SubStr(cTimeString, 4, 2))
			nS := Val(SubStr(cTimeString, 7, 2))
			RETURN TRUE
		END FUNCTION
		
		RETURN

END CLASS
```
The local function _ToHMS, when storing the value in the nS variable, also overwrites the value of the nH variable (that is, it corrupts the value of the nH variable). When returning from a local function, the external variables nH and nS contain invalid values.

**Comment by leon-ts** [comment]
Oh, this problem is not related to local function. I converted the local function to a static method of this class and got the same problem.

**Comment by RobertvanderHulst** [comment]
Leonid,
You are not passing nS as last parameter but nH again:

`_ToHMS(cTime, OUT nH, OUT nM, OUT nH)`

**Comment by leon-ts** [comment]
Robert,
Indeed, sorry! It's time to go on vacation :)
Thanks a lot for the hint!
