### ISSUE TITLE
Intellisense problem with chained expressions

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#838]
!!! Not a showstopper !!!

With chained method calls, intellisense shows info of first node for the next ones. Following code for ToString() shows parameter tips for CompareTo() instead, and the final ":" shows members of INT instead of STRING:

```
FUNCTION Start() AS VOID
LOCAL c AS STRING
c:CompareTo("aa"):ToString():
```
![intel21](https://user-images.githubusercontent.com/14542129/139908754-92ff729f-2530-43dd-a61b-df4a347f4f45.png)

![intel22](https://user-images.githubusercontent.com/14542129/139908766-83bf5239-6fb8-4e1f-b7f3-e38bea73b79f.png)

**Comment by RobertvanderHulst** [comment]
This works correct now in the current build

**Comment by cpyrgas** [comment]
Indeed, but there's still something not working well. This does not produce member completion:

LOCAL c AS STRING
c:ToString():Length:

**Comment by cpyrgas** [comment]
Perfect! (confirmed)
