### ISSUE TITLE
Parameters with CLIPPER calling convention cannot have default values

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#839]
Following code reports two errors that CLIPPER methods cannot have default values. Is there a fundamental reason why this is not allowed? I would think that it is possible to store the default values in attributes, but maybe I am not thinking of something.

This is used in several places in the IslandTug application. Can be workarounded of course, but would be nice if this is supported, as it is in VO.

```
// error XS9072: Parameters with CLIPPER calling convention cannot have default values.
CLASS TestClass
	METHOD TestClipper(a := 1, b := "asd")
	RETURN NIL
END CLASS
```

**Comment by RobertvanderHulst** [comment]
Chris,

First: Default parameters for CLIPPER methods are allowed in VO but not properly supported. If you call a method or function late bound then the default value is ignored.
So if you use the class like this
```
local o 
o := TestClass{}
o:TestClipper()

```
then TestClipper will receive 2 NIL values.
And if I remember correctly: even when you strongly type the method in VO and call it late bound then the defaults are also not passed. The late bound "stub" that gets generated by the VO compiler does not check for default parameters as far as I remember.

Now for X#:
CLIPPER calling convention gets compiled into a PARAMS array with a compiler generated parameter name and the real parameter names are encoded in the ClipperCallingConvention attribute that is placed on the method/function. This attribute is modeled after the same attribute in Vulcan and only has a list of names.
For non CLIPPER calling conventions the default parameters are stored in a DefaultParameterValue Attribute that is placed on the parameter that the attribute applies to. This attribute has 2 values: a type flag (int) and a value (object)

I see 2 solutions to do this for CLIPPER calling convention:
1) Enhance the ClipperCallingConvention attribute and add an array of type flags and an array of values
2) Enhance the DefaultParameterValue attribute and add a parameter name, and allow multiple of these attributes to be placed on either the compiler generated parameter or on the method itself.

**Comment by wriedmann** [comment]
Hi Robert,
that is correct: "even when you strongly type the method in VO and call it late bound then the defaults are also not passed".
Default parameters in VO are working only when you call them early bound because the parameter substitution is done at compile time.

**Comment by cpyrgas** [comment]
Arrgghhhh, actually even when you call the method early bound in VO, the default value is still being ignored!!! I'm used to the very sloppy behavior in VO, but that much silliness I did not expect it, should had tested it myself already.

So I think actually we should never allow default params in untyped methods, because if we do, then existing code (which uses default values which are being ignored in VO) might stop working properly! But maybe the error should be changed into a warning and make the compiler ignore the default value, like VO does? I do not have a strong opinion about it, it's just that there are 49 places where this is reported in the said app.

**Comment by cpyrgas** [comment]
And for completeness, VO silently ignores default values even in untyped functions! Of course...

```
FUNCTION Start() AS INT
? UntypedFunction() // NIL !
? UntypedFunction("with param") // "with param"
FUNCTION UntypedFunction(p := "default value")
RETURN p
```

**Comment by cpyrgas** [comment]
Nah, leave it an error...
