### ISSUE TITLE
Intellisense: mouse hint for VAR variable shows type of constructor arguments instead of class itself

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#844]
Consider this:

```VAR startInfo := ProcessStartInfo{"some.exe"}```

If you hover mouse cursor over "startInfo" you'll see that it is a... string, and not an instance of ProcessStartInfo class.

---

```VAR startInfo := ProcessStartInfo{5}```
startInfo is shown as INT

---

```VAR startInfo := ProcessStartInfo{5, "some.exe"}```
startInfo is shown as STRING

---

```
LOCAL nVarInt := 5 AS INT
VAR startInfo := ProcessStartInfo{nVarInt}
```
startInfo is shown as INT

---

```
LOCAL nVarInt := 5 AS INT
VAR startInfo := ProcessStartInfo{nVarInt, "lalala"}
```
startInfo is shown as STRING

---

```VAR startInfo := ProcessStartInfo{}```
startInfo is shown as ProcessStartInfo.

P.S. This issue doesn't affect compilation which is correct, just the mouse hint is the problem.

**Comment by cpyrgas** [comment]
Confirmed fixed.
