### ISSUE TITLE
More FoxPro array stuff

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#848]
```
LOCAL a(10) AS ARRAY
LOCAL a[10]

```
These should also create a FoxPro array in the FoxPro dialect

I think the best thing is to always map AS ARRAY to AS __FoxArray in the FoxPro dialect and catch these 2 syntaxes as well.

**Comment by cpyrgas** [comment]
Agreed

**Comment by RobertvanderHulst** [comment]
Additionally: SqlExec() now expects a normal array. This should then also be changed to a FoxPro array.
We may be able to achieve this by compiling ARRAY into __FoxArray since the VFP assembly is compiled in the FoxPro dialect

**Comment by jpmoschi** [comment]
Only to understand the proposed change:
what is happen in that cases?
local la1:= Array{}
local la2:= DbStruct()
The compiler will convert too?

**Comment by jpmoschi** [comment]
In my country there is a very common phrase "los 2 a la final"
It means that the 2 have enough entity and usability. They must could be able to coexist even in the FoxPro dialect

**Comment by cpyrgas** [comment]
Maybe all db functions that have to do or use arrays need to be redefined in the XSharp.VFP library as well (where they get priority over the ones defined in the other runtime libraries). And those functions would simply call the "original" functions, while only doing the xBase/VFP array conversions. Maybe even operator methods can be defined in the two array types to make automatic conversions from the one to the other?

**Comment by Karl1155** [comment]
Robert,

What´s missing is the handling of the declaration syntax: 

`LOCAL a1 AS ARRAY`

currently it can be used to create a VO Array, but Foxpro creates a logic var. i´m wondering if such a misleading declaration is widely used in the Fox community ? 

a PUBLIC declaration fails with the compile error XS9002: Parser: unexpected input 'AS'

`PUBLIC a2 AS ARRAY `


Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
The public and the private statements in all dialects BUT FoxPro do not support the `AS<type>` clause.
I  had overlooked that clause for FoxPro.
I will add the  `AS<type>` clause to support this in the FoxPro dialect, but this clause _WILL DO NOTHING_.
Both PUBLIC and PRIVATE variables are untyped (e.g. USUAL) in all XBase dialects.
Maybe I can use the  `AS<type>` clause in the editor for code completion (like FoxPro does).

Robert

**Comment by cpyrgas** [comment]
When Im trying to compile the syntax mentioned in the report:

**Comment by cpyrgas** [comment]
Confirmed fixed
