### ISSUE TITLE
NullReferenceException in XSharp.Rdd

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#849]
There is a hidden issue in the Create method of the `CDX.CdxOrderBagList` class that results in a NullReferenceException.
See screenshot:
![screenshot1](https://user-images.githubusercontent.com/64518775/141127981-4bb38677-15b1-4b97-ba5d-60e3353b8946.png)

If the `SELF:Add` method returns FALSE, then further control will reach the line of code:
`VAR lOk := oBag:OrderCreate(info)`
and raise an exception, since oBag is not initialized (NULL).

The Add method can return FALSE in the following case: if you pass the path to the index file in the short name style (DOS 8.3) to the Create method, NET operations (such as Path.GetDirectoryName), when passed in a short path, return a long path. As a result, two types of paths circulate within the algorithm in the Create method - short and long. As a result, a problem arises. For example, the next time a new tag is created in the same index file, the FindOrderBag method does not find the index file, although it already exists in the _bags collection, but with a short name.

**Comment by RobertvanderHulst** [comment]
Leonid,
What do you suggest ?
Should we convert the short file name to a long file name ?

**Comment by leon-ts** [comment]
Robert,
I ran into this problem when creating a temporary DBF file with an index in a temporary directory. The application has been transported to X# from VO, so the temporary directory in it is defined via the GetTempPath (WinAPI) function, which, in turn, uses environment variables (TMP, TEMP, etc.). And these variables contain the path in the short name format (this is how these variables were automatically created by Windows).

Since XSharp.Rdd is multiplatform oriented, I understand that you cannot call the GetLongPathName WinAPI function in it to convert the path to a long name. Therefore, I propose the following. At the beginning of the Create method, a check is made for the existence of the index file:
```
IF File(info:BagName)
    info:BagName := FPathName()
```
It automatically translates a short name into a long name (the FPathName function always returns a long name). The problem only arises when the CDX file does not yet exist and the File function returns FALSE. In this case, I suggest adding a special line that will do this conversion if the file does not exist (.NET methods such as GetDirectoryName also convert short name to long name.):
```
IF File(info:BagName)
    info:BagName := FPathName()
ELSE
    info:BagName := Path.Combine( Path.GetDirectoryName(info:BagName), Path.GetFileName(info:BagName) ) // Short name (MS-DOS 8.3) -> Long Name (if necessary)
ENDIF
```

**Comment by leon-ts** [comment]
I will add that the short name of the temporary folder can be generated by Windows (as an alias) if, for example, the user account name is more than eight characters. Otherwise, the short and long paths will coincide and the problem will not appear.

**Comment by cpyrgas** [comment]
Didn't have a repro sample, so will let Leonid confirm this

**Comment by leon-ts** [comment]
Guys,
The beta is not yet available, so I cannot check if the problem is fixed. I have so far looked at the changes in the "Fixes 849" link through the git browser. To be honest, I didn't see any fixes directly in the **CDX.CdxOrderBagList.Create** method where the problem was found.

I noticed that in this commit, the `IF File (...)` check was added to different methods, but in my opinion this is an unnecessary operation that will only slow down the methods, but add no benefit. Once again I draw your attention to the fact that the problem described in the ticket is specifically in the algorithm of the **CDX.CdxOrderBagList.Create** method when using the short file path format. By itself, the use of short file names (SFN) in Windows, including when it is processed in X# code, works without problems.

It's no secret that after the transition from unmanaged to managed code, developers are faced with an application performance issue. Therefore, we have to pay a lot of attention to this. In this regard, additional operations, even as simple as `IF File`, are undesirable if they are not needed. And in this case, they are not necessary. Therefore, I ask you to cancel this entire commit, if possible. And later I will provide you with a detailed test code example where this problem is reproduced so that you can directly detect the problem in the algorithm of the **CDX.CdxOrderBagList.Create** method.

P.S. I will be on vacation for New Year's holidays. Therefore, I will provide all the necessary materials in early January.

**Comment by RobertvanderHulst** [comment]
Leonid,

The IF File() checks are there because it is a simple way to fill the runtime slot where we can get the file name with FPathName(). There is probably a better / faster way but this works.
We share your concerns w.r.t. speed. You'll see in the next build that we have spend considerable time in the RDD since the last built to fix a few issues and improve the speed, both in exclusive but also in shared mode.

Robert

**Comment by leon-ts** [comment]
Robert,

Perhaps I did not quite clearly put it. I meant only those lines of code that were added in this commit ([Fixes #849](https://github.com/X-Sharp/XSharpPublic/commit/43942ea53d3eedd9024b194b7095d8b2e0f40f0e)) only for converting file names from SFN (DOS-8.3) to LFN (one of the examples is shown in the screenshot, new lines are highlighted in green). There is even a comment.

**Runtime/XSharp.Rdd/Dbf/AbstractMemo.prg**
![screenshot1](https://user-images.githubusercontent.com/64518775/147454195-fd39b424-a607-4d73-ba6f-e22079b6e666.png)

These lines did not exist before and they were added only to solve the SFN problem. But this is not necessary. NET (including X#) works great with SFN. You added these lines at my request to solve the problem in the **CDX.CdxOrderBagList.Create** method. But there was a misunderstanding. The only problem was in the code for the **CDX.CdxOrderBagList.Create** method.

P.S. In addition, in this particular code (in the screenshot), the full LFN path to the file can be obtained from an already open stream (if it is really necessary for other purposes):
`SELF:FileName := SELF:_oStream:Name`

**Comment by RobertvanderHulst** [comment]
I have adjusted this in the current build

**Comment by leon-ts** [comment]
Robert,
I see that the card has been moved to Closed. However, as promised, I made an example that reproduces the problem in version 2.9: [CreateOrderWithShortPathName.zip](https://github.com/X-Sharp/XSharpPublic/files/7880597/CreateOrderWithShortPathName.zip)

In the new version 2.10, this problem seems to be solved. The above example worked without errors.

**Comment by RobertvanderHulst** [comment]
Leonid,
Thanks for confirming
