### ISSUE TITLE
Mouse hint for members of VOSTRUCT doesn't work if Dot is used

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#851]
![image](https://user-images.githubusercontent.com/9467830/141249294-40896ea5-4bdd-4f3b-b72b-a0456ce77e3b.png)

Member completion after dot works fine, but mouse hint doesn't. And vice-versa - if colon is used, then mouse hint works fine, but member completion shows only Object's methods without structure's members.

**Comment by RobertvanderHulst** [comment]
Serrgio,

Can you check to see if the tooltip is shown when you enable the option "allow DOT for instance members" ?

Robert

**Comment by Serggio** [comment]
Yes, with the option "allow DOT for instance members" the tooltip works as expected, but I'd like to keep it off.

**Comment by RobertvanderHulst** [comment]
Serggio,
Sure, but that confirms what I was thinking.

**Comment by cpyrgas** [comment]
Confirmed fixed
