### ISSUE TITLE
The 'XSharp Project System' package did not load correctly

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#852]
In plain C# projects I get the following error:
![image](https://user-images.githubusercontent.com/20905638/141259830-b3fb480a-108c-4d68-aeee-f6ed8ec90e82.png)

I use the new version 2.9.1.1

**Comment by VolkmarR** [comment]
I can confirm this error.

**Comment by hpetriffer** [comment]
It works with the new version
