### ISSUE TITLE
'Easy' Language improvements

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#853]
- `ASYNC `modifier for functions
- `AS <type>` for `PUBLIC `declarations. These will be ignored by the compiler (PUBLIC variables are USUAL) but may be used in the editor

**Comment by cpyrgas** [comment]
Not sure if I am doing something wrong, but the following reports error XS9002: Parser: unexpected input 'AS'

FUNCTION Start() AS INT
PUBLIC test AS INT
test := 123

**Comment by RobertvanderHulst** [comment]
Did you use the FoxPro dialect?
This only works in that dialect.

**Comment by cpyrgas** [comment]
Ah, confirmed done!
