### ISSUE TITLE
Partial Classes with multiple summaries give compiler error xs1569

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#855]
For the following code, the Compiler (2.8c and 2.9a) creates the error 
`xs1569 - Error writing to XML documentation file: Failed to compare two elements in the array.`

```
///<summery>Dummy1</summery>
partial class Dummy
end class

///<summery>Dummy2</summery>
partial class Dummy
end class
```

The problem is caused by the second summary xml comment. I tried the same in c# and in that case, the xml file contains  2 summary nodes for the class, but doesn't give an error.

This imho is not urgent.

**Comment by leon-ts** [comment]
Volkmar,
I have previously described this error in this ticket: https://github.com/X-Sharp/XSharpPublic/issues/783

**Comment by VolkmarR** [comment]
Duplicate #783

**Comment by RobertvanderHulst** [comment]
The summaries will now be merged like in C#
