### ISSUE TITLE
Line Breaks in XML Comments using <br/> are ignored

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#858]
Currently line breaks in XML comments (using `<br/>`) are ignored. Here is an example

    /// <summary>Test for line breaks</summary>
    /// <remarks>
    /// Line 1<br/>
    /// Line 2<br />
    /// Line 3
    /// </remarks>

In X# code, the remarks are shown all in one line

![image](https://user-images.githubusercontent.com/9860916/141648769-8300ef97-effd-4a5e-b9f1-45874d2a1a4a.png)

In C# code, the remarks are shown with the line breaks
![image](https://user-images.githubusercontent.com/9860916/141648977-49c9df7d-b9d6-4feb-b73b-9c1675d5d8a1.png)

**Comment by cpyrgas** [comment]
Confirm fixed
