### ISSUE TITLE
VS Form designer problem with CHAR properties

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#859]
Attached solution has two forms, each containing a regular control and a control that contains a CHAR property (it's a custom control, but same problem exists with regular controls). 

After opening the form, one of them shows empty, while the other one displays other controls ok, but the custom control is displayed at location (0,0) with no caption, so apparently does not load correctly. When removing the assignment of the CHAR property from the code, the forms do open correctly again, until they are saved again.

[WindowsFormsApplication25.zip](https://github.com/X-Sharp/XSharpPublic/files/7532340/WindowsFormsApplication25.zip)

**Comment by cpyrgas** [comment]
Hmm, no it does not happen with ALL Char properties, for example the TextBox control has a PasswordChar property which is of Char type and it works fine. But the DevExpress TextEdit control which has a (hidden in sub options) Char option doesn't. The attached form opens empty:

[WindowsFormsApplication25.zip](https://github.com/X-Sharp/XSharpPublic/files/7532366/WindowsFormsApplication25.zip)

Removing the line from designer.prg below, allows it to load correctly:

SELF:textEdit1:Properties:MaskSettings:Set("placeholder", c'

**Comment by RobertvanderHulst** [comment]
Chris,
I'll look into the issue with the char literals tomorrow.


Robert

**Comment by RobertvanderHulst** [comment]
Chris,
I think the intellisense database for this solution dates from before my last change for the nested type.
Can you execute the "Rebuild Intellisense Database" menu option and try again ?

**Comment by RobertvanderHulst** [comment]
And I also noted that the character between the 2 quotes is char 0. That should have been coded as \0. I will fix that in the code generator

**Comment by cpyrgas** [comment]
Robert, both solutions are new ones, created as tests just before I opened the tickets. But I tried reindexing and also completely deleting the .vs fodler and I still have the same behavior. I guess you cannot reproduce this? Neither the one with the custom control or the DevExpress control?

Yeah, I forgot to mention this about the "null" char, this is also causing some trouble.

**Comment by RobertvanderHulst** [comment]
I could reproduce the problem with the custom control. In this case the encoding of the NULL character was the problem.
I am looking into the DevExpress control now as well.

**Comment by RobertvanderHulst** [comment]
Correction: you did not upload the DevExpress example. Both ZIPs in the message contain the same example

**Comment by cpyrgas** [comment]
Ah, sorry about that. But just checked and it is the same problem, has to do with the null character, so that should be covered now as well.

But my other sample (with custom controls) fails even without the null character, it fails with any character. But I will test again with your update and will report back.

**Comment by cpyrgas** [comment]
Confirmed fixed.
