### ISSUE TITLE
Error calling Rebuild Intellisense Database

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#865]
When you call the "Tools \ XSharp \ Rebuild Intellisense Database" menu, an error occurs (in the screenshot), after which the VS window remains empty (the solution and projects disappear). After restarting VS, the solution and projects are fine (not corrupted).

![screenshot1](https://user-images.githubusercontent.com/64518775/142017117-74f739dd-c830-4d20-861e-ce650ba53cc1.png)

X#: 2.9.1.1 (last build for 11/16/2021)
VS: 2019 (16.11.6)

**Comment by RobertvanderHulst** [comment]
Leonid,
Is there a space in the full filename of the solution ?

**Comment by leon-ts** [comment]
Robert,
Full path to solution file:
`D:\Projects\Visual Studio 2019\ComInTec-WinTU\WinTU\WinTU.sln`

**Comment by RobertvanderHulst** [comment]
I probably need to surround the file name with quotes. I’ll try to test that tomorrow.

**Comment by cpyrgas** [comment]
Confirm fixed
