### ISSUE TITLE
Periodic error when compiling defines

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#866]
Periodically, the following error occurs when compiling defines. Occurs 1 time in 10, in all versions of X#. Sometimes I need to call a rebuild several times for the error to disappear. Over time, it becomes very annoying.

**Error:**
![screenshot3](https://user-images.githubusercontent.com/64518775/142027399-07c3b098-dff6-41f3-a18b-8c3e965e5438.png)
**Defines:**
![screenshot1](https://user-images.githubusercontent.com/64518775/142027155-4f467ebe-6d59-4944-b063-181e78b3b2f2.png)
**Part of the code:**
![screenshot2](https://user-images.githubusercontent.com/64518775/142027224-24f65b97-3f9f-4097-8355-67b22472032d.png)

**Comment by RobertvanderHulst** [comment]
Please retest with 2.13. We have made some changes in the code that resolves DEFINES

**Comment by RobertvanderHulst** [comment]
Leonid,
Can you conform that this is fixed ?

**Comment by leon-ts** [comment]
Robert,
This error is hard to catch. As I wrote earlier - it occurs 1 time out of 10. I plan to install version 2.13 as a working version (I'm currently using 2.9.1.1) later this week. Before that, I installed beta version 2.13 and the problem was not observed (DEFINEs were compiled correctly). But to say for sure that the problem is fixed, I need to work with version 2.13 for a while.

**Comment by RobertvanderHulst** [comment]
Leonid,
Fair enough. I will close the issue for now. If you see it again, feel free to reopen it.

Robert
