### ISSUE TITLE
Generate XML comments

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#867]
Generate XML comments when the user types ///
Conditions:
- Cursor must be on a line before the start of an entity
- Cursor must NOT be before a comment line

**Comment by cpyrgas** [comment]
Confirmed done! Wow, intellisense for X# in VS is becoming really good!

**Comment by RobertvanderHulst** [comment]
Today I checked in a change so we also have intellisense etc for pseudo function that the compiler handles, such as PCOUNT(), ARGCOUNT(), _GETMPARAM() etc.
I am now generating a special PRG file in the .vs subfolder with source for these functions and including that in all VS projects (not in the source code for the compiler of course) so they can be handled like normal functions.
For example:

```
/// <summary>Return the name of an identifier as a string</summary>
/// <param name="expr">An Identifier. This could be the name of a variable or type.</param>
FUNCTION Nameof(expr AS OBJECT) AS STRING

/// <summary>Return the number of parameters that were passed to a function/method of the Clipper calling convention.</summary>
FUNCTION PCount() AS DWORD
```
![image](https://user-images.githubusercontent.com/14240939/142618750-65dc73f4-81dd-4bfc-b55b-09e832eed8ea.png)

**Comment by cpyrgas** [comment]
Tried it, that's also very nice!
