### ISSUE TITLE
Intellisense problem with a VOSTRUCT confusing (?) the parser 

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#868]
Following code does not produce member completion and hovering over the "TestClass" shows a tooltip "UNDECLARED TestClass"

By removing either the Foo vostruct or the bar class, it now works fine!

```
VOSTRUCT Foo
MEMBER mmm AS INT

CLASS bar
END CLASS

FUNCTION Start() AS INT
LOCAL oTest AS TestClass
oTest: // no member completion
RETURN 0

CLASS TestCLass 
EXPORT n AS INT
END CLASS

```

**Comment by cpyrgas** [comment]
Also a tooltip on SELF shows "LOCAL SELF AS Foo.TestClass", so apparently TestClass accidentally becomes a nested class.

There's one more bug but it's too tiny to open a new ticket for it, the SELF tooltip shows "LOCAL SELF"

```
VOSTRUCT Foo
MEMBER mmm AS INT

CLASS bar
END CLASS

CLASS TestCLass 
METHOD Test()
SELF:Test()
END CLASS
```
![intel24](https://user-images.githubusercontent.com/14542129/142609221-bb00be6b-6530-4cfa-ae73-014e51b7fed4.png)

**Comment by RobertvanderHulst** [comment]
I had seen that too (yesterday).
Will fix that later today.

**Comment by cpyrgas** [comment]
Confirmed fixed. Tooltip on SELF still says "LOCAL SELF...", but this is really minor.
