### ISSUE TITLE
Directory() function lists the current directory name twice 

### ISSUE THREAD

**Issue by wriedmann** [X-Sharp/XSharpPublic#87]
The function Directory() when called with the "D" parameter to list also the directory includes the current directory name twice (it should not be listed).

As example:
The folder c:\temp\dirtest contains only one file "xx.txt". 
The call 
`Directory( "C:\temp\dirtest\*.*", "D" )`
lists 3 entries: (
dirtest
dirtest
xx.txt

**Comment by RobertvanderHulst** [comment]
The same code in VO also returns 3 elements. The problem seems to be that the names of the first 2 elements are wrong. They should have been "." and "..". Will fix that.

Robert
