### ISSUE TITLE
Mouse tooltip for a class is shown as for a property with the same name

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#871]
![image](https://user-images.githubusercontent.com/9467830/143178994-4a837d75-0619-47ba-8d9d-6c24d75b525c.png)
Maybe it's already fixed, but it's worth checking.

**Comment by cpyrgas** [comment]
It indeed still exists, see the attached solution, it happens in this code:

```
FUNCTION Start() AS VOID

PARTIAL CLASS Window123 INHERIT DATADIALOG
	PROTECT oCCPushButton1 AS PUSHBUTTON
METHOD PushButton1( )
    SELF:oCCPushButton1:Image := Icon{}
END CLASS

```
[VOMDIApp19.zip](https://github.com/X-Sharp/XSharpPublic/files/7594873/VOMDIApp19.zip)

**Comment by RobertvanderHulst** [comment]
I think the parser sees the word Icon and matches it with the icon property of the window.
At that place I am retrieving all the tokens in the current buffer until the mouse pointer position.
I guess I'll have to tell it to include the curly brace after the current token as well, so it recognizes that Icon is a type.
I think it already does that for the left paren

Robert

**Comment by cpyrgas** [comment]
Confirmed fixed
