### ISSUE TITLE
Unequal approach to casting NET arrays to USUAL type

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#876]
Casting an array of type INT[] to type USUAL retains its original type. After that, you can easily perform the reverse conversion of the USUAL type to the current type. But if you use an array of type STRING[], then after casting to USUAL it becomes type ARRAY, which distorts the result and makes it impossible to simply convert back to the original type. In particular, the problem occurs when passing parameters to Rdd via the VoDbInfo function.

**Example:**
```
LOCAL u AS USUAL
LOCAL a1 AS INT[]
LOCAL a2 AS STRING[]

a1 := <INT>{ 1 }
u := a1 // OK
a1 := u

a2 := <STRING>{ "abc" }
u := a2 // NOT OK
a2 := u // Error
```

**Example (passing parameters through the VoDbInfo function):**
`VoDbInfo(DBI_SOME_CUSTOM_INFO, <STRING>{ "str1", "str2", ... })`

**Comment by RobertvanderHulst** [comment]
Leonid,
I am not sure why, but when you check the type of a1 with a1 is OBJECT[] then that is false, but a2 is OBJECT[] returns TRUE.
The following C# code also demonstrates that

```
         static void Main(string[] args)
        {
            int[] aint = new int[] { 1,2,3 };
            string[] astring = new string[] { "abc","def"};
            DateTime[] adates = new DateTime[] { DateTime.Now, DateTime.Now.AddDays(1)};
            Console.WriteLine(aint is object[]);
            Console.WriteLine(adates is object[]);
            Console.WriteLine(astring is object[]);
        }
```

This explains the difference. It seems that a .Net array of value types is never an object[]
When assigning a object[] to a usual then the usual type tries to convert the object[] array to a X# array

**Comment by RobertvanderHulst** [comment]
Both a1 and a2 return true for the `IS System.Array` expression

**Comment by leon-ts** [comment]
Robert,
I ran your example in C# and it does return interesting results (not quite expected in some cases). But to be honest, I didn't quite understand the problem. There is no use of OBJECT[] in my example. There is an explicit type STRING[]. If you use your example and write the following code in C#, it will return the expected result (true):
`Console.WriteLine(astring is string[]);`

**Comment by RobertvanderHulst** [comment]
The problem is inside the usual constructor where we are converting a object[] to a XSharp.__Array.
This is what happens for the string[] but not for the int[].
I can't really remember why we added that. I don't think Vulcan did that.
I'll remove that conversion for now.

**Comment by cpyrgas** [comment]
Fixed
