### ISSUE TITLE
Incorrect display of members of a class containing a nested enum

### ISSUE THREAD

**Issue by leon-ts** [X-Sharp/XSharpPublic#877]
The following class definition causes the nested enum to display incorrectly in VS 2019 (see screenshot):
```
CLASS Test

	HIDDEN oSomeField AS OBJECT

	METHOD DoSomething(ie AS InternalEnum) AS VOID STRICT
		RETURN

	/// <summary>Description of InternalEnum.</summary>
	HIDDEN ENUM InternalEnum
		/// <summary>Description of SomeItem1.</summary>
		SomeItem1
		/// <summary>Description of SomeItem2.</summary>
		SomeItem2
	END ENUM

END CLASS
```

**Screenshot:**
![screenshot1](https://user-images.githubusercontent.com/64518775/144260383-1f055634-1efb-495c-a1a6-2ff8727a0791.png)

**Comment by leon-ts** [comment]
Today I discovered that this problem is not related to nesting, but is due to the absence of the MEMBER keyword (which is allowed).

**Comment by RobertvanderHulst** [comment]
This no longer happens in our internal build (and it should also not happen in the VS 2022 preview that was uploaded earlier this week).

**Comment by cpyrgas** [comment]
Confirmed fixed.
