### ISSUE TITLE
Error running msbuild from command line

### ISSUE THREAD

**Issue by fxxm** [X-Sharp/XSharpPublic#879]
Running msbuild from the command line for an X# project I get the following error:

error MC1000: Unknown build error, 'The type init
ializer for 'XSharp.CodeDom.XSharpKeywords' threw an exception. Line 133 Position 3, Could not load file or assembly 'X
Sharp.VSParser, Version=2.9.0.0, Culture=neutral, PublicKeyToken=ed555a0467764586' or one of its dependencies. The syst
em cannot find the file specified.'

Presumably it should be looking for Version=2.9.1.1?

**Comment by RobertvanderHulst** [comment]
Fergus,
Is this a WPF project ?

**Comment by fxxm** [comment]
It is. I tried to create a sample to showcase the problem but I couldn't recreate it outside our main solution.

**Comment by RobertvanderHulst** [comment]
Fergus,
As a temporary solution: open a VS dev command prompt (as admin), navigate to the XSharp folder inside program files, then the subfolder Extension\Project. Type gacutil /i XSharp.VSParser.DLL.
That should fix it

**Comment by fxxm** [comment]
Thanks Robert, adding VSParser to the GAC does the trick

**Comment by cpyrgas** [comment]
@fxxm Can you please confirm this is fixed in the latest build, even without manually installing any files to the GAC?
