### ISSUE TITLE
Member completion problem with inherited exception types

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#884]
Exceptions inherited from System.Exception does not produce member completion. The System.Exception type itself does work fine.

```
FUNCTION Start() AS INT
LOCAL o AS DivideByZeroException
? o: // no member completion list shown
TRY
    LOCAL n := 0
    ? n / n
CATCH e AS System.DivideByZeroException
    ? e: // no member completion list shown   
END TRY
```

**Comment by cpyrgas** [comment]
I still have the same issue here, but I think this is because this fix was not included in the new set of dlls that I got today.

**Comment by RobertvanderHulst** [comment]
Yes, that will come in the next build.

**Comment by cpyrgas** [comment]
Confirmed fixed.
