### ISSUE TITLE
Using "array of" results to unexpected behaviour

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#885]
I have changed an existing code from "array" to "array of". This code had then suddenly stopped working. While searching for the cause, I noticed the following:

```
local aTest as array of Brw
local uBrw as usual

uBrw := Brw{}
AAdd(aTest, uBrw)
```

After the AAdd function the array ist empty. The Problem is that in this case the function "FUNCTION AAdd(aTarget AS ARRAY,uNewElement AS USUAL) AS USUAL" is used. The cause I think is, that it exists an implicit conversion from Array of to array, which results to an new array. Now the entry is added to the new array. 
I'm not sure if it is good that an implicit conversion exists. For old code bases it would be better that no implicit conversion exists, so at least the compiler can give an error if no possible function exists

**Comment by RobertvanderHulst** [comment]
Hans Joerg,
I will look into this. 
However, your code does NOT initialize the aTest array. Is that on purpose ?

**Comment by hpetriffer** [comment]
Sorry. It was only an example. I have forgotten to write the initialization

**Comment by cpyrgas** [comment]
Confirmed fixed
