### ISSUE TITLE
Improve XML generation

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#887]
The new /// XML generation feature works fine.
However if you have entered all the info and want to add a `<remarks></remarks>` section, so after the line with the `<params>` you type Enter followed by `/// ` then a new XML comment block is generated.
I think we should check to see if the /// is immediately following a line that is already a xml comment and then NOT generate a new XML comments.

And when you are there:
If you type Enter in the middle of a XML comment block, then it would be nice if the new line would also automatically start with ///.

**Comment by cpyrgas** [comment]
Confirmed done, very nice!
