### ISSUE TITLE
Strange behaviour with Warning XS8073

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#888]
On a Build, I got the Warning `Error XS8073: The result of the expression is always 'true' since a value of type 'DATE' is never equal to 'null' of type 'DATE?'`

After recompiling the solution, the warning was gone without any code changes.

I tried to reproduce the problem using the following code:

    var datum := DateTime.MinValue
    if datum != null
        datum := DateTime.Today
    end if 

But strangely I was not able to get the warning in Visual Studio 2019.

The same code in c# 

    var datum = DateTime.MinValue;
    if (datum != null)
        datum = DateTime.Today;

shows the warning.

**Comment by cpyrgas** [comment]
Volkmar, please check https://github.com/X-Sharp/XSharpPublic/issues/772, you need to set the compiler warning level to 5 (compiler option /warn:5), then the warning will be shown.

**Comment by VolkmarR** [comment]
That worked. Thanks
