### ISSUE TITLE
DBFNTX corruption problem

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#889]
Remco (Descartes) has shared an example when the DBFNTX driver fails.
Analysis showd that I had cached the CurrentStack variable in a local and forgot to update that local when returning from another NTX Method that updated the CurrentStack.
I have now deleted the CurrentStack and the problem is solved.
See commit d2ec771f3e581c88ac1475e2234635b70ee80677 for the code changes
And commit bd44a08a13659315e9ecd5cd7a94dfea239ed949 for a new unit test

**Comment by cpyrgas** [comment]
Confirmed fixed
