### ISSUE TITLE
VS Editor incorrect brace/paren/keyword matching in some cases

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#892]
Put the following code and put the caret in the beginning of line 3. When the caret is at colunm:

* 1, then the  opening and closing paren are highlited, which is probably correct
* 2, then the opening paren and "END CLASS" are being hihlited, which is of course wrong
* 5, then the "{" and the "}" are being highlited, which is also wrong

```
CLASS Child INHERIT DataDialog
METHOD TEst()
(  {    )
END CLASS
```

**Comment by cpyrgas** [comment]
Similar, this causes "(" and "ENDIF" to be matched. (for example when trying to type a type cast in the empty line)

```
function Start()
IF FALSE
(
ENDIF

```

**Comment by RobertvanderHulst** [comment]
The reason why parentheses, curly braces and brackets are highlighted in combination with endif and other open/close keywords is that we are marking these with the same ClassificationTag.
In retrospect these tags are not needed for the operators, so I have removed them. That solves the matching of operators with keywords.
I have looked at the code that is responsible for matching open and close keywords and I seem some room for improvement there too. I will work on that for a future build. I have added ticket #904 for that.

**Comment by cpyrgas** [comment]
The original problem is fixed, but unfortunately now keyword matching is very buggy. Try this for example:

```
FUNCTION Start()
DO CASE
CASE FALSE
CASE TRUE
IF FALSE
ELSE
ENDIF
END CASE

IF FALSE
    
IF FALSE
ELSE
ENDIF
        
ENDIF
```

and press the down arrow many times, to move through all the lines of code, you will see that almost every time, there is a wrong matching. For example, when the caret is on the ENDIF of line 7:

![Keyword_matching](https://user-images.githubusercontent.com/14542129/149225676-965a2d46-b3c3-4cf8-81ac-6162f39c6031.png)

**Comment by RobertvanderHulst** [comment]
This image shows 2 different things:
- matching of open/ close keywords ( else / end if)
- same word highlighting (all the endif words)

**Comment by RobertvanderHulst** [comment]
You can see that there are slightly different colors. You can set these colors in tools/ options

**Comment by cpyrgas** [comment]
Aaahh, ok :)
But I think there are still some (much less important) problems. When you select:
-The first IF, the ELSE is matched
-The first ELSE, then IF and ENDIF are matched
-The ENDIF, then ELSE is matched again

Similarly for the DO CASE..CASE..ENDCASE

**Comment by RobertvanderHulst** [comment]
At this moment it highlights one open/close pair  forward and one pair  backward.
Else ( and case) are marked as both open and close 
More is possible but needs additional work. I have already 
There is also no check for correct matches at this moment.
I have already created a ticket to improve this.

**Comment by cpyrgas** [comment]
Yeah, it is fine now. And the other remaining problem is really minor.
