### ISSUE TITLE
All VS projects have a "NuGet packages" entry in the References node

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#895]
This seems to happen in ALL projects, existing and new, no matter if they are using nuget packages or not

![NuGet_entry](https://user-images.githubusercontent.com/14542129/147072253-f5c5a0e4-dee3-4f75-add3-7d34eaf92196.png)

**Comment by RobertvanderHulst** [comment]
Yes, I am adding the node always. Is that too confusing ?

**Comment by cpyrgas** [comment]
Well, it definitely is to me at least :)

**Comment by cpyrgas** [comment]
I just checked c# and it does not seem to include that. But on the other hand, it always adds another node named "Analyzers", even though it is empty. So it's common in VS to do things like that I guess. I don't know, it was confusing to me, but then again I am not a VS user, so I leave this up to you.

**Comment by RobertvanderHulst** [comment]
I'll leave it for now, since this also shows people that we now support package references.
When it generates too much noise then I will hide it until there are packages installed

**Comment by RobertvanderHulst** [comment]
No noise, so closing this issue
