### ISSUE TITLE
ListView TextColor and TextBackgroundColor ACCESSes

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#896]
I currently review my old ListView code and noticed that I made some changes to the TextColor and TextBackgroundColor ACCESSes to make it work as expected.

The current ListView SDK sources are:

```
ACCESS TextColor 
	LOCAL dwCR AS DWORD

	dwCR := ListView_GetTextColor(SELF:Handle())

	RETURN Color{_AND(dwCR, 0x000000FF), _AND((dwCR >> 8), 0x000000FF), _AND((dwCR >> 16), 0x000000FF)}

ACCESS TextBackgroundColor 
	LOCAL dwCR AS DWORD

	dwCR := ListView_GetTextBkColor(SELF:Handle())

	RETURN Color{_AND(dwCR, 0x000000FF), _AND((dwCR >> 8), 0x000000FF), _AND((dwCR >> 16), 0x000000FF)}

```
If no color has been assigned both ListView_xxx() calls return always 0 which results in a black color. This works by accident for the Textcolor access since the Text system color is also black. There are several options to change the current behaviour. One of them looks like:

```
ACCESS TextColor  CLASS StdListView
LOCAL dwCR AS DWORD
 
 	IF ( dwCR := ListView_GetTextColor(SELF:Handle()) ) == 0xFF000000  
 		RETURN Color { GetSysColor ( COLOR_WINDOWTEXT ) }
 	ENDIF
 	               
 	RETURN Color { dwCR }  
       
       
ACCESS TextBackgroundColor CLASS StdListView
LOCAL dwCR AS DWORD 

 	IF ( dwCR := ListView_GetTextBkColor(SELF:Handle()) ) == 0xFF000000   
 		RETURN Color { GetSysColor ( COLOR_WINDOW ) }
 	ENDIF
 	                    
 	RETURN Color { dwCR }  
```

Karl-Heinz

**Comment by Karl1155** [comment]
Arrg ... forget what i wrote about the 0 results. 

The problem is that both ACCESSes return a black Color object as long as no color has been assigned.  To determine this, i added the comparison with 0xFF000000.

**Comment by cpyrgas** [comment]
Confirmed fixed
