### ISSUE TITLE
AccessViolation with new Version 2.10

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#899]
In the following code we get an access violaton at runtime. If you remove the cast, then everything works as usual. Unfortunately, there may still be several places like this in our system, because some typifications were added over time and some casts were forgotten to be removed. See also the comments in the code with the working statements

```
static func __AdjustNames   (phKey as ptr, cSubKey ref string)     as void 
       if ptr(phKey) = null_ptr // following statements are working: phKey = null_ptr, (ptr)phKey = null_ptr
           //
           //  Kein Hauptschluessel
           //  angegegen, Standardwert ist
           //  HKEY_CURRENT_USER
           //
              phKey := ptr(_cast, HK_CU)
       endif
```

![image](https://user-images.githubusercontent.com/20905638/148177713-4e453841-6365-46d0-bc73-a77371ce0fb7.png)

**Comment by cpyrgas** [comment]
What does "HK_CU" stand for in this code?

**Comment by hpetriffer** [comment]
It is defined as 
define HK_CR    := HKEY_CLASSES_ROOT

The error already happens when executing the If statement

**Comment by cpyrgas** [comment]
Ah, thanks, got it now. But then how are you calling this function, with what arguments? Because when I try this in VO:

__AdjustNames(HKEY_CLASSES_ROOT , c)

I also get a runtime error. (guess "PTR(phKey)" is trying to dereference the pointer?)

**Comment by hpetriffer** [comment]
The first call is:
`cRet := QueryRegString (HKEY_CURRENT_USER, SELF:GetSubKey(cSection), cEntry, cDefault)`

and QueryRegString
```
FUNC QueryRegString (hKey AS PTR, cSubKey AS STRING, cValueName AS STRING, cDefault AS USUAL)  AS STRING 
       __AdjustNames(@hKey, @cSubKey)
```

**Comment by cpyrgas** [comment]
Ok, so that should work, since it is indeed passing a pointer to the pointer and the PTR() command should dereference it. 

Looks like the problem has to do with passing an argument by reference with the @ operator and at the same time also pass the address of something in the same call. Robert, here's a full repro sample:

```
FUNCTION Start() AS VOID
LOCAL c := "test" AS STRING
LOCAL p AS PTR

p := 256
Test_1(@p) 		// works ok
Test_2(@p, @c) 	// System.NullReferenceException

p := 0x80000000
Test_1(@p) 		// also works ok
Test_2(@p, @c) 	// System.AccessViolationException: Attempted to read or write protected memory

FUNCTION Test_1(p AS PTR) AS VOID 
? p
? PTR(p)
FUNCTION Test_2(p AS PTR, c REF STRING) AS VOID 
? p
? PTR(p)
```

**Comment by RobertvanderHulst** [comment]
```
LOCAL c := "test" AS STRING
LOCAL p AS PTR
p := 256
Test_2(@p, @c) 
```
Would it help if the compiler simply refuses to compile this, so the customer would have to change this to

`Test_2(@p, REF c) `

**Comment by ArneOrtlinghaus** [comment]
If the compiler refuses this, then it should be ok for us to change the code. There shouldn't be many places like this in our programs. They are just difficult to find without the help of the compiler.

**Comment by hpetriffer** [comment]
I'm not sure if I understand it correctly. But if we have to change every @ with ref than we have a lot of places to change. Or it is only needed in the case with a ptr?

**Comment by cpyrgas** [comment]
Confirmed fixed
