### ISSUE TITLE
Missing compiler error when adding string and logic

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#90]
There's no compiler error in the code below. Note that this happens only with logic expressions, when trying to add a different datatype to string (INT, DateTime etc) a proper compiler error is reported.

```
FUNCTION Start() AS VOID 
	LOCAL c := "" AS STRING
	LOCAL l := TRUE AS LOGIC
	c := c + l
	c := c + FALSE
	c := c + (c == NULL)
	? c
RETURN	
```

**Comment by RobertvanderHulst** [comment]
Fixed
