### ISSUE TITLE
Help text is displayed incorrectly

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#900]
In the following text, "false" is not displayed for help
X#
![image](https://user-images.githubusercontent.com/20905638/148188913-53cf599e-6f24-466e-a7eb-72ff8d9b7ebb.png)

In c# it is displayed correctly
C#
![image](https://user-images.githubusercontent.com/20905638/148189059-9e88f9f0-8036-491a-af5c-26d48ea6081d.png)

**Comment by cpyrgas** [comment]
Confirmed fixed
