### ISSUE TITLE
Crash of Visual Studio with Version 2.10

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#901]
Since the installation yesterday morning, I have had 4 crashes of Visual Studio 2022 so far. Unfortunately, I have no wayto reproduce the error at the moment. In my opinion, the problem always happens as soon as Intellisense searches for something and wants to make a display. In this case, Visual Studio suddenly stops responding for about 10 seconds and then quits. This time I was writing the ":" in a list.

After restarting, Visual Studio displays the following message
![image](https://user-images.githubusercontent.com/20905638/148198472-a2cec98f-44dc-434c-8eb4-e603d0e3fb52.png)

In the event log there is only this info:
```
Name der fehlerhaften Anwendung: devenv.exe, Version: 17.0.31919.166, Zeitstempel: 0x61982ec5
Name des fehlerhaften Moduls: clr.dll, Version: 4.8.4300.0, Zeitstempel: 0x5f7e616e
Ausnahmecode: 0xc00000fd
Fehleroffset: 0x000000000016ba1e
ID des fehlerhaften Prozesses: 0x29174
Startzeit der fehlerhaften Anwendung: 0x01d8020fcccf435f
Pfad der fehlerhaften Anwendung: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe
Pfad des fehlerhaften Moduls: C:\Windows\Microsoft.NET\Framework64\v4.0.30319\clr.dll
Berichtskennung: d2882b41-cf70-41cc-b9e8-3556e42e4fd3
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 
```

**Comment by hpetriffer** [comment]
I have a MiniDump file of the crashes. If this helps I could provide this file

**Comment by hpetriffer** [comment]
Since yesterday morning I have had 7 crashes

**Comment by RobertvanderHulst** [comment]
@hpetriffer Yes, please send me the minidump

**Comment by hpetriffer** [comment]
In the meantime, I have also done tests with Vs2019. I have the same problems there too. I have send you links to the dump files with email

**Comment by hpetriffer** [comment]
The crash always occurs after entering a ":". The ":" can also be the beginning of an assignment after a space

**Comment by cpyrgas** [comment]
Can you please try deleting the ".vs" folder under your solution, or at least the *.xsdb files inside that? Does it make a difference, do you still get the crashes? This is the intellisense database for the solution (gets re-created after you delete it) and I have seen that sometimes it indeed leads to crashes, if there, something corrupted or so in this file.

You can also try from the VS menu, Tools->XSharp->Rebuild Intellisense Database, but if that still doesn't work, please also try deleting that folder/files to be sure.

**Comment by cpyrgas** [comment]
@hpetriffer are you using #ifdef directives in your code extensively? Most importantly, can you tell if you have #ifdef directives in the prg files that you are editing, when the crash occurs? Because we did find a problem today with such directives and Robert has fixed that already now, hopefully this is related to the crashes you are getting.

**Comment by hpetriffer** [comment]
I deleted the ".vs" folder, but then I also had crashes. 
Regarding the #ifdef, I need to check if they are currently being used in this case. We use them mainly in one project. As far as I remember, however, I often had crashes in files where there were certainly no #ifdef's.

**Comment by cpyrgas** [comment]
Can you please post the contents of a couple such files, together with info on where the crash happened (which line you were editing) and on which var you used ":" on? Maybe it can give a hint on what's causing the problem and we can reproduce here as well and fix it.

**Comment by hpetriffer** [comment]
I will send you the next files. The Problem is, that the crash after restarting Visual Studio does not happen anymore. I will try to make another dump during the crash. Normally it is blocking for some time and than crashes

**Comment by cpyrgas** [comment]
I am not getting any crashes after much testing that I did, but will let @hpetriffer confirm this one
