### ISSUE TITLE
Improve code for keyword pair matching

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#904]

**Comment by RobertvanderHulst** [comment]
- validate that only real matching pairs are highlighted
- for keywords that come with more than 2, always match all relevant tokens, so DO CASE, CASE, OTHERWISE, ENDCASE regardless of which one is highlighted.
The easiest way to do this is to extend the XsClassificationspan and add an identifier that is identical for all tokens that match. And then add a stack with the current active block.
A new open keyword creates an open XsClassificationspan  with a new id and pushes that on the stack
A middle keyword can then create a new span and copy the id from the top of the stack (when it matches with what's on the stack)
A close keyword can then copy the id from the top of the stack and pop the block from the stack.
The question of course is what to do when the middle or close keyword does not match the open keyword on the stack.
For example: The stack contains FOR and the ELSE keyword is found. This could mean 2 things:
- an IF is missing
- the FOR is inserted at the wrong place.
I suggest that we check 1 level further on the stack, so if the Stack contains first IF and then FOR , and an ELSE is found then we pop FOR from the stack (and maybe mark it with in the editor ?). If there is no match on the top or on the next then we should mark ELSE as incorrect.
It is probably the easiest to store the block info in the same location 
At the start of an entity (function, method etc) the block stack should be cleared.

The code that then highlights the keywords that form a group should match the keywords with the same block numbers and highlight them.

**Comment by RobertvanderHulst** [comment]
I have settled for the same way it is done in Visual Objects:
In a multi keyword block, like DO CASE, CASE, CASE, OTHERWISE, ENDCASE then highlighting one of the middle keywords (CASE or OTHERWISE) then the one before (middle or start) and the one after (middle or end) is highlighted,
When the start keyword is selected (DO CASE) then only the first middle keyword (CASE) is highlighted as well.
When the end keyword is selected (ENDCASE) then only the last middle keyword (OTHERWISE) is highlighted.
Of course the whole construct has a [-] marker so you can see that you can collapse the block

**Comment by cpyrgas** [comment]
Looking good!
