### ISSUE TITLE
DBFCDX: Soft seek does not respect OrdScope if no strict key is found

### ISSUE THREAD

**Issue by Serggio** [X-Sharp/XSharpPublic#905]
If there is a scope on a table then if soft seek doesn't find a strict match it goes to the next line, but it doesn't check whether this next line corresponds to the current scope. It should go to EOF if the next line is out of the scope.

**Comment by cpyrgas** [comment]
Confirmed, small sample showing the problem:

```
FUNCTION Start() AS VOID
LOCAL cDbf AS STRING

RddSetDefault("DBFCDX")

cDbf := "C:\DBF\TestScope"
FErase(cDbf + ".cdx")
DbCreate(cDbf, {{"FLD","C",10,0}})
DbUseArea(TRUE,,cDbf)
DbAppend()
FieldPut(1,"A")
DbAppend()
FieldPut(1,"B")
DbAppend()
FieldPut(1,"C")
DbCreateOrder("FLD",cDbf,"FLD")

DbOrderInfo(DBOI_SCOPETOP,,,"B")
DbOrderInfo(DBOI_SCOPEBOTTOM,,,"B")
DbGoTop()
? DbSeek("BB",TRUE) // false, ok
? RecNo(), Eof(), FieldGet(1) // 3, false, should be 4, true
DbCloseArea()

```

**Comment by RobertvanderHulst** [comment]
Fixes. Also in the DBFNTX driver. VO however positions the RDD at the "C" record and returns FALSE for EOF().
I think VO is wrong here.

**Comment by cpyrgas** [comment]
Confirmed fixed
