### ISSUE TITLE
Show include files that are used by a project in the VS project tree

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#906]
The VSParser now returns the include files that were read during parsing.
Investigate if we can show these in the Solution explorer

**Comment by RobertvanderHulst** [comment]
Serrgio,
We have thought about that too (like C# does). 
The potential problem with that is that this could negatively impact the performance of the Solution Explorer.
So if we do that, then it'll be optional.

**Comment by cpyrgas** [comment]
Looking good!
