### ISSUE TITLE
Wrong #ifdef branch is shown as active

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#909]
If I have an project with a definition WINFORMS. In the following code the first branch is shown as active. It is not considered that Winforms is defined

```
FUNCTION Start() AS VOID STRICT
	local u := {1,2} as usual
	if (u is array var val)
		foreach var elem in val
			Console.WriteLine("array")
		next
	endif
#ifndef WINFORMS
	Console.WriteLine("Not Winforms")
#else
	Console.WriteLine("Winforms")
#endif
	WAIT
	return
```
[XSharpTests.zip](https://github.com/X-Sharp/XSharpPublic/files/7868607/XSharpTests.zip)

**Comment by Serggio** [comment]
> with a definition WINFORMS

make sure it is defined with ```#define``` and not ```DEFINE```

**Comment by hpetriffer** [comment]
We use the project settings

**Comment by hpetriffer** [comment]
It seems that the compiler gets also confused with the defines. We have a runtime problem. I will check if I can make an example

**Comment by RobertvanderHulst** [comment]
Hansjoerg,
You can have different defines for the debug and release builds.
Is this define included in both build configurations ?

**Comment by hpetriffer** [comment]
It is really strange. Yes we have defined it in both configurations. We have made some rebuilds. After some changes the problem was going away...But I don't understand why. In the attached example solution do you see the problem? In our case the wrong #ifdef branch is displayed

**Comment by RobertvanderHulst** [comment]
With which build of the compiler / vs integration are you seeing this ?
And with which version of VS?
I would not be surprised if this happened in VS2022 in the first 2.10 build. But it should not happen in the build from yesterday.

**Comment by hpetriffer** [comment]
I use the newest Build 2.10.1. I know that in the example the debug-switch is only inside the debug configuration. I use only that. I have also restarted VS a few times. The behaviour does not change.
This is a screenshot after restarting VS:
![image](https://user-images.githubusercontent.com/20905638/149514352-e7ea6c3d-d277-49d0-8d9e-241b8d999385.png)
This after inserting a line (var test4 := ..)

![image](https://user-images.githubusercontent.com/20905638/149514451-98d00619-6b6a-48f4-89e9-576759fd4941.png)

This are the defines:
![image](https://user-images.githubusercontent.com/20905638/149514537-dae76ac6-4f5c-477e-b9d1-3ef22154b1dd.png)

**Comment by hpetriffer** [comment]
In the last version of X# 2.10.3 I have the same problem with the program file. I have closed and reopened the file, but nothing changes
![image](https://user-images.githubusercontent.com/20905638/149718257-c327dcbb-3307-4005-99aa-0e4a44ba0bfd.png)
![image](https://user-images.githubusercontent.com/20905638/149718297-35b60344-ef04-469a-ba86-7f8e997eef3d.png)

**Comment by cpyrgas** [comment]
Trying to test this, I am trying to enter a new define in this option of the project settings as shown in the above screenshot, but I have not managed to make it work for the Debug configuration, after reopening the project properties, my new define has disappeared. When I choose the Release configuration, then adding it usually works (but not always - did not figure when it does and when not).

**Comment by RobertvanderHulst** [comment]
Chris,
You may have to move the cursor from the defines textbox to another control to force it to be saved.

**Comment by RobertvanderHulst** [comment]
Ah, I think I understand what's happening: I am caching the parse options for a project (for performance reasons).
Apparently when you change the define this does not trigger the parse options to be recreated.
I expect that after you change the define, when you change VS (in the toolbar) from the Debug to the Release configuration and then back to Debug then it should recreate the parse options and the new define should be used.
If not then I will have to look at this again, but I do not want to delay this release for that.

**Comment by cpyrgas** [comment]
Still doesn't seem to work. Actually the value is saved in the .xsproj file, but when opening the project properties it is not visible. Also I indeed still see the reported behavior above, the #ifdef does not "see" the define

**Comment by cpyrgas** [comment]
Forgot to mention, in the Release configuration (in which the define is shown correctly in the project properties window), the #ifdef code highliting does work fine, at least with today's update. Seems the problem is only in Debug.

**Comment by RobertvanderHulst** [comment]
This sounds like a corruption in the project file. I think there is more than one property for the preprocessor defines in the debug configuration.
Can you mail me you project file ?

**Comment by cpyrgas** [comment]
Done, sent two different solutions!

**Comment by cpyrgas** [comment]
Seems to be working now with the newest update Robert sent me, but I'm gonna let Hanjoerg confirm this fix, when testing with his own solution.

**Comment by hpetriffer** [comment]
For me it works also

**Comment by cpyrgas** [comment]
Confirmed fixed then!
