### ISSUE TITLE
Wrong ENDIF expected

### ISSUE THREAD

**Issue by fforay** [X-Sharp/XSharpPublic#911]
In FoxPro Dialect, with Late Binding activated.
This code mimics some existing and exported VFP code.

The following method will raise two errors : 
Line 6, Parser: unexpected input 'IN'
Line 07, Syntax Error, ENDIF expected

**To Reproduce**
01 METHOD CheckMe() AS USUAL
02 LOCAL aFiles
03 LOCAL M.lcFile
04
05 IF VARTYPE(THIS._TempEMFFile)="O"
06 	FOR EACH M.lcFile IN aFiles
07		IF FILE(M.lcFile)
08			DELETE FILE (M.lcFile)
09		ENDIF
10	ENDFOR
11 ENDIF

It would be better to indicate that we cannot use a USUAL in a FOREACH.
The ENDIF missing is a false positive.

**Comment by fforay** [comment]
Same thing....

**Comment by RobertvanderHulst** [comment]
Strange, the error is a parser error. At that stage the compiler has not determined that aFiles is a USUAL.
What happens if you change ENDFOR to NEXT ?

**Comment by fforay** [comment]
;) Exactly the same... in fact, when I had change FOR EACH to FOREACH, I had already tried that.

The only solution I've found is to suppress the LOCAL declaration and put a VAR in front of the var used in the enumeration

**Comment by RobertvanderHulst** [comment]
I'll check it out asap

**Comment by fforay** [comment]
This sample is producing the same kind of error message : 
		METHOD CheckMe() AS USUAL
			LOCAL liALeft, liATop
			IF TRUE
				IF TRUE
					NOP  // <-- Missing ENDIF
				ELSE
					IF liALeft#TRUE OR liATop#TRUE
						NOP
					ENDIF
				ENDIF
			ENDIF
		END METHOD

The first one that appears is the Missing ENDIF, and it seems to be due to the # used as <> without any space
BTW, the other error here is Parser: unexpected input '#TRUE'
Here it was confusing because the use of # was more than one hundred lines after the error message (Missing ENDIF)

What is strange, and that's the same for the previous sample, is that the second error message doesn't appears in "normal" but does in the sample, just as if there was too many code between the error and the error-message.
HTH

**Comment by RobertvanderHulst** [comment]
Fabrice,
#TRUE matches our symbol rule.

**Comment by fforay** [comment]
In the original code, it was compared to a field and the trouble was the same : I changed it to True just for the sample

**Comment by RobertvanderHulst** [comment]
Is there a space before the # chat?
If not then I can change the lexer to assume that the # means !=

**Comment by fforay** [comment]
No spaces before or after the # char.

**Comment by RobertvanderHulst** [comment]
No spaces after the # char, that was clear to me. Otherwise this would not have matched with the symbol rule.
But no spaces before might help in detecting that this is not a symbol but a not equals operator.
I'll see what I can do.

I can also decide not to recognize literal symbols at all in the FoxPro dialect. But that would mean that in the FoxPro dialect you would have to use String2Symbol where this is needed (or we need to invent a special new way to declare literal symbols, like for example `##Symbol`).

**Comment by RobertvanderHulst** [comment]
Fabrice,
The problem with the code was that the parser expects one of these:
- IMPLIED M.lcFile 
- VAR M.lcFile 
- M.lcFile  AS <sometype>
I will change the compiler to make the type optional. In that case the iterator will be of the type USUAL. The compiler will generate a unique iterator name for the FOREACH iterator and will add an assignment statement to the block in which the iterator is assigned to the variable that is in the FOR EACH statement.
So this will become something like 

```
FOR EACH uniquename AS USUAL IN aFiles
    M.lcFile := uniquename
    // original block
ENDFOR
```

I will also fix the problem with the # character

**Comment by fforay** [comment]
I don't have the code in hands now, but I remember in the original VFP code, the var used in the Foreach was declared at the beginning of the method

Télécharger Outlook pour Android<https://aka.ms/ghei36>
________________________________

**Comment by cpyrgas** [comment]
Confirmed fixed.
