### ISSUE TITLE
Conditional Build 

### ISSUE THREAD

**Issue by fforay** [X-Sharp/XSharpPublic#912]
In FoxPro, you can use :
#IF nExpression1 | lExpression1 

#ELIF nExpression1 | lExpression1 

#ENDIF 

where 
nExpression1 is a numerical expression; if nonzero, the code is compiled

lExpression1 is a logical expression; if true, the code is compiled

**Comment by RobertvanderHulst** [comment]
Fabrice,
The problem with the foxpro construct is that they allow this:
```
#If SYS(3004) = "1033"
? "Locale ID is English"
#Elif SYS(3004) = "1034"
? "Locale ID is Spanish"
#Elif SYS(3004) = "1031"
? "Locale ID is German"
#Elif SYS(3004) = "1036"
? "Locale ID is French"
#Endif 
```
There is no way that we can make the preprocessor handle this.
This is another example where FoxPro lives in its own universe.
The docs say this:
**_Conditionally includes source code at compile-time._**
But if I compile the foxpro code on an English machine and then run it on a French machine, what would be the result ?

In theory we could translate this into a normal IF but that would bean that `#endif `has to be interpreted as a `#endif` in combination with `#ifdef` and as `ENDIF `in combination with `#if`
It is not impossible, but again one of those things that you try to avoid as much as possible.

An #if condition based on a #define would be no problem of course.

**Comment by Danila2903** [comment]
Robert, 
> There is no way that we can make the preprocessor handle this. 
So, you're not going to make XBase++ preprocessor handle #if either?

**Comment by RobertvanderHulst** [comment]
@Danila2903 we can implement #if preprocessor commands, but only with conditions based on information that is available when the preprocessor runs.
The condition 
`#If SYS(3004) = "1033"`

from the FoxPro helpfile is a condition that can only be evaluated at runtime.

**Comment by Danila2903** [comment]
@RobertvanderHulst We use #if in the following code:
```
#if XPPVER < 1900000
    // there is no keyword "final" in v.1.8
    #translate final class => class
#endif
```
Could you please implement command #if for that kind of data?

**Comment by cpyrgas** [comment]
Confirmed done
