### ISSUE TITLE
Intellisense does not show any information for a class (Go to definition does not work)

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#914]
DrawToolbox is not recognised in the following class. DrawToolbox is defined in the global namespace inside another included assembly. "go to definition" does not work either. I have the feeling that intellisense in version 2.10.x works less often than before.

![image](https://user-images.githubusercontent.com/20905638/149721157-7663eb52-8f38-4655-a6fd-1bcb00131d41.png)

```
class clsTestSkala inherit DrawToolbox

    // Balkendiagramm
    protect _nUpdateCnt as dword
    protect _nMaxUpdateCnt as dword


    constructor(nUpdateCnt, nMaxUpdateCnt) clipper
        // Initialisierung
        _nUpdateCnt := nUpdateCnt
        _nMaxUpdateCnt := nMaxUpdateCnt
        return

        // Methoden

    method Draw(eventArgs as DevExpress.XtraGrid.Views.Base.RowCellCustomDrawEventArgs) as logic
        self:Init(eventArgs)
        if (_nUpdateCnt == 0)
            self:FillRectangle(self:GetColor(230, 230, 230), self:Left, self:Top, self:Width, self:Height) // nicht verfügbar
        else
            self:FillRectangle(self:GetColor(255, 80, 80), self:Left, self:Top, self:Width, self:Height) // rot

            var width := eventArgs:Bounds:Width
            if _nUpdateCnt < _nMaxUpdateCnt
                width := int(((1.0*width) / (1.0*_nMaxUpdateCnt)) * (1.0*_nUpdateCnt))
                self:FillRectangle(self:GetColor(170, 240, 170), self:Left, self:Top, width, self:Height) // Grün
            endif
        endif

        self:DeInit()
        return true
end class
```

Inside the database the DrawToolbox item exists correctly. If it helps I can provide the solution

**Comment by RobertvanderHulst** [comment]
HansJoerg,
I can't really replicate this. Can you attach the example ?

**Comment by hpetriffer** [comment]
Unfortunately, I can't manage to recreate this example now either. The code in this area has changed some and there it works now. I am closing the issue now. If I have such an example again I open a new one
