### ISSUE TITLE
Improve code generation and error handling for BEGIN SEQUENCE .. END 

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#916]
The current implementation of BEGIN SEQUENCE .. RECOVER USING .. END SEQUENCE is not completely compatible with VO.
The problems in the implementation are:
- when the BREAK command is used then a value is sent to the RECOVER USING statement wrapped in a WrappedException  object. This value is extracted and assigned to the variable declared in the RECOVER USING line. 
- However, when a real exception occurs and this real exception causes the RECOVER USING to be reached then that error is "swallowed" by the code inside RECOVER USING.
- code without a RECOVER USING also swallows exceptions.

Unfortunately we can't simply change this because people may depend on the current behavior.

Proposed solution:

1. Create a compiler option to switch between the current solution (the default) and a new improved solution
2. For code that contains a RECOVER USING, check for wrapped exceptions. When the exception is not a wrapped exception then call a function in the runtime (for now I propose `FUNCTION _SequenceError(e as Exception) AS USUAL` that can process the error. It could for example call the error handler, or throw the error
3. When there is no RECOVER USING clause , then the compiler should generate one and from within this generated clause detect if the RECOVER was reached with a wrapped exception or a normal exception. For wrapped exceptions it would have to get the value and call a special function in the runtime like `FUNCTION _SequenceRecover(uBreakValue as USUAL) AS VOID`. When the generated recover is called with a 'normal' exception then _SequenceError from the previous bullit should be called

**Comment by cpyrgas** [comment]
With a quick first look, this looks very nice! But will do some more thorough testing.

Robert, do you plan to make this compiler option affect also code without BEGIN SEQUENCE statements at all, to make also this more compatible to VO? As discussed earlier by either automatically creating one in every method or even every line of code? (and call the "global" event handler when an exception happens)

**Comment by RobertvanderHulst** [comment]
Chris,
My first intention was to have a method that no longer "eats" exceptions for BEGIN SEQUENCE commands without RECOVER.
The other option (to wrap every statement) is a bit more work. I am looking at that right now.

**Comment by RobertvanderHulst** [comment]
Updated docs and added compiler option on the Project Properties page

**Comment by cpyrgas** [comment]
This is looking very promising! Will need of course testing from users in more "real" conditions, but confirmed for now!

**Comment by cpyrgas** [comment]
Note for future reference: Related to https://github.com/X-Sharp/XSharpPublic/issues/111 and https://github.com/X-Sharp/XSharpPublic/issues/881
