### ISSUE TITLE
XBase++ preprocessor: #include doesn't include file to .ppo

### ISSUE THREAD

**Issue by Danila2903** [X-Sharp/XSharpPublic#920]
I have a problem with translating .prg with XSharp preprocessor. My code has some memvar variables in .ch file. XBase preprocessor includes them into .ppo file and XSharp preprocessor doesn't. The same goes with functions and procedures. It seems that preprocessor doesn't see any code without '#'

## To Reproduce
1. Create test.ch, test.prg
2. Include test.ch in test.prg
3. Call
`xsc.exe -ppo -cs test.prg`

## Files:
** **test.ch**
```
memvar Temp_Memvar 

procedure tempProcedure()
    local tempppp := 0
return

function zeroFunction()
    local zero := 0
return zero

#define T1 1
```

** **test.prg**
```
#include "test.ch"
procedure main()
    local t1 := T1
return
```

### Expected:
** **test.ppo generated with XBase++ preprocessor:**
```
#line 1 "test.prg" 
#line 1 "test.ch"@"test.ch" 
memvar Temp_Memvar

procedure tempProcedure()  
local tempppp := 0
return

function zeroFunction()
    local zero := 0
return zero

#line 1 "test.prg" 
procedure main()
    local t1 := 1
return
```

### Actual:
** **test.ppo generated with XSharp preprocessor:**
```
//PP #include "test.ch"
procedure main()
    local t1 := 1 //need to run xsc.exe with -cs key, otherwise it will be 'local 1 = 1'
return
```

**Comment by RobertvanderHulst** [comment]
This is only an omission in the ppo output. The exe that is produced does have the tempProcedure and the zeroFunction.
W.r.t. the t1 verus T1:
The compiler option /vo8 controls the case sensitivity of the preprocessor. When /vo8 is enabled then the preprocessor is case INsensitive. If you compile this without /vo8 then preprocessor is case sensitive, just like the Xbase++ preprocessor

**Comment by cpyrgas** [comment]
The contents of test.ch are indeed included in the .ppo now, but except for that, there are also being included also around 650 lines from the standard .xh include files like XSharpDefs.xh, which makes it very difficult to review the .ppo. Is this as intended?

**Comment by kpa174** [comment]
I propose to do it by analogy with the xBase preprocessor. It removes all lines with comments and ppo directives (starting with #). For example, if the first line of the source is
```
#include "test.ch"
```
The result will be like this. Note that the std.ch is included by default.
```
#line 1 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\STD.CH"@"STD.CH" 
#line 1 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\Set.ch"@"Set.ch" 
#line 1 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\natmsg.ch"@"natmsg.ch" 
#line 18 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\Set.ch" 
#line 40 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\STD.CH" 
#line 1 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\Get.ch"@"Get.ch" 
#line 45 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\STD.CH" 
#line 1 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\Prompt.ch"@"Prompt.ch" 
#line 50 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\STD.CH" 
#line 1 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\Memvar.ch"@"Memvar.ch" 
#line 56 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\STD.CH" 
#line 1 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\collat.ch"@"collat.ch" 
#line 61 "S:\IBS\SDK\XBASE\XPPW32_190\INCLUDE\STD.CH" 
#line 1 "test.prg" 
#line 1 "test.ch"@"test.ch" 
```

**Comment by RobertvanderHulst** [comment]
Binary compatibility with the Xbase++ preprocessor for the .ppo files was never our intention. Even if we could achieve that, then the preprocessor would most likely not be binary compatible with Harbour or Visual Objects.
The most important thing I think is that you can see now which code was included.
Removing comments and ppo directives will make it more difficult to use a diff tool to compare the PRG and the PPO file.

**Comment by kpa174** [comment]
> Binary compatibility with the Xbase++ preprocessor for the .ppo files was never our intention. Even if we could achieve that, then the preprocessor would most likely not be binary compatible with Harbour or Visual Objects.

Yes, of course. There was no mention of this.

> The most important thing I think is that you can see now which code was included. Removing comments and ppo directives will make it more difficult to use a diff tool to compare the PRG and the PPO file.

The most important thing I think is compiling the PRG and the PPO should give identical results.

**Comment by cpyrgas** [comment]
Personally I do not like it as it is now, it makes it extremely difficult to use the .ppo for preprocessor debugging purposes. But this is not a bug, just annoying due to my personal preferences, so I'm leaving it up to you to close the ticket if you think it's OK.

**Comment by cpyrgas** [comment]
It's A LOT better now. A much smaller issue is now ALL .ppo output file will contain the following lines in the beginning, lines which are redundant of course. Maybe it could be hardcoded so that such lines pointing to the standard X# .xh include files and to the actual prg being currently parsed can be also omitted?

```
#line 1 "C:\Program Files (x86)\XSharp\Include\XSharpDefs.xh"
#line 1 "C:\Program Files (x86)\XSharp\Include\set.xh"
#line 60 "C:\Program Files (x86)\XSharp\Include\XSharpDefs.xh"
#line 1 "C:\Program Files (x86)\XSharp\Include\dbcmd.xh"
#line 63 "C:\Program Files (x86)\XSharp\Include\XSharpDefs.xh"
#line 1 "C:\Program Files (x86)\XSharp\Include\CustomDefs.xh"
#line 65 "C:\Program Files (x86)\XSharp\Include\XSharpDefs.xh"
#line 1 "<path to actual prg file>\myppotest.prg"

```

**Comment by cpyrgas** [comment]
Robert,
OK, fair enough!
