### ISSUE TITLE
XBase++: #DEFINE case sensitivity by default

### ISSUE THREAD

**Issue by Danila2903** [X-Sharp/XSharpPublic#921]
By default, XBase is case insensitive, except preprocessor _#define_ directives. It differentiates between upper and lower case (https://doc.alaska-software.com/content/fdc_xpplrm_hashdefine.html, Description). However, XSharp doesn't.
In XSharp we can use _'-cs'_ key while compiling files, but it will cause case sensitivity in general, not only with using _#define_.
Could you possibly create some new key, e.g. _'-csDef'_ which will differentiate case sensitivity in _#define_, but only there?

**Comment by cpyrgas** [comment]
What is the state of the "Compatible preprocessor" option in the "Dialect" page of the project settings? When this is disabled, then the preprocessor is case insensitive, for example this would report an error if you uncheck it:

```
#define wrongCASE 123
FUNCTION Start() AS VOID
? WrongCase // error XS0103: The name 'WrongCase' does not exist in the current context
RETURN


```

**Comment by Danila2903** [comment]
cpyrgas
I send '-dialect:xBase++' to xcs.exe as parameter

**Comment by cpyrgas** [comment]
@Danila2903 What is the full command line you pass to the compiler?

**Comment by Danila2903** [comment]
@cpyrgas I pass the following command:
`xsc.exe @option.txt test.prg`

in file option.txt I have following options:
```
-dialect:xBase++
-lb -memvar -vo1 -vo5 -vo8 -vo15 -vo16 
-reference:"C:\Program Files (x86)\XSharp\Redist\XSharp.Core.DLL" 
-reference:"C:\Program Files (x86)\XSharp\Redist\XSharp.RT.DLL" 
-ppo
-cs
```

**Comment by cpyrgas** [comment]
@Danila2903 Yes, that's it, it's the -vo8 option that makes the preprocessor case in-sensitive. Removing this will make it case sensitive again, but maybe you need this enabled for another reason?

**Comment by Danila2903** [comment]
@cpyrgas Thank you! No, that's my bad - I've been testing different compiler options and left some of them. Next time I'll use them more carefully!

**Comment by cpyrgas** [comment]
Ah, great, glad it's working ok now for you!
