### ISSUE TITLE
Problem with "." if a class name with the same name as the local variable exists

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#922]
It is not possible to compile the following code:

```
class TestClass
	public property Ret as string get "xyz"
end class

function Start() AS VOID STRICT
        var TestClass := TestClass{}
        Console.WriteLine(i"{TestClass.Ret}")
	TestClass.Test()
        return
```

Here you get the errors:
- An object reference is required for the non-static field, method, or property 'TestClass.Ret'
- An object reference is required for the non-static field, method, or property 'TestClass.Test()'

"Allow dot for instance members" is activated. Dialect is "Visual Object"

**Comment by RobertvanderHulst** [comment]
I assume your example misses the method Test() inside TestClass ?

**Comment by hpetriffer** [comment]
And also the **Property Ret** inside the interpolated string

**Comment by RobertvanderHulst** [comment]
Fixed

**Comment by cpyrgas** [comment]
Confirmed fixed
