### ISSUE TITLE
Formatting of do while does not work

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#923]
If you use the formatter, the block inside of "do while" is not intended

X# 2.10.3
VS 2022
```
	do while recNo <= iLastRec
	recNo++
	enddo
```

**Comment by cpyrgas** [comment]
I'm still seeing the same problem, when using Format Document, the contents inside the DO WHILE command get indented in the same column with "D".

Note that if "WHILE" is used instead of "DO WHILE", then Format Document works correctly.

**Comment by cpyrgas** [comment]
Confirmed fixed
