### ISSUE TITLE
This question remains

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#924]
This question remains
- If you set the scope to A .. G and then enable OrdDescend(), then you expect that the GoTop goes to G and GoBottom to A. So should the runtime automatically switch the scopes?
- Or should with the scope A .. G active the effect be that the area appears empty because these scopes are in the wrong order ?

_Originally posted by @RobertvanderHulst in https://github.com/X-Sharp/XSharpPublic/issues/918#issuecomment-1014698337_

**Comment by cpyrgas** [comment]
Ticket created by accident
