### ISSUE TITLE
XBase++: inline access | assign method

### ISSUE THREAD

**Issue by Danila2903** [X-Sharp/XSharpPublic#926]
## Problem №1
I have XBase++ projects with lots of _inline access_ and _inline access assign_ methods.
As far as I know, in order to compile them in _X#_ I need to declare them in class and then implement outside the class.
But is there another solution? If not, are you going to implement _inline access_ and _assign_ methods?

## Problem №2. Unexpected Behaviour
I'm not sure if it is a bug, but I've had problems with methods declaration and implementation. 
If I have only _access_ keyword, this code compiles:
```
//this code compiles:
class Example
exported:
    method doStub
endclass

access method Example:doStub()
return NIL
     
procedure main()
return
```

If I use _access assign_, it doesn't compile (unexpected input '_assign_'):
```
//this code doesn't compile
class Example
exported:
    method doStub
endclass

access assign method Example:doStub()
return NIL
     
procedure main()
return
```

But when I move _access assign_ to declaration, it compiles again:
```
//this code compiles:
class Example
exported:
    access assign method doStub
endclass

method Example:doStub()
return NIL
     
procedure main()
return
```

All 3 examples can be compiled in _XBase++_ compilator. 
Should I put _access_ only in declaration too and nothing more? Which way of putting _assign_ and _access_ keywords right?

**Comment by RobertvanderHulst** [comment]
Danila (is that your name ?),
Thanks for the examples. 
- INLINE ACCESS is not documented in the Xbase++ help file. Do you have an example of how that is supposed to work ?
- ACCESS ASSIGN should work. The rule in the parser is declared as
```
xppproperty         : (Attributes=attributes)?                                    // NEW Optional Attributes
                      (   Access=ACCESS Assign=ASSIGN?                            // ACCESS | ASSIGN  | ACCESS ASSIGN | ASSIGN ACCESS
                        | Assign=ASSIGN Access=ACCESS?
                      ) 
                      Modifiers=xppmemberModifiers?                               // [CLASS]
                      M=METHOD Id=identifier                                        // METHOD <MethodName>
                      (VAR VarName=identifier)?                                   // [VAR <VarName>]
                      (AS Type=datatype)?                                         // NEW Optional data type
                      end=eos
                    ;
```
I think this is a problem in the lexer where it sees the ASSIGN keyword after ACCESS as an Identifier (name). I'll check into this.

**Comment by Danila2903** [comment]
Robert,

If you are asking about compiling _inline access assign_ code, I've modified example from documentation (https://doc.alaska-software.com/content/stmt_xpplrm_access_pipe_assign.html, section **Examples** -> **ACCESS methods**)
```
class Days
exported:
    var date

    inline method init
        ::date := date()
    return self

    inline access assign method date(dDate)
        if Valtype(dDate) == "D"
            ::date := dDate
        endif
    return ::date
endclass
     
procedure main()
    LOCAL oD := Days():new()
    ? oD:date
    ? oD:date := Date()+3
return
```
This code compiles and executes with XBase++ compiler. So, the behaviour is the same as in documentation, you just put method body to declaration

**Comment by RobertvanderHulst** [comment]
Thanks for the example. We'll make sure that X# can do this as well.

**Comment by cpyrgas** [comment]
The original sample provided:

```
//this code doesn't compile
class Example
exported:
    method doStub
endclass

access assign method Example:doStub()
return NIL
     
procedure main()
return
```

does not compiler, causes a compiler error:

`xpp.prg(7,15): error XS1501: No overload for method 'Example.doStub$Method()' takes 1 arguments`

**Comment by RobertvanderHulst** [comment]
Chris, 
What is the setting for the compiler option vo5?
Background info:
the compiler creates a DoStub property with a getter that calls method$doStub() and a setter that calls method$doStub(value). So the method has to have a parameter or has to have clipper calling convention.

**Comment by cpyrgas** [comment]
Robert,
Ah, OK, with /vo5+ or with supplying a param it works as expected.
