### ISSUE TITLE
XBase++: Method declaration with parentheses

### ISSUE THREAD

**Issue by Danila2903** [X-Sharp/XSharpPublic#927]
XBase++ compiler allows us declare method with parentheses. It is not documented, but my compiler compiles following script:
```
class Example
exported:
    method doStub(arg)
endclass

method Example:doStub(arg)
return NIL

procedure main()
return
```

However, for XSharp I need to modify it, so that declaration doesn't contain parentheses:
```
class Example
exported:
    method doStub
endclass

method Example:doStub(arg)
return NIL

procedure main()
return
```
otherwise I have an error XS9002: mismatched input '(' expecting {IS, IN, COMMA, EOS}

Is it possible to allow to use parentheses in method declaration? In my company we used to use both of the variants and this feature would help us a lot.

**Comment by RobertvanderHulst** [comment]
Yes we can support that too. 
Aargh, why is the documentation never up to date and why is everybody (not just you) using undocumented features...

**Comment by RobertvanderHulst** [comment]
The IS and IN appear in the error list because of the clauses `[IS <MethodName>] [IN <SuperClass>] `
I will implement parameters (that are ignored and do not have an `AS <type>`) but not when you use these clauses

**Comment by cpyrgas** [comment]
Confirmed fixed
