### ISSUE TITLE
Url-encoded values being written to VS 2022 project file

### ISSUE THREAD

**Issue by fxxm** [X-Sharp/XSharpPublic#928]
In VS 2022, if you save a macro (e.g. $(SolutionDir) ) to a field that accepts a macro e.g. "Additional include paths", the value written to the project file is url-encoded. 

 $(SolutionDir) is saved as %24%28SolutionDir%29

![image](https://user-images.githubusercontent.com/38910169/150156467-abfc5ac4-1a86-43e8-9b49-02a3a995a1e3.png)

![image](https://user-images.githubusercontent.com/38910169/150156581-0735ced8-a034-4237-a06a-37065ca7d61d.png)

Although it looks fine, the compiler then can't find the intended path.

**Comment by RobertvanderHulst** [comment]
For now I would recommend to directly edit the project files for these constants. I will not fix this for 2.10 but I will try to fix it in the build after that.

**Comment by cpyrgas** [comment]
Confirmed fixed
