### ISSUE TITLE
COPY STRUCTURE TO command 

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#931]
there´s no problem to compile this code. 

```
// VO-Dialect /ppo+

// note: both commands are part of the dbcmd.xh 

/*

#command COPY STRUCTURE TO <(file)> [FIELDS <fields,...>]           ;
      => DbCopyStruct( <(file)>, { <(fields)> } )

#command COPY STRUCTURE EXTENDED TO <(file)>                      		;
      => DbCopyXStruct( <(file)> )
*/      

FUNCTION CopyStructureTo_Command() AS VOID 
LOCAL cPfad AS STRING 	

	RddSetDefault ( "DBFCDX" ) 
	
	cPfad := "D:\TEST\" 
	
	COPY STRUCTURE TO ( cPfad + "struccopy.dbf") // FIELDS "LAST"	 		
	
	RETURN 
```

- now activate the FIELDS clause and you´ll see the error

error XS9002: Parser: unexpected input 'STRUCTURE'

- now activate the embedded "COPY STRUCTURE" commands. The error disappears and as expected the command is translated to: 

DbCopyStruct( cPfad + "struccopy.dbf" , { "LAST" } )

btw.  i disabled in the dbcmd.xh the "COPY STRUCTURE EXTENDED TO" command, but that doesn´t help. 

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
Which version  of X# ?

Robert

**Comment by Karl1155** [comment]
Robert,

the version is:

2.10.0.0 

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
The command should be changed to 

```
#command COPY STRUCTURE TO <(file)> [__DBFIELDLIST__ <fields>]          ;
      => DbCopyStruct( <(file)>, <fields> )
```

We now have a common FIELDS clause for many DB operations that translates FIELD <list> and optional wildcard matches (for FoxPro) into an array of fields

**Comment by cpyrgas** [comment]
Confirmed fixed.
