### ISSUE TITLE
WED cannot find cavowed.inf file, when opening windows from a nested folder

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#934]
Currently the VO editors search for the .inf and .tpl files in subfolders and in the parent folder of the folder that contains the current binary entity. But if the window/menu etc is located in a subfolder more than two levels deeper than the main solution, then this is not enough and the file cannot be found. Ideally the search should start from the main solution folder, will need information from the project system for that.

**Comment by VolkmarR** [comment]
We are getting more and more errors in our projects due to this problem. Is it possible to integrate this bug into the next version?

**Comment by cpyrgas** [comment]
Volkmar, what is the exact structure of your solution, where is the xsfrm and where the inf/tpl files? Just to make sure we do cover your case.

**Comment by VolkmarR** [comment]
Here's an example, where we face this issue...

RxMasterData (Project)
  Article (Folder)
    ArticleInfo (Folder)
      dtaArticleInfo.prg
        dtaArticleInfo.dtaArticleInfo.xsfrm
        dtaArticleInfo.dtaArticleInfo.rc

**Comment by cpyrgas** [comment]
OK, thanks, I will add some code to search in parent directories.

Although there's a quick workaround that you can use, put the inf and tpl files in:

<ProgramFiles>\XSharp\Templates

and from there they should be visible to ALL your projects

**Comment by cpyrgas** [comment]
Should be working now

**Comment by RobertvanderHulst** [comment]
Confirmed fixed
