### ISSUE TITLE
VS parser incorrect recognises classes one next to the other as nested to each other

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#939]
Given this code:

```
BEGIN NAMESPACE LAWFControls

PUBLIC CLASS Class1 INHERIT System.Windows.Forms.TextBox
	CONSTRUCTOR() STRICT
	PROTECTED OVERRIDE METHOD OnEnter(e AS EventArgs) AS VOID
	PROTECTED OVERRIDE METHOD OnLeave(e AS EventArgs) AS VOID
END CLASS

PUBLIC CLASS Class2 INHERIT System.Windows.Forms.CheckBox
	CONSTRUCTOR() STRICT
	PROTECTED OVERRIDE METHOD OnEnter(e AS EventArgs) AS VOID
	PROTECTED OVERRIDE METHOD OnLeave(e AS EventArgs) AS VOID
END CLASS

END NAMESPACE
```

the entity combox in the toolbar shows those members:

![VS_editor_classes](https://user-images.githubusercontent.com/14542129/151640283-11b408e4-cd7c-43b5-9f2e-32e710078398.png)

so it looks like it incorrectly thinks that class2 is a nested class of class1.

Apart from the editor/intellisense related problems, this also causes trouble in the form designer as well. In this small solution that uses custom controls in a form:

[WindowsFormsApplication1.zip](https://github.com/X-Sharp/XSharpPublic/files/7962661/WindowsFormsApplication1.zip)

the form cannot be opened in the designer, with an error message "Duplicate declaration of member 'lawfCheckBox1'". This is caused by the same problem as above, as there are two custom control classes in a prg file. Workaround is to put each class in its own BEGIN...END NAMESPACE block, this seems to solve the problem both in the editor and in the form designer. Like this:

```
BEGIN NAMESPACE LAWFControls
PUBLIC CLASS Class1 INHERIT System.Windows.Forms.TextBox
END NAMESPACE

BEGIN NAMESPACE LAWFControls
PUBLIC CLASS Class2 INHERIT System.Windows.Forms.CheckBox
END NAMESPACE

```

**Comment by RobertvanderHulst** [comment]
[XSharpModel.zip](https://github.com/X-Sharp/XSharpPublic/files/7966860/XSharpModel.zip)

**Comment by RobertvanderHulst** [comment]
The upload fixes the problem. Copy to the "c:\Program Files (x86)\XSharp\Extension\Project" folder and run the deploy.. cmd files in the "c:\Program Files (x86)\XSharp\Extension\Uninst" folder. Also replace the XSharp.VsParser.Dll in the GAC folder c:\Windows\Microsoft.NET\assembly\GAC_MSIL\XSharp.VSParser\v4.0_2.10.0.0__ed555a0467764586

**Comment by cpyrgas** [comment]
Confirmed fixed!
