### ISSUE TITLE
Error writing to cursor that is returned from SqlExec()

### ISSUE THREAD

**Issue by jpmoschi** [X-Sharp/XSharpPublic#948]
Hello boys , this's me traying to understand and help to solve problems in the last Xsharp revision. This issue, It is an old one and apparently difficult to solve 
 **scatter / gather array functions**

The short example is 
```
if SqlExec(_handle, "Select * from Table WHERE c1= 1" ,"mtmp")
   if reccount()>0 
      mbuff := __ScatterArray( iif( .F. , NIL , NIL ), .F. )
      DbSelectArea( "mtmp" )
      DbAppend()
       __GatherArray(mbuff , IIF( .F. , NIL , NIL ) )
   endif 
endif
```
In the ScreenCapture you can see the call stack. In my opinion the problem is that the operator ASTYPE return null because it can`t detect the type inheritance when try to convert the type RddFieldInfo correctly returned by the function _GetColumn() to the type DbfColumn INHERIT RddFieldInfo. 

Any guide to advance? 
Best regards 
Juan

![Captura](https://user-images.githubusercontent.com/36513811/152224674-65f1ce7d-893e-4b9f-9566-f03ecee1ebdb.PNG)

**Comment by RobertvanderHulst** [comment]
Juan Pablo,
In the future, please include a full working example. 
Your example shows 
`IF SqlExec(...)`

This is not from your real code, because SqlExec() returns a number and not a logic. This would never compile.

However I did find a problem in the DBFVFPSQL RDD when writing values.
The method PutValue should be changed to:

```
OVERRIDE METHOD PutValue(nFldPos AS INT, oValue AS OBJECT) AS LOGIC
            // nFldPos is 1 based, the RDD compiles with /az+
            var result := FALSE 
            IF nFldPos > 0 .AND. nFldPos <= SELF:FieldCount
                var row := _table:Rows[SELF:_RecNo -1]
                row[nFldPos-1] := oValue
                result := TRUE
            ENDIF
            RETURN result
```
At this moment the method ends with `RETURN SUPER:PutValue(..)` and that is incorrect.

**Comment by jpmoschi** [comment]
ok, i understand the problem and continue testing.... I detected another one related with field names bigger than 10 chars and/or data type timestamp columns. 
If you prefer y could try to correct and send you a pull request.

**Comment by RobertvanderHulst** [comment]
Juan,
See my mail to Daniel. 
I would like to see the complete list of issues first

**Comment by jpmoschi** [comment]
Robert,
I did a source code review of the DBFVFP , DBFVFPSQL classes and some related ones. With the idea of ​​contributing to the project, I mention some FoxPro features that can make a difference; if they were taken into account in development, just ignore the comment. They are only intended to take into account some peculiarities of FoxPro and give early warning of some compatibility problems:

- The use of the DBC database in FoxPro is not mandatory. In our case we decided never to use them, the class DBFVFP must consider it

> DBFVFP and DBFVFPSQL support null values in fields definition
> You can create a table with fields that support null values and then 
> sqlexec (1, "select fieldnull, * from mytable","mytable")
>    replace all fieldX with null  // if the definition non support null values, error !!!
> ... And then you can copy the table and the table definition support the null value 
>   copy to freetable 
>   select 0
>   use freetable 
>   ?  fieldnull
>   null 

- DBFVFPSQL support field names biggest than 10 characters , DFFVFP supports field names <= 10 characters

> when you copy a DBFVFPSQL to DBFVFP, the column name is truncated to 10 characters
> ? sqlexec(1,"select timestamp_column , * from mssqltable","sqlresult")
> ? type ("timestamp_column")    // Memo (binary) but really is 8 bytes fixed length 
> M
> copy to FreeTable.dbf
> select 0
> use FreeTable 
> ? TYPE("timestamp_") 
> M
> 
> The timestamp_column does not exist in the new FreeTable. It changed to adapt to DBF header format
> 
> RddFieldInfo  METHOD BlankValue()
> DateTime and Date default values has particularities. The minimum default value is like this
> * FoxPro test in Command Window: 
> = SQLEXEC(1,"set dateformat dmy")
> SET CENTURY ON
> SET date BRITISH
> =SQLCONNECT("SOME_MSSQLSERVER")
> =SQLEXEC(1,"select CAST('01-01-0001' as datetime) as tsql","tsql")
> ? tsql, YEAR(tsql), MONTH(tsql), DAY(tsql)
> 01/01/1900 12:00:00 AM 1900  1  1 
> But in the class DBFVFP, when you create an empty row with empty date or datetime,  the value is as your common sense indicates. Look:
> * in a created dbf free table work area 
> append blank
> ? dtField, YEAR(dtField), MONTH(dtField), DAY(dtField)
>   /  /     AM 00:00:00  0   0   0
> ? dateField, YEAR(dateField), MONTH(dateField), DAY(dateField)
>   /  /       0   0   0

- TimeStamp column particularities

> FoxPro treats timestamp fields as memo (binary). It is not a sortable field but it is possible to do it this way (elemental or combined fields expression like a CODEBLOCK in xsharp ):
> INDEX on CAST(timestamp_column as char(8)) TAG cl1

Have a nice weekend 
JP

**Comment by RobertvanderHulst** [comment]
Juan,
- For DBFVFP DBC files are optional as well. When reading the DBF header, the RDD checks to see if there is information about an attached DBC. When there is, then the DBC is opened (in another datasession) to read (longer) field names, captions etc. When there is not then the field names from the header are used.
- Nullable fields are supported too. If the table has a nullable field (this is stored in the flags byte for the fields in the header) then this is respected.  If you create a new table with DbCreate you can also create nullable fields by adding a modifier to the field type. Something like {"ADDRESS","C:0",80,0} means a character field of length 80 which may be null. We also support other characters after the colon. 'B' means binary, '+' means autoincrement, 'U' means Unicode. I know that this is not documented very well, we will take care of that
- I am not sure what you mean with the empty values for DateTime and Date in SqlExec() cursors and Free tables.
- I assume for your TimeStamp remark you mean a SQL TimeStamp column?

**Comment by jpmoschi** [comment]
Good morning Robert, I answer your comments hoping to be clearer in what I mean:

- Timestamp: I am talking about the MS SQL Server data type. When a cursor (SQLDBFVFP) contains a TimeStamp field. If you want to copy the cursor to another table (DBFVFP) (Copy to T.DBF), the created MEMO file (T.FPT) will contain the binary values ​​of the timestamp field in 8 bytes (not field value is lost)

- With reference to the SqlServer DateTime data type: (FoxPro natively supports 8-byte DateTime, (not DateTime2) for historical reasons, it originates from its predecessor SyBase) treats DateTime fields by placing time 0 in 1900-01 -01. You can´t send to RDBMs the dot.net the value DateTime.MinValue
