### ISSUE TITLE
APrinters() function - Foxpro enhancement.

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#952]
it seems that the function i already posted in the forum got somehow lost, so I add it here. Attached is a zipped Fox viaef with a untyped APrinters() function that mimics the VFP behaviour.

The x# version i´m using is: 2.10.0.3 
[VFPAPrinters.zip](https://github.com/X-Sharp/XSharpPublic/files/8002727/VFPAPrinters.zip)

Karl-Heinz

**Comment by cpyrgas** [comment]
Confirmed done and tested
