### ISSUE TITLE
Ctrl+Space (Edit.CompleteWord) should work always

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#957]
At the moment, Ctrl+Space only seems to work only directly after a dot (or :). Actually it should work at any time

**Comment by cpyrgas** [comment]
This is indeed actually working now. Completion is not triggered automatically on typing chars, but when pressing CTRL+SPACE, it does show the expected list of symbols.

**Comment by RobertvanderHulst** [comment]
Hansjoerg,
Can you confirm that this is fixed ?

**Comment by hpetriffer** [comment]
It works now, But I have found some issues where it is not working correct. I will create a new issue, because it is different
