### ISSUE TITLE
DBSetIndex() in DBFNTX for VO compatibility should(?) change the active order only when it opens the first index file

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#958]
In the following code, VO prints 1,3/1,3. When enabling the DbSetOrder(0) line, then it prints 1,3/1,2.

So apparently in VO/DBFNTX, DBSetIndex() changes the controlling order (after opening an index file), only when there was no other index file opened before (no matter what the actual controlling order is). If opening a 2nd, 3rd etc index file, the controlling order remains as it was before.

In X# currently it works differently, DBSetIndex() seems to always change the active controlling order to match the newly opened index. I really do not like VO's behavior, but I think it should be emulated (at least in VO dialect only?), because it does break existing code (see https://www.xsharp.eu/forum/public-vo-vn/2906-problem-with-searching-for-expression-on-ntx-index#21542)

```
FUNCTION Start() AS VOID STRICT
LOCAL cDbf AS STRING
cDbf := "C:\test\testntx"

RddSetDefault("DBFNTX")

DbCreate(cDbf,{{"FLD","N",5,0}})

DbUseArea(TRUE,,cDbf)
DbCreateIndex(cDbf + "1", "FLD")
DbCreateIndex(cDbf + "2", "-FLD")
DbSetIndex(cDbf + "1")
DbSetIndex(cDbf + "2")
DbAppend()
FieldPut(1,1)
DbAppend()
FieldPut(1,2)
DbCloseArea()

DbUseArea(TRUE,,cDbf)

DbSetIndex(cDbf + "1")
DbGoTop()
? FieldGet(1)

// DbSetOrder(0) // even when using this, VO still does not change the controlling order with the next DbSetIndex()

DbSetIndex(cDbf + "2")
DbGoTop()
? FieldGet(1)

DbCloseArea()
```

**Comment by RobertvanderHulst** [comment]
Chris,
Please note that in the example above:

```
DbCreateIndex(cDbf + "2", "-FLD")
DbSetIndex(cDbf + "1")
DbSetIndex(cDbf + "2")
```
The second DBSetIndex() fails (returns FALSE), because DBCreateIndex() leaves "testntx2.NTX" open, so the first DbSetIndex() adds the index testntx1.NTX to the already open list 
Can you create a test case for this ?

**Comment by RobertvanderHulst** [comment]
Please note that X# was emulating the (incorrect) behavior from Vulcan before

**Comment by cpyrgas** [comment]
Confirmed fixed.
