### ISSUE TITLE
Strange Problem with Winforms Designer releated to VS2022

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#959]
I have a strange Problem with the Windows Designer in Visual Studio 2022. The Winforms Designer works fine with our solution in VS2019 with X# 2.10.0.3. When I open the same solution in VS2022, the Winforms Designer won't open and shows the Error 

![image](https://user-images.githubusercontent.com/9860916/153913764-ff960a8d-b600-4fc7-bc52-2854f70173f0.png)

I tried to create a example solution to reproduce this problem, but I was not able to reproduce it with some simple forms.

Is there any logging that I can activate to help you identify the issue in VS2022?

**Comment by VolkmarR** [comment]
I managed to reproduce the problem. We have to compile our projects as Platform Target X86. That is the cause.
[XSharpWinformsTest.zip](https://github.com/X-Sharp/XSharpPublic/files/8109667/XSharpWinformsTest.zip)

**Comment by VolkmarR** [comment]
It is probably relegated to this problem... https://developercommunity.visualstudio.com/t/WinForms-NET-Framework-Projects-cant-d/1601210

**Comment by RobertvanderHulst** [comment]
Volkmar,
I think you are right. The DLLs and projects that you have referenced need to be x64 or AnyCpu to be used by the 64bit form designer for Windows Forms (when you target the .Net Framework).
I am afraid there is not much we can do about this.
So you will have to either
- design the forms in VS2019
- change the processor from x86 to AnyCpu or x64 in the referenced projects.
