### ISSUE TITLE
VO incompatibility with priority resolving DBF field name vs class property

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#962]
Not sure if this is worth adjusting this, but it indeed broke existing VO code: https://www.xsharp.eu/forum/public-vo-vn/2906-problem-with-searching-for-expression-on-ntx-index#21545

The following code in VO prints DBF_FIELD, iVar, DBF_FIELD, while X# prints DBF_FIELD, iVar, Access. So VO gives priority to the DBF field over the same named access, while X# gives priority to the access. On the other hand, VO gives priority to the field over the dbf field, something which also X# does.

```
// /memvar+ /undeclared+
FUNCTION Start() AS VOID STRICT
LOCAL cDbf AS STRING
cDbf := "C:\test\test.dbf"

DbCreate(cDbf,{{"CONFLICT","C",10,0}})
DbUseArea(TRUE,,cDbf)
DbAppend()
FieldPut(1,"DBF_FIELD")
? CONFLICT // DBF_FIELD, ok
? ClassIvar{}:Test() // iVar, ok
? ClassAccess{}:Test() // DBF_FIELD in VO, Access in X#

DbCloseArea()

CLASS ClassIvar
	PROTECT CONFLICT := "iVar" AS STRING
	METHOD Test()
	RETURN CONFLICT
END CLASS

CLASS ClassAccess
	ACCESS CONFLICT
	RETURN "Access"
	METHOD Test()
	RETURN CONFLICT
END CLASS
```

**Comment by RobertvanderHulst** [comment]
This will be difficult to resolve.
In Visual Objects you can refer to fields inside a class without using the SELF: prefix. To access properties in VO you always must use the SELF: prefix.
This difference does not exist in Roslyn.
The quickest solution to avoid this kind of problems is to enable the compiler option that makes SELF: mandatory.
See https://www.xsharp.eu/help/opt-enforceself.html
and
https://www.xsharp.eu/help/proppage-language.html

**Comment by cpyrgas** [comment]
Agreed, ticket closed.
