### ISSUE TITLE
ADS ACE-Functions

### ISSUE THREAD

**Issue by ecosSystem** [X-Sharp/XSharpPublic#966]
Hi Robert,

could you please implement the ACE-functions

- AdsSetTableTransactionFree
- AdsGetFTSIndexInfo

 TIA
Karl

**Comment by ecosSystem** [comment]
Can I test it anyhow ? If you send me the implementation ?

**Comment by RobertvanderHulst** [comment]
You can download the source for the RDD from GitHub.
The change is in the Runtime branche (not yet in the main branche).
Or you simply include the ACE, ACE32 and ACE64 classes in your code.

Robert

**Comment by RobertvanderHulst** [comment]
Karl
I would try something like this

```
FUNCTION BytePtrLen(bp as byte ptr) as long
local nLen := 0 as long
if bp == NULL_PTR
   return 0
endif
do while bp[1] != 0
    nLen ++
    bp++
enddo
return nLen
```

`And then System.Text.Encoding.Default:GetString(ppucField, BytePtrLen(ppucField))`

or if you want to use encoding from the X# runtimestate

`XSharp.RuntimeState.WinEncoding:GetString(ppucField, BytePtrLen(ppucField))`

**Comment by ecosSystem** [comment]
Hi Robert,
after some mor tests I think the correct implementation if AdsGetFTSIndexInfo is

``_DLL FUNC AdsGetFTSIndexInfo(	hIndex AS IntPtr,;
										pucOutput AS BYTE[],;
										pulBufLen REF DWORD,;
										ppucField OUT BYTE PTR,;
										pulMinWordLen OUT DWORD,;
										pulMaxWordLen OUT DWORD,;
										ppucDelimiters OUT BYTE PTR,;
										ppucNoiseWords OUT BYTE PTR,;
										ppucDropChars OUT BYTE PTR,;
										ppucConditionalChars OUT BYTE PTR,;
										ppucReserved1 AS BYTE[],;
										ppucReserved2 AS BYTE[],;
										pulOptions OUT DWORD)  AS DWORD:ACE32.AdsGetFTSIndexInfo``
as the BYTE PTR's ppucField, ppucDelimiters... all point to pucOutput which should ten be a BYTE[].
With this definition I get reasonable results fpr all parameters.

Karl
