### ISSUE TITLE
Hard to find errors in the include files

### ISSUE THREAD

**Issue by kpa174** [X-Sharp/XSharpPublic#967]
**Is your feature request related to a problem? Please describe.**
It's impossible to tell from error messages where the source is if it's in an include file. For example, if _example.prg_ contains the following line #13:
```
// common.ch - Some commonly used directives from Alaska Software (xBase++)
#include "common.ch"
```
X# gives the following error:
```
example.prg(13,10): error XS9003: Pre-processor: Identifier expected
```
It's impossible to understand which line in _common.ch_ contains an error, and which one. Through long experiments, we managed to establish that this is a string:
```
#define  TRUE   .T.
```

**Describe the solution you'd like**
We suggest that X# indicate in the error message the name of the included file, which can be nested in another, and the line and position within this file.

**Comment by cpyrgas** [comment]
Confirmed fixed.
