### ISSUE TITLE
New InputBuffer class should release data for DBF when DBF is closed

### ISSUE THREAD

**Issue by RobertvanderHulst** [X-Sharp/XSharpPublic#968]
The new inputbuffer class for DBF files keeps the data for tables that are closed.
A customer has code that overwrites DBF file after closing it and after reopening the file the RDD uses the "old" data and not the new data from the file that did overwrite the original file.

**Comment by RobertvanderHulst** [comment]
Fixes in e16e4a95a68bab76bdb4048842493946914759e8

**Comment by cpyrgas** [comment]
Robert, looks good, but can't reproduce this problem with the previous version of the runtime either, so I will let you close it.

**Comment by RobertvanderHulst** [comment]
I have created a unit test for this. The problem happens when the file is closed, overwritten and reopened when the GC had no time to clear the buffer from the cash. In that case the new file was "inheriting" the old buffer
