### ISSUE TITLE
Missing warnings for signed/unsigned conversions

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#971]
In the following code, VO reports a warning "overflow or loss of data possible converting xxx -> yyy", for all assignments, except for the ones with BYTEs. Which is clearly inconsistent, the intended behavior probably was to report a warning in ALL cases, but VO is VO...

In X#, when /vo4- is disabled, then there's an error reported for ALL lines, which is correct.

When /vo4+ is enabled, then there's no error, which is also correct. But there's not a single warning reported either! I think in older builds, warnings were being reported for such conversions, when /vo4+ was enabled, but not absolutely sure, so I am logging this for investigation/consideration.

```
FUNCTION Start() AS VOID
LOCAL n AS INT
LOCAL d AS DWORD
LOCAL b AS BYTE
LOCAL w AS WORD

d := n
n := d

b := n
b := d
b := w

w := n
w := d
```

**Comment by RobertvanderHulst** [comment]
Only narrowing warnings age now shown. DWORD <-> LONG is not reported.

**Comment by cpyrgas** [comment]
Actually I am getting always errors now, no matter if vo4 is enabled or not. In the original sample, only the first two lines do not produce errors (XS0266: Cannot implicitly convert type x to byte/word)

**Comment by cpyrgas** [comment]
Confirmed fixed
