### ISSUE TITLE
GetRValue(), GetGValue() and GetBValue() functions.

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#972]
Robert,

i noticed that the mentioned funcs are implemented in the VOWin32ApiLibrary, but this dll is "x86" only.

https://github.com/X-Sharp/XSharpPublic/blob/07d1f3456576f46aeb81e07352ad902b99502805/Runtime/VOSDK/Source/VOSDK/Win32_API_Library_SDK/WinGDI.prg#L1212

- wouldn´t it make sence to move the funcs to the XSharp.RT, 
- instead of the currently used casts i suggest to use this code.

```
FUNCTION GetRValue ( rgb AS DWORD ) AS BYTE 
RETURN System.Drawing.ColorTranslator.FromWin32( (INT) rgb):R	
	
FUNCTION GetGValue ( rgb AS DWORD ) AS BYTE 
RETURN System.Drawing.ColorTranslator.FromWin32( (INT) rgb):G		

FUNCTION GetBValue ( rgb AS DWORD ) AS BYTE 
RETURN System.Drawing.ColorTranslator.FromWin32( (INT) rgb):B	
```

what do you think ?

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,

> FUNCTION GetRValue ( rgb AS DWORD ) AS BYTE 
> RETURN System.Drawing.ColorTranslator.FromWin32( (INT) rgb):R	
> 	
> FUNCTION GetGValue ( rgb AS DWORD ) AS BYTE 
> RETURN System.Drawing.ColorTranslator.FromWin32( (INT) rgb):G		
> 
> FUNCTION GetBValue ( rgb AS DWORD ) AS BYTE 
> RETURN System.Drawing.ColorTranslator.FromWin32( (INT) rgb):B

That would work, but there is no reference to System.Drawing in XSharp.RT.
We might as well use the code from Win32APILibrary inside XSharp.RT.
I will then keep the functions inside Win32APILibrary and redirect them and return 
XSharp.RT.Functions.GetRValue(..) from these functions, so the definition is in one location only.

**Comment by cpyrgas** [comment]
Guys, won't that produce now compiler warnings about ambiguous functions, since they will be defined in two runtime dlls?

**Comment by Karl1155** [comment]
Chris,

If that happens, wouldn't it be an option to just move the unchanged code to XSharp.RT? ?

```
FUNCTION GetRValue(rgb AS DWORD) AS BYTE
	LOCAL val AS BYTE

	val:=BYTE(_CAST,rgb)
	RETURN val

FUNCTION GetGValue(rgb AS DWORD) AS BYTE
	LOCAL val AS WORD
	LOCAL retval AS BYTE

	val := (WORD(_CAST,rgb))>>8
	retval := BYTE(_CAST,val)
	RETURN retval

FUNCTION GetBValue(rgb AS DWORD) AS BYTE
	LOCAL val AS DWORD
	LOCAL retval AS BYTE

	val := rgb>>16
	retval := BYTE(_CAST,val)
	RETURN retval
```

**Comment by RobertvanderHulst** [comment]
No, there are rules in the compiler that take care of this.

**Comment by cpyrgas** [comment]
@Karl1155 That would break existing compiled libraries (3rd party and not)

Robert, ok, was suspecting this. Will test to make sure and will report back.

**Comment by cpyrgas** [comment]
Confirmed done
