### ISSUE TITLE
GetColor() - Foxpro Enhancement

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#973]
attached is a XIDE viaef (foxpro dialect) which implements the GetColor() func
[VFPColorDialog.zip](https://github.com/X-Sharp/XSharpPublic/files/8127536/VFPColorDialog.zip)

At first, some notes on how the code works.

- Foxpro stores the custom colors in the registry key "HKEY_CURRENT_USER\Software\Microsoft\VisualFoxPro\9.0\ChooseColor"
If the key does not exist, it will be created automatically.

The code uses two arrays:

- the int[]{16} array holds the colorrefs of the sixteen user defined colors. This array is used to set the colorefs via the oDlg:CustomColors property

- the byte[]{64} array is required to read the colors from, or write the colors to the registry. 

The structure of this array looks like:

1. byte  R value of the first colorref
2. byte  G Value of the first colorref
3. byte  B Value of the first colorref
4. byte  0
5. byte  R value of the second colorref
6. byte  G Value of the second colorref
7. byte  B Value of the second colorref
8. byte  0

etc.

if you look at the code you´ll notice that the registry key is closed before the dialog is shown. if the dialog is closed with [ok] the key is opened and closed again. What is the best practice: To do it this way, or leave the registry open until the dialog is closed ?

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
I think that your approach (to keep the key open as short as possible) is the safest.
I made some small modifications to the code:
- ReadColors() and __WriteColors() are now local functions
- ReadColors() returns an INT[]
- Handled the (unlikely) case where the registry contains the key ChooseColor but no byte array
- Length of int[] is derived from length of byte[] and vice versa to make sure these 2 match.

**Comment by cpyrgas** [comment]
Confirmed done
