### ISSUE TITLE
Brace completion with properties

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#974]
If you accept a property with "Enter", then brackets are added at the end.
![image](https://user-images.githubusercontent.com/20905638/155474487-0bdb4020-480c-48ef-a940-601be0827645.png)
![image](https://user-images.githubusercontent.com/20905638/155474494-8d61aeba-427d-444d-bc78-ab28c28793ea.png)

What is the difference between:
General -> Automatic brace completion 
Intellisense - > Enable Brace Completion 

It seems that I have to turn both on for it to work

**Comment by RobertvanderHulst** [comment]
Hand Joerg,
Thanks for reporting this. I noticed this myself and have fixed it for the next build

**Comment by cpyrgas** [comment]
Confirmed fixed
