### ISSUE TITLE
Incorrect info tooltips on keywords

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#979]
In the following code, when hovering on any keyword inside the method code produces a tooltip "PUBLIC CLASS TestClass". When the same code is put inside a funtion (instead of a class method), then it correctly reports "KEYWORD xxx"

```
CLASS TestClass
METHOD Test()
LOCAL loc AS System.Int32
WAIT
IF .T.
ELSE
ENDIF
RETURN
END CLASS

```

**Comment by cpyrgas** [comment]
Almost completely fixed, except for the case with ".T.". When hovering over it, this incorrect tooltip is being shown:

![TRUE_hover](https://user-images.githubusercontent.com/14542129/181758547-baa880d5-ac14-4c1a-a1a3-1fceecd8e72c.png)

**Comment by RobertvanderHulst** [comment]
Well, strictly speaking .T. is not a keyword but a boolean literal. For all literals the editor shows their type. It does so for date literals, string literals, number literals etc.
What did you expect to see ?

**Comment by cpyrgas** [comment]
Oops, sorry, this is absolutely fine actually, I did not read well enough the tooltip text. Confirmed fixed!
