### ISSUE TITLE
Implicit cast does not give an error when when calling a method with wrong class

### ISSUE THREAD

**Issue by hpetriffer** [X-Sharp/XSharpPublic#984]
Similar to Issue #961 (Version X#2.11), calling a typed method does not give a runtime error, when calling a method with an object that does not contain a compatible type.
Sometimes you can get later strange crashes or runtime errors.

The following code ends with an crash. There is only an error message in the event log:
`Description: The process was terminated due to an internal error in the .NET Runtime at IP 745F4382 (74540000) with exit code 80131506.
`
So it is really hard to find the error in the code.

```c#
function Start() as void strict
    TestClass{}.Test()
	Console.ReadLine()
    return

public class TestClass
    public method Test() as void strict
	local x := Today() as object
        self:TestString(x) // gives a FatalExecutionEngineError
	self:TestString((string)x) // gives InvalidCastException
        
        return
		
    public method TestString(c as string) as void
	c:Replace("X","y")
	return

end class
```

A solution would be if the compiler generates for instances of usual and objects (if the typed parameter are not usual or objects) an cast.
e.g.
```c#
self:TestString((string)x)
```

**Comment by RobertvanderHulst** [comment]
HansJoerg,
I will add the cast to the code

**Comment by cpyrgas** [comment]
Confirmed fixed
