### ISSUE TITLE
Warning, not error: incorrect confuse a method with a field or memvar. 

### ISSUE THREAD

**Issue by jpmoschi** [X-Sharp/XSharpPublic#988]
When i compile a project,  i can see many warning like this in Error List window. It is not really an error  
You can see an example of this in the test project sent as part of the issue #985 

_Warning	XS9073	Variable 'XXXX' has not been declared. Assuming this is a FIELD or a MEMVAR._	
But XXXX is a method declared in any context: private inside a class or as global procedure, XXXX is well called in the form xxxx(par1) or xxxx(). 

I am testing in 2.11 revision. 
Best regards 
Juan

**Comment by RobertvanderHulst** [comment]
This warning is coming from the /fox2 compiler option.
An expression like 
xxx(par1) could be:
- function or method call to function with name "xxx"
- array access with parentheses for public / private array with name "xxx"

However, in the case of code that is not an assignment and not an rvalue of an expression (right hand side of an expression) then this will be never an array access. I will change the compiler to suppress this message for the 2.12 build

**Comment by cpyrgas** [comment]
Robert, I prepared a repro sample to explain the problem, but you beat me to it. I'm anyway posting it, to better document the problem:

In the following code compiled with /vo2+, if /undeclared- is disabled, then it reports two errors on the 2 lines calling the function with argeument(s):
error XS0103: The name 'TestSomething' does not exist in the current context

When /declared+ is enabled, then it reports 2 warnings instead:
warning XS9073: Variable 'TestSomething' has not been declared. Assuming this is a FIELD or a MEMVAR.

At runtime, it does work as expected, but that requires /undeclared+ to be enabled

```
// /fox2+
FUNCTION TestSomething(o1,o2)
? o1,o2
RETURN 123

FUNCTION Start() AS VOID
TestSomething()
TestSomething(1)   // error XS0103 with /undeclared- disabled, warning 9073 otherwise
TestSomething(1,2) // error XS0103 with /undeclared- disabled, warning 9073 otherwise
```

**Comment by cpyrgas** [comment]
There's also the problem of

retValue := CallAfunction(1,2)

**Comment by cpyrgas** [comment]
And there's an additional problem with a class method:

```
// /fox2+ /undeclared+
FUNCTION Start() AS VOID
TestClass{}

CLASS TestClass
CONSTRUCTOR()
Test(1,2) // runtime exception, Variable 'Test' does not exist
METHOD Test(a,b)
? a,b
END CLASS
```

This produces a runtime error, that "Variable 'Test' does not exist".

**Comment by RobertvanderHulst** [comment]
> There's also the problem of
> 
> retValue := CallAfunction(1,2)
> 
> which is an r-value...guess nothing can be done about this at compile time

This will most likely have to generate a warning. Or I need to disable the 'undefined' warnings for everything that can also be a function call.

**Comment by RobertvanderHulst** [comment]
> 

I will have a look at this and will fit it when needed.

**Comment by jpmoschi** [comment]
Hi Robert, when do you think you will have time to fix the error expressed by cpyrgas? XSharp.RT confuses method with property and therefore does not recognize any method and this blocks me completely, I can't move forward. I have 3 options:
0: Wait as long as you need, how long?
1: Go back to the previous version of Xsharp, I don't like it
2: Or try to fix the bug myself and bring it to your attention. In case you choose this option, it would be good if you give me some clue because my intention is to solve it as indicated in the comment that I made before. This cannot be resolved at compile time unless you restrict the part that calls the method to be strongly typed (as an Xsharp restriction even though FoxPro allows it)

**Comment by jpmoschi** [comment]
I keep thinking...
An easy solution by defining rules might be to allow using [] for arrays and collections and () for functions and methods. It's easy for Xsharp.RT and MacroCompiler and since VFP supports both ways, FoxPro developers could easily prepare the code.
 Some examples:

> myArray[x,y]
> myCollection[item].myPropertyArray[x]
> myCollection[x].myMethod(args in/out/ref)
> myVar.myMethod(args in/out/ref)
> myVar.myFunction(args )

**Comment by jpmoschi** [comment]
Thanks for the adjustment.
How should I proceed to test this setting before the next version is released? 
Is there any place to take binaries directly?
I should try to follow the steps indicated in XSharpDev/README. Md?

**Comment by cpyrgas** [comment]
All cases confirmed fixed!
