### ISSUE TITLE
Failed to emit module with iif() statement

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#989]
The following causes an error XS7038: Failed to emit module for all iif() lines in the FoxPro dialect.
The same error happens also in the VO dialect, for the last line which uses NULL

The state of /vo10 - compatible iif() behavior does not seem to have an affect on the issue

```
FUNCTION Start() AS VOID
LOCAL u
u := IIF(.t., 123, .NULL.)
u := IIF(.t., {}, .NULL.)
u := IIF(.t., 456, NULL)

```

**Comment by cpyrgas** [comment]
Now the failed mode is gone, instead reports: error XS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'int' and '<null>'

When /vo10+ (compatible iif() behavior) is enabled, shouldn't it compile without errors, at least in the VO dialect?

```
// /vo10+
FUNCTION Start() AS VOID
LOCAL u
u := IIF(.t., {}, NULL) // OK
u := IIF(.t., NULL, {}) // OK
u := IIF(.t., 456, NULL)  // error XS0173: Type of conditional expression cannot be determined because there is no implicit conversion between 'int' and '<null>'
u := IIF(.t., NULL , 456) // error XS0173
u := IIF(.t., 456, NULL_OBJECT)  // error XS0173
u := IIF(.t., NULL_OBJECT , 456) // error XS0173

```

**Comment by RobertvanderHulst** [comment]
Yes, this should compile. The error message is temporary

**Comment by cpyrgas** [comment]
Original problem fixed, but there's a problem in core dialect now, following reports several errors XS0029: Cannot implicitly convert type 'object' to 'string'
When enabling /vo10+, even more (same) errors are being reported.


```
FUNCTION Start() AS VOID
LOCAL c AS STRING
c := iif(FALSE, "", NULL)  // error XS0029
c := iif(FALSE, NULL, NULL)// error XS0029 (twice)
c := iif(FALSE, NULL, "")  // error XS0029

LOCAL o AS OBJECT
o := iif(TRUE,SomeClass{},NULL)
o := iif(TRUE,NULL,SomeClass{})

LOCAL s AS SomeClass
s := iif(TRUE,SomeClass{},NULL)
s := iif(TRUE,NULL,SomeClass{})

CLASS SomeClass
	PROPERTY MyProp1 AS SomeClass GET iif(SELF==NULL,SELF,NULL)
	PROPERTY MyProp2 AS SomeClass GET iif(SELF==NULL,NULL,SELF)
END CLASS
```

**Comment by cpyrgas** [comment]
Original problem fixed, but now same code produces a "failed to emit module" error when /vo10 is disabled, I have adjusted C840 for that. Guess in this case there should be a compiler error that the iif() arguments are incompatible? If yes, I will split the test into two separate ones, so that one of them must pass and the other should report errors.

**Comment by RobertvanderHulst** [comment]
I have fixed this now. The first half of C840 compiles without problems. The second half reports the error 
**Type of IIF expression cannot be determined because there is no implicit conversion between 'byte' and 'System.DBNull'**
I suggest you split the test into 2 parts: one that should compile and one that should fail.
See https://github.com/X-Sharp/XSharpDev/commit/f5220212bd4ed6b1c9f0c409010557b44b48bd4f

**Comment by cpyrgas** [comment]
Confirmed fixed
