### ISSUE TITLE
undeclared var causes an "cannot assign" error - 2.11.0.1

### ISSUE THREAD

**Issue by Karl1155** [X-Sharp/XSharpPublic#991]
the choosen dialect is Foxpro and the /memvar+ and /undeclared+ settings are used.  All works as expected when you run this code:

```
FUNCTION Start( ) AS VOID 
PRIVATE xxxx

xxxx = 12 

xxxx(24)

RETURN    

FUNCTION xxxx( x ) 
	
	? x
	
	RETURN 
```

now disable the "PRIVATE xxxx" line and you should see the error:

error XS9046: Cannot assign to 'xxxx' because it is a 'method'	

Karl-Heinz

**Comment by RobertvanderHulst** [comment]
Karl-Heinz,
This will be difficult to fix I think. I'll try it anyways.
