### ISSUE TITLE
VS silently fails to start project with no error message, when using an incorrect working directory

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#996]
Attached solution has two projects in X# and c#, both with a non existing directory set for the option project options\Debug\Working Directory. When trying to start (Debug or Run) the X# project, it silently fails with no error message and the user is not aware of what the problem is. For the c# project, a helpful error message is shown:

```
---------------------------
Microsoft Visual Studio
---------------------------
The working directory does not exist: 'L:\DoesNotExist'.
---------------------------
OK   
---------------------------
```

**Comment by RobertvanderHulst** [comment]
Did you forget the attachment ?

**Comment by cpyrgas** [comment]
Yeap :)

[ConsoleApplication18.zip](https://github.com/X-Sharp/XSharpPublic/files/8304119/ConsoleApplication18.zip)

**Comment by cpyrgas** [comment]
This is being trapped now and a dialog is shown, but that dialog has both an OK and Cancel buttons, which is a little confusing, as both seem to do the same thing:

![VS_working_directory](https://user-images.githubusercontent.com/14542129/165726452-8fab9899-864f-4f4d-88e0-9215daf104e0.png)

I guess this should only contain an "OK" button. Starting the c# project does indeed show a similar dialog only with OK.

**Comment by RobertvanderHulst** [comment]
The error message was coming from the VS COmmunity Toolkits function MessageBox.ShowError(). I have adjusted this method and sent a pull request. This has been integrated and is now included in the X# project system.

**Comment by cpyrgas** [comment]
Confirmed fixed
