### ISSUE TITLE
Intellisense problem with DATATYPE(<expression>) conversion expressions

### ISSUE THREAD

**Issue by cpyrgas** [X-Sharp/XSharpPublic#997]
See code below:

```
FUNCTION Start() AS VOID STRICT
	LOCAL dw AS DWORD
	n := DWORD( MyFunc(1) ) // no quickinfo, tooltip params or Goto Definition on MyFunc
	? STRING( Str(1) ) // same problem inside the STRING( ) expression

FUNCTION MyFunc(a AS INT) AS INT
RETURN 123
```

**Comment by Serggio** [comment]
But the syntax is ```(DATATYPE)<expression>```

**Comment by RobertvanderHulst** [comment]
> But the syntax is `(DATATYPE)<expression>`

That is the 'new' DotNet expression. In VO we did not have that syntax. There the syntax 
`DWORD(something)`
means:
- when something is a pointer, then treat something as DWORD pointer and get the first value 
- when something is not a pointer then convert/cast the value to a DWORD

**Comment by cpyrgas** [comment]
Isn't it always a conversion for non-pointers in VO (and never a cast)? Because for casting VO uses the different syntax

DWORD(_CAST, something)

**Comment by RobertvanderHulst** [comment]
> Isn't it always a conversion for non-pointers in VO (and never a cast)? Because for casting VO uses the different syntax
> 
> DWORD(_CAST, something)

You're probably right. I would have to check.

**Comment by cpyrgas** [comment]
Confirmed fixed
