### ISSUE TITLE
MacroCompiler - Add way to exclude Assemblies

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#998]
Currently, the macro compiler creates a cache of typename - typesymbol pairs. It does this the first time the macro compiler is loaded and it also does this when new assemblies are loaded.

Add a static configuration or callback to exclude selected assemblies from being cached.

This will help reduce the memory consumption of the MacroCompiler, when third party libraries (like the DevExpress Winforms library) are used.

**Comment by cpyrgas** [comment]
Confirmed done
