### ISSUE TITLE
Add settings to the .editorconfig file to set the settings about indentation

### ISSUE THREAD

**Issue by VolkmarR** [X-Sharp/XSharpPublic#999]
Currently, the editorconfig [(according to this page)](https://www.xsharp.eu/help/_editorconfig-files.html) doesn't allow to setting options for indentation. Can this be added?

![image](https://user-images.githubusercontent.com/9860916/159529122-851d0478-2fc8-4957-8749-23dc713c79d9.png)

**Comment by RobertvanderHulst** [comment]
Yes, of course.

**Comment by RobertvanderHulst** [comment]
This has been added to the VS integration. We have added the following sessings:
- indent_entity_content (true or false)
- indent_block_content (true or false)
- indent_case_content (true or false)
- indent_case_label (true or false)
- indent_continued_lines (true or false)

**Comment by RobertvanderHulst** [comment]
This was also planned in #430
